import { Surah } from "../types/islam.js";

export const abasa: Surah = {
  name: "'Abasa",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "He frowned and turned away (1)",
      transliteration: "ʿabasa watawallā ",
      verse: 5759,
      juz: 30,
      surah: 80,
    },
    {
      number: 2,
      image: "",
      text: "Because came to him the blind man (2)",
      transliteration: "an jāahu l-aʿmā ",
      verse: 5760,
      juz: 30,
      surah: 80,
    },
    {
      number: 3,
      image: "",
      text: "But what would make you know that he might purify himself (3)",
      transliteration: "wamā yud'rīka laʿallahu yazzakkā ",
      verse: 5761,
      juz: 30,
      surah: 80,
    },
    {
      number: 4,
      image: "",
      text: "Or be reminded so would benefit him the reminder (4)",
      transliteration: "aw yadhakkaru fatanfaʿahu l-dhik'rā ",
      verse: 5762,
      juz: 30,
      surah: 80,
    },
    {
      number: 5,
      image: "",
      text: "As for (him) who considers himself free from need (5)",
      transliteration: "ammā mani is'taghnā ",
      verse: 5763,
      juz: 30,
      surah: 80,
    },
    {
      number: 6,
      image: "",
      text: "So you to him give attention (6)",
      transliteration: "fa-anta lahu taṣaddā ",
      verse: 5764,
      juz: 30,
      surah: 80,
    },
    {
      number: 7,
      image: "",
      text: "And not upon you that not he purifies himself (7)",
      transliteration: "wamā ʿalayka allā yazzakkā ",
      verse: 5765,
      juz: 30,
      surah: 80,
    },
    {
      number: 8,
      image: "",
      text: "But as for (he) who came to you striving (8)",
      transliteration: "wa-ammā man jāaka yasʿā ",
      verse: 5766,
      juz: 30,
      surah: 80,
    },
    {
      number: 9,
      image: "",
      text: "While he fears (9)",
      transliteration: "wahuwa yakhshā ",
      verse: 5767,
      juz: 30,
      surah: 80,
    },
    {
      number: 10,
      image: "",
      text: "But you from him (are) distracted (10)",
      transliteration: "fa-anta ʿanhu talahhā ",
      verse: 5768,
      juz: 30,
      surah: 80,
    },
    {
      number: 11,
      image: "",
      text: "Nay Indeed, it (is) a reminder (11)",
      transliteration: "kallā innahā tadhkiratun ",
      verse: 5769,
      juz: 30,
      surah: 80,
    },
    {
      number: 12,
      image: "",
      text: "So whosoever wills may remember it (12)",
      transliteration: "faman shāa dhakarahu ",
      verse: 5770,
      juz: 30,
      surah: 80,
    },
    {
      number: 13,
      image: "",
      text: "In sheets honored (13)",
      transliteration: "fī ṣuḥufin mukarramatin ",
      verse: 5771,
      juz: 30,
      surah: 80,
    },
    {
      number: 14,
      image: "",
      text: "Exalted purified (14)",
      transliteration: "marfūʿatin muṭahharatin ",
      verse: 5772,
      juz: 30,
      surah: 80,
    },
    {
      number: 15,
      image: "",
      text: "In (the) hands (of) scribes (15)",
      transliteration: "bi-aydī safaratin ",
      verse: 5773,
      juz: 30,
      surah: 80,
    },
    {
      number: 16,
      image: "",
      text: "Noble dutiful (16)",
      transliteration: "kirāmin bararatin ",
      verse: 5774,
      juz: 30,
      surah: 80,
    },
    {
      number: 17,
      image: "",
      text: "Is destroyed [the] man how ungrateful is he (17)",
      transliteration: "qutila l-insānu mā akfarahu ",
      verse: 5775,
      juz: 30,
      surah: 80,
    },
    {
      number: 18,
      image: "",
      text: "From what thing He created him (18)",
      transliteration: "min ayyi shayin khalaqahu ",
      verse: 5776,
      juz: 30,
      surah: 80,
    },
    {
      number: 19,
      image: "",
      text: "From a semen-drop He created him then He proportioned him (19)",
      transliteration: "min nuṭ'fatin khalaqahu faqaddarahu ",
      verse: 5777,
      juz: 30,
      surah: 80,
    },
    {
      number: 20,
      image: "",
      text: "Then the way He made easy for him (20)",
      transliteration: "thumma l-sabīla yassarahu ",
      verse: 5778,
      juz: 30,
      surah: 80,
    },
    {
      number: 21,
      image: "",
      text: "Then He causes him to die and provides a grave for him (21)",
      transliteration: "thumma amātahu fa-aqbarahu ",
      verse: 5779,
      juz: 30,
      surah: 80,
    },
    {
      number: 22,
      image: "",
      text: "Then when He wills He will resurrect him (22)",
      transliteration: "thumma idhā shāa ansharahu ",
      verse: 5780,
      juz: 30,
      surah: 80,
    },
    {
      number: 23,
      image: "",
      text: "Nay Not he has accomplished what He commanded him (23)",
      transliteration: "kallā lammā yaqḍi mā amarahu ",
      verse: 5781,
      juz: 30,
      surah: 80,
    },
    {
      number: 24,
      image: "",
      text: "Then let look the man at his food (24)",
      transliteration: "falyanẓuri l-insānu ilā ṭaʿāmihi ",
      verse: 5782,
      juz: 30,
      surah: 80,
    },
    {
      number: 25,
      image: "",
      text: "That [We] [We] poured the water (in) abundance (25)",
      transliteration: "annā ṣababnā l-māa ṣabban ",
      verse: 5783,
      juz: 30,
      surah: 80,
    },
    {
      number: 26,
      image: "",
      text: "Then We cleaved the earth splitting (26)",
      transliteration: "thumma shaqaqnā l-arḍa shaqqan ",
      verse: 5784,
      juz: 30,
      surah: 80,
    },
    {
      number: 27,
      image: "",
      text: "Then We caused to grow therein grain (27)",
      transliteration: "fa-anbatnā fīhā ḥabban ",
      verse: 5785,
      juz: 30,
      surah: 80,
    },
    {
      number: 28,
      image: "",
      text: "And grapes and green fodder (28)",
      transliteration: "waʿinaban waqaḍban ",
      verse: 5786,
      juz: 30,
      surah: 80,
    },
    {
      number: 29,
      image: "",
      text: "And olive and date-palms (29)",
      transliteration: "wazaytūnan wanakhlan ",
      verse: 5787,
      juz: 30,
      surah: 80,
    },
    {
      number: 30,
      image: "",
      text: "And gardens (of) thick foliage (30)",
      transliteration: "waḥadāiqa ghul'ban ",
      verse: 5788,
      juz: 30,
      surah: 80,
    },
    {
      number: 31,
      image: "",
      text: "And fruits and grass (31)",
      transliteration: "wafākihatan wa-abban ",
      verse: 5789,
      juz: 30,
      surah: 80,
    },
    {
      number: 32,
      image: "",
      text: "(As) a provision for you and for your cattle (32)",
      transliteration: "matāʿan lakum wali-anʿāmikum ",
      verse: 5790,
      juz: 30,
      surah: 80,
    },
    {
      number: 33,
      image: "",
      text: "But when comes the Deafening Blast (33)",
      transliteration: "fa-idhā jāati l-ṣākhatu ",
      verse: 5791,
      juz: 30,
      surah: 80,
    },
    {
      number: 34,
      image: "",
      text: "(The) Day will flee a man from his brother (34)",
      transliteration: "yawma yafirru l-maru min akhīhi ",
      verse: 5792,
      juz: 30,
      surah: 80,
    },
    {
      number: 35,
      image: "",
      text: "And his mother and his father (35)",
      transliteration: "wa-ummihi wa-abīhi ",
      verse: 5793,
      juz: 30,
      surah: 80,
    },
    {
      number: 36,
      image: "",
      text: "And his wife and his children (36)",
      transliteration: "waṣāḥibatihi wabanīhi ",
      verse: 5794,
      juz: 30,
      surah: 80,
    },
    {
      number: 37,
      image: "",
      text: "For every man among them that Day (will be) a matter occupying him (37)",
      transliteration: "likulli im'ri-in min'hum yawma-idhin shanun yugh'nīhi ",
      verse: 5795,
      juz: 30,
      surah: 80,
    },
    {
      number: 38,
      image: "",
      text: "Faces that Day (will be) bright (38)",
      transliteration: "wujūhun yawma-idhin mus'firatun ",
      verse: 5796,
      juz: 30,
      surah: 80,
    },
    {
      number: 39,
      image: "",
      text: "Laughing rejoicing at good news (39)",
      transliteration: "ḍāḥikatun mus'tabshiratun ",
      verse: 5797,
      juz: 30,
      surah: 80,
    },
    {
      number: 40,
      image: "",
      text: "And faces that Day upon them (will be) dust (40)",
      transliteration: "wawujūhun yawma-idhin ʿalayhā ghabaratun ",
      verse: 5798,
      juz: 30,
      surah: 80,
    },
    {
      number: 41,
      image: "",
      text: "Will cover them darkness (41)",
      transliteration: "tarhaquhā qataratun ",
      verse: 5799,
      juz: 30,
      surah: 80,
    },
    {
      number: 42,
      image: "",
      text: "Those [they] (are) the disbelievers the wicked ones (42)",
      transliteration: "ulāika humu l-kafaratu l-fajaratu ",
      verse: 5800,
      juz: 30,
      surah: 80,
    },
  ],
};
