import { Surah } from "../types/islam.ts";

export const abasa: Surah = {
  name: "'Abasa",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "The Prophet frowned and turned away",
      verse: 5628,
    },
    {
      number: 2,
      image: "",
      text: "Because there came to him the blind man, [interrupting].",
      verse: 5629,
    },
    {
      number: 3,
      image: "",
      text:
        "But what would make you perceive, [O Muhammad], that perhaps he might be purified",
      verse: 5630,
    },
    {
      number: 4,
      image: "",
      text: "Or be reminded and the remembrance would benefit him?",
      verse: 5631,
    },
    {
      number: 5,
      image: "",
      text: "As for he who thinks himself without need,",
      verse: 5632,
    },
    { number: 6, image: "", text: "To him you give attention.", verse: 5633 },
    {
      number: 7,
      image: "",
      text: "And not upon you [is any blame] if he will not be purified.",
      verse: 5634,
    },
    {
      number: 8,
      image: "",
      text: "But as for he who came to you striving [for knowledge]",
      verse: 5635,
    },
    { number: 9, image: "", text: "While he fears [ Allah ],", verse: 5636 },
    {
      number: 10,
      image: "",
      text: "From him you are distracted.",
      verse: 5637,
    },
    {
      number: 11,
      image: "",
      text: "No! Indeed, these verses are a reminder;",
      verse: 5638,
    },
    {
      number: 12,
      image: "",
      text: "So whoever wills may remember it.",
      verse: 5639,
    },
    {
      number: 13,
      image: "",
      text: "[It is recorded] in honored sheets,",
      verse: 5640,
    },
    { number: 14, image: "", text: "Exalted and purified,", verse: 5641 },
    {
      number: 15,
      image: "",
      text: "[Carried] by the hands of messenger-angels,",
      verse: 5642,
    },
    { number: 16, image: "", text: "Noble and dutiful.", verse: 5643 },
    {
      number: 17,
      image: "",
      text: "Cursed is man; how disbelieving is he.",
      verse: 5644,
    },
    {
      number: 18,
      image: "",
      text: "From what substance did He create him?",
      verse: 5645,
    },
    {
      number: 19,
      image: "",
      text: "From a sperm-drop He created him and destined for him;",
      verse: 5646,
    },
    {
      number: 20,
      image: "",
      text: "Then He eased the way for him;",
      verse: 5647,
    },
    {
      number: 21,
      image: "",
      text: "Then He causes his death and provides a grave for him.",
      verse: 5648,
    },
    {
      number: 22,
      image: "",
      text: "Then when He wills, He will resurrect him.",
      verse: 5649,
    },
    {
      number: 23,
      image: "",
      text: "No! Man has not yet accomplished what He commanded him.",
      verse: 5650,
    },
    {
      number: 24,
      image: "",
      text: "Then let mankind look at his food -",
      verse: 5651,
    },
    {
      number: 25,
      image: "",
      text: "How We poured down water in torrents,",
      verse: 5652,
    },
    {
      number: 26,
      image: "",
      text: "Then We broke open the earth, splitting [it with sprouts],",
      verse: 5653,
    },
    {
      number: 27,
      image: "",
      text: "And caused to grow within it grain",
      verse: 5654,
    },
    { number: 28, image: "", text: "And grapes and herbage", verse: 5655 },
    { number: 29, image: "", text: "And olive and palm trees", verse: 5656 },
    {
      number: 30,
      image: "",
      text: "And gardens of dense shrubbery",
      verse: 5657,
    },
    { number: 31, image: "", text: "And fruit and grass -", verse: 5658 },
    {
      number: 32,
      image: "",
      text: "[As] enjoyment for you and your grazing livestock.",
      verse: 5659,
    },
    {
      number: 33,
      image: "",
      text: "But when there comes the Deafening Blast",
      verse: 5660,
    },
    {
      number: 34,
      image: "",
      text: "On the Day a man will flee from his brother",
      verse: 5661,
    },
    {
      number: 35,
      image: "",
      text: "And his mother and his father",
      verse: 5662,
    },
    {
      number: 36,
      image: "",
      text: "And his wife and his children,",
      verse: 5663,
    },
    {
      number: 37,
      image: "",
      text: "For every man, that Day, will be a matter adequate for him.",
      verse: 5664,
    },
    {
      number: 38,
      image: "",
      text: "[Some] faces, that Day, will be bright -",
      verse: 5665,
    },
    {
      number: 39,
      image: "",
      text: "Laughing, rejoicing at good news.",
      verse: 5666,
    },
    {
      number: 40,
      image: "",
      text: "And [other] faces, that Day, will have upon them dust.",
      verse: 5667,
    },
    { number: 41, image: "", text: "Blackness will cover them.", verse: 5668 },
    {
      number: 42,
      image: "",
      text: "Those are the disbelievers, the wicked ones.",
      verse: 5669,
    },
  ],
};
