import { Surah } from "../types/islam.js";

export const adiyat: Surah = {
  name: "Al-'Adiyat",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "By the racers panting (1)",
      transliteration: "wal-ʿādiyāti ḍabḥan ",
      verse: 6147,
      juz: 30,
      surah: 100,
    },
    {
      number: 2,
      image: "",
      text: "And the producers of sparks striking (2)",
      transliteration: "fal-mūriyāti qadḥan ",
      verse: 6148,
      juz: 30,
      surah: 100,
    },
    {
      number: 3,
      image: "",
      text: "And the chargers (at) dawn (3)",
      transliteration: "fal-mughīrāti ṣub'ḥan ",
      verse: 6149,
      juz: 30,
      surah: 100,
    },
    {
      number: 4,
      image: "",
      text: "Then raise thereby dust (4)",
      transliteration: "fa-atharna bihi naqʿan ",
      verse: 6150,
      juz: 30,
      surah: 100,
    },
    {
      number: 5,
      image: "",
      text: "Then penetrate (in the) center thereby collectively (5)",
      transliteration: "fawasaṭna bihi jamʿan ",
      verse: 6151,
      juz: 30,
      surah: 100,
    },
    {
      number: 6,
      image: "",
      text: "Indeed mankind to his Lord (is) surely ungrateful (6)",
      transliteration: "inna l-insāna lirabbihi lakanūdun ",
      verse: 6152,
      juz: 30,
      surah: 100,
    },
    {
      number: 7,
      image: "",
      text: "And indeed, he on that surely (is) a witness (7)",
      transliteration: "wa-innahu ʿalā dhālika lashahīdun ",
      verse: 6153,
      juz: 30,
      surah: 100,
    },
    {
      number: 8,
      image: "",
      text: "And indeed he in (the) love (of) wealth (is) surely intense (8)",
      transliteration: "wa-innahu liḥubbi l-khayri lashadīdun ",
      verse: 6154,
      juz: 30,
      surah: 100,
    },
    {
      number: 9,
      image: "",
      text: "But does not he know when will be scattered what (is) in the graves (9)",
      transliteration: "afalā yaʿlamu idhā buʿ'thira mā fī l-qubūri ",
      verse: 6155,
      juz: 30,
      surah: 100,
    },
    {
      number: 10,
      image: "",
      text: "And is made apparent what (is) in the breasts (10)",
      transliteration: "waḥuṣṣila mā fī l-ṣudūri ",
      verse: 6156,
      juz: 30,
      surah: 100,
    },
    {
      number: 11,
      image: "",
      text: "Indeed their Lord about them that Day (is) surely All-Aware (11)",
      transliteration: "inna rabbahum bihim yawma-idhin lakhabīrun ",
      verse: 6157,
      juz: 30,
      surah: 100,
    },
  ],
};
