import { Surah } from "../types/islam.js";

export const ahzab: Surah = {
  name: "Al-Ahzab",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "O Prophet O Prophet Fear Allah and (do) not obey the disbelievers and the hypocrites Indeed Allah is All-Knower All-Wise (1)",
      transliteration:
        "yāayyuhā l-nabiyu ittaqi l-laha walā tuṭiʿi l-kāfirīna wal-munāfiqīna inna l-laha kāna ʿalīman ḥakīman ",
      verse: 3534,
      juz: 21,
      surah: 33,
    },
    {
      number: 2,
      image: "",
      text: "And follow what is inspired to you from your Lord Indeed Allah is of what you do All-Aware (2)",
      transliteration:
        "wa-ittabiʿ mā yūḥā ilayka min rabbika inna l-laha kāna bimā taʿmalūna khabīran ",
      verse: 3535,
      juz: 21,
      surah: 33,
    },
    {
      number: 3,
      image: "",
      text: "And put your trust in Allah And Allah is sufficient And Allah is sufficient (as) Disposer of affairs (3)",
      transliteration: "watawakkal ʿalā l-lahi wakafā bil-lahi wakīlan ",
      verse: 3536,
      juz: 21,
      surah: 33,
    },
    {
      number: 4,
      image: "",
      text: "Not Allah (has) made Allah (has) made for any man [of] two hearts in his interior And not He (has) made your wives whom you declare unlawful [of them] (as) your mothers And not He has made your adopted sons your sons That (is) your saying by your mouths but Allah says the truth and He guides (to) the Way (4)",
      transliteration:
        "mā jaʿala l-lahu lirajulin min qalbayni fī jawfihi wamā jaʿala azwājakumu allāī tuẓāhirūna min'hunna ummahātikum wamā jaʿala adʿiyāakum abnāakum dhālikum qawlukum bi-afwāhikum wal-lahu yaqūlu l-ḥaqa wahuwa yahdī l-sabīla ",
      verse: 3537,
      juz: 21,
      surah: 33,
    },
    {
      number: 5,
      image: "",
      text: "Call them by their fathers it (is) more just near Allah But if not you know their fathers  then (they are) your brothers in [the] religion and your friends But not is upon you any blame in what you made a mistake in it but what intended your hearts And Allah And Allah (is) Oft-Forgiving Most Merciful (5)",
      transliteration:
        "id'ʿūhum liābāihim huwa aqsaṭu ʿinda l-lahi fa-in lam taʿlamū ābāahum fa-ikh'wānukum fī l-dīni wamawālīkum walaysa ʿalaykum junāḥun fīmā akhṭatum bihi walākin mā taʿammadat qulūbukum wakāna l-lahu ghafūran raḥīman ",
      verse: 3538,
      juz: 21,
      surah: 33,
    },
    {
      number: 6,
      image: "",
      text: "The Prophet (is) closer to the believers than their own selves and his wives (are) their mothers And possessors (of) relationships some of them (are) closer to another in (the) Decree (of) Allah than the believers and the emigrants except that you do to your friends a kindness That is That is in the Book written (6)",
      transliteration:
        "al-nabiyu awlā bil-mu'minīna min anfusihim wa-azwājuhu ummahātuhum wa-ulū l-arḥāmi baʿḍuhum awlā bibaʿḍin fī kitābi l-lahi mina l-mu'minīna wal-muhājirīna illā an tafʿalū ilā awliyāikum maʿrūfan kāna dhālika fī l-kitābi masṭūran ",
      verse: 3539,
      juz: 21,
      surah: 33,
    },
    {
      number: 7,
      image: "",
      text: "And when We took from the Prophets their Covenant and from you and from Nuh and Ibrahim and Musa and Isa son (of) Maryam And We took from them a covenant strong (7)",
      transliteration:
        "wa-idh akhadhnā mina l-nabiyīna mīthāqahum waminka wamin nūḥin wa-ib'rāhīma wamūsā waʿīsā ib'ni maryama wa-akhadhnā min'hum mīthāqan ghalīẓan ",
      verse: 3540,
      juz: 21,
      surah: 33,
    },
    {
      number: 8,
      image: "",
      text: "That He may ask the truthful about their truth And He has prepared for the disbelievers a punishment painful (8)",
      transliteration:
        "liyasala l-ṣādiqīna ʿan ṣid'qihim wa-aʿadda lil'kāfirīna ʿadhāban alīman ",
      verse: 3541,
      juz: 21,
      surah: 33,
    },
    {
      number: 9,
      image: "",
      text: "O you who believe Remember (the) Favor (of) Allah upon you when came to you (the) hosts and We sent upon them a wind and hosts not you (could) see them And Allah is And Allah is of what you do All-Seer (9)",
      transliteration:
        "yāayyuhā alladhīna āmanū udh'kurū niʿ'mata l-lahi ʿalaykum idh jāatkum junūdun fa-arsalnā ʿalayhim rīḥan wajunūdan lam tarawhā wakāna l-lahu bimā taʿmalūna baṣīran ",
      verse: 3542,
      juz: 21,
      surah: 33,
    },
    {
      number: 10,
      image: "",
      text: "When they came upon you from above you and from below you and when grew wild the eyes and reached the hearts the throats and you assumed about Allah the assumptions (10)",
      transliteration:
        "idh jāūkum min fawqikum wamin asfala minkum wa-idh zāghati l-abṣāru wabalaghati l-qulūbu l-ḥanājira wataẓunnūna bil-lahi l-ẓunūnā ",
      verse: 3543,
      juz: 21,
      surah: 33,
    },
    {
      number: 11,
      image: "",
      text: "There  were tried the believers and shaken (with a) shake severe (11)",
      transliteration:
        "hunālika ub'tuliya l-mu'minūna wazul'zilū zil'zālan shadīdan ",
      verse: 3544,
      juz: 21,
      surah: 33,
    },
    {
      number: 12,
      image: "",
      text: "And when said the hypocrites and those in their hearts (was) a disease Not Allah promised us Allah promised us and His messenger except delusion (12)",
      transliteration:
        "wa-idh yaqūlu l-munāfiqūna wa-alladhīna fī qulūbihim maraḍun mā waʿadanā l-lahu warasūluhu illā ghurūran ",
      verse: 3545,
      juz: 21,
      surah: 33,
    },
    {
      number: 13,
      image: "",
      text: "And when said a party of them O People (of) Yathrib No stand for you so return And asked permission a group of them (from) the Prophet saying Indeed our houses (are) exposed and not they (were) exposed Not they wished but to flee (13)",
      transliteration:
        "wa-idh qālat ṭāifatun min'hum yāahla yathriba lā muqāma lakum fa-ir'jiʿū wayastadhinu farīqun min'humu l-nabiya yaqūlūna inna buyūtanā ʿawratun wamā hiya biʿawratin in yurīdūna illā firāran ",
      verse: 3546,
      juz: 21,
      surah: 33,
    },
    {
      number: 14,
      image: "",
      text: "And if had been entered upon them from all its sides then they had been asked the treachery they (would) have certainly done it and not they (would) have hesitated over it except a little (14)",
      transliteration:
        "walaw dukhilat ʿalayhim min aqṭārihā thumma su-ilū l-fit'nata laātawhā wamā talabbathū bihā illā yasīran ",
      verse: 3547,
      juz: 21,
      surah: 33,
    },
    {
      number: 15,
      image: "",
      text: "And certainly they had promised Allah before before not they would turn their backs And is (the) promise (to) Allah to be questioned (15)",
      transliteration:
        "walaqad kānū ʿāhadū l-laha min qablu lā yuwallūna l-adbāra wakāna ʿahdu l-lahi masūlan ",
      verse: 3548,
      juz: 21,
      surah: 33,
    },
    {
      number: 16,
      image: "",
      text: "Say Never will benefit you the fleeing if you flee from death or killing and then not you will be allowed to enjoy except a little (16)",
      transliteration:
        "qul lan yanfaʿakumu l-firāru in farartum mina l-mawti awi l-qatli wa-idhan lā tumattaʿūna illā qalīlan ",
      verse: 3549,
      juz: 21,
      surah: 33,
    },
    {
      number: 17,
      image: "",
      text: "Say Who (is) it that (is) it that (can) protect you from Allah If He intends for you any harm or He intends for you a mercy And not they will find for them besides besides Allah any protector and not any helper (17)",
      transliteration:
        "qul man dhā alladhī yaʿṣimukum mina l-lahi in arāda bikum sūan aw arāda bikum raḥmatan walā yajidūna lahum min dūni l-lahi waliyyan walā naṣīran ",
      verse: 3550,
      juz: 21,
      surah: 33,
    },
    {
      number: 18,
      image: "",
      text: "Verily Allah knows Allah knows those who hinder among you and those who say to their brothers Come to us and not they come (to) the battle except a few (18)",
      transliteration:
        "qad yaʿlamu l-lahu l-muʿawiqīna minkum wal-qāilīna li-ikh'wānihim halumma ilaynā walā yatūna l-basa illā qalīlan ",
      verse: 3551,
      juz: 21,
      surah: 33,
    },
    {
      number: 19,
      image: "",
      text: "Miserly towards you But when comes the fear you see them looking at you revolving their eyes like one who faints faints from [the] death But when departs the fear they smite you with tongues sharp miserly towards the good Those  not they have believed so Allah made worthless so Allah made worthless their deeds And is that for Allah easy (19)",
      transliteration:
        "ashiḥḥatan ʿalaykum fa-idhā jāa l-khawfu ra-aytahum yanẓurūna ilayka tadūru aʿyunuhum ka-alladhī yugh'shā ʿalayhi mina l-mawti fa-idhā dhahaba l-khawfu salaqūkum bi-alsinatin ḥidādin ashiḥḥatan ʿalā l-khayri ulāika lam yu'minū fa-aḥbaṭa l-lahu aʿmālahum wakāna dhālika ʿalā l-lahi yasīran ",
      verse: 3552,
      juz: 21,
      surah: 33,
    },
    {
      number: 20,
      image: "",
      text: "They think the confederates (have) not withdrawn And if (should) come the confederates they would wish if that they (were) living in (the) desert among the Bedouins asking about your news And if they were among you not they would fight except a little (20)",
      transliteration:
        "yaḥsabūna l-aḥzāba lam yadhhabū wa-in yati l-aḥzābu yawaddū law annahum bādūna fī l-aʿrābi yasalūna ʿan anbāikum walaw kānū fīkum mā qātalū illā qalīlan ",
      verse: 3553,
      juz: 21,
      surah: 33,
    },
    {
      number: 21,
      image: "",
      text: "Certainly is for you in (the) Messenger (of) Allah an excellent example an excellent example for (one) who has hope (in) Allah and the Day the Last and remembers Allah much (21)",
      transliteration:
        "laqad kāna lakum fī rasūli l-lahi us'watun ḥasanatun liman kāna yarjū l-laha wal-yawma l-ākhira wadhakara l-laha kathīran ",
      verse: 3554,
      juz: 21,
      surah: 33,
    },
    {
      number: 22,
      image: "",
      text: "And when saw the believers the confederates they said This (is) what Allah promised us Allah promised us and His Messenger and Allah spoke the truth and Allah spoke the truth and His Messenger And not it increased them except (in) faith and submission (22)",
      transliteration:
        "walammā raā l-mu'minūna l-aḥzāba qālū hādhā mā waʿadanā l-lahu warasūluhu waṣadaqa l-lahu warasūluhu wamā zādahum illā īmānan wataslīman ",
      verse: 3555,
      juz: 21,
      surah: 33,
    },
    {
      number: 23,
      image: "",
      text: "Among the believers (are) men (who) have been true (to) what they promised Allah they promised Allah [on it] And among them (is he) who has fulfilled his vow and among them (is he) who awaits And not they alter (by) any alteration  (23)",
      transliteration:
        "mina l-mu'minīna rijālun ṣadaqū mā ʿāhadū l-laha ʿalayhi famin'hum man qaḍā naḥbahu wamin'hum man yantaẓiru wamā baddalū tabdīlan ",
      verse: 3556,
      juz: 21,
      surah: 33,
    },
    {
      number: 24,
      image: "",
      text: "That Allah may reward That Allah may reward the truthful for their truth and punish the hypocrites if He wills or turn in mercy to them Indeed Allah is Oft-Forgiving Most Merciful (24)",
      transliteration:
        "liyajziya l-lahu l-ṣādiqīna biṣid'qihim wayuʿadhiba l-munāfiqīna in shāa aw yatūba ʿalayhim inna l-laha kāna ghafūran raḥīman ",
      verse: 3557,
      juz: 21,
      surah: 33,
    },
    {
      number: 25,
      image: "",
      text: "And Allah turned back And Allah turned back those who disbelieved in their rage not they obtained any good And sufficient is Allah (for) the believers (in) the battle and Allah is and Allah is All-Strong All-Mighty (25)",
      transliteration:
        "waradda l-lahu alladhīna kafarū bighayẓihim lam yanālū khayran wakafā l-lahu l-mu'minīna l-qitāla wakāna l-lahu qawiyyan ʿazīzan ",
      verse: 3558,
      juz: 21,
      surah: 33,
    },
    {
      number: 26,
      image: "",
      text: "And He brought down those who backed them among (the) People (of) the Scripture from their fortresses and cast into their hearts [the] terror a group you killed and you took captive a group (26)",
      transliteration:
        "wa-anzala alladhīna ẓāharūhum min ahli l-kitābi min ṣayāṣīhim waqadhafa fī qulūbihimu l-ruʿ'ba farīqan taqtulūna watasirūna farīqan ",
      verse: 3559,
      juz: 21,
      surah: 33,
    },
    {
      number: 27,
      image: "",
      text: "And He caused you to inherit their land and their houses and their properties and a land not you (had) trodden And Allah is And Allah is on every thing All-Powerful (27)",
      transliteration:
        "wa-awrathakum arḍahum wadiyārahum wa-amwālahum wa-arḍan lam taṭaūhā wakāna l-lahu ʿalā kulli shayin qadīran ",
      verse: 3560,
      juz: 21,
      surah: 33,
    },
    {
      number: 28,
      image: "",
      text: "O Prophet O Prophet Say to your wives If you desire the life (of) the world and its adornment then come I will provide for you and release you (with) a release good (28)",
      transliteration:
        "yāayyuhā l-nabiyu qul li-azwājika in kuntunna turid'na l-ḥayata l-dun'yā wazīnatahā fataʿālayna umattiʿ'kunna wa-usarriḥ'kunna sarāḥan jamīlan ",
      verse: 3561,
      juz: 21,
      surah: 33,
    },
    {
      number: 29,
      image: "",
      text: "But if you desire Allah and His Messenger and the Home (of) the Hereafter then indeed Allah has prepared for the good-doers among you a reward great (29)",
      transliteration:
        "wa-in kuntunna turid'na l-laha warasūlahu wal-dāra l-ākhirata fa-inna l-laha aʿadda lil'muḥ'sināti minkunna ajran ʿaẓīman ",
      verse: 3562,
      juz: 21,
      surah: 33,
    },
    {
      number: 30,
      image: "",
      text: "O wives (of) the Prophet Whoever commits from you immorality clear will be doubled for her the punishment two fold And that is And that is for Allah easy (30)",
      transliteration:
        "yānisāa l-nabiyi man yati minkunna bifāḥishatin mubayyinatin yuḍāʿaf lahā l-ʿadhābu ḍiʿ'fayni wakāna dhālika ʿalā l-lahi yasīran ",
      verse: 3563,
      juz: 21,
      surah: 33,
    },
    {
      number: 31,
      image: "",
      text: "And whoever is obedient among you to Allah and His Messenger and does righteousness We will give her her reward twice and We have prepared for her a provision noble (31)",
      transliteration:
        "waman yaqnut minkunna lillahi warasūlihi wataʿmal ṣāliḥan nu'tihā ajrahā marratayni wa-aʿtadnā lahā riz'qan karīman ",
      verse: 3564,
      juz: 22,
      surah: 33,
    },
    {
      number: 32,
      image: "",
      text: "O wives (of) the Prophet You are not like anyone among the women If you fear (Allah) then (do) not be soft in speech lest should be moved with desire he who in his heart (is) a disease but say a word appropriate (32)",
      transliteration:
        "yānisāa l-nabiyi lastunna ka-aḥadin mina l-nisāi ini ittaqaytunna falā takhḍaʿna bil-qawli fayaṭmaʿa alladhī fī qalbihi maraḍun waqul'na qawlan maʿrūfan ",
      verse: 3565,
      juz: 22,
      surah: 33,
    },
    {
      number: 33,
      image: "",
      text: "And stay in your houses and (do) not display yourselves (as was the) display (of the times of) ignorance the former And establish the prayer and give zakah and obey Allah and His Messenger Only Allah wishes Allah wishes to remove from you the impurity (O) People (of) the House And to purify you (with thorough) purification (33)",
      transliteration:
        "waqarna fī buyūtikunna walā tabarrajna tabarruja l-jāhiliyati l-ūlā wa-aqim'na l-ṣalata waātīna l-zakata wa-aṭiʿ'na l-laha warasūlahu innamā yurīdu l-lahu liyudh'hiba ʿankumu l-rij'sa ahla l-bayti wayuṭahhirakum taṭhīran ",
      verse: 3566,
      juz: 22,
      surah: 33,
    },
    {
      number: 34,
      image: "",
      text: "And remember what is recited in your houses of (the) Verses (of) Allah and the wisdom Indeed Allah is All-Subtle All-Aware (34)",
      transliteration:
        "wa-udh'kur'na mā yut'lā fī buyūtikunna min āyāti l-lahi wal-ḥik'mati inna l-laha kāna laṭīfan khabīran ",
      verse: 3567,
      juz: 22,
      surah: 33,
    },
    {
      number: 35,
      image: "",
      text: "Indeed the Muslim men and the Muslim women and the believing men and the believing women and the obedient men and the obedient women and the truthful men and the truthful women and the patient men and the patient women and the humble men and the humble women and the men who give charity and the women who give charity and the men who fast and the women who fast and the men who guard their chastity and the women who guard (it) and the men who remember Allah much and the women who remember Allah has prepared Allah has prepared for them forgiveness and a reward great (35)",
      transliteration:
        "inna l-mus'limīna wal-mus'limāti wal-mu'minīna wal-mu'mināti wal-qānitīna wal-qānitāti wal-ṣādiqīna wal-ṣādiqāti wal-ṣābirīna wal-ṣābirāti wal-khāshiʿīna wal-khāshiʿāti wal-mutaṣadiqīna wal-mutaṣadiqāti wal-ṣāimīna wal-ṣāimāti wal-ḥāfiẓīna furūjahum wal-ḥāfiẓāti wal-dhākirīna l-laha kathīran wal-dhākirāti aʿadda l-lahu lahum maghfiratan wa-ajran ʿaẓīman ",
      verse: 3568,
      juz: 22,
      surah: 33,
    },
    {
      number: 36,
      image: "",
      text: "And not (it) is for a believing man and not (for) a believing woman when Allah has decided Allah has decided and His Messenger a matter that (there) should be for them (any) choice about their affair And whoever disobeys Allah and His Messenger certainly he (has) strayed (into) error clear (36)",
      transliteration:
        "wamā kāna limu'minin walā mu'minatin idhā qaḍā l-lahu warasūluhu amran an yakūna lahumu l-khiyaratu min amrihim waman yaʿṣi l-laha warasūlahu faqad ḍalla ḍalālan mubīnan ",
      verse: 3569,
      juz: 22,
      surah: 33,
    },
    {
      number: 37,
      image: "",
      text: "And when you said to the one Allah bestowed favor Allah bestowed favor on him and you bestowed favor on him Keep to yourself your wife and fear Allah But you concealed within yourself what Allah (was to) disclose And you fear the people while Allah has more right that you (should) fear Him So when ended Zaid from her necessary (formalities) We married her to you so that not there be on the believers any discomfort concerning the wives (of) their adopted sons when they have ended from them necessary (formalities) And is (the) Command (of) Allah accomplished (37)",
      transliteration:
        "wa-idh taqūlu lilladhī anʿama l-lahu ʿalayhi wa-anʿamta ʿalayhi amsik ʿalayka zawjaka wa-ittaqi l-laha watukh'fī fī nafsika mā l-lahu mub'dīhi watakhshā l-nāsa wal-lahu aḥaqqu an takhshāhu falammā qaḍā zaydun min'hā waṭaran zawwajnākahā likay lā yakūna ʿalā l-mu'minīna ḥarajun fī azwāji adʿiyāihim idhā qaḍaw min'hunna waṭaran wakāna amru l-lahi mafʿūlan ",
      verse: 3570,
      juz: 22,
      surah: 33,
    },
    {
      number: 38,
      image: "",
      text: "Not (there can) be upon the Prophet any discomfort in what Allah has imposed Allah has imposed on him (That is the) Way (of) Allah concerning those who passed away before before And is (the) Command (of) Allah a decree destined (38)",
      transliteration:
        "mā kāna ʿalā l-nabiyi min ḥarajin fīmā faraḍa l-lahu lahu sunnata l-lahi fī alladhīna khalaw min qablu wakāna amru l-lahi qadaran maqdūran ",
      verse: 3571,
      juz: 22,
      surah: 33,
    },
    {
      number: 39,
      image: "",
      text: "Those who convey (the) Messages (of) Allah and fear Him and (do) not fear anyone except Allah And sufficient is Allah And sufficient is Allah (as) a Reckoner (39)",
      transliteration:
        "alladhīna yuballighūna risālāti l-lahi wayakhshawnahu walā yakhshawna aḥadan illā l-laha wakafā bil-lahi ḥasīban ",
      verse: 3572,
      juz: 22,
      surah: 33,
    },
    {
      number: 40,
      image: "",
      text: "Not is Muhammad (the) father (of) anyone of your men but (he is the) Messenger (of) Allah and Seal (of) the Prophets And Allah is And Allah is of every thing All-Knower (40)",
      transliteration:
        "mā kāna muḥammadun abā aḥadin min rijālikum walākin rasūla l-lahi wakhātama l-nabiyīna wakāna l-lahu bikulli shayin ʿalīman ",
      verse: 3573,
      juz: 22,
      surah: 33,
    },
    {
      number: 41,
      image: "",
      text: "O you who believe O you who believe O you who believe Remember Allah (with) remembrance much (41)",
      transliteration:
        "yāayyuhā alladhīna āmanū udh'kurū l-laha dhik'ran kathīran ",
      verse: 3574,
      juz: 22,
      surah: 33,
    },
    {
      number: 42,
      image: "",
      text: "And glorify Him morning and evening (42)",
      transliteration: "wasabbiḥūhu buk'ratan wa-aṣīlan ",
      verse: 3575,
      juz: 22,
      surah: 33,
    },
    {
      number: 43,
      image: "",
      text: "He (is) the One Who sends His blessings upon you and His Angels so that He may bring you out from the darkness[es] to the light And He is to the believers Merciful (43)",
      transliteration:
        "huwa alladhī yuṣallī ʿalaykum wamalāikatuhu liyukh'rijakum mina l-ẓulumāti ilā l-nūri wakāna bil-mu'minīna raḥīman ",
      verse: 3576,
      juz: 22,
      surah: 33,
    },
    {
      number: 44,
      image: "",
      text: 'Their greetings (on the) Day they will meet Him (will be), "Peace and He has prepared for them a reward noble (44)',
      transliteration:
        "taḥiyyatuhum yawma yalqawnahu salāmun wa-aʿadda lahum ajran karīman ",
      verse: 3577,
      juz: 22,
      surah: 33,
    },
    {
      number: 45,
      image: "",
      text: "O Prophet O Prophet Indeed, We have sent you (as) a witness and a bearer of glad tidings and (as) a warner (45)",
      transliteration:
        "yāayyuhā l-nabiyu innā arsalnāka shāhidan wamubashiran wanadhīran ",
      verse: 3578,
      juz: 22,
      surah: 33,
    },
    {
      number: 46,
      image: "",
      text: "And as one who invites to Allah by His permission and (as) a lamp illuminating (46)",
      transliteration: "wadāʿiyan ilā l-lahi bi-idh'nihi wasirājan munīran ",
      verse: 3579,
      juz: 22,
      surah: 33,
    },
    {
      number: 47,
      image: "",
      text: "And give glad tidings (to) the believers that for them (is) from Allah a Bounty great (47)",
      transliteration:
        "wabashiri l-mu'minīna bi-anna lahum mina l-lahi faḍlan kabīran ",
      verse: 3580,
      juz: 22,
      surah: 33,
    },
    {
      number: 48,
      image: "",
      text: "And (do) not obey the disbelievers and the hypocrites and disregard their harm and put your trust in Allah And sufficient is Allah And sufficient is Allah (as) a Trustee (48)",
      transliteration:
        "walā tuṭiʿi l-kāfirīna wal-munāfiqīna wadaʿ adhāhum watawakkal ʿalā l-lahi wakafā bil-lahi wakīlan ",
      verse: 3581,
      juz: 22,
      surah: 33,
    },
    {
      number: 49,
      image: "",
      text: "O you who believe O you who believe O you who believe When you marry believing women and then divorce them before before [that] you have touched them then not for you on them any waiting period (to) count concerning them So provide for them and release them (with) a release good (49)",
      transliteration:
        "yāayyuhā alladhīna āmanū idhā nakaḥtumu l-mu'mināti thumma ṭallaqtumūhunna min qabli an tamassūhunna famā lakum ʿalayhinna min ʿiddatin taʿtaddūnahā famattiʿūhunna wasarriḥūhunna sarāḥan jamīlan ",
      verse: 3582,
      juz: 22,
      surah: 33,
    },
    {
      number: 50,
      image: "",
      text: "O Prophet O Prophet Indeed, We [We] have made lawful to you your wives (to) whom you have given their bridal money and whom you rightfully possess you rightfully possess from those (whom) Allah has given Allah has given to you and (the) daughters (of) your paternal uncles and (the) daughters (of) your paternal aunts and (the) daughters (of) your maternal uncles and (the) daughters (of) your maternal aunts who emigrated with you and a woman believing if she gives herself to the Prophet if wishes the Prophet to marry her  only for you excluding excluding the believers Certainly We know what We have made obligatory upon them concerning their wives and whom they rightfully possess they rightfully possess that not should be on you any discomfort And Allah is And Allah is Oft-Forgiving Most Merciful (50)",
      transliteration:
        "yāayyuhā l-nabiyu innā aḥlalnā laka azwājaka allātī ātayta ujūrahunna wamā malakat yamīnuka mimmā afāa l-lahu ʿalayka wabanāti ʿammika wabanāti ʿammātika wabanāti khālika wabanāti khālātika allātī hājarna maʿaka wa-im'ra-atan mu'minatan in wahabat nafsahā lilnnabiyyi in arāda l-nabiyu an yastankiḥahā khāliṣatan laka min dūni l-mu'minīna qad ʿalim'nā mā faraḍnā ʿalayhim fī azwājihim wamā malakat aymānuhum likaylā yakūna ʿalayka ḥarajun wakāna l-lahu ghafūran raḥīman ",
      verse: 3583,
      juz: 22,
      surah: 33,
    },
    {
      number: 51,
      image: "",
      text: "You may defer whom you will of them or you may take to yourself whom you will And whoever you desire of those whom you (had) set aside  then (there is) no blame upon you That (is) more suitable that may be cooled their eyes and not they grieve and they may be pleased with what you have given them  all of them And Allah knows what (is) in your hearts And Allah is And Allah is All-Knower Most Forbearing (51)",
      transliteration:
        "tur'jī man tashāu min'hunna watu'wī ilayka man tashāu wamani ib'taghayta mimman ʿazalta falā junāḥa ʿalayka dhālika adnā an taqarra aʿyunuhunna walā yaḥzanna wayarḍayna bimā ātaytahunna kulluhunna wal-lahu yaʿlamu mā fī qulūbikum wakāna l-lahu ʿalīman ḥalīman ",
      verse: 3584,
      juz: 22,
      surah: 33,
    },
    {
      number: 52,
      image: "",
      text: "(It is) not lawful for you (to marry) women after (this) after (this) and not to exchange them for (other) wives even if pleases you their beauty except whom you rightfully possess you rightfully possess And Allah is And Allah is over all things an Observer (52)",
      transliteration:
        "lā yaḥillu laka l-nisāu min baʿdu walā an tabaddala bihinna min azwājin walaw aʿjabaka ḥus'nuhunna illā mā malakat yamīnuka wakāna l-lahu ʿalā kulli shayin raqīban ",
      verse: 3585,
      juz: 22,
      surah: 33,
    },
    {
      number: 53,
      image: "",
      text: "O you who believe O you who believe O you who believe (Do) not enter (the) houses (of) the Prophet except when permission is given to you for a meal without awaiting its preparation But when you are invited then enter and when you have eaten then disperse and not seeking to remain for a conversation Indeed that was troubling the Prophet and he is shy of (dismissing) you But Allah is not shy is not shy of the truth And when you ask them (for) anything then ask them from behind a screen That (is) purer for your hearts and their hearts And not is for you that you trouble (the) Messenger (of) Allah and not that you should marry his wives after him after him ever Indeed that is near Allah an enormity (53)",
      transliteration:
        "yāayyuhā alladhīna āmanū lā tadkhulū buyūta l-nabiyi illā an yu'dhana lakum ilā ṭaʿāmin ghayra nāẓirīna ināhu walākin idhā duʿītum fa-ud'khulū fa-idhā ṭaʿim'tum fa-intashirū walā mus'tanisīna liḥadīthin inna dhālikum kāna yu'dhī l-nabiya fayastaḥyī minkum wal-lahu lā yastaḥyī mina l-ḥaqi wa-idhā sa-altumūhunna matāʿan fasalūhunna min warāi ḥijābin dhālikum aṭharu liqulūbikum waqulūbihinna wamā kāna lakum an tu'dhū rasūla l-lahi walā an tankiḥū azwājahu min baʿdihi abadan inna dhālikum kāna ʿinda l-lahi ʿaẓīman ",
      verse: 3586,
      juz: 22,
      surah: 33,
    },
    {
      number: 54,
      image: "",
      text: "Whether you reveal a thing or conceal it indeed Allah is of all things All-Knower (54)",
      transliteration:
        "in tub'dū shayan aw tukh'fūhu fa-inna l-laha kāna bikulli shayin ʿalīman ",
      verse: 3587,
      juz: 22,
      surah: 33,
    },
    {
      number: 55,
      image: "",
      text: "(There is) no blame upon them concerning their fathers and not their sons and not their brothers and not sons (of) their brothers and not sons (of) their sisters and not their women and not what they rightfully possess they rightfully possess And fear Allah Indeed Allah is over all things a Witness (55)",
      transliteration:
        "lā junāḥa ʿalayhinna fī ābāihinna walā abnāihinna walā ikh'wānihinna walā abnāi ikh'wānihinna walā abnāi akhawātihinna walā nisāihinna walā mā malakat aymānuhunna wa-ittaqīna l-laha inna l-laha kāna ʿalā kulli shayin shahīdan ",
      verse: 3588,
      juz: 22,
      surah: 33,
    },
    {
      number: 56,
      image: "",
      text: "Indeed Allah and His Angels send blessings upon the Prophet O you who believe O you who believe O you who believe Send blessings on him and greet him (with) greetings (56)",
      transliteration:
        "inna l-laha wamalāikatahu yuṣallūna ʿalā l-nabiyi yāayyuhā alladhīna āmanū ṣallū ʿalayhi wasallimū taslīman ",
      verse: 3589,
      juz: 22,
      surah: 33,
    },
    {
      number: 57,
      image: "",
      text: "Indeed those who annoy Allah and His Messenger Allah has cursed them Allah has cursed them in the world and the Hereafter and prepared for them a punishment humiliating (57)",
      transliteration:
        "inna alladhīna yu'dhūna l-laha warasūlahu laʿanahumu l-lahu fī l-dun'yā wal-ākhirati wa-aʿadda lahum ʿadhāban muhīnan ",
      verse: 3590,
      juz: 22,
      surah: 33,
    },
    {
      number: 58,
      image: "",
      text: "And those who harm the believing men and the believing women for other than what they have earned then certainly they bear false accusation and sin manifest (58)",
      transliteration:
        "wa-alladhīna yu'dhūna l-mu'minīna wal-mu'mināti bighayri mā ik'tasabū faqadi iḥ'tamalū buh'tānan wa-ith'man mubīnan ",
      verse: 3591,
      juz: 22,
      surah: 33,
    },
    {
      number: 59,
      image: "",
      text: "O Prophet O Prophet Say to your wives and your daughters and (the) women (of) the believers to draw over themselves [of] their outer garments That (is) more suitable that they should be known and not harmed And is Allah Oft-Forgiving Most Merciful (59)",
      transliteration:
        "yāayyuhā l-nabiyu qul li-azwājika wabanātika wanisāi l-mu'minīna yud'nīna ʿalayhinna min jalābībihinna dhālika adnā an yuʿ'rafna falā yu'dhayna wakāna l-lahu ghafūran raḥīman ",
      verse: 3592,
      juz: 22,
      surah: 33,
    },
    {
      number: 60,
      image: "",
      text: "If (do) not cease the hypocrites and those who in their hearts (is) a disease and those who spread rumors in the city We will let you overpower them We will let you overpower them then not they will remain your neighbors therein except (for) a little (60)",
      transliteration:
        "la-in lam yantahi l-munāfiqūna wa-alladhīna fī qulūbihim maraḍun wal-mur'jifūna fī l-madīnati lanugh'riyannaka bihim thumma lā yujāwirūnaka fīhā illā qalīlan ",
      verse: 3593,
      juz: 22,
      surah: 33,
    },
    {
      number: 61,
      image: "",
      text: "Accursed wherever they are found they are seized and massacred completely and massacred completely (61)",
      transliteration: "malʿūnīna aynamā thuqifū ukhidhū waquttilū taqtīlan ",
      verse: 3594,
      juz: 22,
      surah: 33,
    },
    {
      number: 62,
      image: "",
      text: "(Such is the) Way (of) Allah with those who passed away before before and never you will find in (the) Way (of) Allah any change (62)",
      transliteration:
        "sunnata l-lahi fī alladhīna khalaw min qablu walan tajida lisunnati l-lahi tabdīlan ",
      verse: 3595,
      juz: 22,
      surah: 33,
    },
    {
      number: 63,
      image: "",
      text: "Ask you the people about the Hour Say Only its knowledge (is) with Allah And what will make you know Perhaps the Hour is near (63)",
      transliteration:
        "yasaluka l-nāsu ʿani l-sāʿati qul innamā ʿil'muhā ʿinda l-lahi wamā yud'rīka laʿalla l-sāʿata takūnu qarīban ",
      verse: 3596,
      juz: 22,
      surah: 33,
    },
    {
      number: 64,
      image: "",
      text: "Indeed Allah has cursed the disbelievers and has prepared for them a Blaze (64)",
      transliteration: "inna l-laha laʿana l-kāfirīna wa-aʿadda lahum saʿīran ",
      verse: 3597,
      juz: 22,
      surah: 33,
    },
    {
      number: 65,
      image: "",
      text: "Abiding therein forever not they will find any protector and not any helper (65)",
      transliteration: "khālidīna fīhā abadan lā yajidūna waliyyan walā naṣīran ",
      verse: 3598,
      juz: 22,
      surah: 33,
    },
    {
      number: 66,
      image: "",
      text: "(The) Day will be turned about their faces in the Fire they will say O we wish we (had) obeyed Allah and obeyed the Messenger (66)",
      transliteration:
        "yawma tuqallabu wujūhuhum fī l-nāri yaqūlūna yālaytanā aṭaʿnā l-laha wa-aṭaʿnā l-rasūlā ",
      verse: 3599,
      juz: 22,
      surah: 33,
    },
    {
      number: 67,
      image: "",
      text: "And they will say Our Lord Indeed, we [we] obeyed our chiefs and our great men and they misled us (from) the Way (67)",
      transliteration:
        "waqālū rabbanā innā aṭaʿnā sādatanā wakubarāanā fa-aḍallūnā l-sabīlā ",
      verse: 3600,
      juz: 22,
      surah: 33,
    },
    {
      number: 68,
      image: "",
      text: "Our Lord Give them double [of] punishment and curse them (with) a curse great (68)",
      transliteration:
        "rabbanā ātihim ḍiʿ'fayni mina l-ʿadhābi wal-ʿanhum laʿnan kabīran ",
      verse: 3601,
      juz: 22,
      surah: 33,
    },
    {
      number: 69,
      image: "",
      text: "O you who believe O you who believe O you who believe (Do) not be like those who abused Musa then Allah cleared him then Allah cleared him of what they said And he was near Allah honorable (69)",
      transliteration:
        "yāayyuhā alladhīna āmanū lā takūnū ka-alladhīna ādhaw mūsā fabarra-ahu l-lahu mimmā qālū wakāna ʿinda l-lahi wajīhan ",
      verse: 3602,
      juz: 22,
      surah: 33,
    },
    {
      number: 70,
      image: "",
      text: "O you who believe O you who believe O you who believe Fear Allah and speak a word right (70)",
      transliteration:
        "yāayyuhā alladhīna āmanū ittaqū l-laha waqūlū qawlan sadīdan ",
      verse: 3603,
      juz: 22,
      surah: 33,
    },
    {
      number: 71,
      image: "",
      text: "He will amend for you your deeds and forgive for you your sins And whoever obeys Allah and His Messenger certainly has attained an attainment great (71)",
      transliteration:
        "yuṣ'liḥ lakum aʿmālakum wayaghfir lakum dhunūbakum waman yuṭiʿi l-laha warasūlahu faqad fāza fawzan ʿaẓīman ",
      verse: 3604,
      juz: 22,
      surah: 33,
    },
    {
      number: 72,
      image: "",
      text: "Indeed, We [We] offered the Trust to the heavens and the earth and the mountains but they refused to bear it and they feared from it but bore it the man Indeed, he was unjust ignorant (72)",
      transliteration:
        "innā ʿaraḍnā l-amānata ʿalā l-samāwāti wal-arḍi wal-jibāli fa-abayna an yaḥmil'nahā wa-ashfaqna min'hā waḥamalahā l-insānu innahu kāna ẓalūman jahūlan ",
      verse: 3605,
      juz: 22,
      surah: 33,
    },
    {
      number: 73,
      image: "",
      text: "So that Allah may punish So that Allah may punish the hypocrite men and the hypocrite women and the polytheist men and the polytheist women and Allah will turn (in Mercy) and Allah will turn (in Mercy) to the believing men and the believing women And Allah is And Allah is Oft-Forgiving Most Merciful (73)",
      transliteration:
        "liyuʿadhiba l-lahu l-munāfiqīna wal-munāfiqāti wal-mush'rikīna wal-mush'rikāti wayatūba l-lahu ʿalā l-mu'minīna wal-mu'mināti wakāna l-lahu ghafūran raḥīman ",
      verse: 3606,
      juz: 22,
      surah: 33,
    },
  ],
};
