import { Surah } from "../types/islam.js";

export const ala: Surah = {
  name: "Al-A'la",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "Glorify (the) name (of) your Lord the Most High (1)",
      transliteration: "sabbiḥi is'ma rabbika l-aʿlā ",
      verse: 5949,
      juz: 30,
      surah: 87,
    },
    {
      number: 2,
      image: "",
      text: "The One Who created then proportioned (2)",
      transliteration: "alladhī khalaqa fasawwā ",
      verse: 5950,
      juz: 30,
      surah: 87,
    },
    {
      number: 3,
      image: "",
      text: "And the One Who measured then guided (3)",
      transliteration: "wa-alladhī qaddara fahadā ",
      verse: 5951,
      juz: 30,
      surah: 87,
    },
    {
      number: 4,
      image: "",
      text: "And the One Who brings forth the pasture (4)",
      transliteration: "wa-alladhī akhraja l-marʿā ",
      verse: 5952,
      juz: 30,
      surah: 87,
    },
    {
      number: 5,
      image: "",
      text: "And then makes it stubble dark (5)",
      transliteration: "fajaʿalahu ghuthāan aḥwā ",
      verse: 5953,
      juz: 30,
      surah: 87,
    },
    {
      number: 6,
      image: "",
      text: "We will make you recite so not you will forget (6)",
      transliteration: "sanuq'ri-uka falā tansā ",
      verse: 5954,
      juz: 30,
      surah: 87,
    },
    {
      number: 7,
      image: "",
      text: "Except what wills Allah Indeed, He knows the manifest and what is hidden (7)",
      transliteration:
        "illā mā shāa l-lahu innahu yaʿlamu l-jahra wamā yakhfā ",
      verse: 5955,
      juz: 30,
      surah: 87,
    },
    {
      number: 8,
      image: "",
      text: "And We will ease you to the ease (8)",
      transliteration: "wanuyassiruka lil'yus'rā ",
      verse: 5956,
      juz: 30,
      surah: 87,
    },
    {
      number: 9,
      image: "",
      text: "So remind if benefits the reminder (9)",
      transliteration: "fadhakkir in nafaʿati l-dhik'rā ",
      verse: 5957,
      juz: 30,
      surah: 87,
    },
    {
      number: 10,
      image: "",
      text: "He will pay heed  (one) who fears (Allah) (10)",
      transliteration: "sayadhakkaru man yakhshā ",
      verse: 5958,
      juz: 30,
      surah: 87,
    },
    {
      number: 11,
      image: "",
      text: "And will avoid it the wretched one (11)",
      transliteration: "wayatajannabuhā l-ashqā ",
      verse: 5959,
      juz: 30,
      surah: 87,
    },
    {
      number: 12,
      image: "",
      text: "The one who will burn (in) the Fire [the] great (12)",
      transliteration: "alladhī yaṣlā l-nāra l-kub'rā ",
      verse: 5960,
      juz: 30,
      surah: 87,
    },
    {
      number: 13,
      image: "",
      text: "Then not he will die therein and not will live (13)",
      transliteration: "thumma lā yamūtu fīhā walā yaḥyā ",
      verse: 5961,
      juz: 30,
      surah: 87,
    },
    {
      number: 14,
      image: "",
      text: "Certainly has succeeded (one) who purifies (himself) (14)",
      transliteration: "qad aflaḥa man tazakkā ",
      verse: 5962,
      juz: 30,
      surah: 87,
    },
    {
      number: 15,
      image: "",
      text: "And remembers (the) name (of) his Lord and prays (15)",
      transliteration: "wadhakara is'ma rabbihi faṣallā ",
      verse: 5963,
      juz: 30,
      surah: 87,
    },
    {
      number: 16,
      image: "",
      text: "Nay You prefer the life (of) the world (16)",
      transliteration: "bal tu'thirūna l-ḥayata l-dun'yā ",
      verse: 5964,
      juz: 30,
      surah: 87,
    },
    {
      number: 17,
      image: "",
      text: "While the Hereafter (is) better and everlasting (17)",
      transliteration: "wal-ākhiratu khayrun wa-abqā ",
      verse: 5965,
      juz: 30,
      surah: 87,
    },
    {
      number: 18,
      image: "",
      text: "Indeed this surely (is) in the Scriptures [the] former (18)",
      transliteration: "inna hādhā lafī l-ṣuḥufi l-ūlā ",
      verse: 5966,
      juz: 30,
      surah: 87,
    },
    {
      number: 19,
      image: "",
      text: "(The) Scriptures (of) Ibrahim and Musa (19)",
      transliteration: "ṣuḥufi ib'rāhīma wamūsā ",
      verse: 5967,
      juz: 30,
      surah: 87,
    },
  ],
};
