import { Surah } from "../types/islam.js";

export const alaq: Surah = {
  name: "Al-'Alaq",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "Read in (the) name (of) your Lord the One Who created  (1)",
      transliteration: "iq'ra bi-is'mi rabbika alladhī khalaqa ",
      verse: 6107,
      juz: 30,
      surah: 96,
    },
    {
      number: 2,
      image: "",
      text: "He created man from a clinging substance (2)",
      transliteration: "khalaqa l-insāna min ʿalaqin ",
      verse: 6108,
      juz: 30,
      surah: 96,
    },
    {
      number: 3,
      image: "",
      text: "Read and your Lord (is) the Most Generous (3)",
      transliteration: "iq'ra warabbuka l-akramu ",
      verse: 6109,
      juz: 30,
      surah: 96,
    },
    {
      number: 4,
      image: "",
      text: "The One Who taught by the pen (4)",
      transliteration: "alladhī ʿallama bil-qalami ",
      verse: 6110,
      juz: 30,
      surah: 96,
    },
    {
      number: 5,
      image: "",
      text: "Taught man what not he knew (5)",
      transliteration: "ʿallama l-insāna mā lam yaʿlam ",
      verse: 6111,
      juz: 30,
      surah: 96,
    },
    {
      number: 6,
      image: "",
      text: "Nay Indeed man surely transgresses (6)",
      transliteration: "kallā inna l-insāna layaṭghā ",
      verse: 6112,
      juz: 30,
      surah: 96,
    },
    {
      number: 7,
      image: "",
      text: "That he sees himself self-sufficient (7)",
      transliteration: "an raāhu is'taghnā ",
      verse: 6113,
      juz: 30,
      surah: 96,
    },
    {
      number: 8,
      image: "",
      text: "Indeed to your Lord (is) the return (8)",
      transliteration: "inna ilā rabbika l-ruj'ʿā ",
      verse: 6114,
      juz: 30,
      surah: 96,
    },
    {
      number: 9,
      image: "",
      text: "Have you seen the one who forbids (9)",
      transliteration: "ara-ayta alladhī yanhā ",
      verse: 6115,
      juz: 30,
      surah: 96,
    },
    {
      number: 10,
      image: "",
      text: "A slave when he prays (10)",
      transliteration: "ʿabdan idhā ṣallā ",
      verse: 6116,
      juz: 30,
      surah: 96,
    },
    {
      number: 11,
      image: "",
      text: "Have you seen if he is upon [the] guidance (11)",
      transliteration: "ara-ayta in kāna ʿalā l-hudā ",
      verse: 6117,
      juz: 30,
      surah: 96,
    },
    {
      number: 12,
      image: "",
      text: "Or he enjoins [of the] righteousness (12)",
      transliteration: "aw amara bil-taqwā ",
      verse: 6118,
      juz: 30,
      surah: 96,
    },
    {
      number: 13,
      image: "",
      text: "Have you seen if he denies and turns away (13)",
      transliteration: "ara-ayta in kadhaba watawallā ",
      verse: 6119,
      juz: 30,
      surah: 96,
    },
    {
      number: 14,
      image: "",
      text: "Does not he know that Allah sees (14)",
      transliteration: "alam yaʿlam bi-anna l-laha yarā ",
      verse: 6120,
      juz: 30,
      surah: 96,
    },
    {
      number: 15,
      image: "",
      text: "Nay If not he desists surely We will drag him by the forelock (15)",
      transliteration: "kallā la-in lam yantahi lanasfaʿan bil-nāṣiyati ",
      verse: 6121,
      juz: 30,
      surah: 96,
    },
    {
      number: 16,
      image: "",
      text: "A forelock lying sinful (16)",
      transliteration: "nāṣiyatin kādhibatin khāṭi-atin ",
      verse: 6122,
      juz: 30,
      surah: 96,
    },
    {
      number: 17,
      image: "",
      text: "Then let him call his associates (17)",
      transliteration: "falyadʿu nādiyahu ",
      verse: 6123,
      juz: 30,
      surah: 96,
    },
    {
      number: 18,
      image: "",
      text: "We will call the Angels of Hell (18)",
      transliteration: "sanadʿu l-zabāniyata ",
      verse: 6124,
      juz: 30,
      surah: 96,
    },
    {
      number: 19,
      image: "",
      text: "Nay (Do) not obey him But prostrate and draw near (to Allah) (19)",
      transliteration: "kallā lā tuṭiʿ'hu wa-us'jud wa-iq'tarib ",
      verse: 6125,
      juz: 30,
      surah: 96,
    },
  ],
};
