import { Surah } from "../types/islam.js";

export const anbya: Surah = {
  name: "Al-Anbya",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "(Has) approached for [the] mankind their account while they (are) in heedlessness turning away (1)",
      transliteration:
        "iq'taraba lilnnāsi ḥisābuhum wahum fī ghaflatin muʿ'riḍūna ",
      verse: 2484,
      juz: 17,
      surah: 21,
    },
    {
      number: 2,
      image: "",
      text: "Not comes to them of a Reminder from their Lord anew except they listen to it while they (are at) play (2)",
      transliteration:
        "mā yatīhim min dhik'rin min rabbihim muḥ'dathin illā is'tamaʿūhu wahum yalʿabūna ",
      verse: 2485,
      juz: 17,
      surah: 21,
    },
    {
      number: 3,
      image: "",
      text: "Distracted their hearts And they conceal the private conversation those who [they] wronged Is this except a human being like you So would you approach the magic while you see (it) (3)",
      transliteration:
        "lāhiyatan qulūbuhum wa-asarrū l-najwā alladhīna ẓalamū hal hādhā illā basharun mith'lukum afatatūna l-siḥ'ra wa-antum tub'ṣirūna ",
      verse: 2486,
      juz: 17,
      surah: 21,
    },
    {
      number: 4,
      image: "",
      text: "He said My Lord knows the word in the heavens and the earth And He (is) the All-Hearer the All-Knower (4)",
      transliteration:
        "qāla rabbī yaʿlamu l-qawla fī l-samāi wal-arḍi wahuwa l-samīʿu l-ʿalīmu ",
      verse: 2487,
      juz: 17,
      surah: 21,
    },
    {
      number: 5,
      image: "",
      text: "Nay they say Muddled dreams nay he (has) invented it nay he (is) a poet So let him bring us a sign like what was sent (to) the former (5)",
      transliteration:
        "bal qālū aḍghāthu aḥlāmin bali if'tarāhu bal huwa shāʿirun falyatinā biāyatin kamā ur'sila l-awalūna ",
      verse: 2488,
      juz: 17,
      surah: 21,
    },
    {
      number: 6,
      image: "",
      text: "Not believed before them any town which We destroyed so will they believe (6)",
      transliteration:
        "mā āmanat qablahum min qaryatin ahlaknāhā afahum yu'minūna ",
      verse: 2489,
      juz: 17,
      surah: 21,
    },
    {
      number: 7,
      image: "",
      text: "And not We sent before you except men We revealed to them So ask (the) people (of) the Reminder if you (do) not know (7)",
      transliteration:
        "wamā arsalnā qablaka illā rijālan nūḥī ilayhim fasalū ahla l-dhik'ri in kuntum lā taʿlamūna ",
      verse: 2490,
      juz: 17,
      surah: 21,
    },
    {
      number: 8,
      image: "",
      text: "And not We made them bodies not eating the food and not they were immortals (8)",
      transliteration:
        "wamā jaʿalnāhum jasadan lā yakulūna l-ṭaʿāma wamā kānū khālidīna ",
      verse: 2491,
      juz: 17,
      surah: 21,
    },
    {
      number: 9,
      image: "",
      text: "Then We fulfilled (for) them the promise and We saved them and whom We willed and We destroyed the transgressors (9)",
      transliteration:
        "thumma ṣadaqnāhumu l-waʿda fa-anjaynāhum waman nashāu wa-ahlaknā l-mus'rifīna ",
      verse: 2492,
      juz: 17,
      surah: 21,
    },
    {
      number: 10,
      image: "",
      text: "Indeed We (have) sent down to you a Book in it (is) your mention Then will not you use reason (10)",
      transliteration:
        "laqad anzalnā ilaykum kitāban fīhi dhik'rukum afalā taʿqilūna ",
      verse: 2493,
      juz: 17,
      surah: 21,
    },
    {
      number: 11,
      image: "",
      text: "And how many We (have) shattered of a town (that) was unjust and We produced after them another people another people (11)",
      transliteration:
        "wakam qaṣamnā min qaryatin kānat ẓālimatan wa-anshanā baʿdahā qawman ākharīna ",
      verse: 2494,
      juz: 17,
      surah: 21,
    },
    {
      number: 12,
      image: "",
      text: "Then when they perceived Our torment behold they from it were fleeing (12)",
      transliteration: "falammā aḥassū basanā idhā hum min'hā yarkuḍūna ",
      verse: 2495,
      juz: 17,
      surah: 21,
    },
    {
      number: 13,
      image: "",
      text: "Flee not Flee not but return to what you were given luxury in it and to your homes so that you may be questioned (13)",
      transliteration:
        "lā tarkuḍū wa-ir'jiʿū ilā mā ut'rif'tum fīhi wamasākinikum laʿallakum tus'alūna ",
      verse: 2496,
      juz: 17,
      surah: 21,
    },
    {
      number: 14,
      image: "",
      text: "They said O woe to us Indeed, [we] we were wrongdoers (14)",
      transliteration: "qālū yāwaylanā innā kunnā ẓālimīna ",
      verse: 2497,
      juz: 17,
      surah: 21,
    },
    {
      number: 15,
      image: "",
      text: "Then not ceased [this] their cry until We made them reaped extinct (15)",
      transliteration:
        "famā zālat til'ka daʿwāhum ḥattā jaʿalnāhum ḥaṣīdan khāmidīna ",
      verse: 2498,
      juz: 17,
      surah: 21,
    },
    {
      number: 16,
      image: "",
      text: "And not We created the heavens and the earth and what (is) between them (for) playing (16)",
      transliteration: "wamā khalaqnā l-samāa wal-arḍa wamā baynahumā lāʿibīna ",
      verse: 2499,
      juz: 17,
      surah: 21,
    },
    {
      number: 17,
      image: "",
      text: "If We intended that We take a pastime surely We (could have) taken it from Us if We were doers (17)",
      transliteration:
        "law aradnā an nattakhidha lahwan la-ittakhadhnāhu min ladunnā in kunnā fāʿilīna ",
      verse: 2500,
      juz: 17,
      surah: 21,
    },
    {
      number: 18,
      image: "",
      text: "Nay We hurl the truth against [the] falsehood and it breaks its head behold it (is) vanishing And for you (is) destruction for what you ascribe (18)",
      transliteration:
        "bal naqdhifu bil-ḥaqi ʿalā l-bāṭili fayadmaghuhu fa-idhā huwa zāhiqun walakumu l-waylu mimmā taṣifūna ",
      verse: 2501,
      juz: 17,
      surah: 21,
    },
    {
      number: 19,
      image: "",
      text: "And to Him (belongs) whoever (is) in the heavens and the earth And (those) who (are) near Him not they are arrogant to worship Him and not they tire (19)",
      transliteration:
        "walahu man fī l-samāwāti wal-arḍi waman ʿindahu lā yastakbirūna ʿan ʿibādatihi walā yastaḥsirūna ",
      verse: 2502,
      juz: 17,
      surah: 21,
    },
    {
      number: 20,
      image: "",
      text: "They glorify (Him) [the] night and [the] day not they slacken (20)",
      transliteration: "yusabbiḥūna al-layla wal-nahāra lā yafturūna ",
      verse: 2503,
      juz: 17,
      surah: 21,
    },
    {
      number: 21,
      image: "",
      text: "Or (have) they taken gods from the earth they raise (the dead) (21)",
      transliteration: "ami ittakhadhū ālihatan mina l-arḍi hum yunshirūna ",
      verse: 2504,
      juz: 17,
      surah: 21,
    },
    {
      number: 22,
      image: "",
      text: "If (there) were in both of them gods besides Allah surely they (would) have been ruined So glorified (is) Allah Lord (of) the Throne (above) what they attribute (22)",
      transliteration:
        "law kāna fīhimā ālihatun illā l-lahu lafasadatā fasub'ḥāna l-lahi rabbi l-ʿarshi ʿammā yaṣifūna ",
      verse: 2505,
      juz: 17,
      surah: 21,
    },
    {
      number: 23,
      image: "",
      text: "Not He (can) be questioned about what He does but they will be questioned (23)",
      transliteration: "lā yus'alu ʿammā yafʿalu wahum yus'alūna ",
      verse: 2506,
      juz: 17,
      surah: 21,
    },
    {
      number: 24,
      image: "",
      text: "Or (have) they taken besides Him besides Him gods Say Bring your proof This (is) a Reminder (for those) who (are) with me and a Reminder (for those) who (were) before me But most of them (do) not know the truth so they (are) averse (24)",
      transliteration:
        "ami ittakhadhū min dūnihi ālihatan qul hātū bur'hānakum hādhā dhik'ru man maʿiya wadhik'ru man qablī bal aktharuhum lā yaʿlamūna l-ḥaqa fahum muʿ'riḍūna ",
      verse: 2507,
      juz: 17,
      surah: 21,
    },
    {
      number: 25,
      image: "",
      text: "And not We sent before you before you any Messenger but We reveal(ed) to him that [He] (There is) no god except Me so worship Me (25)",
      transliteration:
        "wamā arsalnā min qablika min rasūlin illā nūḥī ilayhi annahu lā ilāha illā anā fa-uʿ'budūni ",
      verse: 2508,
      juz: 17,
      surah: 21,
    },
    {
      number: 26,
      image: "",
      text: "And they say Has taken the Most Gracious a son Glorified is He Nay (they are) slaves honored (26)",
      transliteration:
        "waqālū ittakhadha l-raḥmānu waladan sub'ḥānahu bal ʿibādun muk'ramūna ",
      verse: 2509,
      juz: 17,
      surah: 21,
    },
    {
      number: 27,
      image: "",
      text: "Not they (can) precede Him in word and they by His command act (27)",
      transliteration: "lā yasbiqūnahu bil-qawli wahum bi-amrihi yaʿmalūna ",
      verse: 2510,
      juz: 17,
      surah: 21,
    },
    {
      number: 28,
      image: "",
      text: "He knows what (is) before them (is) before them and what (is) behind them and not they (can) intercede except for whom He approves And they from fear of Him stand in awe (28)",
      transliteration:
        "yaʿlamu mā bayna aydīhim wamā khalfahum walā yashfaʿūna illā limani ir'taḍā wahum min khashyatihi mush'fiqūna ",
      verse: 2511,
      juz: 17,
      surah: 21,
    },
    {
      number: 29,
      image: "",
      text: "And whoever says of them Indeed, I am a god besides Him besides Him Then that We will recompense (with) Hell Thus We recompense the wrongdoers (29)",
      transliteration:
        "waman yaqul min'hum innī ilāhun min dūnihi fadhālika najzīhi jahannama kadhālika najzī l-ẓālimīna ",
      verse: 2512,
      juz: 17,
      surah: 21,
    },
    {
      number: 30,
      image: "",
      text: "Do not see those who disbelieved that the heavens and the earth were a joined entity then We parted them and We made from [the] water every living thing living thing Then will not they believe (30)",
      transliteration:
        "awalam yara alladhīna kafarū anna l-samāwāti wal-arḍa kānatā ratqan fafataqnāhumā wajaʿalnā mina l-māi kulla shayin ḥayyin afalā yu'minūna ",
      verse: 2513,
      juz: 17,
      surah: 21,
    },
    {
      number: 31,
      image: "",
      text: "And We (have) placed in the earth firmly set mountains lest it (should) shake with them and We made therein broad passes (as) ways so that they may (be) guided (31)",
      transliteration:
        "wajaʿalnā fī l-arḍi rawāsiya an tamīda bihim wajaʿalnā fīhā fijājan subulan laʿallahum yahtadūna ",
      verse: 2514,
      juz: 17,
      surah: 21,
    },
    {
      number: 32,
      image: "",
      text: "And We made the sky a roof protected But they from its Signs turn away (32)",
      transliteration:
        "wajaʿalnā l-samāa saqfan maḥfūẓan wahum ʿan āyātihā muʿ'riḍūna ",
      verse: 2515,
      juz: 17,
      surah: 21,
    },
    {
      number: 33,
      image: "",
      text: "And He (is) the One Who created the night and the day and the sun and the moon each in an orbit floating (33)",
      transliteration:
        "wahuwa alladhī khalaqa al-layla wal-nahāra wal-shamsa wal-qamara kullun fī falakin yasbaḥūna ",
      verse: 2516,
      juz: 17,
      surah: 21,
    },
    {
      number: 34,
      image: "",
      text: "And not We made for any man before you before you [the] immortality so if you die then (would) they live forever (34)",
      transliteration:
        "wamā jaʿalnā libasharin min qablika l-khul'da afa-in mitta fahumu l-khālidūna ",
      verse: 2517,
      juz: 17,
      surah: 21,
    },
    {
      number: 35,
      image: "",
      text: "Every soul (will) taste [the] death And We test you with [the] bad and [the] good (as) a trial and to Us you will be returned (35)",
      transliteration:
        "kullu nafsin dhāiqatu l-mawti wanablūkum bil-shari wal-khayri fit'natan wa-ilaynā tur'jaʿūna ",
      verse: 2518,
      juz: 17,
      surah: 21,
    },
    {
      number: 36,
      image: "",
      text: "And when they see you those who disbelieve not they take you except (in) ridicule Is this the one who mentions your gods And they at (the) mention (of) the Most Gracious [they] (are) disbelievers (36)",
      transliteration:
        "wa-idhā raāka alladhīna kafarū in yattakhidhūnaka illā huzuwan ahādhā alladhī yadhkuru ālihatakum wahum bidhik'ri l-raḥmāni hum kāfirūna ",
      verse: 2519,
      juz: 17,
      surah: 21,
    },
    {
      number: 37,
      image: "",
      text: "Is created the man of haste I will show you My Signs so (do) not ask Me to hasten (37)",
      transliteration:
        "khuliqa l-insānu min ʿajalin sa-urīkum āyātī falā tastaʿjilūni ",
      verse: 2520,
      juz: 17,
      surah: 21,
    },
    {
      number: 38,
      image: "",
      text: "And they say When (will be fulfilled) this promise if you are truthful (38)",
      transliteration: "wayaqūlūna matā hādhā l-waʿdu in kuntum ṣādiqīna ",
      verse: 2521,
      juz: 17,
      surah: 21,
    },
    {
      number: 39,
      image: "",
      text: "If knew those who disbelieved (the) time (when) not they will avert from their faces the Fire and not from their backs and not they will be helped (39)",
      transliteration:
        "law yaʿlamu alladhīna kafarū ḥīna lā yakuffūna ʿan wujūhihimu l-nāra walā ʿan ẓuhūrihim walā hum yunṣarūna ",
      verse: 2522,
      juz: 17,
      surah: 21,
    },
    {
      number: 40,
      image: "",
      text: "Nay it will come to them unexpectedly and bewilder them then not they will be able to repel it and not they will be given respite (40)",
      transliteration:
        "bal tatīhim baghtatan fatabhatuhum falā yastaṭīʿūna raddahā walā hum yunẓarūna ",
      verse: 2523,
      juz: 17,
      surah: 21,
    },
    {
      number: 41,
      image: "",
      text: "And verily were mocked Messengers before you before you then surrounded those who mocked from them what they used at it (to) mock (41)",
      transliteration:
        "walaqadi us'tuh'zi-a birusulin min qablika faḥāqa bi-alladhīna sakhirū min'hum mā kānū bihi yastahziūna ",
      verse: 2524,
      juz: 17,
      surah: 21,
    },
    {
      number: 42,
      image: "",
      text: "Say Who (can) protect you in the night and the day from the Most Gracious Yet they from (the) remembrance (of) their Lord turn away (42)",
      transliteration:
        "qul man yakla-ukum bi-al-layli wal-nahāri mina l-raḥmāni bal hum ʿan dhik'ri rabbihim muʿ'riḍūna ",
      verse: 2525,
      juz: 17,
      surah: 21,
    },
    {
      number: 43,
      image: "",
      text: "Or have they gods (to) defend them from Us Not they are able (to) help themselves and not they from Us can be protected (43)",
      transliteration:
        "am lahum ālihatun tamnaʿuhum min dūninā lā yastaṭīʿūna naṣra anfusihim walā hum minnā yuṣ'ḥabūna ",
      verse: 2526,
      juz: 17,
      surah: 21,
    },
    {
      number: 44,
      image: "",
      text: "Nay We gave provision (to) these and their fathers until grew long for them the life Then do not they see that We We come (to) the land We reduce it from its borders So is (it) they (who will be) overcoming (44)",
      transliteration:
        "bal mattaʿnā hāulāi waābāahum ḥattā ṭāla ʿalayhimu l-ʿumuru afalā yarawna annā natī l-arḍa nanquṣuhā min aṭrāfihā afahumu l-ghālibūna ",
      verse: 2527,
      juz: 17,
      surah: 21,
    },
    {
      number: 45,
      image: "",
      text: "Say Only I warn you by the revelation But not hear the deaf the call when when they are warned (45)",
      transliteration:
        "qul innamā undhirukum bil-waḥyi walā yasmaʿu l-ṣumu l-duʿāa idhā mā yundharūna ",
      verse: 2528,
      juz: 17,
      surah: 21,
    },
    {
      number: 46,
      image: "",
      text: "And if touches them a whiff of (the) punishment (of) your Lord surely they will say O woe to us Indeed, we [we] were wrongdoers (46)",
      transliteration:
        "wala-in massathum nafḥatun min ʿadhābi rabbika layaqūlunna yāwaylanā innā kunnā ẓālimīna ",
      verse: 2529,
      juz: 17,
      surah: 21,
    },
    {
      number: 47,
      image: "",
      text: "And We set the scales (of) the justice for (the) Day (of) the Resurrection so not will be wronged any soul (in) anything And if (there) be weight (of) a seed of a mustard We will bring [with] it And sufficient (are) We (as) Reckoners (47)",
      transliteration:
        "wanaḍaʿu l-mawāzīna l-qis'ṭa liyawmi l-qiyāmati falā tuẓ'lamu nafsun shayan wa-in kāna mith'qāla ḥabbatin min khardalin ataynā bihā wakafā binā ḥāsibīna ",
      verse: 2530,
      juz: 17,
      surah: 21,
    },
    {
      number: 48,
      image: "",
      text: "And verily We gave Musa and Harun the Criterion and a light and a Reminder for the righteous (48)",
      transliteration:
        "walaqad ātaynā mūsā wahārūna l-fur'qāna waḍiyāan wadhik'ran lil'muttaqīna ",
      verse: 2531,
      juz: 17,
      surah: 21,
    },
    {
      number: 49,
      image: "",
      text: "Those who fear their Lord in the unseen and they of the Hour (are) afraid (49)",
      transliteration:
        "alladhīna yakhshawna rabbahum bil-ghaybi wahum mina l-sāʿati mush'fiqūna ",
      verse: 2532,
      juz: 17,
      surah: 21,
    },
    {
      number: 50,
      image: "",
      text: "And this (is) a Reminder blessed which We (have) revealed Then are you of it rejecters (50)",
      transliteration:
        "wahādhā dhik'run mubārakun anzalnāhu afa-antum lahu munkirūna ",
      verse: 2533,
      juz: 17,
      surah: 21,
    },
    {
      number: 51,
      image: "",
      text: "And verily We gave Ibrahim his guidance before before and We were about him Well-Knowing (51)",
      transliteration:
        "walaqad ātaynā ib'rāhīma rush'dahu min qablu wakunnā bihi ʿālimīna ",
      verse: 2534,
      juz: 17,
      surah: 21,
    },
    {
      number: 52,
      image: "",
      text: "When he said to his father and his people What (are) these [the] statues which you to it (are) devoted (52)",
      transliteration:
        "idh qāla li-abīhi waqawmihi mā hādhihi l-tamāthīlu allatī antum lahā ʿākifūna ",
      verse: 2535,
      juz: 17,
      surah: 21,
    },
    {
      number: 53,
      image: "",
      text: "They said We found our forefathers of them worshippers (53)",
      transliteration: "qālū wajadnā ābāanā lahā ʿābidīna ",
      verse: 2536,
      juz: 17,
      surah: 21,
    },
    {
      number: 54,
      image: "",
      text: "He said Verily you are [you] and your forefathers (were) in an error manifest (54)",
      transliteration: "qāla laqad kuntum antum waābāukum fī ḍalālin mubīnin ",
      verse: 2537,
      juz: 17,
      surah: 21,
    },
    {
      number: 55,
      image: "",
      text: "They said Have you come to us with the truth or you (are) of those who play (55)",
      transliteration: "qālū aji'tanā bil-ḥaqi am anta mina l-lāʿibīna ",
      verse: 2538,
      juz: 17,
      surah: 21,
    },
    {
      number: 56,
      image: "",
      text: "He said Nay your Lord (is the) Lord (of) the heavens and the earth the One Who created them and I am to that of the witnesses (56)",
      transliteration:
        "qāla bal rabbukum rabbu l-samāwāti wal-arḍi alladhī faṭarahunna wa-anā ʿalā dhālikum mina l-shāhidīna ",
      verse: 2539,
      juz: 17,
      surah: 21,
    },
    {
      number: 57,
      image: "",
      text: "And by Allah surely, I will plan (against) your idols after [that] you go away turning (your) backs (57)",
      transliteration:
        "watal-lahi la-akīdanna aṣnāmakum baʿda an tuwallū mud'birīna ",
      verse: 2540,
      juz: 17,
      surah: 21,
    },
    {
      number: 58,
      image: "",
      text: "So he made them (into) pieces except a large (one) of them so that they may to it return (58)",
      transliteration:
        "fajaʿalahum judhādhan illā kabīran lahum laʿallahum ilayhi yarjiʿūna ",
      verse: 2541,
      juz: 17,
      surah: 21,
    },
    {
      number: 59,
      image: "",
      text: "They said Who (has) done this to our gods Indeed, he (is) of the wrongdoers (59)",
      transliteration:
        "qālū man faʿala hādhā biālihatinā innahu lamina l-ẓālimīna ",
      verse: 2542,
      juz: 17,
      surah: 21,
    },
    {
      number: 60,
      image: "",
      text: "They said We heard a youth mention them he is called he is called Ibrahim (60)",
      transliteration: "qālū samiʿ'nā fatan yadhkuruhum yuqālu lahu ib'rāhīmu ",
      verse: 2543,
      juz: 17,
      surah: 21,
    },
    {
      number: 61,
      image: "",
      text: "They said Then bring him before (the) eyes (of) the people so that they may bear witness (61)",
      transliteration: "qālū fatū bihi ʿalā aʿyuni l-nāsi laʿallahum yashhadūna ",
      verse: 2544,
      juz: 17,
      surah: 21,
    },
    {
      number: 62,
      image: "",
      text: "They said Have you done this to our gods O Ibrahim (62)",
      transliteration: "qālū a-anta faʿalta hādhā biālihatinā yāib'rāhīmu ",
      verse: 2545,
      juz: 17,
      surah: 21,
    },
    {
      number: 63,
      image: "",
      text: "He said Nay (some doer) did it Their chief (is) this So ask them if they (can) speak (63)",
      transliteration:
        "qāla bal faʿalahu kabīruhum hādhā fasalūhum in kānū yanṭiqūna ",
      verse: 2546,
      juz: 17,
      surah: 21,
    },
    {
      number: 64,
      image: "",
      text: "So they returned to themselves and said Indeed, you [you] (are) the wrongdoers (64)",
      transliteration: "farajaʿū ilā anfusihim faqālū innakum antumu l-ẓālimūna ",
      verse: 2547,
      juz: 17,
      surah: 21,
    },
    {
      number: 65,
      image: "",
      text: "Then they were turned on their heads Verily you know not these (can) speak (65)",
      transliteration:
        "thumma nukisū ʿalā ruūsihim laqad ʿalim'ta mā hāulāi yanṭiqūna ",
      verse: 2548,
      juz: 17,
      surah: 21,
    },
    {
      number: 66,
      image: "",
      text: "He said Then do you worship besides besides Allah what (does) not benefit you (in) anything and not harms you (66)",
      transliteration:
        "qāla afataʿbudūna min dūni l-lahi mā lā yanfaʿukum shayan walā yaḍurrukum ",
      verse: 2549,
      juz: 17,
      surah: 21,
    },
    {
      number: 67,
      image: "",
      text: "Uff to you and to what you worship besides besides Allah Then will not you use reason (67)",
      transliteration:
        "uffin lakum walimā taʿbudūna min dūni l-lahi afalā taʿqilūna ",
      verse: 2550,
      juz: 17,
      surah: 21,
    },
    {
      number: 68,
      image: "",
      text: "They said Burn him and support your gods if you are doers (68)",
      transliteration: "qālū ḥarriqūhu wa-unṣurū ālihatakum in kuntum fāʿilīna ",
      verse: 2551,
      juz: 17,
      surah: 21,
    },
    {
      number: 69,
      image: "",
      text: "We said O fire Be cool[ness] and safe[ty] for Ibrahim (69)",
      transliteration: "qul'nā yānāru kūnī bardan wasalāman ʿalā ib'rāhīma ",
      verse: 2552,
      juz: 17,
      surah: 21,
    },
    {
      number: 70,
      image: "",
      text: "And they intended for him a plan but We made them the greatest losers (70)",
      transliteration: "wa-arādū bihi kaydan fajaʿalnāhumu l-akhsarīna ",
      verse: 2553,
      juz: 17,
      surah: 21,
    },
    {
      number: 71,
      image: "",
      text: "And We delivered him and Lut to the land which We (had) blessed [in it] for the worlds (71)",
      transliteration:
        "wanajjaynāhu walūṭan ilā l-arḍi allatī bāraknā fīhā lil'ʿālamīna ",
      verse: 2554,
      juz: 17,
      surah: 21,
    },
    {
      number: 72,
      image: "",
      text: "And We bestowed on him Isaac and Yaqub (in) addition and all We made righteous (72)",
      transliteration:
        "wawahabnā lahu is'ḥāqa wayaʿqūba nāfilatan wakullan jaʿalnā ṣāliḥīna ",
      verse: 2555,
      juz: 17,
      surah: 21,
    },
    {
      number: 73,
      image: "",
      text: "And We made them leaders they guide by Our Command And We inspired to them (the) doing (of) good deeds and establishment (of) the prayer and giving (of) zakah and they were of Us worshippers (73)",
      transliteration:
        "wajaʿalnāhum a-immatan yahdūna bi-amrinā wa-awḥaynā ilayhim fiʿ'la l-khayrāti wa-iqāma l-ṣalati waītāa l-zakati wakānū lanā ʿābidīna ",
      verse: 2556,
      juz: 17,
      surah: 21,
    },
    {
      number: 74,
      image: "",
      text: "And (to) Lut We gave him judgment and knowledge and We saved him from the town which was doing wicked deeds Indeed, they were a people evil defiantly disobedient (74)",
      transliteration:
        "walūṭan ātaynāhu ḥuk'man waʿil'man wanajjaynāhu mina l-qaryati allatī kānat taʿmalu l-khabāitha innahum kānū qawma sawin fāsiqīna ",
      verse: 2557,
      juz: 17,
      surah: 21,
    },
    {
      number: 75,
      image: "",
      text: "And We admitted him into Our Mercy Indeed, he (was) of the righteous (75)",
      transliteration: "wa-adkhalnāhu fī raḥmatinā innahu mina l-ṣāliḥīna ",
      verse: 2558,
      juz: 17,
      surah: 21,
    },
    {
      number: 76,
      image: "",
      text: "And Nuh when he called before before so We responded to him and We saved him and his family from the affliction [the] great (76)",
      transliteration:
        "wanūḥan idh nādā min qablu fa-is'tajabnā lahu fanajjaynāhu wa-ahlahu mina l-karbi l-ʿaẓīmi ",
      verse: 2559,
      juz: 17,
      surah: 21,
    },
    {
      number: 77,
      image: "",
      text: "And We helped him from the people who denied Our Signs Indeed, they were a people evil so We drowned them all (77)",
      transliteration:
        "wanaṣarnāhu mina l-qawmi alladhīna kadhabū biāyātinā innahum kānū qawma sawin fa-aghraqnāhum ajmaʿīna ",
      verse: 2560,
      juz: 17,
      surah: 21,
    },
    {
      number: 78,
      image: "",
      text: "And Dawud and Sulaiman when they judged concerning the field when pastured in it sheep (of) a people and We were to their judgment witness (78)",
      transliteration:
        "wadāwūda wasulaymāna idh yaḥkumāni fī l-ḥarthi idh nafashat fīhi ghanamu l-qawmi wakunnā liḥuk'mihim shāhidīna ",
      verse: 2561,
      juz: 17,
      surah: 21,
    },
    {
      number: 79,
      image: "",
      text: "And We gave understanding of it (to) Sulaiman and (to) each We gave judgment and knowledge And We subjected with Dawud the mountains (to) glorify Our praises and the birds And We were the Doers (79)",
      transliteration:
        "fafahhamnāhā sulaymāna wakullan ātaynā ḥuk'man waʿil'man wasakharnā maʿa dāwūda l-jibāla yusabbiḥ'na wal-ṭayra wakunnā fāʿilīna ",
      verse: 2562,
      juz: 17,
      surah: 21,
    },
    {
      number: 80,
      image: "",
      text: "And We taught him (the) making (of) coats of armor for you to protect you from your battle Then will you (be) grateful (80)",
      transliteration:
        "waʿallamnāhu ṣanʿata labūsin lakum lituḥ'ṣinakum min basikum fahal antum shākirūna ",
      verse: 2563,
      juz: 17,
      surah: 21,
    },
    {
      number: 81,
      image: "",
      text: "And to Sulaiman the wind forcefully blowing by his command to the land which We blessed [in it] And We are of every thing Knowers (81)",
      transliteration:
        "walisulaymāna l-rīḥa ʿāṣifatan tajrī bi-amrihi ilā l-arḍi allatī bāraknā fīhā wakunnā bikulli shayin ʿālimīna ",
      verse: 2564,
      juz: 17,
      surah: 21,
    },
    {
      number: 82,
      image: "",
      text: "And of the devils (were some) who would dive for him and would do work other than that And We were of them Guardians (82)",
      transliteration:
        "wamina l-shayāṭīni man yaghūṣūna lahu wayaʿmalūna ʿamalan dūna dhālika wakunnā lahum ḥāfiẓīna ",
      verse: 2565,
      juz: 17,
      surah: 21,
    },
    {
      number: 83,
      image: "",
      text: "And Ayub when he called (to) his Lord Indeed, [I] has touched me the adversity and You (are) Most Merciful (of) the Merciful (83)",
      transliteration:
        "wa-ayyūba idh nādā rabbahu annī massaniya l-ḍuru wa-anta arḥamu l-rāḥimīna ",
      verse: 2566,
      juz: 17,
      surah: 21,
    },
    {
      number: 84,
      image: "",
      text: "So We responded to him and We removed what (was) on him of (the) adversity And We gave him his family and (the) like thereof with them (as) Mercy from Ourselves from Ourselves and a reminder for the worshippers (84)",
      transliteration:
        "fa-is'tajabnā lahu fakashafnā mā bihi min ḍurrin waātaynāhu ahlahu wamith'lahum maʿahum raḥmatan min ʿindinā wadhik'rā lil'ʿābidīna ",
      verse: 2567,
      juz: 17,
      surah: 21,
    },
    {
      number: 85,
      image: "",
      text: "And Ishmael and Idris and Dhul-Kifl and Dhul-Kifl all (were) of the patient ones (85)",
      transliteration:
        "wa-is'māʿīla wa-id'rīsa wadhā l-kif'li kullun mina l-ṣābirīna ",
      verse: 2568,
      juz: 17,
      surah: 21,
    },
    {
      number: 86,
      image: "",
      text: "And We admitted them in Our Mercy Indeed, they (were) of the righteous (86)",
      transliteration: "wa-adkhalnāhum fī raḥmatinā innahum mina l-ṣāliḥīna ",
      verse: 2569,
      juz: 17,
      surah: 21,
    },
    {
      number: 87,
      image: "",
      text: "And Dhun-Nun And Dhun-Nun when he went (while) angry and thought that never We would decree upon him Then he called in the darkness(es) that (There is) no god except You Glory be to You Indeed, [I] I am of the wrongdoers (87)",
      transliteration:
        "wadhā l-nūni idh dhahaba mughāḍiban faẓanna an lan naqdira ʿalayhi fanādā fī l-ẓulumāti an lā ilāha illā anta sub'ḥānaka innī kuntu mina l-ẓālimīna ",
      verse: 2570,
      juz: 17,
      surah: 21,
    },
    {
      number: 88,
      image: "",
      text: "So We responded to him and We saved him from the distress And thus We save the believers (88)",
      transliteration:
        "fa-is'tajabnā lahu wanajjaynāhu mina l-ghami wakadhālika nunjī l-mu'minīna ",
      verse: 2571,
      juz: 17,
      surah: 21,
    },
    {
      number: 89,
      image: "",
      text: "And Zakariya when he called (to) his Lord My Lord (Do) not leave me alone while You (are) [the] Best (of) the inheritors (89)",
      transliteration:
        "wazakariyyā idh nādā rabbahu rabbi lā tadharnī fardan wa-anta khayru l-wārithīna ",
      verse: 2572,
      juz: 17,
      surah: 21,
    },
    {
      number: 90,
      image: "",
      text: "So We responded to him and We bestowed on him Yahya and We cured for him his wife Indeed, they used (to) hasten in good deeds and they supplicate to Us (in) hope and fear and they were to Us humbly submissive (90)",
      transliteration:
        "fa-is'tajabnā lahu wawahabnā lahu yaḥyā wa-aṣlaḥnā lahu zawjahu innahum kānū yusāriʿūna fī l-khayrāti wayadʿūnanā raghaban warahaban wakānū lanā khāshiʿīna ",
      verse: 2573,
      juz: 17,
      surah: 21,
    },
    {
      number: 91,
      image: "",
      text: "And she who guarded her chastity so We breathed into her of Our Spirit and We made her and her son a sign for the worlds (91)",
      transliteration:
        "wa-allatī aḥṣanat farjahā fanafakhnā fīhā min rūḥinā wajaʿalnāhā wa-ib'nahā āyatan lil'ʿālamīna ",
      verse: 2574,
      juz: 17,
      surah: 21,
    },
    {
      number: 92,
      image: "",
      text: "Indeed this (is) your religion  religion one and I Am your Lord so worship Me (92)",
      transliteration:
        "inna hādhihi ummatukum ummatan wāḥidatan wa-anā rabbukum fa-uʿ'budūni ",
      verse: 2575,
      juz: 17,
      surah: 21,
    },
    {
      number: 93,
      image: "",
      text: "But they cut off their affair among themselves all to Us (will) return (93)",
      transliteration: "wataqaṭṭaʿū amrahum baynahum kullun ilaynā rājiʿūna ",
      verse: 2576,
      juz: 17,
      surah: 21,
    },
    {
      number: 94,
      image: "",
      text: "Then whoever does [of] [the] righteous deeds while he (is) a believer then not (will be) rejected [of] his effort And indeed, We of it (are) Recorders (94)",
      transliteration:
        "faman yaʿmal mina l-ṣāliḥāti wahuwa mu'minun falā kuf'rāna lisaʿyihi wa-innā lahu kātibūna ",
      verse: 2577,
      juz: 17,
      surah: 21,
    },
    {
      number: 95,
      image: "",
      text: "And (there is) prohibition upon a city which We have destroyed that they not will return (95)",
      transliteration: "waḥarāmun ʿalā qaryatin ahlaknāhā annahum lā yarjiʿūna ",
      verse: 2578,
      juz: 17,
      surah: 21,
    },
    {
      number: 96,
      image: "",
      text: "Until when has been opened (for) the Yajuj and Majuj and they from every elevation descend (96)",
      transliteration:
        "ḥattā idhā futiḥat yajūju wamajūju wahum min kulli ḥadabin yansilūna ",
      verse: 2579,
      juz: 17,
      surah: 21,
    },
    {
      number: 97,
      image: "",
      text: "And has approached the promise [the] true then behold [it] (are) staring (the) eyes (of) those who disbelieved O woe to us Verily we had been in heedlessness of this nay we were wrongdoers (97)",
      transliteration:
        "wa-iq'taraba l-waʿdu l-ḥaqu fa-idhā hiya shākhiṣatun abṣāru alladhīna kafarū yāwaylanā qad kunnā fī ghaflatin min hādhā bal kunnā ẓālimīna ",
      verse: 2580,
      juz: 17,
      surah: 21,
    },
    {
      number: 98,
      image: "",
      text: "Indeed, you and what you worship besides Allah besides Allah besides Allah (are) firewood (of) Hell You to it will come (98)",
      transliteration:
        "innakum wamā taʿbudūna min dūni l-lahi ḥaṣabu jahannama antum lahā wāridūna ",
      verse: 2581,
      juz: 17,
      surah: 21,
    },
    {
      number: 99,
      image: "",
      text: "If were these gods not they (would) have come to it And all therein will abide forever (99)",
      transliteration:
        "law kāna hāulāi ālihatan mā waradūhā wakullun fīhā khālidūna ",
      verse: 2582,
      juz: 17,
      surah: 21,
    },
    {
      number: 100,
      image: "",
      text: "For them therein (is) sighing and they therein not will hear (100)",
      transliteration: "lahum fīhā zafīrun wahum fīhā lā yasmaʿūna ",
      verse: 2583,
      juz: 17,
      surah: 21,
    },
    {
      number: 101,
      image: "",
      text: "Indeed those has gone forth for them from Us the good those from it (will be) removed far (101)",
      transliteration:
        "inna alladhīna sabaqat lahum minnā l-ḥus'nā ulāika ʿanhā mub'ʿadūna ",
      verse: 2584,
      juz: 17,
      surah: 21,
    },
    {
      number: 102,
      image: "",
      text: "Not they will hear (the) slightest sound of it and they in what desire their souls will abide forever (102)",
      transliteration:
        "lā yasmaʿūna ḥasīsahā wahum fī mā ish'tahat anfusuhum khālidūna ",
      verse: 2585,
      juz: 17,
      surah: 21,
    },
    {
      number: 103,
      image: "",
      text: "Not will grieve them the terror [the] greatest and will meet them the Angels This (is) your Day which you were promised (103)",
      transliteration:
        "lā yaḥzunuhumu l-fazaʿu l-akbaru watatalaqqāhumu l-malāikatu hādhā yawmukumu alladhī kuntum tūʿadūna ",
      verse: 2586,
      juz: 17,
      surah: 21,
    },
    {
      number: 104,
      image: "",
      text: "(The) Day We will fold the heaven like (the) folding (of) a scroll for records As We began (the) first creation We will repeat it a promise upon Us Indeed, We  We are (the) Doers (104)",
      transliteration:
        "yawma naṭwī l-samāa kaṭayyi l-sijili lil'kutubi kamā badanā awwala khalqin nuʿīduhu waʿdan ʿalaynā innā kunnā fāʿilīna ",
      verse: 2587,
      juz: 17,
      surah: 21,
    },
    {
      number: 105,
      image: "",
      text: "And verily We have written in the Scripture after after the mention that the earth  will inherit it My slaves the righteous (105)",
      transliteration:
        "walaqad katabnā fī l-zabūri min baʿdi l-dhik'ri anna l-arḍa yarithuhā ʿibādiya l-ṣāliḥūna ",
      verse: 2588,
      juz: 17,
      surah: 21,
    },
    {
      number: 106,
      image: "",
      text: "Indeed in this surely is a Message for a people worshippers (106)",
      transliteration: "inna fī hādhā labalāghan liqawmin ʿābidīna ",
      verse: 2589,
      juz: 17,
      surah: 21,
    },
    {
      number: 107,
      image: "",
      text: "And not We have sent you but (as) a mercy for the worlds (107)",
      transliteration: "wamā arsalnāka illā raḥmatan lil'ʿālamīna ",
      verse: 2590,
      juz: 17,
      surah: 21,
    },
    {
      number: 108,
      image: "",
      text: "Say Only it is revealed to me that your god (is) God One so will you submit (to Him) (108)",
      transliteration:
        "qul innamā yūḥā ilayya annamā ilāhukum ilāhun wāḥidun fahal antum mus'limūna ",
      verse: 2591,
      juz: 17,
      surah: 21,
    },
    {
      number: 109,
      image: "",
      text: "But if they turn away then say I (have) announced to you equally equally And not I know whether is near or far what you are promised (109)",
      transliteration:
        "fa-in tawallaw faqul ādhantukum ʿalā sawāin wa-in adrī aqarībun am baʿīdun mā tūʿadūna ",
      verse: 2592,
      juz: 17,
      surah: 21,
    },
    {
      number: 110,
      image: "",
      text: "Indeed, He knows the declared [of] [the] speech and He knows what you conceal (110)",
      transliteration:
        "innahu yaʿlamu l-jahra mina l-qawli wayaʿlamu mā taktumūna ",
      verse: 2593,
      juz: 17,
      surah: 21,
    },
    {
      number: 111,
      image: "",
      text: "And not I know perhaps it may be a trial for you and an enjoyment for a time (111)",
      transliteration:
        "wa-in adrī laʿallahu fit'natun lakum wamatāʿun ilā ḥīnin ",
      verse: 2594,
      juz: 17,
      surah: 21,
    },
    {
      number: 112,
      image: "",
      text: "He said My Lord judge in truth And our Lord (is) the Most Gracious the One Whose help is sought against what you attribute (112)",
      transliteration:
        "qāla rabbi uḥ'kum bil-ḥaqi warabbunā l-raḥmānu l-mus'taʿānu ʿalā mā taṣifūna ",
      verse: 2595,
      juz: 17,
      surah: 21,
    },
  ],
};
