import { Surah } from "../types/islam.js";

export const balad: Surah = {
  name: "Al-Balad",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "Nay I swear by this city (1)",
      transliteration: "lā uq'simu bihādhā l-baladi ",
      verse: 6024,
      juz: 30,
      surah: 90,
    },
    {
      number: 2,
      image: "",
      text: "And you (are) free (to dwell) in this city (2)",
      transliteration: "wa-anta ḥillun bihādhā l-baladi ",
      verse: 6025,
      juz: 30,
      surah: 90,
    },
    {
      number: 3,
      image: "",
      text: "And the begetter and what he begot (3)",
      transliteration: "wawālidin wamā walada ",
      verse: 6026,
      juz: 30,
      surah: 90,
    },
    {
      number: 4,
      image: "",
      text: "Certainly We have created man (to be) in hardship (4)",
      transliteration: "laqad khalaqnā l-insāna fī kabadin ",
      verse: 6027,
      juz: 30,
      surah: 90,
    },
    {
      number: 5,
      image: "",
      text: "Does he think that not has power over him anyone (5)",
      transliteration: "ayaḥsabu an lan yaqdira ʿalayhi aḥadun ",
      verse: 6028,
      juz: 30,
      surah: 90,
    },
    {
      number: 6,
      image: "",
      text: "He will say I have squandered wealth abundant (6)",
      transliteration: "yaqūlu ahlaktu mālan lubadan ",
      verse: 6029,
      juz: 30,
      surah: 90,
    },
    {
      number: 7,
      image: "",
      text: "Does he think that not sees him anyone (7)",
      transliteration: "ayaḥsabu an lam yarahu aḥadun ",
      verse: 6030,
      juz: 30,
      surah: 90,
    },
    {
      number: 8,
      image: "",
      text: "Have not We made for him two eyes (8)",
      transliteration: "alam najʿal lahu ʿaynayni ",
      verse: 6031,
      juz: 30,
      surah: 90,
    },
    {
      number: 9,
      image: "",
      text: "And a tongue and two lips (9)",
      transliteration: "walisānan washafatayni ",
      verse: 6032,
      juz: 30,
      surah: 90,
    },
    {
      number: 10,
      image: "",
      text: "And shown him the two ways (10)",
      transliteration: "wahadaynāhu l-najdayni ",
      verse: 6033,
      juz: 30,
      surah: 90,
    },
    {
      number: 11,
      image: "",
      text: "But not he has attempted the steep path (11)",
      transliteration: "falā iq'taḥama l-ʿaqabata ",
      verse: 6034,
      juz: 30,
      surah: 90,
    },
    {
      number: 12,
      image: "",
      text: "And what can make you know what the steep path (is) (12)",
      transliteration: "wamā adrāka mā l-ʿaqabatu ",
      verse: 6035,
      juz: 30,
      surah: 90,
    },
    {
      number: 13,
      image: "",
      text: "(It is) freeing a neck (13)",
      transliteration: "fakku raqabatin ",
      verse: 6036,
      juz: 30,
      surah: 90,
    },
    {
      number: 14,
      image: "",
      text: "Or feeding in a day of severe hunger (14)",
      transliteration: "aw iṭ'ʿāmun fī yawmin dhī masghabatin ",
      verse: 6037,
      juz: 30,
      surah: 90,
    },
    {
      number: 15,
      image: "",
      text: "An orphan of near relationship (15)",
      transliteration: "yatīman dhā maqrabatin ",
      verse: 6038,
      juz: 30,
      surah: 90,
    },
    {
      number: 16,
      image: "",
      text: "Or a needy person in misery (16)",
      transliteration: "aw mis'kīnan dhā matrabatin ",
      verse: 6039,
      juz: 30,
      surah: 90,
    },
    {
      number: 17,
      image: "",
      text: "Then he is of those who believe and enjoin (each other) to patience and enjoin (each other) to compassion (17)",
      transliteration:
        "thumma kāna mina alladhīna āmanū watawāṣaw bil-ṣabri watawāṣaw bil-marḥamati ",
      verse: 6040,
      juz: 30,
      surah: 90,
    },
    {
      number: 18,
      image: "",
      text: "Those (are the) companions (of) the right (hand) (18)",
      transliteration: "ulāika aṣḥābu l-maymanati ",
      verse: 6041,
      juz: 30,
      surah: 90,
    },
    {
      number: 19,
      image: "",
      text: "But those who disbelieve in Our Verses they (are the) companions (of) the left (hand) (19)",
      transliteration: "wa-alladhīna kafarū biāyātinā hum aṣḥābu l-mashamati ",
      verse: 6042,
      juz: 30,
      surah: 90,
    },
    {
      number: 20,
      image: "",
      text: "Over them (will be the) Fire closed in (20)",
      transliteration: "ʿalayhim nārun mu'ṣadatun ",
      verse: 6043,
      juz: 30,
      surah: 90,
    },
  ],
};
