import { Surah } from "../types/islam.js";

export const buruj: Surah = {
  name: "Al-Buruj",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "By the sky containing the constellations (1)",
      transliteration: "wal-samāi dhāti l-burūji ",
      verse: 5910,
      juz: 30,
      surah: 85,
    },
    {
      number: 2,
      image: "",
      text: "And the Day Promised (2)",
      transliteration: "wal-yawmi l-mawʿūdi ",
      verse: 5911,
      juz: 30,
      surah: 85,
    },
    {
      number: 3,
      image: "",
      text: "And (the) witness and what is witnessed (3)",
      transliteration: "washāhidin wamashhūdin ",
      verse: 5912,
      juz: 30,
      surah: 85,
    },
    {
      number: 4,
      image: "",
      text: "Destroyed were (the) companions (of) the pit (4)",
      transliteration: "qutila aṣḥābu l-ukh'dūdi ",
      verse: 5913,
      juz: 30,
      surah: 85,
    },
    {
      number: 5,
      image: "",
      text: "(Of) the fire full (of) the fuel (5)",
      transliteration: "al-nāri dhāti l-waqūdi ",
      verse: 5914,
      juz: 30,
      surah: 85,
    },
    {
      number: 6,
      image: "",
      text: "When they by it (were) sitting (6)",
      transliteration: "idh hum ʿalayhā quʿūdun ",
      verse: 5915,
      juz: 30,
      surah: 85,
    },
    {
      number: 7,
      image: "",
      text: "And they over what they were doing to the believers witnesses (7)",
      transliteration: "wahum ʿalā mā yafʿalūna bil-mu'minīna shuhūdun ",
      verse: 5916,
      juz: 30,
      surah: 85,
    },
    {
      number: 8,
      image: "",
      text: "And not they resented [of] them except that they believed in Allah the All-Mighty the Praiseworthy (8)",
      transliteration:
        "wamā naqamū min'hum illā an yu'minū bil-lahi l-ʿazīzi l-ḥamīdi ",
      verse: 5917,
      juz: 30,
      surah: 85,
    },
    {
      number: 9,
      image: "",
      text: "The One Who for Him (is) the dominion (of) the heavens and the earth and Allah on every thing (is) a Witness (9)",
      transliteration:
        "alladhī lahu mul'ku l-samāwāti wal-arḍi wal-lahu ʿalā kulli shayin shahīdun ",
      verse: 5918,
      juz: 30,
      surah: 85,
    },
    {
      number: 10,
      image: "",
      text: "Indeed those who persecuted the believing men and the believing women then not they repented then for them (is the) punishment (of) Hell and for them (is the) punishment (of) the Burning Fire (10)",
      transliteration:
        "inna alladhīna fatanū l-mu'minīna wal-mu'mināti thumma lam yatūbū falahum ʿadhābu jahannama walahum ʿadhābu l-ḥarīqi ",
      verse: 5919,
      juz: 30,
      surah: 85,
    },
    {
      number: 11,
      image: "",
      text: "Indeed those who believe and do the righteous deeds for them (will be) Gardens flow from underneath it the rivers That (is) the success the great (11)",
      transliteration:
        "inna alladhīna āmanū waʿamilū l-ṣāliḥāti lahum jannātun tajrī min taḥtihā l-anhāru dhālika l-fawzu l-kabīru ",
      verse: 5920,
      juz: 30,
      surah: 85,
    },
    {
      number: 12,
      image: "",
      text: "Indeed (the) Grip (of) your Lord (is) surely strong (12)",
      transliteration: "inna baṭsha rabbika lashadīdun ",
      verse: 5921,
      juz: 30,
      surah: 85,
    },
    {
      number: 13,
      image: "",
      text: "Indeed He He originates and repeats (13)",
      transliteration: "innahu huwa yub'di-u wayuʿīdu ",
      verse: 5922,
      juz: 30,
      surah: 85,
    },
    {
      number: 14,
      image: "",
      text: "And He (is) the Oft-Forgiving the Most Loving (14)",
      transliteration: "wahuwa l-ghafūru l-wadūdu ",
      verse: 5923,
      juz: 30,
      surah: 85,
    },
    {
      number: 15,
      image: "",
      text: "Owner (of) the Throne the Glorious (15)",
      transliteration: "dhū l-ʿarshi l-majīdu ",
      verse: 5924,
      juz: 30,
      surah: 85,
    },
    {
      number: 16,
      image: "",
      text: "Doer of what He intends (16)",
      transliteration: "faʿʿālun limā yurīdu ",
      verse: 5925,
      juz: 30,
      surah: 85,
    },
    {
      number: 17,
      image: "",
      text: "Has come to you (the) story (of) the hosts (17)",
      transliteration: "hal atāka ḥadīthu l-junūdi ",
      verse: 5926,
      juz: 30,
      surah: 85,
    },
    {
      number: 18,
      image: "",
      text: "Firaun and Thamud (18)",
      transliteration: "fir'ʿawna wathamūda ",
      verse: 5927,
      juz: 30,
      surah: 85,
    },
    {
      number: 19,
      image: "",
      text: "Nay Those who disbelieve (are) in denial (19)",
      transliteration: "bali alladhīna kafarū fī takdhībin ",
      verse: 5928,
      juz: 30,
      surah: 85,
    },
    {
      number: 20,
      image: "",
      text: "But Allah from behind them encompasses (20)",
      transliteration: "wal-lahu min warāihim muḥīṭun ",
      verse: 5929,
      juz: 30,
      surah: 85,
    },
    {
      number: 21,
      image: "",
      text: "Nay It (is) a Quran Glorious (21)",
      transliteration: "bal huwa qur'ānun majīdun ",
      verse: 5930,
      juz: 30,
      surah: 85,
    },
    {
      number: 22,
      image: "",
      text: "In a Tablet Guarded (22)",
      transliteration: "fī lawḥin maḥfūẓin ",
      verse: 5931,
      juz: 30,
      surah: 85,
    },
  ],
};
