import { Surah } from "../types/islam.js";

export const dhariyat: Surah = {
  name: "Adh-Dhariyat",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "By those scattering dispersing (1)",
      transliteration: "wal-dhāriyāti dharwan ",
      verse: 4676,
      juz: 26,
      surah: 51,
    },
    {
      number: 2,
      image: "",
      text: "And those carrying a load (2)",
      transliteration: "fal-ḥāmilāti wiq'ran ",
      verse: 4677,
      juz: 26,
      surah: 51,
    },
    {
      number: 3,
      image: "",
      text: "And those sailing (with) ease (3)",
      transliteration: "fal-jāriyāti yus'ran ",
      verse: 4678,
      juz: 26,
      surah: 51,
    },
    {
      number: 4,
      image: "",
      text: "And those distributing Command (4)",
      transliteration: "fal-muqasimāti amran ",
      verse: 4679,
      juz: 26,
      surah: 51,
    },
    {
      number: 5,
      image: "",
      text: "Indeed, what you are promised (is) surely true (5)",
      transliteration: "innamā tūʿadūna laṣādiqun ",
      verse: 4680,
      juz: 26,
      surah: 51,
    },
    {
      number: 6,
      image: "",
      text: "And indeed the Judgment (is) surely to occur (6)",
      transliteration: "wa-inna l-dīna lawāqiʿun ",
      verse: 4681,
      juz: 26,
      surah: 51,
    },
    {
      number: 7,
      image: "",
      text: "By the heaven full of pathways (7)",
      transliteration: "wal-samāi dhāti l-ḥubuki ",
      verse: 4682,
      juz: 26,
      surah: 51,
    },
    {
      number: 8,
      image: "",
      text: "Indeed, you (are) surely in a speech differing (8)",
      transliteration: "innakum lafī qawlin mukh'talifin ",
      verse: 4683,
      juz: 26,
      surah: 51,
    },
    {
      number: 9,
      image: "",
      text: "Deluded away from it (is he) who is deluded (9)",
      transliteration: "yu'faku ʿanhu man ufika ",
      verse: 4684,
      juz: 26,
      surah: 51,
    },
    {
      number: 10,
      image: "",
      text: "Cursed be the liars (10)",
      transliteration: "qutila l-kharāṣūna ",
      verse: 4685,
      juz: 26,
      surah: 51,
    },
    {
      number: 11,
      image: "",
      text: "Those who [they] (are) in flood (of) heedlessness (11)",
      transliteration: "alladhīna hum fī ghamratin sāhūna ",
      verse: 4686,
      juz: 26,
      surah: 51,
    },
    {
      number: 12,
      image: "",
      text: "They ask When (is the) Day (of) Judgment (12)",
      transliteration: "yasalūna ayyāna yawmu l-dīni ",
      verse: 4687,
      juz: 26,
      surah: 51,
    },
    {
      number: 13,
      image: "",
      text: "A Day they over the Fire will be tried (13)",
      transliteration: "yawma hum ʿalā l-nāri yuf'tanūna ",
      verse: 4688,
      juz: 26,
      surah: 51,
    },
    {
      number: 14,
      image: "",
      text: "Taste your trial This (is) what you were for it seeking to hasten (14)",
      transliteration:
        "dhūqū fit'natakum hādhā alladhī kuntum bihi tastaʿjilūna ",
      verse: 4689,
      juz: 26,
      surah: 51,
    },
    {
      number: 15,
      image: "",
      text: "Indeed the righteous (will be) in Gardens and springs (15)",
      transliteration: "inna l-mutaqīna fī jannātin waʿuyūnin ",
      verse: 4690,
      juz: 26,
      surah: 51,
    },
    {
      number: 16,
      image: "",
      text: "Taking what their Lord has given them their Lord has given them Indeed, they were before that good-doers (16)",
      transliteration:
        "ākhidhīna mā ātāhum rabbuhum innahum kānū qabla dhālika muḥ'sinīna ",
      verse: 4691,
      juz: 26,
      surah: 51,
    },
    {
      number: 17,
      image: "",
      text: "They used to little of the night [what] sleep (17)",
      transliteration: "kānū qalīlan mina al-layli mā yahjaʿūna ",
      verse: 4692,
      juz: 26,
      surah: 51,
    },
    {
      number: 18,
      image: "",
      text: "And in the hours before dawn they would ask forgiveness (18)",
      transliteration: "wabil-asḥāri hum yastaghfirūna ",
      verse: 4693,
      juz: 26,
      surah: 51,
    },
    {
      number: 19,
      image: "",
      text: "And in their wealth (was the) right (of) those who asked and the deprived (19)",
      transliteration: "wafī amwālihim ḥaqqun lilssāili wal-maḥrūmi ",
      verse: 4694,
      juz: 26,
      surah: 51,
    },
    {
      number: 20,
      image: "",
      text: "And in the earth (are) signs for those who are certain (20)",
      transliteration: "wafī l-arḍi āyātun lil'mūqinīna ",
      verse: 4695,
      juz: 26,
      surah: 51,
    },
    {
      number: 21,
      image: "",
      text: "And in yourselves Then will not you see (21)",
      transliteration: "wafī anfusikum afalā tub'ṣirūna ",
      verse: 4696,
      juz: 26,
      surah: 51,
    },
    {
      number: 22,
      image: "",
      text: "And in the heaven (is) your provision and what you are promised (22)",
      transliteration: "wafī l-samāi riz'qukum wamā tūʿadūna ",
      verse: 4697,
      juz: 26,
      surah: 51,
    },
    {
      number: 23,
      image: "",
      text: "Then by (the) Lord (of) the heaven and the earth indeed, it (is) surely (the) truth (just) as [what] you speak (23)",
      transliteration:
        "fawarabbi l-samāi wal-arḍi innahu laḥaqqun mith'la mā annakum tanṭiqūna ",
      verse: 4698,
      juz: 26,
      surah: 51,
    },
    {
      number: 24,
      image: "",
      text: "Has reached you (the) narration (of the) guests (of) Ibrahim the honored (24)",
      transliteration: "hal atāka ḥadīthu ḍayfi ib'rāhīma l-muk'ramīna ",
      verse: 4699,
      juz: 26,
      surah: 51,
    },
    {
      number: 25,
      image: "",
      text: "When they entered upon him and said Peace He said Peace a people unknown (25)",
      transliteration:
        "idh dakhalū ʿalayhi faqālū salāman qāla salāmun qawmun munkarūna ",
      verse: 4700,
      juz: 26,
      surah: 51,
    },
    {
      number: 26,
      image: "",
      text: "Then he went to his household and came with a calf fat (26)",
      transliteration: "farāgha ilā ahlihi fajāa biʿij'lin samīnin ",
      verse: 4701,
      juz: 26,
      surah: 51,
    },
    {
      number: 27,
      image: "",
      text: "And he placed it near [to] them he said Will not you eat (27)",
      transliteration: "faqarrabahu ilayhim qāla alā takulūna ",
      verse: 4702,
      juz: 26,
      surah: 51,
    },
    {
      number: 28,
      image: "",
      text: "Then he felt from them a fear They said (Do) not fear and they gave him glad tidings of a son learned (28)",
      transliteration:
        "fa-awjasa min'hum khīfatan qālū lā takhaf wabasharūhu bighulāmin ʿalīmin ",
      verse: 4703,
      juz: 26,
      surah: 51,
    },
    {
      number: 29,
      image: "",
      text: "Then came forward his wife with a loud voice and struck her face and she said An old woman barren (29)",
      transliteration:
        "fa-aqbalati im'ra-atuhu fī ṣarratin faṣakkat wajhahā waqālat ʿajūzun ʿaqīmun ",
      verse: 4704,
      juz: 26,
      surah: 51,
    },
    {
      number: 30,
      image: "",
      text: "They said Thus said your Lord Indeed, He [He] (is) the All-Wise the All-Knower (30)",
      transliteration:
        "qālū kadhāliki qāla rabbuki innahu huwa l-ḥakīmu l-ʿalīmu ",
      verse: 4705,
      juz: 26,
      surah: 51,
    },
    {
      number: 31,
      image: "",
      text: "He said Then what (is) your mission O messengers O messengers (31)",
      transliteration: "qāla famā khaṭbukum ayyuhā l-mur'salūna ",
      verse: 4706,
      juz: 27,
      surah: 51,
    },
    {
      number: 32,
      image: "",
      text: "They said Indeed, we [we] have been sent to a people criminal (32)",
      transliteration: "qālū innā ur'sil'nā ilā qawmin muj'rimīna ",
      verse: 4707,
      juz: 27,
      surah: 51,
    },
    {
      number: 33,
      image: "",
      text: "That we may send down upon them stones of clay (33)",
      transliteration: "linur'sila ʿalayhim ḥijāratan min ṭīnin ",
      verse: 4708,
      juz: 27,
      surah: 51,
    },
    {
      number: 34,
      image: "",
      text: "Marked by your Lord by your Lord for the transgressors (34)",
      transliteration: "musawwamatan ʿinda rabbika lil'mus'rifīna ",
      verse: 4709,
      juz: 27,
      surah: 51,
    },
    {
      number: 35,
      image: "",
      text: "Then We brought out (those) who were therein of the believers (35)",
      transliteration: "fa-akhrajnā man kāna fīhā mina l-mu'minīna ",
      verse: 4710,
      juz: 27,
      surah: 51,
    },
    {
      number: 36,
      image: "",
      text: "But not We found therein other than a house of the Muslims (36)",
      transliteration: "famā wajadnā fīhā ghayra baytin mina l-mus'limīna ",
      verse: 4711,
      juz: 27,
      surah: 51,
    },
    {
      number: 37,
      image: "",
      text: "And We left therein a Sign for those who fear the punishment the painful (37)",
      transliteration:
        "wataraknā fīhā āyatan lilladhīna yakhāfūna l-ʿadhāba l-alīma ",
      verse: 4712,
      juz: 27,
      surah: 51,
    },
    {
      number: 38,
      image: "",
      text: "And in Musa when We sent him to Firaun with an authority clear (38)",
      transliteration:
        "wafī mūsā idh arsalnāhu ilā fir'ʿawna bisul'ṭānin mubīnin ",
      verse: 4713,
      juz: 27,
      surah: 51,
    },
    {
      number: 39,
      image: "",
      text: "But he turned away with his supporters and said A magician or a madman (39)",
      transliteration: "fatawallā biruk'nihi waqāla sāḥirun aw majnūnun ",
      verse: 4714,
      juz: 27,
      surah: 51,
    },
    {
      number: 40,
      image: "",
      text: "So We took him and his hosts and threw them into the sea while he (was) blameworthy (40)",
      transliteration:
        "fa-akhadhnāhu wajunūdahu fanabadhnāhum fī l-yami wahuwa mulīmun ",
      verse: 4715,
      juz: 27,
      surah: 51,
    },
    {
      number: 41,
      image: "",
      text: "And in Aad when We sent against them the wind the barren (41)",
      transliteration: "wafī ʿādin idh arsalnā ʿalayhimu l-rīḥa l-ʿaqīma ",
      verse: 4716,
      juz: 27,
      surah: 51,
    },
    {
      number: 42,
      image: "",
      text: "Not it left any thing it came upon it but it made it like disintegrated ruins (42)",
      transliteration:
        "mā tadharu min shayin atat ʿalayhi illā jaʿalathu kal-ramīmi ",
      verse: 4717,
      juz: 27,
      surah: 51,
    },
    {
      number: 43,
      image: "",
      text: "And in Thamud when was said to them Enjoy (yourselves) for a time (43)",
      transliteration: "wafī thamūda idh qīla lahum tamattaʿū ḥattā ḥīnin ",
      verse: 4718,
      juz: 27,
      surah: 51,
    },
    {
      number: 44,
      image: "",
      text: "But they rebelled against (the) Command (of) their Lord so seized them the thunderbolt while they were looking (44)",
      transliteration:
        "faʿataw ʿan amri rabbihim fa-akhadhathumu l-ṣāʿiqatu wahum yanẓurūna ",
      verse: 4719,
      juz: 27,
      surah: 51,
    },
    {
      number: 45,
      image: "",
      text: "Then not they were able to [of] stand and not they could help themselves (45)",
      transliteration: "famā is'taṭāʿū min qiyāmin wamā kānū muntaṣirīna ",
      verse: 4720,
      juz: 27,
      surah: 51,
    },
    {
      number: 46,
      image: "",
      text: "And (the) people (of) Nuh before before indeed, they were a people defiantly disobedient (46)",
      transliteration: "waqawma nūḥin min qablu innahum kānū qawman fāsiqīna ",
      verse: 4721,
      juz: 27,
      surah: 51,
    },
    {
      number: 47,
      image: "",
      text: "And the heaven We constructed it with strength and indeed, We (are) surely (its) Expanders (47)",
      transliteration: "wal-samāa banaynāhā bi-aydin wa-innā lamūsiʿūna ",
      verse: 4722,
      juz: 27,
      surah: 51,
    },
    {
      number: 48,
      image: "",
      text: "And the earth We have spread it how excellent (are) the Spreaders (48)",
      transliteration: "wal-arḍa farashnāhā faniʿ'ma l-māhidūna ",
      verse: 4723,
      juz: 27,
      surah: 51,
    },
    {
      number: 49,
      image: "",
      text: "And of every thing We have created pairs so that you may remember (49)",
      transliteration:
        "wamin kulli shayin khalaqnā zawjayni laʿallakum tadhakkarūna ",
      verse: 4724,
      juz: 27,
      surah: 51,
    },
    {
      number: 50,
      image: "",
      text: "So flee to Allah indeed, I am to you from Him a warner clear (50)",
      transliteration: "fafirrū ilā l-lahi innī lakum min'hu nadhīrun mubīnun ",
      verse: 4725,
      juz: 27,
      surah: 51,
    },
    {
      number: 51,
      image: "",
      text: "And (do) not make with Allah god another Indeed, I am to you from Him a warner clear (51)",
      transliteration:
        "walā tajʿalū maʿa l-lahi ilāhan ākhara innī lakum min'hu nadhīrun mubīnun ",
      verse: 4726,
      juz: 27,
      surah: 51,
    },
    {
      number: 52,
      image: "",
      text: "Likewise not came (to) those before them before them any Messenger but they said A magician or a madman (52)",
      transliteration:
        "kadhālika mā atā alladhīna min qablihim min rasūlin illā qālū sāḥirun aw majnūnun ",
      verse: 4727,
      juz: 27,
      surah: 51,
    },
    {
      number: 53,
      image: "",
      text: "Have they transmitted it to them Have they transmitted it to them Nay they (are) a people transgressing (53)",
      transliteration: "atawāṣaw bihi bal hum qawmun ṭāghūna ",
      verse: 4728,
      juz: 27,
      surah: 51,
    },
    {
      number: 54,
      image: "",
      text: "So turn away from them for not you (are) to be blamed (54)",
      transliteration: "fatawalla ʿanhum famā anta bimalūmin ",
      verse: 4729,
      juz: 27,
      surah: 51,
    },
    {
      number: 55,
      image: "",
      text: "And remind for indeed the reminder benefits the believers (55)",
      transliteration: "wadhakkir fa-inna l-dhik'rā tanfaʿu l-mu'minīna ",
      verse: 4730,
      juz: 27,
      surah: 51,
    },
    {
      number: 56,
      image: "",
      text: "And not I have created the jinn and the mankind except that they worship Me (56)",
      transliteration: "wamā khalaqtu l-jina wal-insa illā liyaʿbudūni ",
      verse: 4731,
      juz: 27,
      surah: 51,
    },
    {
      number: 57,
      image: "",
      text: "Not I want from them any provision and not I want that they (should) feed Me (57)",
      transliteration: "mā urīdu min'hum min riz'qin wamā urīdu an yuṭ'ʿimūni ",
      verse: 4732,
      juz: 27,
      surah: 51,
    },
    {
      number: 58,
      image: "",
      text: "Indeed Allah He (is) the All-Provider Possessor (of) Power the Strong (58)",
      transliteration: "inna l-laha huwa l-razāqu dhū l-quwati l-matīnu ",
      verse: 4733,
      juz: 27,
      surah: 51,
    },
    {
      number: 59,
      image: "",
      text: "So indeed for those who do wrong (is) a portion like (the) portion (of) their companions so let them not ask Me to hasten so let them not ask Me to hasten (59)",
      transliteration:
        "fa-inna lilladhīna ẓalamū dhanūban mith'la dhanūbi aṣḥābihim falā yastaʿjilūni ",
      verse: 4734,
      juz: 27,
      surah: 51,
    },
    {
      number: 60,
      image: "",
      text: "Then woe to those who disbelieve from their Day which they are promised (60)",
      transliteration:
        "fawaylun lilladhīna kafarū min yawmihimu alladhī yūʿadūna ",
      verse: 4735,
      juz: 27,
      surah: 51,
    },
  ],
};
