import { Surah } from "../types/islam.js";

export const duhaa: Surah = {
  name: "Ad-Duhaa",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "By the morning brightness (1)",
      transliteration: "wal-ḍuḥā ",
      verse: 6080,
      juz: 30,
      surah: 93,
    },
    {
      number: 2,
      image: "",
      text: "And the night when it covers with darkness (2)",
      transliteration: "wa-al-layli idhā sajā ",
      verse: 6081,
      juz: 30,
      surah: 93,
    },
    {
      number: 3,
      image: "",
      text: "Not has forsaken you your Lord and not He is displeased (3)",
      transliteration: "mā waddaʿaka rabbuka wamā qalā ",
      verse: 6082,
      juz: 30,
      surah: 93,
    },
    {
      number: 4,
      image: "",
      text: "And surely the Hereafter (is) better for you than the first (4)",
      transliteration: "walalākhiratu khayrun laka mina l-ūlā ",
      verse: 6083,
      juz: 30,
      surah: 93,
    },
    {
      number: 5,
      image: "",
      text: "And soon will give you your Lord then you will be satisfied (5)",
      transliteration: "walasawfa yuʿ'ṭīka rabbuka fatarḍā ",
      verse: 6084,
      juz: 30,
      surah: 93,
    },
    {
      number: 6,
      image: "",
      text: "Did not He find you an orphan and give shelter (6)",
      transliteration: "alam yajid'ka yatīman faāwā ",
      verse: 6085,
      juz: 30,
      surah: 93,
    },
    {
      number: 7,
      image: "",
      text: "And He found you lost so He guided (7)",
      transliteration: "wawajadaka ḍāllan fahadā ",
      verse: 6086,
      juz: 30,
      surah: 93,
    },
    {
      number: 8,
      image: "",
      text: "And He found you in need so He made self-sufficient (8)",
      transliteration: "wawajadaka ʿāilan fa-aghnā ",
      verse: 6087,
      juz: 30,
      surah: 93,
    },
    {
      number: 9,
      image: "",
      text: "So as for the orphan then (do) not oppress (9)",
      transliteration: "fa-ammā l-yatīma falā taqhar ",
      verse: 6088,
      juz: 30,
      surah: 93,
    },
    {
      number: 10,
      image: "",
      text: "And as for one who asks then (do) not repel (10)",
      transliteration: "wa-ammā l-sāila falā tanhar ",
      verse: 6089,
      juz: 30,
      surah: 93,
    },
    {
      number: 11,
      image: "",
      text: "But as for (the) Favor (of) your Lord narrate (11)",
      transliteration: "wa-ammā biniʿ'mati rabbika faḥaddith ",
      verse: 6090,
      juz: 30,
      surah: 93,
    },
  ],
};
