import { Surah } from "../types/islam.js";

export const dukhan: Surah = {
  name: "Ad-Dukhan",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "Ha Meem (1)",
      transliteration: "hha-meem ",
      verse: 4415,
      juz: 25,
      surah: 44,
    },
    {
      number: 2,
      image: "",
      text: "By the Book the clear (2)",
      transliteration: "wal-kitābi l-mubīni ",
      verse: 4416,
      juz: 25,
      surah: 44,
    },
    {
      number: 3,
      image: "",
      text: "Indeed, We revealed it in a Night Blessed Indeed, We [We] are (ever) warning (3)",
      transliteration:
        "innā anzalnāhu fī laylatin mubārakatin innā kunnā mundhirīna ",
      verse: 4417,
      juz: 25,
      surah: 44,
    },
    {
      number: 4,
      image: "",
      text: "Therein is made distinct every affair wise (4)",
      transliteration: "fīhā yuf'raqu kullu amrin ḥakīmin ",
      verse: 4418,
      juz: 25,
      surah: 44,
    },
    {
      number: 5,
      image: "",
      text: "A command from Us Indeed, We [We] are (ever) sending (5)",
      transliteration: "amran min ʿindinā innā kunnā mur'silīna ",
      verse: 4419,
      juz: 25,
      surah: 44,
    },
    {
      number: 6,
      image: "",
      text: "As Mercy from your Lord Indeed, He [He] (is) the All-Hearer the All-Knower (6)",
      transliteration: "raḥmatan min rabbika innahu huwa l-samīʿu l-ʿalīmu ",
      verse: 4420,
      juz: 25,
      surah: 44,
    },
    {
      number: 7,
      image: "",
      text: "Lord (of) the heavens and the earth and whatever (is) between both of them if you are certain (7)",
      transliteration:
        "rabbi l-samāwāti wal-arḍi wamā baynahumā in kuntum mūqinīna ",
      verse: 4421,
      juz: 25,
      surah: 44,
    },
    {
      number: 8,
      image: "",
      text: "(There is) no god except Him He gives life and causes death your Lord and (the) Lord (of) your fathers the former (8)",
      transliteration:
        "lā ilāha illā huwa yuḥ'yī wayumītu rabbukum warabbu ābāikumu l-awalīna ",
      verse: 4422,
      juz: 25,
      surah: 44,
    },
    {
      number: 9,
      image: "",
      text: "Nay they (are) in doubt  playing (9)",
      transliteration: "bal hum fī shakkin yalʿabūna ",
      verse: 4423,
      juz: 25,
      surah: 44,
    },
    {
      number: 10,
      image: "",
      text: "Then watch (for the) Day (when) will bring the sky smoke visible (10)",
      transliteration: "fa-ir'taqib yawma tatī l-samāu bidukhānin mubīnin ",
      verse: 4424,
      juz: 25,
      surah: 44,
    },
    {
      number: 11,
      image: "",
      text: "Enveloping the people This (will be) a punishment painful (11)",
      transliteration: "yaghshā l-nāsa hādhā ʿadhābun alīmun ",
      verse: 4425,
      juz: 25,
      surah: 44,
    },
    {
      number: 12,
      image: "",
      text: "Our Lord Remove from us the punishment indeed, we (are) believers (12)",
      transliteration: "rabbanā ik'shif ʿannā l-ʿadhāba innā mu'minūna ",
      verse: 4426,
      juz: 25,
      surah: 44,
    },
    {
      number: 13,
      image: "",
      text: "How can (there be) for them the reminder when verily had come to them a Messenger clear (13)",
      transliteration: "annā lahumu l-dhik'rā waqad jāahum rasūlun mubīnun ",
      verse: 4427,
      juz: 25,
      surah: 44,
    },
    {
      number: 14,
      image: "",
      text: "Then they turned away from him and said One taught a mad man (14)",
      transliteration: "thumma tawallaw ʿanhu waqālū muʿallamun majnūnun ",
      verse: 4428,
      juz: 25,
      surah: 44,
    },
    {
      number: 15,
      image: "",
      text: "Indeed, We (will) remove the punishment a little indeed, you (will) return (15)",
      transliteration: "innā kāshifū l-ʿadhābi qalīlan innakum ʿāidūna ",
      verse: 4429,
      juz: 25,
      surah: 44,
    },
    {
      number: 16,
      image: "",
      text: "(The) Day We will seize (with) the seizure the greatest indeed, We (will) take retribution (16)",
      transliteration: "yawma nabṭishu l-baṭshata l-kub'rā innā muntaqimūna ",
      verse: 4430,
      juz: 25,
      surah: 44,
    },
    {
      number: 17,
      image: "",
      text: "And certainly We tried before them (the) people (of) Firaun and came to them a Messenger noble (17)",
      transliteration:
        "walaqad fatannā qablahum qawma fir'ʿawna wajāahum rasūlun karīmun ",
      verse: 4431,
      juz: 25,
      surah: 44,
    },
    {
      number: 18,
      image: "",
      text: "That Deliver to me (the) servants (of) Allah Indeed, I am to you a Messenger trustworthy (18)",
      transliteration: "an addū ilayya ʿibāda l-lahi innī lakum rasūlun amīnun ",
      verse: 4432,
      juz: 25,
      surah: 44,
    },
    {
      number: 19,
      image: "",
      text: "And that (do) not exalt yourselves against Allah Indeed, I [I] have come to you with an authority clear (19)",
      transliteration:
        "wa-an lā taʿlū ʿalā l-lahi innī ātīkum bisul'ṭānin mubīnin ",
      verse: 4433,
      juz: 25,
      surah: 44,
    },
    {
      number: 20,
      image: "",
      text: "And indeed, I [I] seek refuge with my Lord and your Lord lest you stone me (20)",
      transliteration: "wa-innī ʿudh'tu birabbī warabbikum an tarjumūni ",
      verse: 4434,
      juz: 25,
      surah: 44,
    },
    {
      number: 21,
      image: "",
      text: "And if not you believe me then leave me alone (21)",
      transliteration: "wa-in lam tu'minū lī fa-iʿ'tazilūni ",
      verse: 4435,
      juz: 25,
      surah: 44,
    },
    {
      number: 22,
      image: "",
      text: "So he called his Lord That these (are) a people criminals (22)",
      transliteration: "fadaʿā rabbahu anna hāulāi qawmun muj'rimūna ",
      verse: 4436,
      juz: 25,
      surah: 44,
    },
    {
      number: 23,
      image: "",
      text: 'Then "Set out with My slaves (by) night Indeed, you (will be) followed (23)',
      transliteration: "fa-asri biʿibādī laylan innakum muttabaʿūna ",
      verse: 4437,
      juz: 25,
      surah: 44,
    },
    {
      number: 24,
      image: "",
      text: "And leave the sea at rest Indeed, they (are) an army (to be) drowned (24)",
      transliteration: "wa-ut'ruki l-baḥra rahwan innahum jundun mugh'raqūna ",
      verse: 4438,
      juz: 25,
      surah: 44,
    },
    {
      number: 25,
      image: "",
      text: "How many (did) they leave of gardens and springs (25)",
      transliteration: "kam tarakū min jannātin waʿuyūnin ",
      verse: 4439,
      juz: 25,
      surah: 44,
    },
    {
      number: 26,
      image: "",
      text: "And cornfields and places noble (26)",
      transliteration: "wazurūʿin wamaqāmin karīmin ",
      verse: 4440,
      juz: 25,
      surah: 44,
    },
    {
      number: 27,
      image: "",
      text: "And pleasant things they used to therein take delight (27)",
      transliteration: "wanaʿmatin kānū fīhā fākihīna ",
      verse: 4441,
      juz: 25,
      surah: 44,
    },
    {
      number: 28,
      image: "",
      text: "Thus And We made it (an) inherit(ance) (for) a people another (28)",
      transliteration: "kadhālika wa-awrathnāhā qawman ākharīna ",
      verse: 4442,
      juz: 25,
      surah: 44,
    },
    {
      number: 29,
      image: "",
      text: "And not wept for them the heaven and the earth and not they were given respite (29)",
      transliteration:
        "famā bakat ʿalayhimu l-samāu wal-arḍu wamā kānū munẓarīna ",
      verse: 4443,
      juz: 25,
      surah: 44,
    },
    {
      number: 30,
      image: "",
      text: "And certainly We saved (the) Children of Israel (the) Children of Israel from the punishment the humiliating (30)",
      transliteration: "walaqad najjaynā banī is'rāīla mina l-ʿadhābi l-muhīni ",
      verse: 4444,
      juz: 25,
      surah: 44,
    },
    {
      number: 31,
      image: "",
      text: "From Firaun Indeed, he was arrogant among the transgressors (31)",
      transliteration: "min fir'ʿawna innahu kāna ʿāliyan mina l-mus'rifīna ",
      verse: 4445,
      juz: 25,
      surah: 44,
    },
    {
      number: 32,
      image: "",
      text: "And certainly We chose them by knowledge over the worlds (32)",
      transliteration: "walaqadi ikh'tarnāhum ʿalā ʿil'min ʿalā l-ʿālamīna ",
      verse: 4446,
      juz: 25,
      surah: 44,
    },
    {
      number: 33,
      image: "",
      text: "And We gave them of the Signs that in it (was) a trial clear (33)",
      transliteration: "waātaynāhum mina l-āyāti mā fīhi balāon mubīnun ",
      verse: 4447,
      juz: 25,
      surah: 44,
    },
    {
      number: 34,
      image: "",
      text: "Indeed these surely, they say (34)",
      transliteration: "inna hāulāi layaqūlūna ",
      verse: 4448,
      juz: 25,
      surah: 44,
    },
    {
      number: 35,
      image: "",
      text: "Not it (is) but our death the first and not we (will be) raised again (35)",
      transliteration: "in hiya illā mawtatunā l-ūlā wamā naḥnu bimunsharīna ",
      verse: 4449,
      juz: 25,
      surah: 44,
    },
    {
      number: 36,
      image: "",
      text: "Then bring our forefathers if you are truthful (36)",
      transliteration: "fatū biābāinā in kuntum ṣādiqīna ",
      verse: 4450,
      juz: 25,
      surah: 44,
    },
    {
      number: 37,
      image: "",
      text: "Are they better or (the) people (of) Tubba and those before them before them We destroyed them indeed, they were criminals (37)",
      transliteration:
        "ahum khayrun am qawmu tubbaʿin wa-alladhīna min qablihim ahlaknāhum innahum kānū muj'rimīna ",
      verse: 4451,
      juz: 25,
      surah: 44,
    },
    {
      number: 38,
      image: "",
      text: "And not We created the heavens and the earth and whatever (is) between them (in) play (38)",
      transliteration:
        "wamā khalaqnā l-samāwāti wal-arḍa wamā baynahumā lāʿibīna ",
      verse: 4452,
      juz: 25,
      surah: 44,
    },
    {
      number: 39,
      image: "",
      text: "Not We created both of them but in [the] truth but most of them (do) not know (39)",
      transliteration:
        "mā khalaqnāhumā illā bil-ḥaqi walākinna aktharahum lā yaʿlamūna ",
      verse: 4453,
      juz: 25,
      surah: 44,
    },
    {
      number: 40,
      image: "",
      text: "Indeed (the) Day of Judgment (the) Day of Judgment (is) an appointed term for them all (40)",
      transliteration: "inna yawma l-faṣli mīqātuhum ajmaʿīna ",
      verse: 4454,
      juz: 25,
      surah: 44,
    },
    {
      number: 41,
      image: "",
      text: "(The) Day not will avail a relation for a relation anything and not they will be helped (41)",
      transliteration:
        "yawma lā yugh'nī mawlan ʿan mawlan shayan walā hum yunṣarūna ",
      verse: 4455,
      juz: 25,
      surah: 44,
    },
    {
      number: 42,
      image: "",
      text: "Except (on) whom Allah has mercy Allah has mercy Indeed, He [He] (is) the All-Mighty the Most Merciful (42)",
      transliteration: "illā man raḥima l-lahu innahu huwa l-ʿazīzu l-raḥīmu ",
      verse: 4456,
      juz: 25,
      surah: 44,
    },
    {
      number: 43,
      image: "",
      text: "Indeed (the) tree (of) Zaqqum (43)",
      transliteration: "inna shajarata l-zaqūmi ",
      verse: 4457,
      juz: 25,
      surah: 44,
    },
    {
      number: 44,
      image: "",
      text: "(Will be) food (of) the sinner(s) (44)",
      transliteration: "ṭaʿāmu l-athīmi ",
      verse: 4458,
      juz: 25,
      surah: 44,
    },
    {
      number: 45,
      image: "",
      text: "Like the murky oil it will boil in the bellies (45)",
      transliteration: "kal-muh'li yaghlī fī l-buṭūni ",
      verse: 4459,
      juz: 25,
      surah: 44,
    },
    {
      number: 46,
      image: "",
      text: "Like boiling (of) scalding water (46)",
      transliteration: "kaghalyi l-ḥamīmi ",
      verse: 4460,
      juz: 25,
      surah: 44,
    },
    {
      number: 47,
      image: "",
      text: "Seize him and drag him into (the) midst (of) the Hellfire (47)",
      transliteration: "khudhūhu fa-iʿ'tilūhu ilā sawāi l-jaḥīmi ",
      verse: 4461,
      juz: 25,
      surah: 44,
    },
    {
      number: 48,
      image: "",
      text: "Then pour over his head of (the) punishment (of) the scalding water (48)",
      transliteration: "thumma ṣubbū fawqa rasihi min ʿadhābi l-ḥamīmi ",
      verse: 4462,
      juz: 25,
      surah: 44,
    },
    {
      number: 49,
      image: "",
      text: "Taste Indeed, you [you] (were) the mighty the noble (49)",
      transliteration: "dhuq innaka anta l-ʿazīzu l-karīmu ",
      verse: 4463,
      juz: 25,
      surah: 44,
    },
    {
      number: 50,
      image: "",
      text: "Indeed this (is) what you used to [about it] doubt (50)",
      transliteration: "inna hādhā mā kuntum bihi tamtarūna ",
      verse: 4464,
      juz: 25,
      surah: 44,
    },
    {
      number: 51,
      image: "",
      text: "Indeed the righteous (will be) in a place secure (51)",
      transliteration: "inna l-mutaqīna fī maqāmin amīnin ",
      verse: 4465,
      juz: 25,
      surah: 44,
    },
    {
      number: 52,
      image: "",
      text: "In gardens and springs (52)",
      transliteration: "fī jannātin waʿuyūnin ",
      verse: 4466,
      juz: 25,
      surah: 44,
    },
    {
      number: 53,
      image: "",
      text: "Wearing garments of fine silk and heavy silk facing each other (53)",
      transliteration: "yalbasūna min sundusin wa-is'tabraqin mutaqābilīna ",
      verse: 4467,
      juz: 25,
      surah: 44,
    },
    {
      number: 54,
      image: "",
      text: "Thus And We will marry them (to) companions with beautiful eyes (to) companions with beautiful eyes (54)",
      transliteration: "kadhālika wazawwajnāhum biḥūrin ʿīnin ",
      verse: 4468,
      juz: 25,
      surah: 44,
    },
    {
      number: 55,
      image: "",
      text: "They will call therein for every (kind) (of) fruit secure (55)",
      transliteration: "yadʿūna fīhā bikulli fākihatin āminīna ",
      verse: 4469,
      juz: 25,
      surah: 44,
    },
    {
      number: 56,
      image: "",
      text: "Not they will taste therein the death except the death the first And He will protect them (from the) punishment (of) the Hellfire (56)",
      transliteration:
        "lā yadhūqūna fīhā l-mawta illā l-mawtata l-ūlā wawaqāhum ʿadhāba l-jaḥīmi ",
      verse: 4470,
      juz: 25,
      surah: 44,
    },
    {
      number: 57,
      image: "",
      text: "A Bounty from your Lord That  it (will be) the success the great (57)",
      transliteration: "faḍlan min rabbika dhālika huwa l-fawzu l-ʿaẓīmu ",
      verse: 4471,
      juz: 25,
      surah: 44,
    },
    {
      number: 58,
      image: "",
      text: "Indeed We have made it easy in your tongue so that they may take heed (58)",
      transliteration:
        "fa-innamā yassarnāhu bilisānika laʿallahum yatadhakkarūna ",
      verse: 4472,
      juz: 25,
      surah: 44,
    },
    {
      number: 59,
      image: "",
      text: "So watch indeed, they (too are) watching (59)",
      transliteration: "fa-ir'taqib innahum mur'taqibūna ",
      verse: 4473,
      juz: 25,
      surah: 44,
    },
  ],
};
