import { Surah } from "../types/islam.js";

export const fajr: Surah = {
  name: "Al-Fajr",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "By the dawn (1)",
      transliteration: "wal-fajri ",
      verse: 5994,
      juz: 30,
      surah: 89,
    },
    {
      number: 2,
      image: "",
      text: "And the nights ten (2)",
      transliteration: "walayālin ʿashrin ",
      verse: 5995,
      juz: 30,
      surah: 89,
    },
    {
      number: 3,
      image: "",
      text: "And the even and the odd (3)",
      transliteration: "wal-shafʿi wal-watri ",
      verse: 5996,
      juz: 30,
      surah: 89,
    },
    {
      number: 4,
      image: "",
      text: "And the night when it passes (4)",
      transliteration: "wa-al-layli idhā yasri ",
      verse: 5997,
      juz: 30,
      surah: 89,
    },
    {
      number: 5,
      image: "",
      text: "Is in that (not) an oath for those who understand (5)",
      transliteration: "hal fī dhālika qasamun lidhī ḥij'rin ",
      verse: 5998,
      juz: 30,
      surah: 89,
    },
    {
      number: 6,
      image: "",
      text: "Did not you see how dealt your Lord with Aad (6)",
      transliteration: "alam tara kayfa faʿala rabbuka biʿādin ",
      verse: 5999,
      juz: 30,
      surah: 89,
    },
    {
      number: 7,
      image: "",
      text: "Iram possessors (of) lofty pillars (7)",
      transliteration: "irama dhāti l-ʿimādi ",
      verse: 6000,
      juz: 30,
      surah: 89,
    },
    {
      number: 8,
      image: "",
      text: "Which not had been created like them in the cities (8)",
      transliteration: "allatī lam yukh'laq mith'luhā fī l-bilādi ",
      verse: 6001,
      juz: 30,
      surah: 89,
    },
    {
      number: 9,
      image: "",
      text: "And Thamud who carved out the rocks in the valley (9)",
      transliteration: "wathamūda alladhīna jābū l-ṣakhra bil-wādi ",
      verse: 6002,
      juz: 30,
      surah: 89,
    },
    {
      number: 10,
      image: "",
      text: "And Firaun owner of stakes (10)",
      transliteration: "wafir'ʿawna dhī l-awtādi ",
      verse: 6003,
      juz: 30,
      surah: 89,
    },
    {
      number: 11,
      image: "",
      text: "Who transgressed in the lands (11)",
      transliteration: "alladhīna ṭaghaw fī l-bilādi ",
      verse: 6004,
      juz: 30,
      surah: 89,
    },
    {
      number: 12,
      image: "",
      text: "And (made) much therein corruption (12)",
      transliteration: "fa-aktharū fīhā l-fasāda ",
      verse: 6005,
      juz: 30,
      surah: 89,
    },
    {
      number: 13,
      image: "",
      text: "So poured on them your Lord scourge (of) punishment (13)",
      transliteration: "faṣabba ʿalayhim rabbuka sawṭa ʿadhābin ",
      verse: 6006,
      juz: 30,
      surah: 89,
    },
    {
      number: 14,
      image: "",
      text: "Indeed your Lord (is) surely Ever Watchful (14)",
      transliteration: "inna rabbaka labil-mir'ṣādi ",
      verse: 6007,
      juz: 30,
      surah: 89,
    },
    {
      number: 15,
      image: "",
      text: "And as for man when does try him his Lord and is generous to him and favors him he says My Lord has honored me (15)",
      transliteration:
        "fa-ammā l-insānu idhā mā ib'talāhu rabbuhu fa-akramahu wanaʿʿamahu fayaqūlu rabbī akramani ",
      verse: 6008,
      juz: 30,
      surah: 89,
    },
    {
      number: 16,
      image: "",
      text: "But when does He try him and restricts for him his provision then he says My Lord (has) humiliated me (16)",
      transliteration:
        "wa-ammā idhā mā ib'talāhu faqadara ʿalayhi riz'qahu fayaqūlu rabbī ahānani ",
      verse: 6009,
      juz: 30,
      surah: 89,
    },
    {
      number: 17,
      image: "",
      text: "Nay But not you honor the orphan (17)",
      transliteration: "kallā bal lā tuk'rimūna l-yatīma ",
      verse: 6010,
      juz: 30,
      surah: 89,
    },
    {
      number: 18,
      image: "",
      text: "And not you feel the urge to feed the poor (18)",
      transliteration: "walā taḥāḍḍūna ʿalā ṭaʿāmi l-mis'kīni ",
      verse: 6011,
      juz: 30,
      surah: 89,
    },
    {
      number: 19,
      image: "",
      text: "And you consume the inheritance devouring altogether (19)",
      transliteration: "watakulūna l-turātha aklan lamman ",
      verse: 6012,
      juz: 30,
      surah: 89,
    },
    {
      number: 20,
      image: "",
      text: "And you love wealth (with) love immense (20)",
      transliteration: "watuḥibbūna l-māla ḥubban jamman ",
      verse: 6013,
      juz: 30,
      surah: 89,
    },
    {
      number: 21,
      image: "",
      text: "Nay When is leveled the earth pounded (and) crushed (21)",
      transliteration: "kallā idhā dukkati l-arḍu dakkan dakkan ",
      verse: 6014,
      juz: 30,
      surah: 89,
    },
    {
      number: 22,
      image: "",
      text: "And comes your Lord and the Angels rank (upon) rank (22)",
      transliteration: "wajāa rabbuka wal-malaku ṣaffan ṣaffan ",
      verse: 6015,
      juz: 30,
      surah: 89,
    },
    {
      number: 23,
      image: "",
      text: "And is brought that Day Hell That Day will remember man but how (will be) for him the remembrance (23)",
      transliteration:
        "wajīa yawma-idhin bijahannama yawma-idhin yatadhakkaru l-insānu wa-annā lahu l-dhik'rā ",
      verse: 6016,
      juz: 30,
      surah: 89,
    },
    {
      number: 24,
      image: "",
      text: "He will say O I wish I had sent forth for my life (24)",
      transliteration: "yaqūlu yālaytanī qaddamtu liḥayātī ",
      verse: 6017,
      juz: 30,
      surah: 89,
    },
    {
      number: 25,
      image: "",
      text: "So that Day not will punish (as) His punishment anyone (25)",
      transliteration: "fayawma-idhin lā yuʿadhibu ʿadhābahu aḥadun ",
      verse: 6018,
      juz: 30,
      surah: 89,
    },
    {
      number: 26,
      image: "",
      text: "And not will bind (as) His binding anyone (26)",
      transliteration: "walā yūthiqu wathāqahu aḥadun ",
      verse: 6019,
      juz: 30,
      surah: 89,
    },
    {
      number: 27,
      image: "",
      text: "O soul who is satisfied (27)",
      transliteration: "yāayyatuhā l-nafsu l-muṭ'ma-inatu ",
      verse: 6020,
      juz: 30,
      surah: 89,
    },
    {
      number: 28,
      image: "",
      text: "Return to your Lord well pleased and pleasing (28)",
      transliteration: "ir'jiʿī ilā rabbiki rāḍiyatan marḍiyyatan ",
      verse: 6021,
      juz: 30,
      surah: 89,
    },
    {
      number: 29,
      image: "",
      text: "So enter among My slaves (29)",
      transliteration: "fa-ud'khulī fī ʿibādī ",
      verse: 6022,
      juz: 30,
      surah: 89,
    },
    {
      number: 30,
      image: "",
      text: "And enter My Paradise (30)",
      transliteration: "wa-ud'khulī jannatī ",
      verse: 6023,
      juz: 30,
      surah: 89,
    },
  ],
};
