import { Surah } from "../types/islam.js";

export const fatir: Surah = {
  name: "Fatir",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "All praises (be) to Allah Originator (of) the heavens and the earth (Who) makes the Angels messengers having wings having wings two or three or four He increases in the creation what He wills Indeed Allah (is) on every thing All-Powerful (1)",
      transliteration:
        "al-ḥamdu lillahi fāṭiri l-samāwāti wal-arḍi jāʿili l-malāikati rusulan ulī ajniḥatin mathnā wathulātha warubāʿa yazīdu fī l-khalqi mā yashāu inna l-laha ʿalā kulli shayin qadīrun ",
      verse: 3661,
      juz: 22,
      surah: 35,
    },
    {
      number: 2,
      image: "",
      text: "What Allah grants Allah grants to mankind of Mercy then none (can) withhold it And what He withholds then none (can) release it thereafter thereafter And He (is) the All-Mighty the All-Wise (2)",
      transliteration:
        "mā yaftaḥi l-lahu lilnnāsi min raḥmatin falā mum'sika lahā wamā yum'sik falā mur'sila lahu min baʿdihi wahuwa l-ʿazīzu l-ḥakīmu ",
      verse: 3662,
      juz: 22,
      surah: 35,
    },
    {
      number: 3,
      image: "",
      text: "O mankind Remember (the) Favor (of) Allah upon you Is (there) any creator other (than) Allah other (than) Allah who provides for you from the sky and the earth (There is) no god but He Then, how (are) you deluded (3)",
      transliteration:
        "yāayyuhā l-nāsu udh'kurū niʿ'mata l-lahi ʿalaykum hal min khāliqin ghayru l-lahi yarzuqukum mina l-samāi wal-arḍi lā ilāha illā huwa fa-annā tu'fakūna ",
      verse: 3663,
      juz: 22,
      surah: 35,
    },
    {
      number: 4,
      image: "",
      text: "And if they deny you then certainly were denied Messengers before you before you And to Allah return the matters (4)",
      transliteration:
        "wa-in yukadhibūka faqad kudhibat rusulun min qablika wa-ilā l-lahi tur'jaʿu l-umūru ",
      verse: 3664,
      juz: 22,
      surah: 35,
    },
    {
      number: 5,
      image: "",
      text: "O mankind Indeed (the) promise (of) Allah (is) true So (let) not deceive you the life (of) the world and (let) not deceive you about Allah the Deceiver (5)",
      transliteration:
        "yāayyuhā l-nāsu inna waʿda l-lahi ḥaqqun falā taghurrannakumu l-ḥayatu l-dun'yā walā yaghurrannakum bil-lahi l-gharūru ",
      verse: 3665,
      juz: 22,
      surah: 35,
    },
    {
      number: 6,
      image: "",
      text: "Indeed the Shaitaan (is) to you an enemy so take him (as) an enemy Only he invites his party that they may be among (the) companions (of) the Blaze (6)",
      transliteration:
        "inna l-shayṭāna lakum ʿaduwwun fa-ittakhidhūhu ʿaduwwan innamā yadʿū ḥiz'bahu liyakūnū min aṣḥābi l-saʿīri ",
      verse: 3666,
      juz: 22,
      surah: 35,
    },
    {
      number: 7,
      image: "",
      text: "Those who disbelieve for them (will be) a punishment severe and those who believe and do righteous deeds for them (will be) forgiveness and a reward great (7)",
      transliteration:
        "alladhīna kafarū lahum ʿadhābun shadīdun wa-alladhīna āmanū waʿamilū l-ṣāliḥāti lahum maghfiratun wa-ajrun kabīrun ",
      verse: 3667,
      juz: 22,
      surah: 35,
    },
    {
      number: 8,
      image: "",
      text: "Then is (he) who  is made fair-seeming to him (the) evil (of) his deed  so that he sees it (as) good For indeed Allah lets go astray whom He wills and guides whom He wills So (let) not go out your soul for them (in) regrets Indeed Allah (is) All-Knower of what they do (8)",
      transliteration:
        "afaman zuyyina lahu sūu ʿamalihi faraāhu ḥasanan fa-inna l-laha yuḍillu man yashāu wayahdī man yashāu falā tadhhab nafsuka ʿalayhim ḥasarātin inna l-laha ʿalīmun bimā yaṣnaʿūna ",
      verse: 3668,
      juz: 22,
      surah: 35,
    },
    {
      number: 9,
      image: "",
      text: "And Allah (is) the One Who sends the winds so that they raise (the) clouds and We drive them to a land dead and We revive therewith the earth after its death Thus (will be) the Resurrection (9)",
      transliteration:
        "wal-lahu alladhī arsala l-riyāḥa fatuthīru saḥāban fasuq'nāhu ilā baladin mayyitin fa-aḥyaynā bihi l-arḍa baʿda mawtihā kadhālika l-nushūru ",
      verse: 3669,
      juz: 22,
      surah: 35,
    },
    {
      number: 10,
      image: "",
      text: "Whoever [is] desires [is] desires the honor then for Allah (is) the Honor all To Him ascends the words good and the deed righteous raises it But those who plot the evil for them (is) a punishment severe and (the) plotting (of) those  it (will) perish (10)",
      transliteration:
        "man kāna yurīdu l-ʿizata falillahi l-ʿizatu jamīʿan ilayhi yaṣʿadu l-kalimu l-ṭayibu wal-ʿamalu l-ṣāliḥu yarfaʿuhu wa-alladhīna yamkurūna l-sayiāti lahum ʿadhābun shadīdun wamakru ulāika huwa yabūru ",
      verse: 3670,
      juz: 22,
      surah: 35,
    },
    {
      number: 11,
      image: "",
      text: "And Allah created you from dust then from a semen-drop then He made you pairs And not conceives any female and not gives birth except with His knowledge And not is granted life any aged person and not is lessened from his life but (is) in a Register Indeed that for Allah (is) easy (11)",
      transliteration:
        "wal-lahu khalaqakum min turābin thumma min nuṭ'fatin thumma jaʿalakum azwājan wamā taḥmilu min unthā walā taḍaʿu illā biʿil'mihi wamā yuʿammaru min muʿammarin walā yunqaṣu min ʿumurihi illā fī kitābin inna dhālika ʿalā l-lahi yasīrun ",
      verse: 3671,
      juz: 22,
      surah: 35,
    },
    {
      number: 12,
      image: "",
      text: "And not are alike the two seas This (is) fresh sweet pleasant its drink and this salty (and) bitter And from each you eat meat fresh and you extract ornaments you wear them and you see the ships in it cleaving so that you may seek of His Bounty and that you may be grateful (12)",
      transliteration:
        "wamā yastawī l-baḥrāni hādhā ʿadhbun furātun sāighun sharābuhu wahādhā mil'ḥun ujājun wamin kullin takulūna laḥman ṭariyyan watastakhrijūna ḥil'yatan talbasūnahā watarā l-ful'ka fīhi mawākhira litabtaghū min faḍlihi walaʿallakum tashkurūna ",
      verse: 3672,
      juz: 22,
      surah: 35,
    },
    {
      number: 13,
      image: "",
      text: "He causes to enter the night in (to) the day and He causes to enter the day in (to) the night and He has subjected the sun and the moon each running for a term appointed That (is) Allah your Lord for Him (is) the Dominion And those whom you invoke besides Him besides Him not they possess even (as much as) the membrane of a date-seed (13)",
      transliteration:
        "yūliju al-layla fī l-nahāri wayūliju l-nahāra fī al-layli wasakhara l-shamsa wal-qamara kullun yajrī li-ajalin musamman dhālikumu l-lahu rabbukum lahu l-mul'ku wa-alladhīna tadʿūna min dūnihi mā yamlikūna min qiṭ'mīrin ",
      verse: 3673,
      juz: 22,
      surah: 35,
    },
    {
      number: 14,
      image: "",
      text: "If you invoke them not they hear your call and if they heard not they (would) respond to you And (on the) Day (of) the Resurrection they will deny your association And none can inform you like (the) All-Aware (14)",
      transliteration:
        "in tadʿūhum lā yasmaʿū duʿāakum walaw samiʿū mā is'tajābū lakum wayawma l-qiyāmati yakfurūna bishir'kikum walā yunabbi-uka mith'lu khabīrin ",
      verse: 3674,
      juz: 22,
      surah: 35,
    },
    {
      number: 15,
      image: "",
      text: "O mankind You (are) those in need of Allah while Allah He (is) Free of need the Praiseworthy (15)",
      transliteration:
        "yāayyuhā l-nāsu antumu l-fuqarāu ilā l-lahi wal-lahu huwa l-ghaniyu l-ḥamīdu ",
      verse: 3675,
      juz: 22,
      surah: 35,
    },
    {
      number: 16,
      image: "",
      text: "If He wills He (can) do away with you and bring in a creation new (16)",
      transliteration: "in yasha yudh'hib'kum wayati bikhalqin jadīdin ",
      verse: 3676,
      juz: 22,
      surah: 35,
    },
    {
      number: 17,
      image: "",
      text: "And not that (is) on Allah difficult (17)",
      transliteration: "wamā dhālika ʿalā l-lahi biʿazīzin ",
      verse: 3677,
      juz: 22,
      surah: 35,
    },
    {
      number: 18,
      image: "",
      text: "And not will bear bearer of burdens burden (of) another And if calls a heavily laden to (carry) its load not will be carried of it anything even if he be near of kin near of kin Only you can warn those who fear their Lord  unseen and establish the prayer And whoever purifies himself then only he purifies for his own self And to Allah (is) the destination (18)",
      transliteration:
        "walā taziru wāziratun wiz'ra ukh'rā wa-in tadʿu muth'qalatun ilā ḥim'lihā lā yuḥ'mal min'hu shayon walaw kāna dhā qur'bā innamā tundhiru alladhīna yakhshawna rabbahum bil-ghaybi wa-aqāmū l-ṣalata waman tazakkā fa-innamā yatazakkā linafsihi wa-ilā l-lahi l-maṣīru ",
      verse: 3678,
      juz: 22,
      surah: 35,
    },
    {
      number: 19,
      image: "",
      text: "And not equal (are) the blind and the seeing (19)",
      transliteration: "wamā yastawī l-aʿmā wal-baṣīru ",
      verse: 3679,
      juz: 22,
      surah: 35,
    },
    {
      number: 20,
      image: "",
      text: "And not the darkness[es] and not [the] light (20)",
      transliteration: "walā l-ẓulumātu walā l-nūru ",
      verse: 3680,
      juz: 22,
      surah: 35,
    },
    {
      number: 21,
      image: "",
      text: "And not the shade and not the heat (21)",
      transliteration: "walā l-ẓilu walā l-ḥarūru ",
      verse: 3681,
      juz: 22,
      surah: 35,
    },
    {
      number: 22,
      image: "",
      text: "And not equal (are) the living and not the dead Indeed Allah causes to hear whom He wills and not you can make hear (those) who (are) in the graves (22)",
      transliteration:
        "wamā yastawī l-aḥyāu walā l-amwātu inna l-laha yus'miʿu man yashāu wamā anta bimus'miʿin man fī l-qubūri ",
      verse: 3682,
      juz: 22,
      surah: 35,
    },
    {
      number: 23,
      image: "",
      text: "Not you (are) but a warner (23)",
      transliteration: "in anta illā nadhīrun ",
      verse: 3683,
      juz: 22,
      surah: 35,
    },
    {
      number: 24,
      image: "",
      text: "Indeed, We [We] have sent you with the truth (as) a bearer of glad tidings and (as) a warner And not (was) any nation but had passed within it a warner (24)",
      transliteration:
        "innā arsalnāka bil-ḥaqi bashīran wanadhīran wa-in min ummatin illā khalā fīhā nadhīrun ",
      verse: 3684,
      juz: 22,
      surah: 35,
    },
    {
      number: 25,
      image: "",
      text: "And if they deny you then certainly denied those who (were) before them (were) before them Came to them their Messengers with clear signs and with Scriptures and with the Book [the] enlightening (25)",
      transliteration:
        "wa-in yukadhibūka faqad kadhaba alladhīna min qablihim jāathum rusuluhum bil-bayināti wabil-zuburi wabil-kitābi l-munīri ",
      verse: 3685,
      juz: 22,
      surah: 35,
    },
    {
      number: 26,
      image: "",
      text: "Then I seized those who disbelieved and how was My rejection (26)",
      transliteration: "thumma akhadhtu alladhīna kafarū fakayfa kāna nakīri ",
      verse: 3686,
      juz: 22,
      surah: 35,
    },
    {
      number: 27,
      image: "",
      text: "Do not you see that Allah sends down from the sky water then We bring forth therewith fruits (of) various [their] colors And in the mountains (are) tracts white and red (of) various [their] colors and intensely black and intensely black (27)",
      transliteration:
        "alam tara anna l-laha anzala mina l-samāi māan fa-akhrajnā bihi thamarātin mukh'talifan alwānuhā wamina l-jibāli judadun bīḍun waḥum'run mukh'talifun alwānuhā wagharābību sūdun ",
      verse: 3687,
      juz: 22,
      surah: 35,
    },
    {
      number: 28,
      image: "",
      text: "And among men and moving creatures and the cattle (are) various [their] colors likewise Only fear Allah among His slaves those who have knowledge Indeed Allah (is) All-Mighty Oft-Forgiving (28)",
      transliteration:
        "wamina l-nāsi wal-dawābi wal-anʿāmi mukh'talifun alwānuhu kadhālika innamā yakhshā l-laha min ʿibādihi l-ʿulamāu inna l-laha ʿazīzun ghafūrun ",
      verse: 3688,
      juz: 22,
      surah: 35,
    },
    {
      number: 29,
      image: "",
      text: "Indeed those who recite (the) Book (of) Allah and establish the prayer and spend out of what We have provided them secretly and openly hope (for) a commerce  never it will perish (29)",
      transliteration:
        "inna alladhīna yatlūna kitāba l-lahi wa-aqāmū l-ṣalata wa-anfaqū mimmā razaqnāhum sirran waʿalāniyatan yarjūna tijāratan lan tabūra ",
      verse: 3689,
      juz: 22,
      surah: 35,
    },
    {
      number: 30,
      image: "",
      text: "That He may give them in full their rewards and increase for them of His Bounty Indeed, He (is) Oft-Forgiving Most Appreciative (30)",
      transliteration:
        "liyuwaffiyahum ujūrahum wayazīdahum min faḍlihi innahu ghafūrun shakūrun ",
      verse: 3690,
      juz: 22,
      surah: 35,
    },
    {
      number: 31,
      image: "",
      text: "And (that) which We have revealed to you of the Book it (is) the truth confirming what (was) before it before it Indeed Allah of His slaves surely, (is) All-Aware All-Seer (31)",
      transliteration:
        "wa-alladhī awḥaynā ilayka mina l-kitābi huwa l-ḥaqu muṣaddiqan limā bayna yadayhi inna l-laha biʿibādihi lakhabīrun baṣīrun ",
      verse: 3691,
      juz: 22,
      surah: 35,
    },
    {
      number: 32,
      image: "",
      text: "Then We caused to inherit the Book those whom We have chosen of Our slaves and among them (is he) who wrongs himself and among them (is he who is) moderate and among them (is he who is) foremost in good deeds by permission (of) Allah That is the Bounty the great (32)",
      transliteration:
        "thumma awrathnā l-kitāba alladhīna iṣ'ṭafaynā min ʿibādinā famin'hum ẓālimun linafsihi wamin'hum muq'taṣidun wamin'hum sābiqun bil-khayrāti bi-idh'ni l-lahi dhālika huwa l-faḍlu l-kabīru ",
      verse: 3692,
      juz: 22,
      surah: 35,
    },
    {
      number: 33,
      image: "",
      text: "Gardens (of) Eternity they will enter them They will be adorned therein with bracelets of gold and pearls and their garments therein (will be of) silk (33)",
      transliteration:
        "jannātu ʿadnin yadkhulūnahā yuḥallawna fīhā min asāwira min dhahabin walu'lu-an walibāsuhum fīhā ḥarīrun ",
      verse: 3693,
      juz: 22,
      surah: 35,
    },
    {
      number: 34,
      image: "",
      text: "And they (will) say All praises (be) to Allah the One Who (has) removed from us the sorrow Indeed our Lord (is) surely Oft-Forgiving Most Appreciative (34)",
      transliteration:
        "waqālū l-ḥamdu lillahi alladhī adhhaba ʿannā l-ḥazana inna rabbanā laghafūrun shakūrun ",
      verse: 3694,
      juz: 22,
      surah: 35,
    },
    {
      number: 35,
      image: "",
      text: "The One Who has settled us (in) a Home (of) Eternity (out) of His Bounty Not touches us therein any fatigue and not touches therein weariness (35)",
      transliteration:
        "alladhī aḥallanā dāra l-muqāmati min faḍlihi lā yamassunā fīhā naṣabun walā yamassunā fīhā lughūbun ",
      verse: 3695,
      juz: 22,
      surah: 35,
    },
    {
      number: 36,
      image: "",
      text: "And those who disbelieve for them (will be the) Fire (of) Hell Not is decreed for them that they die and not will be lightened for them of its torment Thus We recompense every ungrateful one (36)",
      transliteration:
        "wa-alladhīna kafarū lahum nāru jahannama lā yuq'ḍā ʿalayhim fayamūtū walā yukhaffafu ʿanhum min ʿadhābihā kadhālika najzī kulla kafūrin ",
      verse: 3696,
      juz: 22,
      surah: 35,
    },
    {
      number: 37,
      image: "",
      text: "And they will cry therein Our Lord Bring us out we will do righteous (deeds) other than (that) which we used (to) do Did not We give you life long enough that (would) receive admonition therein whoever receives admonition And came to you the warner So taste then not (is) for the wrongdoers any helper (37)",
      transliteration:
        "wahum yaṣṭarikhūna fīhā rabbanā akhrij'nā naʿmal ṣāliḥan ghayra alladhī kunnā naʿmalu awalam nuʿammir'kum mā yatadhakkaru fīhi man tadhakkara wajāakumu l-nadhīru fadhūqū famā lilẓẓālimīna min naṣīrin ",
      verse: 3697,
      juz: 22,
      surah: 35,
    },
    {
      number: 38,
      image: "",
      text: "Indeed Allah (is the) Knower (of the) unseen (of) the heavens and the earth Indeed, He (is the) All-Knower of what (is) in the breasts of what (is) in the breasts (38)",
      transliteration:
        "inna l-laha ʿālimu ghaybi l-samāwāti wal-arḍi innahu ʿalīmun bidhāti l-ṣudūri ",
      verse: 3698,
      juz: 22,
      surah: 35,
    },
    {
      number: 39,
      image: "",
      text: "He (is) the One Who made you successors in the earth And whoever disbelieves then upon him (is) his disbelief And not increase the disbelievers their disbelief near their Lord except (in) hatred and not increase the disbelievers their disbelief except (in) loss (39)",
      transliteration:
        "huwa alladhī jaʿalakum khalāifa fī l-arḍi faman kafara faʿalayhi kuf'ruhu walā yazīdu l-kāfirīna kuf'ruhum ʿinda rabbihim illā maqtan walā yazīdu l-kāfirīna kuf'ruhum illā khasāran ",
      verse: 3699,
      juz: 22,
      surah: 35,
    },
    {
      number: 40,
      image: "",
      text: "Say Have you seen your partners those whom you call besides besides Allah Show Me what they have created from the earth or for them (is) a share in the heavens Or have We given them a Book so they (are) on a clear proof therefrom Nay not promise the wrongdoers some of them (to) others except delusion (40)",
      transliteration:
        "qul ara-aytum shurakāakumu alladhīna tadʿūna min dūni l-lahi arūnī mādhā khalaqū mina l-arḍi am lahum shir'kun fī l-samāwāti am ātaynāhum kitāban fahum ʿalā bayyinatin min'hu bal in yaʿidu l-ẓālimūna baʿḍuhum baʿḍan illā ghurūran ",
      verse: 3700,
      juz: 22,
      surah: 35,
    },
    {
      number: 41,
      image: "",
      text: "Indeed Allah upholds the heavens and the earth lest they cease And if they should cease not can uphold them any one after Him after Him Indeed, He is Most Forbearing Oft-Forgiving (41)",
      transliteration:
        "inna l-laha yum'siku l-samāwāti wal-arḍa an tazūlā wala-in zālatā in amsakahumā min aḥadin min baʿdihi innahu kāna ḥalīman ghafūran ",
      verse: 3701,
      juz: 22,
      surah: 35,
    },
    {
      number: 42,
      image: "",
      text: "And they swore by Allah (the) strongest (of) their oaths that if came to them a warner surely, they would be more guided than any (of) the nations But when came to them a warner not it increased them but (in) aversion (42)",
      transliteration:
        "wa-aqsamū bil-lahi jahda aymānihim la-in jāahum nadhīrun layakūnunna ahdā min iḥ'dā l-umami falammā jāahum nadhīrun mā zādahum illā nufūran ",
      verse: 3702,
      juz: 22,
      surah: 35,
    },
    {
      number: 43,
      image: "",
      text: "(Due to) arrogance in the land and plotting (of) the evil but not encompasses the plot (of) the evil except its own people Then do they wait except (the) way (of) the former (people) But never you will find in (the) way (of) Allah any change and never you will find in (the) way (of) Allah any alteration (43)",
      transliteration:
        "is'tik'bāran fī l-arḍi wamakra l-sayi-i walā yaḥīqu l-makru l-sayi-u illā bi-ahlihi fahal yanẓurūna illā sunnata l-awalīna falan tajida lisunnati l-lahi tabdīlan walan tajida lisunnati l-lahi taḥwīlan ",
      verse: 3703,
      juz: 22,
      surah: 35,
    },
    {
      number: 44,
      image: "",
      text: "Have they not traveled in the land and seen how was (the) end (of) those who (were) before them (were) before them And they were stronger than them (in) power But not is Allah that can escape (from) Him any thing in the heavens and not in the earth Indeed, He is All-Knower All-Powerful (44)",
      transliteration:
        "awalam yasīrū fī l-arḍi fayanẓurū kayfa kāna ʿāqibatu alladhīna min qablihim wakānū ashadda min'hum quwwatan wamā kāna l-lahu liyuʿ'jizahu min shayin fī l-samāwāti walā fī l-arḍi innahu kāna ʿalīman qadīran ",
      verse: 3704,
      juz: 22,
      surah: 35,
    },
    {
      number: 45,
      image: "",
      text: "And if Allah (were to) punish Allah (were to) punish the people for what they have earned not He would leave on its back any creature But He gives them respite till a term appointed And when comes their term then indeed Allah is of His slaves All-Seer (45)",
      transliteration:
        "walaw yuākhidhu l-lahu l-nāsa bimā kasabū mā taraka ʿalā ẓahrihā min dābbatin walākin yu-akhiruhum ilā ajalin musamman fa-idhā jāa ajaluhum fa-inna l-laha kāna biʿibādihi baṣīran ",
      verse: 3705,
      juz: 22,
      surah: 35,
    },
  ],
};
