import { Surah } from "../types/islam.js";

export const ghashiyah: Surah = {
  name: "Al-Ghashiyah",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "Has (there) come to you (the) news (of) the Overwhelming (1)",
      transliteration: "hal atāka ḥadīthu l-ghāshiyati ",
      verse: 5968,
      juz: 30,
      surah: 88,
    },
    {
      number: 2,
      image: "",
      text: "Faces that Day (will be) humbled (2)",
      transliteration: "wujūhun yawma-idhin khāshiʿatun ",
      verse: 5969,
      juz: 30,
      surah: 88,
    },
    {
      number: 3,
      image: "",
      text: "Laboring exhausted (3)",
      transliteration: "ʿāmilatun nāṣibatun ",
      verse: 5970,
      juz: 30,
      surah: 88,
    },
    {
      number: 4,
      image: "",
      text: "They will burn (in) a Fire intensely hot (4)",
      transliteration: "taṣlā nāran ḥāmiyatan ",
      verse: 5971,
      juz: 30,
      surah: 88,
    },
    {
      number: 5,
      image: "",
      text: "They will be given to drink from a spring boiling (5)",
      transliteration: "tus'qā min ʿaynin āniyatin ",
      verse: 5972,
      juz: 30,
      surah: 88,
    },
    {
      number: 6,
      image: "",
      text: "Not is for them food except from a bitter thorny plant (6)",
      transliteration: "laysa lahum ṭaʿāmun illā min ḍarīʿin ",
      verse: 5973,
      juz: 30,
      surah: 88,
    },
    {
      number: 7,
      image: "",
      text: "Not it nourishes and not it avails from hunger (7)",
      transliteration: "lā yus'minu walā yugh'nī min jūʿin ",
      verse: 5974,
      juz: 30,
      surah: 88,
    },
    {
      number: 8,
      image: "",
      text: "Faces that Day (will be) joyful (8)",
      transliteration: "wujūhun yawma-idhin nāʿimatun ",
      verse: 5975,
      juz: 30,
      surah: 88,
    },
    {
      number: 9,
      image: "",
      text: "With their effort satisfied (9)",
      transliteration: "lisaʿyihā rāḍiyatun ",
      verse: 5976,
      juz: 30,
      surah: 88,
    },
    {
      number: 10,
      image: "",
      text: "In a garden elevated (10)",
      transliteration: "fī jannatin ʿāliyatin ",
      verse: 5977,
      juz: 30,
      surah: 88,
    },
    {
      number: 11,
      image: "",
      text: "Not they will hear therein vain talk (11)",
      transliteration: "lā tasmaʿu fīhā lāghiyatan ",
      verse: 5978,
      juz: 30,
      surah: 88,
    },
    {
      number: 12,
      image: "",
      text: "Therein (will be) a spring flowing (12)",
      transliteration: "fīhā ʿaynun jāriyatun ",
      verse: 5979,
      juz: 30,
      surah: 88,
    },
    {
      number: 13,
      image: "",
      text: "Therein (will be) thrones raised high (13)",
      transliteration: "fīhā sururun marfūʿatun ",
      verse: 5980,
      juz: 30,
      surah: 88,
    },
    {
      number: 14,
      image: "",
      text: "And cups put in place (14)",
      transliteration: "wa-akwābun mawḍūʿatun ",
      verse: 5981,
      juz: 30,
      surah: 88,
    },
    {
      number: 15,
      image: "",
      text: "And cushions lined up (15)",
      transliteration: "wanamāriqu maṣfūfatun ",
      verse: 5982,
      juz: 30,
      surah: 88,
    },
    {
      number: 16,
      image: "",
      text: "And carpets spread out (16)",
      transliteration: "wazarābiyyu mabthūthatun ",
      verse: 5983,
      juz: 30,
      surah: 88,
    },
    {
      number: 17,
      image: "",
      text: "Then do not they look towards the camels how they are created (17)",
      transliteration: "afalā yanẓurūna ilā l-ibili kayfa khuliqat ",
      verse: 5984,
      juz: 30,
      surah: 88,
    },
    {
      number: 18,
      image: "",
      text: "And towards the sky how it is raised (18)",
      transliteration: "wa-ilā l-samāi kayfa rufiʿat ",
      verse: 5985,
      juz: 30,
      surah: 88,
    },
    {
      number: 19,
      image: "",
      text: "And towards the mountains how they are fixed (19)",
      transliteration: "wa-ilā l-jibāli kayfa nuṣibat ",
      verse: 5986,
      juz: 30,
      surah: 88,
    },
    {
      number: 20,
      image: "",
      text: "And towards the earth how it is spread out (20)",
      transliteration: "wa-ilā l-arḍi kayfa suṭiḥat ",
      verse: 5987,
      juz: 30,
      surah: 88,
    },
    {
      number: 21,
      image: "",
      text: "So remind only you (are) a reminder (21)",
      transliteration: "fadhakkir innamā anta mudhakkirun ",
      verse: 5988,
      juz: 30,
      surah: 88,
    },
    {
      number: 22,
      image: "",
      text: "You are not over them a controller (22)",
      transliteration: "lasta ʿalayhim bimuṣayṭirin ",
      verse: 5989,
      juz: 30,
      surah: 88,
    },
    {
      number: 23,
      image: "",
      text: "But whoever turns away and disbelieves (23)",
      transliteration: "illā man tawallā wakafara ",
      verse: 5990,
      juz: 30,
      surah: 88,
    },
    {
      number: 24,
      image: "",
      text: "Then will punish him Allah (with) the punishment greatest (24)",
      transliteration: "fayuʿadhibuhu l-lahu l-ʿadhāba l-akbara ",
      verse: 5991,
      juz: 30,
      surah: 88,
    },
    {
      number: 25,
      image: "",
      text: "Indeed to Us (will be) their return (25)",
      transliteration: "inna ilaynā iyābahum ",
      verse: 5992,
      juz: 30,
      surah: 88,
    },
    {
      number: 26,
      image: "",
      text: "Then indeed upon Us (is) their account (26)",
      transliteration: "thumma inna ʿalaynā ḥisābahum ",
      verse: 5993,
      juz: 30,
      surah: 88,
    },
  ],
};
