import { Surah } from "../types/islam.js";

export const haqqah: Surah = {
  name: "Al-Haqqah",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "The Inevitable Reality (1)",
      transliteration: "al-ḥāqatu ",
      verse: 5324,
      juz: 29,
      surah: 69,
    },
    {
      number: 2,
      image: "",
      text: "What (is) the Inevitable Reality (2)",
      transliteration: "mā l-ḥāqatu ",
      verse: 5325,
      juz: 29,
      surah: 69,
    },
    {
      number: 3,
      image: "",
      text: "And what will make you know what (is) the Inevitable Reality (3)",
      transliteration: "wamā adrāka mā l-ḥāqatu ",
      verse: 5326,
      juz: 29,
      surah: 69,
    },
    {
      number: 4,
      image: "",
      text: "Denied Thamud and Aad the Striking Calamity (4)",
      transliteration: "kadhabat thamūdu waʿādun bil-qāriʿati ",
      verse: 5327,
      juz: 29,
      surah: 69,
    },
    {
      number: 5,
      image: "",
      text: "So as for Thamud they were destroyed by the overpowering (blast) (5)",
      transliteration: "fa-ammā thamūdu fa-uh'likū bil-ṭāghiyati ",
      verse: 5328,
      juz: 29,
      surah: 69,
    },
    {
      number: 6,
      image: "",
      text: "And as for Aad they were destroyed by a wind screaming violent (6)",
      transliteration: "wa-ammā ʿādun fa-uh'likū birīḥin ṣarṣarin ʿātiyatin ",
      verse: 5329,
      juz: 29,
      surah: 69,
    },
    {
      number: 7,
      image: "",
      text: "Which He imposed upon them (for) seven nights and eight days (in) succession so you would see the people therein fallen as if they were trunks (of) date-palms hollow (7)",
      transliteration:
        "sakharahā ʿalayhim sabʿa layālin wathamāniyata ayyāmin ḥusūman fatarā l-qawma fīhā ṣarʿā ka-annahum aʿjāzu nakhlin khāwiyatin ",
      verse: 5330,
      juz: 29,
      surah: 69,
    },
    {
      number: 8,
      image: "",
      text: "Then do you see of them any remains (8)",
      transliteration: "fahal tarā lahum min bāqiyatin ",
      verse: 5331,
      juz: 29,
      surah: 69,
    },
    {
      number: 9,
      image: "",
      text: "And came Firaun and (those) before him and the overturned cities with sin (9)",
      transliteration:
        "wajāa fir'ʿawnu waman qablahu wal-mu'tafikātu bil-khāṭi-ati ",
      verse: 5332,
      juz: 29,
      surah: 69,
    },
    {
      number: 10,
      image: "",
      text: "And they disobeyed (the) Messenger (of) their Lord so He seized them (with) a seizure exceeding (10)",
      transliteration:
        "faʿaṣaw rasūla rabbihim fa-akhadhahum akhdhatan rābiyatan ",
      verse: 5333,
      juz: 29,
      surah: 69,
    },
    {
      number: 11,
      image: "",
      text: "Indeed, We when overflowed the water We carried you in the sailing (ship) (11)",
      transliteration: "innā lammā ṭaghā l-māu ḥamalnākum fī l-jāriyati ",
      verse: 5334,
      juz: 29,
      surah: 69,
    },
    {
      number: 12,
      image: "",
      text: "That We might make it for you a reminder and would be conscious of it an ear conscious (12)",
      transliteration:
        "linajʿalahā lakum tadhkiratan wataʿiyahā udhunun wāʿiyatun ",
      verse: 5335,
      juz: 29,
      surah: 69,
    },
    {
      number: 13,
      image: "",
      text: "Then when is blown in the trumpet  a blast single (13)",
      transliteration: "fa-idhā nufikha fī l-ṣūri nafkhatun wāḥidatun ",
      verse: 5336,
      juz: 29,
      surah: 69,
    },
    {
      number: 14,
      image: "",
      text: "And are lifted the earth and the mountains and crushed (with) a crushing single (14)",
      transliteration:
        "waḥumilati l-arḍu wal-jibālu fadukkatā dakkatan wāḥidatan ",
      verse: 5337,
      juz: 29,
      surah: 69,
    },
    {
      number: 15,
      image: "",
      text: "Then (on) that Day will occur the Occurrence (15)",
      transliteration: "fayawma-idhin waqaʿati l-wāqiʿatu ",
      verse: 5338,
      juz: 29,
      surah: 69,
    },
    {
      number: 16,
      image: "",
      text: "And will split the heaven so it (is on) that Day frail (16)",
      transliteration: "wa-inshaqqati l-samāu fahiya yawma-idhin wāhiyatun ",
      verse: 5339,
      juz: 29,
      surah: 69,
    },
    {
      number: 17,
      image: "",
      text: "And the Angels (will be) on its edges and will bear (the) Throne (of) your Lord above them that Day eight (17)",
      transliteration:
        "wal-malaku ʿalā arjāihā wayaḥmilu ʿarsha rabbika fawqahum yawma-idhin thamāniyatun ",
      verse: 5340,
      juz: 29,
      surah: 69,
    },
    {
      number: 18,
      image: "",
      text: "That Day you will be exhibited not will be hidden among you any secret (18)",
      transliteration: "yawma-idhin tuʿ'raḍūna lā takhfā minkum khāfiyatun ",
      verse: 5341,
      juz: 29,
      surah: 69,
    },
    {
      number: 19,
      image: "",
      text: "Then as for (him) who is given his record in his right hand will say Here read my record (19)",
      transliteration:
        "fa-ammā man ūtiya kitābahu biyamīnihi fayaqūlu hāumu iq'raū kitābiyah ",
      verse: 5342,
      juz: 29,
      surah: 69,
    },
    {
      number: 20,
      image: "",
      text: "Indeed, I was certain that I (will) meet my account (20)",
      transliteration: "innī ẓanantu annī mulāqin ḥisābiyah ",
      verse: 5343,
      juz: 29,
      surah: 69,
    },
    {
      number: 21,
      image: "",
      text: "So he (will be) in a life pleasant (21)",
      transliteration: "fahuwa fī ʿīshatin rāḍiyatin ",
      verse: 5344,
      juz: 29,
      surah: 69,
    },
    {
      number: 22,
      image: "",
      text: "In a Garden elevated (22)",
      transliteration: "fī jannatin ʿāliyatin ",
      verse: 5345,
      juz: 29,
      surah: 69,
    },
    {
      number: 23,
      image: "",
      text: "Its clusters of fruits hanging near (23)",
      transliteration: "quṭūfuhā dāniyatun ",
      verse: 5346,
      juz: 29,
      surah: 69,
    },
    {
      number: 24,
      image: "",
      text: "Eat and drink (in) satisfaction for what you sent before you in the days past (24)",
      transliteration:
        "kulū wa-ish'rabū hanīan bimā aslaftum fī l-ayāmi l-khāliyati ",
      verse: 5347,
      juz: 29,
      surah: 69,
    },
    {
      number: 25,
      image: "",
      text: "But as for (him) who is given his record in his left hand will say O! I wish not I had been given my record (25)",
      transliteration:
        "wa-ammā man ūtiya kitābahu bishimālihi fayaqūlu yālaytanī lam ūta kitābiyah ",
      verse: 5348,
      juz: 29,
      surah: 69,
    },
    {
      number: 26,
      image: "",
      text: "And not I had known what (is) my account (26)",
      transliteration: "walam adri mā ḥisābiyah ",
      verse: 5349,
      juz: 29,
      surah: 69,
    },
    {
      number: 27,
      image: "",
      text: "O! I wish it had been the end (27)",
      transliteration: "yālaytahā kānati l-qāḍiyata ",
      verse: 5350,
      juz: 29,
      surah: 69,
    },
    {
      number: 28,
      image: "",
      text: "Not has availed me my wealth (28)",
      transliteration: "mā aghnā ʿannī māliyah ",
      verse: 5351,
      juz: 29,
      surah: 69,
    },
    {
      number: 29,
      image: "",
      text: "Is gone from me my authority (29)",
      transliteration: "halaka ʿannī sul'ṭāniyah ",
      verse: 5352,
      juz: 29,
      surah: 69,
    },
    {
      number: 30,
      image: "",
      text: "Seize him and shackle him (30)",
      transliteration: "khudhūhu faghullūhu ",
      verse: 5353,
      juz: 29,
      surah: 69,
    },
    {
      number: 31,
      image: "",
      text: "Then (into) the Hellfire burn him (31)",
      transliteration: "thumma l-jaḥīma ṣallūhu ",
      verse: 5354,
      juz: 29,
      surah: 69,
    },
    {
      number: 32,
      image: "",
      text: "Then into a chain its length (is) seventy cubits insert him (32)",
      transliteration:
        "thumma fī sil'silatin dharʿuhā sabʿūna dhirāʿan fa-us'lukūhu ",
      verse: 5355,
      juz: 29,
      surah: 69,
    },
    {
      number: 33,
      image: "",
      text: "Indeed, he was not believing in Allah the Most Great (33)",
      transliteration: "innahu kāna lā yu'minu bil-lahi l-ʿaẓīmi ",
      verse: 5356,
      juz: 29,
      surah: 69,
    },
    {
      number: 34,
      image: "",
      text: "And (did) not feel the urge on (the) feeding (of) the poor (34)",
      transliteration: "walā yaḥuḍḍu ʿalā ṭaʿāmi l-mis'kīni ",
      verse: 5357,
      juz: 29,
      surah: 69,
    },
    {
      number: 35,
      image: "",
      text: "So not for him today here any devoted friend (35)",
      transliteration: "falaysa lahu l-yawma hāhunā ḥamīmun ",
      verse: 5358,
      juz: 29,
      surah: 69,
    },
    {
      number: 36,
      image: "",
      text: "And not any food except from (the) discharge of wounds (36)",
      transliteration: "walā ṭaʿāmun illā min ghis'līnin ",
      verse: 5359,
      juz: 29,
      surah: 69,
    },
    {
      number: 37,
      image: "",
      text: "Not will eat it except the sinners (37)",
      transliteration: "lā yakuluhu illā l-khāṭiūna ",
      verse: 5360,
      juz: 29,
      surah: 69,
    },
    {
      number: 38,
      image: "",
      text: "But nay I swear by what you see (38)",
      transliteration: "falā uq'simu bimā tub'ṣirūna ",
      verse: 5361,
      juz: 29,
      surah: 69,
    },
    {
      number: 39,
      image: "",
      text: "And what not you see (39)",
      transliteration: "wamā lā tub'ṣirūna ",
      verse: 5362,
      juz: 29,
      surah: 69,
    },
    {
      number: 40,
      image: "",
      text: "Indeed, it (is) surely (the) Word (of) a Messenger noble (40)",
      transliteration: "innahu laqawlu rasūlin karīmin ",
      verse: 5363,
      juz: 29,
      surah: 69,
    },
    {
      number: 41,
      image: "",
      text: "And not it (is the) word (of) a poet little (is) what you believe (41)",
      transliteration: "wamā huwa biqawli shāʿirin qalīlan mā tu'minūna ",
      verse: 5364,
      juz: 29,
      surah: 69,
    },
    {
      number: 42,
      image: "",
      text: "And not (it is the) word (of) a soothsayer little (is) what you take heed (42)",
      transliteration: "walā biqawli kāhinin qalīlan mā tadhakkarūna ",
      verse: 5365,
      juz: 29,
      surah: 69,
    },
    {
      number: 43,
      image: "",
      text: "(It is) a revelation from (the) Lord (of) the worlds (43)",
      transliteration: "tanzīlun min rabbi l-ʿālamīna ",
      verse: 5366,
      juz: 29,
      surah: 69,
    },
    {
      number: 44,
      image: "",
      text: "And if he (had) fabricated against Us some sayings (44)",
      transliteration: "walaw taqawwala ʿalaynā baʿḍa l-aqāwīli ",
      verse: 5367,
      juz: 29,
      surah: 69,
    },
    {
      number: 45,
      image: "",
      text: "Certainly We (would) have seized him by the right hand (45)",
      transliteration: "la-akhadhnā min'hu bil-yamīni ",
      verse: 5368,
      juz: 29,
      surah: 69,
    },
    {
      number: 46,
      image: "",
      text: "Then certainly We (would) have cut off from him the aorta (46)",
      transliteration: "thumma laqaṭaʿnā min'hu l-watīna ",
      verse: 5369,
      juz: 29,
      surah: 69,
    },
    {
      number: 47,
      image: "",
      text: "And not from you any one [from him] (who could) prevent (it) (47)",
      transliteration: "famā minkum min aḥadin ʿanhu ḥājizīna ",
      verse: 5370,
      juz: 29,
      surah: 69,
    },
    {
      number: 48,
      image: "",
      text: "And indeed, it (is) surely a reminder for the Allah-fearing (48)",
      transliteration: "wa-innahu latadhkiratun lil'muttaqīna ",
      verse: 5371,
      juz: 29,
      surah: 69,
    },
    {
      number: 49,
      image: "",
      text: "And indeed, We surely know that among you (are) deniers (49)",
      transliteration: "wa-innā lanaʿlamu anna minkum mukadhibīna ",
      verse: 5372,
      juz: 29,
      surah: 69,
    },
    {
      number: 50,
      image: "",
      text: "And indeed, it (is) surely a regret upon the disbelievers (50)",
      transliteration: "wa-innahu laḥasratun ʿalā l-kāfirīna ",
      verse: 5373,
      juz: 29,
      surah: 69,
    },
    {
      number: 51,
      image: "",
      text: "And indeed, it (is) surely (the) truth (of) certainty (51)",
      transliteration: "wa-innahu laḥaqqu l-yaqīni ",
      verse: 5374,
      juz: 29,
      surah: 69,
    },
    {
      number: 52,
      image: "",
      text: "So glorify (the) name (of) your Lord the Most Great (52)",
      transliteration: "fasabbiḥ bi-is'mi rabbika l-ʿaẓīmi ",
      verse: 5375,
      juz: 29,
      surah: 69,
    },
  ],
};
