import { Surah } from "../types/islam.js";

export const hijr: Surah = {
  name: "Al-Hijr",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "Alif Laam Ra These (are) the Verses (of) the Book and Quran clear (1)",
      transliteration: "alif-lam-ra til'ka āyātu l-kitābi waqur'ānin mubīnin ",
      verse: 1803,
      juz: 14,
      surah: 15,
    },
    {
      number: 2,
      image: "",
      text: "Perhaps will wish those who disbelieved if they had been Muslims (2)",
      transliteration: "rubamā yawaddu alladhīna kafarū law kānū mus'limīna ",
      verse: 1804,
      juz: 14,
      surah: 15,
    },
    {
      number: 3,
      image: "",
      text: "Leave them (to) eat and enjoy and diverted them the hope then soon they will come to know (3)",
      transliteration:
        "dharhum yakulū wayatamattaʿū wayul'hihimu l-amalu fasawfa yaʿlamūna ",
      verse: 1805,
      juz: 14,
      surah: 15,
    },
    {
      number: 4,
      image: "",
      text: "And not We destroyed any town but (there was) for it a decree known (4)",
      transliteration:
        "wamā ahlaknā min qaryatin illā walahā kitābun maʿlūmun ",
      verse: 1806,
      juz: 14,
      surah: 15,
    },
    {
      number: 5,
      image: "",
      text: "Not (can) advance any nation its term and not (can) delay it (5)",
      transliteration: "mā tasbiqu min ummatin ajalahā wamā yastakhirūna ",
      verse: 1807,
      juz: 14,
      surah: 15,
    },
    {
      number: 6,
      image: "",
      text: "And they say O you (to) whom has been sent down [on him] the Reminder indeed, you (are) surely mad (6)",
      transliteration:
        "waqālū yāayyuhā alladhī nuzzila ʿalayhi l-dhik'ru innaka lamajnūnun ",
      verse: 1808,
      juz: 14,
      surah: 15,
    },
    {
      number: 7,
      image: "",
      text: "Why not you bring to us the Angels if you are of the truthful (7)",
      transliteration: "law mā tatīnā bil-malāikati in kunta mina l-ṣādiqīna ",
      verse: 1809,
      juz: 14,
      surah: 15,
    },
    {
      number: 8,
      image: "",
      text: "Not We send down the Angels except with the truth and not they would be then given respite (8)",
      transliteration:
        "mā nunazzilu l-malāikata illā bil-ḥaqi wamā kānū idhan munẓarīna ",
      verse: 1810,
      juz: 14,
      surah: 15,
    },
    {
      number: 9,
      image: "",
      text: "Indeed, We We have sent down the Reminder and indeed, We of it (are) surely Guardians (9)",
      transliteration: "innā naḥnu nazzalnā l-dhik'ra wa-innā lahu laḥāfiẓūna ",
      verse: 1811,
      juz: 14,
      surah: 15,
    },
    {
      number: 10,
      image: "",
      text: "And certainly We (had) sent before you before you in the sects (of) the former (people) (10)",
      transliteration: "walaqad arsalnā min qablika fī shiyaʿi l-awalīna ",
      verse: 1812,
      juz: 14,
      surah: 15,
    },
    {
      number: 11,
      image: "",
      text: "And not came to them any Messenger but they did at him mock (11)",
      transliteration: "wamā yatīhim min rasūlin illā kānū bihi yastahziūna ",
      verse: 1813,
      juz: 14,
      surah: 15,
    },
    {
      number: 12,
      image: "",
      text: "Thus We let it enter in (the) hearts (of) the criminals (12)",
      transliteration: "kadhālika naslukuhu fī qulūbi l-muj'rimīna ",
      verse: 1814,
      juz: 14,
      surah: 15,
    },
    {
      number: 13,
      image: "",
      text: "Not they believe in it and verily have passed the way(s) (of) the former (people) (13)",
      transliteration: "lā yu'minūna bihi waqad khalat sunnatu l-awalīna ",
      verse: 1815,
      juz: 14,
      surah: 15,
    },
    {
      number: 14,
      image: "",
      text: "And (even) if We opened to them a gate from the heaven and they were to continue therein (to) ascend (14)",
      transliteration:
        "walaw fataḥnā ʿalayhim bāban mina l-samāi faẓallū fīhi yaʿrujūna ",
      verse: 1816,
      juz: 14,
      surah: 15,
    },
    {
      number: 15,
      image: "",
      text: "They would surely say Only have been dazzled our eyes Nay we (are) a people bewitched (15)",
      transliteration:
        "laqālū innamā sukkirat abṣārunā bal naḥnu qawmun masḥūrūna ",
      verse: 1817,
      juz: 14,
      surah: 15,
    },
    {
      number: 16,
      image: "",
      text: "And verily We have placed in the heavens constellations and We have beautified it for the observers (16)",
      transliteration:
        "walaqad jaʿalnā fī l-samāi burūjan wazayyannāhā lilnnāẓirīna ",
      verse: 1818,
      juz: 14,
      surah: 15,
    },
    {
      number: 17,
      image: "",
      text: "And We have protected it from every devil accursed (17)",
      transliteration: "waḥafiẓ'nāhā min kulli shayṭānin rajīmin ",
      verse: 1819,
      juz: 14,
      surah: 15,
    },
    {
      number: 18,
      image: "",
      text: "Except (one) who steals the hearing then follows him a burning flame clear (18)",
      transliteration:
        "illā mani is'taraqa l-samʿa fa-atbaʿahu shihābun mubīnun ",
      verse: 1820,
      juz: 14,
      surah: 15,
    },
    {
      number: 19,
      image: "",
      text: "And the earth We have spread it and [We] cast therein firm mountains and [We] caused to grow therein of every thing well-balanced (19)",
      transliteration:
        "wal-arḍa madadnāhā wa-alqaynā fīhā rawāsiya wa-anbatnā fīhā min kulli shayin mawzūnin ",
      verse: 1821,
      juz: 14,
      surah: 15,
    },
    {
      number: 20,
      image: "",
      text: "And We have made for you therein means of living and whom you are not for him providers (20)",
      transliteration:
        "wajaʿalnā lakum fīhā maʿāyisha waman lastum lahu birāziqīna ",
      verse: 1822,
      juz: 14,
      surah: 15,
    },
    {
      number: 21,
      image: "",
      text: "And not (is) any thing but with Us (are) its treasures and not We send it down except in a measure known (21)",
      transliteration:
        "wa-in min shayin illā ʿindanā khazāinuhu wamā nunazziluhu illā biqadarin maʿlūmin ",
      verse: 1823,
      juz: 14,
      surah: 15,
    },
    {
      number: 22,
      image: "",
      text: "And We have sent the winds fertilizing and We sent down from the sky water and We gave it to you to drink And not you of it (are) retainers (22)",
      transliteration:
        "wa-arsalnā l-riyāḥa lawāqiḥa fa-anzalnā mina l-samāi māan fa-asqaynākumūhu wamā antum lahu bikhāzinīna ",
      verse: 1824,
      juz: 14,
      surah: 15,
    },
    {
      number: 23,
      image: "",
      text: "And indeed, We surely [We] We give life and We cause death and We (are) the Inheritors (23)",
      transliteration: "wa-innā lanaḥnu nuḥ'yī wanumītu wanaḥnu l-wārithūna ",
      verse: 1825,
      juz: 14,
      surah: 15,
    },
    {
      number: 24,
      image: "",
      text: "And verily We know the preceding ones among you and verily We know the later ones (24)",
      transliteration:
        "walaqad ʿalim'nā l-mus'taqdimīna minkum walaqad ʿalim'nā l-mus'takhirīna ",
      verse: 1826,
      juz: 14,
      surah: 15,
    },
    {
      number: 25,
      image: "",
      text: "And indeed your Lord He will gather them Indeed, He (is) All-Wise All-Knowing (25)",
      transliteration:
        "wa-inna rabbaka huwa yaḥshuruhum innahu ḥakīmun ʿalīmun ",
      verse: 1827,
      juz: 14,
      surah: 15,
    },
    {
      number: 26,
      image: "",
      text: "And verily We created humankind (out) of sounding clay from black mud altered (26)",
      transliteration:
        "walaqad khalaqnā l-insāna min ṣalṣālin min ḥama-in masnūnin ",
      verse: 1828,
      juz: 14,
      surah: 15,
    },
    {
      number: 27,
      image: "",
      text: "And the jinn We created it before before from fire scorching (27)",
      transliteration: "wal-jāna khalaqnāhu min qablu min nāri l-samūmi ",
      verse: 1829,
      juz: 14,
      surah: 15,
    },
    {
      number: 28,
      image: "",
      text: "And when your Lord said your Lord said to the Angels Indeed, I (will) create a human being (out) of clay from black mud altered (28)",
      transliteration:
        "wa-idh qāla rabbuka lil'malāikati innī khāliqun basharan min ṣalṣālin min ḥama-in masnūnin ",
      verse: 1830,
      juz: 14,
      surah: 15,
    },
    {
      number: 29,
      image: "",
      text: "So, when I have fashioned him and [I] breathed into him of My spirit then fall down to him prostrating (29)",
      transliteration:
        "fa-idhā sawwaytuhu wanafakhtu fīhi min rūḥī faqaʿū lahu sājidīna ",
      verse: 1831,
      juz: 14,
      surah: 15,
    },
    {
      number: 30,
      image: "",
      text: "So prostrated the Angels all of them together (30)",
      transliteration: "fasajada l-malāikatu kulluhum ajmaʿūna ",
      verse: 1832,
      juz: 14,
      surah: 15,
    },
    {
      number: 31,
      image: "",
      text: "Except Iblis He refused to be with those who prostrated (31)",
      transliteration: "illā ib'līsa abā an yakūna maʿa l-sājidīna ",
      verse: 1833,
      juz: 14,
      surah: 15,
    },
    {
      number: 32,
      image: "",
      text: "He said O Iblis What (is) for you that not you are with those who prostrated (32)",
      transliteration: "qāla yāib'līsu mā laka allā takūna maʿa l-sājidīna ",
      verse: 1834,
      juz: 14,
      surah: 15,
    },
    {
      number: 33,
      image: "",
      text: "He said I am not I am not (one) to prostrate to a human whom You created (out) of clay from black mud altered (33)",
      transliteration:
        "qāla lam akun li-asjuda libasharin khalaqtahu min ṣalṣālin min ḥama-in masnūnin ",
      verse: 1835,
      juz: 14,
      surah: 15,
    },
    {
      number: 34,
      image: "",
      text: "He said Then get out of it for indeed, you (are) expelled (34)",
      transliteration: "qāla fa-ukh'ruj min'hā fa-innaka rajīmun ",
      verse: 1836,
      juz: 14,
      surah: 15,
    },
    {
      number: 35,
      image: "",
      text: "And indeed upon you (will be) the curse till (the) Day (of) [the] Judgment (35)",
      transliteration: "wa-inna ʿalayka l-laʿnata ilā yawmi l-dīni ",
      verse: 1837,
      juz: 14,
      surah: 15,
    },
    {
      number: 36,
      image: "",
      text: "He said O my Lord Then give me respite till (the) Day they are raised (36)",
      transliteration: "qāla rabbi fa-anẓir'nī ilā yawmi yub'ʿathūna ",
      verse: 1838,
      juz: 14,
      surah: 15,
    },
    {
      number: 37,
      image: "",
      text: "He said Then indeed you (are) of the ones given respite (37)",
      transliteration: "qāla fa-innaka mina l-munẓarīna ",
      verse: 1839,
      juz: 14,
      surah: 15,
    },
    {
      number: 38,
      image: "",
      text: "Till the Day (of) the time well-known (38)",
      transliteration: "ilā yawmi l-waqti l-maʿlūmi ",
      verse: 1840,
      juz: 14,
      surah: 15,
    },
    {
      number: 39,
      image: "",
      text: "He said My Lord Because You misled me surely, I will make (evil) fair-seeming to them in the earth and I will mislead them all (39)",
      transliteration:
        "qāla rabbi bimā aghwaytanī la-uzayyinanna lahum fī l-arḍi wala-ugh'wiyannahum ajmaʿīna ",
      verse: 1841,
      juz: 14,
      surah: 15,
    },
    {
      number: 40,
      image: "",
      text: "Except Your slaves among them the ones who are sincere (40)",
      transliteration: "illā ʿibādaka min'humu l-mukh'laṣīna ",
      verse: 1842,
      juz: 14,
      surah: 15,
    },
    {
      number: 41,
      image: "",
      text: "He said This (is) the way to Me straight (41)",
      transliteration: "qāla hādhā ṣirāṭun ʿalayya mus'taqīmun ",
      verse: 1843,
      juz: 14,
      surah: 15,
    },
    {
      number: 42,
      image: "",
      text: "Indeed My slaves not you have over them any authority except those who follow you of the ones who go astray (42)",
      transliteration:
        "inna ʿibādī laysa laka ʿalayhim sul'ṭānun illā mani ittabaʿaka mina l-ghāwīna ",
      verse: 1844,
      juz: 14,
      surah: 15,
    },
    {
      number: 43,
      image: "",
      text: "And indeed Hell (is) surely the promised place for them all (43)",
      transliteration: "wa-inna jahannama lamawʿiduhum ajmaʿīna ",
      verse: 1845,
      juz: 14,
      surah: 15,
    },
    {
      number: 44,
      image: "",
      text: "For it (are) seven gates for each gate among them (is) a portion assigned (44)",
      transliteration:
        "lahā sabʿatu abwābin likulli bābin min'hum juz'on maqsūmun ",
      verse: 1846,
      juz: 14,
      surah: 15,
    },
    {
      number: 45,
      image: "",
      text: "Indeed the righteous (will be) in Gardens and water springs (45)",
      transliteration: "inna l-mutaqīna fī jannātin waʿuyūnin ",
      verse: 1847,
      juz: 14,
      surah: 15,
    },
    {
      number: 46,
      image: "",
      text: "Enter it in peace secure (46)",
      transliteration: "ud'khulūhā bisalāmin āminīna ",
      verse: 1848,
      juz: 14,
      surah: 15,
    },
    {
      number: 47,
      image: "",
      text: "And We (will) remove what (is) in their breasts of rancor (they will be) brothers on thrones facing each other (47)",
      transliteration:
        "wanazaʿnā mā fī ṣudūrihim min ghillin ikh'wānan ʿalā sururin mutaqābilīna ",
      verse: 1849,
      juz: 14,
      surah: 15,
    },
    {
      number: 48,
      image: "",
      text: "Not will touch them therein fatigue and not they from it will be removed (48)",
      transliteration:
        "lā yamassuhum fīhā naṣabun wamā hum min'hā bimukh'rajīna ",
      verse: 1850,
      juz: 14,
      surah: 15,
    },
    {
      number: 49,
      image: "",
      text: "Inform My slaves that I I am the Oft-Forgiving the Most Merciful (49)",
      transliteration: "nabbi ʿibādī annī anā l-ghafūru l-raḥīmu ",
      verse: 1851,
      juz: 14,
      surah: 15,
    },
    {
      number: 50,
      image: "",
      text: "And that My punishment it (is) the punishment the most painful (50)",
      transliteration: "wa-anna ʿadhābī huwa l-ʿadhābu l-alīmu ",
      verse: 1852,
      juz: 14,
      surah: 15,
    },
    {
      number: 51,
      image: "",
      text: "And inform them about (the) guests (of) Ibrahim (51)",
      transliteration: "wanabbi'hum ʿan ḍayfi ib'rāhīma ",
      verse: 1853,
      juz: 14,
      surah: 15,
    },
    {
      number: 52,
      image: "",
      text: "When they entered upon him and said Peace He said Indeed, we (are) of you afraid (52)",
      transliteration:
        "idh dakhalū ʿalayhi faqālū salāman qāla innā minkum wajilūna ",
      verse: 1854,
      juz: 14,
      surah: 15,
    },
    {
      number: 53,
      image: "",
      text: "They said (Do) not be afraid indeed, we [we] bring glad tidings to you of a boy learned (53)",
      transliteration: "qālū lā tawjal innā nubashiruka bighulāmin ʿalīmin ",
      verse: 1855,
      juz: 14,
      surah: 15,
    },
    {
      number: 54,
      image: "",
      text: "He said Do you give me glad tidings Do you give me glad tidings although has overtaken me old age Then about what you give glad tidings (54)",
      transliteration:
        "qāla abashartumūnī ʿalā an massaniya l-kibaru fabima tubashirūna ",
      verse: 1856,
      juz: 14,
      surah: 15,
    },
    {
      number: 55,
      image: "",
      text: "They said We give you glad tidings in truth so (do) not be of the despairing (55)",
      transliteration: "qālū basharnāka bil-ḥaqi falā takun mina l-qāniṭīna ",
      verse: 1857,
      juz: 14,
      surah: 15,
    },
    {
      number: 56,
      image: "",
      text: "He said And who despairs of (the) Mercy (of) his Lord except those who are astray (56)",
      transliteration: "qāla waman yaqnaṭu min raḥmati rabbihi illā l-ḍālūna ",
      verse: 1858,
      juz: 14,
      surah: 15,
    },
    {
      number: 57,
      image: "",
      text: "He said Then what (is) your business O messengers O messengers (57)",
      transliteration: "qāla famā khaṭbukum ayyuhā l-mur'salūna ",
      verse: 1859,
      juz: 14,
      surah: 15,
    },
    {
      number: 58,
      image: "",
      text: "They said Indeed, we [we] have been sent to a people  criminals (58)",
      transliteration: "qālū innā ur'sil'nā ilā qawmin muj'rimīna ",
      verse: 1860,
      juz: 14,
      surah: 15,
    },
    {
      number: 59,
      image: "",
      text: "Except the family of Lut indeed, we surely will save them all (59)",
      transliteration: "illā āla lūṭin innā lamunajjūhum ajmaʿīna ",
      verse: 1861,
      juz: 14,
      surah: 15,
    },
    {
      number: 60,
      image: "",
      text: "Except his wife We have decreed that she (is) surely of those who remain behind (60)",
      transliteration: "illā im'ra-atahu qaddarnā innahā lamina l-ghābirīna ",
      verse: 1862,
      juz: 14,
      surah: 15,
    },
    {
      number: 61,
      image: "",
      text: "And when came (to the) family (of) Lut the messengers (61)",
      transliteration: "falammā jāa āla lūṭin l-mur'salūna ",
      verse: 1863,
      juz: 14,
      surah: 15,
    },
    {
      number: 62,
      image: "",
      text: "He said Indeed, you (are) a people unknown (62)",
      transliteration: "qāla innakum qawmun munkarūna ",
      verse: 1864,
      juz: 14,
      surah: 15,
    },
    {
      number: 63,
      image: "",
      text: "They said Nay we have come to you with what they were in it disputing (63)",
      transliteration: "qālū bal ji'nāka bimā kānū fīhi yamtarūna ",
      verse: 1865,
      juz: 14,
      surah: 15,
    },
    {
      number: 64,
      image: "",
      text: "And we have come to you with the truth and indeed, we surely (are) truthful (64)",
      transliteration: "wa-ataynāka bil-ḥaqi wa-innā laṣādiqūna ",
      verse: 1866,
      juz: 14,
      surah: 15,
    },
    {
      number: 65,
      image: "",
      text: "So travel with your family in a portion of the night and follow their backs and not let look back among you anyone and go on where you are ordered (65)",
      transliteration:
        "fa-asri bi-ahlika biqiṭ'ʿin mina al-layli wa-ittabiʿ adbārahum walā yaltafit minkum aḥadun wa-im'ḍū ḥaythu tu'marūna ",
      verse: 1867,
      juz: 14,
      surah: 15,
    },
    {
      number: 66,
      image: "",
      text: "And We conveyed to him [that] the matter that (the) root (of) these would be cut off (by) early morning (66)",
      transliteration:
        "waqaḍaynā ilayhi dhālika l-amra anna dābira hāulāi maqṭūʿun muṣ'biḥīna ",
      verse: 1868,
      juz: 14,
      surah: 15,
    },
    {
      number: 67,
      image: "",
      text: "And came (the) people (of) the city rejoicing (67)",
      transliteration: "wajāa ahlu l-madīnati yastabshirūna ",
      verse: 1869,
      juz: 14,
      surah: 15,
    },
    {
      number: 68,
      image: "",
      text: "He said Indeed these (are) my guests so (do) not shame me (68)",
      transliteration: "qāla inna hāulāi ḍayfī falā tafḍaḥūni ",
      verse: 1870,
      juz: 14,
      surah: 15,
    },
    {
      number: 69,
      image: "",
      text: "And fear Allah and (do) not disgrace me (69)",
      transliteration: "wa-ittaqū l-laha walā tukh'zūni ",
      verse: 1871,
      juz: 14,
      surah: 15,
    },
    {
      number: 70,
      image: "",
      text: "They said Did not we forbid you from the world (70)",
      transliteration: "qālū awalam nanhaka ʿani l-ʿālamīna ",
      verse: 1872,
      juz: 14,
      surah: 15,
    },
    {
      number: 71,
      image: "",
      text: "He said These (are) my daughters if you would be doers (71)",
      transliteration: "qāla hāulāi banātī in kuntum fāʿilīna ",
      verse: 1873,
      juz: 14,
      surah: 15,
    },
    {
      number: 72,
      image: "",
      text: "By your life indeed, they were in their intoxication wandering blindly (72)",
      transliteration: "laʿamruka innahum lafī sakratihim yaʿmahūna ",
      verse: 1874,
      juz: 14,
      surah: 15,
    },
    {
      number: 73,
      image: "",
      text: "So, seized them the awful cry at sunrise (73)",
      transliteration: "fa-akhadhathumu l-ṣayḥatu mush'riqīna ",
      verse: 1875,
      juz: 14,
      surah: 15,
    },
    {
      number: 74,
      image: "",
      text: "And We made its highest (part) its lowest and We rained upon them stones of baked clay (74)",
      transliteration:
        "fajaʿalnā ʿāliyahā sāfilahā wa-amṭarnā ʿalayhim ḥijāratan min sijjīlin ",
      verse: 1876,
      juz: 14,
      surah: 15,
    },
    {
      number: 75,
      image: "",
      text: "Indeed in that (are) the Signs for those who discern (75)",
      transliteration: "inna fī dhālika laāyātin lil'mutawassimīna ",
      verse: 1877,
      juz: 14,
      surah: 15,
    },
    {
      number: 76,
      image: "",
      text: "And indeed, it (is) on a road established (76)",
      transliteration: "wa-innahā labisabīlin muqīmin ",
      verse: 1878,
      juz: 14,
      surah: 15,
    },
    {
      number: 77,
      image: "",
      text: "Indeed in that surely (is) a Sign for the believers (77)",
      transliteration: "inna fī dhālika laāyatan lil'mu'minīna ",
      verse: 1879,
      juz: 14,
      surah: 15,
    },
    {
      number: 78,
      image: "",
      text: "And were And were (the) companions (of) the wood surely wrongdoers (78)",
      transliteration: "wa-in kāna aṣḥābu l-aykati laẓālimīna ",
      verse: 1880,
      juz: 14,
      surah: 15,
    },
    {
      number: 79,
      image: "",
      text: "So We took retribution from them and indeed, they both (were) on a highway clear (79)",
      transliteration: "fa-intaqamnā min'hum wa-innahumā labi-imāmin mubīnin ",
      verse: 1881,
      juz: 14,
      surah: 15,
    },
    {
      number: 80,
      image: "",
      text: "And certainly denied (the) companions (of) the Rocky Tract the Messengers (80)",
      transliteration: "walaqad kadhaba aṣḥābu l-ḥij'ri l-mur'salīna ",
      verse: 1882,
      juz: 14,
      surah: 15,
    },
    {
      number: 81,
      image: "",
      text: "And We gave them Our Signs but they were from them turning away (81)",
      transliteration: "waātaynāhum āyātinā fakānū ʿanhā muʿ'riḍīna ",
      verse: 1883,
      juz: 14,
      surah: 15,
    },
    {
      number: 82,
      image: "",
      text: "And they used (to) carve from the mountains houses secure (82)",
      transliteration: "wakānū yanḥitūna mina l-jibāli buyūtan āminīna ",
      verse: 1884,
      juz: 14,
      surah: 15,
    },
    {
      number: 83,
      image: "",
      text: "But seized them the awful cry (at) early morning (83)",
      transliteration: "fa-akhadhathumu l-ṣayḥatu muṣ'biḥīna ",
      verse: 1885,
      juz: 14,
      surah: 15,
    },
    {
      number: 84,
      image: "",
      text: "And not availed them what they used (to) earn (84)",
      transliteration: "famā aghnā ʿanhum mā kānū yaksibūna ",
      verse: 1886,
      juz: 14,
      surah: 15,
    },
    {
      number: 85,
      image: "",
      text: "And not We created the heavens and the earth and whatever (is) between them except in truth And indeed the Hour (is) surely coming So overlook (with) forgiveness gracious (85)",
      transliteration:
        "wamā khalaqnā l-samāwāti wal-arḍa wamā baynahumā illā bil-ḥaqi wa-inna l-sāʿata laātiyatun fa-iṣ'faḥi l-ṣafḥa l-jamīla ",
      verse: 1887,
      juz: 14,
      surah: 15,
    },
    {
      number: 86,
      image: "",
      text: "Indeed your Lord He (is) the Creator the All-Knower (86)",
      transliteration: "inna rabbaka huwa l-khalāqu l-ʿalīmu ",
      verse: 1888,
      juz: 14,
      surah: 15,
    },
    {
      number: 87,
      image: "",
      text: "And certainly We have given you seven of the oft-repeated and the Quran Great (87)",
      transliteration:
        "walaqad ātaynāka sabʿan mina l-mathānī wal-qur'āna l-ʿaẓīma ",
      verse: 1889,
      juz: 14,
      surah: 15,
    },
    {
      number: 88,
      image: "",
      text: "(Do) not extend your eyes towards what We have bestowed with it (to) categories of them and (do) not grieve over them And lower your wing to the believers (88)",
      transliteration:
        "lā tamuddanna ʿaynayka ilā mā mattaʿnā bihi azwājan min'hum walā taḥzan ʿalayhim wa-ikh'fiḍ janāḥaka lil'mu'minīna ",
      verse: 1890,
      juz: 14,
      surah: 15,
    },
    {
      number: 89,
      image: "",
      text: "And say Indeed, I [I] am a warner clear (89)",
      transliteration: "waqul innī anā l-nadhīru l-mubīnu ",
      verse: 1891,
      juz: 14,
      surah: 15,
    },
    {
      number: 90,
      image: "",
      text: "As We sent down on those who divided (90)",
      transliteration: "kamā anzalnā ʿalā l-muq'tasimīna ",
      verse: 1892,
      juz: 14,
      surah: 15,
    },
    {
      number: 91,
      image: "",
      text: "Those who have made the Quran (in) parts (91)",
      transliteration: "alladhīna jaʿalū l-qur'āna ʿiḍīna ",
      verse: 1893,
      juz: 14,
      surah: 15,
    },
    {
      number: 92,
      image: "",
      text: "So by your Lord surely We will question them all (92)",
      transliteration: "fawarabbika lanasalannahum ajmaʿīna ",
      verse: 1894,
      juz: 14,
      surah: 15,
    },
    {
      number: 93,
      image: "",
      text: "About what they used (to) do (93)",
      transliteration: "ʿammā kānū yaʿmalūna ",
      verse: 1895,
      juz: 14,
      surah: 15,
    },
    {
      number: 94,
      image: "",
      text: "So proclaim of what you are ordered and turn away from the polytheists (94)",
      transliteration: "fa-iṣ'daʿ bimā tu'maru wa-aʿriḍ ʿani l-mush'rikīna ",
      verse: 1896,
      juz: 14,
      surah: 15,
    },
    {
      number: 95,
      image: "",
      text: "Indeed, We [We] are sufficient for you (against) the mockers (95)",
      transliteration: "innā kafaynāka l-mus'tahziīna ",
      verse: 1897,
      juz: 14,
      surah: 15,
    },
    {
      number: 96,
      image: "",
      text: "Those who set up with Allah god another But soon they will come to know (96)",
      transliteration:
        "alladhīna yajʿalūna maʿa l-lahi ilāhan ākhara fasawfa yaʿlamūna ",
      verse: 1898,
      juz: 14,
      surah: 15,
    },
    {
      number: 97,
      image: "",
      text: "And verily We know that [you] (is) straitened your breast by what they say (97)",
      transliteration: "walaqad naʿlamu annaka yaḍīqu ṣadruka bimā yaqūlūna ",
      verse: 1899,
      juz: 14,
      surah: 15,
    },
    {
      number: 98,
      image: "",
      text: "So glorify with the praise (of) your Lord and be of those who prostrate (98)",
      transliteration: "fasabbiḥ biḥamdi rabbika wakun mina l-sājidīna ",
      verse: 1900,
      juz: 14,
      surah: 15,
    },
    {
      number: 99,
      image: "",
      text: "And worship your Lord until comes to you the certainty (99)",
      transliteration: "wa-uʿ'bud rabbaka ḥattā yatiyaka l-yaqīnu ",
      verse: 1901,
      juz: 14,
      surah: 15,
    },
  ],
};
