import { Surah } from "../types/islam.js";

export const humazah: Surah = {
  name: "Al-Humazah",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "Woe to every slanderer backbiter (1)",
      transliteration: "waylun likulli humazatin lumazatin ",
      verse: 6180,
      juz: 30,
      surah: 104,
    },
    {
      number: 2,
      image: "",
      text: "The one who collects wealth and counts it (2)",
      transliteration: "alladhī jamaʿa mālan waʿaddadahu ",
      verse: 6181,
      juz: 30,
      surah: 104,
    },
    {
      number: 3,
      image: "",
      text: "Thinking that his wealth will make him immortal (3)",
      transliteration: "yaḥsabu anna mālahu akhladahu ",
      verse: 6182,
      juz: 30,
      surah: 104,
    },
    {
      number: 4,
      image: "",
      text: "Nay Surely he will be thrown in the Crusher (4)",
      transliteration: "kallā layunbadhanna fī l-ḥuṭamati ",
      verse: 6183,
      juz: 30,
      surah: 104,
    },
    {
      number: 5,
      image: "",
      text: "And what will make you know what the Crusher (is) (5)",
      transliteration: "wamā adrāka mā l-ḥuṭamatu ",
      verse: 6184,
      juz: 30,
      surah: 104,
    },
    {
      number: 6,
      image: "",
      text: "A Fire Allah kindled (6)",
      transliteration: "nāru l-lahi l-mūqadatu ",
      verse: 6185,
      juz: 30,
      surah: 104,
    },
    {
      number: 7,
      image: "",
      text: "Which mounts up to the hearts (7)",
      transliteration: "allatī taṭṭaliʿu ʿalā l-afidati ",
      verse: 6186,
      juz: 30,
      surah: 104,
    },
    {
      number: 8,
      image: "",
      text: "Indeed, it (will be) upon them closed over (8)",
      transliteration: "innahā ʿalayhim mu'ṣadatun ",
      verse: 6187,
      juz: 30,
      surah: 104,
    },
    {
      number: 9,
      image: "",
      text: "In columns extended (9)",
      transliteration: "fī ʿamadin mumaddadatin ",
      verse: 6188,
      juz: 30,
      surah: 104,
    },
  ],
};
