import { Surah } from "../types/islam.js";

export const infitar: Surah = {
  name: "Al-Infitar",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "When the sky (is) cleft asunder (1)",
      transliteration: "idhā l-samāu infaṭarat ",
      verse: 5830,
      juz: 30,
      surah: 82,
    },
    {
      number: 2,
      image: "",
      text: "And when the stars scatter (2)",
      transliteration: "wa-idhā l-kawākibu intatharat ",
      verse: 5831,
      juz: 30,
      surah: 82,
    },
    {
      number: 3,
      image: "",
      text: "And when the seas are made to gush forth (3)",
      transliteration: "wa-idhā l-biḥāru fujjirat ",
      verse: 5832,
      juz: 30,
      surah: 82,
    },
    {
      number: 4,
      image: "",
      text: "And when the graves are overturned (4)",
      transliteration: "wa-idhā l-qubūru buʿ'thirat ",
      verse: 5833,
      juz: 30,
      surah: 82,
    },
    {
      number: 5,
      image: "",
      text: "Will know a soul what it has sent forth and left behind (5)",
      transliteration: "ʿalimat nafsun mā qaddamat wa-akharat ",
      verse: 5834,
      juz: 30,
      surah: 82,
    },
    {
      number: 6,
      image: "",
      text: "O man What has deceived you concerning your Lord the Most Noble (6)",
      transliteration: "yāayyuhā l-insānu mā gharraka birabbika l-karīmi ",
      verse: 5835,
      juz: 30,
      surah: 82,
    },
    {
      number: 7,
      image: "",
      text: "Who created you then fashioned you then balanced you (7)",
      transliteration: "alladhī khalaqaka fasawwāka faʿadalaka ",
      verse: 5836,
      juz: 30,
      surah: 82,
    },
    {
      number: 8,
      image: "",
      text: "In whatever form what He willed He assembled you (8)",
      transliteration: "fī ayyi ṣūratin mā shāa rakkabaka ",
      verse: 5837,
      juz: 30,
      surah: 82,
    },
    {
      number: 9,
      image: "",
      text: "Nay But you deny the Judgment (9)",
      transliteration: "kallā bal tukadhibūna bil-dīni ",
      verse: 5838,
      juz: 30,
      surah: 82,
    },
    {
      number: 10,
      image: "",
      text: "And indeed over you (are) surely guardians (10)",
      transliteration: "wa-inna ʿalaykum laḥāfiẓīna ",
      verse: 5839,
      juz: 30,
      surah: 82,
    },
    {
      number: 11,
      image: "",
      text: "Noble recording (11)",
      transliteration: "kirāman kātibīna ",
      verse: 5840,
      juz: 30,
      surah: 82,
    },
    {
      number: 12,
      image: "",
      text: "They know whatever you do (12)",
      transliteration: "yaʿlamūna mā tafʿalūna ",
      verse: 5841,
      juz: 30,
      surah: 82,
    },
    {
      number: 13,
      image: "",
      text: "Indeed the righteous (will be) surely in bliss (13)",
      transliteration: "inna l-abrāra lafī naʿīmin ",
      verse: 5842,
      juz: 30,
      surah: 82,
    },
    {
      number: 14,
      image: "",
      text: "And indeed the wicked (will be) surely in Hellfire (14)",
      transliteration: "wa-inna l-fujāra lafī jaḥīmin ",
      verse: 5843,
      juz: 30,
      surah: 82,
    },
    {
      number: 15,
      image: "",
      text: "They will burn (in) it (on the) Day (of) the Judgment (15)",
      transliteration: "yaṣlawnahā yawma l-dīni ",
      verse: 5844,
      juz: 30,
      surah: 82,
    },
    {
      number: 16,
      image: "",
      text: "And not they from it (will be) absent (16)",
      transliteration: "wamā hum ʿanhā bighāibīna ",
      verse: 5845,
      juz: 30,
      surah: 82,
    },
    {
      number: 17,
      image: "",
      text: "And what can make you know what (is the) Day (of) the Judgment (17)",
      transliteration: "wamā adrāka mā yawmu l-dīni ",
      verse: 5846,
      juz: 30,
      surah: 82,
    },
    {
      number: 18,
      image: "",
      text: "Then what can make you know what (is the) Day (of) the Judgment (18)",
      transliteration: "thumma mā adrāka mā yawmu l-dīni ",
      verse: 5847,
      juz: 30,
      surah: 82,
    },
    {
      number: 19,
      image: "",
      text: "(The) Day not will have power a soul for a soul anything and the Command that Day (will be) with Allah (19)",
      transliteration:
        "yawma lā tamliku nafsun linafsin shayan wal-amru yawma-idhin lillahi ",
      verse: 5848,
      juz: 30,
      surah: 82,
    },
  ],
};
