import { Surah } from "../types/islam.js";

export const inshiqaq: Surah = {
  name: "Al-Inshiqaq",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "When the sky is split asunder (1)",
      transliteration: "idhā l-samāu inshaqqat ",
      verse: 5885,
      juz: 30,
      surah: 84,
    },
    {
      number: 2,
      image: "",
      text: "And has listened to its Lord and was obligated (2)",
      transliteration: "wa-adhinat lirabbihā waḥuqqat ",
      verse: 5886,
      juz: 30,
      surah: 84,
    },
    {
      number: 3,
      image: "",
      text: "And when the earth is spread (3)",
      transliteration: "wa-idhā l-arḍu muddat ",
      verse: 5887,
      juz: 30,
      surah: 84,
    },
    {
      number: 4,
      image: "",
      text: "And has cast out what (is) in it and becomes empty (4)",
      transliteration: "wa-alqat mā fīhā watakhallat ",
      verse: 5888,
      juz: 30,
      surah: 84,
    },
    {
      number: 5,
      image: "",
      text: "And has listened to its Lord and was obligated (5)",
      transliteration: "wa-adhinat lirabbihā waḥuqqat ",
      verse: 5889,
      juz: 30,
      surah: 84,
    },
    {
      number: 6,
      image: "",
      text: "O mankind Indeed, you (are) laboring to your Lord (with) exertion and you (will) meet Him (6)",
      transliteration:
        "yāayyuhā l-insānu innaka kādiḥun ilā rabbika kadḥan famulāqīhi ",
      verse: 5890,
      juz: 30,
      surah: 84,
    },
    {
      number: 7,
      image: "",
      text: "Then as for (him) who is given his record in his right (hand) (7)",
      transliteration: "fa-ammā man ūtiya kitābahu biyamīnihi ",
      verse: 5891,
      juz: 30,
      surah: 84,
    },
    {
      number: 8,
      image: "",
      text: "Then soon his account will be taken an account easy (8)",
      transliteration: "fasawfa yuḥāsabu ḥisāban yasīran ",
      verse: 5892,
      juz: 30,
      surah: 84,
    },
    {
      number: 9,
      image: "",
      text: "And he will return to his people happily (9)",
      transliteration: "wayanqalibu ilā ahlihi masrūran ",
      verse: 5893,
      juz: 30,
      surah: 84,
    },
    {
      number: 10,
      image: "",
      text: "But as for (him) who is given his record behind his back (10)",
      transliteration: "wa-ammā man ūtiya kitābahu warāa ẓahrihi ",
      verse: 5894,
      juz: 30,
      surah: 84,
    },
    {
      number: 11,
      image: "",
      text: "Then soon he will call (for) destruction (11)",
      transliteration: "fasawfa yadʿū thubūran ",
      verse: 5895,
      juz: 30,
      surah: 84,
    },
    {
      number: 12,
      image: "",
      text: "And he will burn (in) a Blaze (12)",
      transliteration: "wayaṣlā saʿīran ",
      verse: 5896,
      juz: 30,
      surah: 84,
    },
    {
      number: 13,
      image: "",
      text: "Indeed, he had been among his people happy (13)",
      transliteration: "innahu kāna fī ahlihi masrūran ",
      verse: 5897,
      juz: 30,
      surah: 84,
    },
    {
      number: 14,
      image: "",
      text: "Indeed, he (had) thought that never he would return (14)",
      transliteration: "innahu ẓanna an lan yaḥūra ",
      verse: 5898,
      juz: 30,
      surah: 84,
    },
    {
      number: 15,
      image: "",
      text: "Yes Indeed his Lord was of him All-Seer (15)",
      transliteration: "balā inna rabbahu kāna bihi baṣīran ",
      verse: 5899,
      juz: 30,
      surah: 84,
    },
    {
      number: 16,
      image: "",
      text: "But nay I swear by the twilight glow (16)",
      transliteration: "falā uq'simu bil-shafaqi ",
      verse: 5900,
      juz: 30,
      surah: 84,
    },
    {
      number: 17,
      image: "",
      text: "And the night and what it envelops (17)",
      transliteration: "wa-al-layli wamā wasaqa ",
      verse: 5901,
      juz: 30,
      surah: 84,
    },
    {
      number: 18,
      image: "",
      text: "And the moon when it becomes full (18)",
      transliteration: "wal-qamari idhā ittasaqa ",
      verse: 5902,
      juz: 30,
      surah: 84,
    },
    {
      number: 19,
      image: "",
      text: "You will surely embark (to) stage from stage (19)",
      transliteration: "latarkabunna ṭabaqan ʿan ṭabaqin ",
      verse: 5903,
      juz: 30,
      surah: 84,
    },
    {
      number: 20,
      image: "",
      text: "So what (is) for them not they believe (20)",
      transliteration: "famā lahum lā yu'minūna ",
      verse: 5904,
      juz: 30,
      surah: 84,
    },
    {
      number: 21,
      image: "",
      text: "And when is recited to them the Quran not they prostrate (21)",
      transliteration: "wa-idhā quri-a ʿalayhimu l-qur'ānu lā yasjudūna ",
      verse: 5905,
      juz: 30,
      surah: 84,
    },
    {
      number: 22,
      image: "",
      text: "Nay Those who disbelieved deny (22)",
      transliteration: "bali alladhīna kafarū yukadhibūna ",
      verse: 5906,
      juz: 30,
      surah: 84,
    },
    {
      number: 23,
      image: "",
      text: "And Allah (is) most knowing of what they keep within themselves (23)",
      transliteration: "wal-lahu aʿlamu bimā yūʿūna ",
      verse: 5907,
      juz: 30,
      surah: 84,
    },
    {
      number: 24,
      image: "",
      text: "so give them tidings of a punishment painful (24)",
      transliteration: "fabashir'hum biʿadhābin alīmin ",
      verse: 5908,
      juz: 30,
      surah: 84,
    },
    {
      number: 25,
      image: "",
      text: "Except those who believe and do righteous deeds For them (is) a reward never ending (25)",
      transliteration:
        "illā alladhīna āmanū waʿamilū l-ṣāliḥāti lahum ajrun ghayru mamnūnin ",
      verse: 5909,
      juz: 30,
      surah: 84,
    },
  ],
};
