import { Surah } from "../types/islam.js";

export const kafirun: Surah = {
  name: "Al-Kafirun",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "Say O disbelievers (1)",
      transliteration: "qul yāayyuhā l-kāfirūna ",
      verse: 6208,
      juz: 30,
      surah: 109,
    },
    {
      number: 2,
      image: "",
      text: "Not I worship what you worship (2)",
      transliteration: "lā aʿbudu mā taʿbudūna ",
      verse: 6209,
      juz: 30,
      surah: 109,
    },
    {
      number: 3,
      image: "",
      text: "And not you (are) worshippers (of) what I worship (3)",
      transliteration: "walā antum ʿābidūna mā aʿbudu ",
      verse: 6210,
      juz: 30,
      surah: 109,
    },
    {
      number: 4,
      image: "",
      text: "And not I am a worshipper (of) what you worship (4)",
      transliteration: "walā anā ʿābidun mā ʿabadttum ",
      verse: 6211,
      juz: 30,
      surah: 109,
    },
    {
      number: 5,
      image: "",
      text: "And not you (are) worshippers (of) what I worship (5)",
      transliteration: "walā antum ʿābidūna mā aʿbudu ",
      verse: 6212,
      juz: 30,
      surah: 109,
    },
    {
      number: 6,
      image: "",
      text: "For you (is) your religion and for me (is) my religion (6)",
      transliteration: "lakum dīnukum waliya dīni ",
      verse: 6213,
      juz: 30,
      surah: 109,
    },
  ],
};
