import { Surah } from "../types/islam.js";

export const layl: Surah = {
  name: "Al-Layl",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "By the night when it covers (1)",
      transliteration: "wa-al-layli idhā yaghshā ",
      verse: 6059,
      juz: 30,
      surah: 92,
    },
    {
      number: 2,
      image: "",
      text: "And the day when it shines in brightness (2)",
      transliteration: "wal-nahāri idhā tajallā ",
      verse: 6060,
      juz: 30,
      surah: 92,
    },
    {
      number: 3,
      image: "",
      text: "And He Who created the male and the female (3)",
      transliteration: "wamā khalaqa l-dhakara wal-unthā ",
      verse: 6061,
      juz: 30,
      surah: 92,
    },
    {
      number: 4,
      image: "",
      text: "Indeed your efforts (are) surely diverse (4)",
      transliteration: "inna saʿyakum lashattā ",
      verse: 6062,
      juz: 30,
      surah: 92,
    },
    {
      number: 5,
      image: "",
      text: "Then as for (him) who gives and fears (5)",
      transliteration: "fa-ammā man aʿṭā wa-ittaqā ",
      verse: 6063,
      juz: 30,
      surah: 92,
    },
    {
      number: 6,
      image: "",
      text: "And believes in the best (6)",
      transliteration: "waṣaddaqa bil-ḥus'nā ",
      verse: 6064,
      juz: 30,
      surah: 92,
    },
    {
      number: 7,
      image: "",
      text: "Then We will ease him towards [the] ease (7)",
      transliteration: "fasanuyassiruhu lil'yus'rā ",
      verse: 6065,
      juz: 30,
      surah: 92,
    },
    {
      number: 8,
      image: "",
      text: "But as for (him) who withholds and considers himself free from need (8)",
      transliteration: "wa-ammā man bakhila wa-is'taghnā ",
      verse: 6066,
      juz: 30,
      surah: 92,
    },
    {
      number: 9,
      image: "",
      text: "And denies the best (9)",
      transliteration: "wakadhaba bil-ḥus'nā ",
      verse: 6067,
      juz: 30,
      surah: 92,
    },
    {
      number: 10,
      image: "",
      text: "Then We will ease him towards [the] difficulty (10)",
      transliteration: "fasanuyassiruhu lil'ʿus'rā ",
      verse: 6068,
      juz: 30,
      surah: 92,
    },
    {
      number: 11,
      image: "",
      text: "And not will avail him his wealth when he falls (11)",
      transliteration: "wamā yugh'nī ʿanhu māluhu idhā taraddā ",
      verse: 6069,
      juz: 30,
      surah: 92,
    },
    {
      number: 12,
      image: "",
      text: "Indeed upon Us (is) the guidance (12)",
      transliteration: "inna ʿalaynā lalhudā ",
      verse: 6070,
      juz: 30,
      surah: 92,
    },
    {
      number: 13,
      image: "",
      text: "And indeed for Us (is) the Hereafter and the first (life) (13)",
      transliteration: "wa-inna lanā lalākhirata wal-ūlā ",
      verse: 6071,
      juz: 30,
      surah: 92,
    },
    {
      number: 14,
      image: "",
      text: "So I warn you (of) a Fire blazing (14)",
      transliteration: "fa-andhartukum nāran talaẓẓā ",
      verse: 6072,
      juz: 30,
      surah: 92,
    },
    {
      number: 15,
      image: "",
      text: "Not will burn (in) it except the most wretched (15)",
      transliteration: "lā yaṣlāhā illā l-ashqā ",
      verse: 6073,
      juz: 30,
      surah: 92,
    },
    {
      number: 16,
      image: "",
      text: "The one who denied and turned away (16)",
      transliteration: "alladhī kadhaba watawallā ",
      verse: 6074,
      juz: 30,
      surah: 92,
    },
    {
      number: 17,
      image: "",
      text: "But will be removed from it the righteous (17)",
      transliteration: "wasayujannabuhā l-atqā ",
      verse: 6075,
      juz: 30,
      surah: 92,
    },
    {
      number: 18,
      image: "",
      text: "The one who gives his wealth (to) purify himself (18)",
      transliteration: "alladhī yu'tī mālahu yatazakkā ",
      verse: 6076,
      juz: 30,
      surah: 92,
    },
    {
      number: 19,
      image: "",
      text: "And not for anyone with him any favor to be recompensed (19)",
      transliteration: "wamā li-aḥadin ʿindahu min niʿ'matin tuj'zā ",
      verse: 6077,
      juz: 30,
      surah: 92,
    },
    {
      number: 20,
      image: "",
      text: "Except seeking (the) Countenance (of) his Lord the Most High (20)",
      transliteration: "illā ib'tighāa wajhi rabbihi l-aʿlā ",
      verse: 6078,
      juz: 30,
      surah: 92,
    },
    {
      number: 21,
      image: "",
      text: "And soon, surely he will be pleased (21)",
      transliteration: "walasawfa yarḍā ",
      verse: 6079,
      juz: 30,
      surah: 92,
    },
  ],
};
