import { Surah } from "../types/islam.js";

export const maarij: Surah = {
  name: "Al-Ma'arij",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "Asked a questioner about a punishment bound to happen (1)",
      transliteration: "sa-ala sāilun biʿadhābin wāqiʿin ",
      verse: 5376,
      juz: 29,
      surah: 70,
    },
    {
      number: 2,
      image: "",
      text: "To the disbelievers not of it any preventer (2)",
      transliteration: "lil'kāfirīna laysa lahu dāfiʿun ",
      verse: 5377,
      juz: 29,
      surah: 70,
    },
    {
      number: 3,
      image: "",
      text: "From Allah Owner (of) the ways of ascent (3)",
      transliteration: "mina l-lahi dhī l-maʿāriji ",
      verse: 5378,
      juz: 29,
      surah: 70,
    },
    {
      number: 4,
      image: "",
      text: "Ascend the Angels and the Spirit to Him in a Day [is] its measure (is) fifty thousand year(s) (4)",
      transliteration:
        "taʿruju l-malāikatu wal-rūḥu ilayhi fī yawmin kāna miq'dāruhu khamsīna alfa sanatin ",
      verse: 5379,
      juz: 29,
      surah: 70,
    },
    {
      number: 5,
      image: "",
      text: "So be patient a patience good (5)",
      transliteration: "fa-iṣ'bir ṣabran jamīlan ",
      verse: 5380,
      juz: 29,
      surah: 70,
    },
    {
      number: 6,
      image: "",
      text: "Indeed, they see it (as) far off (6)",
      transliteration: "innahum yarawnahu baʿīdan ",
      verse: 5381,
      juz: 29,
      surah: 70,
    },
    {
      number: 7,
      image: "",
      text: "But We see it near (7)",
      transliteration: "wanarāhu qarīban ",
      verse: 5382,
      juz: 29,
      surah: 70,
    },
    {
      number: 8,
      image: "",
      text: "(The) Day  will be the sky like molten copper (8)",
      transliteration: "yawma takūnu l-samāu kal-muh'li ",
      verse: 5383,
      juz: 29,
      surah: 70,
    },
    {
      number: 9,
      image: "",
      text: "And will be the mountains like wool (9)",
      transliteration: "watakūnu l-jibālu kal-ʿih'ni ",
      verse: 5384,
      juz: 29,
      surah: 70,
    },
    {
      number: 10,
      image: "",
      text: "And not will ask a friend (about) a friend (10)",
      transliteration: "walā yasalu ḥamīmun ḥamīman ",
      verse: 5385,
      juz: 29,
      surah: 70,
    },
    {
      number: 11,
      image: "",
      text: "They will be made to see each other Would wish the criminal if he (could be) ransomed from (the) punishment (of) that Day by his children (11)",
      transliteration:
        "yubaṣṣarūnahum yawaddu l-muj'rimu law yaftadī min ʿadhābi yawmi-idhin bibanīhi ",
      verse: 5386,
      juz: 29,
      surah: 70,
    },
    {
      number: 12,
      image: "",
      text: "And his spouse and his brother (12)",
      transliteration: "waṣāḥibatihi wa-akhīhi ",
      verse: 5387,
      juz: 29,
      surah: 70,
    },
    {
      number: 13,
      image: "",
      text: "And his nearest kindred who sheltered him (13)",
      transliteration: "wafaṣīlatihi allatī tu'wīhi ",
      verse: 5388,
      juz: 29,
      surah: 70,
    },
    {
      number: 14,
      image: "",
      text: "And whoever (is) on the earth all then it (could) save him (14)",
      transliteration: "waman fī l-arḍi jamīʿan thumma yunjīhi ",
      verse: 5389,
      juz: 29,
      surah: 70,
    },
    {
      number: 15,
      image: "",
      text: "By no means Indeed, it (is) surely a Flame of Hell (15)",
      transliteration: "kallā innahā laẓā ",
      verse: 5390,
      juz: 29,
      surah: 70,
    },
    {
      number: 16,
      image: "",
      text: "A remover of the skin of the head (16)",
      transliteration: "nazzāʿatan lilshawā ",
      verse: 5391,
      juz: 29,
      surah: 70,
    },
    {
      number: 17,
      image: "",
      text: "Inviting (him) who turned his back and went away (17)",
      transliteration: "tadʿū man adbara watawallā ",
      verse: 5392,
      juz: 29,
      surah: 70,
    },
    {
      number: 18,
      image: "",
      text: "And collected and hoarded (18)",
      transliteration: "wajamaʿa fa-awʿā ",
      verse: 5393,
      juz: 29,
      surah: 70,
    },
    {
      number: 19,
      image: "",
      text: "Indeed the man was created anxious  (19)",
      transliteration: "inna l-insāna khuliqa halūʿan ",
      verse: 5394,
      juz: 29,
      surah: 70,
    },
    {
      number: 20,
      image: "",
      text: "When touches him the evil distressed (20)",
      transliteration: "idhā massahu l-sharu jazūʿan ",
      verse: 5395,
      juz: 29,
      surah: 70,
    },
    {
      number: 21,
      image: "",
      text: "And when touches him the good withholding (21)",
      transliteration: "wa-idhā massahu l-khayru manūʿan ",
      verse: 5396,
      juz: 29,
      surah: 70,
    },
    {
      number: 22,
      image: "",
      text: "Except those who pray  (22)",
      transliteration: "illā l-muṣalīna ",
      verse: 5397,
      juz: 29,
      surah: 70,
    },
    {
      number: 23,
      image: "",
      text: "Those who [they] at their prayer (are) constant (23)",
      transliteration: "alladhīna hum ʿalā ṣalātihim dāimūna ",
      verse: 5398,
      juz: 29,
      surah: 70,
    },
    {
      number: 24,
      image: "",
      text: "And those who in their wealth (is) a right known (24)",
      transliteration: "wa-alladhīna fī amwālihim ḥaqqun maʿlūmun ",
      verse: 5399,
      juz: 29,
      surah: 70,
    },
    {
      number: 25,
      image: "",
      text: "For the one who asks and the deprived (25)",
      transliteration: "lilssāili wal-maḥrūmi ",
      verse: 5400,
      juz: 29,
      surah: 70,
    },
    {
      number: 26,
      image: "",
      text: "And those who accept (the) truth (of the) Day (of) the Judgment (26)",
      transliteration: "wa-alladhīna yuṣaddiqūna biyawmi l-dīni ",
      verse: 5401,
      juz: 29,
      surah: 70,
    },
    {
      number: 27,
      image: "",
      text: "And those who [they] of (the) punishment (of) their Lord (are) fearful  (27)",
      transliteration: "wa-alladhīna hum min ʿadhābi rabbihim mush'fiqūna ",
      verse: 5402,
      juz: 29,
      surah: 70,
    },
    {
      number: 28,
      image: "",
      text: "Indeed (the) punishment (of) your Lord (is) not to be felt secure (of)  (28)",
      transliteration: "inna ʿadhāba rabbihim ghayru mamūnin ",
      verse: 5403,
      juz: 29,
      surah: 70,
    },
    {
      number: 29,
      image: "",
      text: "And those who [they] their modesty (are) guardians (29)",
      transliteration: "wa-alladhīna hum lifurūjihim ḥāfiẓūna ",
      verse: 5404,
      juz: 29,
      surah: 70,
    },
    {
      number: 30,
      image: "",
      text: "Except from their spouses or what they possess rightfully then indeed, they (are) not blameworthy (30)",
      transliteration:
        "illā ʿalā azwājihim aw mā malakat aymānuhum fa-innahum ghayru malūmīna ",
      verse: 5405,
      juz: 29,
      surah: 70,
    },
    {
      number: 31,
      image: "",
      text: "But whoever seeks beyond that then those [they] (are) the transgressors  (31)",
      transliteration: "famani ib'taghā warāa dhālika fa-ulāika humu l-ʿādūna ",
      verse: 5406,
      juz: 29,
      surah: 70,
    },
    {
      number: 32,
      image: "",
      text: "And those who [they] of their trusts and their promise (are) observers (32)",
      transliteration: "wa-alladhīna hum li-amānātihim waʿahdihim rāʿūna ",
      verse: 5407,
      juz: 29,
      surah: 70,
    },
    {
      number: 33,
      image: "",
      text: "And those who [they] in their testimonies stand firm (33)",
      transliteration: "wa-alladhīna hum bishahādātihim qāimūna ",
      verse: 5408,
      juz: 29,
      surah: 70,
    },
    {
      number: 34,
      image: "",
      text: "And those who [they] on their prayer keep a guard  (34)",
      transliteration: "wa-alladhīna hum ʿalā ṣalātihim yuḥāfiẓūna ",
      verse: 5409,
      juz: 29,
      surah: 70,
    },
    {
      number: 35,
      image: "",
      text: "Those (will be) in Gardens honored (35)",
      transliteration: "ulāika fī jannātin muk'ramūna ",
      verse: 5410,
      juz: 29,
      surah: 70,
    },
    {
      number: 36,
      image: "",
      text: "So what is with those who disbelieve before you (they) hasten (36)",
      transliteration: "famāli alladhīna kafarū qibalaka muh'ṭiʿīna ",
      verse: 5411,
      juz: 29,
      surah: 70,
    },
    {
      number: 37,
      image: "",
      text: "On the right and on the left (in) separate groups (37)",
      transliteration: "ʿani l-yamīni waʿani l-shimāli ʿizīna ",
      verse: 5412,
      juz: 29,
      surah: 70,
    },
    {
      number: 38,
      image: "",
      text: "Does long every person among them that he enters a Garden (of) Delight (38)",
      transliteration:
        "ayaṭmaʿu kullu im'ri-in min'hum an yud'khala jannata naʿīmin ",
      verse: 5413,
      juz: 29,
      surah: 70,
    },
    {
      number: 39,
      image: "",
      text: "By no means Indeed, We [We] have created them from what they know (39)",
      transliteration: "kallā innā khalaqnāhum mimmā yaʿlamūna ",
      verse: 5414,
      juz: 29,
      surah: 70,
    },
    {
      number: 40,
      image: "",
      text: "But nay I swear by (the) Lord (of) the risings and the settings that We (are) surely Able (40)",
      transliteration:
        "falā uq'simu birabbi l-mashāriqi wal-maghāribi innā laqādirūna ",
      verse: 5415,
      juz: 29,
      surah: 70,
    },
    {
      number: 41,
      image: "",
      text: "[On] to [We] replace (with) better than them and not We (are) to be outrun (41)",
      transliteration:
        "ʿalā an nubaddila khayran min'hum wamā naḥnu bimasbūqīna ",
      verse: 5416,
      juz: 29,
      surah: 70,
    },
    {
      number: 42,
      image: "",
      text: "So leave them (to) converse vainly and amuse themselves until they meet their Day which they are promised (42)",
      transliteration:
        "fadharhum yakhūḍū wayalʿabū ḥattā yulāqū yawmahumu alladhī yūʿadūna ",
      verse: 5417,
      juz: 29,
      surah: 70,
    },
    {
      number: 43,
      image: "",
      text: "(The) Day they will come out from the graves rapidly as if they (were) to a goal hastening (43)",
      transliteration:
        "yawma yakhrujūna mina l-ajdāthi sirāʿan ka-annahum ilā nuṣubin yūfiḍūna ",
      verse: 5418,
      juz: 29,
      surah: 70,
    },
    {
      number: 44,
      image: "",
      text: "Humbled their eyesights will cover them humiliation That (is) the Day which they were promised (44)",
      transliteration:
        "khāshiʿatan abṣāruhum tarhaquhum dhillatun dhālika l-yawmu alladhī kānū yūʿadūna ",
      verse: 5419,
      juz: 29,
      surah: 70,
    },
  ],
};
