import { Surah } from "../types/islam.js";

export const maun: Surah = {
  name: "Al-Ma'un",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "Have you seen the one who denies the Judgment (1)",
      transliteration: "ara-ayta alladhī yukadhibu bil-dīni ",
      verse: 6198,
      juz: 30,
      surah: 107,
    },
    {
      number: 2,
      image: "",
      text: "Then that (is) the one who repulses the orphan (2)",
      transliteration: "fadhālika alladhī yaduʿʿu l-yatīma ",
      verse: 6199,
      juz: 30,
      surah: 107,
    },
    {
      number: 3,
      image: "",
      text: "And (does) not feel the urge to feed the poor (3)",
      transliteration: "walā yaḥuḍḍu ʿalā ṭaʿāmi l-mis'kīni ",
      verse: 6200,
      juz: 30,
      surah: 107,
    },
    {
      number: 4,
      image: "",
      text: "So woe to those who pray (4)",
      transliteration: "fawaylun lil'muṣallīna ",
      verse: 6201,
      juz: 30,
      surah: 107,
    },
    {
      number: 5,
      image: "",
      text: "Those who [they] about their prayers (are) neglectful (5)",
      transliteration: "alladhīna hum ʿan ṣalātihim sāhūna ",
      verse: 6202,
      juz: 30,
      surah: 107,
    },
    {
      number: 6,
      image: "",
      text: "Those who [they] make show (6)",
      transliteration: "alladhīna hum yurāūna ",
      verse: 6203,
      juz: 30,
      surah: 107,
    },
    {
      number: 7,
      image: "",
      text: "And they deny [the] small kindnesses (7)",
      transliteration: "wayamnaʿūna l-māʿūna ",
      verse: 6204,
      juz: 30,
      surah: 107,
    },
  ],
};
