import { Surah } from "../types/islam.ts";

export const muddaththir: Surah = {
  name: "Al-Muddaththir",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "O you who covers himself [with a garment],",
      verse: 5365,
    },
    { number: 2, image: "", text: "Arise and warn", verse: 5366 },
    { number: 3, image: "", text: "And your Lord glorify", verse: 5367 },
    { number: 4, image: "", text: "And your clothing purify", verse: 5368 },
    { number: 5, image: "", text: "And uncleanliness avoid", verse: 5369 },
    {
      number: 6,
      image: "",
      text: "And do not confer favor to acquire more",
      verse: 5370,
    },
    {
      number: 7,
      image: "",
      text: "But for your Lord be patient.",
      verse: 5371,
    },
    {
      number: 8,
      image: "",
      text: "And when the trumpet is blown,",
      verse: 5372,
    },
    {
      number: 9,
      image: "",
      text: "That Day will be a difficult day",
      verse: 5373,
    },
    {
      number: 10,
      image: "",
      text: "For the disbelievers -  not easy.",
      verse: 5374,
    },
    {
      number: 11,
      image: "",
      text: "Leave Me with the one I created alone",
      verse: 5375,
    },
    {
      number: 12,
      image: "",
      text: "And to whom I granted extensive wealth",
      verse: 5376,
    },
    {
      number: 13,
      image: "",
      text: "And children present [with him]",
      verse: 5377,
    },
    {
      number: 14,
      image: "",
      text: "And spread [everything] before him, easing [his life].",
      verse: 5378,
    },
    {
      number: 15,
      image: "",
      text: "Then he desires that I should add more.",
      verse: 5379,
    },
    {
      number: 16,
      image: "",
      text: "No! Indeed, he has been toward Our verses obstinate.",
      verse: 5380,
    },
    {
      number: 17,
      image: "",
      text: "I will cover him with arduous torment.",
      verse: 5381,
    },
    {
      number: 18,
      image: "",
      text: "Indeed, he thought and deliberated.",
      verse: 5382,
    },
    {
      number: 19,
      image: "",
      text: "So may he be destroyed [for] how he deliberated.",
      verse: 5383,
    },
    {
      number: 20,
      image: "",
      text: "Then may he be destroyed [for] how he deliberated.",
      verse: 5384,
    },
    { number: 21, image: "", text: "Then he considered [again];", verse: 5385 },
    {
      number: 22,
      image: "",
      text: "Then he frowned and scowled;",
      verse: 5386,
    },
    {
      number: 23,
      image: "",
      text: "Then he turned back and was arrogant",
      verse: 5387,
    },
    {
      number: 24,
      image: "",
      text: 'And said, "This is not but magic imitated [from others].',
      verse: 5388,
    },
    {
      number: 25,
      image: "",
      text: 'This is not but the word of a human being."',
      verse: 5389,
    },
    {
      number: 26,
      image: "",
      text: "I will drive him into Saqar.",
      verse: 5390,
    },
    {
      number: 27,
      image: "",
      text: "And what can make you know what is Saqar?",
      verse: 5391,
    },
    {
      number: 28,
      image: "",
      text: "It lets nothing remain and leaves nothing [unburned],",
      verse: 5392,
    },
    { number: 29, image: "", text: "Blackening the skins.", verse: 5393 },
    {
      number: 30,
      image: "",
      text: "Over it are nineteen [angels].",
      verse: 5394,
    },
    {
      number: 31,
      image: "",
      text:
        'And We have not made the keepers of the Fire except angels. And We have not made their number except as a trial for those who disbelieve -  that those who were given the Scripture will be convinced and those who have believed will increase in faith and those who were given the Scripture and the believers will not doubt and that those in whose hearts is hypocrisy and the disbelievers will say, "What does Allah intend by this as an example?" Thus does Allah leave astray whom He wills and guides whom He wills. And none knows the soldiers of your Lord except Him. And mention of the Fire is not but a reminder to humanity.',
      verse: 5395,
    },
    { number: 32, image: "", text: "No! By the moon", verse: 5396 },
    {
      number: 33,
      image: "",
      text: "And [by] the night when it departs",
      verse: 5397,
    },
    {
      number: 34,
      image: "",
      text: "And [by] the morning when it brightens,",
      verse: 5398,
    },
    {
      number: 35,
      image: "",
      text: "Indeed, the Fire is of the greatest [afflictions]",
      verse: 5399,
    },
    { number: 36, image: "", text: "As a warning to humanity -", verse: 5400 },
    {
      number: 37,
      image: "",
      text: "To whoever wills among you to proceed or stay behind.",
      verse: 5401,
    },
    {
      number: 38,
      image: "",
      text: "Every soul, for what it has earned, will be retained",
      verse: 5402,
    },
    {
      number: 39,
      image: "",
      text: "Except the companions of the right,",
      verse: 5403,
    },
    {
      number: 40,
      image: "",
      text: "[Who will be] in gardens, questioning each other",
      verse: 5404,
    },
    { number: 41, image: "", text: "About the criminals,", verse: 5405 },
    {
      number: 42,
      image: "",
      text: '[And asking them], "What put you into Saqar?"',
      verse: 5406,
    },
    {
      number: 43,
      image: "",
      text: 'They will say, "We were not of those who prayed,',
      verse: 5407,
    },
    {
      number: 44,
      image: "",
      text: "Nor did we used to feed the poor.",
      verse: 5408,
    },
    {
      number: 45,
      image: "",
      text:
        "And we used to enter into vain discourse with those who engaged [in it],",
      verse: 5409,
    },
    {
      number: 46,
      image: "",
      text: "And we used to deny the Day of Recompense",
      verse: 5410,
    },
    {
      number: 47,
      image: "",
      text: 'Until there came to us the certainty."',
      verse: 5411,
    },
    {
      number: 48,
      image: "",
      text:
        "So there will not benefit them the intercession of [any] intercessors.",
      verse: 5412,
    },
    {
      number: 49,
      image: "",
      text:
        "Then what is [the matter] with them that they are, from the reminder, turning away",
      verse: 5413,
    },
    {
      number: 50,
      image: "",
      text: "As if they were alarmed donkeys",
      verse: 5414,
    },
    { number: 51, image: "", text: "Fleeing from a lion?", verse: 5415 },
    {
      number: 52,
      image: "",
      text:
        "Rather, every person among them desires that he would be given scriptures spread about.",
      verse: 5416,
    },
    {
      number: 53,
      image: "",
      text: "No! But they do not fear the Hereafter.",
      verse: 5417,
    },
    {
      number: 54,
      image: "",
      text: "No! Indeed, the Qur'an is a reminder",
      verse: 5418,
    },
    {
      number: 55,
      image: "",
      text: "Then whoever wills will remember it.",
      verse: 5419,
    },
    {
      number: 56,
      image: "",
      text:
        "And they will not remember except that Allah wills. He is worthy of fear and adequate for [granting] forgiveness.",
      verse: 5420,
    },
  ],
};
