import { Surah } from "../types/islam.js";

export const muddaththir: Surah = {
  name: "Al-Muddaththir",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "O you who covers himself (1)",
      transliteration: "yāayyuhā l-mudathiru ",
      verse: 5496,
      juz: 29,
      surah: 74,
    },
    {
      number: 2,
      image: "",
      text: "Stand up and warn (2)",
      transliteration: "qum fa-andhir ",
      verse: 5497,
      juz: 29,
      surah: 74,
    },
    {
      number: 3,
      image: "",
      text: "And your Lord magnify (3)",
      transliteration: "warabbaka fakabbir ",
      verse: 5498,
      juz: 29,
      surah: 74,
    },
    {
      number: 4,
      image: "",
      text: "And your clothing purify (4)",
      transliteration: "wathiyābaka faṭahhir ",
      verse: 5499,
      juz: 29,
      surah: 74,
    },
    {
      number: 5,
      image: "",
      text: "And uncleanliness avoid (5)",
      transliteration: "wal-ruj'za fa-uh'jur ",
      verse: 5500,
      juz: 29,
      surah: 74,
    },
    {
      number: 6,
      image: "",
      text: "And (do) not confer favor (to) acquire more (6)",
      transliteration: "walā tamnun tastakthiru ",
      verse: 5501,
      juz: 29,
      surah: 74,
    },
    {
      number: 7,
      image: "",
      text: "And for your Lord be patient (7)",
      transliteration: "walirabbika fa-iṣ'bir ",
      verse: 5502,
      juz: 29,
      surah: 74,
    },
    {
      number: 8,
      image: "",
      text: "Then when is blown in the trumpet (8)",
      transliteration: "fa-idhā nuqira fī l-nāqūri ",
      verse: 5503,
      juz: 29,
      surah: 74,
    },
    {
      number: 9,
      image: "",
      text: "That Day (will be) a Day difficult (9)",
      transliteration: "fadhālika yawma-idhin yawmun ʿasīrun ",
      verse: 5504,
      juz: 29,
      surah: 74,
    },
    {
      number: 10,
      image: "",
      text: "For the disbelievers  not easy (10)",
      transliteration: "ʿalā l-kāfirīna ghayru yasīrin ",
      verse: 5505,
      juz: 29,
      surah: 74,
    },
    {
      number: 11,
      image: "",
      text: "Leave Me and whom I created alone (11)",
      transliteration: "dharnī waman khalaqtu waḥīdan ",
      verse: 5506,
      juz: 29,
      surah: 74,
    },
    {
      number: 12,
      image: "",
      text: "And I granted to him wealth extensive (12)",
      transliteration: "wajaʿaltu lahu mālan mamdūdan ",
      verse: 5507,
      juz: 29,
      surah: 74,
    },
    {
      number: 13,
      image: "",
      text: "And children present (13)",
      transliteration: "wabanīna shuhūdan ",
      verse: 5508,
      juz: 29,
      surah: 74,
    },
    {
      number: 14,
      image: "",
      text: "And I spread for him ease (14)",
      transliteration: "wamahhadttu lahu tamhīdan ",
      verse: 5509,
      juz: 29,
      surah: 74,
    },
    {
      number: 15,
      image: "",
      text: "Then he desires that I (should) add more (15)",
      transliteration: "thumma yaṭmaʿu an azīda ",
      verse: 5510,
      juz: 29,
      surah: 74,
    },
    {
      number: 16,
      image: "",
      text: "By no means Indeed, he has been to Our Verses stubborn (16)",
      transliteration: "kallā innahu kāna liāyātinā ʿanīdan ",
      verse: 5511,
      juz: 29,
      surah: 74,
    },
    {
      number: 17,
      image: "",
      text: "Soon I will cover Him (with) a laborious punishment (17)",
      transliteration: "sa-ur'hiquhu ṣaʿūdan ",
      verse: 5512,
      juz: 29,
      surah: 74,
    },
    {
      number: 18,
      image: "",
      text: "Indeed, he thought and plotted (18)",
      transliteration: "innahu fakkara waqaddara ",
      verse: 5513,
      juz: 29,
      surah: 74,
    },
    {
      number: 19,
      image: "",
      text: "So may he be destroyed how he plotted (19)",
      transliteration: "faqutila kayfa qaddara ",
      verse: 5514,
      juz: 29,
      surah: 74,
    },
    {
      number: 20,
      image: "",
      text: "Then may he be destroyed how he plotted (20)",
      transliteration: "thumma qutila kayfa qaddara ",
      verse: 5515,
      juz: 29,
      surah: 74,
    },
    {
      number: 21,
      image: "",
      text: "Then he looked (21)",
      transliteration: "thumma naẓara ",
      verse: 5516,
      juz: 29,
      surah: 74,
    },
    {
      number: 22,
      image: "",
      text: "Then he frowned and scowled (22)",
      transliteration: "thumma ʿabasa wabasara ",
      verse: 5517,
      juz: 29,
      surah: 74,
    },
    {
      number: 23,
      image: "",
      text: "Then he turned back and was proud (23)",
      transliteration: "thumma adbara wa-is'takbara ",
      verse: 5518,
      juz: 29,
      surah: 74,
    },
    {
      number: 24,
      image: "",
      text: "Then he said Not (is) this but magic imitated (24)",
      transliteration: "faqāla in hādhā illā siḥ'run yu'tharu ",
      verse: 5519,
      juz: 29,
      surah: 74,
    },
    {
      number: 25,
      image: "",
      text: "Not (is) this but (the) word (of) a human being (25)",
      transliteration: "in hādhā illā qawlu l-bashari ",
      verse: 5520,
      juz: 29,
      surah: 74,
    },
    {
      number: 26,
      image: "",
      text: "Soon I will drive him (into) Hell (26)",
      transliteration: "sa-uṣ'līhi saqara ",
      verse: 5521,
      juz: 29,
      surah: 74,
    },
    {
      number: 27,
      image: "",
      text: "And what can make you know what (is) Hell (27)",
      transliteration: "wamā adrāka mā saqaru ",
      verse: 5522,
      juz: 29,
      surah: 74,
    },
    {
      number: 28,
      image: "",
      text: "Not it lets remain and not it leaves (28)",
      transliteration: "lā tub'qī walā tadharu ",
      verse: 5523,
      juz: 29,
      surah: 74,
    },
    {
      number: 29,
      image: "",
      text: "Scorching the human (skin) (29)",
      transliteration: "lawwāḥatun lil'bashari ",
      verse: 5524,
      juz: 29,
      surah: 74,
    },
    {
      number: 30,
      image: "",
      text: "Over it (are) nine teen (30)",
      transliteration: "ʿalayhā tis'ʿata ʿashara ",
      verse: 5525,
      juz: 29,
      surah: 74,
    },
    {
      number: 31,
      image: "",
      text: "And not We have made keepers (of) the Fire except Angels And not We have made their number except (as) a trial for those who disbelieve  that may be certain those who were given the Scripture and may increase those who believe (in) faith and not may doubt those who were given the Scripture and the believers and that may say those in their hearts (is) a disease and the disbelievers What (does) intend Allah by this example Thus does let go astray Allah whom He wills and guides whom He wills And none knows (the) hosts (of) your Lord except Him And not it (is) but a reminder to (the) human beings (31)",
      transliteration:
        "wamā jaʿalnā aṣḥāba l-nāri illā malāikatan wamā jaʿalnā ʿiddatahum illā fit'natan lilladhīna kafarū liyastayqina alladhīna ūtū l-kitāba wayazdāda alladhīna āmanū īmānan walā yartāba alladhīna ūtū l-kitāba wal-mu'minūna waliyaqūla alladhīna fī qulūbihim maraḍun wal-kāfirūna mādhā arāda l-lahu bihādhā mathalan kadhālika yuḍillu l-lahu man yashāu wayahdī man yashāu wamā yaʿlamu junūda rabbika illā huwa wamā hiya illā dhik'rā lil'bashari ",
      verse: 5526,
      juz: 29,
      surah: 74,
    },
    {
      number: 32,
      image: "",
      text: "Nay By the moon (32)",
      transliteration: "kallā wal-qamari ",
      verse: 5527,
      juz: 29,
      surah: 74,
    },
    {
      number: 33,
      image: "",
      text: "And the night when it departs (33)",
      transliteration: "wa-al-layli idh adbara ",
      verse: 5528,
      juz: 29,
      surah: 74,
    },
    {
      number: 34,
      image: "",
      text: "And the morning when it brightens (34)",
      transliteration: "wal-ṣub'ḥi idhā asfara ",
      verse: 5529,
      juz: 29,
      surah: 74,
    },
    {
      number: 35,
      image: "",
      text: "Indeed, it (is) surely one (of) the greatest (35)",
      transliteration: "innahā la-iḥ'dā l-kubari ",
      verse: 5530,
      juz: 29,
      surah: 74,
    },
    {
      number: 36,
      image: "",
      text: "A warning to (the) human being (36)",
      transliteration: "nadhīran lil'bashari ",
      verse: 5531,
      juz: 29,
      surah: 74,
    },
    {
      number: 37,
      image: "",
      text: "To whoever wills among you to proceed or stay behind (37)",
      transliteration: "liman shāa minkum an yataqaddama aw yata-akhara ",
      verse: 5532,
      juz: 29,
      surah: 74,
    },
    {
      number: 38,
      image: "",
      text: "Every soul for what it has earned (is) pledged (38)",
      transliteration: "kullu nafsin bimā kasabat rahīnatun ",
      verse: 5533,
      juz: 29,
      surah: 74,
    },
    {
      number: 39,
      image: "",
      text: "Except (the) companions (of) the right (39)",
      transliteration: "illā aṣḥāba l-yamīni ",
      verse: 5534,
      juz: 29,
      surah: 74,
    },
    {
      number: 40,
      image: "",
      text: "In Gardens asking each other (40)",
      transliteration: "fī jannātin yatasāalūna ",
      verse: 5535,
      juz: 29,
      surah: 74,
    },
    {
      number: 41,
      image: "",
      text: "About the criminals (41)",
      transliteration: "ʿani l-muj'rimīna ",
      verse: 5536,
      juz: 29,
      surah: 74,
    },
    {
      number: 42,
      image: "",
      text: "What led you into Hell (42)",
      transliteration: "mā salakakum fī saqara ",
      verse: 5537,
      juz: 29,
      surah: 74,
    },
    {
      number: 43,
      image: "",
      text: "They will say Not we were of those who prayed (43)",
      transliteration: "qālū lam naku mina l-muṣalīna ",
      verse: 5538,
      juz: 29,
      surah: 74,
    },
    {
      number: 44,
      image: "",
      text: "And not we used to feed the poor (44)",
      transliteration: "walam naku nuṭ'ʿimu l-mis'kīna ",
      verse: 5539,
      juz: 29,
      surah: 74,
    },
    {
      number: 45,
      image: "",
      text: "And we used to indulge in vain talk with the vain talkers (45)",
      transliteration: "wakunnā nakhūḍu maʿa l-khāiḍīna ",
      verse: 5540,
      juz: 29,
      surah: 74,
    },
    {
      number: 46,
      image: "",
      text: "And we used to deny (the) Day (of) the Judgment (46)",
      transliteration: "wakunnā nukadhibu biyawmi l-dīni ",
      verse: 5541,
      juz: 29,
      surah: 74,
    },
    {
      number: 47,
      image: "",
      text: "Until came to us the certainty (47)",
      transliteration: "ḥattā atānā l-yaqīnu ",
      verse: 5542,
      juz: 29,
      surah: 74,
    },
    {
      number: 48,
      image: "",
      text: "Then not will benefit them intercession (of) the intercessors (48)",
      transliteration: "famā tanfaʿuhum shafāʿatu l-shāfiʿīna ",
      verse: 5543,
      juz: 29,
      surah: 74,
    },
    {
      number: 49,
      image: "",
      text: "Then what (is) for them (that) from the Reminder they (are) turning away (49)",
      transliteration: "famā lahum ʿani l-tadhkirati muʿ'riḍīna ",
      verse: 5544,
      juz: 29,
      surah: 74,
    },
    {
      number: 50,
      image: "",
      text: "As if they (were) donkeys frightened (50)",
      transliteration: "ka-annahum ḥumurun mus'tanfiratun ",
      verse: 5545,
      juz: 29,
      surah: 74,
    },
    {
      number: 51,
      image: "",
      text: "Fleeing from a lion (51)",
      transliteration: "farrat min qaswaratin ",
      verse: 5546,
      juz: 29,
      surah: 74,
    },
    {
      number: 52,
      image: "",
      text: "Nay Desires every person of them that he may be given pages spread out (52)",
      transliteration:
        "bal yurīdu kullu im'ri-in min'hum an yu'tā ṣuḥufan munasharatan ",
      verse: 5547,
      juz: 29,
      surah: 74,
    },
    {
      number: 53,
      image: "",
      text: "Nay But not they fear the Hereafter (53)",
      transliteration: "kallā bal lā yakhāfūna l-ākhirata ",
      verse: 5548,
      juz: 29,
      surah: 74,
    },
    {
      number: 54,
      image: "",
      text: "Nay Indeed, it (is) a Reminder (54)",
      transliteration: "kallā innahu tadhkiratun ",
      verse: 5549,
      juz: 29,
      surah: 74,
    },
    {
      number: 55,
      image: "",
      text: "So whoever wills (may) pay heed to it (55)",
      transliteration: "faman shāa dhakarahu ",
      verse: 5550,
      juz: 29,
      surah: 74,
    },
    {
      number: 56,
      image: "",
      text: "And not will pay heed except that wills Allah He (is) worthy to be feared and worthy to forgive (56)",
      transliteration:
        "wamā yadhkurūna illā an yashāa l-lahu huwa ahlu l-taqwā wa-ahlu l-maghfirati ",
      verse: 5551,
      juz: 29,
      surah: 74,
    },
  ],
};
