import { Surah } from "../types/islam.js";

export const muminun: Surah = {
  name: "Al-Mu'minun",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "Indeed successful (are) the believers (1)",
      transliteration: "qad aflaḥa l-mu'minūna ",
      verse: 2674,
      juz: 18,
      surah: 23,
    },
    {
      number: 2,
      image: "",
      text: "Those who [they] during their prayers (are) humbly submissive (2)",
      transliteration: "alladhīna hum fī ṣalātihim khāshiʿūna ",
      verse: 2675,
      juz: 18,
      surah: 23,
    },
    {
      number: 3,
      image: "",
      text: "Those who [they] from the vain talk turn away (3)",
      transliteration: "wa-alladhīna hum ʿani l-laghwi muʿ'riḍūna ",
      verse: 2676,
      juz: 18,
      surah: 23,
    },
    {
      number: 4,
      image: "",
      text: "Those who [they] of purification works (are) doers (4)",
      transliteration: "wa-alladhīna hum lilzzakati fāʿilūna ",
      verse: 2677,
      juz: 18,
      surah: 23,
    },
    {
      number: 5,
      image: "",
      text: "And those who [they] of their modesty (are) guardians (5)",
      transliteration: "wa-alladhīna hum lifurūjihim ḥāfiẓūna ",
      verse: 2678,
      juz: 18,
      surah: 23,
    },
    {
      number: 6,
      image: "",
      text: "Except from their spouses or what possess their right hands then indeed, they (are) not blameworthy (6)",
      transliteration:
        "illā ʿalā azwājihim aw mā malakat aymānuhum fa-innahum ghayru malūmīna ",
      verse: 2679,
      juz: 18,
      surah: 23,
    },
    {
      number: 7,
      image: "",
      text: "Then whoever seeks beyond that then those [they] (are) the transgressors (7)",
      transliteration: "famani ib'taghā warāa dhālika fa-ulāika humu l-ʿādūna ",
      verse: 2680,
      juz: 18,
      surah: 23,
    },
    {
      number: 8,
      image: "",
      text: "And those who [they] of their trusts and their promise(s) (are) observers (8)",
      transliteration: "wa-alladhīna hum li-amānātihim waʿahdihim rāʿūna ",
      verse: 2681,
      juz: 18,
      surah: 23,
    },
    {
      number: 9,
      image: "",
      text: "And those who [they] over their prayers they guard (9)",
      transliteration: "wa-alladhīna hum ʿalā ṣalawātihim yuḥāfiẓūna ",
      verse: 2682,
      juz: 18,
      surah: 23,
    },
    {
      number: 10,
      image: "",
      text: "Those [they] (are) the inheritors (10)",
      transliteration: "ulāika humu l-wārithūna ",
      verse: 2683,
      juz: 18,
      surah: 23,
    },
    {
      number: 11,
      image: "",
      text: "Who will inherit the Paradise They therein (will) abide forever (11)",
      transliteration: "alladhīna yarithūna l-fir'dawsa hum fīhā khālidūna ",
      verse: 2684,
      juz: 18,
      surah: 23,
    },
    {
      number: 12,
      image: "",
      text: "And indeed We created the humankind from an essence of clay (12)",
      transliteration: "walaqad khalaqnā l-insāna min sulālatin min ṭīnin ",
      verse: 2685,
      juz: 18,
      surah: 23,
    },
    {
      number: 13,
      image: "",
      text: "Then We placed him (as) a semen-drop in a resting place firm (13)",
      transliteration: "thumma jaʿalnāhu nuṭ'fatan fī qarārin makīnin ",
      verse: 2686,
      juz: 18,
      surah: 23,
    },
    {
      number: 14,
      image: "",
      text: "Then We created the semen-drop (into) a clinging substance then We created the clinging substance (into) an embryonic lump then We created the embryonic lump (into) bones then We clothed the bones (with) flesh then We produce it (as) a creation another So blessed is Allah (the) Best (of) the Creators (14)",
      transliteration:
        "thumma khalaqnā l-nuṭ'fata ʿalaqatan fakhalaqnā l-ʿalaqata muḍ'ghatan fakhalaqnā l-muḍ'ghata ʿiẓāman fakasawnā l-ʿiẓāma laḥman thumma anshanāhu khalqan ākhara fatabāraka l-lahu aḥsanu l-khāliqīna ",
      verse: 2687,
      juz: 18,
      surah: 23,
    },
    {
      number: 15,
      image: "",
      text: "Then indeed, you after that surely (will) die (15)",
      transliteration: "thumma innakum baʿda dhālika lamayyitūna ",
      verse: 2688,
      juz: 18,
      surah: 23,
    },
    {
      number: 16,
      image: "",
      text: "Then indeed, you (on the) Day (of) the Resurrection will be resurrected (16)",
      transliteration: "thumma innakum yawma l-qiyāmati tub'ʿathūna ",
      verse: 2689,
      juz: 18,
      surah: 23,
    },
    {
      number: 17,
      image: "",
      text: "And indeed We (have) created above you seven paths and not We are of the creation unaware (17)",
      transliteration:
        "walaqad khalaqnā fawqakum sabʿa ṭarāiqa wamā kunnā ʿani l-khalqi ghāfilīna ",
      verse: 2690,
      juz: 18,
      surah: 23,
    },
    {
      number: 18,
      image: "",
      text: "And We send down from the sky water in (due) measure then We cause it to settle in the earth And indeed, We on taking it away taking it away surely (are) Able (18)",
      transliteration:
        "wa-anzalnā mina l-samāi māan biqadarin fa-askannāhu fī l-arḍi wa-innā ʿalā dhahābin bihi laqādirūna ",
      verse: 2691,
      juz: 18,
      surah: 23,
    },
    {
      number: 19,
      image: "",
      text: "Then We produced for you by it gardens of date-palms of date-palms and grapevines for you in it (are) fruits abundant and from them you eat (19)",
      transliteration:
        "fa-anshanā lakum bihi jannātin min nakhīlin wa-aʿnābin lakum fīhā fawākihu kathīratun wamin'hā takulūna ",
      verse: 2692,
      juz: 18,
      surah: 23,
    },
    {
      number: 20,
      image: "",
      text: "And a tree (that) springs forth from Mount Sinai Mount Sinai (which) produces oil and a relish for those who eat (20)",
      transliteration:
        "washajaratan takhruju min ṭūri saynāa tanbutu bil-duh'ni waṣib'ghin lil'ākilīna ",
      verse: 2693,
      juz: 18,
      surah: 23,
    },
    {
      number: 21,
      image: "",
      text: "And indeed for you in the cattle surely, (is) a lesson We give you drink from what (is) in their bellies and for you in them (are) benefits many and of them you eat (21)",
      transliteration:
        "wa-inna lakum fī l-anʿāmi laʿib'ratan nus'qīkum mimmā fī buṭūnihā walakum fīhā manāfiʿu kathīratun wamin'hā takulūna ",
      verse: 2694,
      juz: 18,
      surah: 23,
    },
    {
      number: 22,
      image: "",
      text: "And on them and on [the] ships you are carried (22)",
      transliteration: "waʿalayhā waʿalā l-ful'ki tuḥ'malūna ",
      verse: 2695,
      juz: 18,
      surah: 23,
    },
    {
      number: 23,
      image: "",
      text: "And verily We sent Nuh to his people and he said O my people Worship Allah not for you (is) any god other than Him Then will not you fear (23)",
      transliteration:
        "walaqad arsalnā nūḥan ilā qawmihi faqāla yāqawmi uʿ'budū l-laha mā lakum min ilāhin ghayruhu afalā tattaqūna ",
      verse: 2696,
      juz: 18,
      surah: 23,
    },
    {
      number: 24,
      image: "",
      text: "But said the chiefs (of) those who disbelieved among his people This is not This is not but a man like you he wishes to assert (his) superiority over you and if Allah had willed Allah had willed surely He (would have) sent down Angels Not we heard of this from our forefathers our forefathers (24)",
      transliteration:
        "faqāla l-mala-u alladhīna kafarū min qawmihi mā hādhā illā basharun mith'lukum yurīdu an yatafaḍḍala ʿalaykum walaw shāa l-lahu la-anzala malāikatan mā samiʿ'nā bihādhā fī ābāinā l-awalīna ",
      verse: 2697,
      juz: 18,
      surah: 23,
    },
    {
      number: 25,
      image: "",
      text: "Not he (is) but a man in him (is) madness so wait concerning him until a time (25)",
      transliteration:
        "in huwa illā rajulun bihi jinnatun fatarabbaṣū bihi ḥattā ḥīnin ",
      verse: 2698,
      juz: 18,
      surah: 23,
    },
    {
      number: 26,
      image: "",
      text: "He said My Lord Help me because they deny me (26)",
      transliteration: "qāla rabbi unṣur'nī bimā kadhabūni ",
      verse: 2699,
      juz: 18,
      surah: 23,
    },
    {
      number: 27,
      image: "",
      text: "So We inspired to him That construct the ship under Our eyes and Our inspiration then when comes Our Command and gushes forth the oven then put into it of every (kind) (of) mates two and your family except those (has) preceded against whom the Word thereof And (do) not address Me concerning those who wronged indeed, they (are) the ones to be drowned (27)",
      transliteration:
        "fa-awḥaynā ilayhi ani iṣ'naʿi l-ful'ka bi-aʿyuninā wawaḥyinā fa-idhā jāa amrunā wafāra l-tanūru fa-us'luk fīhā min kullin zawjayni ith'nayni wa-ahlaka illā man sabaqa ʿalayhi l-qawlu min'hum walā tukhāṭib'nī fī alladhīna ẓalamū innahum mugh'raqūna ",
      verse: 2700,
      juz: 18,
      surah: 23,
    },
    {
      number: 28,
      image: "",
      text: "And when you (have) boarded you and whoever (is) with you [on] the ship then say Praise (be) to Allah Who (has) saved us from the people  the wrongdoers (28)",
      transliteration:
        "fa-idhā is'tawayta anta waman maʿaka ʿalā l-ful'ki faquli l-ḥamdu lillahi alladhī najjānā mina l-qawmi l-ẓālimīna ",
      verse: 2701,
      juz: 18,
      surah: 23,
    },
    {
      number: 29,
      image: "",
      text: "And say My Lord cause me to land (at) a landing place blessed and You (are) the Best (of) those who cause to land.' (29)",
      transliteration:
        "waqul rabbi anzil'nī munzalan mubārakan wa-anta khayru l-munzilīna ",
      verse: 2702,
      juz: 18,
      surah: 23,
    },
    {
      number: 30,
      image: "",
      text: "Indeed in that surely (are) Signs and indeed We are surely testing (30)",
      transliteration: "inna fī dhālika laāyātin wa-in kunnā lamub'talīna ",
      verse: 2703,
      juz: 18,
      surah: 23,
    },
    {
      number: 31,
      image: "",
      text: "Then We produced after them after them a generation another (31)",
      transliteration: "thumma anshanā min baʿdihim qarnan ākharīna ",
      verse: 2704,
      juz: 18,
      surah: 23,
    },
    {
      number: 32,
      image: "",
      text: "And We sent among them a Messenger from themselves [that] Worship Allah not for you (is) any god other than Him Then will not you fear (32)",
      transliteration:
        "fa-arsalnā fīhim rasūlan min'hum ani uʿ'budū l-laha mā lakum min ilāhin ghayruhu afalā tattaqūna ",
      verse: 2705,
      juz: 18,
      surah: 23,
    },
    {
      number: 33,
      image: "",
      text: "And said the chiefs of his people who disbelieved and denied (the) meeting (of) the Hereafter while We had given them luxury in the life (of) the world Not (is) this but a man like you He eats of what you eat [from it] and he drinks of what you drink (33)",
      transliteration:
        "waqāla l-mala-u min qawmihi alladhīna kafarū wakadhabū biliqāi l-ākhirati wa-atrafnāhum fī l-ḥayati l-dun'yā mā hādhā illā basharun mith'lukum yakulu mimmā takulūna min'hu wayashrabu mimmā tashrabūna ",
      verse: 2706,
      juz: 18,
      surah: 23,
    },
    {
      number: 34,
      image: "",
      text: "And surely if you obey a man like you indeed, you then surely (will be) losers (34)",
      transliteration:
        "wala-in aṭaʿtum basharan mith'lakum innakum idhan lakhāsirūna ",
      verse: 2707,
      juz: 18,
      surah: 23,
    },
    {
      number: 35,
      image: "",
      text: "Does he promise you  that you when you are dead and you become dust and bones that you (will be) brought forth (35)",
      transliteration:
        "ayaʿidukum annakum idhā mittum wakuntum turāban waʿiẓāman annakum mukh'rajūna ",
      verse: 2708,
      juz: 18,
      surah: 23,
    },
    {
      number: 36,
      image: "",
      text: "Far-(fetched) far-(fetched) is what you are promised (36)",
      transliteration: "hayhāta hayhāta limā tūʿadūna ",
      verse: 2709,
      juz: 18,
      surah: 23,
    },
    {
      number: 37,
      image: "",
      text: "Not it (is) but our life (of) the world we die and we live and not we (will be) resurrected (37)",
      transliteration:
        "in hiya illā ḥayātunā l-dun'yā namūtu wanaḥyā wamā naḥnu bimabʿūthīna ",
      verse: 2710,
      juz: 18,
      surah: 23,
    },
    {
      number: 38,
      image: "",
      text: "Not (is) he but a man who (has) invented about Allah a lie and not we (in) him (are) believers (38)",
      transliteration:
        "in huwa illā rajulun if'tarā ʿalā l-lahi kadhiban wamā naḥnu lahu bimu'minīna ",
      verse: 2711,
      juz: 18,
      surah: 23,
    },
    {
      number: 39,
      image: "",
      text: "He said My Lord Help me because they deny me (39)",
      transliteration: "qāla rabbi unṣur'nī bimā kadhabūni ",
      verse: 2712,
      juz: 18,
      surah: 23,
    },
    {
      number: 40,
      image: "",
      text: "He said After a little while After a little while surely they will become regretful (40)",
      transliteration: "qāla ʿammā qalīlin layuṣ'biḥunna nādimīna ",
      verse: 2713,
      juz: 18,
      surah: 23,
    },
    {
      number: 41,
      image: "",
      text: "So seized them the awful cry in truth and We made them (as) rubbish of dead leaves So away with the people  the wrongdoers (41)",
      transliteration:
        "fa-akhadhathumu l-ṣayḥatu bil-ḥaqi fajaʿalnāhum ghuthāan fabuʿ'dan lil'qawmi l-ẓālimīna ",
      verse: 2714,
      juz: 18,
      surah: 23,
    },
    {
      number: 42,
      image: "",
      text: "Then We produced after them after them a generation another (42)",
      transliteration: "thumma anshanā min baʿdihim qurūnan ākharīna ",
      verse: 2715,
      juz: 18,
      surah: 23,
    },
    {
      number: 43,
      image: "",
      text: "Not can precede any nation its term and not they (can) delay (it) (43)",
      transliteration: "mā tasbiqu min ummatin ajalahā wamā yastakhirūna ",
      verse: 2716,
      juz: 18,
      surah: 23,
    },
    {
      number: 44,
      image: "",
      text: "Then We sent Our Messengers (in) succession Every time Every time came (to) a nation its Messenger they denied him so We made (them) follow  some of them others and We made them narrations So away with a people  not they believe (44)",
      transliteration:
        "thumma arsalnā rusulanā tatrā kulla mā jāa ummatan rasūluhā kadhabūhu fa-atbaʿnā baʿḍahum baʿḍan wajaʿalnāhum aḥādītha fabuʿ'dan liqawmin lā yu'minūna ",
      verse: 2717,
      juz: 18,
      surah: 23,
    },
    {
      number: 45,
      image: "",
      text: "Then We sent Musa and his brother Harun with Our Signs and an authority clear (45)",
      transliteration:
        "thumma arsalnā mūsā wa-akhāhu hārūna biāyātinā wasul'ṭānin mubīnin ",
      verse: 2718,
      juz: 18,
      surah: 23,
    },
    {
      number: 46,
      image: "",
      text: "To Firaun and his chiefs but they behaved arrogantly and they were a people haughty (46)",
      transliteration:
        "ilā fir'ʿawna wamala-ihi fa-is'takbarū wakānū qawman ʿālīna ",
      verse: 2719,
      juz: 18,
      surah: 23,
    },
    {
      number: 47,
      image: "",
      text: "Then they said Shall we believe (in) two men like ourselves while their people for us (are) slaves (47)",
      transliteration:
        "faqālū anu'minu libasharayni mith'linā waqawmuhumā lanā ʿābidūna ",
      verse: 2720,
      juz: 18,
      surah: 23,
    },
    {
      number: 48,
      image: "",
      text: "So they denied them and they became of those who were destroyed (48)",
      transliteration: "fakadhabūhumā fakānū mina l-muh'lakīna ",
      verse: 2721,
      juz: 18,
      surah: 23,
    },
    {
      number: 49,
      image: "",
      text: "And verily We gave Musa the Scripture so that they may be guided (49)",
      transliteration: "walaqad ātaynā mūsā l-kitāba laʿallahum yahtadūna ",
      verse: 2722,
      juz: 18,
      surah: 23,
    },
    {
      number: 50,
      image: "",
      text: "And We made (the) son (of) Maryam and his mother a Sign and We sheltered them to a high ground of tranquility of tranquility and water springs (50)",
      transliteration:
        "wajaʿalnā ib'na maryama wa-ummahu āyatan waāwaynāhumā ilā rabwatin dhāti qarārin wamaʿīnin ",
      verse: 2723,
      juz: 18,
      surah: 23,
    },
    {
      number: 51,
      image: "",
      text: "O Messengers O Messengers Eat of the good things and do righteous (deeds) Indeed, I Am of what you do All-Knower (51)",
      transliteration:
        "yāayyuhā l-rusulu kulū mina l-ṭayibāti wa-iʿ'malū ṣāliḥan innī bimā taʿmalūna ʿalīmun ",
      verse: 2724,
      juz: 18,
      surah: 23,
    },
    {
      number: 52,
      image: "",
      text: "And indeed this your religion (is) religion one And I Am your Lord so fear Me (52)",
      transliteration:
        "wa-inna hādhihi ummatukum ummatan wāḥidatan wa-anā rabbukum fa-ittaqūni ",
      verse: 2725,
      juz: 18,
      surah: 23,
    },
    {
      number: 53,
      image: "",
      text: "But they cut off their affair (of unity) between them (into) sects each faction in what they have rejoicing (53)",
      transliteration:
        "fataqaṭṭaʿū amrahum baynahum zuburan kullu ḥiz'bin bimā ladayhim fariḥūna ",
      verse: 2726,
      juz: 18,
      surah: 23,
    },
    {
      number: 54,
      image: "",
      text: "So leave them in their confusion until a time (54)",
      transliteration: "fadharhum fī ghamratihim ḥattā ḥīnin ",
      verse: 2727,
      juz: 18,
      surah: 23,
    },
    {
      number: 55,
      image: "",
      text: "Do they think that what We extend to them [with it] of wealth and children (55)",
      transliteration: "ayaḥsabūna annamā numidduhum bihi min mālin wabanīna ",
      verse: 2728,
      juz: 18,
      surah: 23,
    },
    {
      number: 56,
      image: "",
      text: "We hasten to them in the good Nay not they perceive (56)",
      transliteration: "nusāriʿu lahum fī l-khayrāti bal lā yashʿurūna ",
      verse: 2729,
      juz: 18,
      surah: 23,
    },
    {
      number: 57,
      image: "",
      text: "Indeed those who [they] from (the) fear (of) their Lord (are) cautious (57)",
      transliteration: "inna alladhīna hum min khashyati rabbihim mush'fiqūna ",
      verse: 2730,
      juz: 18,
      surah: 23,
    },
    {
      number: 58,
      image: "",
      text: "And those [they] in (the) Signs (of) their Lord believe (58)",
      transliteration: "wa-alladhīna hum biāyāti rabbihim yu'minūna ",
      verse: 2731,
      juz: 18,
      surah: 23,
    },
    {
      number: 59,
      image: "",
      text: "And those [they] with their Lord (do) not associate partners (59)",
      transliteration: "wa-alladhīna hum birabbihim lā yush'rikūna ",
      verse: 2732,
      juz: 18,
      surah: 23,
    },
    {
      number: 60,
      image: "",
      text: "And those who give what they give while their hearts (are) fearful because they to their Lord (will) return (60)",
      transliteration:
        "wa-alladhīna yu'tūna mā ātaw waqulūbuhum wajilatun annahum ilā rabbihim rājiʿūna ",
      verse: 2733,
      juz: 18,
      surah: 23,
    },
    {
      number: 61,
      image: "",
      text: "(It is) those who hasten in the good (deeds) and they in them (are) foremost (61)",
      transliteration: "ulāika yusāriʿūna fī l-khayrāti wahum lahā sābiqūna ",
      verse: 2734,
      juz: 18,
      surah: 23,
    },
    {
      number: 62,
      image: "",
      text: "And not We burden any soul except (to) its capacity and with Us (is) a Record (which) speaks with the truth and they (will) not be wronged (62)",
      transliteration:
        "walā nukallifu nafsan illā wus'ʿahā waladaynā kitābun yanṭiqu bil-ḥaqi wahum lā yuẓ'lamūna ",
      verse: 2735,
      juz: 18,
      surah: 23,
    },
    {
      number: 63,
      image: "",
      text: "Nay their hearts (are) in confusion over this and for them (are) deeds besides besides that they for it (are) doers (63)",
      transliteration:
        "bal qulūbuhum fī ghamratin min hādhā walahum aʿmālun min dūni dhālika hum lahā ʿāmilūna ",
      verse: 2736,
      juz: 18,
      surah: 23,
    },
    {
      number: 64,
      image: "",
      text: "Until when We seize their affluent ones with the punishment behold They cry for help (64)",
      transliteration:
        "ḥattā idhā akhadhnā mut'rafīhim bil-ʿadhābi idhā hum yajarūna ",
      verse: 2737,
      juz: 18,
      surah: 23,
    },
    {
      number: 65,
      image: "",
      text: "(Do) not cry for help today Indeed, you from Us not will be helped (65)",
      transliteration: "lā tajarū l-yawma innakum minnā lā tunṣarūna ",
      verse: 2738,
      juz: 18,
      surah: 23,
    },
    {
      number: 66,
      image: "",
      text: "Verily were My Verses recited to you but you used (to) on your heels turn back (66)",
      transliteration:
        "qad kānat āyātī tut'lā ʿalaykum fakuntum ʿalā aʿqābikum tankiṣūna ",
      verse: 2739,
      juz: 18,
      surah: 23,
    },
    {
      number: 67,
      image: "",
      text: "(Being) arrogant about it conversing by night speaking evil (67)",
      transliteration: "mus'takbirīna bihi sāmiran tahjurūna ",
      verse: 2740,
      juz: 18,
      surah: 23,
    },
    {
      number: 68,
      image: "",
      text: "Then, do not they ponder the Word or has come to them what not (had) come (to) their forefathers (to) their forefathers (68)",
      transliteration:
        "afalam yaddabbarū l-qawla am jāahum mā lam yati ābāahumu l-awalīna ",
      verse: 2741,
      juz: 18,
      surah: 23,
    },
    {
      number: 69,
      image: "",
      text: "Or (do) not they recognize their Messenger so they (are) rejecting him (are) rejecting him (69)",
      transliteration: "am lam yaʿrifū rasūlahum fahum lahu munkirūna ",
      verse: 2742,
      juz: 18,
      surah: 23,
    },
    {
      number: 70,
      image: "",
      text: "Or they say In him (is) madness Nay he brought them the truth but most of them to the truth (are) averse (70)",
      transliteration:
        "am yaqūlūna bihi jinnatun bal jāahum bil-ḥaqi wa-aktharuhum lil'ḥaqqi kārihūna ",
      verse: 2743,
      juz: 18,
      surah: 23,
    },
    {
      number: 71,
      image: "",
      text: "But if (had) followed the truth their desires surely (would) have been corrupted the heavens and the earth and whoever (is) therein Nay We have brought them their reminder but they from their reminder (are) turning away (71)",
      transliteration:
        "walawi ittabaʿa l-ḥaqu ahwāahum lafasadati l-samāwātu wal-arḍu waman fīhinna bal ataynāhum bidhik'rihim fahum ʿan dhik'rihim muʿ'riḍūna ",
      verse: 2744,
      juz: 18,
      surah: 23,
    },
    {
      number: 72,
      image: "",
      text: "Or you ask them (for) a payment But the payment (of) your Lord (is) best and He (is) the Best (of) the Providers (72)",
      transliteration:
        "am tasaluhum kharjan fakharāju rabbika khayrun wahuwa khayru l-rāziqīna ",
      verse: 2745,
      juz: 18,
      surah: 23,
    },
    {
      number: 73,
      image: "",
      text: "And indeed, you certainly call them to (the) Path Straight (73)",
      transliteration: "wa-innaka latadʿūhum ilā ṣirāṭin mus'taqīmin ",
      verse: 2746,
      juz: 18,
      surah: 23,
    },
    {
      number: 74,
      image: "",
      text: "And indeed those who (do) not believe in the Hereafter from the path surely (are) deviating (74)",
      transliteration:
        "wa-inna alladhīna lā yu'minūna bil-ākhirati ʿani l-ṣirāṭi lanākibūna ",
      verse: 2747,
      juz: 18,
      surah: 23,
    },
    {
      number: 75,
      image: "",
      text: "And if We had mercy on them and We removed what (was) on them of (the) hardship surely they would persist in their transgression wandering blindly (75)",
      transliteration:
        "walaw raḥim'nāhum wakashafnā mā bihim min ḍurrin lalajjū fī ṭugh'yānihim yaʿmahūna ",
      verse: 2748,
      juz: 18,
      surah: 23,
    },
    {
      number: 76,
      image: "",
      text: "And verily We seized them with the punishment but not they submit to their Lord and not they supplicate humbly (76)",
      transliteration:
        "walaqad akhadhnāhum bil-ʿadhābi famā is'takānū lirabbihim wamā yataḍarraʿūna ",
      verse: 2749,
      juz: 18,
      surah: 23,
    },
    {
      number: 77,
      image: "",
      text: "Until when We opened for them a gate of a punishment of a punishment severe behold They in it (will be in) despair (77)",
      transliteration:
        "ḥattā idhā fataḥnā ʿalayhim bāban dhā ʿadhābin shadīdin idhā hum fīhi mub'lisūna ",
      verse: 2750,
      juz: 18,
      surah: 23,
    },
    {
      number: 78,
      image: "",
      text: "And He (is) the One Who produced for you the hearing and the sight and the feeling little (is) what you give thanks (78)",
      transliteration:
        "wahuwa alladhī ansha-a lakumu l-samʿa wal-abṣāra wal-afidata qalīlan mā tashkurūna ",
      verse: 2751,
      juz: 18,
      surah: 23,
    },
    {
      number: 79,
      image: "",
      text: "And He (is) the One Who multiplied you in the earth and to Him you will be gathered (79)",
      transliteration:
        "wahuwa alladhī dhara-akum fī l-arḍi wa-ilayhi tuḥ'sharūna ",
      verse: 2752,
      juz: 18,
      surah: 23,
    },
    {
      number: 80,
      image: "",
      text: "And He (is) the One Who gives life and causes death and for Him (is the) alternation (of) the night and the day Then will not you reason (80)",
      transliteration:
        "wahuwa alladhī yuḥ'yī wayumītu walahu ikh'tilāfu al-layli wal-nahāri afalā taʿqilūna ",
      verse: 2753,
      juz: 18,
      surah: 23,
    },
    {
      number: 81,
      image: "",
      text: "Nay they say (the) like (of) what said the former (people) (81)",
      transliteration: "bal qālū mith'la mā qāla l-awalūna ",
      verse: 2754,
      juz: 18,
      surah: 23,
    },
    {
      number: 82,
      image: "",
      text: "They said What! When we are dead and become dust and bones would we surely be resurrected (82)",
      transliteration:
        "qālū a-idhā mit'nā wakunnā turāban waʿiẓāman a-innā lamabʿūthūna ",
      verse: 2755,
      juz: 18,
      surah: 23,
    },
    {
      number: 83,
      image: "",
      text: "Verily we have been promised [we] and our forefathers this before before not (is) this but (the) tales (of) the former (people) (83)",
      transliteration:
        "laqad wuʿid'nā naḥnu waābāunā hādhā min qablu in hādhā illā asāṭīru l-awalīna ",
      verse: 2756,
      juz: 18,
      surah: 23,
    },
    {
      number: 84,
      image: "",
      text: "Say To whom (belongs) the earth and whoever (is) in it if you know (84)",
      transliteration: "qul limani l-arḍu waman fīhā in kuntum taʿlamūna ",
      verse: 2757,
      juz: 18,
      surah: 23,
    },
    {
      number: 85,
      image: "",
      text: "They will say To Allah Say Then will not you remember (85)",
      transliteration: "sayaqūlūna lillahi qul afalā tadhakkarūna ",
      verse: 2758,
      juz: 18,
      surah: 23,
    },
    {
      number: 86,
      image: "",
      text: "Say Who (is the) Lord (of) the seven heavens (of) the seven heavens and (the) Lord (of) the Throne the Great (86)",
      transliteration:
        "qul man rabbu l-samāwāti l-sabʿi warabbu l-ʿarshi l-ʿaẓīmi ",
      verse: 2759,
      juz: 18,
      surah: 23,
    },
    {
      number: 87,
      image: "",
      text: "They will say Allah Say Then will not you fear (Him) (87)",
      transliteration: "sayaqūlūna lillahi qul afalā tattaqūna ",
      verse: 2760,
      juz: 18,
      surah: 23,
    },
    {
      number: 88,
      image: "",
      text: "Say Who is (it) in Whose Hand(s) (is the) dominion (of) all things and He protects and no (one) (can) be protected against Him If you know (88)",
      transliteration:
        "qul man biyadihi malakūtu kulli shayin wahuwa yujīru walā yujāru ʿalayhi in kuntum taʿlamūna ",
      verse: 2761,
      juz: 18,
      surah: 23,
    },
    {
      number: 89,
      image: "",
      text: "They will say Allah Say Then how are you deluded (89)",
      transliteration: "sayaqūlūna lillahi qul fa-annā tus'ḥarūna ",
      verse: 2762,
      juz: 18,
      surah: 23,
    },
    {
      number: 90,
      image: "",
      text: "Nay We (have) brought them the truth but indeed, they surely, (are) liars (90)",
      transliteration: "bal ataynāhum bil-ḥaqi wa-innahum lakādhibūna ",
      verse: 2763,
      juz: 18,
      surah: 23,
    },
    {
      number: 91,
      image: "",
      text: "Not Allah has taken Allah has taken any son and not is with Him any god Then surely (would have) taken away each god what he created and surely would have overpowered some of them [on] others Glory be (to) Allah above what they attribute (91)",
      transliteration:
        "mā ittakhadha l-lahu min waladin wamā kāna maʿahu min ilāhin idhan ladhahaba kullu ilāhin bimā khalaqa walaʿalā baʿḍuhum ʿalā baʿḍin sub'ḥāna l-lahi ʿammā yaṣifūna ",
      verse: 2764,
      juz: 18,
      surah: 23,
    },
    {
      number: 92,
      image: "",
      text: "Knower (of) the unseen and the witnessed exalted is He above what they associate (92)",
      transliteration:
        "ʿālimi l-ghaybi wal-shahādati fataʿālā ʿammā yush'rikūna ",
      verse: 2765,
      juz: 18,
      surah: 23,
    },
    {
      number: 93,
      image: "",
      text: "Say My Lord If You should show me what they are promised (93)",
      transliteration: "qul rabbi immā turiyannī mā yūʿadūna ",
      verse: 2766,
      juz: 18,
      surah: 23,
    },
    {
      number: 94,
      image: "",
      text: "My Lord then (do) not place me among the people  the wrongdoers (94)",
      transliteration: "rabbi falā tajʿalnī fī l-qawmi l-ẓālimīna ",
      verse: 2767,
      juz: 18,
      surah: 23,
    },
    {
      number: 95,
      image: "",
      text: "And indeed We on that We show you what We have promised them surely able (95)",
      transliteration: "wa-innā ʿalā an nuriyaka mā naʿiduhum laqādirūna ",
      verse: 2768,
      juz: 18,
      surah: 23,
    },
    {
      number: 96,
      image: "",
      text: "Repel by that which (is) best  the evil We know best of what they attribute (96)",
      transliteration:
        "id'faʿ bi-allatī hiya aḥsanu l-sayi-ata naḥnu aʿlamu bimā yaṣifūna ",
      verse: 2769,
      juz: 18,
      surah: 23,
    },
    {
      number: 97,
      image: "",
      text: "And say My Lord I seek refuge in You from (the) suggestions (of) the evil ones (97)",
      transliteration: "waqul rabbi aʿūdhu bika min hamazāti l-shayāṭīni ",
      verse: 2770,
      juz: 18,
      surah: 23,
    },
    {
      number: 98,
      image: "",
      text: "And I seek refuge in You My Lord Lest they be present with me (98)",
      transliteration: "wa-aʿūdhu bika rabbi an yaḥḍurūni ",
      verse: 2771,
      juz: 18,
      surah: 23,
    },
    {
      number: 99,
      image: "",
      text: "Until when comes (to) one of them the death he says My Lord Send me back (99)",
      transliteration: "ḥattā idhā jāa aḥadahumu l-mawtu qāla rabbi ir'jiʿūni ",
      verse: 2772,
      juz: 18,
      surah: 23,
    },
    {
      number: 100,
      image: "",
      text: "That I may do righteous (deeds) in what I left behind No Indeed, it (is) a word he speaks it and before them and before them (is) a barrier till (the) Day they are resurrected (100)",
      transliteration:
        "laʿallī aʿmalu ṣāliḥan fīmā taraktu kallā innahā kalimatun huwa qāiluhā wamin warāihim barzakhun ilā yawmi yub'ʿathūna ",
      verse: 2773,
      juz: 18,
      surah: 23,
    },
    {
      number: 101,
      image: "",
      text: "So when is blown in the trumpet then not (there) will be relationship among them that Day and not will they ask each other (101)",
      transliteration:
        "fa-idhā nufikha fī l-ṣūri falā ansāba baynahum yawma-idhin walā yatasāalūna ",
      verse: 2774,
      juz: 18,
      surah: 23,
    },
    {
      number: 102,
      image: "",
      text: "Then (the one) whose (are) heavy his scales then those  they (are) the successful (102)",
      transliteration: "faman thaqulat mawāzīnuhu fa-ulāika humu l-muf'liḥūna ",
      verse: 2775,
      juz: 18,
      surah: 23,
    },
    {
      number: 103,
      image: "",
      text: "But (the one) whose (are) light his scales then those they [who] have lost their souls in Hell they (will) abide forever (103)",
      transliteration:
        "waman khaffat mawāzīnuhu fa-ulāika alladhīna khasirū anfusahum fī jahannama khālidūna ",
      verse: 2776,
      juz: 18,
      surah: 23,
    },
    {
      number: 104,
      image: "",
      text: "Will burn their faces the Fire and they in it (will) grin with displaced lips (104)",
      transliteration: "talfaḥu wujūhahumu l-nāru wahum fīhā kāliḥūna ",
      verse: 2777,
      juz: 18,
      surah: 23,
    },
    {
      number: 105,
      image: "",
      text: "Were not Were not My Verses recited to you and you used (to) deny them deny them (105)",
      transliteration:
        "alam takun āyātī tut'lā ʿalaykum fakuntum bihā tukadhibūna ",
      verse: 2778,
      juz: 18,
      surah: 23,
    },
    {
      number: 106,
      image: "",
      text: "They (will) say Our Lord Overcame [on] us our wretchedness and we were a people astray (106)",
      transliteration:
        "qālū rabbanā ghalabat ʿalaynā shiq'watunā wakunnā qawman ḍāllīna ",
      verse: 2779,
      juz: 18,
      surah: 23,
    },
    {
      number: 107,
      image: "",
      text: "Our Lord Bring us out from it then if we return then indeed, we (would be) wrongdoers (107)",
      transliteration: "rabbanā akhrij'nā min'hā fa-in ʿud'nā fa-innā ẓālimūna ",
      verse: 2780,
      juz: 18,
      surah: 23,
    },
    {
      number: 108,
      image: "",
      text: "He (will) say Remain despised in it and (do) not speak to Me (108)",
      transliteration: "qāla ikh'saū fīhā walā tukallimūni ",
      verse: 2781,
      juz: 18,
      surah: 23,
    },
    {
      number: 109,
      image: "",
      text: "Indeed (there) was a party of My slaves (who) said Our Lord We believe so forgive us and have mercy on us and You (are) best (of) those who show mercy (109)",
      transliteration:
        "innahu kāna farīqun min ʿibādī yaqūlūna rabbanā āmannā fa-igh'fir lanā wa-ir'ḥamnā wa-anta khayru l-rāḥimīna ",
      verse: 2782,
      juz: 18,
      surah: 23,
    },
    {
      number: 110,
      image: "",
      text: "But you took them (in) mockery until they made you forget My remembrance and you used (to) at them laugh (110)",
      transliteration:
        "fa-ittakhadhtumūhum sikh'riyyan ḥattā ansawkum dhik'rī wakuntum min'hum taḍḥakūna ",
      verse: 2783,
      juz: 18,
      surah: 23,
    },
    {
      number: 111,
      image: "",
      text: "Indeed, I have rewarded them this Day because they were patient indeed, they [they] (are) the successful ones (111)",
      transliteration:
        "innī jazaytuhumu l-yawma bimā ṣabarū annahum humu l-fāizūna ",
      verse: 2784,
      juz: 18,
      surah: 23,
    },
    {
      number: 112,
      image: "",
      text: "He will say How long did you remain in the earth (in) number (of) years (112)",
      transliteration: "qāla kam labith'tum fī l-arḍi ʿadada sinīna ",
      verse: 2785,
      juz: 18,
      surah: 23,
    },
    {
      number: 113,
      image: "",
      text: "They will say We remained a day or a part (of) a day but ask those who keep count (113)",
      transliteration: "qālū labith'nā yawman aw baʿḍa yawmin fasali l-ʿādīna ",
      verse: 2786,
      juz: 18,
      surah: 23,
    },
    {
      number: 114,
      image: "",
      text: "He will say Not you stayed but a little if only you [you] knew (114)",
      transliteration:
        "qāla in labith'tum illā qalīlan law annakum kuntum taʿlamūna ",
      verse: 2787,
      juz: 18,
      surah: 23,
    },
    {
      number: 115,
      image: "",
      text: "Then did you think that We created you uselessly and that you to Us not will be returned (115)",
      transliteration:
        "afaḥasib'tum annamā khalaqnākum ʿabathan wa-annakum ilaynā lā tur'jaʿūna ",
      verse: 2788,
      juz: 18,
      surah: 23,
    },
    {
      number: 116,
      image: "",
      text: "So exalted is Allah the King the Truth (There is) no god except Him (the) Lord (of) the Throne Honorable (116)",
      transliteration:
        "fataʿālā l-lahu l-maliku l-ḥaqu lā ilāha illā huwa rabbu l-ʿarshi l-karīmi ",
      verse: 2789,
      juz: 18,
      surah: 23,
    },
    {
      number: 117,
      image: "",
      text: "And whoever invokes with Allah god other no proof for him in it Then only his account (is) with his Lord Indeed, [he] not will succeed the disbelievers (117)",
      transliteration:
        "waman yadʿu maʿa l-lahi ilāhan ākhara lā bur'hāna lahu bihi fa-innamā ḥisābuhu ʿinda rabbihi innahu lā yuf'liḥu l-kāfirūna ",
      verse: 2790,
      juz: 18,
      surah: 23,
    },
    {
      number: 118,
      image: "",
      text: "And say My Lord Forgive and have mercy and You (are the) Best (of) those who show mercy (118)",
      transliteration: "waqul rabbi igh'fir wa-ir'ḥam wa-anta khayru l-rāḥimīna ",
      verse: 2791,
      juz: 18,
      surah: 23,
    },
  ],
};
