import { Surah } from "../types/islam.js";

export const mursalat: Surah = {
  name: "Al-Mursalat",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "By the ones sent forth one after another (1)",
      transliteration: "wal-mur'salāti ʿur'fan ",
      verse: 5623,
      juz: 29,
      surah: 77,
    },
    {
      number: 2,
      image: "",
      text: "And the winds that blow violently (2)",
      transliteration: "fal-ʿāṣifāti ʿaṣfan ",
      verse: 5624,
      juz: 29,
      surah: 77,
    },
    {
      number: 3,
      image: "",
      text: "And the ones that scatter far and wide (3)",
      transliteration: "wal-nāshirāti nashran ",
      verse: 5625,
      juz: 29,
      surah: 77,
    },
    {
      number: 4,
      image: "",
      text: "And those who separate (by the) Criterion (4)",
      transliteration: "fal-fāriqāti farqan ",
      verse: 5626,
      juz: 29,
      surah: 77,
    },
    {
      number: 5,
      image: "",
      text: "And those who bring down (the) Reminder (5)",
      transliteration: "fal-mul'qiyāti dhik'ran ",
      verse: 5627,
      juz: 29,
      surah: 77,
    },
    {
      number: 6,
      image: "",
      text: "(As) justification or warning (6)",
      transliteration: "ʿudh'ran aw nudh'ran ",
      verse: 5628,
      juz: 29,
      surah: 77,
    },
    {
      number: 7,
      image: "",
      text: "Indeed, what you are promised will surely occur (7)",
      transliteration: "innamā tūʿadūna lawāqiʿun ",
      verse: 5629,
      juz: 29,
      surah: 77,
    },
    {
      number: 8,
      image: "",
      text: "So when the stars are obliterated (8)",
      transliteration: "fa-idhā l-nujūmu ṭumisat ",
      verse: 5630,
      juz: 29,
      surah: 77,
    },
    {
      number: 9,
      image: "",
      text: "And when the heaven is cleft asunder (9)",
      transliteration: "wa-idhā l-samāu furijat ",
      verse: 5631,
      juz: 29,
      surah: 77,
    },
    {
      number: 10,
      image: "",
      text: "And when the mountains are blown away (10)",
      transliteration: "wa-idhā l-jibālu nusifat ",
      verse: 5632,
      juz: 29,
      surah: 77,
    },
    {
      number: 11,
      image: "",
      text: "And when the Messengers are gathered to their appointed time (11)",
      transliteration: "wa-idhā l-rusulu uqqitat ",
      verse: 5633,
      juz: 29,
      surah: 77,
    },
    {
      number: 12,
      image: "",
      text: "For what Day are (these) postponed (12)",
      transliteration: "li-ayyi yawmin ujjilat ",
      verse: 5634,
      juz: 29,
      surah: 77,
    },
    {
      number: 13,
      image: "",
      text: "For (the) Day (of) Judgment (13)",
      transliteration: "liyawmi l-faṣli ",
      verse: 5635,
      juz: 29,
      surah: 77,
    },
    {
      number: 14,
      image: "",
      text: "And what will make you know what (is the) Day (of) the Judgment (14)",
      transliteration: "wamā adrāka mā yawmu l-faṣli ",
      verse: 5636,
      juz: 29,
      surah: 77,
    },
    {
      number: 15,
      image: "",
      text: "Woe that Day to the deniers (15)",
      transliteration: "waylun yawma-idhin lil'mukadhibīna ",
      verse: 5637,
      juz: 29,
      surah: 77,
    },
    {
      number: 16,
      image: "",
      text: "Did not We destroy the former (people) (16)",
      transliteration: "alam nuh'liki l-awalīna ",
      verse: 5638,
      juz: 29,
      surah: 77,
    },
    {
      number: 17,
      image: "",
      text: "Then We follow them up (with) the later ones (17)",
      transliteration: "thumma nut'biʿuhumu l-ākhirīna ",
      verse: 5639,
      juz: 29,
      surah: 77,
    },
    {
      number: 18,
      image: "",
      text: "Thus We deal with the criminals (18)",
      transliteration: "kadhālika nafʿalu bil-muj'rimīna ",
      verse: 5640,
      juz: 29,
      surah: 77,
    },
    {
      number: 19,
      image: "",
      text: "Woe that Day to the deniers (19)",
      transliteration: "waylun yawma-idhin lil'mukadhibīna ",
      verse: 5641,
      juz: 29,
      surah: 77,
    },
    {
      number: 20,
      image: "",
      text: "Did not We create you from a water despicable (20)",
      transliteration: "alam nakhluqkkum min māin mahīnin ",
      verse: 5642,
      juz: 29,
      surah: 77,
    },
    {
      number: 21,
      image: "",
      text: "Then We placed it in an abode safe (21)",
      transliteration: "fajaʿalnāhu fī qarārin makīnin ",
      verse: 5643,
      juz: 29,
      surah: 77,
    },
    {
      number: 22,
      image: "",
      text: "For a period known (22)",
      transliteration: "ilā qadarin maʿlūmin ",
      verse: 5644,
      juz: 29,
      surah: 77,
    },
    {
      number: 23,
      image: "",
      text: "So We measured and Best (are We to) measure (23)",
      transliteration: "faqadarnā faniʿ'ma l-qādirūna ",
      verse: 5645,
      juz: 29,
      surah: 77,
    },
    {
      number: 24,
      image: "",
      text: "Woe that Day to the deniers (24)",
      transliteration: "waylun yawma-idhin lil'mukadhibīna ",
      verse: 5646,
      juz: 29,
      surah: 77,
    },
    {
      number: 25,
      image: "",
      text: "Have not We made the earth a receptacle (25)",
      transliteration: "alam najʿali l-arḍa kifātan ",
      verse: 5647,
      juz: 29,
      surah: 77,
    },
    {
      number: 26,
      image: "",
      text: "(For the) living and (the) dead (26)",
      transliteration: "aḥyāan wa-amwātan ",
      verse: 5648,
      juz: 29,
      surah: 77,
    },
    {
      number: 27,
      image: "",
      text: "And We made therein firmly set mountains lofty and We gave you to drink water  sweet (27)",
      transliteration:
        "wajaʿalnā fīhā rawāsiya shāmikhātin wa-asqaynākum māan furātan ",
      verse: 5649,
      juz: 29,
      surah: 77,
    },
    {
      number: 28,
      image: "",
      text: "Woe that Day to the deniers (28)",
      transliteration: "waylun yawma-idhin lil'mukadhibīna ",
      verse: 5650,
      juz: 29,
      surah: 77,
    },
    {
      number: 29,
      image: "",
      text: "Proceed to what you used to in it deny (29)",
      transliteration: "inṭaliqū ilā mā kuntum bihi tukadhibūna ",
      verse: 5651,
      juz: 29,
      surah: 77,
    },
    {
      number: 30,
      image: "",
      text: "Proceed to a shadow having three columns (30)",
      transliteration: "inṭaliqū ilā ẓillin dhī thalāthi shuʿabin ",
      verse: 5652,
      juz: 29,
      surah: 77,
    },
    {
      number: 31,
      image: "",
      text: "No cool shade and not availing against the flame (31)",
      transliteration: "lā ẓalīlin walā yugh'nī mina l-lahabi ",
      verse: 5653,
      juz: 29,
      surah: 77,
    },
    {
      number: 32,
      image: "",
      text: "Indeed, it throws up sparks as the fortress (32)",
      transliteration: "innahā tarmī bishararin kal-qaṣri ",
      verse: 5654,
      juz: 29,
      surah: 77,
    },
    {
      number: 33,
      image: "",
      text: "As if they (were) camels yellow (33)",
      transliteration: "ka-annahu jimālatun ṣuf'run ",
      verse: 5655,
      juz: 29,
      surah: 77,
    },
    {
      number: 34,
      image: "",
      text: "Woe that Day to the deniers (34)",
      transliteration: "waylun yawma-idhin lil'mukadhibīna ",
      verse: 5656,
      juz: 29,
      surah: 77,
    },
    {
      number: 35,
      image: "",
      text: "This (is) a Day not they will speak (35)",
      transliteration: "hādhā yawmu lā yanṭiqūna ",
      verse: 5657,
      juz: 29,
      surah: 77,
    },
    {
      number: 36,
      image: "",
      text: "And not will it be permitted for them to make excuses (36)",
      transliteration: "walā yu'dhanu lahum fayaʿtadhirūna ",
      verse: 5658,
      juz: 29,
      surah: 77,
    },
    {
      number: 37,
      image: "",
      text: "Woe that Day to the deniers (37)",
      transliteration: "waylun yawma-idhin lil'mukadhibīna ",
      verse: 5659,
      juz: 29,
      surah: 77,
    },
    {
      number: 38,
      image: "",
      text: "This (is the) Day (of) Judgment We have gathered you and the former (people) (38)",
      transliteration: "hādhā yawmu l-faṣli jamaʿnākum wal-awalīna ",
      verse: 5660,
      juz: 29,
      surah: 77,
    },
    {
      number: 39,
      image: "",
      text: "So if is for you a plan then plan against Me (39)",
      transliteration: "fa-in kāna lakum kaydun fakīdūni ",
      verse: 5661,
      juz: 29,
      surah: 77,
    },
    {
      number: 40,
      image: "",
      text: "Woe that Day to the deniers (40)",
      transliteration: "waylun yawma-idhin lil'mukadhibīna ",
      verse: 5662,
      juz: 29,
      surah: 77,
    },
    {
      number: 41,
      image: "",
      text: "Indeed the righteous (will be) in shades and springs (41)",
      transliteration: "inna l-mutaqīna fī ẓilālin waʿuyūnin ",
      verse: 5663,
      juz: 29,
      surah: 77,
    },
    {
      number: 42,
      image: "",
      text: "And fruits from what they desire (42)",
      transliteration: "wafawākiha mimmā yashtahūna ",
      verse: 5664,
      juz: 29,
      surah: 77,
    },
    {
      number: 43,
      image: "",
      text: "Eat and drink (in) satisfaction for what you used to do (43)",
      transliteration: "kulū wa-ish'rabū hanīan bimā kuntum taʿmalūna ",
      verse: 5665,
      juz: 29,
      surah: 77,
    },
    {
      number: 44,
      image: "",
      text: "Indeed, We thus reward the good-doers (44)",
      transliteration: "innā kadhālika najzī l-muḥ'sinīna ",
      verse: 5666,
      juz: 29,
      surah: 77,
    },
    {
      number: 45,
      image: "",
      text: "Woe that Day to the deniers (45)",
      transliteration: "waylun yawma-idhin lil'mukadhibīna ",
      verse: 5667,
      juz: 29,
      surah: 77,
    },
    {
      number: 46,
      image: "",
      text: "Eat and enjoy yourselves a little indeed, you (are) criminals (46)",
      transliteration: "kulū watamattaʿū qalīlan innakum muj'rimūna ",
      verse: 5668,
      juz: 29,
      surah: 77,
    },
    {
      number: 47,
      image: "",
      text: "Woe that Day to the deniers (47)",
      transliteration: "waylun yawma-idhin lil'mukadhibīna ",
      verse: 5669,
      juz: 29,
      surah: 77,
    },
    {
      number: 48,
      image: "",
      text: "And when it is said to them Bow not they bow (48)",
      transliteration: "wa-idhā qīla lahumu ir'kaʿū lā yarkaʿūna ",
      verse: 5670,
      juz: 29,
      surah: 77,
    },
    {
      number: 49,
      image: "",
      text: "Woe that Day to the deniers (49)",
      transliteration: "waylun yawma-idhin lil'mukadhibīna ",
      verse: 5671,
      juz: 29,
      surah: 77,
    },
    {
      number: 50,
      image: "",
      text: "Then in what statement after it will they believe (50)",
      transliteration: "fabi-ayyi ḥadīthin baʿdahu yu'minūna ",
      verse: 5672,
      juz: 29,
      surah: 77,
    },
  ],
};
