import { Surah } from "../types/islam.ts";

export const mursalat: Surah = {
  name: "Al-Mursalat",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "By those [winds] sent forth in gusts",
      verse: 5492,
    },
    {
      number: 2,
      image: "",
      text: "And the winds that blow violently",
      verse: 5493,
    },
    {
      number: 3,
      image: "",
      text: "And [by] the winds that spread [clouds]",
      verse: 5494,
    },
    {
      number: 4,
      image: "",
      text: "And those [angels] who bring criterion",
      verse: 5495,
    },
    {
      number: 5,
      image: "",
      text: "And those [angels] who deliver a message",
      verse: 5496,
    },
    { number: 6, image: "", text: "As justification or warning,", verse: 5497 },
    {
      number: 7,
      image: "",
      text: "Indeed, what you are promised is to occur.",
      verse: 5498,
    },
    {
      number: 8,
      image: "",
      text: "So when the stars are obliterated",
      verse: 5499,
    },
    {
      number: 9,
      image: "",
      text: "And when the heaven is opened",
      verse: 5500,
    },
    {
      number: 10,
      image: "",
      text: "And when the mountains are blown away",
      verse: 5501,
    },
    {
      number: 11,
      image: "",
      text: "And when the messengers' time has come...",
      verse: 5502,
    },
    {
      number: 12,
      image: "",
      text: "For what Day was it postponed?",
      verse: 5503,
    },
    { number: 13, image: "", text: "For the Day of Judgement.", verse: 5504 },
    {
      number: 14,
      image: "",
      text: "And what can make you know what is the Day of Judgement?",
      verse: 5505,
    },
    {
      number: 15,
      image: "",
      text: "Woe, that Day, to the deniers.",
      verse: 5506,
    },
    {
      number: 16,
      image: "",
      text: "Did We not destroy the former peoples?",
      verse: 5507,
    },
    {
      number: 17,
      image: "",
      text: "Then We will follow them with the later ones.",
      verse: 5508,
    },
    {
      number: 18,
      image: "",
      text: "Thus do We deal with the criminals.",
      verse: 5509,
    },
    {
      number: 19,
      image: "",
      text: "Woe, that Day, to the deniers.",
      verse: 5510,
    },
    {
      number: 20,
      image: "",
      text: "Did We not create you from a liquid disdained?",
      verse: 5511,
    },
    {
      number: 21,
      image: "",
      text: "And We placed it in a firm lodging",
      verse: 5512,
    },
    { number: 22, image: "", text: "For a known extent.", verse: 5513 },
    {
      number: 23,
      image: "",
      text: "And We determined [it], and excellent [are We] to determine.",
      verse: 5514,
    },
    {
      number: 24,
      image: "",
      text: "Woe, that Day, to the deniers.",
      verse: 5515,
    },
    {
      number: 25,
      image: "",
      text: "Have We not made the earth a container",
      verse: 5516,
    },
    { number: 26, image: "", text: "Of the living and the dead?", verse: 5517 },
    {
      number: 27,
      image: "",
      text:
        "And We placed therein lofty, firmly set mountains and have given you to drink sweet water.",
      verse: 5518,
    },
    {
      number: 28,
      image: "",
      text: "Woe, that Day, to the deniers.",
      verse: 5519,
    },
    {
      number: 29,
      image: "",
      text: '[They will be told], "Proceed to that which you used to deny.',
      verse: 5520,
    },
    {
      number: 30,
      image: "",
      text: "Proceed to a shadow [of smoke] having three columns",
      verse: 5521,
    },
    {
      number: 31,
      image: "",
      text: '[But having] no cool shade and availing not against the flame."',
      verse: 5522,
    },
    {
      number: 32,
      image: "",
      text: "Indeed, it throws sparks [as huge] as a fortress,",
      verse: 5523,
    },
    {
      number: 33,
      image: "",
      text: "As if they were yellowish [black] camels.",
      verse: 5524,
    },
    {
      number: 34,
      image: "",
      text: "Woe, that Day, to the deniers.",
      verse: 5525,
    },
    {
      number: 35,
      image: "",
      text: "This is a Day they will not speak,",
      verse: 5526,
    },
    {
      number: 36,
      image: "",
      text: "Nor will it be permitted for them to make an excuse.",
      verse: 5527,
    },
    {
      number: 37,
      image: "",
      text: "Woe, that Day, to the deniers.",
      verse: 5528,
    },
    {
      number: 38,
      image: "",
      text:
        "This is the Day of Judgement; We will have assembled you and the former peoples.",
      verse: 5529,
    },
    {
      number: 39,
      image: "",
      text: "So if you have a plan, then plan against Me.",
      verse: 5530,
    },
    {
      number: 40,
      image: "",
      text: "Woe, that Day, to the deniers.",
      verse: 5531,
    },
    {
      number: 41,
      image: "",
      text: "Indeed, the righteous will be among shades and springs",
      verse: 5532,
    },
    {
      number: 42,
      image: "",
      text: "And fruits from whatever they desire,",
      verse: 5533,
    },
    {
      number: 43,
      image: "",
      text:
        '[Being told], "Eat and drink in satisfaction for what you used to do."',
      verse: 5534,
    },
    {
      number: 44,
      image: "",
      text: "Indeed, We thus reward the doers of good.",
      verse: 5535,
    },
    {
      number: 45,
      image: "",
      text: "Woe, that Day, to the deniers.",
      verse: 5536,
    },
    {
      number: 46,
      image: "",
      text:
        "[O disbelievers], eat and enjoy yourselves a little; indeed, you are criminals.",
      verse: 5537,
    },
    {
      number: 47,
      image: "",
      text: "Woe, that Day, to the deniers.",
      verse: 5538,
    },
    {
      number: 48,
      image: "",
      text: 'And when it is said to them, "Bow [in prayer]," they do not bow.',
      verse: 5539,
    },
    {
      number: 49,
      image: "",
      text: "Woe, that Day, to the deniers.",
      verse: 5540,
    },
    {
      number: 50,
      image: "",
      text: "Then in what statement after the Qur'an will they believe?",
      verse: 5541,
    },
  ],
};
