import { Surah } from "../types/islam.js";

export const mutaffifin: Surah = {
  name: "Al-Mutaffifin",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "Woe to those who give less (1)",
      transliteration: "waylun lil'muṭaffifīna ",
      verse: 5849,
      juz: 30,
      surah: 83,
    },
    {
      number: 2,
      image: "",
      text: "Those who when they take a measure from the people they take in full (2)",
      transliteration: "alladhīna idhā ik'tālū ʿalā l-nāsi yastawfūna ",
      verse: 5850,
      juz: 30,
      surah: 83,
    },
    {
      number: 3,
      image: "",
      text: "But when they give by measure (to) them or they weigh (for) them they give less (3)",
      transliteration: "wa-idhā kālūhum aw wazanūhum yukh'sirūna ",
      verse: 5851,
      juz: 30,
      surah: 83,
    },
    {
      number: 4,
      image: "",
      text: "Do not think those that they (will be) resurrected (4)",
      transliteration: "alā yaẓunnu ulāika annahum mabʿūthūna ",
      verse: 5852,
      juz: 30,
      surah: 83,
    },
    {
      number: 5,
      image: "",
      text: "For a Day Great (5)",
      transliteration: "liyawmin ʿaẓīmin ",
      verse: 5853,
      juz: 30,
      surah: 83,
    },
    {
      number: 6,
      image: "",
      text: "(The) Day will stand mankind before (the) Lord (of) the worlds (6)",
      transliteration: "yawma yaqūmu l-nāsu lirabbi l-ʿālamīna ",
      verse: 5854,
      juz: 30,
      surah: 83,
    },
    {
      number: 7,
      image: "",
      text: "Nay Indeed (the) record (of) the wicked (is) surely in Sijjin (7)",
      transliteration: "kallā inna kitāba l-fujāri lafī sijjīnin ",
      verse: 5855,
      juz: 30,
      surah: 83,
    },
    {
      number: 8,
      image: "",
      text: "And what can make you know what (is) Sijjin (8)",
      transliteration: "wamā adrāka mā sijjīnun ",
      verse: 5856,
      juz: 30,
      surah: 83,
    },
    {
      number: 9,
      image: "",
      text: "A book written (9)",
      transliteration: "kitābun marqūmun ",
      verse: 5857,
      juz: 30,
      surah: 83,
    },
    {
      number: 10,
      image: "",
      text: "Woe that Day to the deniers (10)",
      transliteration: "waylun yawma-idhin lil'mukadhibīna ",
      verse: 5858,
      juz: 30,
      surah: 83,
    },
    {
      number: 11,
      image: "",
      text: "Those who deny (the) Day (of) the Judgment (11)",
      transliteration: "alladhīna yukadhibūna biyawmi l-dīni ",
      verse: 5859,
      juz: 30,
      surah: 83,
    },
    {
      number: 12,
      image: "",
      text: "And not can deny [of] it except every transgressor sinful (12)",
      transliteration: "wamā yukadhibu bihi illā kullu muʿ'tadin athīmin ",
      verse: 5860,
      juz: 30,
      surah: 83,
    },
    {
      number: 13,
      image: "",
      text: "When are recited to him Our Verses he says Stories (of) the former (people) (13)",
      transliteration: "idhā tut'lā ʿalayhi āyātunā qāla asāṭīru l-awalīna ",
      verse: 5861,
      juz: 30,
      surah: 83,
    },
    {
      number: 14,
      image: "",
      text: "Nay But (the) stain has covered [over] their hearts (for) what they used to earn (14)",
      transliteration: "kallā bal rāna ʿalā qulūbihim mā kānū yaksibūna ",
      verse: 5862,
      juz: 30,
      surah: 83,
    },
    {
      number: 15,
      image: "",
      text: "Nay Indeed, they from their Lord that Day surely will be partitioned (15)",
      transliteration: "kallā innahum ʿan rabbihim yawma-idhin lamaḥjūbūna ",
      verse: 5863,
      juz: 30,
      surah: 83,
    },
    {
      number: 16,
      image: "",
      text: "Then indeed, they (surely) will burn (in) the Hellfire (16)",
      transliteration: "thumma innahum laṣālū l-jaḥīmi ",
      verse: 5864,
      juz: 30,
      surah: 83,
    },
    {
      number: 17,
      image: "",
      text: "Then it will be said This (is) what you used to [of it] deny (17)",
      transliteration: "thumma yuqālu hādhā alladhī kuntum bihi tukadhibūna ",
      verse: 5865,
      juz: 30,
      surah: 83,
    },
    {
      number: 18,
      image: "",
      text: "Nay Indeed (the) record (of) the righteous (will be) surely in Illiyin (18)",
      transliteration: "kallā inna kitāba l-abrāri lafī ʿilliyyīna ",
      verse: 5866,
      juz: 30,
      surah: 83,
    },
    {
      number: 19,
      image: "",
      text: "And what can make you know what (is) Illiyun (19)",
      transliteration: "wamā adrāka mā ʿilliyyūna ",
      verse: 5867,
      juz: 30,
      surah: 83,
    },
    {
      number: 20,
      image: "",
      text: "A book written (20)",
      transliteration: "kitābun marqūmun ",
      verse: 5868,
      juz: 30,
      surah: 83,
    },
    {
      number: 21,
      image: "",
      text: "Witness it those brought near (21)",
      transliteration: "yashhaduhu l-muqarabūna ",
      verse: 5869,
      juz: 30,
      surah: 83,
    },
    {
      number: 22,
      image: "",
      text: "Indeed the righteous (will be) surely in bliss (22)",
      transliteration: "inna l-abrāra lafī naʿīmin ",
      verse: 5870,
      juz: 30,
      surah: 83,
    },
    {
      number: 23,
      image: "",
      text: "On thrones observing (23)",
      transliteration: "ʿalā l-arāiki yanẓurūna ",
      verse: 5871,
      juz: 30,
      surah: 83,
    },
    {
      number: 24,
      image: "",
      text: "You will recognize in their faces (the) radiance (of) bliss (24)",
      transliteration: "taʿrifu fī wujūhihim naḍrata l-naʿīmi ",
      verse: 5872,
      juz: 30,
      surah: 83,
    },
    {
      number: 25,
      image: "",
      text: "They will be given to drink of a pure wine sealed (25)",
      transliteration: "yus'qawna min raḥīqin makhtūmin ",
      verse: 5873,
      juz: 30,
      surah: 83,
    },
    {
      number: 26,
      image: "",
      text: "Its seal (will be of) musk And for that let aspire the aspirers (26)",
      transliteration:
        "khitāmuhu mis'kun wafī dhālika falyatanāfasi l-mutanāfisūna ",
      verse: 5874,
      juz: 30,
      surah: 83,
    },
    {
      number: 27,
      image: "",
      text: "And its mixture (is) of Tasneem (27)",
      transliteration: "wamizājuhu min tasnīmin ",
      verse: 5875,
      juz: 30,
      surah: 83,
    },
    {
      number: 28,
      image: "",
      text: "A spring will drink from it those brought near (28)",
      transliteration: "ʿaynan yashrabu bihā l-muqarabūna ",
      verse: 5876,
      juz: 30,
      surah: 83,
    },
    {
      number: 29,
      image: "",
      text: "Indeed those who committed crimes used to at those who believed laugh (29)",
      transliteration:
        "inna alladhīna ajramū kānū mina alladhīna āmanū yaḍḥakūna ",
      verse: 5877,
      juz: 30,
      surah: 83,
    },
    {
      number: 30,
      image: "",
      text: "And when they passed by them they winked at one another (30)",
      transliteration: "wa-idhā marrū bihim yataghāmazūna ",
      verse: 5878,
      juz: 30,
      surah: 83,
    },
    {
      number: 31,
      image: "",
      text: "And when they returned to their people they would return jesting (31)",
      transliteration: "wa-idhā inqalabū ilā ahlihimu inqalabū fakihīna ",
      verse: 5879,
      juz: 30,
      surah: 83,
    },
    {
      number: 32,
      image: "",
      text: "And when they saw them they said Indeed these surely have gone astray (32)",
      transliteration: "wa-idhā ra-awhum qālū inna hāulāi laḍāllūna ",
      verse: 5880,
      juz: 30,
      surah: 83,
    },
    {
      number: 33,
      image: "",
      text: "But not they had been sent over them (as) guardians (33)",
      transliteration: "wamā ur'silū ʿalayhim ḥāfiẓīna ",
      verse: 5881,
      juz: 30,
      surah: 83,
    },
    {
      number: 34,
      image: "",
      text: "So today those who believed  at the disbelievers they will laugh (34)",
      transliteration: "fal-yawma alladhīna āmanū mina l-kufāri yaḍḥakūna ",
      verse: 5882,
      juz: 30,
      surah: 83,
    },
    {
      number: 35,
      image: "",
      text: "On the thrones observing (35)",
      transliteration: "ʿalā l-arāiki yanẓurūna ",
      verse: 5883,
      juz: 30,
      surah: 83,
    },
    {
      number: 36,
      image: "",
      text: "Have (not) been rewarded the disbelievers (for) what they used to do (36)",
      transliteration: "hal thuwwiba l-kufāru mā kānū yafʿalūna ",
      verse: 5884,
      juz: 30,
      surah: 83,
    },
  ],
};
