import { Surah } from "../types/islam.js";

export const muzzammil: Surah = {
  name: "Al-Muzzammil",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "O you who wraps himself (1)",
      transliteration: "yāayyuhā l-muzamilu ",
      verse: 5476,
      juz: 29,
      surah: 73,
    },
    {
      number: 2,
      image: "",
      text: "Stand (in) the night except a little (2)",
      transliteration: "qumi al-layla illā qalīlan ",
      verse: 5477,
      juz: 29,
      surah: 73,
    },
    {
      number: 3,
      image: "",
      text: "Half of it or lessen from it a little (3)",
      transliteration: "niṣ'fahu awi unquṣ min'hu qalīlan ",
      verse: 5478,
      juz: 29,
      surah: 73,
    },
    {
      number: 4,
      image: "",
      text: "Or add to it and recite the Quran (with) measured rhythmic recitation (4)",
      transliteration: "aw zid ʿalayhi warattili l-qur'āna tartīlan ",
      verse: 5479,
      juz: 29,
      surah: 73,
    },
    {
      number: 5,
      image: "",
      text: "Indeed, We will cast upon you a Word heavy (5)",
      transliteration: "innā sanul'qī ʿalayka qawlan thaqīlan ",
      verse: 5480,
      juz: 29,
      surah: 73,
    },
    {
      number: 6,
      image: "",
      text: "Indeed (the) rising (at) the night it (is) very hard and most potent and more suitable (for) Word (6)",
      transliteration:
        "inna nāshi-ata al-layli hiya ashaddu waṭan wa-aqwamu qīlan ",
      verse: 5481,
      juz: 29,
      surah: 73,
    },
    {
      number: 7,
      image: "",
      text: "Indeed for you in the day (is) occupation prolonged (7)",
      transliteration: "inna laka fī l-nahāri sabḥan ṭawīlan ",
      verse: 5482,
      juz: 29,
      surah: 73,
    },
    {
      number: 8,
      image: "",
      text: "And remember (the) name (of) your Lord and devote yourself to Him (with) devotion (8)",
      transliteration: "wa-udh'kuri is'ma rabbika watabattal ilayhi tabtīlan ",
      verse: 5483,
      juz: 29,
      surah: 73,
    },
    {
      number: 9,
      image: "",
      text: "(The) Lord (of) the east and the west (there is) no god except Him so take Him (as) Disposer of Affairs (9)",
      transliteration:
        "rabbu l-mashriqi wal-maghribi lā ilāha illā huwa fa-ittakhidh'hu wakīlan ",
      verse: 5484,
      juz: 29,
      surah: 73,
    },
    {
      number: 10,
      image: "",
      text: "And be patient over what they say and avoid them an avoidance gracious (10)",
      transliteration:
        "wa-iṣ'bir ʿalā mā yaqūlūna wa-uh'jur'hum hajran jamīlan ",
      verse: 5485,
      juz: 29,
      surah: 73,
    },
    {
      number: 11,
      image: "",
      text: "And leave Me and the deniers possessors (of) the ease and allow them respite  a little (11)",
      transliteration:
        "wadharnī wal-mukadhibīna ulī l-naʿmati wamahhil'hum qalīlan ",
      verse: 5486,
      juz: 29,
      surah: 73,
    },
    {
      number: 12,
      image: "",
      text: "Indeed with Us (are) shackles and burning fire (12)",
      transliteration: "inna ladaynā ankālan wajaḥīman ",
      verse: 5487,
      juz: 29,
      surah: 73,
    },
    {
      number: 13,
      image: "",
      text: "And food that chokes and a punishment painful (13)",
      transliteration: "waṭaʿāman dhā ghuṣṣatin waʿadhāban alīman ",
      verse: 5488,
      juz: 29,
      surah: 73,
    },
    {
      number: 14,
      image: "",
      text: "(On the) Day will quake the earth and the mountains and will become the mountains a heap of sand pouring down (14)",
      transliteration:
        "yawma tarjufu l-arḍu wal-jibālu wakānati l-jibālu kathīban mahīlan ",
      verse: 5489,
      juz: 29,
      surah: 73,
    },
    {
      number: 15,
      image: "",
      text: "Indeed, We [We] have sent to you a Messenger (as) a witness upon you as We sent to Firaun a Messenger (15)",
      transliteration:
        "innā arsalnā ilaykum rasūlan shāhidan ʿalaykum kamā arsalnā ilā fir'ʿawna rasūlan ",
      verse: 5490,
      juz: 29,
      surah: 73,
    },
    {
      number: 16,
      image: "",
      text: "But disobeyed Firaun the Messenger so We seized him (with) a seizure ruinous (16)",
      transliteration:
        "faʿaṣā fir'ʿawnu l-rasūla fa-akhadhnāhu akhdhan wabīlan ",
      verse: 5491,
      juz: 29,
      surah: 73,
    },
    {
      number: 17,
      image: "",
      text: "Then how will you guard yourselves if you disbelieve a Day (that) will make the children gray-haired (17)",
      transliteration:
        "fakayfa tattaqūna in kafartum yawman yajʿalu l-wil'dāna shīban ",
      verse: 5492,
      juz: 29,
      surah: 73,
    },
    {
      number: 18,
      image: "",
      text: "The heaven (will) break apart therefrom is His Promise to be fulfilled (18)",
      transliteration: "al-samāu munfaṭirun bihi kāna waʿduhu mafʿūlan ",
      verse: 5493,
      juz: 29,
      surah: 73,
    },
    {
      number: 19,
      image: "",
      text: "Indeed this (is) a Reminder then whoever wills (let him) take to his Lord a way (19)",
      transliteration:
        "inna hādhihi tadhkiratun faman shāa ittakhadha ilā rabbihi sabīlan ",
      verse: 5494,
      juz: 29,
      surah: 73,
    },
    {
      number: 20,
      image: "",
      text: "Indeed your Lord knows that you stand (a little) less than two-thirds (of) the night and half of it and a third of it and (so do) a group of those who (are) with you And Allah determines the night and the day He knows that not you count it so He has turned to you so recite what is easy of the Quran He knows that there will be among you sick and others traveling in the land seeking of (the) Bounty (of) Allah and others fighting in (the) way (of) Allah So recite what is easy of it and establish the prayer and give the zakah and loan Allah a loan goodly And whatever you send forth for yourselves of good you will find it with Allah It (will be) better and greater (in) reward And seek forgiveness (of) Allah Indeed Allah (is) Oft-Forgiving Most Merciful (20)",
      transliteration:
        "inna rabbaka yaʿlamu annaka taqūmu adnā min thuluthayi al-layli waniṣ'fahu wathuluthahu waṭāifatun mina alladhīna maʿaka wal-lahu yuqaddiru al-layla wal-nahāra ʿalima an lan tuḥ'ṣūhu fatāba ʿalaykum fa-iq'raū mā tayassara mina l-qur'āni ʿalima an sayakūnu minkum marḍā waākharūna yaḍribūna fī l-arḍi yabtaghūna min faḍli l-lahi waākharūna yuqātilūna fī sabīli l-lahi fa-iq'raū mā tayassara min'hu wa-aqīmū l-ṣalata waātū l-zakata wa-aqriḍū l-laha qarḍan ḥasanan wamā tuqaddimū li-anfusikum min khayrin tajidūhu ʿinda l-lahi huwa khayran wa-aʿẓama ajran wa-is'taghfirū l-laha inna l-laha ghafūrun raḥīmun ",
      verse: 5495,
      juz: 29,
      surah: 73,
    },
  ],
};
