import { Surah } from "../types/islam.js";

export const naba: Surah = {
  name: "An-Naba",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "About what are they asking one another (1)",
      transliteration: "ʿamma yatasāalūna ",
      verse: 5673,
      juz: 30,
      surah: 78,
    },
    {
      number: 2,
      image: "",
      text: "About the News the Great (2)",
      transliteration: "ʿani l-naba-i l-ʿaẓīmi ",
      verse: 5674,
      juz: 30,
      surah: 78,
    },
    {
      number: 3,
      image: "",
      text: "(About) which they (are) concerning it (in) disagreement (3)",
      transliteration: "alladhī hum fīhi mukh'talifūna ",
      verse: 5675,
      juz: 30,
      surah: 78,
    },
    {
      number: 4,
      image: "",
      text: "Nay (soon) they will know (4)",
      transliteration: "kallā sayaʿlamūna ",
      verse: 5676,
      juz: 30,
      surah: 78,
    },
    {
      number: 5,
      image: "",
      text: "Then Nay (soon) they will know (5)",
      transliteration: "thumma kallā sayaʿlamūna ",
      verse: 5677,
      juz: 30,
      surah: 78,
    },
    {
      number: 6,
      image: "",
      text: "Have not We made the earth a resting place (6)",
      transliteration: "alam najʿali l-arḍa mihādan ",
      verse: 5678,
      juz: 30,
      surah: 78,
    },
    {
      number: 7,
      image: "",
      text: "And the mountains (as) pegs (7)",
      transliteration: "wal-jibāla awtādan ",
      verse: 5679,
      juz: 30,
      surah: 78,
    },
    {
      number: 8,
      image: "",
      text: "And We created you (in) pairs (8)",
      transliteration: "wakhalaqnākum azwājan ",
      verse: 5680,
      juz: 30,
      surah: 78,
    },
    {
      number: 9,
      image: "",
      text: "And We made your sleep (for) rest (9)",
      transliteration: "wajaʿalnā nawmakum subātan ",
      verse: 5681,
      juz: 30,
      surah: 78,
    },
    {
      number: 10,
      image: "",
      text: "And We made the night (as) covering (10)",
      transliteration: "wajaʿalnā al-layla libāsan ",
      verse: 5682,
      juz: 30,
      surah: 78,
    },
    {
      number: 11,
      image: "",
      text: "And We made the day (for) livelihood (11)",
      transliteration: "wajaʿalnā l-nahāra maʿāshan ",
      verse: 5683,
      juz: 30,
      surah: 78,
    },
    {
      number: 12,
      image: "",
      text: "And We constructed over you seven strong (12)",
      transliteration: "wabanaynā fawqakum sabʿan shidādan ",
      verse: 5684,
      juz: 30,
      surah: 78,
    },
    {
      number: 13,
      image: "",
      text: "And We placed a lamp burning (13)",
      transliteration: "wajaʿalnā sirājan wahhājan ",
      verse: 5685,
      juz: 30,
      surah: 78,
    },
    {
      number: 14,
      image: "",
      text: "And We sent down from the rain clouds water pouring abundantly (14)",
      transliteration: "wa-anzalnā mina l-muʿ'ṣirāti māan thajjājan ",
      verse: 5686,
      juz: 30,
      surah: 78,
    },
    {
      number: 15,
      image: "",
      text: "That We may bring forth thereby grain and vegetation (15)",
      transliteration: "linukh'rija bihi ḥabban wanabātan ",
      verse: 5687,
      juz: 30,
      surah: 78,
    },
    {
      number: 16,
      image: "",
      text: "And gardens (of) thick foliage (16)",
      transliteration: "wajannātin alfāfan ",
      verse: 5688,
      juz: 30,
      surah: 78,
    },
    {
      number: 17,
      image: "",
      text: "Indeed (the) Day (of) the Judgment is an appointed time (17)",
      transliteration: "inna yawma l-faṣli kāna mīqātan ",
      verse: 5689,
      juz: 30,
      surah: 78,
    },
    {
      number: 18,
      image: "",
      text: "(The) Day (in which) shall be blown in the trumpet and you will come forth (in) crowds (18)",
      transliteration: "yawma yunfakhu fī l-ṣūri fatatūna afwājan ",
      verse: 5690,
      juz: 30,
      surah: 78,
    },
    {
      number: 19,
      image: "",
      text: "And is opened the heaven and becomes gateways (19)",
      transliteration: "wafutiḥati l-samāu fakānat abwāban ",
      verse: 5691,
      juz: 30,
      surah: 78,
    },
    {
      number: 20,
      image: "",
      text: "And are moved the mountains and become a mirage (20)",
      transliteration: "wasuyyirati l-jibālu fakānat sarāban ",
      verse: 5692,
      juz: 30,
      surah: 78,
    },
    {
      number: 21,
      image: "",
      text: "Indeed Hell is lying in wait (21)",
      transliteration: "inna jahannama kānat mir'ṣādan ",
      verse: 5693,
      juz: 30,
      surah: 78,
    },
    {
      number: 22,
      image: "",
      text: "For the transgressors a place of return (22)",
      transliteration: "lilṭṭāghīna maāban ",
      verse: 5694,
      juz: 30,
      surah: 78,
    },
    {
      number: 23,
      image: "",
      text: "(They will) be remaining therein (for) ages (23)",
      transliteration: "lābithīna fīhā aḥqāban ",
      verse: 5695,
      juz: 30,
      surah: 78,
    },
    {
      number: 24,
      image: "",
      text: "Not they will taste therein coolness and not any drink (24)",
      transliteration: "lā yadhūqūna fīhā bardan walā sharāban ",
      verse: 5696,
      juz: 30,
      surah: 78,
    },
    {
      number: 25,
      image: "",
      text: "Except scalding water and purulence (25)",
      transliteration: "illā ḥamīman waghassāqan ",
      verse: 5697,
      juz: 30,
      surah: 78,
    },
    {
      number: 26,
      image: "",
      text: "A recompense appropriate (26)",
      transliteration: "jazāan wifāqan ",
      verse: 5698,
      juz: 30,
      surah: 78,
    },
    {
      number: 27,
      image: "",
      text: "Indeed, they were not expecting an account (27)",
      transliteration: "innahum kānū lā yarjūna ḥisāban ",
      verse: 5699,
      juz: 30,
      surah: 78,
    },
    {
      number: 28,
      image: "",
      text: "And they denied Our Signs (with) denial (28)",
      transliteration: "wakadhabū biāyātinā kidhāban ",
      verse: 5700,
      juz: 30,
      surah: 78,
    },
    {
      number: 29,
      image: "",
      text: "And every thing We have enumerated it (in) a Book (29)",
      transliteration: "wakulla shayin aḥṣaynāhu kitāban ",
      verse: 5701,
      juz: 30,
      surah: 78,
    },
    {
      number: 30,
      image: "",
      text: "So taste and never We will increase you except (in) punishment (30)",
      transliteration: "fadhūqū falan nazīdakum illā ʿadhāban ",
      verse: 5702,
      juz: 30,
      surah: 78,
    },
    {
      number: 31,
      image: "",
      text: "Indeed for the righteous (is) success (31)",
      transliteration: "inna lil'muttaqīna mafāzan ",
      verse: 5703,
      juz: 30,
      surah: 78,
    },
    {
      number: 32,
      image: "",
      text: "Gardens and grapevines (32)",
      transliteration: "ḥadāiqa wa-aʿnāban ",
      verse: 5704,
      juz: 30,
      surah: 78,
    },
    {
      number: 33,
      image: "",
      text: "And splendid companions well-matched (33)",
      transliteration: "wakawāʿiba atrāban ",
      verse: 5705,
      juz: 30,
      surah: 78,
    },
    {
      number: 34,
      image: "",
      text: "And a cup full (34)",
      transliteration: "wakasan dihāqan ",
      verse: 5706,
      juz: 30,
      surah: 78,
    },
    {
      number: 35,
      image: "",
      text: "Not they will hear therein any vain talk and not any falsehood (35)",
      transliteration: "lā yasmaʿūna fīhā laghwan walā kidhāban ",
      verse: 5707,
      juz: 30,
      surah: 78,
    },
    {
      number: 36,
      image: "",
      text: "(As) a reward from your Lord a gift (according to) account (36)",
      transliteration: "jazāan min rabbika ʿaṭāan ḥisāban ",
      verse: 5708,
      juz: 30,
      surah: 78,
    },
    {
      number: 37,
      image: "",
      text: "Lord (of) the heavens and the earth and whatever (is) between both of them the Most Gracious not they have power from Him (to) address (37)",
      transliteration:
        "rabbi l-samāwāti wal-arḍi wamā baynahumā l-raḥmāni lā yamlikūna min'hu khiṭāban ",
      verse: 5709,
      juz: 30,
      surah: 78,
    },
    {
      number: 38,
      image: "",
      text: "(The) Day will stand the Spirit and the Angels (in) rows not they will speak except (one) who  permits [for] him the Most Gracious and he (will) say (what is) correct (38)",
      transliteration:
        "yawma yaqūmu l-rūḥu wal-malāikatu ṣaffan lā yatakallamūna illā man adhina lahu l-raḥmānu waqāla ṣawāban ",
      verse: 5710,
      juz: 30,
      surah: 78,
    },
    {
      number: 39,
      image: "",
      text: "That (is) the Day the True So whoever wills let him take towards his Lord a return (39)",
      transliteration:
        "dhālika l-yawmu l-ḥaqu faman shāa ittakhadha ilā rabbihi maāban ",
      verse: 5711,
      juz: 30,
      surah: 78,
    },
    {
      number: 40,
      image: "",
      text: "Indeed We [We] have warned you (of) a punishment near (the) Day will see the man what have sent forth his hands and will say the disbeliever O I wish I were dust (40)",
      transliteration:
        "innā andharnākum ʿadhāban qarīban yawma yanẓuru l-maru mā qaddamat yadāhu wayaqūlu l-kāfiru yālaytanī kuntu turāban ",
      verse: 5712,
      juz: 30,
      surah: 78,
    },
  ],
};
