import { Surah } from "../types/islam.js";

export const najm: Surah = {
  name: "An-Najm",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "By the star when it goes down (1)",
      transliteration: "wal-najmi idhā hawā ",
      verse: 4785,
      juz: 27,
      surah: 53,
    },
    {
      number: 2,
      image: "",
      text: "Not has strayed your companion and not has he erred (2)",
      transliteration: "mā ḍalla ṣāḥibukum wamā ghawā ",
      verse: 4786,
      juz: 27,
      surah: 53,
    },
    {
      number: 3,
      image: "",
      text: "And not he speaks from the desire (3)",
      transliteration: "wamā yanṭiqu ʿani l-hawā ",
      verse: 4787,
      juz: 27,
      surah: 53,
    },
    {
      number: 4,
      image: "",
      text: "Not it (is) except a revelation revealed (4)",
      transliteration: "in huwa illā waḥyun yūḥā ",
      verse: 4788,
      juz: 27,
      surah: 53,
    },
    {
      number: 5,
      image: "",
      text: "Has taught him the (one) mighty (in) power (5)",
      transliteration: "ʿallamahu shadīdu l-quwā ",
      verse: 4789,
      juz: 27,
      surah: 53,
    },
    {
      number: 6,
      image: "",
      text: "Possessor of soundness Possessor of soundness And he rose (6)",
      transliteration: "dhū mirratin fa-is'tawā ",
      verse: 4790,
      juz: 27,
      surah: 53,
    },
    {
      number: 7,
      image: "",
      text: "While he (was) in the horizon  the highest (7)",
      transliteration: "wahuwa bil-ufuqi l-aʿlā ",
      verse: 4791,
      juz: 27,
      surah: 53,
    },
    {
      number: 8,
      image: "",
      text: "Then he approached and came down (8)",
      transliteration: "thumma danā fatadallā ",
      verse: 4792,
      juz: 27,
      surah: 53,
    },
    {
      number: 9,
      image: "",
      text: "And was (at) a distance (of) two bow-(lengths) or nearer (9)",
      transliteration: "fakāna qāba qawsayni aw adnā ",
      verse: 4793,
      juz: 27,
      surah: 53,
    },
    {
      number: 10,
      image: "",
      text: "So he revealed to His slave what he revealed (10)",
      transliteration: "fa-awḥā ilā ʿabdihi mā awḥā ",
      verse: 4794,
      juz: 27,
      surah: 53,
    },
    {
      number: 11,
      image: "",
      text: "Not lied the heart what it saw (11)",
      transliteration: "mā kadhaba l-fuādu mā raā ",
      verse: 4795,
      juz: 27,
      surah: 53,
    },
    {
      number: 12,
      image: "",
      text: "Then will you dispute with him about what he saw (12)",
      transliteration: "afatumārūnahu ʿalā mā yarā ",
      verse: 4796,
      juz: 27,
      surah: 53,
    },
    {
      number: 13,
      image: "",
      text: "And certainly he saw him (in) descent another (13)",
      transliteration: "walaqad raāhu nazlatan ukh'rā ",
      verse: 4797,
      juz: 27,
      surah: 53,
    },
    {
      number: 14,
      image: "",
      text: "Near (the) Lote Tree (of) the utmost boundary (14)",
      transliteration: "ʿinda sid'rati l-muntahā ",
      verse: 4798,
      juz: 27,
      surah: 53,
    },
    {
      number: 15,
      image: "",
      text: "Near it (is the) Garden (of) Abode (15)",
      transliteration: "ʿindahā jannatu l-mawā ",
      verse: 4799,
      juz: 27,
      surah: 53,
    },
    {
      number: 16,
      image: "",
      text: "When covered the Lote Tree what covers (16)",
      transliteration: "idh yaghshā l-sid'rata mā yaghshā ",
      verse: 4800,
      juz: 27,
      surah: 53,
    },
    {
      number: 17,
      image: "",
      text: "Not swerved the sight and not it transgressed (17)",
      transliteration: "mā zāgha l-baṣaru wamā ṭaghā ",
      verse: 4801,
      juz: 27,
      surah: 53,
    },
    {
      number: 18,
      image: "",
      text: "Certainly he saw of (the) Signs (of) his Lord the Greatest (18)",
      transliteration: "laqad raā min āyāti rabbihi l-kub'rā ",
      verse: 4802,
      juz: 27,
      surah: 53,
    },
    {
      number: 19,
      image: "",
      text: "So have you seen the Lat and the Uzza (19)",
      transliteration: "afara-aytumu l-lāta wal-ʿuzā ",
      verse: 4803,
      juz: 27,
      surah: 53,
    },
    {
      number: 20,
      image: "",
      text: "And Manat the third the other (20)",
      transliteration: "wamanata l-thālithata l-ukh'rā ",
      verse: 4804,
      juz: 27,
      surah: 53,
    },
    {
      number: 21,
      image: "",
      text: "Is for you the male and for Him the female (21)",
      transliteration: "alakumu l-dhakaru walahu l-unthā ",
      verse: 4805,
      juz: 27,
      surah: 53,
    },
    {
      number: 22,
      image: "",
      text: "This then (is) a division unfair (22)",
      transliteration: "til'ka idhan qis'matun ḍīzā ",
      verse: 4806,
      juz: 27,
      surah: 53,
    },
    {
      number: 23,
      image: "",
      text: "Not they (are) except names you have named them you and your forefathers not has Allah sent down has Allah sent down for it any authority Not they follow except assumption and what desire the(ir) souls And certainly has come to them from their Lord the guidance (23)",
      transliteration:
        "in hiya illā asmāon sammaytumūhā antum waābāukum mā anzala l-lahu bihā min sul'ṭānin in yattabiʿūna illā l-ẓana wamā tahwā l-anfusu walaqad jāahum min rabbihimu l-hudā ",
      verse: 4807,
      juz: 27,
      surah: 53,
    },
    {
      number: 24,
      image: "",
      text: "Or (is) for man what he wishes (24)",
      transliteration: "am lil'insāni mā tamannā ",
      verse: 4808,
      juz: 27,
      surah: 53,
    },
    {
      number: 25,
      image: "",
      text: "But for Allah (is) the last and the first (25)",
      transliteration: "falillahi l-ākhiratu wal-ūlā ",
      verse: 4809,
      juz: 27,
      surah: 53,
    },
    {
      number: 26,
      image: "",
      text: "And how many of (the) Angels in the heavens not will avail their intercession anything except after after [that] Allah has given permission Allah has given permission for whom He wills and approves (26)",
      transliteration:
        "wakam min malakin fī l-samāwāti lā tugh'nī shafāʿatuhum shayan illā min baʿdi an yadhana l-lahu liman yashāu wayarḍā ",
      verse: 4810,
      juz: 27,
      surah: 53,
    },
    {
      number: 27,
      image: "",
      text: "Indeed those who (do) not believe in the Hereafter surely they name the Angels name(s) (of) female (27)",
      transliteration:
        "inna alladhīna lā yu'minūna bil-ākhirati layusammūna l-malāikata tasmiyata l-unthā ",
      verse: 4811,
      juz: 27,
      surah: 53,
    },
    {
      number: 28,
      image: "",
      text: "And not for them about it any knowledge Not they follow but assumption And indeed the assumption (does) not avail against the truth anything (28)",
      transliteration:
        "wamā lahum bihi min ʿil'min in yattabiʿūna illā l-ẓana wa-inna l-ẓana lā yugh'nī mina l-ḥaqi shayan ",
      verse: 4812,
      juz: 27,
      surah: 53,
    },
    {
      number: 29,
      image: "",
      text: "So turn away from (him) who turns away from Our Reminder and not he desires except the life (of) the world (29)",
      transliteration:
        "fa-aʿriḍ ʿan man tawallā ʿan dhik'rinā walam yurid illā l-ḥayata l-dun'yā ",
      verse: 4813,
      juz: 27,
      surah: 53,
    },
    {
      number: 30,
      image: "",
      text: "That (is) their sum of knowledge Indeed your Lord (is) He (Who) knows best (he) who strays from His Path and He knows best (he) who is guided (30)",
      transliteration:
        "dhālika mablaghuhum mina l-ʿil'mi inna rabbaka huwa aʿlamu biman ḍalla ʿan sabīlihi wahuwa aʿlamu bimani ih'tadā ",
      verse: 4814,
      juz: 27,
      surah: 53,
    },
    {
      number: 31,
      image: "",
      text: "And for Allah (is) whatever (is) in the heavens and whatever (is) in the earth that He may recompense those who do evil with what they have done and recompense those who do good with the best (31)",
      transliteration:
        "walillahi mā fī l-samāwāti wamā fī l-arḍi liyajziya alladhīna asāū bimā ʿamilū wayajziya alladhīna aḥsanū bil-ḥus'nā ",
      verse: 4815,
      juz: 27,
      surah: 53,
    },
    {
      number: 32,
      image: "",
      text: "Those who avoid great sins and the immoralities except the small faults indeed your Lord (is) vast (in) forgiveness He (is) most knowing about you (is) most knowing about you when He produced you from the earth and when you (were) fetuses in (the) wombs (of) your mothers So (do) not ascribe purity (to) yourselves He knows best (he) who fears (32)",
      transliteration:
        "alladhīna yajtanibūna kabāira l-ith'mi wal-fawāḥisha illā l-lamama inna rabbaka wāsiʿu l-maghfirati huwa aʿlamu bikum idh ansha-akum mina l-arḍi wa-idh antum ajinnatun fī buṭūni ummahātikum falā tuzakkū anfusakum huwa aʿlamu bimani ittaqā ",
      verse: 4816,
      juz: 27,
      surah: 53,
    },
    {
      number: 33,
      image: "",
      text: "Did you see the one who turned away (33)",
      transliteration: "afara-ayta alladhī tawallā ",
      verse: 4817,
      juz: 27,
      surah: 53,
    },
    {
      number: 34,
      image: "",
      text: "And gave a little and withheld (34)",
      transliteration: "wa-aʿṭā qalīlan wa-akdā ",
      verse: 4818,
      juz: 27,
      surah: 53,
    },
    {
      number: 35,
      image: "",
      text: "Is with him (the) knowledge (of) the unseen so he sees (35)",
      transliteration: "aʿindahu ʿil'mu l-ghaybi fahuwa yarā ",
      verse: 4819,
      juz: 27,
      surah: 53,
    },
    {
      number: 36,
      image: "",
      text: "Or not he was informed with what (was) in (the) Scriptures (of) Musa (36)",
      transliteration: "am lam yunabba bimā fī ṣuḥufi mūsā ",
      verse: 4820,
      juz: 27,
      surah: 53,
    },
    {
      number: 37,
      image: "",
      text: "And Ibrahim who fulfilled (37)",
      transliteration: "wa-ib'rāhīma alladhī waffā ",
      verse: 4821,
      juz: 27,
      surah: 53,
    },
    {
      number: 38,
      image: "",
      text: "That not will bear a bearer of burdens (the) burden (of) another (38)",
      transliteration: "allā taziru wāziratun wiz'ra ukh'rā ",
      verse: 4822,
      juz: 27,
      surah: 53,
    },
    {
      number: 39,
      image: "",
      text: "And that is not for man except what he strives (for) (39)",
      transliteration: "wa-an laysa lil'insāni illā mā saʿā ",
      verse: 4823,
      juz: 27,
      surah: 53,
    },
    {
      number: 40,
      image: "",
      text: "And that his striving will soon be seen (40)",
      transliteration: "wa-anna saʿyahu sawfa yurā ",
      verse: 4824,
      juz: 27,
      surah: 53,
    },
    {
      number: 41,
      image: "",
      text: "Then he will be recompensed for it the recompense the fullest (41)",
      transliteration: "thumma yuj'zāhu l-jazāa l-awfā ",
      verse: 4825,
      juz: 27,
      surah: 53,
    },
    {
      number: 42,
      image: "",
      text: "And that to your Lord (is) the final goal (42)",
      transliteration: "wa-anna ilā rabbika l-muntahā ",
      verse: 4826,
      juz: 27,
      surah: 53,
    },
    {
      number: 43,
      image: "",
      text: "And that He [He] makes (one) laugh and makes (one) weep (43)",
      transliteration: "wa-annahu huwa aḍḥaka wa-abkā ",
      verse: 4827,
      juz: 27,
      surah: 53,
    },
    {
      number: 44,
      image: "",
      text: "And that He [He] causes death and gives life (44)",
      transliteration: "wa-annahu huwa amāta wa-aḥyā ",
      verse: 4828,
      juz: 27,
      surah: 53,
    },
    {
      number: 45,
      image: "",
      text: "And that He created the pairs the male and the female (45)",
      transliteration: "wa-annahu khalaqa l-zawjayni l-dhakara wal-unthā ",
      verse: 4829,
      juz: 27,
      surah: 53,
    },
    {
      number: 46,
      image: "",
      text: "From a semen-drop when it is emitted (46)",
      transliteration: "min nuṭ'fatin idhā tum'nā ",
      verse: 4830,
      juz: 27,
      surah: 53,
    },
    {
      number: 47,
      image: "",
      text: "And that upon Him (is) the bringing forth another (47)",
      transliteration: "wa-anna ʿalayhi l-nashata l-ukh'rā ",
      verse: 4831,
      juz: 27,
      surah: 53,
    },
    {
      number: 48,
      image: "",
      text: "And that He [He] enriches and suffices (48)",
      transliteration: "wa-annahu huwa aghnā wa-aqnā ",
      verse: 4832,
      juz: 27,
      surah: 53,
    },
    {
      number: 49,
      image: "",
      text: "And that He [He] (is the) Lord (of) Sirius (49)",
      transliteration: "wa-annahu huwa rabbu l-shiʿ'rā ",
      verse: 4833,
      juz: 27,
      surah: 53,
    },
    {
      number: 50,
      image: "",
      text: "And that He destroyed Aad the first (50)",
      transliteration: "wa-annahu ahlaka ʿādan l-ūlā ",
      verse: 4834,
      juz: 27,
      surah: 53,
    },
    {
      number: 51,
      image: "",
      text: "And Thamud so not He spared (51)",
      transliteration: "wathamūdā famā abqā ",
      verse: 4835,
      juz: 27,
      surah: 53,
    },
    {
      number: 52,
      image: "",
      text: "And (the) people (of) Nuh before before Indeed, they they were they were more unjust and more rebellious (52)",
      transliteration:
        "waqawma nūḥin min qablu innahum kānū hum aẓlama wa-aṭghā ",
      verse: 4836,
      juz: 27,
      surah: 53,
    },
    {
      number: 53,
      image: "",
      text: "And the overturned cities He overthrew (53)",
      transliteration: "wal-mu'tafikata ahwā ",
      verse: 4837,
      juz: 27,
      surah: 53,
    },
    {
      number: 54,
      image: "",
      text: "So covered them what covered (54)",
      transliteration: "faghashāhā mā ghashā ",
      verse: 4838,
      juz: 27,
      surah: 53,
    },
    {
      number: 55,
      image: "",
      text: "Then which (of) the Favors (of) your Lord will you doubt (55)",
      transliteration: "fabi-ayyi ālāi rabbika tatamārā ",
      verse: 4839,
      juz: 27,
      surah: 53,
    },
    {
      number: 56,
      image: "",
      text: "This (is) a warner from the warners the former (56)",
      transliteration: "hādhā nadhīrun mina l-nudhuri l-ūlā ",
      verse: 4840,
      juz: 27,
      surah: 53,
    },
    {
      number: 57,
      image: "",
      text: "Has approached the Approaching Day (57)",
      transliteration: "azifati l-āzifatu ",
      verse: 4841,
      juz: 27,
      surah: 53,
    },
    {
      number: 58,
      image: "",
      text: "Not is for it besides besides Allah any remover (58)",
      transliteration: "laysa lahā min dūni l-lahi kāshifatun ",
      verse: 4842,
      juz: 27,
      surah: 53,
    },
    {
      number: 59,
      image: "",
      text: "Then of this statement you wonder (59)",
      transliteration: "afamin hādhā l-ḥadīthi taʿjabūna ",
      verse: 4843,
      juz: 27,
      surah: 53,
    },
    {
      number: 60,
      image: "",
      text: "And you laugh and (do) not weep (60)",
      transliteration: "wataḍḥakūna walā tabkūna ",
      verse: 4844,
      juz: 27,
      surah: 53,
    },
    {
      number: 61,
      image: "",
      text: "While you amuse (yourselves) (61)",
      transliteration: "wa-antum sāmidūna ",
      verse: 4845,
      juz: 27,
      surah: 53,
    },
    {
      number: 62,
      image: "",
      text: "So prostrate to Allah and worship (Him) (62)",
      transliteration: "fa-us'judū lillahi wa-uʿ'budū ",
      verse: 4846,
      juz: 27,
      surah: 53,
    },
  ],
};
