import { Surah } from "../types/islam.js";

export const nas: Surah = {
  name: "An-Nas",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "Say I seek refuge in (the) Lord (of) mankind (1)",
      transliteration: "qul aʿūdhu birabbi l-nāsi ",
      verse: 6231,
      juz: 30,
      surah: 114,
    },
    {
      number: 2,
      image: "",
      text: "(The) King (of) mankind (2)",
      transliteration: "maliki l-nāsi ",
      verse: 6232,
      juz: 30,
      surah: 114,
    },
    {
      number: 3,
      image: "",
      text: "(The) God (of) mankind (3)",
      transliteration: "ilāhi l-nāsi ",
      verse: 6233,
      juz: 30,
      surah: 114,
    },
    {
      number: 4,
      image: "",
      text: "From (the) evil (of) the whisperer the one who withdraws (4)",
      transliteration: "min sharri l-waswāsi l-khanāsi ",
      verse: 6234,
      juz: 30,
      surah: 114,
    },
    {
      number: 5,
      image: "",
      text: "The one who whispers in (the) breasts (of) mankind (5)",
      transliteration: "alladhī yuwaswisu fī ṣudūri l-nāsi ",
      verse: 6235,
      juz: 30,
      surah: 114,
    },
    {
      number: 6,
      image: "",
      text: "From the jinn and men (6)",
      transliteration: "mina l-jinati wal-nāsi ",
      verse: 6236,
      juz: 30,
      surah: 114,
    },
  ],
};
