import { Surah } from "../types/islam.js";

export const naziat: Surah = {
  name: "An-Naz'iat",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "By those who extract violently (1)",
      transliteration: "wal-nāziʿāti gharqan ",
      verse: 5713,
      juz: 30,
      surah: 79,
    },
    {
      number: 2,
      image: "",
      text: "And those who draw out gently (2)",
      transliteration: "wal-nāshiṭāti nashṭan ",
      verse: 5714,
      juz: 30,
      surah: 79,
    },
    {
      number: 3,
      image: "",
      text: "And those who glide swimming (3)",
      transliteration: "wal-sābiḥāti sabḥan ",
      verse: 5715,
      juz: 30,
      surah: 79,
    },
    {
      number: 4,
      image: "",
      text: "And those who race each other (in) a race (4)",
      transliteration: "fal-sābiqāti sabqan ",
      verse: 5716,
      juz: 30,
      surah: 79,
    },
    {
      number: 5,
      image: "",
      text: "And those who arrange (the) matter (5)",
      transliteration: "fal-mudabirāti amran ",
      verse: 5717,
      juz: 30,
      surah: 79,
    },
    {
      number: 6,
      image: "",
      text: "(The) Day will quake the quaking one (6)",
      transliteration: "yawma tarjufu l-rājifatu ",
      verse: 5718,
      juz: 30,
      surah: 79,
    },
    {
      number: 7,
      image: "",
      text: "Follows it the subsequent (7)",
      transliteration: "tatbaʿuhā l-rādifatu ",
      verse: 5719,
      juz: 30,
      surah: 79,
    },
    {
      number: 8,
      image: "",
      text: "Hearts that Day will palpitate (8)",
      transliteration: "qulūbun yawma-idhin wājifatun ",
      verse: 5720,
      juz: 30,
      surah: 79,
    },
    {
      number: 9,
      image: "",
      text: "Their eyes humbled (9)",
      transliteration: "abṣāruhā khāshiʿatun ",
      verse: 5721,
      juz: 30,
      surah: 79,
    },
    {
      number: 10,
      image: "",
      text: "They say Will we indeed be returned to the former state (10)",
      transliteration: "yaqūlūna a-innā lamardūdūna fī l-ḥāfirati ",
      verse: 5722,
      juz: 30,
      surah: 79,
    },
    {
      number: 11,
      image: "",
      text: "What! When we are bones decayed (11)",
      transliteration: "a-idhā kunnā ʿiẓāman nakhiratan ",
      verse: 5723,
      juz: 30,
      surah: 79,
    },
    {
      number: 12,
      image: "",
      text: "They say This then (would be) a return losing (12)",
      transliteration: "qālū til'ka idhan karratun khāsiratun ",
      verse: 5724,
      juz: 30,
      surah: 79,
    },
    {
      number: 13,
      image: "",
      text: "Then only it (will be) a shout single (13)",
      transliteration: "fa-innamā hiya zajratun wāḥidatun ",
      verse: 5725,
      juz: 30,
      surah: 79,
    },
    {
      number: 14,
      image: "",
      text: "And behold They (will be) awakened (14)",
      transliteration: "fa-idhā hum bil-sāhirati ",
      verse: 5726,
      juz: 30,
      surah: 79,
    },
    {
      number: 15,
      image: "",
      text: "Has (there) come to you (the) story (of) Musa (15)",
      transliteration: "hal atāka ḥadīthu mūsā ",
      verse: 5727,
      juz: 30,
      surah: 79,
    },
    {
      number: 16,
      image: "",
      text: "When called him his Lord in the valley the sacred (of) Tuwa (16)",
      transliteration: "idh nādāhu rabbuhu bil-wādi l-muqadasi ṭuwan ",
      verse: 5728,
      juz: 30,
      surah: 79,
    },
    {
      number: 17,
      image: "",
      text: "Go to Firaun Indeed, he (has) transgressed (17)",
      transliteration: "idh'hab ilā fir'ʿawna innahu ṭaghā ",
      verse: 5729,
      juz: 30,
      surah: 79,
    },
    {
      number: 18,
      image: "",
      text: "And say Would [for] you [to] [that] purify yourself (18)",
      transliteration: "faqul hal laka ilā an tazakkā ",
      verse: 5730,
      juz: 30,
      surah: 79,
    },
    {
      number: 19,
      image: "",
      text: "And I will guide you to your Lord so you would fear (19)",
      transliteration: "wa-ahdiyaka ilā rabbika fatakhshā ",
      verse: 5731,
      juz: 30,
      surah: 79,
    },
    {
      number: 20,
      image: "",
      text: "Then he showed him the sign the great (20)",
      transliteration: "fa-arāhu l-āyata l-kub'rā ",
      verse: 5732,
      juz: 30,
      surah: 79,
    },
    {
      number: 21,
      image: "",
      text: "But he denied and disobeyed (21)",
      transliteration: "fakadhaba waʿaṣā ",
      verse: 5733,
      juz: 30,
      surah: 79,
    },
    {
      number: 22,
      image: "",
      text: "Then he turned his back striving (22)",
      transliteration: "thumma adbara yasʿā ",
      verse: 5734,
      juz: 30,
      surah: 79,
    },
    {
      number: 23,
      image: "",
      text: "And he gathered and called out (23)",
      transliteration: "faḥashara fanādā ",
      verse: 5735,
      juz: 30,
      surah: 79,
    },
    {
      number: 24,
      image: "",
      text: "Then he said I am your Lord the Most High (24)",
      transliteration: "faqāla anā rabbukumu l-aʿlā ",
      verse: 5736,
      juz: 30,
      surah: 79,
    },
    {
      number: 25,
      image: "",
      text: "So seized him Allah (with) an exemplary punishment (for) the last and the first (25)",
      transliteration: "fa-akhadhahu l-lahu nakāla l-ākhirati wal-ūlā ",
      verse: 5737,
      juz: 30,
      surah: 79,
    },
    {
      number: 26,
      image: "",
      text: "Indeed in that surely (is) a lesson for whoever fears (26)",
      transliteration: "inna fī dhālika laʿib'ratan liman yakhshā ",
      verse: 5738,
      juz: 30,
      surah: 79,
    },
    {
      number: 27,
      image: "",
      text: "Are you a more difficult creation or the heaven He constructed it (27)",
      transliteration: "a-antum ashaddu khalqan ami l-samāu banāhā ",
      verse: 5739,
      juz: 30,
      surah: 79,
    },
    {
      number: 28,
      image: "",
      text: "He raised its ceiling and proportioned it (28)",
      transliteration: "rafaʿa samkahā fasawwāhā ",
      verse: 5740,
      juz: 30,
      surah: 79,
    },
    {
      number: 29,
      image: "",
      text: "And He darkened its night and brought out its brightness (29)",
      transliteration: "wa-aghṭasha laylahā wa-akhraja ḍuḥāhā ",
      verse: 5741,
      juz: 30,
      surah: 79,
    },
    {
      number: 30,
      image: "",
      text: "And the earth after that He spread it (30)",
      transliteration: "wal-arḍa baʿda dhālika daḥāhā ",
      verse: 5742,
      juz: 30,
      surah: 79,
    },
    {
      number: 31,
      image: "",
      text: "He brought forth from it its water and its pasture (31)",
      transliteration: "akhraja min'hā māahā wamarʿāhā ",
      verse: 5743,
      juz: 30,
      surah: 79,
    },
    {
      number: 32,
      image: "",
      text: "And the mountains He made them firm (32)",
      transliteration: "wal-jibāla arsāhā ",
      verse: 5744,
      juz: 30,
      surah: 79,
    },
    {
      number: 33,
      image: "",
      text: "(As) a provision for you and for your cattle (33)",
      transliteration: "matāʿan lakum wali-anʿāmikum ",
      verse: 5745,
      juz: 30,
      surah: 79,
    },
    {
      number: 34,
      image: "",
      text: "But when comes the Overwhelming Calamity the great (34)",
      transliteration: "fa-idhā jāati l-ṭāmatu l-kub'rā ",
      verse: 5746,
      juz: 30,
      surah: 79,
    },
    {
      number: 35,
      image: "",
      text: "(The) Day will remember man what he strove (for) (35)",
      transliteration: "yawma yatadhakkaru l-insānu mā saʿā ",
      verse: 5747,
      juz: 30,
      surah: 79,
    },
    {
      number: 36,
      image: "",
      text: "And will be made manifest the Hellfire to (him) who sees (36)",
      transliteration: "waburrizati l-jaḥīmu liman yarā ",
      verse: 5748,
      juz: 30,
      surah: 79,
    },
    {
      number: 37,
      image: "",
      text: "Then as for (him) who transgressed (37)",
      transliteration: "fa-ammā man ṭaghā ",
      verse: 5749,
      juz: 30,
      surah: 79,
    },
    {
      number: 38,
      image: "",
      text: "And preferred the life (of) the world (38)",
      transliteration: "waāthara l-ḥayata l-dun'yā ",
      verse: 5750,
      juz: 30,
      surah: 79,
    },
    {
      number: 39,
      image: "",
      text: "Then indeed the Hellfire it (is) the refuge (39)",
      transliteration: "fa-inna l-jaḥīma hiya l-mawā ",
      verse: 5751,
      juz: 30,
      surah: 79,
    },
    {
      number: 40,
      image: "",
      text: "But as for (him) who feared standing (before) his Lord and restrained his soul from the vain desires (40)",
      transliteration:
        "wa-ammā man khāfa maqāma rabbihi wanahā l-nafsa ʿani l-hawā ",
      verse: 5752,
      juz: 30,
      surah: 79,
    },
    {
      number: 41,
      image: "",
      text: "Then indeed Paradise  it (is) the refuge (41)",
      transliteration: "fa-inna l-janata hiya l-mawā ",
      verse: 5753,
      juz: 30,
      surah: 79,
    },
    {
      number: 42,
      image: "",
      text: "They ask you about the Hour when (is) its arrival (42)",
      transliteration: "yasalūnaka ʿani l-sāʿati ayyāna mur'sāhā ",
      verse: 5754,
      juz: 30,
      surah: 79,
    },
    {
      number: 43,
      image: "",
      text: "In what (are) you [of] (to) mention it (43)",
      transliteration: "fīma anta min dhik'rāhā ",
      verse: 5755,
      juz: 30,
      surah: 79,
    },
    {
      number: 44,
      image: "",
      text: "To your Lord (is) its finality (44)",
      transliteration: "ilā rabbika muntahāhā ",
      verse: 5756,
      juz: 30,
      surah: 79,
    },
    {
      number: 45,
      image: "",
      text: "Only you (are) a warner (for him) who fears it (45)",
      transliteration: "innamā anta mundhiru man yakhshāhā ",
      verse: 5757,
      juz: 30,
      surah: 79,
    },
    {
      number: 46,
      image: "",
      text: "As though they (the) Day they see it not they had remained except an evening or a morning thereof (46)",
      transliteration:
        "ka-annahum yawma yarawnahā lam yalbathū illā ʿashiyyatan aw ḍuḥāhā ",
      verse: 5758,
      juz: 30,
      surah: 79,
    },
  ],
};
