import { Surah } from "../types/islam.ts";

export const naziat: Surah = {
  name: "An-Naz'iat",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "By those [angels] who extract with violence",
      verse: 5582,
    },
    {
      number: 2,
      image: "",
      text: "And [by] those who remove with ease",
      verse: 5583,
    },
    {
      number: 3,
      image: "",
      text: "And [by] those who glide [as if] swimming",
      verse: 5584,
    },
    {
      number: 4,
      image: "",
      text: "And those who race each other in a race",
      verse: 5585,
    },
    {
      number: 5,
      image: "",
      text: "And those who arrange [each] matter,",
      verse: 5586,
    },
    {
      number: 6,
      image: "",
      text: "On the Day the blast [of the Horn] will convulse [creation],",
      verse: 5587,
    },
    {
      number: 7,
      image: "",
      text: "There will follow it the subsequent [one].",
      verse: 5588,
    },
    {
      number: 8,
      image: "",
      text: "Hearts, that Day, will tremble,",
      verse: 5589,
    },
    { number: 9, image: "", text: "Their eyes humbled.", verse: 5590 },
    {
      number: 10,
      image: "",
      text:
        'They are [presently] saying, "Will we indeed be returned to [our] former state [of life]?',
      verse: 5591,
    },
    {
      number: 11,
      image: "",
      text: "Even if we should be decayed bones?",
      verse: 5592,
    },
    {
      number: 12,
      image: "",
      text: 'They say, "That, then, would be a losing return."',
      verse: 5593,
    },
    {
      number: 13,
      image: "",
      text: "Indeed, it will be but one shout,",
      verse: 5594,
    },
    {
      number: 14,
      image: "",
      text: "And suddenly they will be [alert] upon the earth's surface.",
      verse: 5595,
    },
    {
      number: 15,
      image: "",
      text: "Has there reached you the story of Moses? -",
      verse: 5596,
    },
    {
      number: 16,
      image: "",
      text: "When his Lord called to him in the sacred valley of Tuwa,",
      verse: 5597,
    },
    {
      number: 17,
      image: "",
      text: '"Go to Pharaoh. Indeed, he has transgressed.',
      verse: 5598,
    },
    {
      number: 18,
      image: "",
      text: "And say to him, 'Would you [be willing to] purify yourself",
      verse: 5599,
    },
    {
      number: 19,
      image: "",
      text: "And let me guide you to your Lord so you would fear [Him]?'\"",
      verse: 5600,
    },
    {
      number: 20,
      image: "",
      text: "And he showed him the greatest sign,",
      verse: 5601,
    },
    {
      number: 21,
      image: "",
      text: "But Pharaoh denied and disobeyed.",
      verse: 5602,
    },
    {
      number: 22,
      image: "",
      text: "Then he turned his back, striving.",
      verse: 5603,
    },
    {
      number: 23,
      image: "",
      text: "And he gathered [his people] and called out",
      verse: 5604,
    },
    {
      number: 24,
      image: "",
      text: 'And said, "I am your most exalted lord."',
      verse: 5605,
    },
    {
      number: 25,
      image: "",
      text:
        "So Allah seized him in exemplary punishment for the last and the first [transgression].",
      verse: 5606,
    },
    {
      number: 26,
      image: "",
      text: "Indeed in that is a warning for whoever would fear [ Allah ].",
      verse: 5607,
    },
    {
      number: 27,
      image: "",
      text:
        "Are you a more difficult creation or is the heaven? Allah constructed it.",
      verse: 5608,
    },
    {
      number: 28,
      image: "",
      text: "He raised its ceiling and proportioned it.",
      verse: 5609,
    },
    {
      number: 29,
      image: "",
      text: "And He darkened its night and extracted its brightness.",
      verse: 5610,
    },
    {
      number: 30,
      image: "",
      text: "And after that He spread the earth.",
      verse: 5611,
    },
    {
      number: 31,
      image: "",
      text: "He extracted from it its water and its pasture,",
      verse: 5612,
    },
    {
      number: 32,
      image: "",
      text: "And the mountains He set firmly",
      verse: 5613,
    },
    {
      number: 33,
      image: "",
      text: "As provision for you and your grazing livestock.",
      verse: 5614,
    },
    {
      number: 34,
      image: "",
      text: "But when there comes the greatest Overwhelming Calamity -",
      verse: 5615,
    },
    {
      number: 35,
      image: "",
      text: "The Day when man will remember that for which he strove,",
      verse: 5616,
    },
    {
      number: 36,
      image: "",
      text: "And Hellfire will be exposed for [all] those who see -",
      verse: 5617,
    },
    {
      number: 37,
      image: "",
      text: "So as for he who transgressed",
      verse: 5618,
    },
    {
      number: 38,
      image: "",
      text: "And preferred the life of the world,",
      verse: 5619,
    },
    {
      number: 39,
      image: "",
      text: "Then indeed, Hellfire will be [his] refuge.",
      verse: 5620,
    },
    {
      number: 40,
      image: "",
      text:
        "But as for he who feared the position of his Lord and prevented the soul from [unlawful] inclination,",
      verse: 5621,
    },
    {
      number: 41,
      image: "",
      text: "Then indeed, Paradise will be [his] refuge.",
      verse: 5622,
    },
    {
      number: 42,
      image: "",
      text: "They ask you, [O Muhammad], about the Hour: when is its arrival?",
      verse: 5623,
    },
    {
      number: 43,
      image: "",
      text: "In what [position] are you that you should mention it?",
      verse: 5624,
    },
    {
      number: 44,
      image: "",
      text: "To your Lord is its finality.",
      verse: 5625,
    },
    {
      number: 45,
      image: "",
      text: "You are only a warner for those who fear it.",
      verse: 5626,
    },
    {
      number: 46,
      image: "",
      text:
        "It will be, on the Day they see it, as though they had not remained [in the world] except for an afternoon or a morning thereof.",
      verse: 5627,
    },
  ],
};
