import { Surah } from "../types/islam.js";

export const nuh: Surah = {
  name: "Nuh",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "Indeed, We [We] sent Nuh to his people that Warn your people from before [that] comes to them a punishment painful (1)",
      transliteration:
        "innā arsalnā nūḥan ilā qawmihi an andhir qawmaka min qabli an yatiyahum ʿadhābun alīmun ",
      verse: 5420,
      juz: 29,
      surah: 71,
    },
    {
      number: 2,
      image: "",
      text: "He said O my people Indeed, I am to you a warner clear (2)",
      transliteration: "qāla yāqawmi innī lakum nadhīrun mubīnun ",
      verse: 5421,
      juz: 29,
      surah: 71,
    },
    {
      number: 3,
      image: "",
      text: "That Worship Allah and fear Him and obey me (3)",
      transliteration: "ani uʿ'budū l-laha wa-ittaqūhu wa-aṭīʿūni ",
      verse: 5422,
      juz: 29,
      surah: 71,
    },
    {
      number: 4,
      image: "",
      text: "He will forgive for you [of] your sins and give you respite for a term specified Indeed (the) term (of) Allah when it comes not is delayed if you know (4)",
      transliteration:
        "yaghfir lakum min dhunūbikum wayu-akhir'kum ilā ajalin musamman inna ajala l-lahi idhā jāa lā yu-akharu law kuntum taʿlamūna ",
      verse: 5423,
      juz: 29,
      surah: 71,
    },
    {
      number: 5,
      image: "",
      text: "He said My Lord Indeed, I invited my people night and day (5)",
      transliteration: "qāla rabbi innī daʿawtu qawmī laylan wanahāran ",
      verse: 5424,
      juz: 29,
      surah: 71,
    },
    {
      number: 6,
      image: "",
      text: "But not increased them my invitation except (in) flight (6)",
      transliteration: "falam yazid'hum duʿāī illā firāran ",
      verse: 5425,
      juz: 29,
      surah: 71,
    },
    {
      number: 7,
      image: "",
      text: "And indeed, I every time I invited them that You may forgive them they put their fingers in their ears and covered themselves (with) their garments and persisted and were arrogant (with) pride (7)",
      transliteration:
        "wa-innī kullamā daʿawtuhum litaghfira lahum jaʿalū aṣābiʿahum fī ādhānihim wa-is'taghshaw thiyābahum wa-aṣarrū wa-is'takbarū is'tik'bāran ",
      verse: 5426,
      juz: 29,
      surah: 71,
    },
    {
      number: 8,
      image: "",
      text: "Then indeed, I invited them publicly (8)",
      transliteration: "thumma innī daʿawtuhum jihāran ",
      verse: 5427,
      juz: 29,
      surah: 71,
    },
    {
      number: 9,
      image: "",
      text: "Then indeed, I announced to them and I confided to them secretly (9)",
      transliteration: "thumma innī aʿlantu lahum wa-asrartu lahum is'rāran ",
      verse: 5428,
      juz: 29,
      surah: 71,
    },
    {
      number: 10,
      image: "",
      text: "Then I said Ask forgiveness (from) your Lord Indeed, He is Oft-Forgiving (10)",
      transliteration: "faqul'tu is'taghfirū rabbakum innahu kāna ghaffāran ",
      verse: 5429,
      juz: 29,
      surah: 71,
    },
    {
      number: 11,
      image: "",
      text: "He will send down (rain from) the sky upon you (in) abundance (11)",
      transliteration: "yur'sili l-samāa ʿalaykum mid'rāran ",
      verse: 5430,
      juz: 29,
      surah: 71,
    },
    {
      number: 12,
      image: "",
      text: "And provide you with wealth and children and make for you gardens and make for you rivers (12)",
      transliteration:
        "wayum'did'kum bi-amwālin wabanīna wayajʿal lakum jannātin wayajʿal lakum anhāran ",
      verse: 5431,
      juz: 29,
      surah: 71,
    },
    {
      number: 13,
      image: "",
      text: "What (is) for you not you attribute to Allah grandeur (13)",
      transliteration: "mā lakum lā tarjūna lillahi waqāran ",
      verse: 5432,
      juz: 29,
      surah: 71,
    },
    {
      number: 14,
      image: "",
      text: "And indeed He created you (in) stages (14)",
      transliteration: "waqad khalaqakum aṭwāran ",
      verse: 5433,
      juz: 29,
      surah: 71,
    },
    {
      number: 15,
      image: "",
      text: "Do not you see how did create Allah (the) seven heavens (in) layers (15)",
      transliteration:
        "alam taraw kayfa khalaqa l-lahu sabʿa samāwātin ṭibāqan ",
      verse: 5434,
      juz: 29,
      surah: 71,
    },
    {
      number: 16,
      image: "",
      text: "And made the moon therein a light and made the sun a lamp (16)",
      transliteration:
        "wajaʿala l-qamara fīhinna nūran wajaʿala l-shamsa sirājan ",
      verse: 5435,
      juz: 29,
      surah: 71,
    },
    {
      number: 17,
      image: "",
      text: "And Allah has caused you to grow from the earth (as) a growth (17)",
      transliteration: "wal-lahu anbatakum mina l-arḍi nabātan ",
      verse: 5436,
      juz: 29,
      surah: 71,
    },
    {
      number: 18,
      image: "",
      text: "Then He will return you into it and bring you forth (a new) bringing forth (18)",
      transliteration: "thumma yuʿīdukum fīhā wayukh'rijukum ikh'rājan ",
      verse: 5437,
      juz: 29,
      surah: 71,
    },
    {
      number: 19,
      image: "",
      text: "And Allah made for you the earth an expanse (19)",
      transliteration: "wal-lahu jaʿala lakumu l-arḍa bisāṭan ",
      verse: 5438,
      juz: 29,
      surah: 71,
    },
    {
      number: 20,
      image: "",
      text: "That you may go along therein (in) paths wide (20)",
      transliteration: "litaslukū min'hā subulan fijājan ",
      verse: 5439,
      juz: 29,
      surah: 71,
    },
    {
      number: 21,
      image: "",
      text: "Said Nuh My Lord Indeed, they disobeyed me and followed (the one) who (did) not increase him his wealth and his children except (in) loss (21)",
      transliteration:
        "qāla nūḥun rabbi innahum ʿaṣawnī wa-ittabaʿū man lam yazid'hu māluhu wawaladuhu illā khasāran ",
      verse: 5440,
      juz: 29,
      surah: 71,
    },
    {
      number: 22,
      image: "",
      text: "And they have planned a plan great (22)",
      transliteration: "wamakarū makran kubbāran ",
      verse: 5441,
      juz: 29,
      surah: 71,
    },
    {
      number: 23,
      image: "",
      text: "And they said (Do) not leave your gods and (do) not leave Wadd and not Suwa and not Yaguth and Yauq and Nasr (23)",
      transliteration:
        "waqālū lā tadharunna ālihatakum walā tadharunna waddan walā suwāʿan walā yaghūtha wayaʿūqa wanasran ",
      verse: 5442,
      juz: 29,
      surah: 71,
    },
    {
      number: 24,
      image: "",
      text: "And indeed they have led astray many And not increase the wrongdoers except (in) error (24)",
      transliteration:
        "waqad aḍallū kathīran walā tazidi l-ẓālimīna illā ḍalālan ",
      verse: 5443,
      juz: 29,
      surah: 71,
    },
    {
      number: 25,
      image: "",
      text: "Because of their sins they were drowned then made to enter (the) Fire and not they found for themselves from besides Allah any helpers (25)",
      transliteration:
        "mimmā khaṭīātihim ugh'riqū fa-ud'khilū nāran falam yajidū lahum min dūni l-lahi anṣāran ",
      verse: 5444,
      juz: 29,
      surah: 71,
    },
    {
      number: 26,
      image: "",
      text: "And said Nuh My Lord (Do) not leave on the earth any (of) the disbelievers (as) an inhabitant (26)",
      transliteration:
        "waqāla nūḥun rabbi lā tadhar ʿalā l-arḍi mina l-kāfirīna dayyāran ",
      verse: 5445,
      juz: 29,
      surah: 71,
    },
    {
      number: 27,
      image: "",
      text: "Indeed, You if You leave them they will mislead Your slaves and not they will beget except a wicked a disbeliever (27)",
      transliteration:
        "innaka in tadharhum yuḍillū ʿibādaka walā yalidū illā fājiran kaffāran ",
      verse: 5446,
      juz: 29,
      surah: 71,
    },
    {
      number: 28,
      image: "",
      text: "My Lord Forgive me and my parents and whoever enters my house  a believer and the believing men and the believing women And (do) not increase the wrongdoers except (in) destruction (28)",
      transliteration:
        "rabbi igh'fir lī waliwālidayya waliman dakhala baytiya mu'minan walil'mu'minīna wal-mu'mināti walā tazidi l-ẓālimīna illā tabāran ",
      verse: 5447,
      juz: 29,
      surah: 71,
    },
  ],
};
