import { Surah } from "../types/islam.js";

export const qaf: Surah = {
  name: "Qaf",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "Qaf By the Quran the Glorious (1)",
      transliteration: "qaf wal-qur'āni l-majīdi ",
      verse: 4631,
      juz: 26,
      surah: 50,
    },
    {
      number: 2,
      image: "",
      text: "Nay they wonder that has come to them a warner from them So say the disbelievers This (is) a thing amazing (2)",
      transliteration:
        "bal ʿajibū an jāahum mundhirun min'hum faqāla l-kāfirūna hādhā shayon ʿajībun ",
      verse: 4632,
      juz: 26,
      surah: 50,
    },
    {
      number: 3,
      image: "",
      text: "What! When we die and have become dust That (is) a return far (3)",
      transliteration: "a-idhā mit'nā wakunnā turāban dhālika rajʿun baʿīdun ",
      verse: 4633,
      juz: 26,
      surah: 50,
    },
    {
      number: 4,
      image: "",
      text: "Certainly We know what diminishes the earth of them and with Us (is) a Book guarded (4)",
      transliteration:
        "qad ʿalim'nā mā tanquṣu l-arḍu min'hum waʿindanā kitābun ḥafīẓun ",
      verse: 4634,
      juz: 26,
      surah: 50,
    },
    {
      number: 5,
      image: "",
      text: "Nay they denied the truth when it came (to) them so they (are) in a state confused (5)",
      transliteration:
        "bal kadhabū bil-ḥaqi lammā jāahum fahum fī amrin marījin ",
      verse: 4635,
      juz: 26,
      surah: 50,
    },
    {
      number: 6,
      image: "",
      text: "Then do not they look at the sky above them  how We structured it and adorned it and not for it any rifts (6)",
      transliteration:
        "afalam yanẓurū ilā l-samāi fawqahum kayfa banaynāhā wazayyannāhā wamā lahā min furūjin ",
      verse: 4636,
      juz: 26,
      surah: 50,
    },
    {
      number: 7,
      image: "",
      text: "And the earth We have spread it out and cast therein firmly set mountains and We made to grow therein of every kind beautiful (7)",
      transliteration:
        "wal-arḍa madadnāhā wa-alqaynā fīhā rawāsiya wa-anbatnā fīhā min kulli zawjin bahījin ",
      verse: 4637,
      juz: 26,
      surah: 50,
    },
    {
      number: 8,
      image: "",
      text: "Giving insight and a reminder for every slave who turns (8)",
      transliteration: "tabṣiratan wadhik'rā likulli ʿabdin munībin ",
      verse: 4638,
      juz: 26,
      surah: 50,
    },
    {
      number: 9,
      image: "",
      text: "And We have sent down from the sky water blessed then We made to grow thereby gardens and grain (for) the harvest (9)",
      transliteration:
        "wanazzalnā mina l-samāi māan mubārakan fa-anbatnā bihi jannātin waḥabba l-ḥaṣīdi ",
      verse: 4639,
      juz: 26,
      surah: 50,
    },
    {
      number: 10,
      image: "",
      text: "And the palms trees tall  for it (are) layers arranged (10)",
      transliteration: "wal-nakhla bāsiqātin lahā ṭalʿun naḍīdun ",
      verse: 4640,
      juz: 26,
      surah: 50,
    },
    {
      number: 11,
      image: "",
      text: "A provision for the slaves and We give life therewith (to) a land dead Thus (will be) the coming forth (11)",
      transliteration:
        "riz'qan lil'ʿibādi wa-aḥyaynā bihi baldatan maytan kadhālika l-khurūju ",
      verse: 4641,
      juz: 26,
      surah: 50,
    },
    {
      number: 12,
      image: "",
      text: "Denied before them (the) people (of) Nuh and (the) companions (of) Ar-Raas and Thamud (12)",
      transliteration:
        "kadhabat qablahum qawmu nūḥin wa-aṣḥābu l-rasi wathamūdu ",
      verse: 4642,
      juz: 26,
      surah: 50,
    },
    {
      number: 13,
      image: "",
      text: "And Aad and Firaun and (the) brothers (of) Lut (13)",
      transliteration: "waʿādun wafir'ʿawnu wa-ikh'wānu lūṭin ",
      verse: 4643,
      juz: 26,
      surah: 50,
    },
    {
      number: 14,
      image: "",
      text: "And (the) companions (of) the wood and (the) people (of) Tubba All denied the Messengers so was fulfilled My Threat (14)",
      transliteration:
        "wa-aṣḥābu l-aykati waqawmu tubbaʿin kullun kadhaba l-rusula faḥaqqa waʿīdi ",
      verse: 4644,
      juz: 26,
      surah: 50,
    },
    {
      number: 15,
      image: "",
      text: "Were We then tired with the creation the first Nay they (are) in doubt about a creation new (15)",
      transliteration:
        "afaʿayīnā bil-khalqi l-awali bal hum fī labsin min khalqin jadīdin ",
      verse: 4645,
      juz: 26,
      surah: 50,
    },
    {
      number: 16,
      image: "",
      text: "And certainly We created man and We know what whispers to him his soul and We (are) nearer to him than (his) jugular vein (his) jugular vein (16)",
      transliteration:
        "walaqad khalaqnā l-insāna wanaʿlamu mā tuwaswisu bihi nafsuhu wanaḥnu aqrabu ilayhi min ḥabli l-warīdi ",
      verse: 4646,
      juz: 26,
      surah: 50,
    },
    {
      number: 17,
      image: "",
      text: "When receive the two receivers on the right and on the left seated (17)",
      transliteration:
        "idh yatalaqqā l-mutalaqiyāni ʿani l-yamīni waʿani l-shimāli qaʿīdun ",
      verse: 4647,
      juz: 26,
      surah: 50,
    },
    {
      number: 18,
      image: "",
      text: "Not he utters any word but with him (is) an observer ready (18)",
      transliteration: "mā yalfiẓu min qawlin illā ladayhi raqībun ʿatīdun ",
      verse: 4648,
      juz: 26,
      surah: 50,
    },
    {
      number: 19,
      image: "",
      text: "And will come (the) stupor (of) death in truth That (is) what you were [from it] avoiding (19)",
      transliteration:
        "wajāat sakratu l-mawti bil-ḥaqi dhālika mā kunta min'hu taḥīdu ",
      verse: 4649,
      juz: 26,
      surah: 50,
    },
    {
      number: 20,
      image: "",
      text: "And will be blown [in] the trumpet That (is the) Day (of) the Warning (20)",
      transliteration: "wanufikha fī l-ṣūri dhālika yawmu l-waʿīdi ",
      verse: 4650,
      juz: 26,
      surah: 50,
    },
    {
      number: 21,
      image: "",
      text: "And will come every soul with it a driver and a witness (21)",
      transliteration: "wajāat kullu nafsin maʿahā sāiqun washahīdun ",
      verse: 4651,
      juz: 26,
      surah: 50,
    },
    {
      number: 22,
      image: "",
      text: "Certainly you were in heedlessness of this So We have removed from you your cover so your sight today (is) sharp (22)",
      transliteration:
        "laqad kunta fī ghaflatin min hādhā fakashafnā ʿanka ghiṭāaka fabaṣaruka l-yawma ḥadīdun ",
      verse: 4652,
      juz: 26,
      surah: 50,
    },
    {
      number: 23,
      image: "",
      text: "And (will) say his companion This (is) what (is) with me ready (23)",
      transliteration: "waqāla qarīnuhu hādhā mā ladayya ʿatīdun ",
      verse: 4653,
      juz: 26,
      surah: 50,
    },
    {
      number: 24,
      image: "",
      text: "Throw in (to) Hell every disbeliever stubborn (24)",
      transliteration: "alqiyā fī jahannama kulla kaffārin ʿanīdin ",
      verse: 4654,
      juz: 26,
      surah: 50,
    },
    {
      number: 25,
      image: "",
      text: "Forbidder of good transgressor doubter (25)",
      transliteration: "mannāʿin lil'khayri muʿ'tadin murībin ",
      verse: 4655,
      juz: 26,
      surah: 50,
    },
    {
      number: 26,
      image: "",
      text: "Who made with Allah a god another so throw him in(to) the punishment the severe (26)",
      transliteration:
        "alladhī jaʿala maʿa l-lahi ilāhan ākhara fa-alqiyāhu fī l-ʿadhābi l-shadīdi ",
      verse: 4656,
      juz: 26,
      surah: 50,
    },
    {
      number: 27,
      image: "",
      text: "Will say his companion Our Lord not I made him transgress but he was in error far (27)",
      transliteration:
        "qāla qarīnuhu rabbanā mā aṭghaytuhu walākin kāna fī ḍalālin baʿīdin ",
      verse: 4657,
      juz: 26,
      surah: 50,
    },
    {
      number: 28,
      image: "",
      text: "He will say (Do) not dispute (in) My presence and indeed I sent forth to you the Warning (28)",
      transliteration:
        "qāla lā takhtaṣimū ladayya waqad qaddamtu ilaykum bil-waʿīdi ",
      verse: 4658,
      juz: 26,
      surah: 50,
    },
    {
      number: 29,
      image: "",
      text: "Not will be changed the word with Me and not I Am unjust to My slaves (29)",
      transliteration:
        "mā yubaddalu l-qawlu ladayya wamā anā biẓallāmin lil'ʿabīdi ",
      verse: 4659,
      juz: 26,
      surah: 50,
    },
    {
      number: 30,
      image: "",
      text: "(The) Day We will say to Hell Are you filled And it will say Are (there) any more (30)",
      transliteration:
        "yawma naqūlu lijahannama hali im'talati wataqūlu hal min mazīdin ",
      verse: 4660,
      juz: 26,
      surah: 50,
    },
    {
      number: 31,
      image: "",
      text: "And will be brought near the Paradise to the righteous not far (31)",
      transliteration: "wa-uz'lifati l-janatu lil'muttaqīna ghayra baʿīdin ",
      verse: 4661,
      juz: 26,
      surah: 50,
    },
    {
      number: 32,
      image: "",
      text: "This (is) what you were promised for everyone who turns (and) who keeps (32)",
      transliteration: "hādhā mā tūʿadūna likulli awwābin ḥafīẓin ",
      verse: 4662,
      juz: 26,
      surah: 50,
    },
    {
      number: 33,
      image: "",
      text: "Who feared the Most Gracious in the unseen and came with a heart returning (33)",
      transliteration:
        "man khashiya l-raḥmāna bil-ghaybi wajāa biqalbin munībin ",
      verse: 4663,
      juz: 26,
      surah: 50,
    },
    {
      number: 34,
      image: "",
      text: "Enter it in peace That (is) a Day (of) Eternity (34)",
      transliteration: "ud'khulūhā bisalāmin dhālika yawmu l-khulūdi ",
      verse: 4664,
      juz: 26,
      surah: 50,
    },
    {
      number: 35,
      image: "",
      text: "For them whatever they wish therein and with Us (is) more (35)",
      transliteration: "lahum mā yashāūna fīhā waladaynā mazīdun ",
      verse: 4665,
      juz: 26,
      surah: 50,
    },
    {
      number: 36,
      image: "",
      text: "And how many We destroyed before them of a generation they (were) stronger than them (in) power so they explored throughout the lands Is (there) any place of escape (36)",
      transliteration:
        "wakam ahlaknā qablahum min qarnin hum ashaddu min'hum baṭshan fanaqqabū fī l-bilādi hal min maḥīṣin ",
      verse: 4666,
      juz: 26,
      surah: 50,
    },
    {
      number: 37,
      image: "",
      text: "Indeed in that surely, is a reminder for (one) who is  for him a heart or (who) gives ear (who) gives ear while he (is) a witness (37)",
      transliteration:
        "inna fī dhālika ladhik'rā liman kāna lahu qalbun aw alqā l-samʿa wahuwa shahīdun ",
      verse: 4667,
      juz: 26,
      surah: 50,
    },
    {
      number: 38,
      image: "",
      text: "And certainly We created the heavens and the earth and whatever (is) between both of them in six periods and (did) not touch Us any fatigue (38)",
      transliteration:
        "walaqad khalaqnā l-samāwāti wal-arḍa wamā baynahumā fī sittati ayyāmin wamā massanā min lughūbin ",
      verse: 4668,
      juz: 26,
      surah: 50,
    },
    {
      number: 39,
      image: "",
      text: "So be patient over what they say and glorify (the) praise (of) your Lord before (the) rising (of) the sun and before the setting (39)",
      transliteration:
        "fa-iṣ'bir ʿalā mā yaqūlūna wasabbiḥ biḥamdi rabbika qabla ṭulūʿi l-shamsi waqabla l-ghurūbi ",
      verse: 4669,
      juz: 26,
      surah: 50,
    },
    {
      number: 40,
      image: "",
      text: "And of the night glorify Him and after the prostration (40)",
      transliteration: "wamina al-layli fasabbiḥ'hu wa-adbāra l-sujūdi ",
      verse: 4670,
      juz: 26,
      surah: 50,
    },
    {
      number: 41,
      image: "",
      text: "And listen (The) Day will call the caller from a place near (41)",
      transliteration: "wa-is'tamiʿ yawma yunādi l-munādi min makānin qarībin ",
      verse: 4671,
      juz: 26,
      surah: 50,
    },
    {
      number: 42,
      image: "",
      text: "(The) Day they will hear the Blast in truth That (is the) Day (of) coming forth (42)",
      transliteration:
        "yawma yasmaʿūna l-ṣayḥata bil-ḥaqi dhālika yawmu l-khurūji ",
      verse: 4672,
      juz: 26,
      surah: 50,
    },
    {
      number: 43,
      image: "",
      text: "Indeed, We [We] [We] give life and [We] cause death and to Us (is) the final return (43)",
      transliteration: "innā naḥnu nuḥ'yī wanumītu wa-ilaynā l-maṣīru ",
      verse: 4673,
      juz: 26,
      surah: 50,
    },
    {
      number: 44,
      image: "",
      text: "(The) Day will split the earth from them hurrying That (is) a gathering for Us easy (44)",
      transliteration:
        "yawma tashaqqaqu l-arḍu ʿanhum sirāʿan dhālika ḥashrun ʿalaynā yasīrun ",
      verse: 4674,
      juz: 26,
      surah: 50,
    },
    {
      number: 45,
      image: "",
      text: "We know best [of] what they say and not (are) you over them the one to compel But remind with the Quran whoever fears My threat (45)",
      transliteration:
        "naḥnu aʿlamu bimā yaqūlūna wamā anta ʿalayhim bijabbārin fadhakkir bil-qur'āni man yakhāfu waʿīdi ",
      verse: 4675,
      juz: 26,
      surah: 50,
    },
  ],
};
