import { Surah } from "../types/islam.js";

export const qalam: Surah = {
  name: "Al-Qalam",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "Nun By the pen and what they write (1)",
      transliteration: "noon wal-qalami wamā yasṭurūna ",
      verse: 5272,
      juz: 29,
      surah: 68,
    },
    {
      number: 2,
      image: "",
      text: "Not you (are) by (the) Grace (of) your Lord a madman (2)",
      transliteration: "mā anta biniʿ'mati rabbika bimajnūnin ",
      verse: 5273,
      juz: 29,
      surah: 68,
    },
    {
      number: 3,
      image: "",
      text: "And indeed for you surely (is) a reward without end (3)",
      transliteration: "wa-inna laka la-ajran ghayra mamnūnin ",
      verse: 5274,
      juz: 29,
      surah: 68,
    },
    {
      number: 4,
      image: "",
      text: "And indeed, you surely (are) (of) a moral character great (4)",
      transliteration: "wa-innaka laʿalā khuluqin ʿaẓīmin ",
      verse: 5275,
      juz: 29,
      surah: 68,
    },
    {
      number: 5,
      image: "",
      text: "So you will see and they will see (5)",
      transliteration: "fasatub'ṣiru wayub'ṣirūna ",
      verse: 5276,
      juz: 29,
      surah: 68,
    },
    {
      number: 6,
      image: "",
      text: "Which of you (is) the afflicted one (6)",
      transliteration: "bi-ayyikumu l-maftūnu ",
      verse: 5277,
      juz: 29,
      surah: 68,
    },
    {
      number: 7,
      image: "",
      text: "Indeed your Lord He (is) most knowing of (he) who has strayed from His way and He (is) most knowing of the guided ones (7)",
      transliteration:
        "inna rabbaka huwa aʿlamu biman ḍalla ʿan sabīlihi wahuwa aʿlamu bil-muh'tadīna ",
      verse: 5278,
      juz: 29,
      surah: 68,
    },
    {
      number: 8,
      image: "",
      text: "So (do) not obey the deniers (8)",
      transliteration: "falā tuṭiʿi l-mukadhibīna ",
      verse: 5279,
      juz: 29,
      surah: 68,
    },
    {
      number: 9,
      image: "",
      text: "They wish that you should compromise so they would compromise (9)",
      transliteration: "waddū law tud'hinu fayud'hinūna ",
      verse: 5280,
      juz: 29,
      surah: 68,
    },
    {
      number: 10,
      image: "",
      text: "And (do) not obey every habitual swearer worthless (10)",
      transliteration: "walā tuṭiʿ kulla ḥallāfin mahīnin ",
      verse: 5281,
      juz: 29,
      surah: 68,
    },
    {
      number: 11,
      image: "",
      text: "Defamer going about with malicious gossip (11)",
      transliteration: "hammāzin mashāin binamīmin ",
      verse: 5282,
      juz: 29,
      surah: 68,
    },
    {
      number: 12,
      image: "",
      text: "A preventer of (the) good transgressor sinful (12)",
      transliteration: "mannāʿin lil'khayri muʿ'tadin athīmin ",
      verse: 5283,
      juz: 29,
      surah: 68,
    },
    {
      number: 13,
      image: "",
      text: "Cruel after (all) that utterly useless (13)",
      transliteration: "ʿutullin baʿda dhālika zanīmin ",
      verse: 5284,
      juz: 29,
      surah: 68,
    },
    {
      number: 14,
      image: "",
      text: "Because (he) is a possessor (of) wealth and children (14)",
      transliteration: "an kāna dhā mālin wabanīna ",
      verse: 5285,
      juz: 29,
      surah: 68,
    },
    {
      number: 15,
      image: "",
      text: "When are recited to him Our Verses he says Stories (of) the former (people) (15)",
      transliteration: "idhā tut'lā ʿalayhi āyātunā qāla asāṭīru l-awalīna ",
      verse: 5286,
      juz: 29,
      surah: 68,
    },
    {
      number: 16,
      image: "",
      text: "We will brand him on the snout (16)",
      transliteration: "sanasimuhu ʿalā l-khur'ṭūmi ",
      verse: 5287,
      juz: 29,
      surah: 68,
    },
    {
      number: 17,
      image: "",
      text: "Indeed, We have tried them as We tried (the) companions (of) the garden when they swore to pluck its fruit (in the) morning (17)",
      transliteration:
        "innā balawnāhum kamā balawnā aṣḥāba l-janati idh aqsamū layaṣrimunnahā muṣ'biḥīna ",
      verse: 5288,
      juz: 29,
      surah: 68,
    },
    {
      number: 18,
      image: "",
      text: "And not making exception (18)",
      transliteration: "walā yastathnūna ",
      verse: 5289,
      juz: 29,
      surah: 68,
    },
    {
      number: 19,
      image: "",
      text: "So there came upon it a visitation from your Lord while they were asleep (19)",
      transliteration: "faṭāfa ʿalayhā ṭāifun min rabbika wahum nāimūna ",
      verse: 5290,
      juz: 29,
      surah: 68,
    },
    {
      number: 20,
      image: "",
      text: "So it became as if reaped (20)",
      transliteration: "fa-aṣbaḥat kal-ṣarīmi ",
      verse: 5291,
      juz: 29,
      surah: 68,
    },
    {
      number: 21,
      image: "",
      text: "And they called one another (at) morning (21)",
      transliteration: "fatanādaw muṣ'biḥīna ",
      verse: 5292,
      juz: 29,
      surah: 68,
    },
    {
      number: 22,
      image: "",
      text: "That Go early to your crop if you would pluck (the) fruit (22)",
      transliteration: "ani igh'dū ʿalā ḥarthikum in kuntum ṣārimīna ",
      verse: 5293,
      juz: 29,
      surah: 68,
    },
    {
      number: 23,
      image: "",
      text: "So they went while they lowered (their) voices (23)",
      transliteration: "fa-inṭalaqū wahum yatakhāfatūna ",
      verse: 5294,
      juz: 29,
      surah: 68,
    },
    {
      number: 24,
      image: "",
      text: "That Not will enter it today upon you any poor person (24)",
      transliteration: "an lā yadkhulannahā l-yawma ʿalaykum mis'kīnun ",
      verse: 5295,
      juz: 29,
      surah: 68,
    },
    {
      number: 25,
      image: "",
      text: "And they went early with determination able (25)",
      transliteration: "waghadaw ʿalā ḥardin qādirīna ",
      verse: 5296,
      juz: 29,
      surah: 68,
    },
    {
      number: 26,
      image: "",
      text: "But when they saw it they said Indeed, we (are) surely lost (26)",
      transliteration: "falammā ra-awhā qālū innā laḍāllūna ",
      verse: 5297,
      juz: 29,
      surah: 68,
    },
    {
      number: 27,
      image: "",
      text: "Nay We (are) deprived (27)",
      transliteration: "bal naḥnu maḥrūmūna ",
      verse: 5298,
      juz: 29,
      surah: 68,
    },
    {
      number: 28,
      image: "",
      text: "Said (the) most moderate of them Did not I tell you 'Why not you glorify (Allah)?' (28)",
      transliteration: "qāla awsaṭuhum alam aqul lakum lawlā tusabbiḥūna ",
      verse: 5299,
      juz: 29,
      surah: 68,
    },
    {
      number: 29,
      image: "",
      text: "They said Glory be (to) our Lord Indeed, we [we] were wrongdoers (29)",
      transliteration: "qālū sub'ḥāna rabbinā innā kunnā ẓālimīna ",
      verse: 5300,
      juz: 29,
      surah: 68,
    },
    {
      number: 30,
      image: "",
      text: "Then approached some of them to others blaming each other (30)",
      transliteration: "fa-aqbala baʿḍuhum ʿalā baʿḍin yatalāwamūna ",
      verse: 5301,
      juz: 29,
      surah: 68,
    },
    {
      number: 31,
      image: "",
      text: "They said O woe to us Indeed, we [we] were transgressors (31)",
      transliteration: "qālū yāwaylanā innā kunnā ṭāghīna ",
      verse: 5302,
      juz: 29,
      surah: 68,
    },
    {
      number: 32,
      image: "",
      text: "Perhaps our Lord [that] will substitute for us a better than it Indeed, we to our Lord turn devoutly (32)",
      transliteration:
        "ʿasā rabbunā an yub'dilanā khayran min'hā innā ilā rabbinā rāghibūna ",
      verse: 5303,
      juz: 29,
      surah: 68,
    },
    {
      number: 33,
      image: "",
      text: "Such (is) the punishment And surely the punishment (of) the Hereafter (is) greater if they know (33)",
      transliteration:
        "kadhālika l-ʿadhābu walaʿadhābu l-ākhirati akbaru law kānū yaʿlamūna ",
      verse: 5304,
      juz: 29,
      surah: 68,
    },
    {
      number: 34,
      image: "",
      text: "Indeed for the righteous with their Lord (are) Gardens (of) Delight (34)",
      transliteration: "inna lil'muttaqīna ʿinda rabbihim jannāti l-naʿīmi ",
      verse: 5305,
      juz: 29,
      surah: 68,
    },
    {
      number: 35,
      image: "",
      text: "Then will We treat the Muslims like the criminals (35)",
      transliteration: "afanajʿalu l-mus'limīna kal-muj'rimīna ",
      verse: 5306,
      juz: 29,
      surah: 68,
    },
    {
      number: 36,
      image: "",
      text: "What (is) for you How (do) you judge (36)",
      transliteration: "mā lakum kayfa taḥkumūna ",
      verse: 5307,
      juz: 29,
      surah: 68,
    },
    {
      number: 37,
      image: "",
      text: "Or (is) for you a book wherein you learn (37)",
      transliteration: "am lakum kitābun fīhi tadrusūna ",
      verse: 5308,
      juz: 29,
      surah: 68,
    },
    {
      number: 38,
      image: "",
      text: "Indeed for you in it what you choose (38)",
      transliteration: "inna lakum fīhi lamā takhayyarūna ",
      verse: 5309,
      juz: 29,
      surah: 68,
    },
    {
      number: 39,
      image: "",
      text: "Or for you oaths from us reaching to (the) Day (of) the Resurrection indeed for you (is) what you judge (39)",
      transliteration:
        "am lakum aymānun ʿalaynā bālighatun ilā yawmi l-qiyāmati inna lakum lamā taḥkumūna ",
      verse: 5310,
      juz: 29,
      surah: 68,
    },
    {
      number: 40,
      image: "",
      text: "Ask them which of them for that (is) responsible (40)",
      transliteration: "salhum ayyuhum bidhālika zaʿīmun ",
      verse: 5311,
      juz: 29,
      surah: 68,
    },
    {
      number: 41,
      image: "",
      text: "Or (are) for them partners Then let them bring their partners if they are truthful (41)",
      transliteration:
        "am lahum shurakāu falyatū bishurakāihim in kānū ṣādiqīna ",
      verse: 5312,
      juz: 29,
      surah: 68,
    },
    {
      number: 42,
      image: "",
      text: "(The) Day will be uncovered from the shin and they will be called to prostrate but not they will be able (42)",
      transliteration:
        "yawma yuk'shafu ʿan sāqin wayud'ʿawna ilā l-sujūdi falā yastaṭīʿūna ",
      verse: 5313,
      juz: 29,
      surah: 68,
    },
    {
      number: 43,
      image: "",
      text: "Humbled their eyes will cover them humiliation And indeed they were called to prostrate while they (were) sound (43)",
      transliteration:
        "khāshiʿatan abṣāruhum tarhaquhum dhillatun waqad kānū yud'ʿawna ilā l-sujūdi wahum sālimūna ",
      verse: 5314,
      juz: 29,
      surah: 68,
    },
    {
      number: 44,
      image: "",
      text: "So leave Me and whoever denies this Statement We will progressively lead them from where not they know (44)",
      transliteration:
        "fadharnī waman yukadhibu bihādhā l-ḥadīthi sanastadrijuhum min ḥaythu lā yaʿlamūna ",
      verse: 5315,
      juz: 29,
      surah: 68,
    },
    {
      number: 45,
      image: "",
      text: "And I will give respite to them Indeed My plan (is) firm (45)",
      transliteration: "wa-um'lī lahum inna kaydī matīnun ",
      verse: 5316,
      juz: 29,
      surah: 68,
    },
    {
      number: 46,
      image: "",
      text: "Or you ask them a payment so they from (the) debt (are) burdened (46)",
      transliteration: "am tasaluhum ajran fahum min maghramin muth'qalūna ",
      verse: 5317,
      juz: 29,
      surah: 68,
    },
    {
      number: 47,
      image: "",
      text: "Or (is) with them the unseen so they write it (47)",
      transliteration: "am ʿindahumu l-ghaybu fahum yaktubūna ",
      verse: 5318,
      juz: 29,
      surah: 68,
    },
    {
      number: 48,
      image: "",
      text: "So be patient for (the) decision (of) your Lord and (do) not be like (the) companion (of) the fish when he called out while he (was) distressed (48)",
      transliteration:
        "fa-iṣ'bir liḥuk'mi rabbika walā takun kaṣāḥibi l-ḥūti idh nādā wahuwa makẓūmun ",
      verse: 5319,
      juz: 29,
      surah: 68,
    },
    {
      number: 49,
      image: "",
      text: "If not that overtook him a Favor from his Lord surely he would have been thrown onto (the) naked shore while he (was) blamed (49)",
      transliteration:
        "lawlā an tadārakahu niʿ'matun min rabbihi lanubidha bil-ʿarāi wahuwa madhmūmun ",
      verse: 5320,
      juz: 29,
      surah: 68,
    },
    {
      number: 50,
      image: "",
      text: "But chose him his Lord and made him of the righteous (50)",
      transliteration: "fa-ij'tabāhu rabbuhu fajaʿalahu mina l-ṣāliḥīna ",
      verse: 5321,
      juz: 29,
      surah: 68,
    },
    {
      number: 51,
      image: "",
      text: "And indeed would almost those who disbelieve surely make you slip with their look when they hear the Message and they say Indeed, he (is) surely mad (51)",
      transliteration:
        "wa-in yakādu alladhīna kafarū layuz'liqūnaka bi-abṣārihim lammā samiʿū l-dhik'ra wayaqūlūna innahu lamajnūnun ",
      verse: 5322,
      juz: 29,
      surah: 68,
    },
    {
      number: 52,
      image: "",
      text: "And not it (is) but a Reminder to the worlds (52)",
      transliteration: "wamā huwa illā dhik'run lil'ʿālamīna ",
      verse: 5323,
      juz: 29,
      surah: 68,
    },
  ],
};
