import { Surah } from "../types/islam.js";

export const qamar: Surah = {
  name: "Al-Qamar",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "Has come near the Hour and has split the moon (1)",
      transliteration: "iq'tarabati l-sāʿatu wa-inshaqqa l-qamaru ",
      verse: 4847,
      juz: 27,
      surah: 54,
    },
    {
      number: 2,
      image: "",
      text: "And if they see a Sign they turn away and say Magic continuing (2)",
      transliteration:
        "wa-in yaraw āyatan yuʿ'riḍū wayaqūlū siḥ'run mus'tamirrun ",
      verse: 4848,
      juz: 27,
      surah: 54,
    },
    {
      number: 3,
      image: "",
      text: "And they denied and followed their desires but (for) every matter (will be a) settlement (3)",
      transliteration:
        "wakadhabū wa-ittabaʿū ahwāahum wakullu amrin mus'taqirrun ",
      verse: 4849,
      juz: 27,
      surah: 54,
    },
    {
      number: 4,
      image: "",
      text: "And certainly has come to them of the information wherein wherein (is) deterrence (4)",
      transliteration: "walaqad jāahum mina l-anbāi mā fīhi muz'dajarun ",
      verse: 4850,
      juz: 27,
      surah: 54,
    },
    {
      number: 5,
      image: "",
      text: "Wisdom perfect but not will avail the warnings (5)",
      transliteration: "ḥik'matun bālighatun famā tugh'ni l-nudhuru ",
      verse: 4851,
      juz: 27,
      surah: 54,
    },
    {
      number: 6,
      image: "",
      text: "So turn away from them (The) Day will call the caller to a thing terrible (6)",
      transliteration: "fatawalla ʿanhum yawma yadʿu l-dāʿi ilā shayin nukurin ",
      verse: 4852,
      juz: 27,
      surah: 54,
    },
    {
      number: 7,
      image: "",
      text: "(Will be) humbled their eyes they will come forth from the graves as if they (were) locusts spreading (7)",
      transliteration:
        "khushaʿan abṣāruhum yakhrujūna mina l-ajdāthi ka-annahum jarādun muntashirun ",
      verse: 4853,
      juz: 27,
      surah: 54,
    },
    {
      number: 8,
      image: "",
      text: "Racing ahead towards the caller Will say the disbelievers This (is) a Day difficult (8)",
      transliteration:
        "muh'ṭiʿīna ilā l-dāʿi yaqūlu l-kāfirūna hādhā yawmun ʿasirun ",
      verse: 4854,
      juz: 27,
      surah: 54,
    },
    {
      number: 9,
      image: "",
      text: "Denied before them (the) people (of) Nuh and they denied Our slave and said A madman and he was repelled (9)",
      transliteration:
        "kadhabat qablahum qawmu nūḥin fakadhabū ʿabdanā waqālū majnūnun wa-uz'dujira ",
      verse: 4855,
      juz: 27,
      surah: 54,
    },
    {
      number: 10,
      image: "",
      text: "So he called his Lord I am one overpowered so help (10)",
      transliteration: "fadaʿā rabbahu annī maghlūbun fa-intaṣir ",
      verse: 4856,
      juz: 27,
      surah: 54,
    },
    {
      number: 11,
      image: "",
      text: "So We opened (the) gates (of) heaven with water pouring down (11)",
      transliteration: "fafataḥnā abwāba l-samāi bimāin mun'hamirin ",
      verse: 4857,
      juz: 27,
      surah: 54,
    },
    {
      number: 12,
      image: "",
      text: "And We caused to burst the earth (with) springs so met the water(s) for a matter already predestined (12)",
      transliteration:
        "wafajjarnā l-arḍa ʿuyūnan fal-taqā l-māu ʿalā amrin qad qudira ",
      verse: 4858,
      juz: 27,
      surah: 54,
    },
    {
      number: 13,
      image: "",
      text: "And We carried him on (ark) made of planks (ark) made of planks and nails (13)",
      transliteration: "waḥamalnāhu ʿalā dhāti alwāḥin wadusurin ",
      verse: 4859,
      juz: 27,
      surah: 54,
    },
    {
      number: 14,
      image: "",
      text: "Sailing before Our eyes a reward for (he) who was denied (14)",
      transliteration: "tajrī bi-aʿyuninā jazāan liman kāna kufira ",
      verse: 4860,
      juz: 27,
      surah: 54,
    },
    {
      number: 15,
      image: "",
      text: "And certainly We left it (as) a Sign so is (there) any who will receive admonition (15)",
      transliteration: "walaqad taraknāhā āyatan fahal min muddakirin ",
      verse: 4861,
      juz: 27,
      surah: 54,
    },
    {
      number: 16,
      image: "",
      text: "So how was My punishment and My warnings (16)",
      transliteration: "fakayfa kāna ʿadhābī wanudhuri ",
      verse: 4862,
      juz: 27,
      surah: 54,
    },
    {
      number: 17,
      image: "",
      text: "And certainly We have made easy the Quran for remembrance so is (there) any who will receive admonition (17)",
      transliteration:
        "walaqad yassarnā l-qur'āna lildhik'ri fahal min muddakirin ",
      verse: 4863,
      juz: 27,
      surah: 54,
    },
    {
      number: 18,
      image: "",
      text: "Denied Aad so how was My punishment and My warnings (18)",
      transliteration: "kadhabat ʿādun fakayfa kāna ʿadhābī wanudhuri ",
      verse: 4864,
      juz: 27,
      surah: 54,
    },
    {
      number: 19,
      image: "",
      text: "Indeed, We [We] sent upon them a wind furious on a day (of) misfortune continuous (19)",
      transliteration:
        "innā arsalnā ʿalayhim rīḥan ṣarṣaran fī yawmi naḥsin mus'tamirrin ",
      verse: 4865,
      juz: 27,
      surah: 54,
    },
    {
      number: 20,
      image: "",
      text: "Plucking out men as if they (were) trunks (of) date-palms uprooted (20)",
      transliteration: "tanziʿu l-nāsa ka-annahum aʿjāzu nakhlin munqaʿirin ",
      verse: 4866,
      juz: 27,
      surah: 54,
    },
    {
      number: 21,
      image: "",
      text: "So how was My punishment and My warnings (21)",
      transliteration: "fakayfa kāna ʿadhābī wanudhuri ",
      verse: 4867,
      juz: 27,
      surah: 54,
    },
    {
      number: 22,
      image: "",
      text: "And certainly We have made easy the Quran for remembrance so is (there) any who will receive admonition (22)",
      transliteration:
        "walaqad yassarnā l-qur'āna lildhik'ri fahal min muddakirin ",
      verse: 4868,
      juz: 27,
      surah: 54,
    },
    {
      number: 23,
      image: "",
      text: "Denied Thamud the warnings (23)",
      transliteration: "kadhabat thamūdu bil-nudhuri ",
      verse: 4869,
      juz: 27,
      surah: 54,
    },
    {
      number: 24,
      image: "",
      text: "And said Is (it) a human being among us one (that) we should follow him Indeed, we then (will be) surely in error and madness (24)",
      transliteration:
        "faqālū abasharan minnā wāḥidan nattabiʿuhu innā idhan lafī ḍalālin wasuʿurin ",
      verse: 4870,
      juz: 27,
      surah: 54,
    },
    {
      number: 25,
      image: "",
      text: "Has been sent the Reminder to him from among us Nay he (is) a liar insolent (25)",
      transliteration:
        "a-ul'qiya l-dhik'ru ʿalayhi min bayninā bal huwa kadhābun ashirun ",
      verse: 4871,
      juz: 27,
      surah: 54,
    },
    {
      number: 26,
      image: "",
      text: "They will know tomorrow who (is) the liar the insolent one (26)",
      transliteration: "sayaʿlamūna ghadan mani l-kadhābu l-ashiru ",
      verse: 4872,
      juz: 27,
      surah: 54,
    },
    {
      number: 27,
      image: "",
      text: "Indeed, We (are) sending the she-camel (as) a trial for them so watch them and be patient (27)",
      transliteration:
        "innā mur'silū l-nāqati fit'natan lahum fa-ir'taqib'hum wa-iṣ'ṭabir ",
      verse: 4873,
      juz: 27,
      surah: 54,
    },
    {
      number: 28,
      image: "",
      text: "And inform them that the water (is) to be shared between them each drink attended (28)",
      transliteration:
        "wanabbi'hum anna l-māa qis'matun baynahum kullu shir'bin muḥ'taḍarun ",
      verse: 4874,
      juz: 27,
      surah: 54,
    },
    {
      number: 29,
      image: "",
      text: "But they called their companion and he took and hamstrung (29)",
      transliteration: "fanādaw ṣāḥibahum fataʿāṭā faʿaqara ",
      verse: 4875,
      juz: 27,
      surah: 54,
    },
    {
      number: 30,
      image: "",
      text: "So how was My punishment and My warnings (30)",
      transliteration: "fakayfa kāna ʿadhābī wanudhuri ",
      verse: 4876,
      juz: 27,
      surah: 54,
    },
    {
      number: 31,
      image: "",
      text: "Indeed, We [We] sent upon them thunderous blast single and they became like dry twig fragments (used by) a fence builder (31)",
      transliteration:
        "innā arsalnā ʿalayhim ṣayḥatan wāḥidatan fakānū kahashīmi l-muḥ'taẓiri ",
      verse: 4877,
      juz: 27,
      surah: 54,
    },
    {
      number: 32,
      image: "",
      text: "And certainly We have made easy the Quran for remembrance so is (there) any who will receive admonition (32)",
      transliteration:
        "walaqad yassarnā l-qur'āna lildhik'ri fahal min muddakirin ",
      verse: 4878,
      juz: 27,
      surah: 54,
    },
    {
      number: 33,
      image: "",
      text: "Denied (the) people (of) Lut the warnings (33)",
      transliteration: "kadhabat qawmu lūṭin bil-nudhuri ",
      verse: 4879,
      juz: 27,
      surah: 54,
    },
    {
      number: 34,
      image: "",
      text: "Indeed, We [We] sent upon them a storm of stones except (the) family (of) Lut We saved them by dawn (34)",
      transliteration:
        "innā arsalnā ʿalayhim ḥāṣiban illā āla lūṭin najjaynāhum bisaḥarin ",
      verse: 4880,
      juz: 27,
      surah: 54,
    },
    {
      number: 35,
      image: "",
      text: "(As) a favor from Us Thus We reward (one) who (is) grateful (35)",
      transliteration: "niʿ'matan min ʿindinā kadhālika najzī man shakara ",
      verse: 4881,
      juz: 27,
      surah: 54,
    },
    {
      number: 36,
      image: "",
      text: "And certainly he warned them (of) Our seizure but they disputed the warnings (36)",
      transliteration: "walaqad andharahum baṭshatanā fatamāraw bil-nudhuri ",
      verse: 4882,
      juz: 27,
      surah: 54,
    },
    {
      number: 37,
      image: "",
      text: "And certainly they demanded from him they demanded from him his guests so We blinded their eyes So taste My punishment and My warnings (37)",
      transliteration:
        "walaqad rāwadūhu ʿan ḍayfihi faṭamasnā aʿyunahum fadhūqū ʿadhābī wanudhuri ",
      verse: 4883,
      juz: 27,
      surah: 54,
    },
    {
      number: 38,
      image: "",
      text: "And certainly seized them in the morning early a punishment abiding (38)",
      transliteration: "walaqad ṣabbaḥahum buk'ratan ʿadhābun mus'taqirrun ",
      verse: 4884,
      juz: 27,
      surah: 54,
    },
    {
      number: 39,
      image: "",
      text: "So taste My punishment and My warnings (39)",
      transliteration: "fadhūqū ʿadhābī wanudhuri ",
      verse: 4885,
      juz: 27,
      surah: 54,
    },
    {
      number: 40,
      image: "",
      text: "And certainly We have made easy the Quran for remembrance so is (there) any who will receive admonition (40)",
      transliteration:
        "walaqad yassarnā l-qur'āna lildhik'ri fahal min muddakirin ",
      verse: 4886,
      juz: 27,
      surah: 54,
    },
    {
      number: 41,
      image: "",
      text: "And certainly came (to the) people (of) Firaun warnings (41)",
      transliteration: "walaqad jāa āla fir'ʿawna l-nudhuru ",
      verse: 4887,
      juz: 27,
      surah: 54,
    },
    {
      number: 42,
      image: "",
      text: "They denied Our Signs all of them so We seized them (with) a seizure (of) All-Mighty (the) Powerful One (42)",
      transliteration:
        "kadhabū biāyātinā kullihā fa-akhadhnāhum akhdha ʿazīzin muq'tadirin ",
      verse: 4888,
      juz: 27,
      surah: 54,
    },
    {
      number: 43,
      image: "",
      text: "Are your disbelievers better than those or for you (is) an exemption in the Scriptures (43)",
      transliteration:
        "akuffārukum khayrun min ulāikum am lakum barāatun fī l-zuburi ",
      verse: 4889,
      juz: 27,
      surah: 54,
    },
    {
      number: 44,
      image: "",
      text: "Or (do) they say We (are) an assembly helping (each other) (44)",
      transliteration: "am yaqūlūna naḥnu jamīʿun muntaṣirun ",
      verse: 4890,
      juz: 27,
      surah: 54,
    },
    {
      number: 45,
      image: "",
      text: "Soon will be defeated (their) assembly and they will turn (their) backs (45)",
      transliteration: "sayuh'zamu l-jamʿu wayuwallūna l-dubura ",
      verse: 4891,
      juz: 27,
      surah: 54,
    },
    {
      number: 46,
      image: "",
      text: "Nay the Hour (is) their promised time and the Hour (will be) more grievous and more bitter (46)",
      transliteration: "bali l-sāʿatu mawʿiduhum wal-sāʿatu adhā wa-amarru ",
      verse: 4892,
      juz: 27,
      surah: 54,
    },
    {
      number: 47,
      image: "",
      text: "Indeed the criminals (are) in an error and madness (47)",
      transliteration: "inna l-muj'rimīna fī ḍalālin wasuʿurin ",
      verse: 4893,
      juz: 27,
      surah: 54,
    },
    {
      number: 48,
      image: "",
      text: "(The) Day they will be dragged into the Fire on their faces Taste (the) touch (of) Hell (48)",
      transliteration:
        "yawma yus'ḥabūna fī l-nāri ʿalā wujūhihim dhūqū massa saqara ",
      verse: 4894,
      juz: 27,
      surah: 54,
    },
    {
      number: 49,
      image: "",
      text: "Indeed, [We] every thing We created it by a measure (49)",
      transliteration: "innā kulla shayin khalaqnāhu biqadarin ",
      verse: 4895,
      juz: 27,
      surah: 54,
    },
    {
      number: 50,
      image: "",
      text: "And not (is) Our Command but one like the twinkling (of) the eye (50)",
      transliteration: "wamā amrunā illā wāḥidatun kalamḥin bil-baṣari ",
      verse: 4896,
      juz: 27,
      surah: 54,
    },
    {
      number: 51,
      image: "",
      text: "And certainly We destroyed your kinds so is (there) any who will receive admonition (51)",
      transliteration: "walaqad ahlaknā ashyāʿakum fahal min muddakirin ",
      verse: 4897,
      juz: 27,
      surah: 54,
    },
    {
      number: 52,
      image: "",
      text: "And every thing they did (is) in the written records (52)",
      transliteration: "wakullu shayin faʿalūhu fī l-zuburi ",
      verse: 4898,
      juz: 27,
      surah: 54,
    },
    {
      number: 53,
      image: "",
      text: "And every small and big (is) written down (53)",
      transliteration: "wakullu ṣaghīrin wakabīrin mus'taṭarun ",
      verse: 4899,
      juz: 27,
      surah: 54,
    },
    {
      number: 54,
      image: "",
      text: "Indeed the righteous (will be) in gardens and river (54)",
      transliteration: "inna l-mutaqīna fī jannātin wanaharin ",
      verse: 4900,
      juz: 27,
      surah: 54,
    },
    {
      number: 55,
      image: "",
      text: "In a seat (of) honor near a King Most Powerful (55)",
      transliteration: "fī maqʿadi ṣid'qin ʿinda malīkin muq'tadirin ",
      verse: 4901,
      juz: 27,
      surah: 54,
    },
  ],
};
