import { Surah } from "../types/islam.js";

export const qariah: Surah = {
  name: "Al-Qari'ah",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "The Striking Calamity (1)",
      transliteration: "al-qāriʿatu ",
      verse: 6158,
      juz: 30,
      surah: 101,
    },
    {
      number: 2,
      image: "",
      text: "What (is) the Striking Calamity (2)",
      transliteration: "mā l-qāriʿatu ",
      verse: 6159,
      juz: 30,
      surah: 101,
    },
    {
      number: 3,
      image: "",
      text: "And what will make you know what (is) the Striking Calamity (3)",
      transliteration: "wamā adrāka mā l-qāriʿatu ",
      verse: 6160,
      juz: 30,
      surah: 101,
    },
    {
      number: 4,
      image: "",
      text: "(The) Day will be the mankind like moths scattered (4)",
      transliteration: "yawma yakūnu l-nāsu kal-farāshi l-mabthūthi ",
      verse: 6161,
      juz: 30,
      surah: 101,
    },
    {
      number: 5,
      image: "",
      text: "And will be the mountains like wool fluffed up (5)",
      transliteration: "watakūnu l-jibālu kal-ʿih'ni l-manfūshi ",
      verse: 6162,
      juz: 30,
      surah: 101,
    },
    {
      number: 6,
      image: "",
      text: "Then as for (him) whose (are) heavy his scales (6)",
      transliteration: "fa-ammā man thaqulat mawāzīnuhu ",
      verse: 6163,
      juz: 30,
      surah: 101,
    },
    {
      number: 7,
      image: "",
      text: "Then he (will be) in a life pleasant (7)",
      transliteration: "fahuwa fī ʿīshatin rāḍiyatin ",
      verse: 6164,
      juz: 30,
      surah: 101,
    },
    {
      number: 8,
      image: "",
      text: "But as for (him) whose (are) light his scales (8)",
      transliteration: "wa-ammā man khaffat mawāzīnuhu ",
      verse: 6165,
      juz: 30,
      surah: 101,
    },
    {
      number: 9,
      image: "",
      text: "His abode (will be the) Pit (9)",
      transliteration: "fa-ummuhu hāwiyatun ",
      verse: 6166,
      juz: 30,
      surah: 101,
    },
    {
      number: 10,
      image: "",
      text: "And what will make you know what it is (10)",
      transliteration: "wamā adrāka mā hiyah ",
      verse: 6167,
      juz: 30,
      surah: 101,
    },
    {
      number: 11,
      image: "",
      text: "A Fire intensely hot (11)",
      transliteration: "nārun ḥāmiyatun ",
      verse: 6168,
      juz: 30,
      surah: 101,
    },
  ],
};
