import { Surah } from "../types/islam.js";

export const qiyamah: Surah = {
  name: "Al-Qiyamah",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "Nay I swear by (the) Day (of) the Resurrection (1)",
      transliteration: "lā uq'simu biyawmi l-qiyāmati ",
      verse: 5552,
      juz: 29,
      surah: 75,
    },
    {
      number: 2,
      image: "",
      text: "And nay I swear by the soul self-accusing (2)",
      transliteration: "walā uq'simu bil-nafsi l-lawāmati ",
      verse: 5553,
      juz: 29,
      surah: 75,
    },
    {
      number: 3,
      image: "",
      text: "Does think [the] man that not We will assemble his bones (3)",
      transliteration: "ayaḥsabu l-insānu allan najmaʿa ʿiẓāmahu ",
      verse: 5554,
      juz: 29,
      surah: 75,
    },
    {
      number: 4,
      image: "",
      text: "Nay (We are) Able on that We can restore his fingertips (4)",
      transliteration: "balā qādirīna ʿalā an nusawwiya banānahu ",
      verse: 5555,
      juz: 29,
      surah: 75,
    },
    {
      number: 5,
      image: "",
      text: "Nay Desires [the] man to give (the) lie (to) what is before him (5)",
      transliteration: "bal yurīdu l-insānu liyafjura amāmahu ",
      verse: 5556,
      juz: 29,
      surah: 75,
    },
    {
      number: 6,
      image: "",
      text: "He asks When (is the) Day (of) the Resurrection (6)",
      transliteration: "yasalu ayyāna yawmu l-qiyāmati ",
      verse: 5557,
      juz: 29,
      surah: 75,
    },
    {
      number: 7,
      image: "",
      text: "So when is dazzled the vision (7)",
      transliteration: "fa-idhā bariqa l-baṣaru ",
      verse: 5558,
      juz: 29,
      surah: 75,
    },
    {
      number: 8,
      image: "",
      text: "And becomes dark the moon (8)",
      transliteration: "wakhasafa l-qamaru ",
      verse: 5559,
      juz: 29,
      surah: 75,
    },
    {
      number: 9,
      image: "",
      text: "And are joined the sun and the moon (9)",
      transliteration: "wajumiʿa l-shamsu wal-qamaru ",
      verse: 5560,
      juz: 29,
      surah: 75,
    },
    {
      number: 10,
      image: "",
      text: "Will say [the] man that Day Where (is) the escape (10)",
      transliteration: "yaqūlu l-insānu yawma-idhin ayna l-mafaru ",
      verse: 5561,
      juz: 29,
      surah: 75,
    },
    {
      number: 11,
      image: "",
      text: "By no means (There is) no refuge (11)",
      transliteration: "kallā lā wazara ",
      verse: 5562,
      juz: 29,
      surah: 75,
    },
    {
      number: 12,
      image: "",
      text: "To your Lord that Day (is) the place of rest (12)",
      transliteration: "ilā rabbika yawma-idhin l-mus'taqaru ",
      verse: 5563,
      juz: 29,
      surah: 75,
    },
    {
      number: 13,
      image: "",
      text: "Will be informed [the] man that Day of what he sent forth and kept back (13)",
      transliteration: "yunabba-u l-insānu yawma-idhin bimā qaddama wa-akhara ",
      verse: 5564,
      juz: 29,
      surah: 75,
    },
    {
      number: 14,
      image: "",
      text: "Nay [The] man against himself (will be) a witness (14)",
      transliteration: "bali l-insānu ʿalā nafsihi baṣīratun ",
      verse: 5565,
      juz: 29,
      surah: 75,
    },
    {
      number: 15,
      image: "",
      text: "Even if he presents his excuses (15)",
      transliteration: "walaw alqā maʿādhīrahu ",
      verse: 5566,
      juz: 29,
      surah: 75,
    },
    {
      number: 16,
      image: "",
      text: "Not move with it your tongue to hasten with it (16)",
      transliteration: "lā tuḥarrik bihi lisānaka litaʿjala bihi ",
      verse: 5567,
      juz: 29,
      surah: 75,
    },
    {
      number: 17,
      image: "",
      text: "Indeed upon Us (is) its collection and its recitation (17)",
      transliteration: "inna ʿalaynā jamʿahu waqur'ānahu ",
      verse: 5568,
      juz: 29,
      surah: 75,
    },
    {
      number: 18,
      image: "",
      text: "And when We have recited it then follow its recitation (18)",
      transliteration: "fa-idhā qaranāhu fa-ittabiʿ qur'ānahu ",
      verse: 5569,
      juz: 29,
      surah: 75,
    },
    {
      number: 19,
      image: "",
      text: "Then indeed upon Us (is) its explanation (19)",
      transliteration: "thumma inna ʿalaynā bayānahu ",
      verse: 5570,
      juz: 29,
      surah: 75,
    },
    {
      number: 20,
      image: "",
      text: "No But you love the immediate (20)",
      transliteration: "kallā bal tuḥibbūna l-ʿājilata ",
      verse: 5571,
      juz: 29,
      surah: 75,
    },
    {
      number: 21,
      image: "",
      text: "And leave the Hereafter (21)",
      transliteration: "watadharūna l-ākhirata ",
      verse: 5572,
      juz: 29,
      surah: 75,
    },
    {
      number: 22,
      image: "",
      text: "Faces that Day (will be) radiant (22)",
      transliteration: "wujūhun yawma-idhin nāḍiratun ",
      verse: 5573,
      juz: 29,
      surah: 75,
    },
    {
      number: 23,
      image: "",
      text: "Towards their Lord looking (23)",
      transliteration: "ilā rabbihā nāẓiratun ",
      verse: 5574,
      juz: 29,
      surah: 75,
    },
    {
      number: 24,
      image: "",
      text: "And faces that Day (will be) distorted (24)",
      transliteration: "wawujūhun yawma-idhin bāsiratun ",
      verse: 5575,
      juz: 29,
      surah: 75,
    },
    {
      number: 25,
      image: "",
      text: "Thinking that will be done to them backbreaking (25)",
      transliteration: "taẓunnu an yuf'ʿala bihā fāqiratun ",
      verse: 5576,
      juz: 29,
      surah: 75,
    },
    {
      number: 26,
      image: "",
      text: "No When it reaches the collar bones (26)",
      transliteration: "kallā idhā balaghati l-tarāqiya ",
      verse: 5577,
      juz: 29,
      surah: 75,
    },
    {
      number: 27,
      image: "",
      text: "And it is said Who (will) cure (27)",
      transliteration: "waqīla man rāqin ",
      verse: 5578,
      juz: 29,
      surah: 75,
    },
    {
      number: 28,
      image: "",
      text: "And he is certain that it (is) the parting (28)",
      transliteration: "waẓanna annahu l-firāqu ",
      verse: 5579,
      juz: 29,
      surah: 75,
    },
    {
      number: 29,
      image: "",
      text: "And is wound the leg about the leg (29)",
      transliteration: "wal-tafati l-sāqu bil-sāqi ",
      verse: 5580,
      juz: 29,
      surah: 75,
    },
    {
      number: 30,
      image: "",
      text: "To your Lord that Day (will be) the driving (30)",
      transliteration: "ilā rabbika yawma-idhin l-masāqu ",
      verse: 5581,
      juz: 29,
      surah: 75,
    },
    {
      number: 31,
      image: "",
      text: "And not he accepted (the) truth and not he prayed (31)",
      transliteration: "falā ṣaddaqa walā ṣallā ",
      verse: 5582,
      juz: 29,
      surah: 75,
    },
    {
      number: 32,
      image: "",
      text: "But he denied and turned away (32)",
      transliteration: "walākin kadhaba watawallā ",
      verse: 5583,
      juz: 29,
      surah: 75,
    },
    {
      number: 33,
      image: "",
      text: "Then he went to his family swaggering (33)",
      transliteration: "thumma dhahaba ilā ahlihi yatamaṭṭā ",
      verse: 5584,
      juz: 29,
      surah: 75,
    },
    {
      number: 34,
      image: "",
      text: "Woe to you and woe (34)",
      transliteration: "awlā laka fa-awlā ",
      verse: 5585,
      juz: 29,
      surah: 75,
    },
    {
      number: 35,
      image: "",
      text: "Then woe to you and woe (35)",
      transliteration: "thumma awlā laka fa-awlā ",
      verse: 5586,
      juz: 29,
      surah: 75,
    },
    {
      number: 36,
      image: "",
      text: "Does think man that he will be left neglected (36)",
      transliteration: "ayaḥsabu l-insānu an yut'raka sudan ",
      verse: 5587,
      juz: 29,
      surah: 75,
    },
    {
      number: 37,
      image: "",
      text: "Was not he a semen-drop of semen emitted (37)",
      transliteration: "alam yaku nuṭ'fatan min maniyyin yum'nā ",
      verse: 5588,
      juz: 29,
      surah: 75,
    },
    {
      number: 38,
      image: "",
      text: "Then he was a clinging substance then He created and proportioned (38)",
      transliteration: "thumma kāna ʿalaqatan fakhalaqa fasawwā ",
      verse: 5589,
      juz: 29,
      surah: 75,
    },
    {
      number: 39,
      image: "",
      text: "Then made of him two kinds (the) male and the female (39)",
      transliteration: "fajaʿala min'hu l-zawjayni l-dhakara wal-unthā ",
      verse: 5590,
      juz: 29,
      surah: 75,
    },
    {
      number: 40,
      image: "",
      text: "Is not [that] (He) Able [over] to give life (to) the dead (40)",
      transliteration: "alaysa dhālika biqādirin ʿalā an yuḥ'yiya l-mawtā ",
      verse: 5591,
      juz: 29,
      surah: 75,
    },
  ],
};
