import { Surah } from "../types/islam.js";

export const rahman: Surah = {
  name: "Ar-Rahman",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "The Most Gracious (1)",
      transliteration: "al-raḥmānu ",
      verse: 4902,
      juz: 27,
      surah: 55,
    },
    {
      number: 2,
      image: "",
      text: "He taught the Quran (2)",
      transliteration: "ʿallama l-qur'āna ",
      verse: 4903,
      juz: 27,
      surah: 55,
    },
    {
      number: 3,
      image: "",
      text: "He created [the] man (3)",
      transliteration: "khalaqa l-insāna ",
      verse: 4904,
      juz: 27,
      surah: 55,
    },
    {
      number: 4,
      image: "",
      text: "He taught him [the] speech (4)",
      transliteration: "ʿallamahu l-bayāna ",
      verse: 4905,
      juz: 27,
      surah: 55,
    },
    {
      number: 5,
      image: "",
      text: "The sun and the moon by (precise) calculation (5)",
      transliteration: "al-shamsu wal-qamaru biḥus'bānin ",
      verse: 4906,
      juz: 27,
      surah: 55,
    },
    {
      number: 6,
      image: "",
      text: "And the stars and the trees both prostrate (6)",
      transliteration: "wal-najmu wal-shajaru yasjudāni ",
      verse: 4907,
      juz: 27,
      surah: 55,
    },
    {
      number: 7,
      image: "",
      text: "And the heaven He raised it and He has set up the balance (7)",
      transliteration: "wal-samāa rafaʿahā wawaḍaʿa l-mīzāna ",
      verse: 4908,
      juz: 27,
      surah: 55,
    },
    {
      number: 8,
      image: "",
      text: "That not you may transgress in the balance (8)",
      transliteration: "allā taṭghaw fī l-mīzāni ",
      verse: 4909,
      juz: 27,
      surah: 55,
    },
    {
      number: 9,
      image: "",
      text: "And establish the weight in justice and (do) not make deficient the balance (9)",
      transliteration: "wa-aqīmū l-wazna bil-qis'ṭi walā tukh'sirū l-mīzāna ",
      verse: 4910,
      juz: 27,
      surah: 55,
    },
    {
      number: 10,
      image: "",
      text: "And the earth He laid it for the creatures (10)",
      transliteration: "wal-arḍa waḍaʿahā lil'anāmi ",
      verse: 4911,
      juz: 27,
      surah: 55,
    },
    {
      number: 11,
      image: "",
      text: "Therein (is) fruit and date-palms having sheaths (11)",
      transliteration: "fīhā fākihatun wal-nakhlu dhātu l-akmāmi ",
      verse: 4912,
      juz: 27,
      surah: 55,
    },
    {
      number: 12,
      image: "",
      text: "And the grain having husk and scented plants (12)",
      transliteration: "wal-ḥabu dhū l-ʿaṣfi wal-rayḥānu ",
      verse: 4913,
      juz: 27,
      surah: 55,
    },
    {
      number: 13,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (13)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4914,
      juz: 27,
      surah: 55,
    },
    {
      number: 14,
      image: "",
      text: "He created the man from clay like the pottery (14)",
      transliteration: "khalaqa l-insāna min ṣalṣālin kal-fakhāri ",
      verse: 4915,
      juz: 27,
      surah: 55,
    },
    {
      number: 15,
      image: "",
      text: "And He created the jinn from a smokeless flame of fire (15)",
      transliteration: "wakhalaqa l-jāna min mārijin min nārin ",
      verse: 4916,
      juz: 27,
      surah: 55,
    },
    {
      number: 16,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (16)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4917,
      juz: 27,
      surah: 55,
    },
    {
      number: 17,
      image: "",
      text: "Lord (of) the two Easts and Lord (of) the two Wests (17)",
      transliteration: "rabbu l-mashriqayni warabbu l-maghribayni ",
      verse: 4918,
      juz: 27,
      surah: 55,
    },
    {
      number: 18,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (18)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4919,
      juz: 27,
      surah: 55,
    },
    {
      number: 19,
      image: "",
      text: "He released the two seas meeting (19)",
      transliteration: "maraja l-baḥrayni yaltaqiyāni ",
      verse: 4920,
      juz: 27,
      surah: 55,
    },
    {
      number: 20,
      image: "",
      text: "Between both of them (is) a barrier not they transgress (20)",
      transliteration: "baynahumā barzakhun lā yabghiyāni ",
      verse: 4921,
      juz: 27,
      surah: 55,
    },
    {
      number: 21,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (21)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4922,
      juz: 27,
      surah: 55,
    },
    {
      number: 22,
      image: "",
      text: "Come forth from both of them the pearl and the coral (22)",
      transliteration: "yakhruju min'humā l-lu'lu-u wal-marjānu ",
      verse: 4923,
      juz: 27,
      surah: 55,
    },
    {
      number: 23,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (23)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4924,
      juz: 27,
      surah: 55,
    },
    {
      number: 24,
      image: "",
      text: "And for Him (are) the ships elevated in the sea like mountains (24)",
      transliteration: "walahu l-jawāri l-munshaātu fī l-baḥri kal-aʿlāmi ",
      verse: 4925,
      juz: 27,
      surah: 55,
    },
    {
      number: 25,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (25)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4926,
      juz: 27,
      surah: 55,
    },
    {
      number: 26,
      image: "",
      text: "Everyone who (is) on it (will) perish (26)",
      transliteration: "kullu man ʿalayhā fānin ",
      verse: 4927,
      juz: 27,
      surah: 55,
    },
    {
      number: 27,
      image: "",
      text: "But will remain (the) Face (of) your Lord (the) Owner (of) Majesty and Honor (27)",
      transliteration: "wayabqā wajhu rabbika dhū l-jalāli wal-ik'rāmi ",
      verse: 4928,
      juz: 27,
      surah: 55,
    },
    {
      number: 28,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (28)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4929,
      juz: 27,
      surah: 55,
    },
    {
      number: 29,
      image: "",
      text: "Asks Him whoever (is) in the heavens and the earth Every day He (is) in a matter (29)",
      transliteration:
        "yasaluhu man fī l-samāwāti wal-arḍi kulla yawmin huwa fī shanin ",
      verse: 4930,
      juz: 27,
      surah: 55,
    },
    {
      number: 30,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (30)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4931,
      juz: 27,
      surah: 55,
    },
    {
      number: 31,
      image: "",
      text: "Soon We will attend to you O you two classes (31)",
      transliteration: "sanafrughu lakum ayyuha l-thaqalāni ",
      verse: 4932,
      juz: 27,
      surah: 55,
    },
    {
      number: 32,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (32)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4933,
      juz: 27,
      surah: 55,
    },
    {
      number: 33,
      image: "",
      text: "O assembly (of) the jinn and the men If you are able to pass beyond [of] (the) regions (of) the heavens and the earth then pass Not you (can) pass except by authority (33)",
      transliteration:
        "yāmaʿshara l-jini wal-insi ini is'taṭaʿtum an tanfudhū min aqṭāri l-samāwāti wal-arḍi fa-unfudhū lā tanfudhūna illā bisul'ṭānin ",
      verse: 4934,
      juz: 27,
      surah: 55,
    },
    {
      number: 34,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (34)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4935,
      juz: 27,
      surah: 55,
    },
    {
      number: 35,
      image: "",
      text: "Will be sent against both of you a flame of fire and smoke and not you will (be able to) defend yourselves (35)",
      transliteration:
        "yur'salu ʿalaykumā shuwāẓun min nārin wanuḥāsun falā tantaṣirāni ",
      verse: 4936,
      juz: 27,
      surah: 55,
    },
    {
      number: 36,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (36)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4937,
      juz: 27,
      surah: 55,
    },
    {
      number: 37,
      image: "",
      text: "Then when is split the heaven and it becomes rose-colored like murky oil (37)",
      transliteration: "fa-idhā inshaqqati l-samāu fakānat wardatan kal-dihāni ",
      verse: 4938,
      juz: 27,
      surah: 55,
    },
    {
      number: 38,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (38)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4939,
      juz: 27,
      surah: 55,
    },
    {
      number: 39,
      image: "",
      text: "Then (on) that Day not will be asked about his sin any man and not any jinn (39)",
      transliteration: "fayawma-idhin lā yus'alu ʿan dhanbihi insun walā jānnun ",
      verse: 4940,
      juz: 27,
      surah: 55,
    },
    {
      number: 40,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (40)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4941,
      juz: 27,
      surah: 55,
    },
    {
      number: 41,
      image: "",
      text: "Will be known the criminals by their marks and will be seized by the forelocks and the feet (41)",
      transliteration:
        "yuʿ'rafu l-muj'rimūna bisīmāhum fayu'khadhu bil-nawāṣī wal-aqdāmi ",
      verse: 4942,
      juz: 27,
      surah: 55,
    },
    {
      number: 42,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (42)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4943,
      juz: 27,
      surah: 55,
    },
    {
      number: 43,
      image: "",
      text: "This (is) Hell which deny [of it] the criminals (43)",
      transliteration: "hādhihi jahannamu allatī yukadhibu bihā l-muj'rimūna ",
      verse: 4944,
      juz: 27,
      surah: 55,
    },
    {
      number: 44,
      image: "",
      text: "They will go around between it and between scalding water heated (44)",
      transliteration: "yaṭūfūna baynahā wabayna ḥamīmin ānin ",
      verse: 4945,
      juz: 27,
      surah: 55,
    },
    {
      number: 45,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (45)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4946,
      juz: 27,
      surah: 55,
    },
    {
      number: 46,
      image: "",
      text: "But for (him) who fears (the) standing (before) his Lord (are) two gardens (46)",
      transliteration: "waliman khāfa maqāma rabbihi jannatāni ",
      verse: 4947,
      juz: 27,
      surah: 55,
    },
    {
      number: 47,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (47)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4948,
      juz: 27,
      surah: 55,
    },
    {
      number: 48,
      image: "",
      text: "Having branches (48)",
      transliteration: "dhawātā afnānin ",
      verse: 4949,
      juz: 27,
      surah: 55,
    },
    {
      number: 49,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (49)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4950,
      juz: 27,
      surah: 55,
    },
    {
      number: 50,
      image: "",
      text: "In both of them (are) two springs flowing (50)",
      transliteration: "fīhimā ʿaynāni tajriyāni ",
      verse: 4951,
      juz: 27,
      surah: 55,
    },
    {
      number: 51,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (51)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4952,
      juz: 27,
      surah: 55,
    },
    {
      number: 52,
      image: "",
      text: "In both of them [of] (are) every fruits (in) pairs (52)",
      transliteration: "fīhimā min kulli fākihatin zawjāni ",
      verse: 4953,
      juz: 27,
      surah: 55,
    },
    {
      number: 53,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (53)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4954,
      juz: 27,
      surah: 55,
    },
    {
      number: 54,
      image: "",
      text: "Reclining on couches (whose) inner linings (are) of brocade and (the) fruit (of) both the gardens (is) near (54)",
      transliteration:
        "muttakiīna ʿalā furushin baṭāinuhā min is'tabraqin wajanā l-janatayni dānin ",
      verse: 4955,
      juz: 27,
      surah: 55,
    },
    {
      number: 55,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (55)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4956,
      juz: 27,
      surah: 55,
    },
    {
      number: 56,
      image: "",
      text: "In them (will be) companions of modest gaze (will be) companions of modest gaze not has touched them any man before them and not any jinn (56)",
      transliteration:
        "fīhinna qāṣirātu l-ṭarfi lam yaṭmith'hunna insun qablahum walā jānnun ",
      verse: 4957,
      juz: 27,
      surah: 55,
    },
    {
      number: 57,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (57)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4958,
      juz: 27,
      surah: 55,
    },
    {
      number: 58,
      image: "",
      text: "As if they were rubies and coral (58)",
      transliteration: "ka-annahunna l-yāqūtu wal-marjānu ",
      verse: 4959,
      juz: 27,
      surah: 55,
    },
    {
      number: 59,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (59)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4960,
      juz: 27,
      surah: 55,
    },
    {
      number: 60,
      image: "",
      text: "Is (the) reward for the good but good (60)",
      transliteration: "hal jazāu l-iḥ'sāni illā l-iḥ'sānu ",
      verse: 4961,
      juz: 27,
      surah: 55,
    },
    {
      number: 61,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (61)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4962,
      juz: 27,
      surah: 55,
    },
    {
      number: 62,
      image: "",
      text: "Besides these two Besides these two (are) two gardens (62)",
      transliteration: "wamin dūnihimā jannatāni ",
      verse: 4963,
      juz: 27,
      surah: 55,
    },
    {
      number: 63,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (63)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4964,
      juz: 27,
      surah: 55,
    },
    {
      number: 64,
      image: "",
      text: "Dark green (64)",
      transliteration: "mud'hāmmatāni ",
      verse: 4965,
      juz: 27,
      surah: 55,
    },
    {
      number: 65,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (65)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4966,
      juz: 27,
      surah: 55,
    },
    {
      number: 66,
      image: "",
      text: "In both of them (are) two springs gushing forth (66)",
      transliteration: "fīhimā ʿaynāni naḍḍākhatāni ",
      verse: 4967,
      juz: 27,
      surah: 55,
    },
    {
      number: 67,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (67)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4968,
      juz: 27,
      surah: 55,
    },
    {
      number: 68,
      image: "",
      text: "In both of them (are) fruits and date-palms and pomegranates (68)",
      transliteration: "fīhimā fākihatun wanakhlun warummānun ",
      verse: 4969,
      juz: 27,
      surah: 55,
    },
    {
      number: 69,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (69)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4970,
      juz: 27,
      surah: 55,
    },
    {
      number: 70,
      image: "",
      text: "In them (are) good and beautiful ones (70)",
      transliteration: "fīhinna khayrātun ḥisānun ",
      verse: 4971,
      juz: 27,
      surah: 55,
    },
    {
      number: 71,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (71)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4972,
      juz: 27,
      surah: 55,
    },
    {
      number: 72,
      image: "",
      text: "Fair ones restrained in the pavilions (72)",
      transliteration: "ḥūrun maqṣūrātun fī l-khiyāmi ",
      verse: 4973,
      juz: 27,
      surah: 55,
    },
    {
      number: 73,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (73)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4974,
      juz: 27,
      surah: 55,
    },
    {
      number: 74,
      image: "",
      text: "Not has touched them any man before them and not any jinn (74)",
      transliteration: "lam yaṭmith'hunna insun qablahum walā jānnun ",
      verse: 4975,
      juz: 27,
      surah: 55,
    },
    {
      number: 75,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (75)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4976,
      juz: 27,
      surah: 55,
    },
    {
      number: 76,
      image: "",
      text: "Reclining on cushions green and carpets beautiful (76)",
      transliteration: "muttakiīna ʿalā rafrafin khuḍ'rin waʿabqariyyin ḥisānin ",
      verse: 4977,
      juz: 27,
      surah: 55,
    },
    {
      number: 77,
      image: "",
      text: "So which (of the) favors (of) your Lord will you both deny (77)",
      transliteration: "fabi-ayyi ālāi rabbikumā tukadhibāni ",
      verse: 4978,
      juz: 27,
      surah: 55,
    },
    {
      number: 78,
      image: "",
      text: "Blessed is (the) name (of) your Lord Owner (of) Majesty and Honor (78)",
      transliteration: "tabāraka us'mu rabbika dhī l-jalāli wal-ik'rāmi ",
      verse: 4979,
      juz: 27,
      surah: 55,
    },
  ],
};
