import { Surah } from "../types/islam.ts";

export const rahman: Surah = {
  name: "Ar-Rahman",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "The Most Merciful",
      verse: 4771,
    },
    {
      number: 2,
      image: "",
      text: "Taught the Qur'an,",
      verse: 4772,
    },
    {
      number: 3,
      image: "",
      text: "Created man,",
      verse: 4773,
    },
    {
      number: 4,
      image: "",
      text: "[And] taught him eloquence.",
      verse: 4774,
    },
    {
      number: 5,
      image: "",
      text: "The sun and the moon [move] by precise calculation,",
      verse: 4775,
    },
    {
      number: 6,
      image: "",
      text: "And the stars and trees prostrate.",
      verse: 4776,
    },
    {
      number: 7,
      image: "",
      text: "And the heaven He raised and imposed the balance",
      verse: 4777,
    },
    {
      number: 8,
      image: "",
      text: "That you not transgress within the balance.",
      verse: 4778,
    },
    {
      number: 9,
      image: "",
      text:
        "And establish weight in justice and do not make deficient the balance.",
      verse: 4779,
    },
    {
      number: 10,
      image: "",
      text: "And the earth He laid [out] for the creatures.",
      verse: 4780,
    },
    {
      number: 11,
      image: "",
      text: "Therein is fruit and palm trees having sheaths [of dates]",
      verse: 4781,
    },
    {
      number: 12,
      image: "",
      text: "And grain having husks and scented plants.",
      verse: 4782,
    },
    {
      number: 13,
      image: "",
      text: "So which of the favors of your Lord would you deny?",
      verse: 4783,
    },
    {
      number: 14,
      image: "",
      text: "He created man from clay like [that of] pottery.",
      verse: 4784,
    },
    {
      number: 15,
      image: "",
      text: "And He created the jinn from a smokeless flame of fire.",
      verse: 4785,
    },
    {
      number: 16,
      image: "",
      text: "So which of the favors of your Lord would you deny?",
      verse: 4786,
    },
    {
      number: 17,
      image: "",
      text: "[He is] Lord of the two sunrises and Lord of the two sunsets.",
      verse: 4787,
    },
    {
      number: 18,
      image: "",
      text: "So which of the favors of your Lord would you deny?",
      verse: 4788,
    },
    {
      number: 19,
      image: "",
      text: "He released the two seas, meeting [side by side];",
      verse: 4789,
    },
    {
      number: 20,
      image: "",
      text: "Between them is a barrier [so] neither of them transgresses.",
      verse: 4790,
    },
    {
      number: 21,
      image: "",
      text: "So which of the favors of your Lord would you deny?",
      verse: 4791,
    },
    {
      number: 22,
      image: "",
      text: "From both of them emerge pearl and coral.",
      verse: 4792,
    },
    {
      number: 23,
      image: "",
      text: "So which of the favors of your Lord would you deny?",
      verse: 4793,
    },
    {
      number: 24,
      image: "",
      text:
        "And to Him belong the ships [with sails] elevated in the sea like mountains.",
      verse: 4794,
    },
    {
      number: 25,
      image: "",
      text: "So which of the favors of your Lord would you deny?",
      verse: 4795,
    },
    {
      number: 26,
      image: "",
      text: "Everyone upon the earth will perish,",
      verse: 4796,
    },
    {
      number: 27,
      image: "",
      text:
        "And there will remain the Face of your Lord, Owner of Majesty and Honor.",
      verse: 4797,
    },
    {
      number: 28,
      image: "",
      text: "So which of the favors of your Lord would you deny?",
      verse: 4798,
    },
    {
      number: 29,
      image: "",
      text:
        "Whoever is within the heavens and earth asks Him; every day He is bringing about a matter.",
      verse: 4799,
    },
    {
      number: 30,
      image: "",
      text: "So which of the favors of your Lord would you deny?",
      verse: 4800,
    },
    {
      number: 31,
      image: "",
      text: "We will attend to you, O prominent beings.",
      verse: 4801,
    },
    {
      number: 32,
      image: "",
      text: "So which of the favors of your Lord would you deny?",
      verse: 4802,
    },
    {
      number: 33,
      image: "",
      text:
        "O company of jinn and mankind, if you are able to pass beyond the regions of the heavens and the earth, then pass. You will not pass except by authority [from Allah ].",
      verse: 4803,
    },
    {
      number: 34,
      image: "",
      text: "So which of the favors of your Lord would you deny?",
      verse: 4804,
    },
    {
      number: 35,
      image: "",
      text:
        "There will be sent upon you a flame of fire and smoke, and you will not defend yourselves.",
      verse: 4805,
    },
    {
      number: 36,
      image: "",
      text: "So which of the favors of your Lord would you deny?",
      verse: 4806,
    },
    {
      number: 37,
      image: "",
      text:
        "And when the heaven is split open and becomes rose-colored like oil -",
      verse: 4807,
    },
    {
      number: 38,
      image: "",
      text: "So which of the favors of your Lord would you deny? -",
      verse: 4808,
    },
    {
      number: 39,
      image: "",
      text:
        "Then on that Day none will be asked about his sin among men or jinn.",
      verse: 4809,
    },
    {
      number: 40,
      image: "",
      text: "So which of the favors of your Lord would you deny?",
      verse: 4810,
    },
    {
      number: 41,
      image: "",
      text:
        "The criminals will be known by their marks, and they will be seized by the forelocks and the feet.",
      verse: 4811,
    },
    {
      number: 42,
      image: "",
      text: "So which of the favors of your Lord would you deny?",
      verse: 4812,
    },
    {
      number: 43,
      image: "",
      text: "This is Hell, which the criminals deny.",
      verse: 4813,
    },
    {
      number: 44,
      image: "",
      text:
        "They will go around between it and scalding water, heated [to the utmost degree].",
      verse: 4814,
    },
    {
      number: 45,
      image: "",
      text: "So which of the favors of your Lord would you deny?",
      verse: 4815,
    },
    {
      number: 46,
      image: "",
      text:
        "But for he who has feared the position of his Lord are two gardens -",
      verse: 4816,
    },
    {
      number: 47,
      image: "",
      text: "So which of the favors of your Lord would you deny? -",
      verse: 4817,
    },
    {
      number: 48,
      image: "",
      text: "Having [spreading] branches.",
      verse: 4818,
    },
    {
      number: 49,
      image: "",
      text: "So which of the favors of your Lord would you deny?",
      verse: 4819,
    },
    {
      number: 50,
      image: "",
      text: "In both of them are two springs, flowing.",
      verse: 4820,
    },
    {
      number: 51,
      image: "",
      text: "So which of the favors of your Lord would you deny?",
      verse: 4821,
    },
    {
      number: 52,
      image: "",
      text: "In both of them are of every fruit, two kinds.",
      verse: 4822,
    },
    {
      number: 53,
      image: "",
      text: "So which of the favors of your Lord would you deny?",
      verse: 4823,
    },
    {
      number: 54,
      image: "",
      text:
        "[They are] reclining on beds whose linings are of silk brocade, and the fruit of the two gardens is hanging low.",
      verse: 4824,
    },
    {
      number: 55,
      image: "",
      text: "So which of the favors of your Lord would you deny?",
      verse: 4825,
    },
    {
      number: 56,
      image: "",
      text:
        "In them are women limiting [their] glances, untouched before them by man or jinni -",
      verse: 4826,
    },
    {
      number: 57,
      image: "",
      text: "So which of the favors of your Lord would you deny? -",
      verse: 4827,
    },
    {
      number: 58,
      image: "",
      text: "As if they were rubies and coral.",
      verse: 4828,
    },
    {
      number: 59,
      image: "",
      text: "So which of the favors of your Lord would you deny?",
      verse: 4829,
    },
    {
      number: 60,
      image: "",
      text: "Is the reward for good [anything] but good?",
      verse: 4830,
    },
    {
      number: 61,
      image: "",
      text: "So which of the favors of your Lord would you deny?",
      verse: 4831,
    },
    {
      number: 62,
      image: "",
      text: "And below them both [in excellence] are two [other] gardens -",
      verse: 4832,
    },
    {
      number: 63,
      image: "",
      text: "So which of the favors of your Lord would you deny? -",
      verse: 4833,
    },
    {
      number: 64,
      image: "",
      text: "Dark green [in color].",
      verse: 4834,
    },
    {
      number: 65,
      image: "",
      text: "So which of the favors of your Lord would you deny?",
      verse: 4835,
    },
    {
      number: 66,
      image: "",
      text: "In both of them are two springs, spouting.",
      verse: 4836,
    },
    {
      number: 67,
      image: "",
      text: "So which of the favors of your Lord would you deny?",
      verse: 4837,
    },
    {
      number: 68,
      image: "",
      text: "In both of them are fruit and palm trees and pomegranates.",
      verse: 4838,
    },
    {
      number: 69,
      image: "",
      text: "So which of the favors of your Lord would you deny?",
      verse: 4839,
    },
    {
      number: 70,
      image: "",
      text: "In them are good and beautiful women -",
      verse: 4840,
    },
    {
      number: 71,
      image: "",
      text: "So which of the favors of your Lord would you deny? -",
      verse: 4841,
    },
    {
      number: 72,
      image: "",
      text: "Fair ones reserved in pavilions -",
      verse: 4842,
    },
    {
      number: 73,
      image: "",
      text: "So which of the favors of your Lord would you deny? -",
      verse: 4843,
    },
    {
      number: 74,
      image: "",
      text: "Untouched before them by man or jinni -",
      verse: 4844,
    },
    {
      number: 75,
      image: "",
      text: "So which of the favors of your Lord would you deny? -",
      verse: 4845,
    },
    {
      number: 76,
      image: "",
      text: "Reclining on green cushions and beautiful fine carpets.",
      verse: 4846,
    },
    {
      number: 77,
      image: "",
      text: "So which of the favors of your Lord would you deny?",
      verse: 4847,
    },
    {
      number: 78,
      image: "",
      text: "Blessed is the name of your Lord, Owner of Majesty and Honor.",
      verse: 4848,
    },
  ],
};
