import { Surah } from "../types/islam.js";

export const sad: Surah = {
  name: "Sad",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "Saad By the Quran full (of) reminder full (of) reminder (1)",
      transliteration: "sad wal-qur'āni dhī l-dhik'ri ",
      verse: 3971,
      juz: 23,
      surah: 38,
    },
    {
      number: 2,
      image: "",
      text: "Nay those who disbelieve (are) in self-glory and opposition (2)",
      transliteration: "bali alladhīna kafarū fī ʿizzatin washiqāqin ",
      verse: 3972,
      juz: 23,
      surah: 38,
    },
    {
      number: 3,
      image: "",
      text: "How many We destroyed before them before them of a generation then they called out when there (was) no longer time (for) escape (3)",
      transliteration:
        "kam ahlaknā min qablihim min qarnin fanādaw walāta ḥīna manāṣin ",
      verse: 3973,
      juz: 23,
      surah: 38,
    },
    {
      number: 4,
      image: "",
      text: "And they wonder that has come to them a warner from themselves And said the disbelievers This (is) a magician a liar (4)",
      transliteration:
        "waʿajibū an jāahum mundhirun min'hum waqāla l-kāfirūna hādhā sāḥirun kadhābun ",
      verse: 3974,
      juz: 23,
      surah: 38,
    },
    {
      number: 5,
      image: "",
      text: "Has he made the gods (into) one god (into) one god Indeed this (is) certainly a thing curious (5)",
      transliteration:
        "ajaʿala l-ālihata ilāhan wāḥidan inna hādhā lashayon ʿujābun ",
      verse: 3975,
      juz: 23,
      surah: 38,
    },
    {
      number: 6,
      image: "",
      text: "And went forth the chiefs among them that Continue and be patient over your gods Indeed this (is) certainly a thing intended (6)",
      transliteration:
        "wa-inṭalaqa l-mala-u min'hum ani im'shū wa-iṣ'birū ʿalā ālihatikum inna hādhā lashayon yurādu ",
      verse: 3976,
      juz: 23,
      surah: 38,
    },
    {
      number: 7,
      image: "",
      text: "Not we heard of this in the religion the last Not (is) this but a fabrication (7)",
      transliteration:
        "mā samiʿ'nā bihādhā fī l-milati l-ākhirati in hādhā illā ikh'tilāqun ",
      verse: 3977,
      juz: 23,
      surah: 38,
    },
    {
      number: 8,
      image: "",
      text: "Has been revealed to him the Message from among us Nay They (are) in doubt about My Message Nay not yet they have tasted My punishment (8)",
      transliteration:
        "a-unzila ʿalayhi l-dhik'ru min bayninā bal hum fī shakkin min dhik'rī bal lammā yadhūqū ʿadhābi ",
      verse: 3978,
      juz: 23,
      surah: 38,
    },
    {
      number: 9,
      image: "",
      text: "Or have they (the) treasures (of the) Mercy (of) your Lord the All-Mighty the Bestower (9)",
      transliteration: "am ʿindahum khazāinu raḥmati rabbika l-ʿazīzi l-wahābi ",
      verse: 3979,
      juz: 23,
      surah: 38,
    },
    {
      number: 10,
      image: "",
      text: "Or for them (is the) dominion (of) the heavens and the earth and whatever (is) between them Then let them ascend by the means (10)",
      transliteration:
        "am lahum mul'ku l-samāwāti wal-arḍi wamā baynahumā falyartaqū fī l-asbābi ",
      verse: 3980,
      juz: 23,
      surah: 38,
    },
    {
      number: 11,
      image: "",
      text: "Soldiers  there there (they will be) defeated among the companies (11)",
      transliteration: "jundun mā hunālika mahzūmun mina l-aḥzābi ",
      verse: 3981,
      juz: 23,
      surah: 38,
    },
    {
      number: 12,
      image: "",
      text: "Denied before them (the) people (of) Nuh and Aad and Firaun (the) owner (of) the stakes (12)",
      transliteration:
        "kadhabat qablahum qawmu nūḥin waʿādun wafir'ʿawnu dhū l-awtādi ",
      verse: 3982,
      juz: 23,
      surah: 38,
    },
    {
      number: 13,
      image: "",
      text: "And Thamud and (the) people (of) Lut and (the) companions (of) the wood Those (were) the companies (13)",
      transliteration:
        "wathamūdu waqawmu lūṭin wa-aṣḥābu al'aykati ulāika l-aḥzābu ",
      verse: 3983,
      juz: 23,
      surah: 38,
    },
    {
      number: 14,
      image: "",
      text: "Not all (of them) but denied the Messengers so (was) just My penalty (14)",
      transliteration: "in kullun illā kadhaba l-rusula faḥaqqa ʿiqābi ",
      verse: 3984,
      juz: 23,
      surah: 38,
    },
    {
      number: 15,
      image: "",
      text: "And not await these but a shout one not for it any delay (15)",
      transliteration:
        "wamā yanẓuru hāulāi illā ṣayḥatan wāḥidatan mā lahā min fawāqin ",
      verse: 3985,
      juz: 23,
      surah: 38,
    },
    {
      number: 16,
      image: "",
      text: "And they say Our Lord Hasten for us our share before (the) Day (of) the Account (16)",
      transliteration: "waqālū rabbanā ʿajjil lanā qiṭṭanā qabla yawmi l-ḥisābi ",
      verse: 3986,
      juz: 23,
      surah: 38,
    },
    {
      number: 17,
      image: "",
      text: "Be patient over what they say and remember Our slave Dawood the possessor of strength the possessor of strength Indeed, he (was) repeatedly turning (17)",
      transliteration:
        "iṣ'bir ʿalā mā yaqūlūna wa-udh'kur ʿabdanā dāwūda dhā l-aydi innahu awwābun ",
      verse: 3987,
      juz: 23,
      surah: 38,
    },
    {
      number: 18,
      image: "",
      text: "Indeed, We subjected the mountains with him glorifying in the evening and [the] sunrise (18)",
      transliteration:
        "innā sakharnā l-jibāla maʿahu yusabbiḥ'na bil-ʿashiyi wal-ish'rāqi ",
      verse: 3988,
      juz: 23,
      surah: 38,
    },
    {
      number: 19,
      image: "",
      text: "And the birds assembled all with him repeatedly turning (19)",
      transliteration: "wal-ṭayra maḥshūratan kullun lahu awwābun ",
      verse: 3989,
      juz: 23,
      surah: 38,
    },
    {
      number: 20,
      image: "",
      text: "And We strengthened his kingdom and We gave him [the] wisdom and decisive speech (20)",
      transliteration:
        "washadadnā mul'kahu waātaynāhu l-ḥik'mata wafaṣla l-khiṭābi ",
      verse: 3990,
      juz: 23,
      surah: 38,
    },
    {
      number: 21,
      image: "",
      text: "And has (there) come to you (the) news (of) the litigants when they climbed over the wall (of) the chamber (21)",
      transliteration: "wahal atāka naba-u l-khaṣmi idh tasawwarū l-miḥ'rāba ",
      verse: 3991,
      juz: 23,
      surah: 38,
    },
    {
      number: 22,
      image: "",
      text: "When they entered upon Dawood and he was afraid of them they said (Do) not fear (We are) two litigants has wronged one of us to another so judge between us in truth and (do) not be unjust and guide us to an even [the] path (22)",
      transliteration:
        "idh dakhalū ʿalā dāwūda fafaziʿa min'hum qālū lā takhaf khaṣmāni baghā baʿḍunā ʿalā baʿḍin fa-uḥ'kum baynanā bil-ḥaqi walā tush'ṭiṭ wa-ih'dinā ilā sawāi l-ṣirāṭi ",
      verse: 3992,
      juz: 23,
      surah: 38,
    },
    {
      number: 23,
      image: "",
      text: "Indeed this (is) my brother he has ninety-nine ninety-nine ewe(s) while I have ewe one so he said Entrust her to me and he overpowered me in [the] speech (23)",
      transliteration:
        "inna hādhā akhī lahu tis'ʿun watis'ʿūna naʿjatan waliya naʿjatun wāḥidatun faqāla akfil'nīhā waʿazzanī fī l-khiṭābi ",
      verse: 3993,
      juz: 23,
      surah: 38,
    },
    {
      number: 24,
      image: "",
      text: "He said Certainly he has wronged you by demanding your ewe to his ewes And indeed many of the partners certainly oppress some of them [on] another except those who believe and do righteous deeds and few (are) they (are) they And became certain Dawood that We (had) tried him and he asked forgiveness (of) his Lord and fell down bowing and turned in repentance (24)",
      transliteration:
        "qāla laqad ẓalamaka bisuāli naʿjatika ilā niʿājihi wa-inna kathīran mina l-khulaṭāi layabghī baʿḍuhum ʿalā baʿḍin illā alladhīna āmanū waʿamilū l-ṣāliḥāti waqalīlun mā hum waẓanna dāwūdu annamā fatannāhu fa-is'taghfara rabbahu wakharra rākiʿan wa-anāba ",
      verse: 3994,
      juz: 23,
      surah: 38,
    },
    {
      number: 25,
      image: "",
      text: "So We forgave for him that And indeed for him with Us surely is a near access and a good place of return (25)",
      transliteration:
        "faghafarnā lahu dhālika wa-inna lahu ʿindanā lazul'fā waḥus'na maābin ",
      verse: 3995,
      juz: 23,
      surah: 38,
    },
    {
      number: 26,
      image: "",
      text: "O Dawood Indeed, We [We] have made you a vicegerent in the earth so judge between [the] men in truth and (do) not follow the desire for it will lead you astray from (the) way (of) Allah Indeed those who go astray from (the) way (of) Allah for them (is) a punishment severe because they forgot (the) Day (of) Account (26)",
      transliteration:
        "yādāwūdu innā jaʿalnāka khalīfatan fī l-arḍi fa-uḥ'kum bayna l-nāsi bil-ḥaqi walā tattabiʿi l-hawā fayuḍillaka ʿan sabīli l-lahi inna alladhīna yaḍillūna ʿan sabīli l-lahi lahum ʿadhābun shadīdun bimā nasū yawma l-ḥisābi ",
      verse: 3996,
      juz: 23,
      surah: 38,
    },
    {
      number: 27,
      image: "",
      text: "And not We created the heaven and the earth and whatever (is) between them without purpose That (is the) assumption (of) those who disbelieve So woe to those who disbelieve from the Fire (27)",
      transliteration:
        "wamā khalaqnā l-samāa wal-arḍa wamā baynahumā bāṭilan dhālika ẓannu alladhīna kafarū fawaylun lilladhīna kafarū mina l-nāri ",
      verse: 3997,
      juz: 23,
      surah: 38,
    },
    {
      number: 28,
      image: "",
      text: "Or should We treat those who believe and do righteous deeds like those who spread corruption in the earth Or should We treat the pious like the wicked (28)",
      transliteration:
        "am najʿalu alladhīna āmanū waʿamilū l-ṣāliḥāti kal-muf'sidīna fī l-arḍi am najʿalu l-mutaqīna kal-fujāri ",
      verse: 3998,
      juz: 23,
      surah: 38,
    },
    {
      number: 29,
      image: "",
      text: "(This is) a Book We have revealed it to you blessed that they may ponder (over) its Verses and may be reminded those of understanding those of understanding (29)",
      transliteration:
        "kitābun anzalnāhu ilayka mubārakun liyaddabbarū āyātihi waliyatadhakkara ulū l-albābi ",
      verse: 3999,
      juz: 23,
      surah: 38,
    },
    {
      number: 30,
      image: "",
      text: "And We gave to Dawood Sulaiman an excellent slave Indeed, he (was) one who repeatedly turned (30)",
      transliteration:
        "wawahabnā lidāwūda sulaymāna niʿ'ma l-ʿabdu innahu awwābun ",
      verse: 4000,
      juz: 23,
      surah: 38,
    },
    {
      number: 31,
      image: "",
      text: "When were displayed to him in the afternoon excellent bred steeds excellent bred steeds (31)",
      transliteration: "idh ʿuriḍa ʿalayhi bil-ʿashiyi l-ṣāfinātu l-jiyādu ",
      verse: 4001,
      juz: 23,
      surah: 38,
    },
    {
      number: 32,
      image: "",
      text: "And he said Indeed, I [I] preferred (the) love (of) the good over (the) remembrance (of) my Lord Until they were hidden in the veil (32)",
      transliteration:
        "faqāla innī aḥbabtu ḥubba l-khayri ʿan dhik'ri rabbī ḥattā tawārat bil-ḥijābi ",
      verse: 4002,
      juz: 23,
      surah: 38,
    },
    {
      number: 33,
      image: "",
      text: "Return them to me Then he began (to) pass (his hand) over the legs and the necks (33)",
      transliteration: "ruddūhā ʿalayya faṭafiqa masḥan bil-sūqi wal-aʿnāqi ",
      verse: 4003,
      juz: 23,
      surah: 38,
    },
    {
      number: 34,
      image: "",
      text: "And certainly We tried Sulaiman and We placed on his throne a body then he turned (34)",
      transliteration:
        "walaqad fatannā sulaymāna wa-alqaynā ʿalā kur'siyyihi jasadan thumma anāba ",
      verse: 4004,
      juz: 23,
      surah: 38,
    },
    {
      number: 35,
      image: "",
      text: "He said O my Lord Forgive me and grant me a kingdom not (will) belong to anyone after me after me Indeed, You [You] (are) the Bestower (35)",
      transliteration:
        "qāla rabbi igh'fir lī wahab lī mul'kan lā yanbaghī li-aḥadin min baʿdī innaka anta l-wahābu ",
      verse: 4005,
      juz: 23,
      surah: 38,
    },
    {
      number: 36,
      image: "",
      text: "Then We subjected to him the wind to flow by his command gently wherever he directed (36)",
      transliteration:
        "fasakharnā lahu l-rīḥa tajrī bi-amrihi rukhāan ḥaythu aṣāba ",
      verse: 4006,
      juz: 23,
      surah: 38,
    },
    {
      number: 37,
      image: "",
      text: "And the devils every builder and diver (37)",
      transliteration: "wal-shayāṭīna kulla bannāin waghawwāṣin ",
      verse: 4007,
      juz: 23,
      surah: 38,
    },
    {
      number: 38,
      image: "",
      text: "And others bound in chains (38)",
      transliteration: "waākharīna muqarranīna fī l-aṣfādi ",
      verse: 4008,
      juz: 23,
      surah: 38,
    },
    {
      number: 39,
      image: "",
      text: "This (is) Our gift so grant or withhold without account (39)",
      transliteration: "hādhā ʿaṭāunā fa-um'nun aw amsik bighayri ḥisābin ",
      verse: 4009,
      juz: 23,
      surah: 38,
    },
    {
      number: 40,
      image: "",
      text: "And indeed for him with Us surely is a near access and a good place of return (40)",
      transliteration: "wa-inna lahu ʿindanā lazul'fā waḥus'na maābin ",
      verse: 4010,
      juz: 23,
      surah: 38,
    },
    {
      number: 41,
      image: "",
      text: "And remember Our slave Ayyub when he called his Lord That [I] (has) touched me Shaitaan with distress and suffering (41)",
      transliteration:
        "wa-udh'kur ʿabdanā ayyūba idh nādā rabbahu annī massaniya l-shayṭānu binuṣ'bin waʿadhābin ",
      verse: 4011,
      juz: 23,
      surah: 38,
    },
    {
      number: 42,
      image: "",
      text: "Strike with your foot This (is a spring of) water to bathe cool and a drink (42)",
      transliteration: "ur'kuḍ birij'lika hādhā mugh'tasalun bāridun washarābun ",
      verse: 4012,
      juz: 23,
      surah: 38,
    },
    {
      number: 43,
      image: "",
      text: "And We granted [to] him his family and a like of them with them a Mercy from Us and a Reminder for those of understanding for those of understanding (43)",
      transliteration:
        "wawahabnā lahu ahlahu wamith'lahum maʿahum raḥmatan minnā wadhik'rā li-ulī l-albābi ",
      verse: 4013,
      juz: 23,
      surah: 38,
    },
    {
      number: 44,
      image: "",
      text: "And take in your hand a bunch and strike with it and (do) not break (your) oath Indeed, We [We] found him patient an excellent slave Indeed, he repeatedly turned (44)",
      transliteration:
        "wakhudh biyadika ḍigh'than fa-iḍ'rib bihi walā taḥnath innā wajadnāhu ṣābiran niʿ'ma l-ʿabdu innahu awwābun ",
      verse: 4014,
      juz: 23,
      surah: 38,
    },
    {
      number: 45,
      image: "",
      text: "And remember Our slaves Ibrahim and Isaac and Ayyub possessors (of) strength and vision (45)",
      transliteration:
        "wa-udh'kur ʿibādanā ib'rāhīma wa-is'ḥāqa wayaʿqūba ulī l-aydī wal-abṣāri ",
      verse: 4015,
      juz: 23,
      surah: 38,
    },
    {
      number: 46,
      image: "",
      text: "Indeed, We [We] chose them for an exclusive (quality) remembrance (of) the Home (46)",
      transliteration: "innā akhlaṣnāhum bikhāliṣatin dhik'rā l-dāri ",
      verse: 4016,
      juz: 23,
      surah: 38,
    },
    {
      number: 47,
      image: "",
      text: "And indeed, they to Us (are) from the chosen ones the best (47)",
      transliteration: "wa-innahum ʿindanā lamina l-muṣ'ṭafayna l-akhyāri ",
      verse: 4017,
      juz: 23,
      surah: 38,
    },
    {
      number: 48,
      image: "",
      text: "And remember Ishmael and Elisha and Dhul-kifl and Dhul-kifl and all (are) from the best (48)",
      transliteration:
        "wa-udh'kur is'māʿīla wal-yasaʿa wadhā l-kif'li wakullun mina l-akhyāri ",
      verse: 4018,
      juz: 23,
      surah: 38,
    },
    {
      number: 49,
      image: "",
      text: "This (is) a Reminder And indeed for the righteous surely, is a good place of return (49)",
      transliteration: "hādhā dhik'run wa-inna lil'muttaqīna laḥus'na maābin ",
      verse: 4019,
      juz: 23,
      surah: 38,
    },
    {
      number: 50,
      image: "",
      text: "Gardens (of) Eternity (will be) opened for them the gates (50)",
      transliteration: "jannāti ʿadnin mufattaḥatan lahumu l-abwābu ",
      verse: 4020,
      juz: 23,
      surah: 38,
    },
    {
      number: 51,
      image: "",
      text: "Reclining therein they will call therein for fruit many and drink (51)",
      transliteration:
        "muttakiīna fīhā yadʿūna fīhā bifākihatin kathīratin washarābin ",
      verse: 4021,
      juz: 23,
      surah: 38,
    },
    {
      number: 52,
      image: "",
      text: "And with them (will be) companions of modest gaze (will be) companions of modest gaze well-matched (52)",
      transliteration: "waʿindahum qāṣirātu l-ṭarfi atrābun ",
      verse: 4022,
      juz: 23,
      surah: 38,
    },
    {
      number: 53,
      image: "",
      text: "This (is) what you are promised for (the) Day (of) Account (53)",
      transliteration: "hādhā mā tūʿadūna liyawmi l-ḥisābi ",
      verse: 4023,
      juz: 23,
      surah: 38,
    },
    {
      number: 54,
      image: "",
      text: "Indeed this (is) surely Our provision not for it any depletion (54)",
      transliteration: "inna hādhā lariz'qunā mā lahu min nafādin ",
      verse: 4024,
      juz: 23,
      surah: 38,
    },
    {
      number: 55,
      image: "",
      text: "This (is so) And indeed for the transgressors surely (is) an evil place of return (55)",
      transliteration: "hādhā wa-inna lilṭṭāghīna lasharra maābin ",
      verse: 4025,
      juz: 23,
      surah: 38,
    },
    {
      number: 56,
      image: "",
      text: "Hell they will burn therein and wretched (is) the resting place (56)",
      transliteration: "jahannama yaṣlawnahā fabi'sa l-mihādu ",
      verse: 4026,
      juz: 23,
      surah: 38,
    },
    {
      number: 57,
      image: "",
      text: "This (is so) Then let them taste it boiling fluid and purulence (57)",
      transliteration: "hādhā falyadhūqūhu ḥamīmun waghassāqun ",
      verse: 4027,
      juz: 23,
      surah: 38,
    },
    {
      number: 58,
      image: "",
      text: "And other of its type (of various) kinds (58)",
      transliteration: "waākharu min shaklihi azwājun ",
      verse: 4028,
      juz: 23,
      surah: 38,
    },
    {
      number: 59,
      image: "",
      text: "This (is) a company bursting (in) with you No welcome for them Indeed, they (will) burn (in) the Fire (59)",
      transliteration:
        "hādhā fawjun muq'taḥimun maʿakum lā marḥaban bihim innahum ṣālū l-nāri ",
      verse: 4029,
      juz: 23,
      surah: 38,
    },
    {
      number: 60,
      image: "",
      text: "They say Nay You  no welcome for you You brought this upon us So wretched (is) the settlement (60)",
      transliteration:
        "qālū bal antum lā marḥaban bikum antum qaddamtumūhu lanā fabi'sa l-qarāru ",
      verse: 4030,
      juz: 23,
      surah: 38,
    },
    {
      number: 61,
      image: "",
      text: "They will say Our Lord whoever brought upon us this increase for him a punishment double in the Fire (61)",
      transliteration:
        "qālū rabbanā man qaddama lanā hādhā fazid'hu ʿadhāban ḍiʿ'fan fī l-nāri ",
      verse: 4031,
      juz: 23,
      surah: 38,
    },
    {
      number: 62,
      image: "",
      text: "And they (will) say What (is) for us not we see men we used to count them among the bad ones (62)",
      transliteration:
        "waqālū mā lanā lā narā rijālan kunnā naʿudduhum mina l-ashrāri ",
      verse: 4032,
      juz: 23,
      surah: 38,
    },
    {
      number: 63,
      image: "",
      text: "Did we take them (in) ridicule or has turned away from them the vision (63)",
      transliteration: "attakhadhnāhum sikh'riyyan am zāghat ʿanhumu l-abṣāru ",
      verse: 4033,
      juz: 23,
      surah: 38,
    },
    {
      number: 64,
      image: "",
      text: "Indeed that (is) surely (the) truth  (the) quarreling (of the) people (of) the Fire (64)",
      transliteration: "inna dhālika laḥaqqun takhāṣumu ahli l-nāri ",
      verse: 4034,
      juz: 23,
      surah: 38,
    },
    {
      number: 65,
      image: "",
      text: "Say Only I am a warner and not (is there) any god except Allah the One the Irresistible (65)",
      transliteration:
        "qul innamā anā mundhirun wamā min ilāhin illā l-lahu l-wāḥidu l-qahāru ",
      verse: 4035,
      juz: 23,
      surah: 38,
    },
    {
      number: 66,
      image: "",
      text: "Lord (of) the heavens and the earth and whatever (is) between them the All-Mighty the Oft-Forgiving (66)",
      transliteration:
        "rabbu l-samāwāti wal-arḍi wamā baynahumā l-ʿazīzu l-ghafāru ",
      verse: 4036,
      juz: 23,
      surah: 38,
    },
    {
      number: 67,
      image: "",
      text: "Say It (is) a news great (67)",
      transliteration: "qul huwa naba-on ʿaẓīmun ",
      verse: 4037,
      juz: 23,
      surah: 38,
    },
    {
      number: 68,
      image: "",
      text: "You from it turn away (68)",
      transliteration: "antum ʿanhu muʿ'riḍūna ",
      verse: 4038,
      juz: 23,
      surah: 38,
    },
    {
      number: 69,
      image: "",
      text: "Not is for me any knowledge (of) the chiefs the exalted when they were disputing (69)",
      transliteration:
        "mā kāna liya min ʿil'min bil-mala-i l-aʿlā idh yakhtaṣimūna ",
      verse: 4039,
      juz: 23,
      surah: 38,
    },
    {
      number: 70,
      image: "",
      text: "Not has been revealed to me except that only I am a warner clear (70)",
      transliteration: "in yūḥā ilayya illā annamā anā nadhīrun mubīnun ",
      verse: 4040,
      juz: 23,
      surah: 38,
    },
    {
      number: 71,
      image: "",
      text: "When said your Lord to the Angels Indeed, I Am going to create a human being from clay (71)",
      transliteration:
        "idh qāla rabbuka lil'malāikati innī khāliqun basharan min ṭīnin ",
      verse: 4041,
      juz: 23,
      surah: 38,
    },
    {
      number: 72,
      image: "",
      text: "So when I have proportioned him and breathed into him of My spirit then fall down to him prostrating (72)",
      transliteration:
        "fa-idhā sawwaytuhu wanafakhtu fīhi min rūḥī faqaʿū lahu sājidīna ",
      verse: 4042,
      juz: 23,
      surah: 38,
    },
    {
      number: 73,
      image: "",
      text: "So prostrated the Angels all of them together (73)",
      transliteration: "fasajada l-malāikatu kulluhum ajmaʿūna ",
      verse: 4043,
      juz: 23,
      surah: 38,
    },
    {
      number: 74,
      image: "",
      text: "Except Iblis he was arrogant and became of the disbelievers (74)",
      transliteration: "illā ib'līsa is'takbara wakāna mina l-kāfirīna ",
      verse: 4044,
      juz: 23,
      surah: 38,
    },
    {
      number: 75,
      image: "",
      text: "He said O Iblis What prevented you that you (should) prostrate to (one) whom I created with My Hands Are you arrogant or are you of the exalted ones (75)",
      transliteration:
        "qāla yāib'līsu mā manaʿaka an tasjuda limā khalaqtu biyadayya astakbarta am kunta mina l-ʿālīna ",
      verse: 4045,
      juz: 23,
      surah: 38,
    },
    {
      number: 76,
      image: "",
      text: "He said I am better than him You created me from fire and You created him from clay (76)",
      transliteration:
        "qāla anā khayrun min'hu khalaqtanī min nārin wakhalaqtahu min ṭīnin ",
      verse: 4046,
      juz: 23,
      surah: 38,
    },
    {
      number: 77,
      image: "",
      text: "He said Then get out of it for indeed, you (are) accursed (77)",
      transliteration: "qāla fa-ukh'ruj min'hā fa-innaka rajīmun ",
      verse: 4047,
      juz: 23,
      surah: 38,
    },
    {
      number: 78,
      image: "",
      text: "And indeed upon you (is) My curse until (the) Day (of) Judgment (78)",
      transliteration: "wa-inna ʿalayka laʿnatī ilā yawmi l-dīni ",
      verse: 4048,
      juz: 23,
      surah: 38,
    },
    {
      number: 79,
      image: "",
      text: "He said My Lord Then give me respite until (the) Day they are resurrected (79)",
      transliteration: "qāla rabbi fa-anẓir'nī ilā yawmi yub'ʿathūna ",
      verse: 4049,
      juz: 23,
      surah: 38,
    },
    {
      number: 80,
      image: "",
      text: "He said Then indeed, you (are) of those given respite (80)",
      transliteration: "qāla fa-innaka mina l-munẓarīna ",
      verse: 4050,
      juz: 23,
      surah: 38,
    },
    {
      number: 81,
      image: "",
      text: "Until (the) Day (of) the time well-known (81)",
      transliteration: "ilā yawmi l-waqti l-maʿlūmi ",
      verse: 4051,
      juz: 23,
      surah: 38,
    },
    {
      number: 82,
      image: "",
      text: "He said Then by Your might I will surely mislead them all (82)",
      transliteration: "qāla fabiʿizzatika la-ugh'wiyannahum ajmaʿīna ",
      verse: 4052,
      juz: 23,
      surah: 38,
    },
    {
      number: 83,
      image: "",
      text: "Except Your slaves among them the chosen ones (83)",
      transliteration: "illā ʿibādaka min'humu l-mukh'laṣīna ",
      verse: 4053,
      juz: 23,
      surah: 38,
    },
    {
      number: 84,
      image: "",
      text: "He said Then (it is) the truth and the truth I say (84)",
      transliteration: "qāla fal-ḥaqu wal-ḥaqa aqūlu ",
      verse: 4054,
      juz: 23,
      surah: 38,
    },
    {
      number: 85,
      image: "",
      text: "Surely I will fill Hell with you and those who follow you among them all (85)",
      transliteration:
        "la-amla-anna jahannama minka wamimman tabiʿaka min'hum ajmaʿīna ",
      verse: 4055,
      juz: 23,
      surah: 38,
    },
    {
      number: 86,
      image: "",
      text: "Say Not I ask of you for it any payment and not I am of the ones who pretend (86)",
      transliteration:
        "qul mā asalukum ʿalayhi min ajrin wamā anā mina l-mutakalifīna ",
      verse: 4056,
      juz: 23,
      surah: 38,
    },
    {
      number: 87,
      image: "",
      text: "Not it (is) except a Reminder to the worlds (87)",
      transliteration: "in huwa illā dhik'run lil'ʿālamīna ",
      verse: 4057,
      juz: 23,
      surah: 38,
    },
    {
      number: 88,
      image: "",
      text: "And surely you will know its information after a time (88)",
      transliteration: "walataʿlamunna naba-ahu baʿda ḥīnin ",
      verse: 4058,
      juz: 23,
      surah: 38,
    },
  ],
};
