import { Surah } from "../types/islam.js";

export const saffat: Surah = {
  name: "As-Saffat",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "By those lined (in) rows (1)",
      transliteration: "wal-ṣāfāti ṣaffan ",
      verse: 3789,
      juz: 23,
      surah: 37,
    },
    {
      number: 2,
      image: "",
      text: "And those who drive strongly (2)",
      transliteration: "fal-zājirāti zajran ",
      verse: 3790,
      juz: 23,
      surah: 37,
    },
    {
      number: 3,
      image: "",
      text: "And those who recite (the) Message (3)",
      transliteration: "fal-tāliyāti dhik'ran ",
      verse: 3791,
      juz: 23,
      surah: 37,
    },
    {
      number: 4,
      image: "",
      text: "Indeed your Lord (is) surely One (4)",
      transliteration: "inna ilāhakum lawāḥidun ",
      verse: 3792,
      juz: 23,
      surah: 37,
    },
    {
      number: 5,
      image: "",
      text: "Lord (of) the heavens and the earth and what (is) between both of them and Lord (of) each point of sunrise (5)",
      transliteration:
        "rabbu l-samāwāti wal-arḍi wamā baynahumā warabbu l-mashāriqi ",
      verse: 3793,
      juz: 23,
      surah: 37,
    },
    {
      number: 6,
      image: "",
      text: "Indeed, We [We] adorned the sky [the world] with an adornment (of) the stars (6)",
      transliteration: "innā zayyannā l-samāa l-dun'yā bizīnatin l-kawākibi ",
      verse: 3794,
      juz: 23,
      surah: 37,
    },
    {
      number: 7,
      image: "",
      text: "And (to) guard against every devil rebellious (7)",
      transliteration: "waḥif'ẓan min kulli shayṭānin māridin ",
      verse: 3795,
      juz: 23,
      surah: 37,
    },
    {
      number: 8,
      image: "",
      text: "Not they may listen to the assembly [the] exalted are pelted from every side (8)",
      transliteration:
        "lā yassammaʿūna ilā l-mala-i l-aʿlā wayuq'dhafūna min kulli jānibin ",
      verse: 3796,
      juz: 23,
      surah: 37,
    },
    {
      number: 9,
      image: "",
      text: "Repelled and for them (is) a punishment perpetual (9)",
      transliteration: "duḥūran walahum ʿadhābun wāṣibun ",
      verse: 3797,
      juz: 23,
      surah: 37,
    },
    {
      number: 10,
      image: "",
      text: "Except (him) who snatches (by) theft but follows him a burning flame piercing (10)",
      transliteration:
        "illā man khaṭifa l-khaṭfata fa-atbaʿahu shihābun thāqibun ",
      verse: 3798,
      juz: 23,
      surah: 37,
    },
    {
      number: 11,
      image: "",
      text: "Then ask them Are they a stronger creation or (those) whom We have created Indeed, We created them from a clay sticky (11)",
      transliteration:
        "fa-is'taftihim ahum ashaddu khalqan am man khalaqnā innā khalaqnāhum min ṭīnin lāzibin ",
      verse: 3799,
      juz: 23,
      surah: 37,
    },
    {
      number: 12,
      image: "",
      text: "Nay you wonder while they mock (12)",
      transliteration: "bal ʿajib'ta wayaskharūna ",
      verse: 3800,
      juz: 23,
      surah: 37,
    },
    {
      number: 13,
      image: "",
      text: "And when they are reminded not they receive admonition (13)",
      transliteration: "wa-idhā dhukkirū lā yadhkurūna ",
      verse: 3801,
      juz: 23,
      surah: 37,
    },
    {
      number: 14,
      image: "",
      text: "And when they see a Sign they mock (14)",
      transliteration: "wa-idhā ra-aw āyatan yastaskhirūna ",
      verse: 3802,
      juz: 23,
      surah: 37,
    },
    {
      number: 15,
      image: "",
      text: "And they say Not (is) this except a magic clear (15)",
      transliteration: "waqālū in hādhā illā siḥ'run mubīnun ",
      verse: 3803,
      juz: 23,
      surah: 37,
    },
    {
      number: 16,
      image: "",
      text: "Is it when we are dead and have become dust and bones shall we then be certainly resurrected (16)",
      transliteration:
        "a-idhā mit'nā wakunnā turāban waʿiẓāman a-innā lamabʿūthūna ",
      verse: 3804,
      juz: 23,
      surah: 37,
    },
    {
      number: 17,
      image: "",
      text: "Or our fathers former (17)",
      transliteration: "awaābāunā l-awalūna ",
      verse: 3805,
      juz: 23,
      surah: 37,
    },
    {
      number: 18,
      image: "",
      text: "Say Yes and you (will be) humiliated (18)",
      transliteration: "qul naʿam wa-antum dākhirūna ",
      verse: 3806,
      juz: 23,
      surah: 37,
    },
    {
      number: 19,
      image: "",
      text: "Then only it (will be) a cry single then, behold They will see (19)",
      transliteration: "fa-innamā hiya zajratun wāḥidatun fa-idhā hum yanẓurūna ",
      verse: 3807,
      juz: 23,
      surah: 37,
    },
    {
      number: 20,
      image: "",
      text: "And they will say O woe to us This (is the) Day (of) the Recompense (20)",
      transliteration: "waqālū yāwaylanā hādhā yawmu l-dīni ",
      verse: 3808,
      juz: 23,
      surah: 37,
    },
    {
      number: 21,
      image: "",
      text: "This (is the) Day (of) Judgment which you used to [of it] deny (21)",
      transliteration: "hādhā yawmu l-faṣli alladhī kuntum bihi tukadhibūna ",
      verse: 3809,
      juz: 23,
      surah: 37,
    },
    {
      number: 22,
      image: "",
      text: "Gather those who wronged and their kinds and what they used (to) worship (22)",
      transliteration:
        "uḥ'shurū alladhīna ẓalamū wa-azwājahum wamā kānū yaʿbudūna ",
      verse: 3810,
      juz: 23,
      surah: 37,
    },
    {
      number: 23,
      image: "",
      text: "Besides Besides Allah then lead them to (the) Path (of) the Hellfire (23)",
      transliteration: "min dūni l-lahi fa-ih'dūhum ilā ṣirāṭi l-jaḥīmi ",
      verse: 3811,
      juz: 23,
      surah: 37,
    },
    {
      number: 24,
      image: "",
      text: "And stop them indeed, they (are) to be questioned (24)",
      transliteration: "waqifūhum innahum masūlūna ",
      verse: 3812,
      juz: 23,
      surah: 37,
    },
    {
      number: 25,
      image: "",
      text: "What (is) for you (Why) not you help one another (25)",
      transliteration: "mā lakum lā tanāṣarūna ",
      verse: 3813,
      juz: 23,
      surah: 37,
    },
    {
      number: 26,
      image: "",
      text: "Nay they (on) that Day (will) surrender (26)",
      transliteration: "bal humu l-yawma mus'taslimūna ",
      verse: 3814,
      juz: 23,
      surah: 37,
    },
    {
      number: 27,
      image: "",
      text: "And will approach some of them to others questioning one another (27)",
      transliteration: "wa-aqbala baʿḍuhum ʿalā baʿḍin yatasāalūna ",
      verse: 3815,
      juz: 23,
      surah: 37,
    },
    {
      number: 28,
      image: "",
      text: "They will say Indeed, you [you] used (to) come (to) us from the right (28)",
      transliteration: "qālū innakum kuntum tatūnanā ʿani l-yamīni ",
      verse: 3816,
      juz: 23,
      surah: 37,
    },
    {
      number: 29,
      image: "",
      text: "They will say Nay not you were believers (29)",
      transliteration: "qālū bal lam takūnū mu'minīna ",
      verse: 3817,
      juz: 23,
      surah: 37,
    },
    {
      number: 30,
      image: "",
      text: "And not was for us over you any authority Nay you were a people transgressing (30)",
      transliteration:
        "wamā kāna lanā ʿalaykum min sul'ṭānin bal kuntum qawman ṭāghīna ",
      verse: 3818,
      juz: 23,
      surah: 37,
    },
    {
      number: 31,
      image: "",
      text: "So has been proved true against us (the) Word (of) our Lord indeed, we (will) certainly taste (31)",
      transliteration: "faḥaqqa ʿalaynā qawlu rabbinā innā ladhāiqūna ",
      verse: 3819,
      juz: 23,
      surah: 37,
    },
    {
      number: 32,
      image: "",
      text: "So we led you astray indeed, we were astray (32)",
      transliteration: "fa-aghwaynākum innā kunnā ghāwīna ",
      verse: 3820,
      juz: 23,
      surah: 37,
    },
    {
      number: 33,
      image: "",
      text: "Then indeed, they that Day in the punishment (will be) sharers (33)",
      transliteration: "fa-innahum yawma-idhin fī l-ʿadhābi mush'tarikūna ",
      verse: 3821,
      juz: 23,
      surah: 37,
    },
    {
      number: 34,
      image: "",
      text: "Indeed, We thus We deal with the criminals (34)",
      transliteration: "innā kadhālika nafʿalu bil-muj'rimīna ",
      verse: 3822,
      juz: 23,
      surah: 37,
    },
    {
      number: 35,
      image: "",
      text: "Indeed, they were when it was said to them (There is) no god except Allah were arrogant (35)",
      transliteration:
        "innahum kānū idhā qīla lahum lā ilāha illā l-lahu yastakbirūna ",
      verse: 3823,
      juz: 23,
      surah: 37,
    },
    {
      number: 36,
      image: "",
      text: "And they say Are we to leave our gods for a poet mad (36)",
      transliteration:
        "wayaqūlūna a-innā latārikū ālihatinā lishāʿirin majnūnin ",
      verse: 3824,
      juz: 23,
      surah: 37,
    },
    {
      number: 37,
      image: "",
      text: "Nay he has brought the truth and confirmed the Messengers (37)",
      transliteration: "bal jāa bil-ḥaqi waṣaddaqa l-mur'salīna ",
      verse: 3825,
      juz: 23,
      surah: 37,
    },
    {
      number: 38,
      image: "",
      text: "Indeed, you (will) surely taste the punishment painful (38)",
      transliteration: "innakum ladhāiqū l-ʿadhābi l-alīmi ",
      verse: 3826,
      juz: 23,
      surah: 37,
    },
    {
      number: 39,
      image: "",
      text: "And not you will be recompensed except what you used to do (39)",
      transliteration: "wamā tuj'zawna illā mā kuntum taʿmalūna ",
      verse: 3827,
      juz: 23,
      surah: 37,
    },
    {
      number: 40,
      image: "",
      text: "Except (the) slaves (of) Allah the chosen ones (40)",
      transliteration: "illā ʿibāda l-lahi l-mukh'laṣīna ",
      verse: 3828,
      juz: 23,
      surah: 37,
    },
    {
      number: 41,
      image: "",
      text: "Those for them (will be) a provision determined (41)",
      transliteration: "ulāika lahum riz'qun maʿlūmun ",
      verse: 3829,
      juz: 23,
      surah: 37,
    },
    {
      number: 42,
      image: "",
      text: "Fruits and they (will) be honored (42)",
      transliteration: "fawākihu wahum muk'ramūna ",
      verse: 3830,
      juz: 23,
      surah: 37,
    },
    {
      number: 43,
      image: "",
      text: "In Gardens (of) Delight (43)",
      transliteration: "fī jannāti l-naʿīmi ",
      verse: 3831,
      juz: 23,
      surah: 37,
    },
    {
      number: 44,
      image: "",
      text: "On thrones facing each other (44)",
      transliteration: "ʿalā sururin mutaqābilīna ",
      verse: 3832,
      juz: 23,
      surah: 37,
    },
    {
      number: 45,
      image: "",
      text: "Will be circulated among them a cup from a flowing spring (45)",
      transliteration: "yuṭāfu ʿalayhim bikasin min maʿīnin ",
      verse: 3833,
      juz: 23,
      surah: 37,
    },
    {
      number: 46,
      image: "",
      text: "White delicious for the drinkers (46)",
      transliteration: "bayḍāa ladhatin lilshāribīna ",
      verse: 3834,
      juz: 23,
      surah: 37,
    },
    {
      number: 47,
      image: "",
      text: "Not in it (is) bad effect and not they from it will be intoxicated (47)",
      transliteration: "lā fīhā ghawlun walā hum ʿanhā yunzafūna ",
      verse: 3835,
      juz: 23,
      surah: 37,
    },
    {
      number: 48,
      image: "",
      text: "And with them (will be) companions of modest gaze (will be) companions of modest gaze (having) beautiful eyes (48)",
      transliteration: "waʿindahum qāṣirātu l-ṭarfi ʿīnun ",
      verse: 3836,
      juz: 23,
      surah: 37,
    },
    {
      number: 49,
      image: "",
      text: "As if they were eggs well protected (49)",
      transliteration: "ka-annahunna bayḍun maknūnun ",
      verse: 3837,
      juz: 23,
      surah: 37,
    },
    {
      number: 50,
      image: "",
      text: "And (will) approach some of them to others questioning one another (50)",
      transliteration: "fa-aqbala baʿḍuhum ʿalā baʿḍin yatasāalūna ",
      verse: 3838,
      juz: 23,
      surah: 37,
    },
    {
      number: 51,
      image: "",
      text: "Will say a speaker among them Indeed, I had for me a companion (51)",
      transliteration: "qāla qāilun min'hum innī kāna lī qarīnun ",
      verse: 3839,
      juz: 23,
      surah: 37,
    },
    {
      number: 52,
      image: "",
      text: "Who (would) say Are you indeed surely of those who believe (52)",
      transliteration: "yaqūlu a-innaka lamina l-muṣadiqīna ",
      verse: 3840,
      juz: 23,
      surah: 37,
    },
    {
      number: 53,
      image: "",
      text: "Is (it) when we have died and become dust and bones will we surely be brought to Judgment (53)",
      transliteration:
        "a-idhā mit'nā wakunnā turāban waʿiẓāman a-innā lamadīnūna ",
      verse: 3841,
      juz: 23,
      surah: 37,
    },
    {
      number: 54,
      image: "",
      text: "He (will) say Will you be looking (54)",
      transliteration: "qāla hal antum muṭṭaliʿūna ",
      verse: 3842,
      juz: 23,
      surah: 37,
    },
    {
      number: 55,
      image: "",
      text: "Then he (will) look and see him in (the) midst (of) the Hellfire (55)",
      transliteration: "fa-iṭṭalaʿa faraāhu fī sawāi l-jaḥīmi ",
      verse: 3843,
      juz: 23,
      surah: 37,
    },
    {
      number: 56,
      image: "",
      text: "He (will) say By Allah verily you almost ruined me (56)",
      transliteration: "qāla tal-lahi in kidtta latur'dīni ",
      verse: 3844,
      juz: 23,
      surah: 37,
    },
    {
      number: 57,
      image: "",
      text: "And if not (for the) Grace (of) my Lord certainly, I (would) have been among those brought (57)",
      transliteration: "walawlā niʿ'matu rabbī lakuntu mina l-muḥ'ḍarīna ",
      verse: 3845,
      juz: 23,
      surah: 37,
    },
    {
      number: 58,
      image: "",
      text: "Then are not we (to) die (58)",
      transliteration: "afamā naḥnu bimayyitīna ",
      verse: 3846,
      juz: 23,
      surah: 37,
    },
    {
      number: 59,
      image: "",
      text: "Except our death the first and not we will be punished (59)",
      transliteration: "illā mawtatanā l-ūlā wamā naḥnu bimuʿadhabīna ",
      verse: 3847,
      juz: 23,
      surah: 37,
    },
    {
      number: 60,
      image: "",
      text: "Indeed this surely (is) the attainment great (60)",
      transliteration: "inna hādhā lahuwa l-fawzu l-ʿaẓīmu ",
      verse: 3848,
      juz: 23,
      surah: 37,
    },
    {
      number: 61,
      image: "",
      text: "For (the) like (of) this let work the workers (61)",
      transliteration: "limith'li hādhā falyaʿmali l-ʿāmilūna ",
      verse: 3849,
      juz: 23,
      surah: 37,
    },
    {
      number: 62,
      image: "",
      text: "Is that better (as) hospitality or (the) tree (of) Zaqqum (62)",
      transliteration: "adhālika khayrun nuzulan am shajaratu l-zaqūmi ",
      verse: 3850,
      juz: 23,
      surah: 37,
    },
    {
      number: 63,
      image: "",
      text: "Indeed, We [We] have made it a trial for the wrongdoers (63)",
      transliteration: "innā jaʿalnāhā fit'natan lilẓẓālimīna ",
      verse: 3851,
      juz: 23,
      surah: 37,
    },
    {
      number: 64,
      image: "",
      text: "Indeed, it (is) a tree that grows in (the) bottom (of) the Hellfire (64)",
      transliteration: "innahā shajaratun takhruju fī aṣli l-jaḥīmi ",
      verse: 3852,
      juz: 23,
      surah: 37,
    },
    {
      number: 65,
      image: "",
      text: "Its emerging fruit (is) as if it (was) heads (of) the devils (65)",
      transliteration: "ṭalʿuhā ka-annahu ruūsu l-shayāṭīni ",
      verse: 3853,
      juz: 23,
      surah: 37,
    },
    {
      number: 66,
      image: "",
      text: "And indeed, they (will) surely eat from it and fill with it (their) bellies (66)",
      transliteration: "fa-innahum laākilūna min'hā famāliūna min'hā l-buṭūna ",
      verse: 3854,
      juz: 23,
      surah: 37,
    },
    {
      number: 67,
      image: "",
      text: "Then indeed for them in it (is) a mixture of boiling water (67)",
      transliteration: "thumma inna lahum ʿalayhā lashawban min ḥamīmin ",
      verse: 3855,
      juz: 23,
      surah: 37,
    },
    {
      number: 68,
      image: "",
      text: "Then indeed their return (will) surely be to the Hellfire (68)",
      transliteration: "thumma inna marjiʿahum la-ilā l-jaḥīmi ",
      verse: 3856,
      juz: 23,
      surah: 37,
    },
    {
      number: 69,
      image: "",
      text: "Indeed, they found their fathers astray (69)",
      transliteration: "innahum alfaw ābāahum ḍāllīna ",
      verse: 3857,
      juz: 23,
      surah: 37,
    },
    {
      number: 70,
      image: "",
      text: "So they on their footsteps they hastened (70)",
      transliteration: "fahum ʿalā āthārihim yuh'raʿūna ",
      verse: 3858,
      juz: 23,
      surah: 37,
    },
    {
      number: 71,
      image: "",
      text: "And verily went astray before them most (of) the former (people) (71)",
      transliteration: "walaqad ḍalla qablahum aktharu l-awalīna ",
      verse: 3859,
      juz: 23,
      surah: 37,
    },
    {
      number: 72,
      image: "",
      text: "And verily We sent among them warners (72)",
      transliteration: "walaqad arsalnā fīhim mundhirīna ",
      verse: 3860,
      juz: 23,
      surah: 37,
    },
    {
      number: 73,
      image: "",
      text: "Then see how was (the) end (of) those who were warned (73)",
      transliteration: "fa-unẓur kayfa kāna ʿāqibatu l-mundharīna ",
      verse: 3861,
      juz: 23,
      surah: 37,
    },
    {
      number: 74,
      image: "",
      text: "Except (the) slaves (of) Allah the chosen ones (74)",
      transliteration: "illā ʿibāda l-lahi l-mukh'laṣīna ",
      verse: 3862,
      juz: 23,
      surah: 37,
    },
    {
      number: 75,
      image: "",
      text: "And verily called Us Nuh and Best (are We as) Responders (75)",
      transliteration: "walaqad nādānā nūḥun falaniʿ'ma l-mujībūna ",
      verse: 3863,
      juz: 23,
      surah: 37,
    },
    {
      number: 76,
      image: "",
      text: "And We saved him and his family from the distress the great (76)",
      transliteration: "wanajjaynāhu wa-ahlahu mina l-karbi l-ʿaẓīmi ",
      verse: 3864,
      juz: 23,
      surah: 37,
    },
    {
      number: 77,
      image: "",
      text: "And We made his offspring [they] the survivors (77)",
      transliteration: "wajaʿalnā dhurriyyatahu humu l-bāqīna ",
      verse: 3865,
      juz: 23,
      surah: 37,
    },
    {
      number: 78,
      image: "",
      text: "And We left for him among the later generations (78)",
      transliteration: "wataraknā ʿalayhi fī l-ākhirīna ",
      verse: 3866,
      juz: 23,
      surah: 37,
    },
    {
      number: 79,
      image: "",
      text: "Peace be upon Nuh among the worlds (79)",
      transliteration: "salāmun ʿalā nūḥin fī l-ʿālamīna ",
      verse: 3867,
      juz: 23,
      surah: 37,
    },
    {
      number: 80,
      image: "",
      text: "Indeed, We thus [We] reward the good-doers (80)",
      transliteration: "innā kadhālika najzī l-muḥ'sinīna ",
      verse: 3868,
      juz: 23,
      surah: 37,
    },
    {
      number: 81,
      image: "",
      text: "Indeed, he (was) of Our slaves believing (81)",
      transliteration: "innahu min ʿibādinā l-mu'minīna ",
      verse: 3869,
      juz: 23,
      surah: 37,
    },
    {
      number: 82,
      image: "",
      text: "Then We drowned the others (82)",
      transliteration: "thumma aghraqnā l-ākharīna ",
      verse: 3870,
      juz: 23,
      surah: 37,
    },
    {
      number: 83,
      image: "",
      text: "And indeed among his kind (was) surely Ibrahim (83)",
      transliteration: "wa-inna min shīʿatihi la-ib'rāhīma ",
      verse: 3871,
      juz: 23,
      surah: 37,
    },
    {
      number: 84,
      image: "",
      text: "When he came (to) his Lord with a heart sound (84)",
      transliteration: "idh jāa rabbahu biqalbin salīmin ",
      verse: 3872,
      juz: 23,
      surah: 37,
    },
    {
      number: 85,
      image: "",
      text: "When he said to his father and his people What is it you worship (85)",
      transliteration: "idh qāla li-abīhi waqawmihi mādhā taʿbudūna ",
      verse: 3873,
      juz: 23,
      surah: 37,
    },
    {
      number: 86,
      image: "",
      text: "Is it falsehood  gods other than Allah  (that) you desire (86)",
      transliteration: "a-if'kan ālihatan dūna l-lahi turīdūna ",
      verse: 3874,
      juz: 23,
      surah: 37,
    },
    {
      number: 87,
      image: "",
      text: "Then what (do) you think about (the) Lord (of) the worlds (87)",
      transliteration: "famā ẓannukum birabbi l-ʿālamīna ",
      verse: 3875,
      juz: 23,
      surah: 37,
    },
    {
      number: 88,
      image: "",
      text: "Then he glanced a glance at the stars (88)",
      transliteration: "fanaẓara naẓratan fī l-nujūmi ",
      verse: 3876,
      juz: 23,
      surah: 37,
    },
    {
      number: 89,
      image: "",
      text: "And he said Indeed, I am sick (89)",
      transliteration: "faqāla innī saqīmun ",
      verse: 3877,
      juz: 23,
      surah: 37,
    },
    {
      number: 90,
      image: "",
      text: "So they turned away from him departing (90)",
      transliteration: "fatawallaw ʿanhu mud'birīna ",
      verse: 3878,
      juz: 23,
      surah: 37,
    },
    {
      number: 91,
      image: "",
      text: "Then he turned to their gods and said Do not you eat (91)",
      transliteration: "farāgha ilā ālihatihim faqāla alā takulūna ",
      verse: 3879,
      juz: 23,
      surah: 37,
    },
    {
      number: 92,
      image: "",
      text: "What (is) for you not you speak (92)",
      transliteration: "mā lakum lā tanṭiqūna ",
      verse: 3880,
      juz: 23,
      surah: 37,
    },
    {
      number: 93,
      image: "",
      text: "Then he turned upon them striking with the right hand (93)",
      transliteration: "farāgha ʿalayhim ḍarban bil-yamīni ",
      verse: 3881,
      juz: 23,
      surah: 37,
    },
    {
      number: 94,
      image: "",
      text: "Then they advanced towards him hastening (94)",
      transliteration: "fa-aqbalū ilayhi yaziffūna ",
      verse: 3882,
      juz: 23,
      surah: 37,
    },
    {
      number: 95,
      image: "",
      text: "He said Do you worship what you carve (95)",
      transliteration: "qāla ataʿbudūna mā tanḥitūna ",
      verse: 3883,
      juz: 23,
      surah: 37,
    },
    {
      number: 96,
      image: "",
      text: "While Allah created you and what you make (96)",
      transliteration: "wal-lahu khalaqakum wamā taʿmalūna ",
      verse: 3884,
      juz: 23,
      surah: 37,
    },
    {
      number: 97,
      image: "",
      text: "They said Build for him a structure and throw him into the blazing Fire (97)",
      transliteration: "qālū ib'nū lahu bun'yānan fa-alqūhu fī l-jaḥīmi ",
      verse: 3885,
      juz: 23,
      surah: 37,
    },
    {
      number: 98,
      image: "",
      text: "And they intended for him a plot but We made them the lowest (98)",
      transliteration: "fa-arādū bihi kaydan fajaʿalnāhumu l-asfalīna ",
      verse: 3886,
      juz: 23,
      surah: 37,
    },
    {
      number: 99,
      image: "",
      text: "And he said Indeed, I am going to my Lord He will guide me (99)",
      transliteration: "waqāla innī dhāhibun ilā rabbī sayahdīni ",
      verse: 3887,
      juz: 23,
      surah: 37,
    },
    {
      number: 100,
      image: "",
      text: "My Lord grant me of the righteous (100)",
      transliteration: "rabbi hab lī mina l-ṣāliḥīna ",
      verse: 3888,
      juz: 23,
      surah: 37,
    },
    {
      number: 101,
      image: "",
      text: "So We gave him the glad tidings of a boy forbearing (101)",
      transliteration: "fabasharnāhu bighulāmin ḥalīmin ",
      verse: 3889,
      juz: 23,
      surah: 37,
    },
    {
      number: 102,
      image: "",
      text: "Then when he reached the (age of) working with him the (age of) working with him he said O my son Indeed, I have seen in the dream that I am sacrificing you so look what you see He said O my father Do what you are commanded You will find me if Allah wills Allah wills of the patient ones (102)",
      transliteration:
        "falammā balagha maʿahu l-saʿya qāla yābunayya innī arā fī l-manāmi annī adhbaḥuka fa-unẓur mādhā tarā qāla yāabati if'ʿal mā tu'maru satajidunī in shāa l-lahu mina l-ṣābirīna ",
      verse: 3890,
      juz: 23,
      surah: 37,
    },
    {
      number: 103,
      image: "",
      text: "Then when both of them had submitted and he put him down upon his forehead (103)",
      transliteration: "falammā aslamā watallahu lil'jabīni ",
      verse: 3891,
      juz: 23,
      surah: 37,
    },
    {
      number: 104,
      image: "",
      text: "And We called out to him that O Ibrahim (104)",
      transliteration: "wanādaynāhu an yāib'rāhīmu ",
      verse: 3892,
      juz: 23,
      surah: 37,
    },
    {
      number: 105,
      image: "",
      text: "Verily you have fulfilled the vision Indeed, We thus [We] reward the good-doers (105)",
      transliteration: "qad ṣaddaqta l-ru'yā innā kadhālika najzī l-muḥ'sinīna ",
      verse: 3893,
      juz: 23,
      surah: 37,
    },
    {
      number: 106,
      image: "",
      text: "Indeed this (was) surely [it] the trial clear (106)",
      transliteration: "inna hādhā lahuwa l-balāu l-mubīnu ",
      verse: 3894,
      juz: 23,
      surah: 37,
    },
    {
      number: 107,
      image: "",
      text: "And We ransomed him with a sacrifice great (107)",
      transliteration: "wafadaynāhu bidhib'ḥin ʿaẓīmin ",
      verse: 3895,
      juz: 23,
      surah: 37,
    },
    {
      number: 108,
      image: "",
      text: "And We left for him among the later generations (108)",
      transliteration: "wataraknā ʿalayhi fī l-ākhirīna ",
      verse: 3896,
      juz: 23,
      surah: 37,
    },
    {
      number: 109,
      image: "",
      text: "Peace be on Ibrahim (109)",
      transliteration: "salāmun ʿalā ib'rāhīma ",
      verse: 3897,
      juz: 23,
      surah: 37,
    },
    {
      number: 110,
      image: "",
      text: "Thus We reward the good-doers (110)",
      transliteration: "kadhālika najzī l-muḥ'sinīna ",
      verse: 3898,
      juz: 23,
      surah: 37,
    },
    {
      number: 111,
      image: "",
      text: "Indeed, he (was) of Our slaves believing (111)",
      transliteration: "innahu min ʿibādinā l-mu'minīna ",
      verse: 3899,
      juz: 23,
      surah: 37,
    },
    {
      number: 112,
      image: "",
      text: "And We gave him glad tidings of Isaac a Prophet among the righteous (112)",
      transliteration: "wabasharnāhu bi-is'ḥāqa nabiyyan mina l-ṣāliḥīna ",
      verse: 3900,
      juz: 23,
      surah: 37,
    },
    {
      number: 113,
      image: "",
      text: "And We blessed him and [on] Isaac And of their offspring (are) good-doers and unjust to himself clear (113)",
      transliteration:
        "wabāraknā ʿalayhi waʿalā is'ḥāqa wamin dhurriyyatihimā muḥ'sinun waẓālimun linafsihi mubīnun ",
      verse: 3901,
      juz: 23,
      surah: 37,
    },
    {
      number: 114,
      image: "",
      text: "And verily We conferred Favor upon Musa and Harun (114)",
      transliteration: "walaqad manannā ʿalā mūsā wahārūna ",
      verse: 3902,
      juz: 23,
      surah: 37,
    },
    {
      number: 115,
      image: "",
      text: "And We saved both of them and their people from the distress the great (115)",
      transliteration: "wanajjaynāhumā waqawmahumā mina l-karbi l-ʿaẓīmi ",
      verse: 3903,
      juz: 23,
      surah: 37,
    },
    {
      number: 116,
      image: "",
      text: "And We helped them so they became so they became the victors (116)",
      transliteration: "wanaṣarnāhum fakānū humu l-ghālibīna ",
      verse: 3904,
      juz: 23,
      surah: 37,
    },
    {
      number: 117,
      image: "",
      text: "And We gave both of them the Book the clear (117)",
      transliteration: "waātaynāhumā l-kitāba l-mus'tabīna ",
      verse: 3905,
      juz: 23,
      surah: 37,
    },
    {
      number: 118,
      image: "",
      text: "And We guided both of them (to) the Path the Straight (118)",
      transliteration: "wahadaynāhumā l-ṣirāṭa l-mus'taqīma ",
      verse: 3906,
      juz: 23,
      surah: 37,
    },
    {
      number: 119,
      image: "",
      text: "And We left for both of them among the later generations (119)",
      transliteration: "wataraknā ʿalayhimā fī l-ākhirīna ",
      verse: 3907,
      juz: 23,
      surah: 37,
    },
    {
      number: 120,
      image: "",
      text: "Peace be upon Musa and Harun (120)",
      transliteration: "salāmun ʿalā mūsā wahārūna ",
      verse: 3908,
      juz: 23,
      surah: 37,
    },
    {
      number: 121,
      image: "",
      text: "Indeed, We thus reward the good-doers (121)",
      transliteration: "innā kadhālika najzī l-muḥ'sinīna ",
      verse: 3909,
      juz: 23,
      surah: 37,
    },
    {
      number: 122,
      image: "",
      text: "Indeed, both of them (were) of Our slaves believing (122)",
      transliteration: "innahumā min ʿibādinā l-mu'minīna ",
      verse: 3910,
      juz: 23,
      surah: 37,
    },
    {
      number: 123,
      image: "",
      text: "And indeed Elijah (was) surely of the Messengers (123)",
      transliteration: "wa-inna il'yāsa lamina l-mur'salīna ",
      verse: 3911,
      juz: 23,
      surah: 37,
    },
    {
      number: 124,
      image: "",
      text: "When he said to his people Will not you fear (124)",
      transliteration: "idh qāla liqawmihi alā tattaqūna ",
      verse: 3912,
      juz: 23,
      surah: 37,
    },
    {
      number: 125,
      image: "",
      text: "Do you call Baal and you forsake (the) Best (of) Creators  (125)",
      transliteration: "atadʿūna baʿlan watadharūna aḥsana l-khāliqīna ",
      verse: 3913,
      juz: 23,
      surah: 37,
    },
    {
      number: 126,
      image: "",
      text: "Allah your Lord and (the) Lord (of) your forefathers (of) your forefathers (126)",
      transliteration: "al-laha rabbakum warabba ābāikumu l-awalīna ",
      verse: 3914,
      juz: 23,
      surah: 37,
    },
    {
      number: 127,
      image: "",
      text: "But they denied him so indeed, they (will) surely be brought (127)",
      transliteration: "fakadhabūhu fa-innahum lamuḥ'ḍarūna ",
      verse: 3915,
      juz: 23,
      surah: 37,
    },
    {
      number: 128,
      image: "",
      text: "Except (the) slaves (of) Allah the chosen ones (128)",
      transliteration: "illā ʿibāda l-lahi l-mukh'laṣīna ",
      verse: 3916,
      juz: 23,
      surah: 37,
    },
    {
      number: 129,
      image: "",
      text: "And We left for him among the later generations (129)",
      transliteration: "wataraknā ʿalayhi fī l-ākhirīna ",
      verse: 3917,
      juz: 23,
      surah: 37,
    },
    {
      number: 130,
      image: "",
      text: "Peace be upon Elijah (130)",
      transliteration: "salāmun ʿalā il yāsīna ",
      verse: 3918,
      juz: 23,
      surah: 37,
    },
    {
      number: 131,
      image: "",
      text: "Indeed, We thus reward the good-doers (131)",
      transliteration: "innā kadhālika najzī l-muḥ'sinīna ",
      verse: 3919,
      juz: 23,
      surah: 37,
    },
    {
      number: 132,
      image: "",
      text: "Indeed, he (was) of Our slaves believing (132)",
      transliteration: "innahu min ʿibādinā l-mu'minīna ",
      verse: 3920,
      juz: 23,
      surah: 37,
    },
    {
      number: 133,
      image: "",
      text: "And indeed Lut (was) of the Messengers (133)",
      transliteration: "wa-inna lūṭan lamina l-mur'salīna ",
      verse: 3921,
      juz: 23,
      surah: 37,
    },
    {
      number: 134,
      image: "",
      text: "When We saved him and his family all (134)",
      transliteration: "idh najjaynāhu wa-ahlahu ajmaʿīna ",
      verse: 3922,
      juz: 23,
      surah: 37,
    },
    {
      number: 135,
      image: "",
      text: "Except an old woman (was) among those who remained behind (135)",
      transliteration: "illā ʿajūzan fī l-ghābirīna ",
      verse: 3923,
      juz: 23,
      surah: 37,
    },
    {
      number: 136,
      image: "",
      text: "Then We destroyed the others (136)",
      transliteration: "thumma dammarnā l-ākharīna ",
      verse: 3924,
      juz: 23,
      surah: 37,
    },
    {
      number: 137,
      image: "",
      text: "And indeed, you surely pass by them (in the) morning (137)",
      transliteration: "wa-innakum latamurrūna ʿalayhim muṣ'biḥīna ",
      verse: 3925,
      juz: 23,
      surah: 37,
    },
    {
      number: 138,
      image: "",
      text: "And at night Then will not you use reason (138)",
      transliteration: "wabi-al-layli afalā taʿqilūna ",
      verse: 3926,
      juz: 23,
      surah: 37,
    },
    {
      number: 139,
      image: "",
      text: "And indeed Yunus (was) surely of the Messengers (139)",
      transliteration: "wa-inna yūnusa lamina l-mur'salīna ",
      verse: 3927,
      juz: 23,
      surah: 37,
    },
    {
      number: 140,
      image: "",
      text: "When he ran away to the ship laden (140)",
      transliteration: "idh abaqa ilā l-ful'ki l-mashḥūni ",
      verse: 3928,
      juz: 23,
      surah: 37,
    },
    {
      number: 141,
      image: "",
      text: "Then he drew lots and was of the losers (141)",
      transliteration: "fasāhama fakāna mina l-mud'ḥaḍīna ",
      verse: 3929,
      juz: 23,
      surah: 37,
    },
    {
      number: 142,
      image: "",
      text: "Then swallowed him the fish while he (was) blameworthy (142)",
      transliteration: "fal-taqamahu l-ḥūtu wahuwa mulīmun ",
      verse: 3930,
      juz: 23,
      surah: 37,
    },
    {
      number: 143,
      image: "",
      text: "And if not that he was of those who glorify (143)",
      transliteration: "falawlā annahu kāna mina l-musabiḥīna ",
      verse: 3931,
      juz: 23,
      surah: 37,
    },
    {
      number: 144,
      image: "",
      text: "Certainly, he (would have) remained in its belly until the Day they are resurrected (144)",
      transliteration: "lalabitha fī baṭnihi ilā yawmi yub'ʿathūna ",
      verse: 3932,
      juz: 23,
      surah: 37,
    },
    {
      number: 145,
      image: "",
      text: "But We cast him onto the open shore while he (was) ill (145)",
      transliteration: "fanabadhnāhu bil-ʿarāi wahuwa saqīmun ",
      verse: 3933,
      juz: 23,
      surah: 37,
    },
    {
      number: 146,
      image: "",
      text: "And We caused to grow over him a plant of gourd (146)",
      transliteration: "wa-anbatnā ʿalayhi shajaratan min yaqṭīnin ",
      verse: 3934,
      juz: 23,
      surah: 37,
    },
    {
      number: 147,
      image: "",
      text: "And We sent him to a hundred thousand or more (147)",
      transliteration: "wa-arsalnāhu ilā mi-ati alfin aw yazīdūna ",
      verse: 3935,
      juz: 23,
      surah: 37,
    },
    {
      number: 148,
      image: "",
      text: "And they believed so We gave them enjoyment for a while (148)",
      transliteration: "faāmanū famattaʿnāhum ilā ḥīnin ",
      verse: 3936,
      juz: 23,
      surah: 37,
    },
    {
      number: 149,
      image: "",
      text: "Then ask them Does your Lord (have) daughters while for them (are) sons (149)",
      transliteration: "fa-is'taftihim alirabbika l-banātu walahumu l-banūna ",
      verse: 3937,
      juz: 23,
      surah: 37,
    },
    {
      number: 150,
      image: "",
      text: "Or did We create the Angels females while they (were) witnesses (150)",
      transliteration: "am khalaqnā l-malāikata ināthan wahum shāhidūna ",
      verse: 3938,
      juz: 23,
      surah: 37,
    },
    {
      number: 151,
      image: "",
      text: "No doubt indeed, they of their falsehood [they] say (151)",
      transliteration: "alā innahum min if'kihim layaqūlūna ",
      verse: 3939,
      juz: 23,
      surah: 37,
    },
    {
      number: 152,
      image: "",
      text: "Allah has begotten Allah has begotten and indeed, they surely (are) liars (152)",
      transliteration: "walada l-lahu wa-innahum lakādhibūna ",
      verse: 3940,
      juz: 23,
      surah: 37,
    },
    {
      number: 153,
      image: "",
      text: "Has He chosen [the] daughters over sons (153)",
      transliteration: "aṣṭafā l-banāti ʿalā l-banīna ",
      verse: 3941,
      juz: 23,
      surah: 37,
    },
    {
      number: 154,
      image: "",
      text: "What is with you What is with you How you judge (154)",
      transliteration: "mā lakum kayfa taḥkumūna ",
      verse: 3942,
      juz: 23,
      surah: 37,
    },
    {
      number: 155,
      image: "",
      text: "Then will not you pay heed (155)",
      transliteration: "afalā tadhakkarūna ",
      verse: 3943,
      juz: 23,
      surah: 37,
    },
    {
      number: 156,
      image: "",
      text: "Or (is) for you an authority clear (156)",
      transliteration: "am lakum sul'ṭānun mubīnun ",
      verse: 3944,
      juz: 23,
      surah: 37,
    },
    {
      number: 157,
      image: "",
      text: "Then bring your book if you are truthful (157)",
      transliteration: "fatū bikitābikum in kuntum ṣādiqīna ",
      verse: 3945,
      juz: 23,
      surah: 37,
    },
    {
      number: 158,
      image: "",
      text: "And they have made between Him and between the jinn a relationship but certainly know the jinn that they (will) surely be brought (158)",
      transliteration:
        "wajaʿalū baynahu wabayna l-jinati nasaban walaqad ʿalimati l-jinatu innahum lamuḥ'ḍarūna ",
      verse: 3946,
      juz: 23,
      surah: 37,
    },
    {
      number: 159,
      image: "",
      text: "Glory be (to) Allah above what they attribute (159)",
      transliteration: "sub'ḥāna l-lahi ʿammā yaṣifūna ",
      verse: 3947,
      juz: 23,
      surah: 37,
    },
    {
      number: 160,
      image: "",
      text: "Except (the) slaves (of) Allah the chosen (160)",
      transliteration: "illā ʿibāda l-lahi l-mukh'laṣīna ",
      verse: 3948,
      juz: 23,
      surah: 37,
    },
    {
      number: 161,
      image: "",
      text: "So indeed, you and what you worship (161)",
      transliteration: "fa-innakum wamā taʿbudūna ",
      verse: 3949,
      juz: 23,
      surah: 37,
    },
    {
      number: 162,
      image: "",
      text: "Not you from Him can tempt away (anyone) (162)",
      transliteration: "mā antum ʿalayhi bifātinīna ",
      verse: 3950,
      juz: 23,
      surah: 37,
    },
    {
      number: 163,
      image: "",
      text: "Except who he (is) to burn (in) the Hellfire (163)",
      transliteration: "illā man huwa ṣāli l-jaḥīmi ",
      verse: 3951,
      juz: 23,
      surah: 37,
    },
    {
      number: 164,
      image: "",
      text: "And not among us except for him (is) a position known (164)",
      transliteration: "wamā minnā illā lahu maqāmun maʿlūmun ",
      verse: 3952,
      juz: 23,
      surah: 37,
    },
    {
      number: 165,
      image: "",
      text: "And indeed, we surely, [we] stand in rows (165)",
      transliteration: "wa-innā lanaḥnu l-ṣāfūna ",
      verse: 3953,
      juz: 23,
      surah: 37,
    },
    {
      number: 166,
      image: "",
      text: "And indeed, we surely, [we] glorify (Allah) (166)",
      transliteration: "wa-innā lanaḥnu l-musabiḥūna ",
      verse: 3954,
      juz: 23,
      surah: 37,
    },
    {
      number: 167,
      image: "",
      text: "And indeed they used to say (167)",
      transliteration: "wa-in kānū layaqūlūna ",
      verse: 3955,
      juz: 23,
      surah: 37,
    },
    {
      number: 168,
      image: "",
      text: "If that we had a reminder from the former (people) (168)",
      transliteration: "law anna ʿindanā dhik'ran mina l-awalīna ",
      verse: 3956,
      juz: 23,
      surah: 37,
    },
    {
      number: 169,
      image: "",
      text: "Certainly, we (would) have been slaves (of) Allah the chosen (169)",
      transliteration: "lakunnā ʿibāda l-lahi l-mukh'laṣīna ",
      verse: 3957,
      juz: 23,
      surah: 37,
    },
    {
      number: 170,
      image: "",
      text: "But they disbelieved in it so soon they will know (170)",
      transliteration: "fakafarū bihi fasawfa yaʿlamūna ",
      verse: 3958,
      juz: 23,
      surah: 37,
    },
    {
      number: 171,
      image: "",
      text: "And verily has preceded Our Word for Our slaves the Messengers (171)",
      transliteration: "walaqad sabaqat kalimatunā liʿibādinā l-mur'salīna ",
      verse: 3959,
      juz: 23,
      surah: 37,
    },
    {
      number: 172,
      image: "",
      text: "Indeed they surely they (would be) the victorious (172)",
      transliteration: "innahum lahumu l-manṣūrūna ",
      verse: 3960,
      juz: 23,
      surah: 37,
    },
    {
      number: 173,
      image: "",
      text: "And indeed Our host surely, they (will be) those who overcome (173)",
      transliteration: "wa-inna jundanā lahumu l-ghālibūna ",
      verse: 3961,
      juz: 23,
      surah: 37,
    },
    {
      number: 174,
      image: "",
      text: "So turn away from them until a time (174)",
      transliteration: "fatawalla ʿanhum ḥattā ḥīnin ",
      verse: 3962,
      juz: 23,
      surah: 37,
    },
    {
      number: 175,
      image: "",
      text: "And see them so soon they will see (175)",
      transliteration: "wa-abṣir'hum fasawfa yub'ṣirūna ",
      verse: 3963,
      juz: 23,
      surah: 37,
    },
    {
      number: 176,
      image: "",
      text: "Then is (it) for Our punishment they hasten (176)",
      transliteration: "afabiʿadhābinā yastaʿjilūna ",
      verse: 3964,
      juz: 23,
      surah: 37,
    },
    {
      number: 177,
      image: "",
      text: "But when it descends in their territory then evil (will be) (the) morning (for) those who were warned (177)",
      transliteration: "fa-idhā nazala bisāḥatihim fasāa ṣabāḥu l-mundharīna ",
      verse: 3965,
      juz: 23,
      surah: 37,
    },
    {
      number: 178,
      image: "",
      text: "So turn away from them for a time (178)",
      transliteration: "watawalla ʿanhum ḥattā ḥīnin ",
      verse: 3966,
      juz: 23,
      surah: 37,
    },
    {
      number: 179,
      image: "",
      text: "And see so soon they will see (179)",
      transliteration: "wa-abṣir fasawfa yub'ṣirūna ",
      verse: 3967,
      juz: 23,
      surah: 37,
    },
    {
      number: 180,
      image: "",
      text: "Glory (be to) your Lord (the) Lord (of) Honor above what they attribute (180)",
      transliteration: "sub'ḥāna rabbika rabbi l-ʿizati ʿammā yaṣifūna ",
      verse: 3968,
      juz: 23,
      surah: 37,
    },
    {
      number: 181,
      image: "",
      text: "And peace be upon the Messengers (181)",
      transliteration: "wasalāmun ʿalā l-mur'salīna ",
      verse: 3969,
      juz: 23,
      surah: 37,
    },
    {
      number: 182,
      image: "",
      text: "And all praise (be) to Allah (the) Lord (of) the worlds (182)",
      transliteration: "wal-ḥamdu lillahi rabbi l-ʿālamīna ",
      verse: 3970,
      juz: 23,
      surah: 37,
    },
  ],
};
