import { Surah } from "../types/islam.js";

export const sajdah: Surah = {
  name: "As-Sajdah",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "Alif Lam Meem (1)",
      transliteration: "alif-lam-meem ",
      verse: 3504,
      juz: 21,
      surah: 32,
    },
    {
      number: 2,
      image: "",
      text: "(The) revelation (of) the Book (there is) no doubt about it from (the) Lord (of) the worlds (2)",
      transliteration: "tanzīlu l-kitābi lā rayba fīhi min rabbi l-ʿālamīna ",
      verse: 3505,
      juz: 21,
      surah: 32,
    },
    {
      number: 3,
      image: "",
      text: "Or (do) they say He invented it Nay it (is) the truth from your Lord that you may warn a people not has come to them any warner before you before you so that they may be guided (3)",
      transliteration:
        "am yaqūlūna if'tarāhu bal huwa l-ḥaqu min rabbika litundhira qawman mā atāhum min nadhīrin min qablika laʿallahum yahtadūna ",
      verse: 3506,
      juz: 21,
      surah: 32,
    },
    {
      number: 4,
      image: "",
      text: "Allah (is) the One Who created the heavens and the earth and whatever (is) between them in six periods Then established Himself on the Throne Not for you besides Him besides Him any protector and not any intercessor Then will not you take heed (4)",
      transliteration:
        "al-lahu alladhī khalaqa l-samāwāti wal-arḍa wamā baynahumā fī sittati ayyāmin thumma is'tawā ʿalā l-ʿarshi mā lakum min dūnihi min waliyyin walā shafīʿin afalā tatadhakkarūna ",
      verse: 3507,
      juz: 21,
      surah: 32,
    },
    {
      number: 5,
      image: "",
      text: "He regulates the affair of the heaven to the earth then it will ascend to Him in a Day (the) measure of which is (the) measure of which is a thousand years of what you count (5)",
      transliteration:
        "yudabbiru l-amra mina l-samāi ilā l-arḍi thumma yaʿruju ilayhi fī yawmin kāna miq'dāruhu alfa sanatin mimmā taʿuddūna ",
      verse: 3508,
      juz: 21,
      surah: 32,
    },
    {
      number: 6,
      image: "",
      text: "That (is the) Knower (of) the hidden and the witnessed the All-Mighty the Most Merciful (6)",
      transliteration: "dhālika ʿālimu l-ghaybi wal-shahādati l-ʿazīzu l-raḥīmu ",
      verse: 3509,
      juz: 21,
      surah: 32,
    },
    {
      number: 7,
      image: "",
      text: "The One Who made good every thing He created and He began (the) creation (of) man from clay (7)",
      transliteration:
        "alladhī aḥsana kulla shayin khalaqahu wabada-a khalqa l-insāni min ṭīnin ",
      verse: 3510,
      juz: 21,
      surah: 32,
    },
    {
      number: 8,
      image: "",
      text: "Then He made his progeny from an extract of water despised (8)",
      transliteration: "thumma jaʿala naslahu min sulālatin min māin mahīnin ",
      verse: 3511,
      juz: 21,
      surah: 32,
    },
    {
      number: 9,
      image: "",
      text: "Then He fashioned him and breathed into him from His spirit and made for you the hearing and the sight and feelings little [what] thanks you give (9)",
      transliteration:
        "thumma sawwāhu wanafakha fīhi min rūḥihi wajaʿala lakumu l-samʿa wal-abṣāra wal-afidata qalīlan mā tashkurūna ",
      verse: 3512,
      juz: 21,
      surah: 32,
    },
    {
      number: 10,
      image: "",
      text: "And they say Is (it) when we are lost in the earth will we certainly be in a creation new Nay they in (the) meeting (of) their Lord (are) disbelievers (10)",
      transliteration:
        "waqālū a-idhā ḍalalnā fī l-arḍi a-innā lafī khalqin jadīdin bal hum biliqāi rabbihim kāfirūna ",
      verse: 3513,
      juz: 21,
      surah: 32,
    },
    {
      number: 11,
      image: "",
      text: "Say Will take your soul (the) Angel (of) the death the one who has been put in charge of you Then to your Lord you will be returned (11)",
      transliteration:
        "qul yatawaffākum malaku l-mawti alladhī wukkila bikum thumma ilā rabbikum tur'jaʿūna ",
      verse: 3514,
      juz: 21,
      surah: 32,
    },
    {
      number: 12,
      image: "",
      text: "And if you (could) see when the criminals (will) hang their heads before their Lord Our Lord we have seen and we have heard so return us we will do righteous (deeds) Indeed, we (are now) certain (12)",
      transliteration:
        "walaw tarā idhi l-muj'rimūna nākisū ruūsihim ʿinda rabbihim rabbanā abṣarnā wasamiʿ'nā fa-ir'jiʿ'nā naʿmal ṣāliḥan innā mūqinūna ",
      verse: 3515,
      juz: 21,
      surah: 32,
    },
    {
      number: 13,
      image: "",
      text: "And if We (had) willed surely We (would) have given every soul its guidance but (is) true the Word from Me that I will surely fill Hell with the jinn and the men together (13)",
      transliteration:
        "walaw shi'nā laātaynā kulla nafsin hudāhā walākin ḥaqqa l-qawlu minnī la-amla-anna jahannama mina l-jinati wal-nāsi ajmaʿīna ",
      verse: 3516,
      juz: 21,
      surah: 32,
    },
    {
      number: 14,
      image: "",
      text: "So taste because you forgot (the) meeting (of) this Day of yours (of) this Day of yours Indeed, We have forgotten you And taste (the) punishment (of) eternity for what you used (to) do (14)",
      transliteration:
        "fadhūqū bimā nasītum liqāa yawmikum hādhā innā nasīnākum wadhūqū ʿadhāba l-khul'di bimā kuntum taʿmalūna ",
      verse: 3517,
      juz: 21,
      surah: 32,
    },
    {
      number: 15,
      image: "",
      text: "Only believe in Our Verses those who when they are reminded of them fall down prostrating and glorify (the) praises (of) their Lord and they are not arrogant are not arrogant (15)",
      transliteration:
        "innamā yu'minu biāyātinā alladhīna idhā dhukkirū bihā kharrū sujjadan wasabbaḥū biḥamdi rabbihim wahum lā yastakbirūna ",
      verse: 3518,
      juz: 21,
      surah: 32,
    },
    {
      number: 16,
      image: "",
      text: "Forsake their sides from (their) beds they call their Lord (in) fear and hope and out of what We have provided them they spend (16)",
      transliteration:
        "tatajāfā junūbuhum ʿani l-maḍājiʿi yadʿūna rabbahum khawfan waṭamaʿan wamimmā razaqnāhum yunfiqūna ",
      verse: 3519,
      juz: 21,
      surah: 32,
    },
    {
      number: 17,
      image: "",
      text: "And not knows a soul what is hidden for them of (the) comfort (for) the eyes (as) a reward for what they used (to) do (17)",
      transliteration:
        "falā taʿlamu nafsun mā ukh'fiya lahum min qurrati aʿyunin jazāan bimā kānū yaʿmalūna ",
      verse: 3520,
      juz: 21,
      surah: 32,
    },
    {
      number: 18,
      image: "",
      text: "Then is one who is a believer like (him) who is defiantly disobedient Not they are equal (18)",
      transliteration: "afaman kāna mu'minan kaman kāna fāsiqan lā yastawūna ",
      verse: 3521,
      juz: 21,
      surah: 32,
    },
    {
      number: 19,
      image: "",
      text: "As for those who believe and do righteous deeds then for them (are) Gardens (of) Refuge (as) hospitality for what they used (to) do (19)",
      transliteration:
        "ammā alladhīna āmanū waʿamilū l-ṣāliḥāti falahum jannātu l-mawā nuzulan bimā kānū yaʿmalūna ",
      verse: 3522,
      juz: 21,
      surah: 32,
    },
    {
      number: 20,
      image: "",
      text: "But as for those who are defiantly disobedient then their refuge (is) the Fire Every time they wish to come out from it they (will) be returned in it and it (will) be said to them Taste (the) punishment (of) the Fire which you used (to) [in it] deny (20)",
      transliteration:
        "wa-ammā alladhīna fasaqū famawāhumu l-nāru kullamā arādū an yakhrujū min'hā uʿīdū fīhā waqīla lahum dhūqū ʿadhāba l-nāri alladhī kuntum bihi tukadhibūna ",
      verse: 3523,
      juz: 21,
      surah: 32,
    },
    {
      number: 21,
      image: "",
      text: "And surely, We will let them taste of the punishment the nearer before the punishment the greater so that they may return (21)",
      transliteration:
        "walanudhīqannahum mina l-ʿadhābi l-adnā dūna l-ʿadhābi l-akbari laʿallahum yarjiʿūna ",
      verse: 3524,
      juz: 21,
      surah: 32,
    },
    {
      number: 22,
      image: "",
      text: "And who (is) more unjust than (he) who is reminded of (the) Verses (of) his Lord then he turns away from them Indeed, We from the criminals (will) take retribution (22)",
      transliteration:
        "waman aẓlamu mimman dhukkira biāyāti rabbihi thumma aʿraḍa ʿanhā innā mina l-muj'rimīna muntaqimūna ",
      verse: 3525,
      juz: 21,
      surah: 32,
    },
    {
      number: 23,
      image: "",
      text: "And certainly We gave Musa the Scripture so (do) not be in doubt about receiving it And We made it a guide for the Children of Israel for the Children of Israel (23)",
      transliteration:
        "walaqad ātaynā mūsā l-kitāba falā takun fī mir'yatin min liqāihi wajaʿalnāhu hudan libanī is'rāīla ",
      verse: 3526,
      juz: 21,
      surah: 32,
    },
    {
      number: 24,
      image: "",
      text: "And We made from them leaders guiding by Our Command when they were patient and they were of Our Verses certain (24)",
      transliteration:
        "wajaʿalnā min'hum a-immatan yahdūna bi-amrinā lammā ṣabarū wakānū biāyātinā yūqinūna ",
      verse: 3527,
      juz: 21,
      surah: 32,
    },
    {
      number: 25,
      image: "",
      text: "Indeed your Lord [He] will judge between them (on the) Day (of) Resurrection in what they used (to) [in it] differ (25)",
      transliteration:
        "inna rabbaka huwa yafṣilu baynahum yawma l-qiyāmati fīmā kānū fīhi yakhtalifūna ",
      verse: 3528,
      juz: 21,
      surah: 32,
    },
    {
      number: 26,
      image: "",
      text: "Does it not guide [for] them (that) how many We have destroyed before them before them of the generations they walk about in their dwellings Indeed in that surely, are Signs Then do not they hear (26)",
      transliteration:
        "awalam yahdi lahum kam ahlaknā min qablihim mina l-qurūni yamshūna fī masākinihim inna fī dhālika laāyātin afalā yasmaʿūna ",
      verse: 3529,
      juz: 21,
      surah: 32,
    },
    {
      number: 27,
      image: "",
      text: "Do not they see that We drive water to the land [the] barren then We bring forth thereby crops eat from it their cattle and they themselves Then do not they see (27)",
      transliteration:
        "awalam yaraw annā nasūqu l-māa ilā l-arḍi l-juruzi fanukh'riju bihi zarʿan takulu min'hu anʿāmuhum wa-anfusuhum afalā yub'ṣirūna ",
      verse: 3530,
      juz: 21,
      surah: 32,
    },
    {
      number: 28,
      image: "",
      text: "And they say When (will be) this decision if you are truthful (28)",
      transliteration: "wayaqūlūna matā hādhā l-fatḥu in kuntum ṣādiqīna ",
      verse: 3531,
      juz: 21,
      surah: 32,
    },
    {
      number: 29,
      image: "",
      text: "Say (On the) Day (of) the Decision not will benefit those who disbelieve their belief and not they will be granted respite (29)",
      transliteration:
        "qul yawma l-fatḥi lā yanfaʿu alladhīna kafarū īmānuhum walā hum yunẓarūna ",
      verse: 3532,
      juz: 21,
      surah: 32,
    },
    {
      number: 30,
      image: "",
      text: "So turn away from them and wait Indeed, they (are) waiting (30)",
      transliteration: "fa-aʿriḍ ʿanhum wa-intaẓir innahum muntaẓirūna ",
      verse: 3533,
      juz: 21,
      surah: 32,
    },
  ],
};
