import { Surah } from "../types/islam.js";

export const shams: Surah = {
  name: "Ash-Shams",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "By the sun and its brightness (1)",
      transliteration: "wal-shamsi waḍuḥāhā ",
      verse: 6044,
      juz: 30,
      surah: 91,
    },
    {
      number: 2,
      image: "",
      text: "And the moon when it follows it (2)",
      transliteration: "wal-qamari idhā talāhā ",
      verse: 6045,
      juz: 30,
      surah: 91,
    },
    {
      number: 3,
      image: "",
      text: "And the day when it displays it (3)",
      transliteration: "wal-nahāri idhā jallāhā ",
      verse: 6046,
      juz: 30,
      surah: 91,
    },
    {
      number: 4,
      image: "",
      text: "And the night when it covers it (4)",
      transliteration: "wa-al-layli idhā yaghshāhā ",
      verse: 6047,
      juz: 30,
      surah: 91,
    },
    {
      number: 5,
      image: "",
      text: "And the heaven and (He) Who constructed it (5)",
      transliteration: "wal-samāi wamā banāhā ",
      verse: 6048,
      juz: 30,
      surah: 91,
    },
    {
      number: 6,
      image: "",
      text: "And the earth and by (He) Who spread it (6)",
      transliteration: "wal-arḍi wamā ṭaḥāhā ",
      verse: 6049,
      juz: 30,
      surah: 91,
    },
    {
      number: 7,
      image: "",
      text: "And (the) soul and (He) Who proportioned it (7)",
      transliteration: "wanafsin wamā sawwāhā ",
      verse: 6050,
      juz: 30,
      surah: 91,
    },
    {
      number: 8,
      image: "",
      text: "And He inspired it (to distinguish) its wickedness and its righteousness (8)",
      transliteration: "fa-alhamahā fujūrahā wataqwāhā ",
      verse: 6051,
      juz: 30,
      surah: 91,
    },
    {
      number: 9,
      image: "",
      text: "Indeed he succeeds who purifies it (9)",
      transliteration: "qad aflaḥa man zakkāhā ",
      verse: 6052,
      juz: 30,
      surah: 91,
    },
    {
      number: 10,
      image: "",
      text: "And indeed he fails who buries it (10)",
      transliteration: "waqad khāba man dassāhā ",
      verse: 6053,
      juz: 30,
      surah: 91,
    },
    {
      number: 11,
      image: "",
      text: "Denied Thamud by their transgression (11)",
      transliteration: "kadhabat thamūdu biṭaghwāhā ",
      verse: 6054,
      juz: 30,
      surah: 91,
    },
    {
      number: 12,
      image: "",
      text: "When (was) sent forth (the) most wicked of them (12)",
      transliteration: "idhi inbaʿatha ashqāhā ",
      verse: 6055,
      juz: 30,
      surah: 91,
    },
    {
      number: 13,
      image: "",
      text: "But said to them (the) Messenger (of) Allah (It is the) she-camel (of) Allah and her drink (13)",
      transliteration: "faqāla lahum rasūlu l-lahi nāqata l-lahi wasuq'yāhā ",
      verse: 6056,
      juz: 30,
      surah: 91,
    },
    {
      number: 14,
      image: "",
      text: "But they denied him and they hamstrung her So destroyed them their Lord for their sin and leveled them (14)",
      transliteration:
        "fakadhabūhu faʿaqarūhā fadamdama ʿalayhim rabbuhum bidhanbihim fasawwāhā ",
      verse: 6057,
      juz: 30,
      surah: 91,
    },
    {
      number: 15,
      image: "",
      text: "And not He fears its consequences (15)",
      transliteration: "walā yakhāfu ʿuq'bāhā ",
      verse: 6058,
      juz: 30,
      surah: 91,
    },
  ],
};
