import { Surah } from "../types/islam.js";

export const sharh: Surah = {
  name: "Ash-Sharh",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "Have not We expanded for you your breast (1)",
      transliteration: "alam nashraḥ laka ṣadraka ",
      verse: 6091,
      juz: 30,
      surah: 94,
    },
    {
      number: 2,
      image: "",
      text: "And We removed from you your burden (2)",
      transliteration: "wawaḍaʿnā ʿanka wiz'raka ",
      verse: 6092,
      juz: 30,
      surah: 94,
    },
    {
      number: 3,
      image: "",
      text: "Which weighed upon your back (3)",
      transliteration: "alladhī anqaḍa ẓahraka ",
      verse: 6093,
      juz: 30,
      surah: 94,
    },
    {
      number: 4,
      image: "",
      text: "And We raised high for you your reputation (4)",
      transliteration: "warafaʿnā laka dhik'raka ",
      verse: 6094,
      juz: 30,
      surah: 94,
    },
    {
      number: 5,
      image: "",
      text: "So indeed with the hardship (is) ease (5)",
      transliteration: "fa-inna maʿa l-ʿus'ri yus'ran ",
      verse: 6095,
      juz: 30,
      surah: 94,
    },
    {
      number: 6,
      image: "",
      text: "Indeed with the hardship (is) ease (6)",
      transliteration: "inna maʿa l-ʿus'ri yus'ran ",
      verse: 6096,
      juz: 30,
      surah: 94,
    },
    {
      number: 7,
      image: "",
      text: "So when you have finished then labor hard (7)",
      transliteration: "fa-idhā faraghta fa-inṣab ",
      verse: 6097,
      juz: 30,
      surah: 94,
    },
    {
      number: 8,
      image: "",
      text: "And to your Lord turn your attention (8)",
      transliteration: "wa-ilā rabbika fa-ir'ghab ",
      verse: 6098,
      juz: 30,
      surah: 94,
    },
  ],
};
