import { Surah } from "../types/islam.js";

export const shuara: Surah = {
  name: "Ash-Shu'ara",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "Ta Seem Meem (1)",
      transliteration: "tta-seen-meem ",
      verse: 2933,
      juz: 19,
      surah: 26,
    },
    {
      number: 2,
      image: "",
      text: "These (are the) Verses (of) the Book clear (2)",
      transliteration: "til'ka āyātu l-kitābi l-mubīni ",
      verse: 2934,
      juz: 19,
      surah: 26,
    },
    {
      number: 3,
      image: "",
      text: "Perhaps you (would) kill yourself that not they become believers (3)",
      transliteration: "laʿallaka bākhiʿun nafsaka allā yakūnū mu'minīna ",
      verse: 2935,
      juz: 19,
      surah: 26,
    },
    {
      number: 4,
      image: "",
      text: "If We will We can send down to them from the sky a Sign so would bend their necks to it (in) humility (4)",
      transliteration:
        "in nasha nunazzil ʿalayhim mina l-samāi āyatan faẓallat aʿnāquhum lahā khāḍiʿīna ",
      verse: 2936,
      juz: 19,
      surah: 26,
    },
    {
      number: 5,
      image: "",
      text: "And (does) not come to them any reminder from the Most Gracious new but they from it turn away (5)",
      transliteration:
        "wamā yatīhim min dhik'rin mina l-raḥmāni muḥ'dathin illā kānū ʿanhu muʿ'riḍīna ",
      verse: 2937,
      juz: 19,
      surah: 26,
    },
    {
      number: 6,
      image: "",
      text: "So verily they have denied then will come to them the news (of) what they used at it (to) mock (6)",
      transliteration:
        "faqad kadhabū fasayatīhim anbāu mā kānū bihi yastahziūna ",
      verse: 2938,
      juz: 19,
      surah: 26,
    },
    {
      number: 7,
      image: "",
      text: "Do not they see at the earth  how many We produced in it of every kind noble (7)",
      transliteration:
        "awalam yaraw ilā l-arḍi kam anbatnā fīhā min kulli zawjin karīmin ",
      verse: 2939,
      juz: 19,
      surah: 26,
    },
    {
      number: 8,
      image: "",
      text: "Indeed in that surely (is) a sign but not are most of them believers (8)",
      transliteration: "inna fī dhālika laāyatan wamā kāna aktharuhum mu'minīna ",
      verse: 2940,
      juz: 19,
      surah: 26,
    },
    {
      number: 9,
      image: "",
      text: "And indeed your Lord surely, He (is) the All-Mighty the Most Merciful (9)",
      transliteration: "wa-inna rabbaka lahuwa l-ʿazīzu l-raḥīmu ",
      verse: 2941,
      juz: 19,
      surah: 26,
    },
    {
      number: 10,
      image: "",
      text: "And when your Lord called your Lord called Musa [that] Go (to) the people (who are) wrongdoers (10)",
      transliteration: "wa-idh nādā rabbuka mūsā ani i'ti l-qawma l-ẓālimīna ",
      verse: 2942,
      juz: 19,
      surah: 26,
    },
    {
      number: 11,
      image: "",
      text: "(The) people (of) Firaun Will not they fear (11)",
      transliteration: "qawma fir'ʿawna alā yattaqūna ",
      verse: 2943,
      juz: 19,
      surah: 26,
    },
    {
      number: 12,
      image: "",
      text: "He said My Lord Indeed, I [I] fear that they will deny me (12)",
      transliteration: "qāla rabbi innī akhāfu an yukadhibūni ",
      verse: 2944,
      juz: 19,
      surah: 26,
    },
    {
      number: 13,
      image: "",
      text: "And straitens my breast and not expresses well my tongue so send for Harun (13)",
      transliteration:
        "wayaḍīqu ṣadrī walā yanṭaliqu lisānī fa-arsil ilā hārūna ",
      verse: 2945,
      juz: 19,
      surah: 26,
    },
    {
      number: 14,
      image: "",
      text: "And they have against me a crime so I fear that they will kill me (14)",
      transliteration: "walahum ʿalayya dhanbun fa-akhāfu an yaqtulūni ",
      verse: 2946,
      juz: 19,
      surah: 26,
    },
    {
      number: 15,
      image: "",
      text: "He said Nay go both of you with Our Signs Indeed, We (are) with you listening (15)",
      transliteration:
        "qāla kallā fa-idh'habā biāyātinā innā maʿakum mus'tamiʿūna ",
      verse: 2947,
      juz: 19,
      surah: 26,
    },
    {
      number: 16,
      image: "",
      text: "So go both of you (to) Firaun and say 'Indeed, we (are the) Messenger (of the) Lord (of) the worlds (16)",
      transliteration: "fatiyā fir'ʿawna faqūlā innā rasūlu rabbi l-ʿālamīna ",
      verse: 2948,
      juz: 19,
      surah: 26,
    },
    {
      number: 17,
      image: "",
      text: "[That] send with us (the) Children of Israel.' (the) Children of Israel.' (17)",
      transliteration: "an arsil maʿanā banī is'rāīla ",
      verse: 2949,
      juz: 19,
      surah: 26,
    },
    {
      number: 18,
      image: "",
      text: "He said Did not we bring you up among us (as) a child and you remained among us of your life years (18)",
      transliteration:
        "qāla alam nurabbika fīnā walīdan walabith'ta fīnā min ʿumurika sinīna ",
      verse: 2950,
      juz: 19,
      surah: 26,
    },
    {
      number: 19,
      image: "",
      text: "And you did your deed which you did and you (were) of the ungrateful (19)",
      transliteration:
        "wafaʿalta faʿlataka allatī faʿalta wa-anta mina l-kāfirīna ",
      verse: 2951,
      juz: 19,
      surah: 26,
    },
    {
      number: 20,
      image: "",
      text: "He said I did it when I (was) of those who are astray (20)",
      transliteration: "qāla faʿaltuhā idhan wa-anā mina l-ḍālīna ",
      verse: 2952,
      juz: 19,
      surah: 26,
    },
    {
      number: 21,
      image: "",
      text: "So I fled from you when I feared you But granted to me my Lord judgment and made me of the Messengers (21)",
      transliteration:
        "fafarartu minkum lammā khif'tukum fawahaba lī rabbī ḥuk'man wajaʿalanī mina l-mur'salīna ",
      verse: 2953,
      juz: 19,
      surah: 26,
    },
    {
      number: 22,
      image: "",
      text: "And this (is the) favor with which you reproach [on] me that you have enslaved (the) Children of Israel (the) Children of Israel (22)",
      transliteration:
        "watil'ka niʿ'matun tamunnuhā ʿalayya an ʿabbadtta banī is'rāīla ",
      verse: 2954,
      juz: 19,
      surah: 26,
    },
    {
      number: 23,
      image: "",
      text: "Firaun said Firaun said And what (is the) Lord (of) the worlds (23)",
      transliteration: "qāla fir'ʿawnu wamā rabbu l-ʿālamīna ",
      verse: 2955,
      juz: 19,
      surah: 26,
    },
    {
      number: 24,
      image: "",
      text: "He said Lord (of) the heavens and the earth and whatever (is) between them if you (should) be convinced (24)",
      transliteration:
        "qāla rabbu l-samāwāti wal-arḍi wamā baynahumā in kuntum mūqinīna ",
      verse: 2956,
      juz: 19,
      surah: 26,
    },
    {
      number: 25,
      image: "",
      text: "He said to those around him Do not you hear (25)",
      transliteration: "qāla liman ḥawlahu alā tastamiʿūna ",
      verse: 2957,
      juz: 19,
      surah: 26,
    },
    {
      number: 26,
      image: "",
      text: "He said Your Lord and (the) Lord (of) your forefathers (of) your forefathers (26)",
      transliteration: "qāla rabbukum warabbu ābāikumu l-awalīna ",
      verse: 2958,
      juz: 19,
      surah: 26,
    },
    {
      number: 27,
      image: "",
      text: "He said Indeed your Messenger who has been sent to you (is) surely mad (27)",
      transliteration: "qāla inna rasūlakumu alladhī ur'sila ilaykum lamajnūnun ",
      verse: 2959,
      juz: 19,
      surah: 26,
    },
    {
      number: 28,
      image: "",
      text: "He said Lord (of) the east and the west and whatever (is) between them if you were (to) reason (28)",
      transliteration:
        "qāla rabbu l-mashriqi wal-maghribi wamā baynahumā in kuntum taʿqilūna ",
      verse: 2960,
      juz: 19,
      surah: 26,
    },
    {
      number: 29,
      image: "",
      text: "He said If you take a god other than me I will surely make you among those imprisoned (29)",
      transliteration:
        "qāla la-ini ittakhadhta ilāhan ghayrī la-ajʿalannaka mina l-masjūnīna ",
      verse: 2961,
      juz: 19,
      surah: 26,
    },
    {
      number: 30,
      image: "",
      text: "He said Even if I bring you something manifest (30)",
      transliteration: "qāla awalaw ji'tuka bishayin mubīnin ",
      verse: 2962,
      juz: 19,
      surah: 26,
    },
    {
      number: 31,
      image: "",
      text: "He said Then bring it if you are of the truthful (31)",
      transliteration: "qāla fati bihi in kunta mina l-ṣādiqīna ",
      verse: 2963,
      juz: 19,
      surah: 26,
    },
    {
      number: 32,
      image: "",
      text: "So he threw his staff and behold It (was) a serpent manifest (32)",
      transliteration: "fa-alqā ʿaṣāhu fa-idhā hiya thuʿ'bānun mubīnun ",
      verse: 2964,
      juz: 19,
      surah: 26,
    },
    {
      number: 33,
      image: "",
      text: "And he drew out his hand and behold It (was) white for the observers (33)",
      transliteration: "wanazaʿa yadahu fa-idhā hiya bayḍāu lilnnāẓirīna ",
      verse: 2965,
      juz: 19,
      surah: 26,
    },
    {
      number: 34,
      image: "",
      text: "He said to the chiefs around him Indeed this (is) surely a magician learned (34)",
      transliteration: "qāla lil'mala-i ḥawlahu inna hādhā lasāḥirun ʿalīmun ",
      verse: 2966,
      juz: 19,
      surah: 26,
    },
    {
      number: 35,
      image: "",
      text: "He wants to drive you out from your land by his magic so what (do) you advise (35)",
      transliteration:
        "yurīdu an yukh'rijakum min arḍikum bisiḥ'rihi famādhā tamurūna ",
      verse: 2967,
      juz: 19,
      surah: 26,
    },
    {
      number: 36,
      image: "",
      text: "They said Postpone him and his brother and send in the cities gatherers  (36)",
      transliteration: "qālū arjih wa-akhāhu wa-ib'ʿath fī l-madāini ḥāshirīna ",
      verse: 2968,
      juz: 19,
      surah: 26,
    },
    {
      number: 37,
      image: "",
      text: "They (will) bring to you every magician learned (37)",
      transliteration: "yatūka bikulli saḥḥārin ʿalīmin ",
      verse: 2969,
      juz: 19,
      surah: 26,
    },
    {
      number: 38,
      image: "",
      text: "So were assembled the magicians for (the) appointment (on) a day well-known (38)",
      transliteration: "fajumiʿa l-saḥaratu limīqāti yawmin maʿlūmin ",
      verse: 2970,
      juz: 19,
      surah: 26,
    },
    {
      number: 39,
      image: "",
      text: "And it was said to the people Will you assemble (39)",
      transliteration: "waqīla lilnnāsi hal antum muj'tamiʿūna ",
      verse: 2971,
      juz: 19,
      surah: 26,
    },
    {
      number: 40,
      image: "",
      text: "That we may follow the magicians if they are they are the victorious (40)",
      transliteration: "laʿallanā nattabiʿu l-saḥarata in kānū humu l-ghālibīna ",
      verse: 2972,
      juz: 19,
      surah: 26,
    },
    {
      number: 41,
      image: "",
      text: "So when came the magicians they said to Firaun Is there for us a reward if we are we are the victorious (41)",
      transliteration:
        "falammā jāa l-saḥaratu qālū lifir'ʿawna a-inna lanā la-ajran in kunnā naḥnu l-ghālibīna ",
      verse: 2973,
      juz: 19,
      surah: 26,
    },
    {
      number: 42,
      image: "",
      text: "He said Yes and indeed you then surely (will be) of the ones who are brought near (42)",
      transliteration: "qāla naʿam wa-innakum idhan lamina l-muqarabīna ",
      verse: 2974,
      juz: 19,
      surah: 26,
    },
    {
      number: 43,
      image: "",
      text: "Said to them Musa Throw what you (are) going to throw (43)",
      transliteration: "qāla lahum mūsā alqū mā antum mul'qūna ",
      verse: 2975,
      juz: 19,
      surah: 26,
    },
    {
      number: 44,
      image: "",
      text: "So they threw their ropes and their staffs and said By the might (of) Firaun indeed, we surely, we (are) the victorious (44)",
      transliteration:
        "fa-alqaw ḥibālahum waʿiṣiyyahum waqālū biʿizzati fir'ʿawna innā lanaḥnu l-ghālibūna ",
      verse: 2976,
      juz: 19,
      surah: 26,
    },
    {
      number: 45,
      image: "",
      text: "Then threw Musa his staff and behold It swallowed what they falsified (45)",
      transliteration: "fa-alqā mūsā ʿaṣāhu fa-idhā hiya talqafu mā yafikūna ",
      verse: 2977,
      juz: 19,
      surah: 26,
    },
    {
      number: 46,
      image: "",
      text: "Then fell down the magicians prostrate (46)",
      transliteration: "fa-ul'qiya l-saḥaratu sājidīna ",
      verse: 2978,
      juz: 19,
      surah: 26,
    },
    {
      number: 47,
      image: "",
      text: "They said We believe in (the) Lord (of) the worlds (47)",
      transliteration: "qālū āmannā birabbi l-ʿālamīna ",
      verse: 2979,
      juz: 19,
      surah: 26,
    },
    {
      number: 48,
      image: "",
      text: "Lord (of) Musa and Harun (48)",
      transliteration: "rabbi mūsā wahārūna ",
      verse: 2980,
      juz: 19,
      surah: 26,
    },
    {
      number: 49,
      image: "",
      text: "He said You believed in him before [that] I gave permission to you Indeed, he (is) surely your chief who has taught you the magic so surely soon you will know I will surely cut off your hands and your feet of opposite sides and I will surely crucify you all (49)",
      transliteration:
        "qāla āmantum lahu qabla an ādhana lakum innahu lakabīrukumu alladhī ʿallamakumu l-siḥ'ra falasawfa taʿlamūna la-uqaṭṭiʿanna aydiyakum wa-arjulakum min khilāfin wala-uṣallibannakum ajmaʿīna ",
      verse: 2981,
      juz: 19,
      surah: 26,
    },
    {
      number: 50,
      image: "",
      text: "They said No harm Indeed, we to our Lord (will) return (50)",
      transliteration: "qālū lā ḍayra innā ilā rabbinā munqalibūna ",
      verse: 2982,
      juz: 19,
      surah: 26,
    },
    {
      number: 51,
      image: "",
      text: "Indeed, we hope that will forgive us our Lord our sins because we are (the) first (of) the believers (51)",
      transliteration:
        "innā naṭmaʿu an yaghfira lanā rabbunā khaṭāyānā an kunnā awwala l-mu'minīna ",
      verse: 2983,
      juz: 19,
      surah: 26,
    },
    {
      number: 52,
      image: "",
      text: "And We inspired to Musa [that] Travel by night with My slaves indeed, you (will be) followed (52)",
      transliteration:
        "wa-awḥaynā ilā mūsā an asri biʿibādī innakum muttabaʿūna ",
      verse: 2984,
      juz: 19,
      surah: 26,
    },
    {
      number: 53,
      image: "",
      text: "Then sent Firaun in the cities gatherers (53)",
      transliteration: "fa-arsala fir'ʿawnu fī l-madāini ḥāshirīna ",
      verse: 2985,
      juz: 19,
      surah: 26,
    },
    {
      number: 54,
      image: "",
      text: "Indeed these (are) certainly a band small (54)",
      transliteration: "inna hāulāi lashir'dhimatun qalīlūna ",
      verse: 2986,
      juz: 19,
      surah: 26,
    },
    {
      number: 55,
      image: "",
      text: "And indeed, they [to] us (are) surely enraging (55)",
      transliteration: "wa-innahum lanā laghāiẓūna ",
      verse: 2987,
      juz: 19,
      surah: 26,
    },
    {
      number: 56,
      image: "",
      text: "And indeed, we (are) surely a multitude forewarned (56)",
      transliteration: "wa-innā lajamīʿun ḥādhirūna ",
      verse: 2988,
      juz: 19,
      surah: 26,
    },
    {
      number: 57,
      image: "",
      text: "So We expelled them from gardens and springs (57)",
      transliteration: "fa-akhrajnāhum min jannātin waʿuyūnin ",
      verse: 2989,
      juz: 19,
      surah: 26,
    },
    {
      number: 58,
      image: "",
      text: "And treasures and a place honorable (58)",
      transliteration: "wakunūzin wamaqāmin karīmin ",
      verse: 2990,
      juz: 19,
      surah: 26,
    },
    {
      number: 59,
      image: "",
      text: "Thus And We caused to inherit them (the) Children of Israel (the) Children of Israel (59)",
      transliteration: "kadhālika wa-awrathnāhā banī is'rāīla ",
      verse: 2991,
      juz: 19,
      surah: 26,
    },
    {
      number: 60,
      image: "",
      text: "So they followed them (at) sunrise (60)",
      transliteration: "fa-atbaʿūhum mush'riqīna ",
      verse: 2992,
      juz: 19,
      surah: 26,
    },
    {
      number: 61,
      image: "",
      text: "Then when saw each other the two hosts said (the) companions (of) Musa Indeed, we (are) surely to be overtaken (61)",
      transliteration:
        "falammā tarāā l-jamʿāni qāla aṣḥābu mūsā innā lamud'rakūna ",
      verse: 2993,
      juz: 19,
      surah: 26,
    },
    {
      number: 62,
      image: "",
      text: "He said Nay indeed with me (is) my Lord He will guide me (62)",
      transliteration: "qāla kallā inna maʿiya rabbī sayahdīni ",
      verse: 2994,
      juz: 19,
      surah: 26,
    },
    {
      number: 63,
      image: "",
      text: "Then We inspired to Musa [that] Strike with your staff the sea So it parted and became each part like the mountain [the] great (63)",
      transliteration:
        "fa-awḥaynā ilā mūsā ani iḍ'rib biʿaṣāka l-baḥra fa-infalaqa fakāna kullu fir'qin kal-ṭawdi l-ʿaẓīmi ",
      verse: 2995,
      juz: 19,
      surah: 26,
    },
    {
      number: 64,
      image: "",
      text: "And We brought near there the others (64)",
      transliteration: "wa-azlafnā thamma l-ākharīna ",
      verse: 2996,
      juz: 19,
      surah: 26,
    },
    {
      number: 65,
      image: "",
      text: "And We saved Musa and who (were) with him all (65)",
      transliteration: "wa-anjaynā mūsā waman maʿahu ajmaʿīna ",
      verse: 2997,
      juz: 19,
      surah: 26,
    },
    {
      number: 66,
      image: "",
      text: "Then We drowned the others (66)",
      transliteration: "thumma aghraqnā l-ākharīna ",
      verse: 2998,
      juz: 19,
      surah: 26,
    },
    {
      number: 67,
      image: "",
      text: "Indeed in that surely (is) a Sign but not are most of them believers (67)",
      transliteration: "inna fī dhālika laāyatan wamā kāna aktharuhum mu'minīna ",
      verse: 2999,
      juz: 19,
      surah: 26,
    },
    {
      number: 68,
      image: "",
      text: "And indeed your Lord surely He (is) the All-Mighty the Most Merciful (68)",
      transliteration: "wa-inna rabbaka lahuwa l-ʿazīzu l-raḥīmu ",
      verse: 3000,
      juz: 19,
      surah: 26,
    },
    {
      number: 69,
      image: "",
      text: "And recite to them (the) news (of) Ibrahim (69)",
      transliteration: "wa-ut'lu ʿalayhim naba-a ib'rāhīma ",
      verse: 3001,
      juz: 19,
      surah: 26,
    },
    {
      number: 70,
      image: "",
      text: "When he said to his father and his people What (do) you worship (70)",
      transliteration: "idh qāla li-abīhi waqawmihi mā taʿbudūna ",
      verse: 3002,
      juz: 19,
      surah: 26,
    },
    {
      number: 71,
      image: "",
      text: "They said We worship idols so we will remain to them devoted (71)",
      transliteration: "qālū naʿbudu aṣnāman fanaẓallu lahā ʿākifīna ",
      verse: 3003,
      juz: 19,
      surah: 26,
    },
    {
      number: 72,
      image: "",
      text: "He said Do they hear you when you call (72)",
      transliteration: "qāla hal yasmaʿūnakum idh tadʿūna ",
      verse: 3004,
      juz: 19,
      surah: 26,
    },
    {
      number: 73,
      image: "",
      text: "Or (do) they benefit you or they harm (you) (73)",
      transliteration: "aw yanfaʿūnakum aw yaḍurrūna ",
      verse: 3005,
      juz: 19,
      surah: 26,
    },
    {
      number: 74,
      image: "",
      text: "They said Nay but we found our forefathers like that  doing (74)",
      transliteration: "qālū bal wajadnā ābāanā kadhālika yafʿalūna ",
      verse: 3006,
      juz: 19,
      surah: 26,
    },
    {
      number: 75,
      image: "",
      text: "He said Do you see what you have been worshipping (75)",
      transliteration: "qāla afara-aytum mā kuntum taʿbudūna ",
      verse: 3007,
      juz: 19,
      surah: 26,
    },
    {
      number: 76,
      image: "",
      text: "You and your forefathers and your forefathers (76)",
      transliteration: "antum waābāukumu l-aqdamūna ",
      verse: 3008,
      juz: 19,
      surah: 26,
    },
    {
      number: 77,
      image: "",
      text: "Indeed, they (are) enemies to me except (the) Lord (of) the worlds (77)",
      transliteration: "fa-innahum ʿaduwwun lī illā rabba l-ʿālamīna ",
      verse: 3009,
      juz: 19,
      surah: 26,
    },
    {
      number: 78,
      image: "",
      text: "The One Who created me and He guides me (78)",
      transliteration: "alladhī khalaqanī fahuwa yahdīni ",
      verse: 3010,
      juz: 19,
      surah: 26,
    },
    {
      number: 79,
      image: "",
      text: "And the One Who [He] gives me food and gives me drink (79)",
      transliteration: "wa-alladhī huwa yuṭ'ʿimunī wayasqīni ",
      verse: 3011,
      juz: 19,
      surah: 26,
    },
    {
      number: 80,
      image: "",
      text: "And when I am ill then He cures me (80)",
      transliteration: "wa-idhā mariḍ'tu fahuwa yashfīni ",
      verse: 3012,
      juz: 19,
      surah: 26,
    },
    {
      number: 81,
      image: "",
      text: "And the One Who will cause me to die then he will give me life (81)",
      transliteration: "wa-alladhī yumītunī thumma yuḥ'yīni ",
      verse: 3013,
      juz: 19,
      surah: 26,
    },
    {
      number: 82,
      image: "",
      text: "And the One Who  I hope that He will forgive for me my faults (on the) Day (of) the Judgment (82)",
      transliteration: "wa-alladhī aṭmaʿu an yaghfira lī khaṭīatī yawma l-dīni ",
      verse: 3014,
      juz: 19,
      surah: 26,
    },
    {
      number: 83,
      image: "",
      text: "My Lord Grant [for] me wisdom and join me with the righteous (83)",
      transliteration: "rabbi hab lī ḥuk'man wa-alḥiq'nī bil-ṣāliḥīna ",
      verse: 3015,
      juz: 19,
      surah: 26,
    },
    {
      number: 84,
      image: "",
      text: "And grant [for] me a mention (of) honor among the later (generations) (84)",
      transliteration: "wa-ij'ʿal lī lisāna ṣid'qin fī l-ākhirīna ",
      verse: 3016,
      juz: 19,
      surah: 26,
    },
    {
      number: 85,
      image: "",
      text: "And make me of (the) inheritors (of) Garden(s) (of) Delight (85)",
      transliteration: "wa-ij'ʿalnī min warathati jannati l-naʿīmi ",
      verse: 3017,
      juz: 19,
      surah: 26,
    },
    {
      number: 86,
      image: "",
      text: "And forgive my father Indeed, he is of those astray (86)",
      transliteration: "wa-igh'fir li-abī innahu kāna mina l-ḍālīna ",
      verse: 3018,
      juz: 19,
      surah: 26,
    },
    {
      number: 87,
      image: "",
      text: "And (do) not disgrace me (on the) Day they are resurrected (87)",
      transliteration: "walā tukh'zinī yawma yub'ʿathūna ",
      verse: 3019,
      juz: 19,
      surah: 26,
    },
    {
      number: 88,
      image: "",
      text: "(The) Day not will benefit wealth and not sons (88)",
      transliteration: "yawma lā yanfaʿu mālun walā banūna ",
      verse: 3020,
      juz: 19,
      surah: 26,
    },
    {
      number: 89,
      image: "",
      text: "Except (he) who comes (to) Allah with a heart sound (89)",
      transliteration: "illā man atā l-laha biqalbin salīmin ",
      verse: 3021,
      juz: 19,
      surah: 26,
    },
    {
      number: 90,
      image: "",
      text: "And (will be) brought near the Paradise for the righteous (90)",
      transliteration: "wa-uz'lifati l-janatu lil'muttaqīna ",
      verse: 3022,
      juz: 19,
      surah: 26,
    },
    {
      number: 91,
      image: "",
      text: "And (will be) made manifest the Hellfire to the deviators (91)",
      transliteration: "waburrizati l-jaḥīmu lil'ghāwīna ",
      verse: 3023,
      juz: 19,
      surah: 26,
    },
    {
      number: 92,
      image: "",
      text: "And it will be said to them Where (is) that you used (to) worship (92)",
      transliteration: "waqīla lahum ayna mā kuntum taʿbudūna ",
      verse: 3024,
      juz: 19,
      surah: 26,
    },
    {
      number: 93,
      image: "",
      text: "Besides Allah Besides Allah Besides Allah Can they help you or help themselves (93)",
      transliteration: "min dūni l-lahi hal yanṣurūnakum aw yantaṣirūna ",
      verse: 3025,
      juz: 19,
      surah: 26,
    },
    {
      number: 94,
      image: "",
      text: "Then they will be overturned into it they and the deviators (94)",
      transliteration: "fakub'kibū fīhā hum wal-ghāwūna ",
      verse: 3026,
      juz: 19,
      surah: 26,
    },
    {
      number: 95,
      image: "",
      text: "And (the) hosts (of) Iblis all together (95)",
      transliteration: "wajunūdu ib'līsa ajmaʿūna ",
      verse: 3027,
      juz: 19,
      surah: 26,
    },
    {
      number: 96,
      image: "",
      text: "They (will) say while they in it (are) disputing (96)",
      transliteration: "qālū wahum fīhā yakhtaṣimūna ",
      verse: 3028,
      juz: 19,
      surah: 26,
    },
    {
      number: 97,
      image: "",
      text: "By Allah indeed we were surely in error clear (97)",
      transliteration: "tal-lahi in kunnā lafī ḍalālin mubīnin ",
      verse: 3029,
      juz: 19,
      surah: 26,
    },
    {
      number: 98,
      image: "",
      text: "When we equated you with (the) Lord (of) the worlds (98)",
      transliteration: "idh nusawwīkum birabbi l-ʿālamīna ",
      verse: 3030,
      juz: 19,
      surah: 26,
    },
    {
      number: 99,
      image: "",
      text: "And not misguided us except the criminals (99)",
      transliteration: "wamā aḍallanā illā l-muj'rimūna ",
      verse: 3031,
      juz: 19,
      surah: 26,
    },
    {
      number: 100,
      image: "",
      text: "So (now) not we have any intercessors (100)",
      transliteration: "famā lanā min shāfiʿīna ",
      verse: 3032,
      juz: 19,
      surah: 26,
    },
    {
      number: 101,
      image: "",
      text: "And not a friend close (101)",
      transliteration: "walā ṣadīqin ḥamīmin ",
      verse: 3033,
      juz: 19,
      surah: 26,
    },
    {
      number: 102,
      image: "",
      text: "Then if that we had a return then we could be of the believers (102)",
      transliteration: "falaw anna lanā karratan fanakūna mina l-mu'minīna ",
      verse: 3034,
      juz: 19,
      surah: 26,
    },
    {
      number: 103,
      image: "",
      text: "Indeed in that surely is a Sign but not are most of them believers (103)",
      transliteration: "inna fī dhālika laāyatan wamā kāna aktharuhum mu'minīna ",
      verse: 3035,
      juz: 19,
      surah: 26,
    },
    {
      number: 104,
      image: "",
      text: "And indeed your Lord surely He (is) the All-Mighty the Most Merciful (104)",
      transliteration: "wa-inna rabbaka lahuwa l-ʿazīzu l-raḥīmu ",
      verse: 3036,
      juz: 19,
      surah: 26,
    },
    {
      number: 105,
      image: "",
      text: "Denied (the) people (of) Nuh the Messengers (105)",
      transliteration: "kadhabat qawmu nūḥin l-mur'salīna ",
      verse: 3037,
      juz: 19,
      surah: 26,
    },
    {
      number: 106,
      image: "",
      text: "When said to them their brother Nuh Will not you fear (Allah) (106)",
      transliteration: "idh qāla lahum akhūhum nūḥun alā tattaqūna ",
      verse: 3038,
      juz: 19,
      surah: 26,
    },
    {
      number: 107,
      image: "",
      text: "Indeed, I am to you a Messenger trustworthy (107)",
      transliteration: "innī lakum rasūlun amīnun ",
      verse: 3039,
      juz: 19,
      surah: 26,
    },
    {
      number: 108,
      image: "",
      text: "So fear Allah and obey me (108)",
      transliteration: "fa-ittaqū l-laha wa-aṭīʿūni ",
      verse: 3040,
      juz: 19,
      surah: 26,
    },
    {
      number: 109,
      image: "",
      text: "And not I ask (of) you for it any payment Not (is) my payment but from (the) Lord (of) the worlds (109)",
      transliteration:
        "wamā asalukum ʿalayhi min ajrin in ajriya illā ʿalā rabbi l-ʿālamīna ",
      verse: 3041,
      juz: 19,
      surah: 26,
    },
    {
      number: 110,
      image: "",
      text: "So fear Allah and obey me (110)",
      transliteration: "fa-ittaqū l-laha wa-aṭīʿūni ",
      verse: 3042,
      juz: 19,
      surah: 26,
    },
    {
      number: 111,
      image: "",
      text: "They said Should we believe in you while followed you the lowest (111)",
      transliteration: "qālū anu'minu laka wa-ittabaʿaka l-ardhalūna ",
      verse: 3043,
      juz: 19,
      surah: 26,
    },
    {
      number: 112,
      image: "",
      text: "He said And what (do) I know of what they used (to) do (112)",
      transliteration: "qāla wamā ʿil'mī bimā kānū yaʿmalūna ",
      verse: 3044,
      juz: 19,
      surah: 26,
    },
    {
      number: 113,
      image: "",
      text: "Verily their account (is) but upon my Lord if you perceive (113)",
      transliteration: "in ḥisābuhum illā ʿalā rabbī law tashʿurūna ",
      verse: 3045,
      juz: 19,
      surah: 26,
    },
    {
      number: 114,
      image: "",
      text: "And not I am the one to drive away the believers (114)",
      transliteration: "wamā anā biṭāridi l-mu'minīna ",
      verse: 3046,
      juz: 19,
      surah: 26,
    },
    {
      number: 115,
      image: "",
      text: "Not I am but a warner clear (115)",
      transliteration: "in anā illā nadhīrun mubīnun ",
      verse: 3047,
      juz: 19,
      surah: 26,
    },
    {
      number: 116,
      image: "",
      text: "They said If not you desist O Nuh Surely you will be of those who are stoned (116)",
      transliteration:
        "qālū la-in lam tantahi yānūḥu latakūnanna mina l-marjūmīna ",
      verse: 3048,
      juz: 19,
      surah: 26,
    },
    {
      number: 117,
      image: "",
      text: "He said My Lord Indeed my people have denied me (117)",
      transliteration: "qāla rabbi inna qawmī kadhabūni ",
      verse: 3049,
      juz: 19,
      surah: 26,
    },
    {
      number: 118,
      image: "",
      text: "So judge between me and between them (with decisive) judgment and save me and who (are) with me of the believers (118)",
      transliteration:
        "fa-if'taḥ baynī wabaynahum fatḥan wanajjinī waman maʿiya mina l-mu'minīna ",
      verse: 3050,
      juz: 19,
      surah: 26,
    },
    {
      number: 119,
      image: "",
      text: "So We saved him and who (were) with him in the ship laden (119)",
      transliteration: "fa-anjaynāhu waman maʿahu fī l-ful'ki l-mashḥūni ",
      verse: 3051,
      juz: 19,
      surah: 26,
    },
    {
      number: 120,
      image: "",
      text: "Then We drowned thereafter the remaining ones (120)",
      transliteration: "thumma aghraqnā baʿdu l-bāqīna ",
      verse: 3052,
      juz: 19,
      surah: 26,
    },
    {
      number: 121,
      image: "",
      text: "Indeed in that surely, (is) a sign but not are most of them believers (121)",
      transliteration: "inna fī dhālika laāyatan wamā kāna aktharuhum mu'minīna ",
      verse: 3053,
      juz: 19,
      surah: 26,
    },
    {
      number: 122,
      image: "",
      text: "And indeed your Lord surely, He (is) the All-Mighty the Most Merciful (122)",
      transliteration: "wa-inna rabbaka lahuwa l-ʿazīzu l-raḥīmu ",
      verse: 3054,
      juz: 19,
      surah: 26,
    },
    {
      number: 123,
      image: "",
      text: "Denied (the people) of Aad the Messengers (123)",
      transliteration: "kadhabat ʿādun l-mur'salīna ",
      verse: 3055,
      juz: 19,
      surah: 26,
    },
    {
      number: 124,
      image: "",
      text: "When said to them their brother Hud Will not you fear (Allah) (124)",
      transliteration: "idh qāla lahum akhūhum hūdun alā tattaqūna ",
      verse: 3056,
      juz: 19,
      surah: 26,
    },
    {
      number: 125,
      image: "",
      text: "Indeed, I am to you a Messenger trustworthy (125)",
      transliteration: "innī lakum rasūlun amīnun ",
      verse: 3057,
      juz: 19,
      surah: 26,
    },
    {
      number: 126,
      image: "",
      text: "So fear Allah and obey me (126)",
      transliteration: "fa-ittaqū l-laha wa-aṭīʿūni ",
      verse: 3058,
      juz: 19,
      surah: 26,
    },
    {
      number: 127,
      image: "",
      text: "And not I ask you for it any payment Not (is) my payment except from (the) Lord (of) the worlds (127)",
      transliteration:
        "wamā asalukum ʿalayhi min ajrin in ajriya illā ʿalā rabbi l-ʿālamīna ",
      verse: 3059,
      juz: 19,
      surah: 26,
    },
    {
      number: 128,
      image: "",
      text: "Do you construct on every elevation a sign amusing yourselves (128)",
      transliteration: "atabnūna bikulli rīʿin āyatan taʿbathūna ",
      verse: 3060,
      juz: 19,
      surah: 26,
    },
    {
      number: 129,
      image: "",
      text: "And take for yourselves strongholds that you may live forever (129)",
      transliteration: "watattakhidhūna maṣāniʿa laʿallakum takhludūna ",
      verse: 3061,
      juz: 19,
      surah: 26,
    },
    {
      number: 130,
      image: "",
      text: "And when you seize you seize (as) tyrants (130)",
      transliteration: "wa-idhā baṭashtum baṭashtum jabbārīna ",
      verse: 3062,
      juz: 19,
      surah: 26,
    },
    {
      number: 131,
      image: "",
      text: "So fear Allah and obey me (131)",
      transliteration: "fa-ittaqū l-laha wa-aṭīʿūni ",
      verse: 3063,
      juz: 19,
      surah: 26,
    },
    {
      number: 132,
      image: "",
      text: "And fear the One Who has aided you with what you know (132)",
      transliteration: "wa-ittaqū alladhī amaddakum bimā taʿlamūna ",
      verse: 3064,
      juz: 19,
      surah: 26,
    },
    {
      number: 133,
      image: "",
      text: "He has aided you with cattle and children (133)",
      transliteration: "amaddakum bi-anʿāmin wabanīna ",
      verse: 3065,
      juz: 19,
      surah: 26,
    },
    {
      number: 134,
      image: "",
      text: "And gardens and springs (134)",
      transliteration: "wajannātin waʿuyūnin ",
      verse: 3066,
      juz: 19,
      surah: 26,
    },
    {
      number: 135,
      image: "",
      text: "Indeed, I [I] fear for you (the) punishment (of) a Day Great (135)",
      transliteration: "innī akhāfu ʿalaykum ʿadhāba yawmin ʿaẓīmin ",
      verse: 3067,
      juz: 19,
      surah: 26,
    },
    {
      number: 136,
      image: "",
      text: "They said (It is) same to us whether you advise or not you are of the advisors (136)",
      transliteration:
        "qālū sawāon ʿalaynā awaʿaẓta am lam takun mina l-wāʿiẓīna ",
      verse: 3068,
      juz: 19,
      surah: 26,
    },
    {
      number: 137,
      image: "",
      text: "Not (is) this but (the) custom (of) the former (people) (137)",
      transliteration: "in hādhā illā khuluqu l-awalīna ",
      verse: 3069,
      juz: 19,
      surah: 26,
    },
    {
      number: 138,
      image: "",
      text: "And not we (are) the ones to be punished (138)",
      transliteration: "wamā naḥnu bimuʿadhabīna ",
      verse: 3070,
      juz: 19,
      surah: 26,
    },
    {
      number: 139,
      image: "",
      text: "So they denied him then We destroyed them Indeed in that surely, is a sign but not are most of them believers (139)",
      transliteration:
        "fakadhabūhu fa-ahlaknāhum inna fī dhālika laāyatan wamā kāna aktharuhum mu'minīna ",
      verse: 3071,
      juz: 19,
      surah: 26,
    },
    {
      number: 140,
      image: "",
      text: "And indeed your Lord surely, He (is) the All-Mighty the Most Merciful (140)",
      transliteration: "wa-inna rabbaka lahuwa l-ʿazīzu l-raḥīmu ",
      verse: 3072,
      juz: 19,
      surah: 26,
    },
    {
      number: 141,
      image: "",
      text: "Denied Thamud the Messengers (141)",
      transliteration: "kadhabat thamūdu l-mur'salīna ",
      verse: 3073,
      juz: 19,
      surah: 26,
    },
    {
      number: 142,
      image: "",
      text: "When said to them their brother Salih Will not you fear (Allah) (142)",
      transliteration: "idh qāla lahum akhūhum ṣāliḥun alā tattaqūna ",
      verse: 3074,
      juz: 19,
      surah: 26,
    },
    {
      number: 143,
      image: "",
      text: "Indeed, I am to you a Messenger trustworthy (143)",
      transliteration: "innī lakum rasūlun amīnun ",
      verse: 3075,
      juz: 19,
      surah: 26,
    },
    {
      number: 144,
      image: "",
      text: "So fear Allah and obey me (144)",
      transliteration: "fa-ittaqū l-laha wa-aṭīʿūni ",
      verse: 3076,
      juz: 19,
      surah: 26,
    },
    {
      number: 145,
      image: "",
      text: "And not I ask you for it any payment Not (is) my payment except from (the) Lord (of) the worlds (145)",
      transliteration:
        "wamā asalukum ʿalayhi min ajrin in ajriya illā ʿalā rabbi l-ʿālamīna ",
      verse: 3077,
      juz: 19,
      surah: 26,
    },
    {
      number: 146,
      image: "",
      text: "Will you be left in what (is) here secure (146)",
      transliteration: "atut'rakūna fī mā hāhunā āminīna ",
      verse: 3078,
      juz: 19,
      surah: 26,
    },
    {
      number: 147,
      image: "",
      text: "In gardens and springs (147)",
      transliteration: "fī jannātin waʿuyūnin ",
      verse: 3079,
      juz: 19,
      surah: 26,
    },
    {
      number: 148,
      image: "",
      text: "And cornfields and date-palms its spadix soft (148)",
      transliteration: "wazurūʿin wanakhlin ṭalʿuhā haḍīmun ",
      verse: 3080,
      juz: 19,
      surah: 26,
    },
    {
      number: 149,
      image: "",
      text: "And you carve of the mountains houses skillfully (149)",
      transliteration: "watanḥitūna mina l-jibāli buyūtan fārihīna ",
      verse: 3081,
      juz: 19,
      surah: 26,
    },
    {
      number: 150,
      image: "",
      text: "So fear Allah and obey me (150)",
      transliteration: "fa-ittaqū l-laha wa-aṭīʿūni ",
      verse: 3082,
      juz: 19,
      surah: 26,
    },
    {
      number: 151,
      image: "",
      text: "And (do) not obey (the) command (of) the transgressors (151)",
      transliteration: "walā tuṭīʿū amra l-mus'rifīna ",
      verse: 3083,
      juz: 19,
      surah: 26,
    },
    {
      number: 152,
      image: "",
      text: "Those who spread corruption in the earth and (do) not reform (152)",
      transliteration: "alladhīna yuf'sidūna fī l-arḍi walā yuṣ'liḥūna ",
      verse: 3084,
      juz: 19,
      surah: 26,
    },
    {
      number: 153,
      image: "",
      text: "They said Only you (are) of those bewitched (153)",
      transliteration: "qālū innamā anta mina l-musaḥarīna ",
      verse: 3085,
      juz: 19,
      surah: 26,
    },
    {
      number: 154,
      image: "",
      text: "Not you (are) except a man like us so bring a sign if you (are) of the truthful (154)",
      transliteration:
        "mā anta illā basharun mith'lunā fati biāyatin in kunta mina l-ṣādiqīna ",
      verse: 3086,
      juz: 19,
      surah: 26,
    },
    {
      number: 155,
      image: "",
      text: "He said This (is) a she-camel For her (is a share of) drink and for you (is a share of) drink (on) a day known (155)",
      transliteration:
        "qāla hādhihi nāqatun lahā shir'bun walakum shir'bu yawmin maʿlūmin ",
      verse: 3087,
      juz: 19,
      surah: 26,
    },
    {
      number: 156,
      image: "",
      text: "And (do) not touch her with harm lest seize you (the) punishment (of) a Day Great (156)",
      transliteration:
        "walā tamassūhā bisūin fayakhudhakum ʿadhābu yawmin ʿaẓīmin ",
      verse: 3088,
      juz: 19,
      surah: 26,
    },
    {
      number: 157,
      image: "",
      text: "But they hamstrung her then they became regretful (157)",
      transliteration: "faʿaqarūhā fa-aṣbaḥū nādimīna ",
      verse: 3089,
      juz: 19,
      surah: 26,
    },
    {
      number: 158,
      image: "",
      text: "So seized them the punishment Indeed in that surely is a sign but not are most of them believers (158)",
      transliteration:
        "fa-akhadhahumu l-ʿadhābu inna fī dhālika laāyatan wamā kāna aktharuhum mu'minīna ",
      verse: 3090,
      juz: 19,
      surah: 26,
    },
    {
      number: 159,
      image: "",
      text: "And indeed your Lord surely He (is) the All-Mighty the Most Merciful (159)",
      transliteration: "wa-inna rabbaka lahuwa l-ʿazīzu l-raḥīmu ",
      verse: 3091,
      juz: 19,
      surah: 26,
    },
    {
      number: 160,
      image: "",
      text: "Denied (the) people (of) Lut the Messengers (160)",
      transliteration: "kadhabat qawmu lūṭin l-mur'salīna ",
      verse: 3092,
      juz: 19,
      surah: 26,
    },
    {
      number: 161,
      image: "",
      text: "When said to them their brother Lut Will not you fear (Allah) (161)",
      transliteration: "idh qāla lahum akhūhum lūṭun alā tattaqūna ",
      verse: 3093,
      juz: 19,
      surah: 26,
    },
    {
      number: 162,
      image: "",
      text: "Indeed, I am to you a Messenger trustworthy (162)",
      transliteration: "innī lakum rasūlun amīnun ",
      verse: 3094,
      juz: 19,
      surah: 26,
    },
    {
      number: 163,
      image: "",
      text: "So fear Allah and obey me (163)",
      transliteration: "fa-ittaqū l-laha wa-aṭīʿūni ",
      verse: 3095,
      juz: 19,
      surah: 26,
    },
    {
      number: 164,
      image: "",
      text: "And not I ask you for it any payment Not (is) my payment except from (the) Lord (of) the worlds (164)",
      transliteration:
        "wamā asalukum ʿalayhi min ajrin in ajriya illā ʿalā rabbi l-ʿālamīna ",
      verse: 3096,
      juz: 19,
      surah: 26,
    },
    {
      number: 165,
      image: "",
      text: "Do you approach the males among the worlds (165)",
      transliteration: "atatūna l-dhuk'rāna mina l-ʿālamīna ",
      verse: 3097,
      juz: 19,
      surah: 26,
    },
    {
      number: 166,
      image: "",
      text: "And you leave what created for you your Lord of your mates Nay you (are) a people transgressing (166)",
      transliteration:
        "watadharūna mā khalaqa lakum rabbukum min azwājikum bal antum qawmun ʿādūna ",
      verse: 3098,
      juz: 19,
      surah: 26,
    },
    {
      number: 167,
      image: "",
      text: "They said If not you desist O Lut Surely, you will be of the ones driven out (167)",
      transliteration:
        "qālū la-in lam tantahi yālūṭu latakūnanna mina l-mukh'rajīna ",
      verse: 3099,
      juz: 19,
      surah: 26,
    },
    {
      number: 168,
      image: "",
      text: "He said Indeed, I am (of) your deed of those who detest (168)",
      transliteration: "qāla innī liʿamalikum mina l-qālīna ",
      verse: 3100,
      juz: 19,
      surah: 26,
    },
    {
      number: 169,
      image: "",
      text: "My Lord Save me and my family from what they do (169)",
      transliteration: "rabbi najjinī wa-ahlī mimmā yaʿmalūna ",
      verse: 3101,
      juz: 19,
      surah: 26,
    },
    {
      number: 170,
      image: "",
      text: "So We saved him and his family all (170)",
      transliteration: "fanajjaynāhu wa-ahlahu ajmaʿīna ",
      verse: 3102,
      juz: 19,
      surah: 26,
    },
    {
      number: 171,
      image: "",
      text: "Except an old woman (was) among those who remained behind (171)",
      transliteration: "illā ʿajūzan fī l-ghābirīna ",
      verse: 3103,
      juz: 19,
      surah: 26,
    },
    {
      number: 172,
      image: "",
      text: "Then We destroyed the others (172)",
      transliteration: "thumma dammarnā l-ākharīna ",
      verse: 3104,
      juz: 19,
      surah: 26,
    },
    {
      number: 173,
      image: "",
      text: "And We rained upon them a rain and evil was (was) the rain (on) those who were warned (173)",
      transliteration: "wa-amṭarnā ʿalayhim maṭaran fasāa maṭaru l-mundharīna ",
      verse: 3105,
      juz: 19,
      surah: 26,
    },
    {
      number: 174,
      image: "",
      text: "Indeed in that surely is a sign but not are most of them believers (174)",
      transliteration: "inna fī dhālika laāyatan wamā kāna aktharuhum mu'minīna ",
      verse: 3106,
      juz: 19,
      surah: 26,
    },
    {
      number: 175,
      image: "",
      text: "And indeed your Lord surely, He (is) the All-Mighty the Most Merciful (175)",
      transliteration: "wa-inna rabbaka lahuwa l-ʿazīzu l-raḥīmu ",
      verse: 3107,
      juz: 19,
      surah: 26,
    },
    {
      number: 176,
      image: "",
      text: "Denied (the) companions (of the) Wood the Messengers (176)",
      transliteration: "kadhaba aṣḥābu al'aykati l-mur'salīna ",
      verse: 3108,
      juz: 19,
      surah: 26,
    },
    {
      number: 177,
      image: "",
      text: "When said to them Shuaib Will not you fear (Allah) (177)",
      transliteration: "idh qāla lahum shuʿaybun alā tattaqūna ",
      verse: 3109,
      juz: 19,
      surah: 26,
    },
    {
      number: 178,
      image: "",
      text: "Indeed, I am to you a Messenger trustworthy (178)",
      transliteration: "innī lakum rasūlun amīnun ",
      verse: 3110,
      juz: 19,
      surah: 26,
    },
    {
      number: 179,
      image: "",
      text: "So fear Allah and obey me (179)",
      transliteration: "fa-ittaqū l-laha wa-aṭīʿūni ",
      verse: 3111,
      juz: 19,
      surah: 26,
    },
    {
      number: 180,
      image: "",
      text: "And not I ask (of) you for it any payment Not (is) my payment except from (the) Lord (of) the worlds (180)",
      transliteration:
        "wamā asalukum ʿalayhi min ajrin in ajriya illā ʿalā rabbi l-ʿālamīna ",
      verse: 3112,
      juz: 19,
      surah: 26,
    },
    {
      number: 181,
      image: "",
      text: "Give full measure and (do) not be of those who cause loss (181)",
      transliteration: "awfū l-kayla walā takūnū mina l-mukh'sirīna ",
      verse: 3113,
      juz: 19,
      surah: 26,
    },
    {
      number: 182,
      image: "",
      text: "And weigh with a balance [the] even (182)",
      transliteration: "wazinū bil-qis'ṭāsi l-mus'taqīmi ",
      verse: 3114,
      juz: 19,
      surah: 26,
    },
    {
      number: 183,
      image: "",
      text: "And (do) not deprive people (of) their things and (do) not commit evil in the earth spreading corruption (183)",
      transliteration:
        "walā tabkhasū l-nāsa ashyāahum walā taʿthaw fī l-arḍi muf'sidīna ",
      verse: 3115,
      juz: 19,
      surah: 26,
    },
    {
      number: 184,
      image: "",
      text: "And fear the One Who created you and the generations the former (184)",
      transliteration: "wa-ittaqū alladhī khalaqakum wal-jibilata l-awalīna ",
      verse: 3116,
      juz: 19,
      surah: 26,
    },
    {
      number: 185,
      image: "",
      text: "They said Only you (are) of those bewitched (185)",
      transliteration: "qālū innamā anta mina l-musaḥarīna ",
      verse: 3117,
      juz: 19,
      surah: 26,
    },
    {
      number: 186,
      image: "",
      text: "And not you (are) except a man like us and indeed we think you surely (are) of the liars (186)",
      transliteration:
        "wamā anta illā basharun mith'lunā wa-in naẓunnuka lamina l-kādhibīna ",
      verse: 3118,
      juz: 19,
      surah: 26,
    },
    {
      number: 187,
      image: "",
      text: "Then cause to fall upon us fragments of the sky if you are of the truthful (187)",
      transliteration:
        "fa-asqiṭ ʿalaynā kisafan mina l-samāi in kunta mina l-ṣādiqīna ",
      verse: 3119,
      juz: 19,
      surah: 26,
    },
    {
      number: 188,
      image: "",
      text: "He said My Lord knows best of what you do (188)",
      transliteration: "qāla rabbī aʿlamu bimā taʿmalūna ",
      verse: 3120,
      juz: 19,
      surah: 26,
    },
    {
      number: 189,
      image: "",
      text: "But they denied him so seized them (the) punishment (of the) day (of) the shadow Indeed, it was (the) punishment (of) a Day Great (189)",
      transliteration:
        "fakadhabūhu fa-akhadhahum ʿadhābu yawmi l-ẓulati innahu kāna ʿadhāba yawmin ʿaẓīmin ",
      verse: 3121,
      juz: 19,
      surah: 26,
    },
    {
      number: 190,
      image: "",
      text: "Indeed in that surely, is a sign but not are most of them believers (190)",
      transliteration: "inna fī dhālika laāyatan wamā kāna aktharuhum mu'minīna ",
      verse: 3122,
      juz: 19,
      surah: 26,
    },
    {
      number: 191,
      image: "",
      text: "And indeed your Lord surely, He (is) the All-Mighty the Most Merciful (191)",
      transliteration: "wa-inna rabbaka lahuwa l-ʿazīzu l-raḥīmu ",
      verse: 3123,
      juz: 19,
      surah: 26,
    },
    {
      number: 192,
      image: "",
      text: "And indeed, it surely, is a Revelation (of the) Lord (of) the worlds (192)",
      transliteration: "wa-innahu latanzīlu rabbi l-ʿālamīna ",
      verse: 3124,
      juz: 19,
      surah: 26,
    },
    {
      number: 193,
      image: "",
      text: "Has brought it down Has brought it down the Spirit [the] Trustworthy (193)",
      transliteration: "nazala bihi l-rūḥu l-amīnu ",
      verse: 3125,
      juz: 19,
      surah: 26,
    },
    {
      number: 194,
      image: "",
      text: "Upon your heart that you may be of the warners (194)",
      transliteration: "ʿalā qalbika litakūna mina l-mundhirīna ",
      verse: 3126,
      juz: 19,
      surah: 26,
    },
    {
      number: 195,
      image: "",
      text: "In language Arabic clear (195)",
      transliteration: "bilisānin ʿarabiyyin mubīnin ",
      verse: 3127,
      juz: 19,
      surah: 26,
    },
    {
      number: 196,
      image: "",
      text: "And indeed, it surely, (is) in (the) Scriptures (of) the former (people) (196)",
      transliteration: "wa-innahu lafī zuburi l-awalīna ",
      verse: 3128,
      juz: 19,
      surah: 26,
    },
    {
      number: 197,
      image: "",
      text: "Is it not Is it not to them a sign that know it (the) scholars (of the) Children (of) Israel (197)",
      transliteration:
        "awalam yakun lahum āyatan an yaʿlamahu ʿulamāu banī is'rāīla ",
      verse: 3129,
      juz: 19,
      surah: 26,
    },
    {
      number: 198,
      image: "",
      text: "And if We (had) revealed it to any (of) the non-Arabs (198)",
      transliteration: "walaw nazzalnāhu ʿalā baʿḍi l-aʿjamīna ",
      verse: 3130,
      juz: 19,
      surah: 26,
    },
    {
      number: 199,
      image: "",
      text: "And he (had) recited it to them not they would in it (be) believers (199)",
      transliteration: "faqara-ahu ʿalayhim mā kānū bihi mu'minīna ",
      verse: 3131,
      juz: 19,
      surah: 26,
    },
    {
      number: 200,
      image: "",
      text: "Thus We have inserted it into (the) hearts (of) the criminals (200)",
      transliteration: "kadhālika salaknāhu fī qulūbi l-muj'rimīna ",
      verse: 3132,
      juz: 19,
      surah: 26,
    },
    {
      number: 201,
      image: "",
      text: "Not they will believe in it until they see the punishment [the] painful (201)",
      transliteration: "lā yu'minūna bihi ḥattā yarawū l-ʿadhāba l-alīma ",
      verse: 3133,
      juz: 19,
      surah: 26,
    },
    {
      number: 202,
      image: "",
      text: "And it will come to them suddenly while they (do) not perceive (202)",
      transliteration: "fayatiyahum baghtatan wahum lā yashʿurūna ",
      verse: 3134,
      juz: 19,
      surah: 26,
    },
    {
      number: 203,
      image: "",
      text: "Then they will say Are we (to be) reprieved (203)",
      transliteration: "fayaqūlū hal naḥnu munẓarūna ",
      verse: 3135,
      juz: 19,
      surah: 26,
    },
    {
      number: 204,
      image: "",
      text: "So is it for Our punishment they wish to hasten (204)",
      transliteration: "afabiʿadhābinā yastaʿjilūna ",
      verse: 3136,
      juz: 19,
      surah: 26,
    },
    {
      number: 205,
      image: "",
      text: "Then have you seen if We let them enjoy (for) years (205)",
      transliteration: "afara-ayta in mattaʿnāhum sinīna ",
      verse: 3137,
      juz: 19,
      surah: 26,
    },
    {
      number: 206,
      image: "",
      text: "Then comes to them what they were promised (206)",
      transliteration: "thumma jāahum mā kānū yūʿadūna ",
      verse: 3138,
      juz: 19,
      surah: 26,
    },
    {
      number: 207,
      image: "",
      text: "Not (will) avail them what enjoyment they were given enjoyment they were given (207)",
      transliteration: "mā aghnā ʿanhum mā kānū yumattaʿūna ",
      verse: 3139,
      juz: 19,
      surah: 26,
    },
    {
      number: 208,
      image: "",
      text: "And not We destroyed any town but it had warners (208)",
      transliteration: "wamā ahlaknā min qaryatin illā lahā mundhirūna ",
      verse: 3140,
      juz: 19,
      surah: 26,
    },
    {
      number: 209,
      image: "",
      text: "(To) remind and not We are unjust (209)",
      transliteration: "dhik'rā wamā kunnā ẓālimīna ",
      verse: 3141,
      juz: 19,
      surah: 26,
    },
    {
      number: 210,
      image: "",
      text: "And not have brought it down have brought it down the devils (210)",
      transliteration: "wamā tanazzalat bihi l-shayāṭīnu ",
      verse: 3142,
      juz: 19,
      surah: 26,
    },
    {
      number: 211,
      image: "",
      text: "And not (it) suits [for] them and not they are able (211)",
      transliteration: "wamā yanbaghī lahum wamā yastaṭīʿūna ",
      verse: 3143,
      juz: 19,
      surah: 26,
    },
    {
      number: 212,
      image: "",
      text: "Indeed, they from the hearing (are) surely banished (212)",
      transliteration: "innahum ʿani l-samʿi lamaʿzūlūna ",
      verse: 3144,
      juz: 19,
      surah: 26,
    },
    {
      number: 213,
      image: "",
      text: "So (do) not invoke with Allah god another lest you be of those punished (213)",
      transliteration:
        "falā tadʿu maʿa l-lahi ilāhan ākhara fatakūna mina l-muʿadhabīna ",
      verse: 3145,
      juz: 19,
      surah: 26,
    },
    {
      number: 214,
      image: "",
      text: "And warn your kindred [the] closest (214)",
      transliteration: "wa-andhir ʿashīrataka l-aqrabīna ",
      verse: 3146,
      juz: 19,
      surah: 26,
    },
    {
      number: 215,
      image: "",
      text: "And lower your wing to (those) who follow you of the believers (215)",
      transliteration: "wa-ikh'fiḍ janāḥaka limani ittabaʿaka mina l-mu'minīna ",
      verse: 3147,
      juz: 19,
      surah: 26,
    },
    {
      number: 216,
      image: "",
      text: "Then if they disobey you then say Indeed, I am innocent of what you do (216)",
      transliteration: "fa-in ʿaṣawka faqul innī barīon mimmā taʿmalūna ",
      verse: 3148,
      juz: 19,
      surah: 26,
    },
    {
      number: 217,
      image: "",
      text: "And put (your) trust in the All-Mighty the Most Merciful (217)",
      transliteration: "watawakkal ʿalā l-ʿazīzi l-raḥīmi ",
      verse: 3149,
      juz: 19,
      surah: 26,
    },
    {
      number: 218,
      image: "",
      text: "The One Who sees you when you stand up (218)",
      transliteration: "alladhī yarāka ḥīna taqūmu ",
      verse: 3150,
      juz: 19,
      surah: 26,
    },
    {
      number: 219,
      image: "",
      text: "And your movements among those who prostrate (219)",
      transliteration: "wataqallubaka fī l-sājidīna ",
      verse: 3151,
      juz: 19,
      surah: 26,
    },
    {
      number: 220,
      image: "",
      text: "Indeed, He [He] (is) the All-Hearer the All-Knower (220)",
      transliteration: "innahu huwa l-samīʿu l-ʿalīmu ",
      verse: 3152,
      juz: 19,
      surah: 26,
    },
    {
      number: 221,
      image: "",
      text: "Shall I inform you upon whom descend the devils (221)",
      transliteration: "hal unabbi-ukum ʿalā man tanazzalu l-shayāṭīnu ",
      verse: 3153,
      juz: 19,
      surah: 26,
    },
    {
      number: 222,
      image: "",
      text: "They descend upon every liar sinful (222)",
      transliteration: "tanazzalu ʿalā kulli affākin athīmin ",
      verse: 3154,
      juz: 19,
      surah: 26,
    },
    {
      number: 223,
      image: "",
      text: "They pass on (what is) heard and most of them (are) liars (223)",
      transliteration: "yul'qūna l-samʿa wa-aktharuhum kādhibūna ",
      verse: 3155,
      juz: 19,
      surah: 26,
    },
    {
      number: 224,
      image: "",
      text: "And the poets  follow them the deviators (224)",
      transliteration: "wal-shuʿarāu yattabiʿuhumu l-ghāwūna ",
      verse: 3156,
      juz: 19,
      surah: 26,
    },
    {
      number: 225,
      image: "",
      text: "Do not you see that they in every valley [they] roam (225)",
      transliteration: "alam tara annahum fī kulli wādin yahīmūna ",
      verse: 3157,
      juz: 19,
      surah: 26,
    },
    {
      number: 226,
      image: "",
      text: "And that they say what not they do (226)",
      transliteration: "wa-annahum yaqūlūna mā lā yafʿalūna ",
      verse: 3158,
      juz: 19,
      surah: 26,
    },
    {
      number: 227,
      image: "",
      text: "Except those who believe and do righteous deeds and remember Allah much and defend themselves after after after they were wronged And will come to know those who have wronged (to) what return they will return (227)",
      transliteration:
        "illā alladhīna āmanū waʿamilū l-ṣāliḥāti wadhakarū l-laha kathīran wa-intaṣarū min baʿdi mā ẓulimū wasayaʿlamu alladhīna ẓalamū ayya munqalabin yanqalibūna ",
      verse: 3159,
      juz: 19,
      surah: 26,
    },
  ],
};
