import { Surah } from "../types/islam.js";

export const sin: Surah = {
  name: "Ya'Sin",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "Ya Seen (1)",
      transliteration: "ya-seen ",
      verse: 3706,
      juz: 22,
      surah: 36,
    },
    {
      number: 2,
      image: "",
      text: "By the Quran the Wise (2)",
      transliteration: "wal-qur'āni l-ḥakīmi ",
      verse: 3707,
      juz: 22,
      surah: 36,
    },
    {
      number: 3,
      image: "",
      text: "Indeed, you (are) among the Messengers (3)",
      transliteration: "innaka lamina l-mur'salīna ",
      verse: 3708,
      juz: 22,
      surah: 36,
    },
    {
      number: 4,
      image: "",
      text: "On a Path Straight (4)",
      transliteration: "ʿalā ṣirāṭin mus'taqīmin ",
      verse: 3709,
      juz: 22,
      surah: 36,
    },
    {
      number: 5,
      image: "",
      text: "A revelation (of) the All-Mighty the Most Merciful (5)",
      transliteration: "tanzīla l-ʿazīzi l-raḥīmi ",
      verse: 3710,
      juz: 22,
      surah: 36,
    },
    {
      number: 6,
      image: "",
      text: "That you may warn a people not were warned their forefathers so they (are) heedless (6)",
      transliteration: "litundhira qawman mā undhira ābāuhum fahum ghāfilūna ",
      verse: 3711,
      juz: 22,
      surah: 36,
    },
    {
      number: 7,
      image: "",
      text: "Certainly (has) proved true the word upon most of them so they (do) not believe (7)",
      transliteration: "laqad ḥaqqa l-qawlu ʿalā aktharihim fahum lā yu'minūna ",
      verse: 3712,
      juz: 22,
      surah: 36,
    },
    {
      number: 8,
      image: "",
      text: "Indeed, We [We] have placed on their necks iron collars and they (are up) to the chins so they (are with) heads raised up (8)",
      transliteration:
        "innā jaʿalnā fī aʿnāqihim aghlālan fahiya ilā l-adhqāni fahum muq'maḥūna ",
      verse: 3713,
      juz: 22,
      surah: 36,
    },
    {
      number: 9,
      image: "",
      text: "And We have made from before/between their hands/their front a barrier and from behind them a barrier and We covered them so they (do) not see (9)",
      transliteration:
        "wajaʿalnā min bayni aydīhim saddan wamin khalfihim saddan fa-aghshaynāhum fahum lā yub'ṣirūna ",
      verse: 3714,
      juz: 22,
      surah: 36,
    },
    {
      number: 10,
      image: "",
      text: "And it (is) same to them whether you warn them or (do) not warn them not they will believe (10)",
      transliteration:
        "wasawāon ʿalayhim a-andhartahum am lam tundhir'hum lā yu'minūna ",
      verse: 3715,
      juz: 22,
      surah: 36,
    },
    {
      number: 11,
      image: "",
      text: "Only you (can) warn (him) who follows the Reminder and fears the Most Gracious in the unseen So give him glad tidings of forgiveness and a reward noble (11)",
      transliteration:
        "innamā tundhiru mani ittabaʿa l-dhik'ra wakhashiya l-raḥmāna bil-ghaybi fabashir'hu bimaghfiratin wa-ajrin karīmin ",
      verse: 3716,
      juz: 22,
      surah: 36,
    },
    {
      number: 12,
      image: "",
      text: "Indeed, We [We] [We] give life (to) the dead and We record what they have sent before and their footprints and every thing We have enumerated it in a Register clear (12)",
      transliteration:
        "innā naḥnu nuḥ'yī l-mawtā wanaktubu mā qaddamū waāthārahum wakulla shayin aḥṣaynāhu fī imāmin mubīnin ",
      verse: 3717,
      juz: 22,
      surah: 36,
    },
    {
      number: 13,
      image: "",
      text: "And set forth to them an example (of the) companions (of) the city when came to it the Messengers (13)",
      transliteration:
        "wa-iḍ'rib lahum mathalan aṣḥāba l-qaryati idh jāahā l-mur'salūna ",
      verse: 3718,
      juz: 22,
      surah: 36,
    },
    {
      number: 14,
      image: "",
      text: "When We sent to them two (Messengers) but they denied both of them so We strengthened them with a third and they said Indeed, We to you (are) Messengers (14)",
      transliteration:
        "idh arsalnā ilayhimu ith'nayni fakadhabūhumā faʿazzaznā bithālithin faqālū innā ilaykum mur'salūna ",
      verse: 3719,
      juz: 22,
      surah: 36,
    },
    {
      number: 15,
      image: "",
      text: "They said Not you (are) but human beings like us and not has revealed the Most Gracious any thing Not you (are) but lying (15)",
      transliteration:
        "qālū mā antum illā basharun mith'lunā wamā anzala l-raḥmānu min shayin in antum illā takdhibūna ",
      verse: 3720,
      juz: 22,
      surah: 36,
    },
    {
      number: 16,
      image: "",
      text: "They said Our Lord knows that we to you (are) surely Messengers (16)",
      transliteration: "qālū rabbunā yaʿlamu innā ilaykum lamur'salūna ",
      verse: 3721,
      juz: 22,
      surah: 36,
    },
    {
      number: 17,
      image: "",
      text: "And not (is) on us except the conveyance clear (17)",
      transliteration: "wamā ʿalaynā illā l-balāghu l-mubīnu ",
      verse: 3722,
      juz: 22,
      surah: 36,
    },
    {
      number: 18,
      image: "",
      text: "They said Indeed, we [we] see an evil omen from you If not you desist surely, we will stone you and surely will touch you from us a punishment painful (18)",
      transliteration:
        "qālū innā taṭayyarnā bikum la-in lam tantahū lanarjumannakum walayamassannakum minnā ʿadhābun alīmun ",
      verse: 3723,
      juz: 22,
      surah: 36,
    },
    {
      number: 19,
      image: "",
      text: "They said Your evil omen (be) with you Is it because you are admonished Nay you (are) a people transgressing (19)",
      transliteration:
        "qālū ṭāirukum maʿakum a-in dhukkir'tum bal antum qawmun mus'rifūna ",
      verse: 3724,
      juz: 22,
      surah: 36,
    },
    {
      number: 20,
      image: "",
      text: "And came from (the) farthest end (of) the city a man running He said O my People Follow the Messengers (20)",
      transliteration:
        "wajāa min aqṣā l-madīnati rajulun yasʿā qāla yāqawmi ittabiʿū l-mur'salīna ",
      verse: 3725,
      juz: 22,
      surah: 36,
    },
    {
      number: 21,
      image: "",
      text: "Follow (those) who (do) not ask (of) you any payment and they (are) rightly guided (21)",
      transliteration: "ittabiʿū man lā yasalukum ajran wahum muh'tadūna ",
      verse: 3726,
      juz: 22,
      surah: 36,
    },
    {
      number: 22,
      image: "",
      text: "And what (is) for me (that) not I worship the One Who created me and to Whom you will be returned (22)",
      transliteration:
        "wamā liya lā aʿbudu alladhī faṭaranī wa-ilayhi tur'jaʿūna ",
      verse: 3727,
      juz: 22,
      surah: 36,
    },
    {
      number: 23,
      image: "",
      text: "Should I take besides Him besides Him gods If intends for me the Most Gracious any harm not will avail [from] me their intercession (in) anything and not they (can) save me (23)",
      transliteration:
        "a-attakhidhu min dūnihi ālihatan in yurid'ni l-raḥmānu biḍurrin lā tugh'ni ʿannī shafāʿatuhum shayan walā yunqidhūni ",
      verse: 3728,
      juz: 22,
      surah: 36,
    },
    {
      number: 24,
      image: "",
      text: "Indeed, I then surely would be in an error clear (24)",
      transliteration: "innī idhan lafī ḍalālin mubīnin ",
      verse: 3729,
      juz: 22,
      surah: 36,
    },
    {
      number: 25,
      image: "",
      text: "Indeed, I [I] have believed in your Lord so listen to me (25)",
      transliteration: "innī āmantu birabbikum fa-is'maʿūni ",
      verse: 3730,
      juz: 22,
      surah: 36,
    },
    {
      number: 26,
      image: "",
      text: "It was said Enter Paradise He said I wish my people knew (26)",
      transliteration: "qīla ud'khuli l-janata qāla yālayta qawmī yaʿlamūna ",
      verse: 3731,
      juz: 22,
      surah: 36,
    },
    {
      number: 27,
      image: "",
      text: "Of how has forgiven me my Lord and placed me among the honored ones (27)",
      transliteration: "bimā ghafara lī rabbī wajaʿalanī mina l-muk'ramīna ",
      verse: 3732,
      juz: 22,
      surah: 36,
    },
    {
      number: 28,
      image: "",
      text: "And not We sent down upon his people after him after him any host from the heaven and not were We (to) send down (28)",
      transliteration:
        "wamā anzalnā ʿalā qawmihi min baʿdihi min jundin mina l-samāi wamā kunnā munzilīna ",
      verse: 3733,
      juz: 23,
      surah: 36,
    },
    {
      number: 29,
      image: "",
      text: "Not it was but a shout one then behold They (were) extinguished (29)",
      transliteration: "in kānat illā ṣayḥatan wāḥidatan fa-idhā hum khāmidūna ",
      verse: 3734,
      juz: 23,
      surah: 36,
    },
    {
      number: 30,
      image: "",
      text: "Alas for the servants Not came to them any Messenger but they did mock at him mock at him (30)",
      transliteration:
        "yāḥasratan ʿalā l-ʿibādi mā yatīhim min rasūlin illā kānū bihi yastahziūna ",
      verse: 3735,
      juz: 23,
      surah: 36,
    },
    {
      number: 31,
      image: "",
      text: "Do not they see how many We destroyed before them of the generations That they to them will not return will not return (31)",
      transliteration:
        "alam yaraw kam ahlaknā qablahum mina l-qurūni annahum ilayhim lā yarjiʿūna ",
      verse: 3736,
      juz: 23,
      surah: 36,
    },
    {
      number: 32,
      image: "",
      text: "And surely all then together before Us (will be) brought (32)",
      transliteration: "wa-in kullun lammā jamīʿun ladaynā muḥ'ḍarūna ",
      verse: 3737,
      juz: 23,
      surah: 36,
    },
    {
      number: 33,
      image: "",
      text: "And a Sign for them (is) the earth dead We give it life and We bring forth from it grain and from it they eat (33)",
      transliteration:
        "waāyatun lahumu l-arḍu l-maytatu aḥyaynāhā wa-akhrajnā min'hā ḥabban famin'hu yakulūna ",
      verse: 3738,
      juz: 23,
      surah: 36,
    },
    {
      number: 34,
      image: "",
      text: "And We placed therein gardens of date-palms and grapevines and We caused to gush forth in it of the springs (34)",
      transliteration:
        "wajaʿalnā fīhā jannātin min nakhīlin wa-aʿnābin wafajjarnā fīhā mina l-ʿuyūni ",
      verse: 3739,
      juz: 23,
      surah: 36,
    },
    {
      number: 35,
      image: "",
      text: "That they may eat of its fruit And not made it their hands So will not they be grateful (35)",
      transliteration:
        "liyakulū min thamarihi wamā ʿamilathu aydīhim afalā yashkurūna ",
      verse: 3740,
      juz: 23,
      surah: 36,
    },
    {
      number: 36,
      image: "",
      text: "Glory be (to) the One Who created (in) pairs all of what grows the earth and of themselves and of what not they know (36)",
      transliteration:
        "sub'ḥāna alladhī khalaqa l-azwāja kullahā mimmā tunbitu l-arḍu wamin anfusihim wamimmā lā yaʿlamūna ",
      verse: 3741,
      juz: 23,
      surah: 36,
    },
    {
      number: 37,
      image: "",
      text: "And a Sign for them (is) the night We withdraw from it the day Then behold They (are) those in darkness (37)",
      transliteration:
        "waāyatun lahumu al-laylu naslakhu min'hu l-nahāra fa-idhā hum muẓ'limūna ",
      verse: 3742,
      juz: 23,
      surah: 36,
    },
    {
      number: 38,
      image: "",
      text: "And the sun runs to a term appointed for it That (is the) Decree (of) the All-Mighty the All-Knowing (38)",
      transliteration:
        "wal-shamsu tajrī limus'taqarrin lahā dhālika taqdīru l-ʿazīzi l-ʿalīmi ",
      verse: 3743,
      juz: 23,
      surah: 36,
    },
    {
      number: 39,
      image: "",
      text: "And the moon  We have ordained for it phases until it returns like the date stalk the old (39)",
      transliteration:
        "wal-qamara qaddarnāhu manāzila ḥattā ʿāda kal-ʿur'jūni l-qadīmi ",
      verse: 3744,
      juz: 23,
      surah: 36,
    },
    {
      number: 40,
      image: "",
      text: "Not the sun is permitted for it  that it overtakes the moon and not the night (can) outstrip the day but all in an orbit they are floating (40)",
      transliteration:
        "lā l-shamsu yanbaghī lahā an tud'rika l-qamara walā al-laylu sābiqu l-nahāri wakullun fī falakin yasbaḥūna ",
      verse: 3745,
      juz: 23,
      surah: 36,
    },
    {
      number: 41,
      image: "",
      text: "And a Sign for them (is) that We carried their offspring in the ship laden (41)",
      transliteration:
        "waāyatun lahum annā ḥamalnā dhurriyyatahum fī l-ful'ki l-mashḥūni ",
      verse: 3746,
      juz: 23,
      surah: 36,
    },
    {
      number: 42,
      image: "",
      text: "And We created for them from (the) likes of it what they ride (42)",
      transliteration: "wakhalaqnā lahum min mith'lihi mā yarkabūna ",
      verse: 3747,
      juz: 23,
      surah: 36,
    },
    {
      number: 43,
      image: "",
      text: "And if We will We could drown them then not (would be) a responder to a cry for them and not they would be saved (43)",
      transliteration:
        "wa-in nasha nugh'riq'hum falā ṣarīkha lahum walā hum yunqadhūna ",
      verse: 3748,
      juz: 23,
      surah: 36,
    },
    {
      number: 44,
      image: "",
      text: "Except (by) Mercy from Us and provision for a time (44)",
      transliteration: "illā raḥmatan minnā wamatāʿan ilā ḥīnin ",
      verse: 3749,
      juz: 23,
      surah: 36,
    },
    {
      number: 45,
      image: "",
      text: "And when it is said to them Fear what (is) before you (is) before you and what (is) behind you so that you may receive mercy (45)",
      transliteration:
        "wa-idhā qīla lahumu ittaqū mā bayna aydīkum wamā khalfakum laʿallakum tur'ḥamūna ",
      verse: 3750,
      juz: 23,
      surah: 36,
    },
    {
      number: 46,
      image: "",
      text: "And not comes to them of a Sign from (the) Signs (of) their Lord but they from it turn away (46)",
      transliteration:
        "wamā tatīhim min āyatin min āyāti rabbihim illā kānū ʿanhā muʿ'riḍīna ",
      verse: 3751,
      juz: 23,
      surah: 36,
    },
    {
      number: 47,
      image: "",
      text: "And when it is said to them Spend from what (has) provided you Allah Said those who disbelieved to those who believed Should we feed whom if Allah willed  Allah willed  He would have fed him Not (are) you except in an error clear (47)",
      transliteration:
        "wa-idhā qīla lahum anfiqū mimmā razaqakumu l-lahu qāla alladhīna kafarū lilladhīna āmanū anuṭ'ʿimu man law yashāu l-lahu aṭʿamahu in antum illā fī ḍalālin mubīnin ",
      verse: 3752,
      juz: 23,
      surah: 36,
    },
    {
      number: 48,
      image: "",
      text: "And they say When (is) this promise if you are truthful (48)",
      transliteration: "wayaqūlūna matā hādhā l-waʿdu in kuntum ṣādiqīna ",
      verse: 3753,
      juz: 23,
      surah: 36,
    },
    {
      number: 49,
      image: "",
      text: "Not they await except a shout one it will seize them while they are disputing (49)",
      transliteration:
        "mā yanẓurūna illā ṣayḥatan wāḥidatan takhudhuhum wahum yakhiṣṣimūna ",
      verse: 3754,
      juz: 23,
      surah: 36,
    },
    {
      number: 50,
      image: "",
      text: "Then not they will be able (to) make a will and not to their people they (can) return (50)",
      transliteration: "falā yastaṭīʿūna tawṣiyatan walā ilā ahlihim yarjiʿūna ",
      verse: 3755,
      juz: 23,
      surah: 36,
    },
    {
      number: 51,
      image: "",
      text: "And will be blown [in] the trumpet and behold They from the graves to their Lord [they] will hasten (51)",
      transliteration:
        "wanufikha fī l-ṣūri fa-idhā hum mina l-ajdāthi ilā rabbihim yansilūna ",
      verse: 3756,
      juz: 23,
      surah: 36,
    },
    {
      number: 52,
      image: "",
      text: "They [will] say O woe to us Who has raised us from our sleeping place This (is) What (had) promised the Most Gracious and told (the) truth the Messengers (52)",
      transliteration:
        "qālū yāwaylanā man baʿathanā min marqadinā hādhā mā waʿada l-raḥmānu waṣadaqa l-mur'salūna ",
      verse: 3757,
      juz: 23,
      surah: 36,
    },
    {
      number: 53,
      image: "",
      text: "Not it will be but a shout single so behold They all before Us (will be) brought (53)",
      transliteration:
        "in kānat illā ṣayḥatan wāḥidatan fa-idhā hum jamīʿun ladaynā muḥ'ḍarūna ",
      verse: 3758,
      juz: 23,
      surah: 36,
    },
    {
      number: 54,
      image: "",
      text: "So this Day not will be wronged a soul (in) anything and not you will be recompensed except (for) what you used (to) do (54)",
      transliteration:
        "fal-yawma lā tuẓ'lamu nafsun shayan walā tuj'zawna illā mā kuntum taʿmalūna ",
      verse: 3759,
      juz: 23,
      surah: 36,
    },
    {
      number: 55,
      image: "",
      text: "Indeed (the) companions (of) Paradise this Day [in] will be occupied (in) amusement (55)",
      transliteration: "inna aṣḥāba l-janati l-yawma fī shughulin fākihūna ",
      verse: 3760,
      juz: 23,
      surah: 36,
    },
    {
      number: 56,
      image: "",
      text: "They and their spouses in shades on [the] couches reclining (56)",
      transliteration: "hum wa-azwājuhum fī ẓilālin ʿalā l-arāiki muttakiūna ",
      verse: 3761,
      juz: 23,
      surah: 36,
    },
    {
      number: 57,
      image: "",
      text: "For them therein (are) fruits and for them (is) whatever they call for (57)",
      transliteration: "lahum fīhā fākihatun walahum mā yaddaʿūna ",
      verse: 3762,
      juz: 23,
      surah: 36,
    },
    {
      number: 58,
      image: "",
      text: "Peace A word from a Lord Most Merciful (58)",
      transliteration: "salāmun qawlan min rabbin raḥīmin ",
      verse: 3763,
      juz: 23,
      surah: 36,
    },
    {
      number: 59,
      image: "",
      text: "But stand apart today O criminals O criminals (59)",
      transliteration: "wa-im'tāzū l-yawma ayyuhā l-muj'rimūna ",
      verse: 3764,
      juz: 23,
      surah: 36,
    },
    {
      number: 60,
      image: "",
      text: "Did not I enjoin upon you O Children of Adam O Children of Adam That (do) not worship the Shaitaan indeed, he (is) for you an enemy clear (60)",
      transliteration:
        "alam aʿhad ilaykum yābanī ādama an lā taʿbudū l-shayṭāna innahu lakum ʿaduwwun mubīnun ",
      verse: 3765,
      juz: 23,
      surah: 36,
    },
    {
      number: 61,
      image: "",
      text: "And that you worship Me This (is) a Path Straight (61)",
      transliteration: "wa-ani uʿ'budūnī hādhā ṣirāṭun mus'taqīmun ",
      verse: 3766,
      juz: 23,
      surah: 36,
    },
    {
      number: 62,
      image: "",
      text: "And indeed he led astray from you a multitude great Then did not you use reason (62)",
      transliteration:
        "walaqad aḍalla minkum jibillan kathīran afalam takūnū taʿqilūna ",
      verse: 3767,
      juz: 23,
      surah: 36,
    },
    {
      number: 63,
      image: "",
      text: "This (is) (the) Hell which you were promised (63)",
      transliteration: "hādhihi jahannamu allatī kuntum tūʿadūna ",
      verse: 3768,
      juz: 23,
      surah: 36,
    },
    {
      number: 64,
      image: "",
      text: "Burn therein today because you used to disbelieve (64)",
      transliteration: "iṣ'lawhā l-yawma bimā kuntum takfurūna ",
      verse: 3769,
      juz: 23,
      surah: 36,
    },
    {
      number: 65,
      image: "",
      text: "This Day We will seal [on] their mouths and will speak to Us their hands and will bear witness their feet about what they used to earn (65)",
      transliteration:
        "al-yawma nakhtimu ʿalā afwāhihim watukallimunā aydīhim watashhadu arjuluhum bimā kānū yaksibūna ",
      verse: 3770,
      juz: 23,
      surah: 36,
    },
    {
      number: 66,
      image: "",
      text: "And if We willed We (would have) surely obliterated [over] their eyes then they (would) race (to find) the path then how (could) they see (66)",
      transliteration:
        "walaw nashāu laṭamasnā ʿalā aʿyunihim fa-is'tabaqū l-ṣirāṭa fa-annā yub'ṣirūna ",
      verse: 3771,
      juz: 23,
      surah: 36,
    },
    {
      number: 67,
      image: "",
      text: "And if We willed surely, We (would have) transformed them in their places then not they would have been able to proceed and not return (67)",
      transliteration:
        "walaw nashāu lamasakhnāhum ʿalā makānatihim famā is'taṭāʿū muḍiyyan walā yarjiʿūna ",
      verse: 3772,
      juz: 23,
      surah: 36,
    },
    {
      number: 68,
      image: "",
      text: "And (he) whom We grant him long life We reverse him in the creation Then will not they use intellect (68)",
      transliteration:
        "waman nuʿammir'hu nunakkis'hu fī l-khalqi afalā yaʿqilūna ",
      verse: 3773,
      juz: 23,
      surah: 36,
    },
    {
      number: 69,
      image: "",
      text: "And not We taught him [the] poetry and not it is befitting for him Not it (is) except a Reminder and a Quran clear (69)",
      transliteration:
        "wamā ʿallamnāhu l-shiʿ'ra wamā yanbaghī lahu in huwa illā dhik'run waqur'ānun mubīnun ",
      verse: 3774,
      juz: 23,
      surah: 36,
    },
    {
      number: 70,
      image: "",
      text: "To warn (him) who is alive and may be proved true the Word against the disbelievers (70)",
      transliteration:
        "liyundhira man kāna ḥayyan wayaḥiqqa l-qawlu ʿalā l-kāfirīna ",
      verse: 3775,
      juz: 23,
      surah: 36,
    },
    {
      number: 71,
      image: "",
      text: "Do not they see that We [We] created for them from what have made Our hands cattle then they [for them] (are the) owners (71)",
      transliteration:
        "awalam yaraw annā khalaqnā lahum mimmā ʿamilat aydīnā anʿāman fahum lahā mālikūna ",
      verse: 3776,
      juz: 23,
      surah: 36,
    },
    {
      number: 72,
      image: "",
      text: "And We have tamed them for them so some of them  they ride them and some of them they eat (72)",
      transliteration:
        "wadhallalnāhā lahum famin'hā rakūbuhum wamin'hā yakulūna ",
      verse: 3777,
      juz: 23,
      surah: 36,
    },
    {
      number: 73,
      image: "",
      text: "And for them therein (are) benefits and drinks so (will) not they give thanks (73)",
      transliteration: "walahum fīhā manāfiʿu wamashāribu afalā yashkurūna ",
      verse: 3778,
      juz: 23,
      surah: 36,
    },
    {
      number: 74,
      image: "",
      text: "But they have taken besides besides Allah gods that they may be helped (74)",
      transliteration:
        "wa-ittakhadhū min dūni l-lahi ālihatan laʿallahum yunṣarūna ",
      verse: 3779,
      juz: 23,
      surah: 36,
    },
    {
      number: 75,
      image: "",
      text: "Not they are able to help them but they  for them (are) hosts (who will) be brought (75)",
      transliteration: "lā yastaṭīʿūna naṣrahum wahum lahum jundun muḥ'ḍarūna ",
      verse: 3780,
      juz: 23,
      surah: 36,
    },
    {
      number: 76,
      image: "",
      text: "So (let) not grieve you their speech Indeed, We [We] know what they conceal and what they declare (76)",
      transliteration:
        "falā yaḥzunka qawluhum innā naʿlamu mā yusirrūna wamā yuʿ'linūna ",
      verse: 3781,
      juz: 23,
      surah: 36,
    },
    {
      number: 77,
      image: "",
      text: "Does not see [the] man that We [We] created him from a semen-drop Then behold He (is) an opponent clear (77)",
      transliteration:
        "awalam yara l-insānu annā khalaqnāhu min nuṭ'fatin fa-idhā huwa khaṣīmun mubīnun ",
      verse: 3782,
      juz: 23,
      surah: 36,
    },
    {
      number: 78,
      image: "",
      text: "And he sets forth for Us an example and forgets his (own) creation He says Who will give life (to) the bones while they (are) decomposed (78)",
      transliteration:
        "waḍaraba lanā mathalan wanasiya khalqahu qāla man yuḥ'yī l-ʿiẓāma wahiya ramīmun ",
      verse: 3783,
      juz: 23,
      surah: 36,
    },
    {
      number: 79,
      image: "",
      text: "Say He will give them life Who produced them (the) first time and He (is) of every creation All-Knower (79)",
      transliteration:
        "qul yuḥ'yīhā alladhī ansha-ahā awwala marratin wahuwa bikulli khalqin ʿalīmun ",
      verse: 3784,
      juz: 23,
      surah: 36,
    },
    {
      number: 80,
      image: "",
      text: "The One Who made for you from the tree [the] green  fire and behold You from it ignite (80)",
      transliteration:
        "alladhī jaʿala lakum mina l-shajari l-akhḍari nāran fa-idhā antum min'hu tūqidūna ",
      verse: 3785,
      juz: 23,
      surah: 36,
    },
    {
      number: 81,
      image: "",
      text: "Is it not (He) Who created the heavens and the earth Able to [that] create (the) like of them Yes, indeed and He (is) the Supreme Creator the All-Knower (81)",
      transliteration:
        "awalaysa alladhī khalaqa l-samāwāti wal-arḍa biqādirin ʿalā an yakhluqa mith'lahum balā wahuwa l-khalāqu l-ʿalīmu ",
      verse: 3786,
      juz: 23,
      surah: 36,
    },
    {
      number: 82,
      image: "",
      text: "Only His Command when He intends a thing that He says to it Be and it is (82)",
      transliteration:
        "innamā amruhu idhā arāda shayan an yaqūla lahu kun fayakūnu ",
      verse: 3787,
      juz: 23,
      surah: 36,
    },
    {
      number: 83,
      image: "",
      text: "So glory be (to) the One who in Whose hand is (the) dominion (of) all things and to Him you will be returned (83)",
      transliteration:
        "fasub'ḥāna alladhī biyadihi malakūtu kulli shayin wa-ilayhi tur'jaʿūna ",
      verse: 3788,
      juz: 23,
      surah: 36,
    },
  ],
};
