import { Surah } from "../types/islam.js";

export const taha: Surah = {
  name: "Taha",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "Ta Ha (1)",
      transliteration: "tta-ha ",
      verse: 2349,
      juz: 16,
      surah: 20,
    },
    {
      number: 2,
      image: "",
      text: "Not We (have) sent down to you the Quran that you be distressed (2)",
      transliteration: "mā anzalnā ʿalayka l-qur'āna litashqā ",
      verse: 2350,
      juz: 16,
      surah: 20,
    },
    {
      number: 3,
      image: "",
      text: "(But) (as) a reminder for (those) who fear (3)",
      transliteration: "illā tadhkiratan liman yakhshā ",
      verse: 2351,
      juz: 16,
      surah: 20,
    },
    {
      number: 4,
      image: "",
      text: "A revelation from (He) Who created the earth and the heavens [the] high (4)",
      transliteration: "tanzīlan mimman khalaqa l-arḍa wal-samāwāti l-ʿulā ",
      verse: 2352,
      juz: 16,
      surah: 20,
    },
    {
      number: 5,
      image: "",
      text: "The Most Gracious over the Throne is established (5)",
      transliteration: "al-raḥmānu ʿalā l-ʿarshi is'tawā ",
      verse: 2353,
      juz: 16,
      surah: 20,
    },
    {
      number: 6,
      image: "",
      text: "To Him (belongs) whatever (is) in the heavens and whatever (is) in the earth and whatever (is) between them and whatever (is) under the soil (6)",
      transliteration:
        "lahu mā fī l-samāwāti wamā fī l-arḍi wamā baynahumā wamā taḥta l-tharā ",
      verse: 2354,
      juz: 16,
      surah: 20,
    },
    {
      number: 7,
      image: "",
      text: "And if you speak aloud the word then indeed, He knows the secret and the more hidden (7)",
      transliteration:
        "wa-in tajhar bil-qawli fa-innahu yaʿlamu l-sira wa-akhfā ",
      verse: 2355,
      juz: 16,
      surah: 20,
    },
    {
      number: 8,
      image: "",
      text: "Allah  (there is) no god except Him To Him (belong) the Names the Most Beautiful (8)",
      transliteration: "al-lahu lā ilāha illā huwa lahu l-asmāu l-ḥus'nā ",
      verse: 2356,
      juz: 16,
      surah: 20,
    },
    {
      number: 9,
      image: "",
      text: "And has come to you the narration (of) Musa (9)",
      transliteration: "wahal atāka ḥadīthu mūsā ",
      verse: 2357,
      juz: 16,
      surah: 20,
    },
    {
      number: 10,
      image: "",
      text: "When he saw a fire then he said to his family Stay here indeed, I [I] perceived a fire perhaps I (can) bring you therefrom a burning brand or I find at the fire guidance (10)",
      transliteration:
        "idh raā nāran faqāla li-ahlihi um'kuthū innī ānastu nāran laʿallī ātīkum min'hā biqabasin aw ajidu ʿalā l-nāri hudan ",
      verse: 2358,
      juz: 16,
      surah: 20,
    },
    {
      number: 11,
      image: "",
      text: "Then when he came to it he was called O Musa (11)",
      transliteration: "falammā atāhā nūdiya yāmūsā ",
      verse: 2359,
      juz: 16,
      surah: 20,
    },
    {
      number: 12,
      image: "",
      text: "Indeed, [I] I Am your Lord so remove your shoes Indeed, you (are) in the valley the sacred (of) Tuwa (12)",
      transliteration:
        "innī anā rabbuka fa-ikh'laʿ naʿlayka innaka bil-wādi l-muqadasi ṭuwan ",
      verse: 2360,
      juz: 16,
      surah: 20,
    },
    {
      number: 13,
      image: "",
      text: "And I (have) chosen you so listen to what is revealed (13)",
      transliteration: "wa-anā ikh'tartuka fa-is'tamiʿ limā yūḥā ",
      verse: 2361,
      juz: 16,
      surah: 20,
    },
    {
      number: 14,
      image: "",
      text: "Indeed, [I] I Am Allah (There is) no god but I so worship Me and establish the prayer for My remembrance (14)",
      transliteration:
        "innanī anā l-lahu lā ilāha illā anā fa-uʿ'bud'nī wa-aqimi l-ṣalata lidhik'rī ",
      verse: 2362,
      juz: 16,
      surah: 20,
    },
    {
      number: 15,
      image: "",
      text: "Indeed the Hour (will be) coming I almost [I] hide it that may be recompensed every soul for what it strives (15)",
      transliteration:
        "inna l-sāʿata ātiyatun akādu ukh'fīhā lituj'zā kullu nafsin bimā tasʿā ",
      verse: 2363,
      juz: 16,
      surah: 20,
    },
    {
      number: 16,
      image: "",
      text: "So (do) not (let) avert you from it (one) who (does) not believe in it and follows his desires lest you perish (16)",
      transliteration:
        "falā yaṣuddannaka ʿanhā man lā yu'minu bihā wa-ittabaʿa hawāhu fatardā ",
      verse: 2364,
      juz: 16,
      surah: 20,
    },
    {
      number: 17,
      image: "",
      text: "And what (is) that in your right hand O Musa (17)",
      transliteration: "wamā til'ka biyamīnika yāmūsā ",
      verse: 2365,
      juz: 16,
      surah: 20,
    },
    {
      number: 18,
      image: "",
      text: "He said It (is) my staff I lean upon it and I bring down leaves with it for my sheep and for me in it (are) uses other (18)",
      transliteration:
        "qāla hiya ʿaṣāya atawakka-u ʿalayhā wa-ahushu bihā ʿalā ghanamī waliya fīhā maāribu ukh'rā ",
      verse: 2366,
      juz: 16,
      surah: 20,
    },
    {
      number: 19,
      image: "",
      text: "He said Throw it down O Musa (19)",
      transliteration: "qāla alqihā yāmūsā ",
      verse: 2367,
      juz: 16,
      surah: 20,
    },
    {
      number: 20,
      image: "",
      text: "So he threw it down and behold It (was) a snake moving swiftly (20)",
      transliteration: "fa-alqāhā fa-idhā hiya ḥayyatun tasʿā ",
      verse: 2368,
      juz: 16,
      surah: 20,
    },
    {
      number: 21,
      image: "",
      text: "He said Seize it and (do) not fear We will return it (to) its state the former (21)",
      transliteration: "qāla khudh'hā walā takhaf sanuʿīduhā sīratahā l-ūlā ",
      verse: 2369,
      juz: 16,
      surah: 20,
    },
    {
      number: 22,
      image: "",
      text: "And draw near your hand to your side it will come out white without any without any disease (as) a sign another (22)",
      transliteration:
        "wa-uḍ'mum yadaka ilā janāḥika takhruj bayḍāa min ghayri sūin āyatan ukh'rā ",
      verse: 2370,
      juz: 16,
      surah: 20,
    },
    {
      number: 23,
      image: "",
      text: "That We may show you of Our Signs the Greatest (23)",
      transliteration: "linuriyaka min āyātinā l-kub'rā ",
      verse: 2371,
      juz: 16,
      surah: 20,
    },
    {
      number: 24,
      image: "",
      text: "Go to Firaun Indeed, he (has) transgressed (24)",
      transliteration: "idh'hab ilā fir'ʿawna innahu ṭaghā ",
      verse: 2372,
      juz: 16,
      surah: 20,
    },
    {
      number: 25,
      image: "",
      text: "He said My Lord Expand for me my breast (25)",
      transliteration: "qāla rabbi ish'raḥ lī ṣadrī ",
      verse: 2373,
      juz: 16,
      surah: 20,
    },
    {
      number: 26,
      image: "",
      text: "And ease for me my task (26)",
      transliteration: "wayassir lī amrī ",
      verse: 2374,
      juz: 16,
      surah: 20,
    },
    {
      number: 27,
      image: "",
      text: "And untie (the) knot from my tongue (27)",
      transliteration: "wa-uḥ'lul ʿuq'datan min lisānī ",
      verse: 2375,
      juz: 16,
      surah: 20,
    },
    {
      number: 28,
      image: "",
      text: "That they may understand my speech (28)",
      transliteration: "yafqahū qawlī ",
      verse: 2376,
      juz: 16,
      surah: 20,
    },
    {
      number: 29,
      image: "",
      text: "And appoint for me a minister from my family (29)",
      transliteration: "wa-ij'ʿal lī wazīran min ahlī ",
      verse: 2377,
      juz: 16,
      surah: 20,
    },
    {
      number: 30,
      image: "",
      text: "Harun my brother (30)",
      transliteration: "hārūna akhī ",
      verse: 2378,
      juz: 16,
      surah: 20,
    },
    {
      number: 31,
      image: "",
      text: "Reinforce through him my strength (31)",
      transliteration: "ush'dud bihi azrī ",
      verse: 2379,
      juz: 16,
      surah: 20,
    },
    {
      number: 32,
      image: "",
      text: "And make him share [in] my task (32)",
      transliteration: "wa-ashrik'hu fī amrī ",
      verse: 2380,
      juz: 16,
      surah: 20,
    },
    {
      number: 33,
      image: "",
      text: "That we may glorify You much (33)",
      transliteration: "kay nusabbiḥaka kathīran ",
      verse: 2381,
      juz: 16,
      surah: 20,
    },
    {
      number: 34,
      image: "",
      text: "And [we] remember You much (34)",
      transliteration: "wanadhkuraka kathīran ",
      verse: 2382,
      juz: 16,
      surah: 20,
    },
    {
      number: 35,
      image: "",
      text: "Indeed, [You] You are of us All-Seer (35)",
      transliteration: "innaka kunta binā baṣīran ",
      verse: 2383,
      juz: 16,
      surah: 20,
    },
    {
      number: 36,
      image: "",
      text: "He said Verily you are granted your request O Musa (36)",
      transliteration: "qāla qad ūtīta su'laka yāmūsā ",
      verse: 2384,
      juz: 16,
      surah: 20,
    },
    {
      number: 37,
      image: "",
      text: "And indeed We conferred a favor on you another time another time (37)",
      transliteration: "walaqad manannā ʿalayka marratan ukh'rā ",
      verse: 2385,
      juz: 16,
      surah: 20,
    },
    {
      number: 38,
      image: "",
      text: "When We inspired to your mother what is inspired (38)",
      transliteration: "idh awḥaynā ilā ummika mā yūḥā ",
      verse: 2386,
      juz: 16,
      surah: 20,
    },
    {
      number: 39,
      image: "",
      text: "That cast him in the chest then cast it in the river then let cast it the river on the bank will take him an enemy to Me and an enemy to him And I cast over you love from Me and that you may be brought up under My eye (39)",
      transliteration:
        "ani iq'dhifīhi fī l-tābūti fa-iq'dhifīhi fī l-yami falyul'qihi l-yamu bil-sāḥili yakhudh'hu ʿaduwwun lī waʿaduwwun lahu wa-alqaytu ʿalayka maḥabbatan minnī walituṣ'naʿa ʿalā ʿaynī ",
      verse: 2387,
      juz: 16,
      surah: 20,
    },
    {
      number: 40,
      image: "",
      text: "When was going your sister and she said Shall I show you [to] (one) who will nurse and rear him So We returned you to your mother that may be cooled her eyes and not she grieves And you killed a man but We saved you from the distress and We tried you (with) a trial Then you remained (some) years with (the) people (of) Madyan Then you came at the decreed (time) O Musa (40)",
      transliteration:
        "idh tamshī ukh'tuka fataqūlu hal adullukum ʿalā man yakfuluhu farajaʿnāka ilā ummika kay taqarra ʿaynuhā walā taḥzana waqatalta nafsan fanajjaynāka mina l-ghami wafatannāka futūnan falabith'ta sinīna fī ahli madyana thumma ji'ta ʿalā qadarin yāmūsā ",
      verse: 2388,
      juz: 16,
      surah: 20,
    },
    {
      number: 41,
      image: "",
      text: "And I (have) chosen you for Myself (41)",
      transliteration: "wa-iṣ'ṭanaʿtuka linafsī ",
      verse: 2389,
      juz: 16,
      surah: 20,
    },
    {
      number: 42,
      image: "",
      text: "Go you and your brother with My Signs and (do) not slacken in My remembrance (42)",
      transliteration: "idh'hab anta wa-akhūka biāyātī walā taniyā fī dhik'rī ",
      verse: 2390,
      juz: 16,
      surah: 20,
    },
    {
      number: 43,
      image: "",
      text: "Go, both of you to Firaun Indeed, he (has) transgressed (43)",
      transliteration: "idh'habā ilā fir'ʿawna innahu ṭaghā ",
      verse: 2391,
      juz: 16,
      surah: 20,
    },
    {
      number: 44,
      image: "",
      text: "And speak to him a word gentle perhaps he may take heed or fear (44)",
      transliteration:
        "faqūlā lahu qawlan layyinan laʿallahu yatadhakkaru aw yakhshā ",
      verse: 2392,
      juz: 16,
      surah: 20,
    },
    {
      number: 45,
      image: "",
      text: "They said Our Lord Indeed, we fear that he will hasten against us or that he will transgress (45)",
      transliteration:
        "qālā rabbanā innanā nakhāfu an yafruṭa ʿalaynā aw an yaṭghā ",
      verse: 2393,
      juz: 16,
      surah: 20,
    },
    {
      number: 46,
      image: "",
      text: "He said (Do) not fear Indeed, I Am with you both I hear and I see (46)",
      transliteration: "qāla lā takhāfā innanī maʿakumā asmaʿu wa-arā ",
      verse: 2394,
      juz: 16,
      surah: 20,
    },
    {
      number: 47,
      image: "",
      text: "So go to him and say Indeed, we both (are) Messengers (of) your Lord so send with us (the) Children of Israel (the) Children of Israel and (do) not torment them Verily we came to you with a Sign from your Lord And peace on (one) who follows the Guidance (47)",
      transliteration:
        "fatiyāhu faqūlā innā rasūlā rabbika fa-arsil maʿanā banī is'rāīla walā tuʿadhib'hum qad ji'nāka biāyatin min rabbika wal-salāmu ʿalā mani ittabaʿa l-hudā ",
      verse: 2395,
      juz: 16,
      surah: 20,
    },
    {
      number: 48,
      image: "",
      text: "Indeed, we verily it has been revealed to us that the punishment (will be) on (one) who denies and turns away (48)",
      transliteration:
        "innā qad ūḥiya ilaynā anna l-ʿadhāba ʿalā man kadhaba watawallā ",
      verse: 2396,
      juz: 16,
      surah: 20,
    },
    {
      number: 49,
      image: "",
      text: "He said Then who (is) your Lord O Musa (49)",
      transliteration: "qāla faman rabbukumā yāmūsā ",
      verse: 2397,
      juz: 16,
      surah: 20,
    },
    {
      number: 50,
      image: "",
      text: "He said Our Lord (is) the One Who gave (to) every thing its form then He guided (it) (50)",
      transliteration:
        "qāla rabbunā alladhī aʿṭā kulla shayin khalqahu thumma hadā ",
      verse: 2398,
      juz: 16,
      surah: 20,
    },
    {
      number: 51,
      image: "",
      text: "He said Then what (is the) case (of) the generations (of) the former (51)",
      transliteration: "qāla famā bālu l-qurūni l-ūlā ",
      verse: 2399,
      juz: 16,
      surah: 20,
    },
    {
      number: 52,
      image: "",
      text: "He said Its knowledge (is) with my Lord in a Record Not errs my Lord and not forgets (52)",
      transliteration:
        "qāla ʿil'muhā ʿinda rabbī fī kitābin lā yaḍillu rabbī walā yansā ",
      verse: 2400,
      juz: 16,
      surah: 20,
    },
    {
      number: 53,
      image: "",
      text: "The One Who made for you the earth (as) a bed and inserted for you therein ways and sent down from the sky water then We (have) brought forth with it pairs of plants diverse (53)",
      transliteration:
        "alladhī jaʿala lakumu l-arḍa mahdan wasalaka lakum fīhā subulan wa-anzala mina l-samāi māan fa-akhrajnā bihi azwājan min nabātin shattā ",
      verse: 2401,
      juz: 16,
      surah: 20,
    },
    {
      number: 54,
      image: "",
      text: "Eat and pasture your cattle Indeed in that surely (are) Signs for possessors (of) intelligence (54)",
      transliteration:
        "kulū wa-ir'ʿaw anʿāmakum inna fī dhālika laāyātin li-ulī l-nuhā ",
      verse: 2402,
      juz: 16,
      surah: 20,
    },
    {
      number: 55,
      image: "",
      text: "From it We created you and in it We will return you and from it We will bring you out time another (55)",
      transliteration:
        "min'hā khalaqnākum wafīhā nuʿīdukum wamin'hā nukh'rijukum tāratan ukh'rā ",
      verse: 2403,
      juz: 16,
      surah: 20,
    },
    {
      number: 56,
      image: "",
      text: "And verily We showed him Our Signs all of them but he denied and refused (56)",
      transliteration: "walaqad araynāhu āyātinā kullahā fakadhaba wa-abā ",
      verse: 2404,
      juz: 16,
      surah: 20,
    },
    {
      number: 57,
      image: "",
      text: "He said Have you come to us to drive us out of our land with your magic O Musa (57)",
      transliteration:
        "qāla aji'tanā litukh'rijanā min arḍinā bisiḥ'rika yāmūsā ",
      verse: 2405,
      juz: 16,
      surah: 20,
    },
    {
      number: 58,
      image: "",
      text: "Then we will surely produce for you magic like it So make between us and between you an appointment not we will fail it [we] and not you (in) a place even (58)",
      transliteration:
        "falanatiyannaka bisiḥ'rin mith'lihi fa-ij'ʿal baynanā wabaynaka mawʿidan lā nukh'lifuhu naḥnu walā anta makānan suwan ",
      verse: 2406,
      juz: 16,
      surah: 20,
    },
    {
      number: 59,
      image: "",
      text: "He said Your appointment (is on the) day (of) the festival and that will be assembled the people (at) forenoon (59)",
      transliteration:
        "qāla mawʿidukum yawmu l-zīnati wa-an yuḥ'shara l-nāsu ḍuḥan ",
      verse: 2407,
      juz: 16,
      surah: 20,
    },
    {
      number: 60,
      image: "",
      text: "Then went away Firaun and put together his plan then came (60)",
      transliteration: "fatawallā fir'ʿawnu fajamaʿa kaydahu thumma atā ",
      verse: 2408,
      juz: 16,
      surah: 20,
    },
    {
      number: 61,
      image: "",
      text: "Said to them Musa Woe to you (Do) not invent against Allah a lie lest He will destroy you with a punishment And verily he failed who invented (61)",
      transliteration:
        "qāla lahum mūsā waylakum lā taftarū ʿalā l-lahi kadhiban fayus'ḥitakum biʿadhābin waqad khāba mani if'tarā ",
      verse: 2409,
      juz: 16,
      surah: 20,
    },
    {
      number: 62,
      image: "",
      text: "Then they disputed (in) their affair among them and they kept secret the private conversation (62)",
      transliteration: "fatanāzaʿū amrahum baynahum wa-asarrū l-najwā ",
      verse: 2410,
      juz: 16,
      surah: 20,
    },
    {
      number: 63,
      image: "",
      text: "They said Indeed these two [two] magicians they intend that they drive you out of your land with their magic and do away with your way the exemplary (63)",
      transliteration:
        "qālū in hādhāni lasāḥirāni yurīdāni an yukh'rijākum min arḍikum bisiḥ'rihimā wayadhhabā biṭarīqatikumu l-muth'lā ",
      verse: 2411,
      juz: 16,
      surah: 20,
    },
    {
      number: 64,
      image: "",
      text: "So put together your plan then come (in) a line And verily (will be) successful today who overcomes (64)",
      transliteration:
        "fa-ajmiʿū kaydakum thumma i'tū ṣaffan waqad aflaḥa l-yawma mani is'taʿlā ",
      verse: 2412,
      juz: 16,
      surah: 20,
    },
    {
      number: 65,
      image: "",
      text: "They said O Musa Either [that] you throw or [that] we will be the first who throws (65)",
      transliteration:
        "qālū yāmūsā immā an tul'qiya wa-immā an nakūna awwala man alqā ",
      verse: 2413,
      juz: 16,
      surah: 20,
    },
    {
      number: 66,
      image: "",
      text: "He said Nay you throw Then behold Their ropes and their staffs seemed to him by their magic that they (were) moving (66)",
      transliteration:
        "qāla bal alqū fa-idhā ḥibāluhum waʿiṣiyyuhum yukhayyalu ilayhi min siḥ'rihim annahā tasʿā ",
      verse: 2414,
      juz: 16,
      surah: 20,
    },
    {
      number: 67,
      image: "",
      text: "So sensed in himself a fear Musa (67)",
      transliteration: "fa-awjasa fī nafsihi khīfatan mūsā ",
      verse: 2415,
      juz: 16,
      surah: 20,
    },
    {
      number: 68,
      image: "",
      text: "We said (Do) not fear Indeed, you you (will be) superior (68)",
      transliteration: "qul'nā lā takhaf innaka anta l-aʿlā ",
      verse: 2416,
      juz: 16,
      surah: 20,
    },
    {
      number: 69,
      image: "",
      text: "And throw what (is) in your right hand it will swallow up what they have made Only they (have) made a trick (of) a magician and not will be successful the magician wherever he comes (69)",
      transliteration:
        "wa-alqi mā fī yamīnika talqaf mā ṣanaʿū innamā ṣanaʿū kaydu sāḥirin walā yuf'liḥu l-sāḥiru ḥaythu atā ",
      verse: 2417,
      juz: 16,
      surah: 20,
    },
    {
      number: 70,
      image: "",
      text: "So were thrown down the magicians prostrating They said We believe in (the) Lord (of) Harun and Musa (70)",
      transliteration:
        "fa-ul'qiya l-saḥaratu sujjadan qālū āmannā birabbi hārūna wamūsā ",
      verse: 2418,
      juz: 16,
      surah: 20,
    },
    {
      number: 71,
      image: "",
      text: "He said You believe [to] him before [that] I gave permission to you Indeed, he (is) your chief the one who taught you the magic So surely I will cut off your hands and your feet of opposite sides and surely I will crucify you on (the) trunks (of) date-palms and surely you will know which of us (is) more severe (in) punishment and more lasting (71)",
      transliteration:
        "qāla āmantum lahu qabla an ādhana lakum innahu lakabīrukumu alladhī ʿallamakumu l-siḥ'ra fala-uqaṭṭiʿanna aydiyakum wa-arjulakum min khilāfin wala-uṣallibannakum fī judhūʿi l-nakhli walataʿlamunna ayyunā ashaddu ʿadhāban wa-abqā ",
      verse: 2419,
      juz: 16,
      surah: 20,
    },
    {
      number: 72,
      image: "",
      text: "They said Never we will prefer you over what has come to us of the clear proofs and the One Who created us So decree whatever you (are) decreeing Only you can decree (for) this life (of) the world (72)",
      transliteration:
        "qālū lan nu'thiraka ʿalā mā jāanā mina l-bayināti wa-alladhī faṭaranā fa-iq'ḍi mā anta qāḍin innamā taqḍī hādhihi l-ḥayata l-dun'yā ",
      verse: 2420,
      juz: 16,
      surah: 20,
    },
    {
      number: 73,
      image: "",
      text: "Indeed, [we] we believe in our Lord that He may forgive for us our sins and what you compelled us on it of the magic And Allah (is) Best and Ever Lasting (73)",
      transliteration:
        "innā āmannā birabbinā liyaghfira lanā khaṭāyānā wamā akrahtanā ʿalayhi mina l-siḥ'ri wal-lahu khayrun wa-abqā ",
      verse: 2421,
      juz: 16,
      surah: 20,
    },
    {
      number: 74,
      image: "",
      text: "Indeed, he who comes (to) his Lord (as) a criminal then indeed for him (is) Hell Not he will die in it and not live (74)",
      transliteration:
        "innahu man yati rabbahu muj'riman fa-inna lahu jahannama lā yamūtu fīhā walā yaḥyā ",
      verse: 2422,
      juz: 16,
      surah: 20,
    },
    {
      number: 75,
      image: "",
      text: "But whoever comes to Him (as) a believer verily he has done the righteous deeds then those for them (will be) the ranks [the] high (75)",
      transliteration:
        "waman yatihi mu'minan qad ʿamila l-ṣāliḥāti fa-ulāika lahumu l-darajātu l-ʿulā ",
      verse: 2423,
      juz: 16,
      surah: 20,
    },
    {
      number: 76,
      image: "",
      text: "Gardens (of) Eden flows from underneath them the rivers abiding forever in it And that (is) the reward (for him) who purifies himself (76)",
      transliteration:
        "jannātu ʿadnin tajrī min taḥtihā l-anhāru khālidīna fīhā wadhālika jazāu man tazakkā ",
      verse: 2424,
      juz: 16,
      surah: 20,
    },
    {
      number: 77,
      image: "",
      text: "And verily We inspired to Musa that Travel by night with My slaves and strike for them a path in the sea dry not fearing to be overtaken and not being afraid (77)",
      transliteration:
        "walaqad awḥaynā ilā mūsā an asri biʿibādī fa-iḍ'rib lahum ṭarīqan fī l-baḥri yabasan lā takhāfu darakan walā takhshā ",
      verse: 2425,
      juz: 16,
      surah: 20,
    },
    {
      number: 78,
      image: "",
      text: "Then followed them Firaun with his forces but covered them from the sea what covered them (78)",
      transliteration:
        "fa-atbaʿahum fir'ʿawnu bijunūdihi faghashiyahum mina l-yami mā ghashiyahum ",
      verse: 2426,
      juz: 16,
      surah: 20,
    },
    {
      number: 79,
      image: "",
      text: "And led astray Firaun his people and (did) not guide them (79)",
      transliteration: "wa-aḍalla fir'ʿawnu qawmahu wamā hadā ",
      verse: 2427,
      juz: 16,
      surah: 20,
    },
    {
      number: 80,
      image: "",
      text: "O Children of Israel O Children of Israel Verily We delivered you from your enemy and We made a covenant with you on (the) side (of) the Mount the right and We sent down to you the Manna and the quails (80)",
      transliteration:
        "yābanī is'rāīla qad anjaynākum min ʿaduwwikum wawāʿadnākum jāniba l-ṭūri l-aymana wanazzalnā ʿalaykumu l-mana wal-salwā ",
      verse: 2428,
      juz: 16,
      surah: 20,
    },
    {
      number: 81,
      image: "",
      text: "Eat of (the) good things which We have provided you and (do) not transgress therein lest should descend upon you My Anger And whoever on whom descends on whom descends My Anger indeed he (has) perished (81)",
      transliteration:
        "kulū min ṭayyibāti mā razaqnākum walā taṭghaw fīhi fayaḥilla ʿalaykum ghaḍabī waman yaḥlil ʿalayhi ghaḍabī faqad hawā ",
      verse: 2429,
      juz: 16,
      surah: 20,
    },
    {
      number: 82,
      image: "",
      text: "But indeed, I Am the Perpetual Forgiver of whoever repents and believes and does righteous (deeds) then remains guided (82)",
      transliteration:
        "wa-innī laghaffārun liman tāba waāmana waʿamila ṣāliḥan thumma ih'tadā ",
      verse: 2430,
      juz: 16,
      surah: 20,
    },
    {
      number: 83,
      image: "",
      text: "And what made you hasten from your people O Musa (83)",
      transliteration: "wamā aʿjalaka ʿan qawmika yāmūsā ",
      verse: 2431,
      juz: 16,
      surah: 20,
    },
    {
      number: 84,
      image: "",
      text: "He said They (are) close upon my tracks and I hastened to you my Lord that You be pleased (84)",
      transliteration:
        "qāla hum ulāi ʿalā atharī waʿajil'tu ilayka rabbi litarḍā ",
      verse: 2432,
      juz: 16,
      surah: 20,
    },
    {
      number: 85,
      image: "",
      text: "He said But indeed, We [verily] We (have) tried your people after you after you and has led them astray the Samiri (85)",
      transliteration:
        "qāla fa-innā qad fatannā qawmaka min baʿdika wa-aḍallahumu l-sāmiriyu ",
      verse: 2433,
      juz: 16,
      surah: 20,
    },
    {
      number: 86,
      image: "",
      text: "Then Musa returned Then Musa returned to his people angry (and) sorrowful He said O my people Did not promise you your Lord a promise good Then, did seem long to you the promise or did you desire that descend upon you (the) Anger of your Lord so you broke (the) promise to me (86)",
      transliteration:
        "farajaʿa mūsā ilā qawmihi ghaḍbāna asifan qāla yāqawmi alam yaʿid'kum rabbukum waʿdan ḥasanan afaṭāla ʿalaykumu l-ʿahdu am aradttum an yaḥilla ʿalaykum ghaḍabun min rabbikum fa-akhlaftum mawʿidī ",
      verse: 2434,
      juz: 16,
      surah: 20,
    },
    {
      number: 87,
      image: "",
      text: "They said Not we broke promise to you by our will but we [we] were made to carry burdens from ornaments (of) the people so we threw them and thus threw the Samiri (87)",
      transliteration:
        "qālū mā akhlafnā mawʿidaka bimalkinā walākinnā ḥummil'nā awzāran min zīnati l-qawmi faqadhafnāhā fakadhālika alqā l-sāmiriyu ",
      verse: 2435,
      juz: 16,
      surah: 20,
    },
    {
      number: 88,
      image: "",
      text: "Then he brought forth for them a calf's body it had a lowing sound and they said This (is) your god and the god (of) Musa but he forgot (88)",
      transliteration:
        "fa-akhraja lahum ʿij'lan jasadan lahu khuwārun faqālū hādhā ilāhukum wa-ilāhu mūsā fanasiya ",
      verse: 2436,
      juz: 16,
      surah: 20,
    },
    {
      number: 89,
      image: "",
      text: "Then, did not they see that not it (could) return to them a word and not possess for them any harm and not any benefit (89)",
      transliteration:
        "afalā yarawna allā yarjiʿu ilayhim qawlan walā yamliku lahum ḍarran walā nafʿan ",
      verse: 2437,
      juz: 16,
      surah: 20,
    },
    {
      number: 90,
      image: "",
      text: "And verily (had) said to them Harun before before O my people Only you are being tested by it and indeed your Lord (is) the Most Gracious so follow me and obey my order (90)",
      transliteration:
        "walaqad qāla lahum hārūnu min qablu yāqawmi innamā futintum bihi wa-inna rabbakumu l-raḥmānu fa-ittabiʿūnī wa-aṭīʿū amrī ",
      verse: 2438,
      juz: 16,
      surah: 20,
    },
    {
      number: 91,
      image: "",
      text: "They said Never we will cease being devoted to it being devoted to it until returns to us Musa (91)",
      transliteration:
        "qālū lan nabraḥa ʿalayhi ʿākifīna ḥattā yarjiʿa ilaynā mūsā ",
      verse: 2439,
      juz: 16,
      surah: 20,
    },
    {
      number: 92,
      image: "",
      text: "He said O Harun What prevented you when you saw them going astray (92)",
      transliteration: "qāla yāhārūnu mā manaʿaka idh ra-aytahum ḍallū ",
      verse: 2440,
      juz: 16,
      surah: 20,
    },
    {
      number: 93,
      image: "",
      text: "That not you follow me Then, have you disobeyed my order (93)",
      transliteration: "allā tattabiʿani afaʿaṣayta amrī ",
      verse: 2441,
      juz: 16,
      surah: 20,
    },
    {
      number: 94,
      image: "",
      text: "He said O son of my mother (Do) not seize (me) by my beard and not by my head Indeed, I [I] feared that you would say You caused division between (the) Children of Israel (the) Children of Israel and not you respect my word (94)",
      transliteration:
        "qāla yabna-umma lā takhudh biliḥ'yatī walā birasī innī khashītu an taqūla farraqta bayna banī is'rāīla walam tarqub qawlī ",
      verse: 2442,
      juz: 16,
      surah: 20,
    },
    {
      number: 95,
      image: "",
      text: "He said Then what (is) your case O Samiri (95)",
      transliteration: "qāla famā khaṭbuka yāsāmiriyyu ",
      verse: 2443,
      juz: 16,
      surah: 20,
    },
    {
      number: 96,
      image: "",
      text: "He said I perceived what not they perceive in it so I took a handful from (the) track (of) the Messenger then threw it and thus suggested to me my soul (96)",
      transliteration:
        "qāla baṣur'tu bimā lam yabṣurū bihi faqabaḍtu qabḍatan min athari l-rasūli fanabadhtuhā wakadhālika sawwalat lī nafsī ",
      verse: 2444,
      juz: 16,
      surah: 20,
    },
    {
      number: 97,
      image: "",
      text: "He said Then go And indeed for you in the life that you will say (Do) not touch And indeed for you (is) an appointment never you will fail to (keep) it And look at your god that which you have remained to it devoted Surely we will burn it then certainly we will scatter it in the sea (in) particles (97)",
      transliteration:
        "qāla fa-idh'hab fa-inna laka fī l-ḥayati an taqūla lā misāsa wa-inna laka mawʿidan lan tukh'lafahu wa-unẓur ilā ilāhika alladhī ẓalta ʿalayhi ʿākifan lanuḥarriqannahu thumma lanansifannahu fī l-yami nasfan ",
      verse: 2445,
      juz: 16,
      surah: 20,
    },
    {
      number: 98,
      image: "",
      text: "Only your God (is) Allah the One (there is) no god but He He has encompassed all things (in) knowledge (98)",
      transliteration:
        "innamā ilāhukumu l-lahu alladhī lā ilāha illā huwa wasiʿa kulla shayin ʿil'man ",
      verse: 2446,
      juz: 16,
      surah: 20,
    },
    {
      number: 99,
      image: "",
      text: "Thus We relate to you from (the) news (of) what has preceded has preceded And certainly We have given you from Us a Reminder (99)",
      transliteration:
        "kadhālika naquṣṣu ʿalayka min anbāi mā qad sabaqa waqad ātaynāka min ladunnā dhik'ran ",
      verse: 2447,
      juz: 16,
      surah: 20,
    },
    {
      number: 100,
      image: "",
      text: "Whoever turns away from it then indeed, he will bear (on the) Day (of) Resurrection a burden (100)",
      transliteration:
        "man aʿraḍa ʿanhu fa-innahu yaḥmilu yawma l-qiyāmati wiz'ran ",
      verse: 2448,
      juz: 16,
      surah: 20,
    },
    {
      number: 101,
      image: "",
      text: "Abiding forever in it and evil for them (on the) Day (of) the Resurrection (as) a load (101)",
      transliteration: "khālidīna fīhi wasāa lahum yawma l-qiyāmati ḥim'lan ",
      verse: 2449,
      juz: 16,
      surah: 20,
    },
    {
      number: 102,
      image: "",
      text: "(The) Day will be blown in the Trumpet and We will gather the criminals that Day blue-eyed (102)",
      transliteration:
        "yawma yunfakhu fī l-ṣūri wanaḥshuru l-muj'rimīna yawma-idhin zur'qan ",
      verse: 2450,
      juz: 16,
      surah: 20,
    },
    {
      number: 103,
      image: "",
      text: "They are murmuring among themselves Not you remained except (for) ten (103)",
      transliteration: "yatakhāfatūna baynahum in labith'tum illā ʿashran ",
      verse: 2451,
      juz: 16,
      surah: 20,
    },
    {
      number: 104,
      image: "",
      text: "We know best what they will say when will say (the) best of them (in) conduct Not you remained except (for) a day (104)",
      transliteration:
        "naḥnu aʿlamu bimā yaqūlūna idh yaqūlu amthaluhum ṭarīqatan in labith'tum illā yawman ",
      verse: 2452,
      juz: 16,
      surah: 20,
    },
    {
      number: 105,
      image: "",
      text: "And they ask you about the mountains so say Will blast them my Lord (into) particles (105)",
      transliteration: "wayasalūnaka ʿani l-jibāli faqul yansifuhā rabbī nasfan ",
      verse: 2453,
      juz: 16,
      surah: 20,
    },
    {
      number: 106,
      image: "",
      text: "Then He will leave it a level plain (106)",
      transliteration: "fayadharuhā qāʿan ṣafṣafan ",
      verse: 2454,
      juz: 16,
      surah: 20,
    },
    {
      number: 107,
      image: "",
      text: "Not you will see in it any crookedness and not any curve (107)",
      transliteration: "lā tarā fīhā ʿiwajan walā amtan ",
      verse: 2455,
      juz: 16,
      surah: 20,
    },
    {
      number: 108,
      image: "",
      text: "On that Day they will follow the caller no deviation from it And (will be) humbled the voices for the Most Gracious so not you will hear except a faint sound (108)",
      transliteration:
        "yawma-idhin yattabiʿūna l-dāʿiya lā ʿiwaja lahu wakhashaʿati l-aṣwātu lilrraḥmāni falā tasmaʿu illā hamsan ",
      verse: 2456,
      juz: 16,
      surah: 20,
    },
    {
      number: 109,
      image: "",
      text: "(On) that Day not will benefit the intercession except (to) whom has given permission [to him] the Most Gracious and He has accepted for him a word (109)",
      transliteration:
        "yawma-idhin lā tanfaʿu l-shafāʿatu illā man adhina lahu l-raḥmānu waraḍiya lahu qawlan ",
      verse: 2457,
      juz: 16,
      surah: 20,
    },
    {
      number: 110,
      image: "",
      text: "He knows what (is) before them (is) before them and what (is) behind them while not they encompass it (in) knowledge (110)",
      transliteration:
        "yaʿlamu mā bayna aydīhim wamā khalfahum walā yuḥīṭūna bihi ʿil'man ",
      verse: 2458,
      juz: 16,
      surah: 20,
    },
    {
      number: 111,
      image: "",
      text: "And (will be) humbled the faces before the Ever-Living the Self-Subsisting And verily will have failed (he) who carried wrongdoing (111)",
      transliteration:
        "waʿanati l-wujūhu lil'ḥayyi l-qayūmi waqad khāba man ḥamala ẓul'man ",
      verse: 2459,
      juz: 16,
      surah: 20,
    },
    {
      number: 112,
      image: "",
      text: "But (he) who does of the righteous deeds while he (is) a believer then not he will fear injustice and not deprivation (112)",
      transliteration:
        "waman yaʿmal mina l-ṣāliḥāti wahuwa mu'minun falā yakhāfu ẓul'man walā haḍman ",
      verse: 2460,
      juz: 16,
      surah: 20,
    },
    {
      number: 113,
      image: "",
      text: "And thus We have sent it down (the) Quran (in) Arabic and We have explained in it of the warnings that they may fear or it may cause [for] them remembrance (113)",
      transliteration:
        "wakadhālika anzalnāhu qur'ānan ʿarabiyyan waṣarrafnā fīhi mina l-waʿīdi laʿallahum yattaqūna aw yuḥ'dithu lahum dhik'ran ",
      verse: 2461,
      juz: 16,
      surah: 20,
    },
    {
      number: 114,
      image: "",
      text: "So high (above all) (is) Allah the King the True And (do) not hasten with the Quran before before [that] is completed to you its revelation and say My Lord Increase me (in) knowledge (114)",
      transliteration:
        "fataʿālā l-lahu l-maliku l-ḥaqu walā taʿjal bil-qur'āni min qabli an yuq'ḍā ilayka waḥyuhu waqul rabbi zid'nī ʿil'man ",
      verse: 2462,
      juz: 16,
      surah: 20,
    },
    {
      number: 115,
      image: "",
      text: "And verily We made a covenant with Adam before before but he forgot and not We found in him determination (115)",
      transliteration:
        "walaqad ʿahid'nā ilā ādama min qablu fanasiya walam najid lahu ʿazman ",
      verse: 2463,
      juz: 16,
      surah: 20,
    },
    {
      number: 116,
      image: "",
      text: "And when We said to the Angels Prostrate to Adam then they prostrated except Iblis he refused (116)",
      transliteration:
        "wa-idh qul'nā lil'malāikati us'judū liādama fasajadū illā ib'līsa abā ",
      verse: 2464,
      juz: 16,
      surah: 20,
    },
    {
      number: 117,
      image: "",
      text: "Then We said O Adam Indeed this (is) an enemy to you and to your wife So not (let) him drive you both from Paradise so (that) you would suffer (117)",
      transliteration:
        "faqul'nā yāādamu inna hādhā ʿaduwwun laka walizawjika falā yukh'rijannakumā mina l-janati fatashqā ",
      verse: 2465,
      juz: 16,
      surah: 20,
    },
    {
      number: 118,
      image: "",
      text: "Indeed for you that not you will be hungry therein and not you will be unclothed (118)",
      transliteration: "inna laka allā tajūʿa fīhā walā taʿrā ",
      verse: 2466,
      juz: 16,
      surah: 20,
    },
    {
      number: 119,
      image: "",
      text: "And that you not will suffer from thirst therein and not exposed to the sun's heat (119)",
      transliteration: "wa-annaka lā taẓma-u fīhā walā taḍḥā ",
      verse: 2467,
      juz: 16,
      surah: 20,
    },
    {
      number: 120,
      image: "",
      text: "Then whispered to him Shaitaan he said O Adam Shall I direct you to (the) tree (of) the Eternity and a kingdom not (that will) deteriorate (120)",
      transliteration:
        "fawaswasa ilayhi l-shayṭānu qāla yāādamu hal adulluka ʿalā shajarati l-khul'di wamul'kin lā yablā ",
      verse: 2468,
      juz: 16,
      surah: 20,
    },
    {
      number: 121,
      image: "",
      text: "Then they both ate from it so became apparent to them their shame and they began (to) fasten on themselves from (the) leaves (of) Paradise And Adam disobeyed And Adam disobeyed his Lord and erred (121)",
      transliteration:
        "fa-akalā min'hā fabadat lahumā sawātuhumā waṭafiqā yakhṣifāni ʿalayhimā min waraqi l-janati waʿaṣā ādamu rabbahu faghawā ",
      verse: 2469,
      juz: 16,
      surah: 20,
    },
    {
      number: 122,
      image: "",
      text: "Then chose him his Lord and turned to him and guided (him) (122)",
      transliteration: "thumma ij'tabāhu rabbuhu fatāba ʿalayhi wahadā ",
      verse: 2470,
      juz: 16,
      surah: 20,
    },
    {
      number: 123,
      image: "",
      text: "He said Go down from it all some of you to others (as) enemy Then if comes to you from Me guidance then whoever follows My guidance then not he will go astray and not suffer (123)",
      transliteration:
        "qāla ih'biṭā min'hā jamīʿan baʿḍukum libaʿḍin ʿaduwwun fa-immā yatiyannakum minnī hudan famani ittabaʿa hudāya falā yaḍillu walā yashqā ",
      verse: 2471,
      juz: 16,
      surah: 20,
    },
    {
      number: 124,
      image: "",
      text: "And whoever turns away from My remembrance then indeed for him (is) a life straitened and We will gather him (on the) Day (of) the Resurrection blind (124)",
      transliteration:
        "waman aʿraḍa ʿan dhik'rī fa-inna lahu maʿīshatan ḍankan wanaḥshuruhu yawma l-qiyāmati aʿmā ",
      verse: 2472,
      juz: 16,
      surah: 20,
    },
    {
      number: 125,
      image: "",
      text: "He will say My Lord Why You raised me blind while [verily] I had sight (125)",
      transliteration: "qāla rabbi lima ḥashartanī aʿmā waqad kuntu baṣīran ",
      verse: 2473,
      juz: 16,
      surah: 20,
    },
    {
      number: 126,
      image: "",
      text: "He will say Thus came to you Our Signs but you forgot them and thus today you will be forgotten (126)",
      transliteration:
        "qāla kadhālika atatka āyātunā fanasītahā wakadhālika l-yawma tunsā ",
      verse: 2474,
      juz: 16,
      surah: 20,
    },
    {
      number: 127,
      image: "",
      text: "And thus We recompense (he) who transgresses and not believes in (the) Signs (of) his Lord And surely (the) punishment (of) the Hereafter (is) more severe and more lasting (127)",
      transliteration:
        "wakadhālika najzī man asrafa walam yu'min biāyāti rabbihi walaʿadhābu l-ākhirati ashaddu wa-abqā ",
      verse: 2475,
      juz: 16,
      surah: 20,
    },
    {
      number: 128,
      image: "",
      text: "Then has not it guided [for] them how many We (have) destroyed before them of the generations (as) they walk in their dwellings Indeed in that surely (are) Signs for possessors (of) intelligence (128)",
      transliteration:
        "afalam yahdi lahum kam ahlaknā qablahum mina l-qurūni yamshūna fī masākinihim inna fī dhālika laāyātin li-ulī l-nuhā ",
      verse: 2476,
      juz: 16,
      surah: 20,
    },
    {
      number: 129,
      image: "",
      text: "And if not (for) a Word (that) preceded from your Lord surely (would) have been an obligation and a term determined (129)",
      transliteration:
        "walawlā kalimatun sabaqat min rabbika lakāna lizāman wa-ajalun musamman ",
      verse: 2477,
      juz: 16,
      surah: 20,
    },
    {
      number: 130,
      image: "",
      text: "So be patient over what they say and glorify with praise (of) your Lord before (the) rising (of) the sun and before its setting and from (the) hours (of) the night and glorify (at the) ends (of) the day so that you may be satisfied (130)",
      transliteration:
        "fa-iṣ'bir ʿalā mā yaqūlūna wasabbiḥ biḥamdi rabbika qabla ṭulūʿi l-shamsi waqabla ghurūbihā wamin ānāi al-layli fasabbiḥ wa-aṭrāfa l-nahāri laʿallaka tarḍā ",
      verse: 2478,
      juz: 16,
      surah: 20,
    },
    {
      number: 131,
      image: "",
      text: "And (do) not extend your eyes towards what We have given for enjoyment [with it] pairs of them (the) splendor (of) the life (of) the world that We may test them in it And (the) provision (of) your Lord (is) better and more lasting (131)",
      transliteration:
        "walā tamuddanna ʿaynayka ilā mā mattaʿnā bihi azwājan min'hum zahrata l-ḥayati l-dun'yā linaftinahum fīhi wariz'qu rabbika khayrun wa-abqā ",
      verse: 2479,
      juz: 16,
      surah: 20,
    },
    {
      number: 132,
      image: "",
      text: "And enjoin (on) your family the prayer and be steadfast therein Not We ask you (for) provision We provide (for) you and the outcome (is) for the righteous[ness] (132)",
      transliteration:
        "wamur ahlaka bil-ṣalati wa-iṣ'ṭabir ʿalayhā lā nasaluka riz'qan naḥnu narzuquka wal-ʿāqibatu lilttaqwā ",
      verse: 2480,
      juz: 16,
      surah: 20,
    },
    {
      number: 133,
      image: "",
      text: "And they say Why not he brings us a sign from his Lord Has not come to them evidence (of) what (was) in the Scriptures the former (133)",
      transliteration:
        "waqālū lawlā yatīnā biāyatin min rabbihi awalam tatihim bayyinatu mā fī l-ṣuḥufi l-ūlā ",
      verse: 2481,
      juz: 16,
      surah: 20,
    },
    {
      number: 134,
      image: "",
      text: "And if We (had) destroyed them with a punishment before him before him surely they (would) have said Our Lord why not You sent to us a Messenger so we (could) have followed Your signs before before [that] we were humiliated and disgraced (134)",
      transliteration:
        "walaw annā ahlaknāhum biʿadhābin min qablihi laqālū rabbanā lawlā arsalta ilaynā rasūlan fanattabiʿa āyātika min qabli an nadhilla wanakhzā ",
      verse: 2482,
      juz: 16,
      surah: 20,
    },
    {
      number: 135,
      image: "",
      text: "Say Each (is) waiting so await Then you will know who (are the) companions (of) the way [the] even and who is guided (135)",
      transliteration:
        "qul kullun mutarabbiṣun fatarabbaṣū fasataʿlamūna man aṣḥābu l-ṣirāṭi l-sawiyi wamani ih'tadā ",
      verse: 2483,
      juz: 16,
      surah: 20,
    },
  ],
};
