import { Surah } from "../types/islam.js";

export const takathur: Surah = {
  name: "At-Takathur",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "Diverts you the competition to increase (1)",
      transliteration: "alhākumu l-takāthuru ",
      verse: 6169,
      juz: 30,
      surah: 102,
    },
    {
      number: 2,
      image: "",
      text: "Until you visit the graves (2)",
      transliteration: "ḥattā zur'tumu l-maqābira ",
      verse: 6170,
      juz: 30,
      surah: 102,
    },
    {
      number: 3,
      image: "",
      text: "Nay Soon you will know (3)",
      transliteration: "kallā sawfa taʿlamūna ",
      verse: 6171,
      juz: 30,
      surah: 102,
    },
    {
      number: 4,
      image: "",
      text: "Then nay Soon you will know (4)",
      transliteration: "thumma kallā sawfa taʿlamūna ",
      verse: 6172,
      juz: 30,
      surah: 102,
    },
    {
      number: 5,
      image: "",
      text: "Nay If you know (with) a knowledge (of) certainty (5)",
      transliteration: "kallā law taʿlamūna ʿil'ma l-yaqīni ",
      verse: 6173,
      juz: 30,
      surah: 102,
    },
    {
      number: 6,
      image: "",
      text: "Surely you will see the Hellfire (6)",
      transliteration: "latarawunna l-jaḥīma ",
      verse: 6174,
      juz: 30,
      surah: 102,
    },
    {
      number: 7,
      image: "",
      text: "Then surely you will see it (with the) eye (of) certainty (7)",
      transliteration: "thumma latarawunnahā ʿayna l-yaqīni ",
      verse: 6175,
      juz: 30,
      surah: 102,
    },
    {
      number: 8,
      image: "",
      text: "Then surely you will be asked that Day about the pleasures (8)",
      transliteration: "thumma latus'alunna yawma-idhin ʿani l-naʿīmi ",
      verse: 6176,
      juz: 30,
      surah: 102,
    },
  ],
};
