import { Surah } from "../types/islam.js";

export const takwir: Surah = {
  name: "At-Takwir",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "When the sun is wrapped up (1)",
      transliteration: "idhā l-shamsu kuwwirat ",
      verse: 5801,
      juz: 30,
      surah: 81,
    },
    {
      number: 2,
      image: "",
      text: "And when the stars fall, losing their luster (2)",
      transliteration: "wa-idhā l-nujūmu inkadarat ",
      verse: 5802,
      juz: 30,
      surah: 81,
    },
    {
      number: 3,
      image: "",
      text: "And when the mountains are moved away (3)",
      transliteration: "wa-idhā l-jibālu suyyirat ",
      verse: 5803,
      juz: 30,
      surah: 81,
    },
    {
      number: 4,
      image: "",
      text: "And when the full-term she-camels (are) left untended (4)",
      transliteration: "wa-idhā l-ʿishāru ʿuṭṭilat ",
      verse: 5804,
      juz: 30,
      surah: 81,
    },
    {
      number: 5,
      image: "",
      text: "And when the wild beasts are gathered (5)",
      transliteration: "wa-idhā l-wuḥūshu ḥushirat ",
      verse: 5805,
      juz: 30,
      surah: 81,
    },
    {
      number: 6,
      image: "",
      text: "And when the seas are made to overflow (6)",
      transliteration: "wa-idhā l-biḥāru sujjirat ",
      verse: 5806,
      juz: 30,
      surah: 81,
    },
    {
      number: 7,
      image: "",
      text: "And when the souls are paired (7)",
      transliteration: "wa-idhā l-nufūsu zuwwijat ",
      verse: 5807,
      juz: 30,
      surah: 81,
    },
    {
      number: 8,
      image: "",
      text: "And when the female infant buried alive is asked (8)",
      transliteration: "wa-idhā l-mawūdatu su-ilat ",
      verse: 5808,
      juz: 30,
      surah: 81,
    },
    {
      number: 9,
      image: "",
      text: "For what sin she was killed (9)",
      transliteration: "bi-ayyi dhanbin qutilat ",
      verse: 5809,
      juz: 30,
      surah: 81,
    },
    {
      number: 10,
      image: "",
      text: "And when the pages are laid open (10)",
      transliteration: "wa-idhā l-ṣuḥufu nushirat ",
      verse: 5810,
      juz: 30,
      surah: 81,
    },
    {
      number: 11,
      image: "",
      text: "And when the sky is stripped away (11)",
      transliteration: "wa-idhā l-samāu kushiṭat ",
      verse: 5811,
      juz: 30,
      surah: 81,
    },
    {
      number: 12,
      image: "",
      text: "And when the Hellfire is set ablaze (12)",
      transliteration: "wa-idhā l-jaḥīmu suʿʿirat ",
      verse: 5812,
      juz: 30,
      surah: 81,
    },
    {
      number: 13,
      image: "",
      text: "And when Paradise is brought near (13)",
      transliteration: "wa-idhā l-janatu uz'lifat ",
      verse: 5813,
      juz: 30,
      surah: 81,
    },
    {
      number: 14,
      image: "",
      text: "Will know a soul what it has brought (14)",
      transliteration: "ʿalimat nafsun mā aḥḍarat ",
      verse: 5814,
      juz: 30,
      surah: 81,
    },
    {
      number: 15,
      image: "",
      text: "But nay I swear by the retreating planets (15)",
      transliteration: "falā uq'simu bil-khunasi ",
      verse: 5815,
      juz: 30,
      surah: 81,
    },
    {
      number: 16,
      image: "",
      text: "Those that run (and) disappear (16)",
      transliteration: "al-jawāri l-kunasi ",
      verse: 5816,
      juz: 30,
      surah: 81,
    },
    {
      number: 17,
      image: "",
      text: "And the night when it departs (17)",
      transliteration: "wa-al-layli idhā ʿasʿasa ",
      verse: 5817,
      juz: 30,
      surah: 81,
    },
    {
      number: 18,
      image: "",
      text: "And the dawn when it breathes (18)",
      transliteration: "wal-ṣub'ḥi idhā tanaffasa ",
      verse: 5818,
      juz: 30,
      surah: 81,
    },
    {
      number: 19,
      image: "",
      text: "Indeed, it (is) surely a word (of) a Messenger noble (19)",
      transliteration: "innahu laqawlu rasūlin karīmin ",
      verse: 5819,
      juz: 30,
      surah: 81,
    },
    {
      number: 20,
      image: "",
      text: "Possessor of power with (the) Owner of the Throne secure (20)",
      transliteration: "dhī quwwatin ʿinda dhī l-ʿarshi makīnin ",
      verse: 5820,
      juz: 30,
      surah: 81,
    },
    {
      number: 21,
      image: "",
      text: "One to be obeyed and trustworthy (21)",
      transliteration: "muṭāʿin thamma amīnin ",
      verse: 5821,
      juz: 30,
      surah: 81,
    },
    {
      number: 22,
      image: "",
      text: "And not (is) your companion mad (22)",
      transliteration: "wamā ṣāḥibukum bimajnūnin ",
      verse: 5822,
      juz: 30,
      surah: 81,
    },
    {
      number: 23,
      image: "",
      text: "And certainly he saw him in the horizon the clear (23)",
      transliteration: "walaqad raāhu bil-ufuqi l-mubīni ",
      verse: 5823,
      juz: 30,
      surah: 81,
    },
    {
      number: 24,
      image: "",
      text: "And not he (is) on the unseen a withholder (24)",
      transliteration: "wamā huwa ʿalā l-ghaybi biḍanīnin ",
      verse: 5824,
      juz: 30,
      surah: 81,
    },
    {
      number: 25,
      image: "",
      text: "And not it (is the) word (of) Shaitaan accursed (25)",
      transliteration: "wamā huwa biqawli shayṭānin rajīmin ",
      verse: 5825,
      juz: 30,
      surah: 81,
    },
    {
      number: 26,
      image: "",
      text: "So where are you going (26)",
      transliteration: "fa-ayna tadhhabūna ",
      verse: 5826,
      juz: 30,
      surah: 81,
    },
    {
      number: 27,
      image: "",
      text: "Not it (is) except a reminder to the worlds (27)",
      transliteration: "in huwa illā dhik'run lil'ʿālamīna ",
      verse: 5827,
      juz: 30,
      surah: 81,
    },
    {
      number: 28,
      image: "",
      text: "For whoever wills among you to take a straight way (28)",
      transliteration: "liman shāa minkum an yastaqīma ",
      verse: 5828,
      juz: 30,
      surah: 81,
    },
    {
      number: 29,
      image: "",
      text: "And not you will except that wills Allah Lord (of) the worlds (29)",
      transliteration: "wamā tashāūna illā an yashāa l-lahu rabbu l-ʿālamīna ",
      verse: 5829,
      juz: 30,
      surah: 81,
    },
  ],
};
