import { Surah } from "../types/islam.js";

export const tariq: Surah = {
  name: "At-Tariq",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "By the sky and the night comer (1)",
      transliteration: "wal-samāi wal-ṭāriqi ",
      verse: 5932,
      juz: 30,
      surah: 86,
    },
    {
      number: 2,
      image: "",
      text: "And what can make you know what the night comer (is) (2)",
      transliteration: "wamā adrāka mā l-ṭāriqu ",
      verse: 5933,
      juz: 30,
      surah: 86,
    },
    {
      number: 3,
      image: "",
      text: "(It is) the star the piercing (3)",
      transliteration: "al-najmu l-thāqibu ",
      verse: 5934,
      juz: 30,
      surah: 86,
    },
    {
      number: 4,
      image: "",
      text: "Not (is) every soul but over it (is) a protector (4)",
      transliteration: "in kullu nafsin lammā ʿalayhā ḥāfiẓun ",
      verse: 5935,
      juz: 30,
      surah: 86,
    },
    {
      number: 5,
      image: "",
      text: "So let see man from what he is created (5)",
      transliteration: "falyanẓuri l-insānu mimma khuliqa ",
      verse: 5936,
      juz: 30,
      surah: 86,
    },
    {
      number: 6,
      image: "",
      text: "He is created from a water ejected (6)",
      transliteration: "khuliqa min māin dāfiqin ",
      verse: 5937,
      juz: 30,
      surah: 86,
    },
    {
      number: 7,
      image: "",
      text: "Coming forth from between the backbone and the ribs (7)",
      transliteration: "yakhruju min bayni l-ṣul'bi wal-tarāibi ",
      verse: 5938,
      juz: 30,
      surah: 86,
    },
    {
      number: 8,
      image: "",
      text: "Indeed, He to return him (is) Able (8)",
      transliteration: "innahu ʿalā rajʿihi laqādirun ",
      verse: 5939,
      juz: 30,
      surah: 86,
    },
    {
      number: 9,
      image: "",
      text: "(The) Day will be tested the secrets (9)",
      transliteration: "yawma tub'lā l-sarāiru ",
      verse: 5940,
      juz: 30,
      surah: 86,
    },
    {
      number: 10,
      image: "",
      text: "Then not (is) for him any power and not any helper (10)",
      transliteration: "famā lahu min quwwatin walā nāṣirin ",
      verse: 5941,
      juz: 30,
      surah: 86,
    },
    {
      number: 11,
      image: "",
      text: "By the sky which returns (11)",
      transliteration: "wal-samāi dhāti l-rajʿi ",
      verse: 5942,
      juz: 30,
      surah: 86,
    },
    {
      number: 12,
      image: "",
      text: "And the earth which cracks open (12)",
      transliteration: "wal-arḍi dhāti l-ṣadʿi ",
      verse: 5943,
      juz: 30,
      surah: 86,
    },
    {
      number: 13,
      image: "",
      text: "Indeed, it (is) surely a Word decisive (13)",
      transliteration: "innahu laqawlun faṣlun ",
      verse: 5944,
      juz: 30,
      surah: 86,
    },
    {
      number: 14,
      image: "",
      text: "And not it (is) for amusement (14)",
      transliteration: "wamā huwa bil-hazli ",
      verse: 5945,
      juz: 30,
      surah: 86,
    },
    {
      number: 15,
      image: "",
      text: "Indeed, they are plotting a plot (15)",
      transliteration: "innahum yakīdūna kaydan ",
      verse: 5946,
      juz: 30,
      surah: 86,
    },
    {
      number: 16,
      image: "",
      text: "But I am planning a plan (16)",
      transliteration: "wa-akīdu kaydan ",
      verse: 5947,
      juz: 30,
      surah: 86,
    },
    {
      number: 17,
      image: "",
      text: "So give respite (to) the disbelievers Give respite to them  little (17)",
      transliteration: "famahhili l-kāfirīna amhil'hum ruwaydan ",
      verse: 5948,
      juz: 30,
      surah: 86,
    },
  ],
};
