import { Surah } from "../types/islam.js";

export const tin: Surah = {
  name: "At-Tin",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "By the fig and the olive (1)",
      transliteration: "wal-tīni wal-zaytūni ",
      verse: 6099,
      juz: 30,
      surah: 95,
    },
    {
      number: 2,
      image: "",
      text: "And (the) Mount Sinai (2)",
      transliteration: "waṭūri sīnīna ",
      verse: 6100,
      juz: 30,
      surah: 95,
    },
    {
      number: 3,
      image: "",
      text: "And this [the] city [the] secure (3)",
      transliteration: "wahādhā l-baladi l-amīni ",
      verse: 6101,
      juz: 30,
      surah: 95,
    },
    {
      number: 4,
      image: "",
      text: "Indeed We created man in (the) best mould (4)",
      transliteration: "laqad khalaqnā l-insāna fī aḥsani taqwīmin ",
      verse: 6102,
      juz: 30,
      surah: 95,
    },
    {
      number: 5,
      image: "",
      text: "Then We returned him (to the) lowest (of the) low (5)",
      transliteration: "thumma radadnāhu asfala sāfilīna ",
      verse: 6103,
      juz: 30,
      surah: 95,
    },
    {
      number: 6,
      image: "",
      text: "Except those who believe and do righteous deeds then for them (is a) reward never ending (6)",
      transliteration:
        "illā alladhīna āmanū waʿamilū l-ṣāliḥāti falahum ajrun ghayru mamnūnin ",
      verse: 6104,
      juz: 30,
      surah: 95,
    },
    {
      number: 7,
      image: "",
      text: "Then what causes you to deny after (this) the judgment (7)",
      transliteration: "famā yukadhibuka baʿdu bil-dīni ",
      verse: 6105,
      juz: 30,
      surah: 95,
    },
    {
      number: 8,
      image: "",
      text: "Is not Allah (the) Most Just (of) the Judges (8)",
      transliteration: "alaysa l-lahu bi-aḥkami l-ḥākimīna ",
      verse: 6106,
      juz: 30,
      surah: 95,
    },
  ],
};
