import { Surah } from "../types/islam.js";

export const tur: Surah = {
  name: "At-Tur",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "By the Mount (1)",
      transliteration: "wal-ṭūri ",
      verse: 4736,
      juz: 27,
      surah: 52,
    },
    {
      number: 2,
      image: "",
      text: "And by (the) Book written (2)",
      transliteration: "wakitābin masṭūrin ",
      verse: 4737,
      juz: 27,
      surah: 52,
    },
    {
      number: 3,
      image: "",
      text: "In parchment unrolled (3)",
      transliteration: "fī raqqin manshūrin ",
      verse: 4738,
      juz: 27,
      surah: 52,
    },
    {
      number: 4,
      image: "",
      text: "By the House frequented (4)",
      transliteration: "wal-bayti l-maʿmūri ",
      verse: 4739,
      juz: 27,
      surah: 52,
    },
    {
      number: 5,
      image: "",
      text: "By the roof raised high (5)",
      transliteration: "wal-saqfi l-marfūʿi ",
      verse: 4740,
      juz: 27,
      surah: 52,
    },
    {
      number: 6,
      image: "",
      text: "By the sea filled (6)",
      transliteration: "wal-baḥri l-masjūri ",
      verse: 4741,
      juz: 27,
      surah: 52,
    },
    {
      number: 7,
      image: "",
      text: "Indeed (the) punishment (of) your Lord (will) surely occur (7)",
      transliteration: "inna ʿadhāba rabbika lawāqiʿun ",
      verse: 4742,
      juz: 27,
      surah: 52,
    },
    {
      number: 8,
      image: "",
      text: "Not for it any preventer (8)",
      transliteration: "mā lahu min dāfiʿin ",
      verse: 4743,
      juz: 27,
      surah: 52,
    },
    {
      number: 9,
      image: "",
      text: "(On the) Day will shake the heaven (with violent) shake (9)",
      transliteration: "yawma tamūru l-samāu mawran ",
      verse: 4744,
      juz: 27,
      surah: 52,
    },
    {
      number: 10,
      image: "",
      text: "And will move away the mountains (with an awful) movement (10)",
      transliteration: "watasīru l-jibālu sayran ",
      verse: 4745,
      juz: 27,
      surah: 52,
    },
    {
      number: 11,
      image: "",
      text: "Then woe that Day to the deniers (11)",
      transliteration: "fawaylun yawma-idhin lil'mukadhibīna ",
      verse: 4746,
      juz: 27,
      surah: 52,
    },
    {
      number: 12,
      image: "",
      text: "Who [they] in (vain) discourse are playing (12)",
      transliteration: "alladhīna hum fī khawḍin yalʿabūna ",
      verse: 4747,
      juz: 27,
      surah: 52,
    },
    {
      number: 13,
      image: "",
      text: "(The) Day they will be thrust (in)to (the) Fire (of) Hell (with) a thrust (13)",
      transliteration: "yawma yudaʿʿūna ilā nāri jahannama daʿʿan ",
      verse: 4748,
      juz: 27,
      surah: 52,
    },
    {
      number: 14,
      image: "",
      text: "This (is) the Fire which you used to [of it] deny (14)",
      transliteration: "hādhihi l-nāru allatī kuntum bihā tukadhibūna ",
      verse: 4749,
      juz: 27,
      surah: 52,
    },
    {
      number: 15,
      image: "",
      text: "Then is this magic Then is this magic or you (do) not see (15)",
      transliteration: "afasiḥ'run hādhā am antum lā tub'ṣirūna ",
      verse: 4750,
      juz: 27,
      surah: 52,
    },
    {
      number: 16,
      image: "",
      text: "Burn in it then be patient or (do) not be patient (it is) same for you Only you are being recompensed (for) what you used to do (16)",
      transliteration:
        "iṣ'lawhā fa-iṣ'birū aw lā taṣbirū sawāon ʿalaykum innamā tuj'zawna mā kuntum taʿmalūna ",
      verse: 4751,
      juz: 27,
      surah: 52,
    },
    {
      number: 17,
      image: "",
      text: "Indeed the righteous (will be) in Gardens and pleasure (17)",
      transliteration: "inna l-mutaqīna fī jannātin wanaʿīmin ",
      verse: 4752,
      juz: 27,
      surah: 52,
    },
    {
      number: 18,
      image: "",
      text: "Enjoying in what has given them their Lord and protected them their Lord (from the) punishment (of) Hellfire (18)",
      transliteration:
        "fākihīna bimā ātāhum rabbuhum wawaqāhum rabbuhum ʿadhāba l-jaḥīmi ",
      verse: 4753,
      juz: 27,
      surah: 52,
    },
    {
      number: 19,
      image: "",
      text: "Eat and drink (in) satisfaction for what you used to do (19)",
      transliteration: "kulū wa-ish'rabū hanīan bimā kuntum taʿmalūna ",
      verse: 4754,
      juz: 27,
      surah: 52,
    },
    {
      number: 20,
      image: "",
      text: "Reclining on thrones lined up and We will marry them to fair ones (with) large eyes (20)",
      transliteration:
        "muttakiīna ʿalā sururin maṣfūfatin wazawwajnāhum biḥūrin ʿīnin ",
      verse: 4755,
      juz: 27,
      surah: 52,
    },
    {
      number: 21,
      image: "",
      text: "And those who believed and followed them their offspring in faith We will join with them their offspring and not We will deprive them of their deeds (in) any thing Every person for what he earned (is) pledged (21)",
      transliteration:
        "wa-alladhīna āmanū wa-ittabaʿathum dhurriyyatuhum biīmānin alḥaqnā bihim dhurriyyatahum wamā alatnāhum min ʿamalihim min shayin kullu im'ri-in bimā kasaba rahīnun ",
      verse: 4756,
      juz: 27,
      surah: 52,
    },
    {
      number: 22,
      image: "",
      text: "And We will provide them with fruit and meat from what they desire (22)",
      transliteration: "wa-amdadnāhum bifākihatin walaḥmin mimmā yashtahūna ",
      verse: 4757,
      juz: 27,
      surah: 52,
    },
    {
      number: 23,
      image: "",
      text: "They will pass to one another therein a cup no ill speech therein and no sin (23)",
      transliteration: "yatanāzaʿūna fīhā kasan lā laghwun fīhā walā tathīmun ",
      verse: 4758,
      juz: 27,
      surah: 52,
    },
    {
      number: 24,
      image: "",
      text: "And will circulate among them boys for them as if they (were) pearls well-protected (24)",
      transliteration:
        "wayaṭūfu ʿalayhim ghil'mānun lahum ka-annahum lu'lu-on maknūnun ",
      verse: 4759,
      juz: 27,
      surah: 52,
    },
    {
      number: 25,
      image: "",
      text: "And will approach some of them to others inquiring (25)",
      transliteration: "wa-aqbala baʿḍuhum ʿalā baʿḍin yatasāalūna ",
      verse: 4760,
      juz: 27,
      surah: 52,
    },
    {
      number: 26,
      image: "",
      text: "They will say Indeed, we [we] were before among our families fearful (26)",
      transliteration: "qālū innā kunnā qablu fī ahlinā mush'fiqīna ",
      verse: 4761,
      juz: 27,
      surah: 52,
    },
    {
      number: 27,
      image: "",
      text: "But Allah conferred favor But Allah conferred favor upon us and protected us (from the) punishment (of) the Scorching Fire (27)",
      transliteration: "famanna l-lahu ʿalaynā wawaqānā ʿadhāba l-samūmi ",
      verse: 4762,
      juz: 27,
      surah: 52,
    },
    {
      number: 28,
      image: "",
      text: "Indeed, we [we] used to before before call Him Indeed, He [He] (is) the Most Kind the Most Merciful (28)",
      transliteration:
        "innā kunnā min qablu nadʿūhu innahu huwa l-baru l-raḥīmu ",
      verse: 4763,
      juz: 27,
      surah: 52,
    },
    {
      number: 29,
      image: "",
      text: "Therefore remind for not you (are) by (the) grace (of) your Lord a soothsayer and not a madman (29)",
      transliteration:
        "fadhakkir famā anta biniʿ'mati rabbika bikāhinin walā majnūnin ",
      verse: 4764,
      juz: 27,
      surah: 52,
    },
    {
      number: 30,
      image: "",
      text: "Or (do) they say A poet we wait for him a misfortune of time a misfortune of time (30)",
      transliteration: "am yaqūlūna shāʿirun natarabbaṣu bihi rayba l-manūni ",
      verse: 4765,
      juz: 27,
      surah: 52,
    },
    {
      number: 31,
      image: "",
      text: "Say Wait for indeed I am with you among those who wait (31)",
      transliteration: "qul tarabbaṣū fa-innī maʿakum mina l-mutarabiṣīna ",
      verse: 4766,
      juz: 27,
      surah: 52,
    },
    {
      number: 32,
      image: "",
      text: "Or command them their minds this or they (are) a people transgressing (32)",
      transliteration: "am tamuruhum aḥlāmuhum bihādhā am hum qawmun ṭāghūna ",
      verse: 4767,
      juz: 27,
      surah: 52,
    },
    {
      number: 33,
      image: "",
      text: "Or (do) they say He has made it up Nay not they believe (33)",
      transliteration: "am yaqūlūna taqawwalahu bal lā yu'minūna ",
      verse: 4768,
      juz: 27,
      surah: 52,
    },
    {
      number: 34,
      image: "",
      text: "Then let them bring a statement like it if they are truthful (34)",
      transliteration: "falyatū biḥadīthin mith'lihi in kānū ṣādiqīna ",
      verse: 4769,
      juz: 27,
      surah: 52,
    },
    {
      number: 35,
      image: "",
      text: "Or they were created of nothing nothing or (are) they the creators (35)",
      transliteration: "am khuliqū min ghayri shayin am humu l-khāliqūna ",
      verse: 4770,
      juz: 27,
      surah: 52,
    },
    {
      number: 36,
      image: "",
      text: "Or (did) they create the heavens and the earth Nay not they are certain (36)",
      transliteration: "am khalaqū l-samāwāti wal-arḍa bal lā yūqinūna ",
      verse: 4771,
      juz: 27,
      surah: 52,
    },
    {
      number: 37,
      image: "",
      text: "Or with them (are the) treasures (of) your Lord or (are) they the controllers (37)",
      transliteration: "am ʿindahum khazāinu rabbika am humu l-muṣayṭirūna ",
      verse: 4772,
      juz: 27,
      surah: 52,
    },
    {
      number: 38,
      image: "",
      text: "Or for them (is) a stairway they listen therewith Then let bring their listener an authority clear (38)",
      transliteration:
        "am lahum sullamun yastamiʿūna fīhi falyati mus'tamiʿuhum bisul'ṭānin mubīnin ",
      verse: 4773,
      juz: 27,
      surah: 52,
    },
    {
      number: 39,
      image: "",
      text: "Or for Him (are) daughters while for you (are) sons (39)",
      transliteration: "am lahu l-banātu walakumu l-banūna ",
      verse: 4774,
      juz: 27,
      surah: 52,
    },
    {
      number: 40,
      image: "",
      text: "Or (do) you ask from them a payment so they from a debt (are) overburdened (40)",
      transliteration: "am tasaluhum ajran fahum min maghramin muth'qalūna ",
      verse: 4775,
      juz: 27,
      surah: 52,
    },
    {
      number: 41,
      image: "",
      text: "Or with them (is) the unseen so they write (it) down (41)",
      transliteration: "am ʿindahumu l-ghaybu fahum yaktubūna ",
      verse: 4776,
      juz: 27,
      surah: 52,
    },
    {
      number: 42,
      image: "",
      text: "Or (do) they intend a plot But those who disbelieve themselves (are in) the plot (42)",
      transliteration: "am yurīdūna kaydan fa-alladhīna kafarū humu l-makīdūna ",
      verse: 4777,
      juz: 27,
      surah: 52,
    },
    {
      number: 43,
      image: "",
      text: "Or for them a god other than Allah Glory be (to) Allah from what they associate (with Him) (43)",
      transliteration:
        "am lahum ilāhun ghayru l-lahi sub'ḥāna l-lahi ʿammā yush'rikūna ",
      verse: 4778,
      juz: 27,
      surah: 52,
    },
    {
      number: 44,
      image: "",
      text: "And if they were to see a portion from the sky falling they will say Clouds heaped up (44)",
      transliteration:
        "wa-in yaraw kis'fan mina l-samāi sāqiṭan yaqūlū saḥābun markūmun ",
      verse: 4779,
      juz: 27,
      surah: 52,
    },
    {
      number: 45,
      image: "",
      text: "So leave them until they meet their Day which in it they will faint (45)",
      transliteration:
        "fadharhum ḥattā yulāqū yawmahumu alladhī fīhi yuṣ'ʿaqūna ",
      verse: 4780,
      juz: 27,
      surah: 52,
    },
    {
      number: 46,
      image: "",
      text: "(The) Day not will avail to them their plotting (in) anything and not they will be helped (46)",
      transliteration:
        "yawma lā yugh'nī ʿanhum kayduhum shayan walā hum yunṣarūna ",
      verse: 4781,
      juz: 27,
      surah: 52,
    },
    {
      number: 47,
      image: "",
      text: "And indeed for those who do wrong (is) a punishment before that but most of them (do) not know (47)",
      transliteration:
        "wa-inna lilladhīna ẓalamū ʿadhāban dūna dhālika walākinna aktharahum lā yaʿlamūna ",
      verse: 4782,
      juz: 27,
      surah: 52,
    },
    {
      number: 48,
      image: "",
      text: "So be patient for (the) Command (of) your Lord for indeed, you (are) in Our Eyes And glorify (the) praise (of) your Lord when you arise (48)",
      transliteration:
        "wa-iṣ'bir liḥuk'mi rabbika fa-innaka bi-aʿyuninā wasabbiḥ biḥamdi rabbika ḥīna taqūmu ",
      verse: 4783,
      juz: 27,
      surah: 52,
    },
    {
      number: 49,
      image: "",
      text: "And of the night glorify Him and after the stars (49)",
      transliteration: "wamina al-layli fasabbiḥ'hu wa-id'bāra l-nujūmi ",
      verse: 4784,
      juz: 27,
      surah: 52,
    },
  ],
};
