import { Surah } from "../types/islam.ts";

export const waqiah: Surah = {
  name: "Al-Waq'iah",
  ayahs: [
    { number: 1, image: "", text: "When the Occurrence occurs,", verse: 4849 },
    {
      number: 2,
      image: "",
      text: "There is, at its occurrence, no denial.",
      verse: 4850,
    },
    {
      number: 3,
      image: "",
      text: "It will bring down [some] and raise up [others].",
      verse: 4851,
    },
    {
      number: 4,
      image: "",
      text: "When the earth is shaken with convulsion",
      verse: 4852,
    },
    {
      number: 5,
      image: "",
      text: "And the mountains are broken down, crumbling",
      verse: 4853,
    },
    { number: 6, image: "", text: "And become dust dispersing.", verse: 4854 },
    {
      number: 7,
      image: "",
      text: "And you become [of] three kinds:",
      verse: 4855,
    },
    {
      number: 8,
      image: "",
      text:
        "Then the companions of the right -  what are the companions of the right?",
      verse: 4856,
    },
    {
      number: 9,
      image: "",
      text:
        "And the companions of the left -  what are the companions of the left?",
      verse: 4857,
    },
    {
      number: 10,
      image: "",
      text: "And the forerunners, the forerunners -",
      verse: 4858,
    },
    {
      number: 11,
      image: "",
      text: "Those are the ones brought near [to Allah ]",
      verse: 4859,
    },
    { number: 12, image: "", text: "In the Gardens of Pleasure,", verse: 4860 },
    {
      number: 13,
      image: "",
      text: "A [large] company of the former peoples",
      verse: 4861,
    },
    {
      number: 14,
      image: "",
      text: "And a few of the later peoples,",
      verse: 4862,
    },
    {
      number: 15,
      image: "",
      text: "On thrones woven [with ornament],",
      verse: 4863,
    },
    {
      number: 16,
      image: "",
      text: "Reclining on them, facing each other.",
      verse: 4864,
    },
    {
      number: 17,
      image: "",
      text: "There will circulate among them young boys made eternal",
      verse: 4865,
    },
    {
      number: 18,
      image: "",
      text:
        "With vessels, pitchers and a cup [of wine] from a flowing spring -",
      verse: 4866,
    },
    {
      number: 19,
      image: "",
      text:
        "No headache will they have therefrom, nor will they be intoxicated -",
      verse: 4867,
    },
    {
      number: 20,
      image: "",
      text: "And fruit of what they select",
      verse: 4868,
    },
    {
      number: 21,
      image: "",
      text: "And the meat of fowl, from whatever they desire.",
      verse: 4869,
    },
    {
      number: 22,
      image: "",
      text: "And [for them are] fair women with large, [beautiful] eyes,",
      verse: 4870,
    },
    {
      number: 23,
      image: "",
      text: "The likenesses of pearls well-protected,",
      verse: 4871,
    },
    {
      number: 24,
      image: "",
      text: "As reward for what they used to do.",
      verse: 4872,
    },
    {
      number: 25,
      image: "",
      text: "They will not hear therein ill speech or commission of sin -",
      verse: 4873,
    },
    {
      number: 26,
      image: "",
      text: 'Only a saying: "Peace, peace."',
      verse: 4874,
    },
    {
      number: 27,
      image: "",
      text:
        "The companions of the right -  what are the companions of the right?",
      verse: 4875,
    },
    {
      number: 28,
      image: "",
      text: "[They will be] among lote trees with thorns removed",
      verse: 4876,
    },
    {
      number: 29,
      image: "",
      text: "And [banana] trees layered [with fruit]",
      verse: 4877,
    },
    { number: 30, image: "", text: "And shade extended", verse: 4878 },
    { number: 31, image: "", text: "And water poured out", verse: 4879 },
    {
      number: 32,
      image: "",
      text: "And fruit, abundant [and varied],",
      verse: 4880,
    },
    {
      number: 33,
      image: "",
      text: "Neither limited [to season] nor forbidden,",
      verse: 4881,
    },
    {
      number: 34,
      image: "",
      text: "And [upon] beds raised high.",
      verse: 4882,
    },
    {
      number: 35,
      image: "",
      text:
        "Indeed, We have produced the women of Paradise in a [new] creation",
      verse: 4883,
    },
    { number: 36, image: "", text: "And made them virgins,", verse: 4884 },
    {
      number: 37,
      image: "",
      text: "Devoted [to their husbands] and of equal age,",
      verse: 4885,
    },
    {
      number: 38,
      image: "",
      text: "For the companions of the right [who are]",
      verse: 4886,
    },
    {
      number: 39,
      image: "",
      text: "A company of the former peoples",
      verse: 4887,
    },
    {
      number: 40,
      image: "",
      text: "And a company of the later peoples.",
      verse: 4888,
    },
    {
      number: 41,
      image: "",
      text:
        "And the companions of the left -  what are the companions of the left?",
      verse: 4889,
    },
    {
      number: 42,
      image: "",
      text: "[They will be] in scorching fire and scalding water",
      verse: 4890,
    },
    { number: 43, image: "", text: "And a shade of black smoke,", verse: 4891 },
    {
      number: 44,
      image: "",
      text: "Neither cool nor beneficial.",
      verse: 4892,
    },
    {
      number: 45,
      image: "",
      text: "Indeed they were, before that, indulging in affluence,",
      verse: 4893,
    },
    {
      number: 46,
      image: "",
      text: "And they used to persist in the great violation,",
      verse: 4894,
    },
    {
      number: 47,
      image: "",
      text:
        'And they used to say, "When we die and become dust and bones, are we indeed to be resurrected?',
      verse: 4895,
    },
    {
      number: 48,
      image: "",
      text: 'And our forefathers [as well]?"',
      verse: 4896,
    },
    {
      number: 49,
      image: "",
      text: 'Say, [O Muhammad], "Indeed, the former and the later peoples',
      verse: 4897,
    },
    {
      number: 50,
      image: "",
      text: 'Are to be gathered together for the appointment of a known Day."',
      verse: 4898,
    },
    {
      number: 51,
      image: "",
      text: "Then indeed you, O those astray [who are] deniers,",
      verse: 4899,
    },
    {
      number: 52,
      image: "",
      text: "Will be eating from trees of zaqqum",
      verse: 4900,
    },
    {
      number: 53,
      image: "",
      text: "And filling with it your bellies",
      verse: 4901,
    },
    {
      number: 54,
      image: "",
      text: "And drinking on top of it from scalding water",
      verse: 4902,
    },
    {
      number: 55,
      image: "",
      text: "And will drink as the drinking of thirsty camels.",
      verse: 4903,
    },
    {
      number: 56,
      image: "",
      text: "That is their accommodation on the Day of Recompense.",
      verse: 4904,
    },
    {
      number: 57,
      image: "",
      text: "We have created you, so why do you not believe?",
      verse: 4905,
    },
    {
      number: 58,
      image: "",
      text: "Have you seen that which you emit?",
      verse: 4906,
    },
    {
      number: 59,
      image: "",
      text: "Is it you who creates it, or are We the Creator?",
      verse: 4907,
    },
    {
      number: 60,
      image: "",
      text: "We have decreed death among you, and We are not to be outdone",
      verse: 4908,
    },
    {
      number: 61,
      image: "",
      text:
        "In that We will change your likenesses and produce you in that [form] which you do not know.",
      verse: 4909,
    },
    {
      number: 62,
      image: "",
      text:
        "And you have already known the first creation, so will you not remember?",
      verse: 4910,
    },
    {
      number: 63,
      image: "",
      text: "And have you seen that [seed] which you sow?",
      verse: 4911,
    },
    {
      number: 64,
      image: "",
      text: "Is it you who makes it grow, or are We the grower?",
      verse: 4912,
    },
    {
      number: 65,
      image: "",
      text:
        "If We willed, We could make it [dry] debris, and you would remain in wonder,",
      verse: 4913,
    },
    {
      number: 66,
      image: "",
      text: '[Saying], "Indeed, we are [now] in debt;',
      verse: 4914,
    },
    {
      number: 67,
      image: "",
      text: 'Rather, we have been deprived."',
      verse: 4915,
    },
    {
      number: 68,
      image: "",
      text: "And have you seen the water that you drink?",
      verse: 4916,
    },
    {
      number: 69,
      image: "",
      text:
        "Is it you who brought it down from the clouds, or is it We who bring it down?",
      verse: 4917,
    },
    {
      number: 70,
      image: "",
      text:
        "If We willed, We could make it bitter, so why are you not grateful?",
      verse: 4918,
    },
    {
      number: 71,
      image: "",
      text: "And have you seen the fire that you ignite?",
      verse: 4919,
    },
    {
      number: 72,
      image: "",
      text: "Is it you who produced its tree, or are We the producer?",
      verse: 4920,
    },
    {
      number: 73,
      image: "",
      text: "We have made it a reminder and provision for the travelers,",
      verse: 4921,
    },
    {
      number: 74,
      image: "",
      text: "So exalt the name of your Lord, the Most Great.",
      verse: 4922,
    },
    {
      number: 75,
      image: "",
      text: "Then I swear by the setting of the stars,",
      verse: 4923,
    },
    {
      number: 76,
      image: "",
      text: "And indeed, it is an oath -  if you could know -  [most] great.",
      verse: 4924,
    },
    {
      number: 77,
      image: "",
      text: "Indeed, it is a noble Qur'an",
      verse: 4925,
    },
    {
      number: 78,
      image: "",
      text: "In a Register well-protected;",
      verse: 4926,
    },
    {
      number: 79,
      image: "",
      text: "None touch it except the purified.",
      verse: 4927,
    },
    {
      number: 80,
      image: "",
      text: "[It is] a revelation from the Lord of the worlds.",
      verse: 4928,
    },
    {
      number: 81,
      image: "",
      text: "Then is it to this statement that you are indifferent",
      verse: 4929,
    },
    {
      number: 82,
      image: "",
      text:
        "And make [the thanks for] your provision that you deny [the Provider]?",
      verse: 4930,
    },
    {
      number: 83,
      image: "",
      text: "Then why, when the soul at death reaches the throat",
      verse: 4931,
    },
    {
      number: 84,
      image: "",
      text: "And you are at that time looking on -",
      verse: 4932,
    },
    {
      number: 85,
      image: "",
      text: "And Our angels are nearer to him than you, but you do not see -",
      verse: 4933,
    },
    {
      number: 86,
      image: "",
      text: "Then why do you not, if you are not to be recompensed,",
      verse: 4934,
    },
    {
      number: 87,
      image: "",
      text: "Bring it back, if you should be truthful?",
      verse: 4935,
    },
    {
      number: 88,
      image: "",
      text: "And if the deceased was of those brought near to Allah,",
      verse: 4936,
    },
    {
      number: 89,
      image: "",
      text: "Then [for him is] rest and bounty and a garden of pleasure.",
      verse: 4937,
    },
    {
      number: 90,
      image: "",
      text: "And if he was of the companions of the right,",
      verse: 4938,
    },
    {
      number: 91,
      image: "",
      text:
        'Then [the angels will say], "Peace for you; [you are] from the companions of the right."',
      verse: 4939,
    },
    {
      number: 92,
      image: "",
      text: "But if he was of the deniers [who were] astray,",
      verse: 4940,
    },
    {
      number: 93,
      image: "",
      text: "Then [for him is] accommodation of scalding water",
      verse: 4941,
    },
    { number: 94, image: "", text: "And burning in Hellfire", verse: 4942 },
    {
      number: 95,
      image: "",
      text: "Indeed, this is the true certainty,",
      verse: 4943,
    },
    {
      number: 96,
      image: "",
      text: "So exalt the name of your Lord, the Most Great.",
      verse: 4944,
    },
  ],
};
