import { Surah } from "../types/islam.js";

export const waqiah: Surah = {
  name: "Al-Waq'iah",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "When occurs the Event (1)",
      transliteration: "idhā waqaʿati l-wāqiʿatu ",
      verse: 4980,
      juz: 27,
      surah: 56,
    },
    {
      number: 2,
      image: "",
      text: "Not at its occurrence a denial (2)",
      transliteration: "laysa liwaqʿatihā kādhibatun ",
      verse: 4981,
      juz: 27,
      surah: 56,
    },
    {
      number: 3,
      image: "",
      text: "Bringing down raising up (3)",
      transliteration: "khāfiḍatun rāfiʿatun ",
      verse: 4982,
      juz: 27,
      surah: 56,
    },
    {
      number: 4,
      image: "",
      text: "When will be shaken the earth (with) a shaking (4)",
      transliteration: "idhā rujjati l-arḍu rajjan ",
      verse: 4983,
      juz: 27,
      surah: 56,
    },
    {
      number: 5,
      image: "",
      text: "And will be crumbled the mountains (with awful) crumbling (5)",
      transliteration: "wabussati l-jibālu bassan ",
      verse: 4984,
      juz: 27,
      surah: 56,
    },
    {
      number: 6,
      image: "",
      text: "So they become dust particles dispersing (6)",
      transliteration: "fakānat habāan munbathan ",
      verse: 4985,
      juz: 27,
      surah: 56,
    },
    {
      number: 7,
      image: "",
      text: "And you will become kinds three (7)",
      transliteration: "wakuntum azwājan thalāthatan ",
      verse: 4986,
      juz: 27,
      surah: 56,
    },
    {
      number: 8,
      image: "",
      text: "Then (the) companions (of) the right what (are the) companions (of) the right (8)",
      transliteration: "fa-aṣḥābu l-maymanati mā aṣḥābu l-maymanati ",
      verse: 4987,
      juz: 27,
      surah: 56,
    },
    {
      number: 9,
      image: "",
      text: "And (the) companions (of) the left what (are the) companions (of) the left (9)",
      transliteration: "wa-aṣḥābu l-mashamati mā aṣḥābu l-mashamati ",
      verse: 4988,
      juz: 27,
      surah: 56,
    },
    {
      number: 10,
      image: "",
      text: "And the foremost (are) the foremost (10)",
      transliteration: "wal-sābiqūna l-sābiqūna ",
      verse: 4989,
      juz: 27,
      surah: 56,
    },
    {
      number: 11,
      image: "",
      text: "Those (are) the nearest ones (11)",
      transliteration: "ulāika l-muqarabūna ",
      verse: 4990,
      juz: 27,
      surah: 56,
    },
    {
      number: 12,
      image: "",
      text: "In Gardens (of) Pleasure (12)",
      transliteration: "fī jannāti l-naʿīmi ",
      verse: 4991,
      juz: 27,
      surah: 56,
    },
    {
      number: 13,
      image: "",
      text: "A company of the former (people) (13)",
      transliteration: "thullatun mina l-awalīna ",
      verse: 4992,
      juz: 27,
      surah: 56,
    },
    {
      number: 14,
      image: "",
      text: "And a few of the later (people) (14)",
      transliteration: "waqalīlun mina l-ākhirīna ",
      verse: 4993,
      juz: 27,
      surah: 56,
    },
    {
      number: 15,
      image: "",
      text: "On thrones decorated (15)",
      transliteration: "ʿalā sururin mawḍūnatin ",
      verse: 4994,
      juz: 27,
      surah: 56,
    },
    {
      number: 16,
      image: "",
      text: "Reclining on them facing each other (16)",
      transliteration: "muttakiīna ʿalayhā mutaqābilīna ",
      verse: 4995,
      juz: 27,
      surah: 56,
    },
    {
      number: 17,
      image: "",
      text: "Will circulate among them boys immortal (17)",
      transliteration: "yaṭūfu ʿalayhim wil'dānun mukhalladūna ",
      verse: 4996,
      juz: 27,
      surah: 56,
    },
    {
      number: 18,
      image: "",
      text: "With vessels and jugs and a cup from a flowing stream (18)",
      transliteration: "bi-akwābin wa-abārīqa wakasin min maʿīnin ",
      verse: 4997,
      juz: 27,
      surah: 56,
    },
    {
      number: 19,
      image: "",
      text: "Not they will get headache therefrom and not they will get intoxicated (19)",
      transliteration: "lā yuṣaddaʿūna ʿanhā walā yunzifūna ",
      verse: 4998,
      juz: 27,
      surah: 56,
    },
    {
      number: 20,
      image: "",
      text: "And fruits of what they select (20)",
      transliteration: "wafākihatin mimmā yatakhayyarūna ",
      verse: 4999,
      juz: 27,
      surah: 56,
    },
    {
      number: 21,
      image: "",
      text: "And (the) flesh (of) fowls of what they desire (21)",
      transliteration: "walaḥmi ṭayrin mimmā yashtahūna ",
      verse: 5000,
      juz: 27,
      surah: 56,
    },
    {
      number: 22,
      image: "",
      text: "And fair ones (with) large eyes (22)",
      transliteration: "waḥūrun ʿīnun ",
      verse: 5001,
      juz: 27,
      surah: 56,
    },
    {
      number: 23,
      image: "",
      text: "Like pearls well-protected (23)",
      transliteration: "ka-amthāli l-lu'lu-i l-maknūni ",
      verse: 5002,
      juz: 27,
      surah: 56,
    },
    {
      number: 24,
      image: "",
      text: "A reward for what they used (to) do (24)",
      transliteration: "jazāan bimā kānū yaʿmalūna ",
      verse: 5003,
      juz: 27,
      surah: 56,
    },
    {
      number: 25,
      image: "",
      text: "Not they will hear therein vain talk and not sinful (speech) (25)",
      transliteration: "lā yasmaʿūna fīhā laghwan walā tathīman ",
      verse: 5004,
      juz: 27,
      surah: 56,
    },
    {
      number: 26,
      image: "",
      text: "Except a saying Peace Peace (26)",
      transliteration: "illā qīlan salāman salāman ",
      verse: 5005,
      juz: 27,
      surah: 56,
    },
    {
      number: 27,
      image: "",
      text: "And (the) companions (of) the right what (are the) companions (of) the right (27)",
      transliteration: "wa-aṣḥābu l-yamīni mā aṣḥābu l-yamīni ",
      verse: 5006,
      juz: 27,
      surah: 56,
    },
    {
      number: 28,
      image: "",
      text: "Among lote trees thornless (28)",
      transliteration: "fī sid'rin makhḍūdin ",
      verse: 5007,
      juz: 27,
      surah: 56,
    },
    {
      number: 29,
      image: "",
      text: "And banana trees layered (29)",
      transliteration: "waṭalḥin manḍūdin ",
      verse: 5008,
      juz: 27,
      surah: 56,
    },
    {
      number: 30,
      image: "",
      text: "And shade extended (30)",
      transliteration: "waẓillin mamdūdin ",
      verse: 5009,
      juz: 27,
      surah: 56,
    },
    {
      number: 31,
      image: "",
      text: "And water poured forth (31)",
      transliteration: "wamāin maskūbin ",
      verse: 5010,
      juz: 27,
      surah: 56,
    },
    {
      number: 32,
      image: "",
      text: "And fruit abundant (32)",
      transliteration: "wafākihatin kathīratin ",
      verse: 5011,
      juz: 27,
      surah: 56,
    },
    {
      number: 33,
      image: "",
      text: "Not limited and not forbidden (33)",
      transliteration: "lā maqṭūʿatin walā mamnūʿatin ",
      verse: 5012,
      juz: 27,
      surah: 56,
    },
    {
      number: 34,
      image: "",
      text: "And (on) couches raised (34)",
      transliteration: "wafurushin marfūʿatin ",
      verse: 5013,
      juz: 27,
      surah: 56,
    },
    {
      number: 35,
      image: "",
      text: "Indeed, We [We] have produced them (into) a creation (35)",
      transliteration: "innā anshanāhunna inshāan ",
      verse: 5014,
      juz: 27,
      surah: 56,
    },
    {
      number: 36,
      image: "",
      text: "And We have made them virgins (36)",
      transliteration: "fajaʿalnāhunna abkāran ",
      verse: 5015,
      juz: 27,
      surah: 56,
    },
    {
      number: 37,
      image: "",
      text: "Devoted equals in age (37)",
      transliteration: "ʿuruban atrāban ",
      verse: 5016,
      juz: 27,
      surah: 56,
    },
    {
      number: 38,
      image: "",
      text: "For (the) companions (of) the right (38)",
      transliteration: "li-aṣḥābi l-yamīni ",
      verse: 5017,
      juz: 27,
      surah: 56,
    },
    {
      number: 39,
      image: "",
      text: "A company of the former people (39)",
      transliteration: "thullatun mina l-awalīna ",
      verse: 5018,
      juz: 27,
      surah: 56,
    },
    {
      number: 40,
      image: "",
      text: "And a company of the later people (40)",
      transliteration: "wathullatun mina l-ākhirīna ",
      verse: 5019,
      juz: 27,
      surah: 56,
    },
    {
      number: 41,
      image: "",
      text: "And (the) companions (of) the left what (are the) companions (of) the left (41)",
      transliteration: "wa-aṣḥābu l-shimāli mā aṣḥābu l-shimāli ",
      verse: 5020,
      juz: 27,
      surah: 56,
    },
    {
      number: 42,
      image: "",
      text: "In scorching fire and scalding water (42)",
      transliteration: "fī samūmin waḥamīmin ",
      verse: 5021,
      juz: 27,
      surah: 56,
    },
    {
      number: 43,
      image: "",
      text: "And a shade of black smoke (43)",
      transliteration: "waẓillin min yaḥmūmin ",
      verse: 5022,
      juz: 27,
      surah: 56,
    },
    {
      number: 44,
      image: "",
      text: "Not cool and not pleasant (44)",
      transliteration: "lā bāridin walā karīmin ",
      verse: 5023,
      juz: 27,
      surah: 56,
    },
    {
      number: 45,
      image: "",
      text: "Indeed, they were before that indulging in affluence (45)",
      transliteration: "innahum kānū qabla dhālika mut'rafīna ",
      verse: 5024,
      juz: 27,
      surah: 56,
    },
    {
      number: 46,
      image: "",
      text: "And were persisting in the sin the great (46)",
      transliteration: "wakānū yuṣirrūna ʿalā l-ḥinthi l-ʿaẓīmi ",
      verse: 5025,
      juz: 27,
      surah: 56,
    },
    {
      number: 47,
      image: "",
      text: "And they used (to) say When we die and become dust and bones will we surely be resurrected (47)",
      transliteration:
        "wakānū yaqūlūna a-idhā mit'nā wakunnā turāban waʿiẓāman a-innā lamabʿūthūna ",
      verse: 5026,
      juz: 27,
      surah: 56,
    },
    {
      number: 48,
      image: "",
      text: "And also our fathers former (48)",
      transliteration: "awaābāunā l-awalūna ",
      verse: 5027,
      juz: 27,
      surah: 56,
    },
    {
      number: 49,
      image: "",
      text: "Say Indeed the former and the later people (49)",
      transliteration: "qul inna l-awalīna wal-ākhirīna ",
      verse: 5028,
      juz: 27,
      surah: 56,
    },
    {
      number: 50,
      image: "",
      text: "Surely, will be gathered for (the) appointment (of) a Day well-known (50)",
      transliteration: "lamajmūʿūna ilā mīqāti yawmin maʿlūmin ",
      verse: 5029,
      juz: 27,
      surah: 56,
    },
    {
      number: 51,
      image: "",
      text: "Then indeed you O those astray O those astray the deniers (51)",
      transliteration: "thumma innakum ayyuhā l-ḍālūna l-mukadhibūna ",
      verse: 5030,
      juz: 27,
      surah: 56,
    },
    {
      number: 52,
      image: "",
      text: "Will surely eat from (the) tree of Zaqqum (52)",
      transliteration: "laākilūna min shajarin min zaqqūmin ",
      verse: 5031,
      juz: 27,
      surah: 56,
    },
    {
      number: 53,
      image: "",
      text: "Then will fill with it the bellies (53)",
      transliteration: "famāliūna min'hā l-buṭūna ",
      verse: 5032,
      juz: 27,
      surah: 56,
    },
    {
      number: 54,
      image: "",
      text: "And drink over it [from] the scalding water (54)",
      transliteration: "fashāribūna ʿalayhi mina l-ḥamīmi ",
      verse: 5033,
      juz: 27,
      surah: 56,
    },
    {
      number: 55,
      image: "",
      text: "And will drink (as) drinking (of) the thirsty camels (55)",
      transliteration: "fashāribūna shur'ba l-hīmi ",
      verse: 5034,
      juz: 27,
      surah: 56,
    },
    {
      number: 56,
      image: "",
      text: "This (is) their hospitality (on the) Day (of) Judgment (56)",
      transliteration: "hādhā nuzuluhum yawma l-dīni ",
      verse: 5035,
      juz: 27,
      surah: 56,
    },
    {
      number: 57,
      image: "",
      text: "We [We] created you so why (do) not you admit the truth (57)",
      transliteration: "naḥnu khalaqnākum falawlā tuṣaddiqūna ",
      verse: 5036,
      juz: 27,
      surah: 56,
    },
    {
      number: 58,
      image: "",
      text: "Do you see what you emit (58)",
      transliteration: "afara-aytum mā tum'nūna ",
      verse: 5037,
      juz: 27,
      surah: 56,
    },
    {
      number: 59,
      image: "",
      text: "Is it you who create it or (are) We the Creators (59)",
      transliteration: "a-antum takhluqūnahu am naḥnu l-khāliqūna ",
      verse: 5038,
      juz: 27,
      surah: 56,
    },
    {
      number: 60,
      image: "",
      text: "We [We] have decreed among you the death and not We (are) outrun (60)",
      transliteration: "naḥnu qaddarnā baynakumu l-mawta wamā naḥnu bimasbūqīna ",
      verse: 5039,
      juz: 27,
      surah: 56,
    },
    {
      number: 61,
      image: "",
      text: "In that We (will) change your likeness[es] and produce you in what not you know (61)",
      transliteration:
        "ʿalā an nubaddila amthālakum wanunshi-akum fī mā lā taʿlamūna ",
      verse: 5040,
      juz: 27,
      surah: 56,
    },
    {
      number: 62,
      image: "",
      text: "And certainly you know the creation the first so why not you take heed (62)",
      transliteration: "walaqad ʿalim'tumu l-nashata l-ūlā falawlā tadhakkarūna ",
      verse: 5041,
      juz: 27,
      surah: 56,
    },
    {
      number: 63,
      image: "",
      text: "And do you see what you sow (63)",
      transliteration: "afara-aytum mā taḥruthūna ",
      verse: 5042,
      juz: 27,
      surah: 56,
    },
    {
      number: 64,
      image: "",
      text: "Is it you (who) cause it to grow or (are) We the Ones Who grow (64)",
      transliteration: "a-antum tazraʿūnahu am naḥnu l-zāriʿūna ",
      verse: 5043,
      juz: 27,
      surah: 56,
    },
    {
      number: 65,
      image: "",
      text: "If We willed We (would) surely, make it debris then you would remain wondering (65)",
      transliteration: "law nashāu lajaʿalnāhu ḥuṭāman faẓaltum tafakkahūna ",
      verse: 5044,
      juz: 27,
      surah: 56,
    },
    {
      number: 66,
      image: "",
      text: "Indeed, we surely are laden with debt (66)",
      transliteration: "innā lamugh'ramūna ",
      verse: 5045,
      juz: 27,
      surah: 56,
    },
    {
      number: 67,
      image: "",
      text: "Nay we (are) deprived (67)",
      transliteration: "bal naḥnu maḥrūmūna ",
      verse: 5046,
      juz: 27,
      surah: 56,
    },
    {
      number: 68,
      image: "",
      text: "Do you see the water which you drink (68)",
      transliteration: "afara-aytumu l-māa alladhī tashrabūna ",
      verse: 5047,
      juz: 27,
      surah: 56,
    },
    {
      number: 69,
      image: "",
      text: "Is it you who send it down from the rain clouds or We (are) the Ones to send (69)",
      transliteration: "a-antum anzaltumūhu mina l-muz'ni am naḥnu l-munzilūna ",
      verse: 5048,
      juz: 27,
      surah: 56,
    },
    {
      number: 70,
      image: "",
      text: "If We willed We (could) make it salty then why are you not grateful then why are you not grateful (70)",
      transliteration: "law nashāu jaʿalnāhu ujājan falawlā tashkurūna ",
      verse: 5049,
      juz: 27,
      surah: 56,
    },
    {
      number: 71,
      image: "",
      text: "Do you see the Fire which you ignite (71)",
      transliteration: "afara-aytumu l-nāra allatī tūrūna ",
      verse: 5050,
      juz: 27,
      surah: 56,
    },
    {
      number: 72,
      image: "",
      text: "Is it you who produced its tree or We (are) the Producers (72)",
      transliteration: "a-antum anshatum shajaratahā am naḥnu l-munshiūna ",
      verse: 5051,
      juz: 27,
      surah: 56,
    },
    {
      number: 73,
      image: "",
      text: "We have made it a reminder and a provision for the wayfarers in the desert (73)",
      transliteration: "naḥnu jaʿalnāhā tadhkiratan wamatāʿan lil'muq'wīna ",
      verse: 5052,
      juz: 27,
      surah: 56,
    },
    {
      number: 74,
      image: "",
      text: "So glorify (the) name (of) your Lord the Most Great (74)",
      transliteration: "fasabbiḥ bi-is'mi rabbika l-ʿaẓīmi ",
      verse: 5053,
      juz: 27,
      surah: 56,
    },
    {
      number: 75,
      image: "",
      text: "But nay I swear by setting (of) the stars (75)",
      transliteration: "falā uq'simu bimawāqiʿi l-nujūmi ",
      verse: 5054,
      juz: 27,
      surah: 56,
    },
    {
      number: 76,
      image: "",
      text: "And indeed, it (is) surely an oath if you know  great (76)",
      transliteration: "wa-innahu laqasamun law taʿlamūna ʿaẓīmun ",
      verse: 5055,
      juz: 27,
      surah: 56,
    },
    {
      number: 77,
      image: "",
      text: "Indeed, it (is) surely, a Quran noble (77)",
      transliteration: "innahu laqur'ānun karīmun ",
      verse: 5056,
      juz: 27,
      surah: 56,
    },
    {
      number: 78,
      image: "",
      text: "In a Book well-guarded (78)",
      transliteration: "fī kitābin maknūnin ",
      verse: 5057,
      juz: 27,
      surah: 56,
    },
    {
      number: 79,
      image: "",
      text: "None touch it except the purified (79)",
      transliteration: "lā yamassuhu illā l-muṭaharūna ",
      verse: 5058,
      juz: 27,
      surah: 56,
    },
    {
      number: 80,
      image: "",
      text: "A Revelation from (the) Lord (of) the worlds (80)",
      transliteration: "tanzīlun min rabbi l-ʿālamīna ",
      verse: 5059,
      juz: 27,
      surah: 56,
    },
    {
      number: 81,
      image: "",
      text: "Then is it to this statement that you (are) indifferent (81)",
      transliteration: "afabihādhā l-ḥadīthi antum mud'hinūna ",
      verse: 5060,
      juz: 27,
      surah: 56,
    },
    {
      number: 82,
      image: "",
      text: "And you make your provision that you deny (82)",
      transliteration: "watajʿalūna riz'qakum annakum tukadhibūna ",
      verse: 5061,
      juz: 27,
      surah: 56,
    },
    {
      number: 83,
      image: "",
      text: "Then why not when it reaches the throat (83)",
      transliteration: "falawlā idhā balaghati l-ḥul'qūma ",
      verse: 5062,
      juz: 27,
      surah: 56,
    },
    {
      number: 84,
      image: "",
      text: "And you (at) that time look on (84)",
      transliteration: "wa-antum ḥīna-idhin tanẓurūna ",
      verse: 5063,
      juz: 27,
      surah: 56,
    },
    {
      number: 85,
      image: "",
      text: "And We (are) nearer to him than you but you (do) not see you (do) not see (85)",
      transliteration: "wanaḥnu aqrabu ilayhi minkum walākin lā tub'ṣirūna ",
      verse: 5064,
      juz: 27,
      surah: 56,
    },
    {
      number: 86,
      image: "",
      text: "Then why not if you are not to be recompensed (86)",
      transliteration: "falawlā in kuntum ghayra madīnīna ",
      verse: 5065,
      juz: 27,
      surah: 56,
    },
    {
      number: 87,
      image: "",
      text: "Bring it back if you are truthful (87)",
      transliteration: "tarjiʿūnahā in kuntum ṣādiqīna ",
      verse: 5066,
      juz: 27,
      surah: 56,
    },
    {
      number: 88,
      image: "",
      text: "Then if he was of those brought near (88)",
      transliteration: "fa-ammā in kāna mina l-muqarabīna ",
      verse: 5067,
      juz: 27,
      surah: 56,
    },
    {
      number: 89,
      image: "",
      text: "Then rest and bounty and a Garden (of) Pleasure (89)",
      transliteration: "farawḥun warayḥānun wajannatu naʿīmin ",
      verse: 5068,
      juz: 27,
      surah: 56,
    },
    {
      number: 90,
      image: "",
      text: "And if he was of (the) companions (of) the right (90)",
      transliteration: "wa-ammā in kāna min aṣḥābi l-yamīni ",
      verse: 5069,
      juz: 27,
      surah: 56,
    },
    {
      number: 91,
      image: "",
      text: "Then, peace for you [from] (the) companions (of) the right (91)",
      transliteration: "fasalāmun laka min aṣḥābi l-yamīni ",
      verse: 5070,
      juz: 27,
      surah: 56,
    },
    {
      number: 92,
      image: "",
      text: "But if he was of the deniers the astray (92)",
      transliteration: "wa-ammā in kāna mina l-mukadhibīna l-ḍālīna ",
      verse: 5071,
      juz: 27,
      surah: 56,
    },
    {
      number: 93,
      image: "",
      text: "Then, hospitality of (the) scalding water (93)",
      transliteration: "fanuzulun min ḥamīmin ",
      verse: 5072,
      juz: 27,
      surah: 56,
    },
    {
      number: 94,
      image: "",
      text: "And burning (in) Hellfire (94)",
      transliteration: "wataṣliyatu jaḥīmin ",
      verse: 5073,
      juz: 27,
      surah: 56,
    },
    {
      number: 95,
      image: "",
      text: "Indeed this surely, it (is the) truth certain (95)",
      transliteration: "inna hādhā lahuwa ḥaqqu l-yaqīni ",
      verse: 5074,
      juz: 27,
      surah: 56,
    },
    {
      number: 96,
      image: "",
      text: "So glorify (the) name (of) your Lord the Most Great (96)",
      transliteration: "fasabbiḥ bi-is'mi rabbika l-ʿaẓīmi ",
      verse: 5075,
      juz: 27,
      surah: 56,
    },
  ],
};
