import { Surah } from "../types/islam.js";

export const zalzalah: Surah = {
  name: "Az-Zalzalah",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "When is shaken the earth (with) its earthquake (1)",
      transliteration: "idhā zul'zilati l-arḍu zil'zālahā ",
      verse: 6139,
      juz: 30,
      surah: 99,
    },
    {
      number: 2,
      image: "",
      text: "And brings forth the earth its burdens (2)",
      transliteration: "wa-akhrajati l-arḍu athqālahā ",
      verse: 6140,
      juz: 30,
      surah: 99,
    },
    {
      number: 3,
      image: "",
      text: "And says man What (is) with it (3)",
      transliteration: "waqāla l-insānu mā lahā ",
      verse: 6141,
      juz: 30,
      surah: 99,
    },
    {
      number: 4,
      image: "",
      text: "That Day it will report its news (4)",
      transliteration: "yawma-idhin tuḥaddithu akhbārahā ",
      verse: 6142,
      juz: 30,
      surah: 99,
    },
    {
      number: 5,
      image: "",
      text: "Because your Lord inspired [to] it (5)",
      transliteration: "bi-anna rabbaka awḥā lahā ",
      verse: 6143,
      juz: 30,
      surah: 99,
    },
    {
      number: 6,
      image: "",
      text: "That Day will proceed the mankind (in) scattered groups to be shown their deeds (6)",
      transliteration: "yawma-idhin yaṣduru l-nāsu ashtātan liyuraw aʿmālahum ",
      verse: 6144,
      juz: 30,
      surah: 99,
    },
    {
      number: 7,
      image: "",
      text: "So whoever does (equal to the) weight (of) an atom good will see it (7)",
      transliteration: "faman yaʿmal mith'qāla dharratin khayran yarahu ",
      verse: 6145,
      juz: 30,
      surah: 99,
    },
    {
      number: 8,
      image: "",
      text: "And whoever does (equal to the) weight (of) an atom evil will see it (8)",
      transliteration: "waman yaʿmal mith'qāla dharratin sharran yarahu ",
      verse: 6146,
      juz: 30,
      surah: 99,
    },
  ],
};
