import { Surah } from "../types/islam.js";

export const zukhruf: Surah = {
  name: "Az-Zukhruf",
  ayahs: [
    {
      number: 1,
      image: "",
      text: "Ha Meem (1)",
      transliteration: "hha-meem ",
      verse: 4326,
      juz: 25,
      surah: 43,
    },
    {
      number: 2,
      image: "",
      text: "By the Book the clear (2)",
      transliteration: "wal-kitābi l-mubīni ",
      verse: 4327,
      juz: 25,
      surah: 43,
    },
    {
      number: 3,
      image: "",
      text: "Indeed, We (have) made it a Quran (in) Arabic so that you may understand (3)",
      transliteration: "innā jaʿalnāhu qur'ānan ʿarabiyyan laʿallakum taʿqilūna ",
      verse: 4328,
      juz: 25,
      surah: 43,
    },
    {
      number: 4,
      image: "",
      text: "And indeed, it (is) in (the) Mother (of) the Book with Us surely exalted full of wisdom (4)",
      transliteration: "wa-innahu fī ummi l-kitābi ladaynā laʿaliyyun ḥakīmun ",
      verse: 4329,
      juz: 25,
      surah: 43,
    },
    {
      number: 5,
      image: "",
      text: "Then should We take away from you the Reminder disregarding (you) because you are a people transgressing (5)",
      transliteration:
        "afanaḍribu ʿankumu l-dhik'ra ṣafḥan an kuntum qawman mus'rifīna ",
      verse: 4330,
      juz: 25,
      surah: 43,
    },
    {
      number: 6,
      image: "",
      text: "And how many We sent of a Prophet among the former (people) (6)",
      transliteration: "wakam arsalnā min nabiyyin fī l-awalīna ",
      verse: 4331,
      juz: 25,
      surah: 43,
    },
    {
      number: 7,
      image: "",
      text: "And not came to them any Prophet any Prophet but they used to mock at him mock at him (7)",
      transliteration: "wamā yatīhim min nabiyyin illā kānū bihi yastahziūna ",
      verse: 4332,
      juz: 25,
      surah: 43,
    },
    {
      number: 8,
      image: "",
      text: "Then We destroyed stronger than them (in) power and has passed (the) example (of) the former (people) (8)",
      transliteration:
        "fa-ahlaknā ashadda min'hum baṭshan wamaḍā mathalu l-awalīna ",
      verse: 4333,
      juz: 25,
      surah: 43,
    },
    {
      number: 9,
      image: "",
      text: "And if you ask them Who created the heavens and the earth They will surely say Created them the All-Mighty the All-Knower (9)",
      transliteration:
        "wala-in sa-altahum man khalaqa l-samāwāti wal-arḍa layaqūlunna khalaqahunna l-ʿazīzu l-ʿalīmu ",
      verse: 4334,
      juz: 25,
      surah: 43,
    },
    {
      number: 10,
      image: "",
      text: "The One Who made for you the earth a bed and made for you therein roads so that you may (be) guided (10)",
      transliteration:
        "alladhī jaʿala lakumu l-arḍa mahdan wajaʿala lakum fīhā subulan laʿallakum tahtadūna ",
      verse: 4335,
      juz: 25,
      surah: 43,
    },
    {
      number: 11,
      image: "",
      text: "And the One Who sends down from the sky water in (due) measure then We revive with it a land dead thus you will be brought forth (11)",
      transliteration:
        "wa-alladhī nazzala mina l-samāi māan biqadarin fa-ansharnā bihi baldatan maytan kadhālika tukh'rajūna ",
      verse: 4336,
      juz: 25,
      surah: 43,
    },
    {
      number: 12,
      image: "",
      text: "And the One Who created the pairs all of them and made for you [of] the ships and the cattle what you ride (12)",
      transliteration:
        "wa-alladhī khalaqa l-azwāja kullahā wajaʿala lakum mina l-ful'ki wal-anʿāmi mā tarkabūna ",
      verse: 4337,
      juz: 25,
      surah: 43,
    },
    {
      number: 13,
      image: "",
      text: "That you may sit firmly on their backs then remember (the) favor (of) your Lord when you sit firmly on them and say Glory be (to) the One Who (has) subjected to us this and not we were of it capable (13)",
      transliteration:
        "litastawū ʿalā ẓuhūrihi thumma tadhkurū niʿ'mata rabbikum idhā is'tawaytum ʿalayhi wataqūlū sub'ḥāna alladhī sakhara lanā hādhā wamā kunnā lahu muq'rinīna ",
      verse: 4338,
      juz: 25,
      surah: 43,
    },
    {
      number: 14,
      image: "",
      text: "And indeed, we to our Lord will surely return (14)",
      transliteration: "wa-innā ilā rabbinā lamunqalibūna ",
      verse: 4339,
      juz: 25,
      surah: 43,
    },
    {
      number: 15,
      image: "",
      text: "But they attribute to Him from His slaves a portion Indeed man surely (is) clearly ungrateful surely (is) clearly ungrateful (15)",
      transliteration:
        "wajaʿalū lahu min ʿibādihi juz'an inna l-insāna lakafūrun mubīnun ",
      verse: 4340,
      juz: 25,
      surah: 43,
    },
    {
      number: 16,
      image: "",
      text: "Or has He taken of what He has created daughters and He has chosen (for) you sons (16)",
      transliteration:
        "ami ittakhadha mimmā yakhluqu banātin wa-aṣfākum bil-banīna ",
      verse: 4341,
      juz: 25,
      surah: 43,
    },
    {
      number: 17,
      image: "",
      text: "And when is given good news (to) one of them of what he sets up for the Most Gracious (as) a likeness becomes his face dark and he (is) filled with grief (17)",
      transliteration:
        "wa-idhā bushira aḥaduhum bimā ḍaraba lilrraḥmāni mathalan ẓalla wajhuhu mus'waddan wahuwa kaẓīmun ",
      verse: 4342,
      juz: 25,
      surah: 43,
    },
    {
      number: 18,
      image: "",
      text: "Then (is one) who is brought up in ornaments and he in the dispute (is) not clear (18)",
      transliteration:
        "awaman yunasha-u fī l-ḥil'yati wahuwa fī l-khiṣāmi ghayru mubīnin ",
      verse: 4343,
      juz: 25,
      surah: 43,
    },
    {
      number: 19,
      image: "",
      text: "And they made the Angels those who themselves (are) slaves (of) the Most Gracious females Did they witness their creation Will be recorded their testimony and they will be questioned (19)",
      transliteration:
        "wajaʿalū l-malāikata alladhīna hum ʿibādu l-raḥmāni ināthan ashahidū khalqahum satuk'tabu shahādatuhum wayus'alūna ",
      verse: 4344,
      juz: 25,
      surah: 43,
    },
    {
      number: 20,
      image: "",
      text: "And they say If had willed the Most Gracious we would not have worshipped them we would not have worshipped them Not they have about that any knowledge Nothing they (do) but lie (20)",
      transliteration:
        "waqālū law shāa l-raḥmānu mā ʿabadnāhum mā lahum bidhālika min ʿil'min in hum illā yakhruṣūna ",
      verse: 4345,
      juz: 25,
      surah: 43,
    },
    {
      number: 21,
      image: "",
      text: "Or have We given them a book before it before it so they to it (are) holding fast (21)",
      transliteration:
        "am ātaynāhum kitāban min qablihi fahum bihi mus'tamsikūna ",
      verse: 4346,
      juz: 25,
      surah: 43,
    },
    {
      number: 22,
      image: "",
      text: "Nay they say Indeed, we [we] found our forefathers upon a religion and indeed, we on their footsteps (are) guided (22)",
      transliteration:
        "bal qālū innā wajadnā ābāanā ʿalā ummatin wa-innā ʿalā āthārihim muh'tadūna ",
      verse: 4347,
      juz: 25,
      surah: 43,
    },
    {
      number: 23,
      image: "",
      text: "And thus not We sent before you before you in a town any warner except said (the) wealthy ones of it Indeed, we [we] found our forefathers on a religion and indeed, we [on] their footsteps (are) following (23)",
      transliteration:
        "wakadhālika mā arsalnā min qablika fī qaryatin min nadhīrin illā qāla mut'rafūhā innā wajadnā ābāanā ʿalā ummatin wa-innā ʿalā āthārihim muq'tadūna ",
      verse: 4348,
      juz: 25,
      surah: 43,
    },
    {
      number: 24,
      image: "",
      text: "He said Even if I brought you better guidance than what you found on it your forefathers They said Indeed, we with what you are sent with [it] (are) disbelievers (24)",
      transliteration:
        "qāla awalaw ji'tukum bi-ahdā mimmā wajadttum ʿalayhi ābāakum qālū innā bimā ur'sil'tum bihi kāfirūna ",
      verse: 4349,
      juz: 25,
      surah: 43,
    },
    {
      number: 25,
      image: "",
      text: "So We took retribution from them Then see how was (the) end (of) the deniers (25)",
      transliteration:
        "fa-intaqamnā min'hum fa-unẓur kayfa kāna ʿāqibatu l-mukadhibīna ",
      verse: 4350,
      juz: 25,
      surah: 43,
    },
    {
      number: 26,
      image: "",
      text: "And when Ibrahim Said Ibrahim Said to his father and his people Indeed, I (am) disassociated from what you worship (26)",
      transliteration:
        "wa-idh qāla ib'rāhīmu li-abīhi waqawmihi innanī barāon mimmā taʿbudūna ",
      verse: 4351,
      juz: 25,
      surah: 43,
    },
    {
      number: 27,
      image: "",
      text: "Except the One Who created me and indeed, He will guide me (27)",
      transliteration: "illā alladhī faṭaranī fa-innahu sayahdīni ",
      verse: 4352,
      juz: 25,
      surah: 43,
    },
    {
      number: 28,
      image: "",
      text: "And he made it a word lasting among his descendents so that they may return (28)",
      transliteration:
        "wajaʿalahā kalimatan bāqiyatan fī ʿaqibihi laʿallahum yarjiʿūna ",
      verse: 4353,
      juz: 25,
      surah: 43,
    },
    {
      number: 29,
      image: "",
      text: "Nay I gave enjoyment (to) these and their forefathers until came to them the truth and a Messenger clear (29)",
      transliteration:
        "bal mattaʿtu hāulāi waābāahum ḥattā jāahumu l-ḥaqu warasūlun mubīnun ",
      verse: 4354,
      juz: 25,
      surah: 43,
    },
    {
      number: 30,
      image: "",
      text: "And when came to them the truth they said This (is) magic and indeed, we of it (are) disbelievers (30)",
      transliteration:
        "walammā jāahumu l-ḥaqu qālū hādhā siḥ'run wa-innā bihi kāfirūna ",
      verse: 4355,
      juz: 25,
      surah: 43,
    },
    {
      number: 31,
      image: "",
      text: "And they say Why not was sent down this the Quran to a man from the two towns great (31)",
      transliteration:
        "waqālū lawlā nuzzila hādhā l-qur'ānu ʿalā rajulin mina l-qaryatayni ʿaẓīmin ",
      verse: 4356,
      juz: 25,
      surah: 43,
    },
    {
      number: 32,
      image: "",
      text: "Do they distribute (the) Mercy (of) your Lord We [We] distribute among them their livelihood in the life (of) the world and We raise some of them above others (in) degrees so that may take some of them others (for) service But (the) Mercy (of) your Lord (is) better than what they accumulate (32)",
      transliteration:
        "ahum yaqsimūna raḥmata rabbika naḥnu qasamnā baynahum maʿīshatahum fī l-ḥayati l-dun'yā warafaʿnā baʿḍahum fawqa baʿḍin darajātin liyattakhidha baʿḍuhum baʿḍan sukh'riyyan waraḥmatu rabbika khayrun mimmā yajmaʿūna ",
      verse: 4357,
      juz: 25,
      surah: 43,
    },
    {
      number: 33,
      image: "",
      text: "And if not that (would) become [the] mankind a community one We (would have) made for (one) who disbelieves in the Most Gracious for their houses roofs of silver and stairways upon which they mount (33)",
      transliteration:
        "walawlā an yakūna l-nāsu ummatan wāḥidatan lajaʿalnā liman yakfuru bil-raḥmāni libuyūtihim suqufan min fiḍḍatin wamaʿārija ʿalayhā yaẓharūna ",
      verse: 4358,
      juz: 25,
      surah: 43,
    },
    {
      number: 34,
      image: "",
      text: "And for their houses doors and couches upon which they recline (34)",
      transliteration: "walibuyūtihim abwāban wasururan ʿalayhā yattakiūna ",
      verse: 4359,
      juz: 25,
      surah: 43,
    },
    {
      number: 35,
      image: "",
      text: "And ornaments of gold And not (is) all that but an enjoyment (of) the life (of) the world And the Hereafter with your Lord (is) for the righteous (35)",
      transliteration:
        "wazukh'rufan wa-in kullu dhālika lammā matāʿu l-ḥayati l-dun'yā wal-ākhiratu ʿinda rabbika lil'muttaqīna ",
      verse: 4360,
      juz: 25,
      surah: 43,
    },
    {
      number: 36,
      image: "",
      text: "And whoever turns away from (the) remembrance (of) the Most Gracious We appoint for him a devil then he (is) to him a companion (36)",
      transliteration:
        "waman yaʿshu ʿan dhik'ri l-raḥmāni nuqayyiḍ lahu shayṭānan fahuwa lahu qarīnun ",
      verse: 4361,
      juz: 25,
      surah: 43,
    },
    {
      number: 37,
      image: "",
      text: "And indeed, they surely, turn them from the Path and they think that they (are) guided (37)",
      transliteration:
        "wa-innahum layaṣuddūnahum ʿani l-sabīli wayaḥsabūna annahum muh'tadūna ",
      verse: 4362,
      juz: 25,
      surah: 43,
    },
    {
      number: 38,
      image: "",
      text: "Until when he comes to Us he says O would that between me and between you (were the) distance (of) the East and the West How wretched is the companion (38)",
      transliteration:
        "ḥattā idhā jāanā qāla yālayta baynī wabaynaka buʿ'da l-mashriqayni fabi'sa l-qarīnu ",
      verse: 4363,
      juz: 25,
      surah: 43,
    },
    {
      number: 39,
      image: "",
      text: "And never will benefit you the Day when you have wronged that you (will be) in the punishment sharing (39)",
      transliteration:
        "walan yanfaʿakumu l-yawma idh ẓalamtum annakum fī l-ʿadhābi mush'tarikūna ",
      verse: 4364,
      juz: 25,
      surah: 43,
    },
    {
      number: 40,
      image: "",
      text: "Then can you cause to hear the deaf or guide the blind and (one) who is in an error clear (40)",
      transliteration:
        "afa-anta tus'miʿu l-ṣuma aw tahdī l-ʿum'ya waman kāna fī ḍalālin mubīnin ",
      verse: 4365,
      juz: 25,
      surah: 43,
    },
    {
      number: 41,
      image: "",
      text: "And whether We take you away We take you away then indeed, We from them (will) take retribution (41)",
      transliteration: "fa-immā nadhhabanna bika fa-innā min'hum muntaqimūna ",
      verse: 4366,
      juz: 25,
      surah: 43,
    },
    {
      number: 42,
      image: "",
      text: "Or We show you that which We have promised them then indeed, We over them have full power (42)",
      transliteration:
        "aw nuriyannaka alladhī waʿadnāhum fa-innā ʿalayhim muq'tadirūna ",
      verse: 4367,
      juz: 25,
      surah: 43,
    },
    {
      number: 43,
      image: "",
      text: "So hold fast to that which is revealed to you Indeed, you (are) on a Path Straight (43)",
      transliteration:
        "fa-is'tamsik bi-alladhī ūḥiya ilayka innaka ʿalā ṣirāṭin mus'taqīmin ",
      verse: 4368,
      juz: 25,
      surah: 43,
    },
    {
      number: 44,
      image: "",
      text: "And indeed, it (is) surely, a Reminder for you and your people and soon you will be questioned (44)",
      transliteration: "wa-innahu ladhik'run laka waliqawmika wasawfa tus'alūna ",
      verse: 4369,
      juz: 25,
      surah: 43,
    },
    {
      number: 45,
      image: "",
      text: "And ask (those) whom We sent before you before you of Our Messengers did We make besides besides the Most Gracious gods to be worshipped (45)",
      transliteration:
        "wasal man arsalnā min qablika min rusulinā ajaʿalnā min dūni l-raḥmāni ālihatan yuʿ'badūna ",
      verse: 4370,
      juz: 25,
      surah: 43,
    },
    {
      number: 46,
      image: "",
      text: "And certainly We sent Musa with Our Signs to Firaun and his chiefs and he said Indeed, I am a Messenger (of the) Lord (of) the worlds (46)",
      transliteration:
        "walaqad arsalnā mūsā biāyātinā ilā fir'ʿawna wamala-ihi faqāla innī rasūlu rabbi l-ʿālamīna ",
      verse: 4371,
      juz: 25,
      surah: 43,
    },
    {
      number: 47,
      image: "",
      text: "But when he came to them with Our Signs behold They at them laughed (47)",
      transliteration: "falammā jāahum biāyātinā idhā hum min'hā yaḍḥakūna ",
      verse: 4372,
      juz: 25,
      surah: 43,
    },
    {
      number: 48,
      image: "",
      text: "And not We showed them of a Sign but it (was) greater than its sister and We seized them with the punishment so that they may return (48)",
      transliteration:
        "wamā nurīhim min āyatin illā hiya akbaru min ukh'tihā wa-akhadhnāhum bil-ʿadhābi laʿallahum yarjiʿūna ",
      verse: 4373,
      juz: 25,
      surah: 43,
    },
    {
      number: 49,
      image: "",
      text: "And they said O [the] magician Invoke for us your Lord by what He has made covenant with you Indeed, we (will) surely be guided (49)",
      transliteration:
        "waqālū yāayyuha l-sāḥiru ud'ʿu lanā rabbaka bimā ʿahida ʿindaka innanā lamuh'tadūna ",
      verse: 4374,
      juz: 25,
      surah: 43,
    },
    {
      number: 50,
      image: "",
      text: "But when We removed from them the punishment behold They broke (their word) (50)",
      transliteration: "falammā kashafnā ʿanhumu l-ʿadhāba idhā hum yankuthūna ",
      verse: 4375,
      juz: 25,
      surah: 43,
    },
    {
      number: 51,
      image: "",
      text: "And called out Firaun among his people he said O my people Is not for me (the) kingdom (of) Egypt and these [the] rivers flowing underneath me underneath me Then do not you see (51)",
      transliteration:
        "wanādā fir'ʿawnu fī qawmihi qāla yāqawmi alaysa lī mul'ku miṣ'ra wahādhihi l-anhāru tajrī min taḥtī afalā tub'ṣirūna ",
      verse: 4376,
      juz: 25,
      surah: 43,
    },
    {
      number: 52,
      image: "",
      text: "Or am I better than this one who  he (is) insignificant and hardly and hardly clear (52)",
      transliteration:
        "am anā khayrun min hādhā alladhī huwa mahīnun walā yakādu yubīnu ",
      verse: 4377,
      juz: 25,
      surah: 43,
    },
    {
      number: 53,
      image: "",
      text: "Then why not are placed on him bracelets of gold or come with him the Angels accompanying (him) (53)",
      transliteration:
        "falawlā ul'qiya ʿalayhi aswiratun min dhahabin aw jāa maʿahu l-malāikatu muq'tarinīna ",
      verse: 4378,
      juz: 25,
      surah: 43,
    },
    {
      number: 54,
      image: "",
      text: "So he bluffed his people and they obeyed him Indeed, they were a people defiantly disobedient (54)",
      transliteration:
        "fa-is'takhaffa qawmahu fa-aṭāʿūhu innahum kānū qawman fāsiqīna ",
      verse: 4379,
      juz: 25,
      surah: 43,
    },
    {
      number: 55,
      image: "",
      text: "So when they angered Us We took retribution from them and We drowned them all (55)",
      transliteration:
        "falammā āsafūnā intaqamnā min'hum fa-aghraqnāhum ajmaʿīna ",
      verse: 4380,
      juz: 25,
      surah: 43,
    },
    {
      number: 56,
      image: "",
      text: "And We made them a precedent and an example for the later (generations) (56)",
      transliteration: "fajaʿalnāhum salafan wamathalan lil'ākhirīna ",
      verse: 4381,
      juz: 25,
      surah: 43,
    },
    {
      number: 57,
      image: "",
      text: "And when is presented (the) son (of) Maryam (as) an example behold Your people about it laughed aloud (57)",
      transliteration:
        "walammā ḍuriba ub'nu maryama mathalan idhā qawmuka min'hu yaṣiddūna ",
      verse: 4382,
      juz: 25,
      surah: 43,
    },
    {
      number: 58,
      image: "",
      text: "And they said Are our gods better or he Not they present it to you except (for) argument Nay they (are) a people argumentative (58)",
      transliteration:
        "waqālū aālihatunā khayrun am huwa mā ḍarabūhu laka illā jadalan bal hum qawmun khaṣimūna ",
      verse: 4383,
      juz: 25,
      surah: 43,
    },
    {
      number: 59,
      image: "",
      text: "Not he (was) except a slave We bestowed Our favor on him and We made him an example for (the) Children of Israel for (the) Children of Israel (59)",
      transliteration:
        "in huwa illā ʿabdun anʿamnā ʿalayhi wajaʿalnāhu mathalan libanī is'rāīla ",
      verse: 4384,
      juz: 25,
      surah: 43,
    },
    {
      number: 60,
      image: "",
      text: "And if We willed surely We (could have) made among you Angels in the earth succeeding (60)",
      transliteration:
        "walaw nashāu lajaʿalnā minkum malāikatan fī l-arḍi yakhlufūna ",
      verse: 4385,
      juz: 25,
      surah: 43,
    },
    {
      number: 61,
      image: "",
      text: "And indeed, it surely (is) a knowledge of the Hour So (do) not (be) doubtful about it and follow Me This (is the) Path Straight (61)",
      transliteration:
        "wa-innahu laʿil'mun lilssāʿati falā tamtarunna bihā wa-ittabiʿūni hādhā ṣirāṭun mus'taqīmun ",
      verse: 4386,
      juz: 25,
      surah: 43,
    },
    {
      number: 62,
      image: "",
      text: "And (let) not avert you the Shaitaan Indeed, he (is) for you an enemy clear (62)",
      transliteration:
        "walā yaṣuddannakumu l-shayṭānu innahu lakum ʿaduwwun mubīnun ",
      verse: 4387,
      juz: 25,
      surah: 43,
    },
    {
      number: 63,
      image: "",
      text: "And when came Isa with clear proofs he said Verily I have come to you with wisdom and that I make clear to you some (of) that which you differ in it So fear Allah and obey me (63)",
      transliteration:
        "walammā jāa ʿīsā bil-bayināti qāla qad ji'tukum bil-ḥik'mati wali-ubayyina lakum baʿḍa alladhī takhtalifūna fīhi fa-ittaqū l-laha wa-aṭīʿūni ",
      verse: 4388,
      juz: 25,
      surah: 43,
    },
    {
      number: 64,
      image: "",
      text: "Indeed Allah He (is) my Lord and your Lord so worship Him This (is) a Path Straight (64)",
      transliteration:
        "inna l-laha huwa rabbī warabbukum fa-uʿ'budūhu hādhā ṣirāṭun mus'taqīmun ",
      verse: 4389,
      juz: 25,
      surah: 43,
    },
    {
      number: 65,
      image: "",
      text: "But differed the factions from among them so woe to those who wronged from (the) punishment (of the) Day painful (65)",
      transliteration:
        "fa-ikh'talafa l-aḥzābu min baynihim fawaylun lilladhīna ẓalamū min ʿadhābi yawmin alīmin ",
      verse: 4390,
      juz: 25,
      surah: 43,
    },
    {
      number: 66,
      image: "",
      text: "Are they waiting except (for) the Hour that it should come on them suddenly while they (do) not perceive (66)",
      transliteration:
        "hal yanẓurūna illā l-sāʿata an tatiyahum baghtatan wahum lā yashʿurūna ",
      verse: 4391,
      juz: 25,
      surah: 43,
    },
    {
      number: 67,
      image: "",
      text: "Friends that Day some of them to others (will be) enemies except the righteous (67)",
      transliteration:
        "al-akhilāu yawma-idhin baʿḍuhum libaʿḍin ʿaduwwun illā l-mutaqīna ",
      verse: 4392,
      juz: 25,
      surah: 43,
    },
    {
      number: 68,
      image: "",
      text: "O My slaves No fear on you this Day and not you will grieve (68)",
      transliteration:
        "yāʿibādi lā khawfun ʿalaykumu l-yawma walā antum taḥzanūna ",
      verse: 4393,
      juz: 25,
      surah: 43,
    },
    {
      number: 69,
      image: "",
      text: "Those who believed in Our Verses and were submissive (69)",
      transliteration: "alladhīna āmanū biāyātinā wakānū mus'limīna ",
      verse: 4394,
      juz: 25,
      surah: 43,
    },
    {
      number: 70,
      image: "",
      text: "Enter Paradise you and your spouses delighted (70)",
      transliteration: "ud'khulū l-janata antum wa-azwājukum tuḥ'barūna ",
      verse: 4395,
      juz: 25,
      surah: 43,
    },
    {
      number: 71,
      image: "",
      text: "Will be circulated for them plates of gold and cups And therein (is) what desires the souls and delights the eyes and you therein will abide forever (71)",
      transliteration:
        "yuṭāfu ʿalayhim biṣiḥāfin min dhahabin wa-akwābin wafīhā mā tashtahīhi l-anfusu wataladhu l-aʿyunu wa-antum fīhā khālidūna ",
      verse: 4396,
      juz: 25,
      surah: 43,
    },
    {
      number: 72,
      image: "",
      text: "And this (is) the Paradise which you are made to inherit for what you used to do (72)",
      transliteration:
        "watil'ka l-janatu allatī ūrith'tumūhā bimā kuntum taʿmalūna ",
      verse: 4397,
      juz: 25,
      surah: 43,
    },
    {
      number: 73,
      image: "",
      text: "For you therein (are) fruits abundant from it you will eat (73)",
      transliteration: "lakum fīhā fākihatun kathīratun min'hā takulūna ",
      verse: 4398,
      juz: 25,
      surah: 43,
    },
    {
      number: 74,
      image: "",
      text: "Indeed the criminals (will be) in (the) punishment (of) Hell abiding forever (74)",
      transliteration: "inna l-muj'rimīna fī ʿadhābi jahannama khālidūna ",
      verse: 4399,
      juz: 25,
      surah: 43,
    },
    {
      number: 75,
      image: "",
      text: "Not will it subside for them and they in it (will) despair (75)",
      transliteration: "lā yufattaru ʿanhum wahum fīhi mub'lisūna ",
      verse: 4400,
      juz: 25,
      surah: 43,
    },
    {
      number: 76,
      image: "",
      text: "And not We wronged them but they were themselves wrongdoers (76)",
      transliteration: "wamā ẓalamnāhum walākin kānū humu l-ẓālimīna ",
      verse: 4401,
      juz: 25,
      surah: 43,
    },
    {
      number: 77,
      image: "",
      text: "And they will call O Malik Let put an end to us your Lord He (will) say Indeed, you (will) remain (77)",
      transliteration:
        "wanādaw yāmāliku liyaqḍi ʿalaynā rabbuka qāla innakum mākithūna ",
      verse: 4402,
      juz: 25,
      surah: 43,
    },
    {
      number: 78,
      image: "",
      text: "Certainly We have brought you the truth but most of you to the truth (are) averse (78)",
      transliteration:
        "laqad ji'nākum bil-ḥaqi walākinna aktharakum lil'ḥaqqi kārihūna ",
      verse: 4403,
      juz: 25,
      surah: 43,
    },
    {
      number: 79,
      image: "",
      text: "Or have they determined an affair Then indeed, We (are) determined (79)",
      transliteration: "am abramū amran fa-innā mub'rimūna ",
      verse: 4404,
      juz: 25,
      surah: 43,
    },
    {
      number: 80,
      image: "",
      text: "Or (do) they think that We (can) not hear their secret(s) and their private counsel(s) Nay and Our Messengers with them are recording (80)",
      transliteration:
        "am yaḥsabūna annā lā nasmaʿu sirrahum wanajwāhum balā warusulunā ladayhim yaktubūna ",
      verse: 4405,
      juz: 25,
      surah: 43,
    },
    {
      number: 81,
      image: "",
      text: "Say If had the Most Gracious a son Then, I (would be the) first (of) the worshippers (81)",
      transliteration:
        "qul in kāna lilrraḥmāni waladun fa-anā awwalu l-ʿābidīna ",
      verse: 4406,
      juz: 25,
      surah: 43,
    },
    {
      number: 82,
      image: "",
      text: "Glory be (to the) Lord (of) the heavens and the earth (the) Lord (of) the Throne above what they ascribe (82)",
      transliteration:
        "sub'ḥāna rabbi l-samāwāti wal-arḍi rabbi l-ʿarshi ʿammā yaṣifūna ",
      verse: 4407,
      juz: 25,
      surah: 43,
    },
    {
      number: 83,
      image: "",
      text: "So leave them (to) converse vainly and play until they meet their Day which they are promised (83)",
      transliteration:
        "fadharhum yakhūḍū wayalʿabū ḥattā yulāqū yawmahumu alladhī yūʿadūna ",
      verse: 4408,
      juz: 25,
      surah: 43,
    },
    {
      number: 84,
      image: "",
      text: "And He (is) the One Who (is) in the heaven  God and in the earth  God And He (is) the All-Wise the All-Knower (84)",
      transliteration:
        "wahuwa alladhī fī l-samāi ilāhun wafī l-arḍi ilāhun wahuwa l-ḥakīmu l-ʿalīmu ",
      verse: 4409,
      juz: 25,
      surah: 43,
    },
    {
      number: 85,
      image: "",
      text: "And blessed (is) the One Who  to Whom (belongs the) dominion (of) the heavens and the earth and whatever (is) between both of them and with Him (is the) knowledge (of) the Hour and to Him you will be returned (85)",
      transliteration:
        "watabāraka alladhī lahu mul'ku l-samāwāti wal-arḍi wamā baynahumā waʿindahu ʿil'mu l-sāʿati wa-ilayhi tur'jaʿūna ",
      verse: 4410,
      juz: 25,
      surah: 43,
    },
    {
      number: 86,
      image: "",
      text: "And not have power those whom they invoke besides Him besides Him (for) the intercession except who testifies to the truth and they know (86)",
      transliteration:
        "walā yamliku alladhīna yadʿūna min dūnihi l-shafāʿata illā man shahida bil-ḥaqi wahum yaʿlamūna ",
      verse: 4411,
      juz: 25,
      surah: 43,
    },
    {
      number: 87,
      image: "",
      text: "And if you ask them who created them they will certainly say Allah Then how are they deluded (87)",
      transliteration:
        "wala-in sa-altahum man khalaqahum layaqūlunna l-lahu fa-annā yu'fakūna ",
      verse: 4412,
      juz: 25,
      surah: 43,
    },
    {
      number: 88,
      image: "",
      text: "And his saying O my Lord Indeed these (are) a people (who do) not believe (88)",
      transliteration: "waqīlihi yārabbi inna hāulāi qawmun lā yu'minūna ",
      verse: 4413,
      juz: 25,
      surah: 43,
    },
    {
      number: 89,
      image: "",
      text: "So turn away from them and say Peace But soon they will know (89)",
      transliteration: "fa-iṣ'faḥ ʿanhum waqul salāmun fasawfa yaʿlamūna ",
      verse: 4414,
      juz: 25,
      surah: 43,
    },
  ],
};
